{
 "title": "PHP-FPM",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(up{job=\"php-fpm\"}, namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(up{job=\"php-fpm\",namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(up{job=\"php-fpm\",namespace=\"$namespace\", service=\"$service\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pod" },
  {
   "title": "Requests accepted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(phpfpm_accepted_connections_total{job=\"php-fpm\", namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Workers utilization",
   "type": "graph",
   "description": "Percent of active processes",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "phpfpm_processes_total{job=\"php-fpm\", namespace=\"$namespace\", service=\"$service\", pod=\"$pod\", state=\"active\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "phpfpm_processes_total{job=\"php-fpm\", namespace=\"$namespace\", service=\"$service\", pod=\"$pod\", state=\"idle\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Queue",
   "type": "graph",
   "description": "Number of connections that have been initiated but not yet accepted",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "phpfpm_listen_queue_max_connections{job=\"php-fpm\", namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "Max queued since fpm start"
    },
    {
     "expr": "phpfpm_listen_queue_connections{job=\"php-fpm\", namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "phpfpm_listen_queue_length_connections{job=\"php-fpm\", namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "Max queue length"
    }
   ]
  },
  {
   "title": "Slow requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(phpfpm_slow_requests_total{job=\"php-fpm\", namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}[1m])/ rate(phpfpm_accepted_connections_total{job=\"php-fpm\", namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}[1m])",
     "legendFormat": "Slow requests"
    }
   ]
  },
  {
   "title": "Requests accepted",
   "type": "graph",
   "description": "The number of request accepted by the pool",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(phpfpm_accepted_connections_total{job=\"php-fpm\", namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}[$__interval_sx4])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Avg Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(sum(phpfpm_processes_total{job=\"php-fpm\", namespace=\"$namespace\", service=\"$service\", pod=\"$pod\", state=\"active\"}) without(state) / sum(phpfpm_processes_total{job=\"php-fpm\", namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}) without(state)) * 100"
    }
   ]
  }
 ]
}