{
 "title": "DNS (node local)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(coredns_build_info{d8_source=\"dkp\"}, node)"
   },
   {
    "name": "rcode",
    "query": "label_values(coredns_dns_responses_total{d8_source=\"dkp\", rcode!=\"NOERROR\"}, rcode)"
   },
   {
    "name": "upstream",
    "query": {
     "query": "label_values(coredns_proxy_request_duration_seconds_sum{d8_source=\"dkp\", proxy_name=\"forward\"},to)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CoreDNS panic count",
   "type": "timeseries",
   "description": "The presence of data in this graph means that some CoreDNS requests resulted in panic; you can see a specific error in the container logs",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_panics_total{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(coredns_panics_total{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Incoming requests count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "sum(rate(coredns_dns_requests_total{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Incoming requests duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_duration_seconds_sum{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval])) by (node) / sum(rate(coredns_dns_requests_total{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_duration_seconds_bucket{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Forwarded requests count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_proxy_request_duration_seconds_count{d8_source=\"dkp\", proxy_name=\"forward\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "sum(rate(coredns_proxy_request_duration_seconds_count{d8_source=\"dkp\", proxy_name=\"forward\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Forwarded requests duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_proxy_request_duration_seconds_sum{d8_source=\"dkp\", proxy_name=\"forward\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval])) by (node) / sum(rate(coredns_proxy_request_duration_seconds_count{d8_source=\"dkp\", proxy_name=\"forward\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Forward duration",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(coredns_proxy_request_duration_seconds_bucket{d8_source=\"dkp\", proxy_name=\"forward\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CoreDNS Forward Healthcheck Failure Count",
   "type": "timeseries",
   "description": "The presence of data in this graph means that some CoreDNS requests resulted in panic; you can see a specific error in the container logs",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_proxy_healthcheck_failures_total{d8_source=\"dkp\", proxy_name=\"forward\", job=\"node-local-dns\", node=~\"$node\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(coredns_proxy_healthcheck_failures_total{d8_source=\"dkp\", proxy_name=\"forward\", job=\"node-local-dns\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cache hit rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval])) by (node)\n/\n(\nsum(rate(coredns_cache_hits_total{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval])) by (node) +\nsum(rate(coredns_cache_misses_total{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval])) by (node) \n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Cache size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(max_over_time(coredns_cache_entries{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$rcode",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 38 },
   "repeat": "rcode",
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{d8_source=\"dkp\", node=~\"$node\", rcode=~\"$rcode\", job=\"node-local-dns\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "sum(rate(coredns_dns_responses_total{d8_source=\"dkp\", node=~\"$node\", rcode=~\"$rcode\", job=\"node-local-dns\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "TCP/UDP requests ratio",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{d8_source=\"dkp\", node=~\"$node\",proto=\"tcp\", job=\"node-local-dns\"}[$__rate_interval]))\n/\nsum(rate(coredns_dns_requests_total{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval]))",
     "legendFormat": "TCP"
    },
    {
     "expr": "sum(rate(coredns_dns_requests_total{d8_source=\"dkp\", node=~\"$node\",proto=\"udp\", job=\"node-local-dns\"}[$__rate_interval]))\n/\nsum(rate(coredns_dns_requests_total{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval]))",
     "legendFormat": "UDP"
    }
   ]
  },
  {
   "title": "Slow kube-dns instances (top 5)",
   "type": "table",
   "description": "Top 5 upstreams by slow kubeforward requests (rate over $__rate_interval).",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "topk(5, sum(rate(coredns_kubeforward_slow_requests_total{d8_source=\"dkp\", job=\"node-local-dns\", node=~\"$node\"}[$__rate_interval])) by (upstream))"
    }
   ]
  },
  {
   "title": "Node $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "repeat": "node",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requests (by qtype)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_requests_total{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Responses (by rcode)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_responses_total{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[5m])) by (rcode)",
       "legendFormat": "{{rcode}}"
      }
     ]
    },
    {
     "title": "Forwarded requests count (by upstream)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_proxy_request_duration_seconds_count{d8_source=\"dkp\", proxy_name=\"forward\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval])) by (to)",
       "legendFormat": "{{to}}"
      },
      {
       "expr": "sum(rate(coredns_proxy_request_duration_seconds_count{d8_source=\"dkp\", proxy_name=\"forward\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Forwarded requests count (by rcode)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_proxy_request_duration_seconds_count{d8_source=\"dkp\", proxy_name=\"forward\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval])) by (rcode)",
       "legendFormat": "{{rcode}}"
      },
      {
       "expr": "sum(rate(coredns_proxy_request_duration_seconds_count{d8_source=\"dkp\", proxy_name=\"forward\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "CoreDNS Forward Healthcheck Failure Count",
     "type": "timeseries",
     "description": "The presence of data in this graph means that some CoreDNS requests resulted in panic; you can see a specific error in the container logs",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_proxy_healthcheck_failures_total{d8_source=\"dkp\", proxy_name=\"forward\", proxy_name=\"forward\", job=\"node-local-dns\", node=~\"$node\"}[$__rate_interval])) by (upstream)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(rate(coredns_proxy_healthcheck_failures_total{d8_source=\"dkp\", proxy_name=\"forward\", job=\"node-local-dns\", node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "TCP/UDP requests ratio",
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_requests_total{d8_source=\"dkp\", node=~\"$node\",proto=\"tcp\", job=\"node-local-dns\"}[$__rate_interval]))\n/\nsum(rate(coredns_dns_requests_total{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval]))",
       "legendFormat": "TCP"
      },
      {
       "expr": "sum(rate(coredns_dns_requests_total{d8_source=\"dkp\", node=~\"$node\",proto=\"udp\", job=\"node-local-dns\"}[$__rate_interval]))\n/\nsum(rate(coredns_dns_requests_total{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval]))",
       "legendFormat": "UDP"
      }
     ]
    },
    {
     "title": "Cache hit rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_cache_hits_total{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval]))\n/\n(\nsum(rate(coredns_cache_hits_total{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval])) +\nsum(rate(coredns_cache_misses_total{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval]))\n)",
       "legendFormat": "Hit"
      }
     ]
    },
    {
     "title": "Cache size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(max_over_time(coredns_cache_entries{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(max_over_time(coredns_cache_entries{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Requests (by zone)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_requests_total{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval])) by (zone)",
       "legendFormat": "{{zone}}"
      },
      {
       "expr": "sum(rate(coredns_dns_requests_total{d8_source=\"dkp\", node=~\"node\", job=\"node-local-dns\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Request duration",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_request_duration_seconds_bucket{d8_source=\"dkp\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Forward duration",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "sum(rate(coredns_proxy_request_duration_seconds_bucket{d8_source=\"dkp\", proxy_name=\"forward\", node=~\"$node\", job=\"node-local-dns\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstream $upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "repeat": "upstream",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Forwarded requests count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_proxy_request_duration_seconds_count{d8_source=\"dkp\", proxy_name=\"forward\", node=~\"$node\", to=~\"$upstream\"}[$__rate_interval]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(coredns_proxy_request_duration_seconds_count{d8_source=\"dkp\", proxy_name=\"forward\", node=~\"$node\", to=~\"$upstream\"}[$__rate_interval])) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Forwarded requests count (by rcode)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_proxy_request_duration_seconds_count{d8_source=\"dkp\", proxy_name=\"forward\", node=~\"$node\", to=~\"$upstream\"}[$__rate_interval])) by (rcode)",
       "legendFormat": "{{rcode}}"
      },
      {
       "expr": "sum(rate(coredns_proxy_request_duration_seconds_count{d8_source=\"dkp\", proxy_name=\"forward\", node=~\"$node\", to=~\"$upstream\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Forward duration",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 103 },
     "targets": [
      {
       "expr": "sum(rate(coredns_proxy_request_duration_seconds_bucket{d8_source=\"dkp\", proxy_name=\"forward\", node=~\"$node\", to=~\"$upstream\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "CoreDNS Forward Healthcheck Failure Count",
     "type": "timeseries",
     "description": "The presence of data in this graph means that some CoreDNS requests resulted in panic; you can see a specific error in the container logs",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_proxy_healthcheck_failures_total{d8_source=\"dkp\", proxy_name=\"forward\", job=\"node-local-dns\", node=~\"$node\", to=~\"$upstream\"}[$__rate_interval])) by (node)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(rate(coredns_proxy_healthcheck_failures_total{d8_source=\"dkp\", proxy_name=\"forward\", proxy_name=\"forward\", job=\"node-local-dns\", node=~\"$node\", to=~\"$upstream\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  }
 ]
}