{
 "title": "Aggregating proxy cache",
 "description": "Monitors Kubernetes Memcached Pods. Shows memory usage, hit rate, evicts and reclaims rate, items in cache, network stats, commands rate. Requires Memcached Exporter for Prometheus.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (memcached_current_bytes{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\"}) / sum by (pod) (memcached_limit_bytes{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Hit rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate (memcached_commands_total{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\",status=\"hit\",command=\"get\"}[$__rate_interval])) / sum by (pod) (rate (memcached_commands_total{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\", command=\"get\"}[$__rate_interval]\n))",
     "legendFormat": "hit: {{pod}}"
    }
   ]
  },
  {
   "title": "Evicts & Reclaims rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(memcached_items_evicted_total{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\"}[$__rate_interval]))",
     "legendFormat": "evicts: {{pod}}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (memcached_current_bytes{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (memcached_limit_bytes{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Hit & Miss ratio",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate (memcached_commands_total{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\", status=\"hit\", command=\"get\"}[$__rate_interval])) / sum by (pod) (rate (memcached_commands_total{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\", command=\"get\"}[$__rate_interval]))",
     "legendFormat": "hit"
    },
    {
     "expr": "sum by (pod) (rate (memcached_commands_total{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\", status=\"miss\", command=\"get\"}[$__rate_interval])) / sum by (pod) (rate (memcached_commands_total{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\", command=\"get\"}[$__rate_interval]))",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Evicts (total)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (memcached_items_evicted_total{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Reclaims (total)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (memcached_items_reclaimed_total{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Items in cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (memcached_current_items{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate (memcached_read_bytes_total{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\"}[$__rate_interval])) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network written",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate (memcached_written_bytes_total{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\"}[$__rate_interval])) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (memcached_current_connections{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Get & Set ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod) (memcached_commands_total{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\",command=\"get\"}) / (sum by (pod) (memcached_commands_total{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\",command=\"get\"}) + sum by (pod) (memcached_commands_total{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\", command=\"set\"}))",
     "legendFormat": "Get"
    },
    {
     "expr": "sum by (pod) (memcached_commands_total{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\",command=\"set\"})  / (sum by (pod) (memcached_commands_total{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\",command=\"get\"}) + sum by (pod) (memcached_commands_total{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\",command=\"set\"}))",
     "legendFormat": "Set"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (command) (rate (memcached_commands_total{source=\"deckhouse\", job=\"memcached\",namespace=\"d8-monitoring\"}[$__rate_interval]))",
     "legendFormat": "{{command}}"
    }
   ]
  }
 ]
}