{
 "title": "Prometheus Benchmark",
 "description": "Metrics useful for benchmarking and loadtesting Prometheus itself.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(up{job=\"prometheus\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pod, version) (prometheus_build_info{source=\"deckhouse\", job=\"prometheus\", pod=\"$pod\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Prometheus Revision",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pod, revision) (prometheus_build_info{source=\"deckhouse\", job=\"prometheus\", pod=\"$pod\"})",
     "legendFormat": "{{revision}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pod) (time() - process_start_time_seconds{job=\"prometheus\",pod=\"$pod\"})",
     "legendFormat": "Age"
    }
   ]
  },
  {
   "title": "Last Successful Config Reload",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pod) (time() - prometheus_config_last_reload_success_timestamp_seconds{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"})",
     "legendFormat": "Age"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (pod) (process_resident_memory_bytes{job=\"prometheus\",pod=\"$pod\"})",
     "legendFormat": "RSS"
    },
    {
     "expr": "max by (pod) (go_memstats_next_gc_bytes{job=\"prometheus\",pod=\"$pod\"})",
     "legendFormat": "Next GC"
    },
    {
     "expr": "max by (pod) (go_memstats_alloc_bytes{job=\"prometheus\",pod=\"$pod\"})",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (pod) (rate(go_memstats_alloc_bytes_total{job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Allocated Bytes/s"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (pod) (irate(process_cpu_seconds_total{job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Symbol Tables Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (pod) (prometheus_tsdb_symbol_table_size_bytes{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"})",
     "legendFormat": "RAM Used"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (pod) (prometheus_tsdb_storage_blocks_bytes_total{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"} or prometheus_tsdb_storage_blocks_bytes{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"})",
     "legendFormat": "Disk Used"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (pod) (process_max_fds{job=\"prometheus\",pod=\"$pod\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "max by (pod) (process_open_fds{job=\"prometheus\",pod=\"$pod\"})",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "Ingestion",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Head Time series",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (pod) (prometheus_tsdb_head_series{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"})",
       "legendFormat": "Time series"
      }
     ]
    },
    {
     "title": "Head Active Appenders",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (pod) (prometheus_tsdb_head_active_appenders{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"})",
       "legendFormat": "Head Appenders"
      }
     ]
    },
    {
     "title": "Samples Appended/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (pod) (rate(prometheus_tsdb_head_samples_appended_total{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "samples/s"
      }
     ]
    },
    {
     "title": "Head Chunks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (pod) (prometheus_tsdb_head_chunks{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"})",
       "legendFormat": "Chunks"
      }
     ]
    },
    {
     "title": "Head Chunks/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "max by (pod) (rate(prometheus_tsdb_head_chunks_created_total{source=\"deckhouse\", job=\"prometheus\",instance=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Created"
      },
      {
       "expr": "max by (pod) (rate(prometheus_tsdb_head_chunks_removed_total{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Removed"
      }
     ]
    },
    {
     "title": "Isolation Watermarks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (pod) (prometheus_tsdb_isolation_high_watermark{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"} - prometheus_tsdb_isolation_low_watermark{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"})",
       "legendFormat": "Difference"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Discovery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Discovered Targets Number",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (name, config) (prometheus_sd_discovered_targets{source=\"deckhouse\", job=\"prometheus\", pod=\"$pod\"})",
       "legendFormat": "{{name}}-{{config}}"
      }
     ]
    },
    {
     "title": "Sent Updates/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (pod) (rate(prometheus_sd_updates_total{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Received Updates/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (pod) (rate(prometheus_sd_received_updates_total{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Scraping",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scrape Interval",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (pod, interval) (rate(prometheus_target_interval_length_seconds_sum{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]) / rate(prometheus_target_interval_length_seconds_count{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{interval}}"
      }
     ]
    },
    {
     "title": "Scrape Problems/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 10, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (pod) (rate(prometheus_target_scrapes_exceeded_sample_limit_total{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Exceeded Sample Limit"
      },
      {
       "expr": "max by (pod) (rate(prometheus_target_scrapes_sample_duplicate_timestamp_total{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Duplicate Timestamp"
      },
      {
       "expr": "max by (pod) (rate(prometheus_target_scrapes_sample_out_of_bounds_total{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Out Of Bounds "
      },
      {
       "expr": "max by (pod) (rate(prometheus_target_scrapes_sample_out_of_order_total{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Out of Order"
      }
     ]
    },
    {
     "title": "Metadata Cache Size Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(max by (pod, scrape_job) (prometheus_target_metadata_cache_bytes{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Metadata Cache Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (pod, scrape_job) (prometheus_target_metadata_cache_bytes{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"})",
       "legendFormat": "{{scrape_job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Head Time Range",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "targets": [
      {
       "expr": "max by (pod) (prometheus_tsdb_head_min_time{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"})",
       "legendFormat": "Min"
      },
      { "expr": "time() * 1000", "legendFormat": "Now" },
      {
       "expr": "max by (pod) (prometheus_tsdb_head_max_time{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Head GC Time/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (pod) (rate(prometheus_tsdb_head_gc_duration_seconds_sum{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "GC Time/s"
      }
     ]
    },
    {
     "title": "Blocks Loaded",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (pod) (prometheus_tsdb_blocks_loaded{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"})",
       "legendFormat": "Blocks Loaded"
      }
     ]
    },
    {
     "title": "TSDB Reloads/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (pod) (rate(prometheus_tsdb_reloads_total{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[10m]))",
       "legendFormat": "Reloads"
      }
     ]
    },
    {
     "title": "WAL Fsync&Truncate Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (pod) (rate(prometheus_tsdb_wal_fsync_duration_seconds_sum{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]) / rate(prometheus_tsdb_wal_fsync_duration_seconds_count{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Fsync Latency"
      },
      {
       "expr": "max by (pod) (rate(prometheus_tsdb_wal_truncate_duration_seconds_sum{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]) / rate(prometheus_tsdb_wal_trunacte_duration_seconds_count{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Truncate Latency"
      }
     ]
    },
    {
     "title": "TSDB Problems/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (pod) (rate(prometheus_tsdb_wal_corruptions_total{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[10m]))",
       "legendFormat": "WAL Corruptions"
      },
      {
       "expr": "max by (pod) (rate(prometheus_tsdb_reloads_failures_total{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[10m]))",
       "legendFormat": "Reload Failures"
      },
      {
       "expr": "rate(prometheus_tsdb_head_series_not_found{source=\"deckhouse\", job=\"prometheus\",instance=\"$Prometheus:9090\"}[10m])",
       "legendFormat": "Head Series Not Found"
      },
      {
       "expr": "rate(prometheus_tsdb_compactions_failed_total{source=\"deckhouse\", job=\"prometheus\",instance=\"$Prometheus:9090\"}[10m])",
       "legendFormat": "Compaction Failures"
      },
      {
       "expr": "rate(prometheus_tsdb_retention_cutoffs_failures_total{source=\"deckhouse\", job=\"prometheus\",instance=\"$Prometheus:9090\"}[10m])",
       "legendFormat": "Retention Cutoff Failures"
      },
      {
       "expr": "rate(prometheus_tsdb_checkpoint_creations_failed_total{source=\"deckhouse\", job=\"prometheus\",instance=\"$Prometheus:9090\"}[10m])",
       "legendFormat": "WAL Checkpoint Creation Failures"
      },
      {
       "expr": "rate(prometheus_tsdb_checkpoint_deletions_failed_total{source=\"deckhouse\", job=\"prometheus\",instance=\"$Prometheus:9090\"}[10m])",
       "legendFormat": "WAL Checkpoint Deletion Failures"
      }
     ]
    },
    {
     "title": "Compactions/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (pod) (rate(prometheus_tsdb_compactions_total{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[10m]))",
       "legendFormat": "Compactions"
      }
     ]
    },
    {
     "title": "Compaction Time/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (pod) (rate(prometheus_tsdb_compaction_duration_seconds_sum{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[10m]))"
      }
     ]
    },
    {
     "title": "Retention Cutoffs/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (pod) (rate(prometheus_tsdb_time_retentions_total{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[10m]))",
       "legendFormat": "Time Cutoffs"
      },
      {
       "expr": "max by (pod) (rate(prometheus_tsdb_size_retentions_total{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[10m]))",
       "legendFormat": "Size Cutoffs"
      }
     ]
    },
    {
     "title": "First Compaction, Avg Chunk Time Range",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
     "targets": [
      {
       "expr": "max by (pod) (rate(prometheus_tsdb_compaction_chunk_range_seconds_sum{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[10m]) / rate(prometheus_tsdb_compaction_chunk_range_seconds_count{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[10m]))",
       "legendFormat": "Chunk Time Range"
      }
     ]
    },
    {
     "title": "First Compaction, Avg Bytes/Sample",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (pod) (rate(prometheus_tsdb_compaction_chunk_size_bytes_sum{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[10m]) / rate(prometheus_tsdb_compaction_chunk_samples_sum{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[10m]))",
       "legendFormat": "Bytes/Sample"
      }
     ]
    },
    {
     "title": "First Compaction, Avg Chunk Samples",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (dpo) (rate(prometheus_tsdb_compaction_chunk_samples_sum{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[10m]) / rate(prometheus_tsdb_compaction_chunk_samples_count{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[10m]))",
       "legendFormat": "Chunk Samples"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Engine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query engine timings/s",
     "type": "timeseries",
     "description": "Time spent in each mode, per second",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (pod, slice) (rate(prometheus_engine_query_duration_seconds_sum{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{slice}}"
      }
     ]
    },
    {
     "title": "Rule group evaulation problems/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (pod) (rate(prometheus_rule_group_iterations_missed_total{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Rule group missed"
      },
      {
       "expr": "max by (pod) (rate(prometheus_rule_evaluation_failures_total{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Rule evals failed"
      }
     ]
    },
    {
     "title": "Evaluation time of rule groups/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (pod) (rate(prometheus_rule_group_duration_seconds_sum{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Rule evaluation duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Notification",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Notification Sent/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (pod, alertmanager) (rate(prometheus_notifications_sent_total{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{alertmanager}}"
      }
     ]
    },
    {
     "title": "Notification Error Ratio",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (pod, alertmanager) (rate(prometheus_notifications_errors_total{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]) / rate(prometheus_notifications_sent_total{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{alertmanager}}"
      }
     ]
    },
    {
     "title": "Notification Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (pod, alertmanager) (rate(prometheus_notifications_latency_seconds_sum{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]) / rate(prometheus_notifications_latency_seconds_count{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{alertmanager}}"
      }
     ]
    },
    {
     "title": "Alertmanagers Discovered",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (pod) (prometheus_notifications_alertmanagers_discovered{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"})",
       "legendFormat": "Alertmanagers"
      }
     ]
    },
    {
     "title": "Notifications Dropped/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (pod) (rate(prometheus_notifications_dropped_total{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Dropped"
      }
     ]
    },
    {
     "title": "Notification Queue",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (pod) (prometheus_notifications_queue_length{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"})",
       "legendFormat": "Pending"
      },
      {
       "expr": "max by (pod) (prometheus_notifications_queue_capacity{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"})",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP requests/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (pod, handler) (rate(prometheus_http_request_duration_seconds_count{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "HTTP request latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (pod, handler) (rate(prometheus_http_request_duration_seconds_sum{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]) / rate(prometheus_http_request_duration_seconds_count{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Time spent in HTTP requests/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (pod, handler) (rate(prometheus_http_request_duration_seconds_sum{source=\"deckhouse\", job=\"prometheus\",pod=\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{handler}}"
      }
     ]
    }
   ]
  }
 ]
}