{{- $defaultGateway := dict }}
{{- include "helm_lib_default_gateway" (list . $defaultGateway) }}
{{- if and $defaultGateway .Values.prometheus.internal.grafana.enabled .Values.global.modules.publicDomainTemplate }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    alb-istio.network.deckhouse.io/auto-create-xlistenerset: "true"
    alb-istio.network.deckhouse.io/session-affinity: '{"mode": "cookie", "path": "/", "ttl": 0}'
    alb-istio.network.deckhouse.io/backend-tls-settings: '{"mode": "MUTUAL", "caCertificates": "/etc/kube-rbac-proxy-client-ssl/ca.crt", "clientCertificate": "/etc/kube-rbac-proxy-client-ssl/client.crt", "privateKey": "/etc/kube-rbac-proxy-client-ssl/client.key", "insecureSkipVerify": true}'
    alb-istio.network.deckhouse.io/tls-secrets: d8-monitoring/{{ include "helm_lib_module_https_secret_name" (list . "httproute-tls") }}
  {{- if or (eq (include "helm_lib_module_https_mode" .) "CertManager") (eq (include "helm_lib_module_https_mode" .) "CustomCertificate") }}
    alb-istio.network.deckhouse.io/response-headers-to-add: '{"Strict-Transport-Security":"max-age=31536000; includeSubDomains","X-Content-Type-Options":"nosniff"}'
  {{- end }}
  {{- if and (ne (include "helm_lib_module_https_mode" .) "Disabled") .Values.prometheus.auth.externalAuthentication }}
    alb-istio.network.deckhouse.io/auth-signin: {{ replace "$host" (include "helm_lib_module_public_domain" (list . "grafana")) .Values.prometheus.auth.externalAuthentication.authSignInURL | quote }}
    alb-istio.network.deckhouse.io/auth-url: {{ .Values.prometheus.auth.externalAuthentication.authURL | quote }}
  {{- else }}
    alb-istio.network.deckhouse.io/basic-auth-secret: d8-monitoring/basic-auth
  {{- end }}
  {{- if .Values.prometheus.auth.whitelistSourceRanges }}
    alb-istio.network.deckhouse.io/whitelist-source-range: {{ .Values.prometheus.auth.whitelistSourceRanges | join "," }}
  {{- end }}
  name: grafana-v10
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" "grafana-v10")) | nindent 2 }}
spec:
  hostnames:
  - {{ include "helm_lib_module_public_domain" (list . "grafana") }}
  parentRefs:
  - group: gateway.networking.x-k8s.io
    kind: XListenerSet
    name: d8-default-listener-set
    namespace: d8-monitoring
    sectionName: grafana
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: grafana-v10
      port: 443
      weight: 1
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          replaceFullPath: /
          type: ReplaceFullPath
    matches:
    - path:
        type: Exact
        value: /login
  - backendRefs:
    - group: ""
      kind: Service
      name: grafana-v10
      port: 443
      weight: 1
    filters:
    - requestHeaderModifier:
        set:
        - name: X-Content-Type-Options
          value: nosniff
      type: RequestHeaderModifier
    matches:
    - path:
        type: PathPrefix
        value: /
{{- if (include "helm_lib_module_https_ingress_tls_enabled" .) }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-redirect
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" "grafana-v10")) | nindent 2 }}
  annotations:
    alb-istio.network.deckhouse.io/auto-create-xlistenerset: "true"
spec:
  hostnames:
  - {{ include "helm_lib_module_public_domain" (list . "grafana") }}
  parentRefs:
  - group: gateway.networking.x-k8s.io
    kind: XListenerSet
    name: d8-default-listener-set
    namespace: d8-monitoring
    sectionName: grafana-redirect
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
    matches:
    - path:
        type: PathPrefix
        value: /
{{- end }}
{{- end }}
