#!/bin/bash

source /antiopa/shell_lib.sh

function __main__() {
  cluster_type=$(values::get global.discovery.clusterType)
  if [[ "$cluster_type" == "ACS" ]] ; then
    return 1
  else
    return 0
  fi
}

hook::run $@
