#!/bin/bash

source /deckhouse/shell_lib.sh

function __main__() {
  enabled::disable_module_if_cluster_is_not_bootstraped

  cluster_type=$(values::get global.discovery.clusterType)
  if [[ "$cluster_type" == "ACS" ]] ; then
    echo "false" > $MODULE_ENABLED_RESULT
  else
    echo "true" > $MODULE_ENABLED_RESULT
  fi
}

enabled::run $@
