apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:subsystem-capability:kubernetes:view_resources
  annotations:
    en.meta.deckhouse.io/title: "Kubernetes: view cluster resources"
    ru.meta.deckhouse.io/title: "Kubernetes: просмотр кластерных ресурсов"
    en.meta.deckhouse.io/description: "Read-only access to common cluster-scoped Kubernetes resources."
    ru.meta.deckhouse.io/description: "Доступ только на чтение к общим кластерным ресурсам Kubernetes."
  labels:
    heritage: deckhouse
    module: user-authz
    rbac.deckhouse.io/kind: capability
    rbac.deckhouse.io/scope: subsystem
    rbac.deckhouse.io/subsystem: kubernetes
    rbac.deckhouse.io/aggregate-to-kubernetes-as: viewer
    rbac.deckhouse.io/aggregate-to-infrastructure-as: viewer
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
      - namespaces/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/log
      - nodes/metrics
      - nodes/proxy
      - nodes/stats
    verbs:
      - '*'
  - apiGroups:
      - node.k8s.io
    resources:
      - runtimeclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - scheduling.k8s.io
    resources:
      - priorityclasses
    verbs:
      - get
      - list
      - watch