{{- $kubernetesSemVer := semver .Values.global.discovery.kubernetesVersion }}
{{- $ccmImageName := join "" (list "cloudControllerManager" $kubernetesSemVer.Major $kubernetesSemVer.Minor ) }}
{{- $ccmImage := include "helm_lib_module_image_no_fail" (list . $ccmImageName) }}
{{- if $ccmImage }}

{{- $ccmConfig := dict }}
{{- $_ := set $ccmConfig "image" $ccmImage }}
{{- $_ := set $ccmConfig "additionalArgs" (list
  (printf "--cluster-cidr=%s" .Values.global.discovery.podSubnet)
  "--allocate-node-cidrs=true"
  "--configure-cloud-routes=true"
  "--cloud-config=/etc/cloud-contoller-manager-config/cloud-config"
  "--cloud-provider=aws"
  "--v=2"
) }}
{{- $_ := set $ccmConfig "additionalEnvs" (list
  (dict "name" "AWS_ACCESS_KEY_ID" "valueFrom" (dict "secretKeyRef" (dict "name" "cloud-controller-manager" "key" "aws-access-key-id")))
  (dict "name" "AWS_SECRET_ACCESS_KEY" "valueFrom" (dict "secretKeyRef" (dict "name" "cloud-controller-manager" "key" "aws-secret-access-key")))
) }}
{{- $_ := set $ccmConfig "additionalPodAnnotations" (dict "checksum/config" (include (print $.Template.BasePath "/cloud-controller-manager/secret.yaml") . | sha256sum)) }}
{{- $_ := set $ccmConfig "additionalVolumeMounts" (list
  (dict "mountPath" "/etc/kubernetes/pki" "name" "k8s-certs" "readOnly" true)
  (dict "mountPath" "/etc/cloud-contoller-manager-config" "name" "config" "readOnly" true)
) }}
{{- $_ := set $ccmConfig "additionalVolumes" (list
  (dict "hostPath" (dict "path" "/etc/kubernetes/pki" "type" "DirectoryOrCreate") "name" "k8s-certs")
  (dict "name" "config" "secret" (dict "secretName" "cloud-controller-manager" "items" (list (dict "key" "cloud-config" "path" "cloud-config"))))
) }}
{{- $_ := set $ccmConfig "vpaEnabled" true }}
{{- $_ := set $ccmConfig "securityPolicyExceptionEnabled" true }}

{{- include "helm_lib_cloud_controller_manager_manifests" (list . $ccmConfig) }}
{{- end }}
