source 'https://rubygems.org'

gem 'jekyll', ">= 3.9.1", "< 3.9.2"
gem 'jekyll-assets'
gem 'html-proofer'
gem 'jekyll-regex-replace'
gem 'kramdown-parser-gfm'
gem 'jekyll_include_plugin'

gem "sprockets", "~> 3.7"
gem "nokogiri", ">= 1.10.8"
gem "jekyll-include-cache", "~> 0.2"
