#!/bin/bash
# Copyright 2025 Flant JSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE

set -Eeo pipefail

# Copy binary.
mkdir -p /opt/deckhouse/bin
cp -f d8-shutdown-inhibitor /opt/deckhouse/bin

chown 0:0 /opt/deckhouse/bin/d8-shutdown-inhibitor
chmod 700 /opt/deckhouse/bin/d8-shutdown-inhibitor

# Install systemd unit.
cp -f d8-shutdown-inhibitor.service /lib/systemd/system
chmod 600 /lib/systemd/system/d8-shutdown-inhibitor.service
systemctl daemon-reload
systemctl enable d8-shutdown-inhibitor.service
