{
 "title": "Pgbouncer / Odyssey",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(pgbouncer_databases_current_connections, namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(pgbouncer_databases_current_connections{namespace=~\"$namespace\"}, service)"
    }
   },
   {
    "name": "db",
    "label": "Database",
    "query": {
     "query": "label_values(pgbouncer_databases_current_connections{namespace=~\"$namespace\",service=~\"$service\"}, database)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (service, database) (pgbouncer_databases_current_connections{namespace=~\"$namespace\", database=~\"$db\", service=~\"$service\"})",
     "legendFormat": "{{service}} / database: {{database}}"
    }
   ]
  },
  {
   "title": "Active clients",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (service, database) (pgbouncer_pools_client_active_connections{namespace=~\"$namespace\", database=~\"$db\", service=~\"$service\"})",
     "legendFormat": "{{service}} / database: {{database}}"
    }
   ]
  },
  {
   "title": "Query time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (service, database) (irate(pgbouncer_stats_queries_duration_seconds_total{namespace=~\"$namespace\", database=~\"$db\", service=~\"$service\"}[1m]))",
     "legendFormat": "{{service}} / database: {{database}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (service, database) (irate(pgbouncer_stats_queries_pooled_total{namespace=~\"$namespace\", database=~\"$db\", service=~\"$service\"}[1m]))",
     "legendFormat": "{{service}} / database: {{database}}"
    }
   ]
  },
  {
   "title": "Total connections to serverer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (service, database) (pgbouncer_pools_server_active_connections{namespace=~\"$namespace\", database=~\"$db\", service=~\"$service\"})",
     "legendFormat": "Active: {{service}} / database: {{database}}"
    },
    {
     "expr": "sum by (service, database) (pgbouncer_pools_server_idle_connections{namespace=~\"$namespace\", database=~\"$db\", service=~\"$service\"} + pgbouncer_pools_server_active_connections{namespace=~\"$namespace\", database=~\"$db\", service=~\"$service\"} )",
     "legendFormat": "Total: {{service}} / database: {{database}}"
    },
    {
     "expr": "sum by (service, database) (pgbouncer_pools_server_idle_connections{namespace=~\"$namespace\", database=~\"$db\", service=~\"$service\"})",
     "legendFormat": "Idle: {{service}} / database: {{database}}"
    }
   ]
  },
  {
   "title": "Data rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by (service, database) (irate(pgbouncer_stats_sent_bytes_total{namespace=~\"$namespace\", database=~\"$db\", service=~\"$service\"}[1m]))",
     "legendFormat": "Sent: {{database}}"
    },
    {
     "expr": "(sum by (service, database) (irate(pgbouncer_stats_received_bytes_total{namespace=~\"$namespace\", database=~\"$db\", service=~\"$service\"}[1m]))) / -1",
     "legendFormat": "{{service}} / database: {{database}}"
    }
   ]
  },
  {
   "title": "Waiting clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (service, database) (irate(pgbouncer_pools_client_waiting_connections{namespace=~\"$namespace\", database=~\"$db\", service=~\"$service\"}[1m]))",
     "legendFormat": "{{service}} / database: {{database}}"
    }
   ]
  }
 ]
}