#!/usr/bin/env bash

# Copyright 2026 Flant JSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE

source /shell_lib.sh

function __config__() {
  cat <<EOF
configVersion: v1
kubernetes:
- name: istioMC
  group: main
  executeHookOnEvent: []
  executeHookOnSynchronization: false
  keepFullObjectsInMemory: false
  apiVersion: deckhouse.io/v1alpha1
  kind: ModuleConfig
  nameSelector:
    matchNames:
    - istio
  jqFilter: |
    {
      "multicluster_enabled": .spec.settings.multicluster.enabled,
    }
kubernetesValidating:
- name: istiomulticlusters.deckhouse.io
  group: main
  includeSnapshotsFrom: ["istioMC"]
  rules:
  - apiGroups:   ["deckhouse.io"]
    apiVersions: ["v1alpha1"]
    operations:  ["CREATE"]
    resources:   ["istiomulticlusters"]
    scope:       "Cluster"
EOF
}

function __main__() {
  multicluster_enabled=$(context::jq -r '.snapshots.istioMC[]?.filterResult.multicluster_enabled')
  if [ "$multicluster_enabled" != "true" ]; then
    jq -nc '
    {
      "allowed": false,
      "message": "IstioMulticlusters can only be created when multicluster is enabled. Enable spec.settings.multicluster.enabled in the istio ModuleConfig."
    }
    ' > $VALIDATING_RESPONSE_PATH
    exit 0
  fi

  jq -nc '{"allowed": true}' >"$VALIDATING_RESPONSE_PATH"
}

hook::run "$@"
