{
 "title": "External ping",
 "tags": [ "nodes" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "source_node",
    "label": "Source",
    "query": "label_values(external_ping_packets_sent_total{source=\"deckhouse\"}, node)"
   },
   {
    "name": "destination_name",
    "label": "Destination",
    "query": "label_values(external_ping_packets_sent_total{source=\"deckhouse\"}, destination_name{source=\"deckhouse\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "From all nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "table-old",
   "description": "Average measurements grouped by ping request targets",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(\n  sum by (destination_name) (increase(external_ping_packets_sent_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__range]))\n  -\n  sum by (destination_name) (increase(external_ping_packets_received_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__range]))\n)\n/\n  sum by (destination_name) (increase(external_ping_packets_sent_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__range]))"
    },
    {
     "expr": "sum by (destination_name) (increase(external_ping_rtt_milliseconds_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__range]))\n/\nsum by (destination_name) (increase(external_ping_packets_sent_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__range]))"
    },
    {
     "expr": "avg by (destination_name) (avg_over_time(external_ping_rtt_mdev{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Average mean RTT with min/max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum (increase(external_ping_rtt_milliseconds_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__rate_interval]))\n/\nsum (increase(external_ping_packets_received_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__rate_interval]))",
     "legendFormat": "RTT"
    },
    {
     "expr": "max (max_over_time(external_ping_rtt_max{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__rate_interval]))",
     "legendFormat": "RTT max"
    },
    {
     "expr": "min (min_over_time(external_ping_rtt_min{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__rate_interval]))",
     "legendFormat": "RTT min"
    }
   ]
  },
  {
   "title": "Mean packet loss",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "( \n  sum by (destination_name) (increase(external_ping_packets_sent_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__rate_interval]))\n  -\n  sum by (destination_name) (increase(external_ping_packets_received_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__rate_interval]))\n)\n/\n  sum by (destination_name) (increase(external_ping_packets_sent_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__rate_interval]))",
     "legendFormat": "{{destination_name}}"
    }
   ]
  },
  {
   "title": "Mean RTT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (destination_name) (increase(external_ping_rtt_milliseconds_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__rate_interval]))\n/\nsum by (destination_name) (increase(external_ping_packets_received_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__rate_interval]))",
     "legendFormat": "{{destination_name}}"
    }
   ]
  },
  {
   "title": "Mean deviation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (destination_name) (avg_over_time(external_ping_rtt_mdev{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__rate_interval]))",
     "legendFormat": "{{destination_name}}"
    }
   ]
  },
  {
   "title": "From $source_node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "source_node",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "table",
     "description": "Average measurements grouped by ping request sources",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "(\n  sum by (destination_name) (increase(external_ping_packets_sent_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__range]))\n  -\n  sum by (destination_name) (increase(external_ping_packets_received_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__range]))\n)\n/\n  sum by (destination_name) (increase(external_ping_packets_sent_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__range]))"
      },
      {
       "expr": "sum by (destination_name) (increase(external_ping_rtt_milliseconds_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__rate_interval]))\n/\nsum by (destination_name) (increase(external_ping_packets_received_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__rate_interval]))"
      },
      {
       "expr": "avg by (destination_name) (avg_over_time(external_ping_rtt_mdev{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Average mean RTT with min/max",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum (increase(external_ping_rtt_milliseconds_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__rate_interval]))\n/\nsum (increase(external_ping_packets_received_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__rate_interval]))",
       "legendFormat": "RTT"
      },
      {
       "expr": "max (max_over_time(external_ping_rtt_max{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__rate_interval]))",
       "legendFormat": "RTT max"
      },
      {
       "expr": "min (min_over_time(external_ping_rtt_min{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__rate_interval]))",
       "legendFormat": "RTT min"
      }
     ]
    },
    {
     "title": "Mean packet loss",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  sum by (destination_name) (increase(external_ping_packets_sent_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__rate_interval]))\n  -\n  sum by (destination_name) (increase(external_ping_packets_received_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__rate_interval]))\n)\n/\n  sum by (destination_name) (increase(external_ping_packets_sent_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__rate_interval]))",
       "legendFormat": "{{destination_name}}"
      }
     ]
    },
    {
     "title": "Mean RTT",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (destination_name) (increase(external_ping_rtt_milliseconds_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__rate_interval]))\n/\nsum by (destination_name) (increase(external_ping_packets_received_total{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__rate_interval]))",
       "legendFormat": "{{destination_name}}"
      }
     ]
    },
    {
     "title": "Mean deviation",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (destination_name) (avg_over_time(external_ping_rtt_mdev{source=\"deckhouse\", node=~\"$source_node\", destination_name=~\"$destination_name\"}[$__rate_interval]))",
       "legendFormat": "{{destination_name}}"
      }
     ]
    }
   ]
  }
 ]
}