#!/bin/bash
# Copyright 2021 Flant JSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE

set -Eeo pipefail
dpkg -i -E virt-what_amd64.deb
apt-mark hold virt-what
