#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p beforeHelm=30
}

function __main__() {
  # Миграция 2019-09-15: https://github.com/deckhouse/deckhouse/merge_requests/1133

  fltr='.'

  fltr=$fltr' | .spec.template.spec.nodeSelector = {"node-role.kubernetes.io/master":""}'
  fltr=$fltr' | .spec.template.spec.tolerations = [{"operator":"Exists"}]'

  kubectl::jq_patch antiopa deploy/antiopa "$fltr"
}

hook::run "$@"
