#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p beforeHelm=30
}

function __main__() {
  fltr='.'

  fltr=$fltr' | .spec.template.spec.nodeSelector = {"node-role.kubernetes.io/master":""}'
  fltr=$fltr' | .spec.template.spec.tolerations = [{"operator":"Exists"}]'

  kubectl::jq_patch antiopa deploy/antiopa "$fltr"
}

hook::run "$@"
