#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p beforeHelm=30
}

function __main__() {
  system_node_count=$(cluster::count_nodes_by_role "system")
  fltr='.'

  if values::has antiopa.nodeSelector ; then
    if ! values::is_false antiopa.nodeSelector ; then
      fltr=$fltr" | .spec.template.spec.nodeSelector = $(values::get --required antiopa.nodeSelector | jq -c .)"
    else
      fltr=$fltr' | del(.spec.template.spec.nodeSelector)'
    fi
  elif (( "$system_node_count" > 0 )); then
    fltr=$fltr' | .spec.template.spec.nodeSelector = {"node-role.flant.com/system":""}'
  else
    fltr=$fltr' | del(.spec.template.spec.nodeSelector)'
  fi

  if values::has antiopa.tolerations ; then
    if ! values::is_false antiopa.tolerations ; then
      fltr=$fltr" | .spec.template.spec.tolerations = $(values::get --required antiopa.tolerations | jq -c .)"
    else
      fltr=$fltr' | del(.spec.template.spec.tolerations)'
    fi
  elif (( "$system_node_count" > 0 )) ; then
    fltr=$fltr' | .spec.template.spec.tolerations = [{"key":"dedicated.flant.com","value":"system"},{"key":"node-role/system"}]'
  else
    fltr=$fltr' | del(.spec.template.spec.tolerations)'
  fi

  kubectl::jq_patch antiopa deploy/antiopa "$fltr"
}

hook::run $@
