#!/bin/bash

function kubectl_apply_jq() {
  NAMESPACE=$1
  RESOURCE=$2
  JQ=$3

  A=$(mktemp)
  B=$(mktemp)
  TMP=$(mktemp)

    CLEANUP_JQ='. | del(
      .metadata.annotations."deployment.kubernetes.io/revision",
      .metadata.annotations."kubectl.kubernetes.io/last-applied-configuration",
      .metadata.creationTimestamp,
      .metadata.generation,
      .metadata.resourceVersion,
      .metadata.selfLink,
      .metadata.uid,
      .status
    )'

  if ! kubectl -n $NAMESPACE get $RESOURCE -o json > $TMP ||
     ! jq "$CLEANUP_JQ" $TMP > $A ||
     ! jq "$JQ" $A > $B ||
     ! kubectl apply -f $B ;
  then
    echo JQ: "$JQ"

    echo "Before JQ"
    cat $A
    echo "After JQ"
    cat $B

    rm $A $B $TMP
    return 1
  fi

  diff -u $A $B
  rm $A $B $TMP
  return 0
}
