#!/bin/bash


function modules_images.registry() {
  kubectl -n antiopa get deploy/antiopa -o json | jq '.spec.template.spec.containers[0].image' -r | cut -d: -f1 | sed 's/\/dev$//'
}

function modules_images.registry_dockercfg() {
  kubectl -n antiopa get secret/registrysecret -o json | jq '.data.".dockercfg"' -r
}
