apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:subsystem:networking:manager
  annotations:
    en.meta.deckhouse.io/title: "Networking: Manager"
    ru.meta.deckhouse.io/title: "Управление подсистемы сети"
    en.meta.deckhouse.io/description: "Management of the Networking subsystem configuration."
    ru.meta.deckhouse.io/description: "Управление конфигурацией подсистемы сети."
  labels:
    heritage: deckhouse
    module: user-authz
    rbac.deckhouse.io/use-role: admin
    rbac.deckhouse.io/kind: role
    rbac.deckhouse.io/scope: subsystem
    rbac.deckhouse.io/subsystem: networking
    rbac.deckhouse.io/aggregate-to-networking-as: superadmin
    rbac.deckhouse.io/aggregate-to-system-as: manager
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.deckhouse.io/aggregate-to-networking-as: manager
rules: []
