#!/usr/bin/env bash

# Copyright 2024 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /shell_lib.sh

function __config__(){
  cat <<EOF
configVersion: v1
kubernetesValidating:
- name: instanceclass-in-nodegroups.deckhouse.io
  group: main
  rules:
  - apiGroups:   ["deckhouse.io"]
    apiVersions: ["*"]
    operations:  ["DELETE"]
    resources:   ["yandexinstanceclasses", "awsinstanceclasses", "openstackinstanceclasses", "vsphereinstanceclasses", "gcpinstanceclasses", "azureinstanceclasses", "dynamixinstanceclasses", "zvirtclusterinstanceclasses", "vcdinstanceclasses", "huaweicloudinstanceclass"]
    scope:       "Cluster"
EOF
}

function __main__() {
    classToDelete=$(context::jq -r '.review.request.name')
    classKind=$(context::jq -r '.review.request.requestKind.kind')

    if context::jq -e '.review.request.oldObject.status.nodeGroupConsumers | length > 0' >/dev/null; then
        nodeGroups=$(context::jq -r '.review.request.oldObject.status.nodeGroupConsumers | join(", ")')
        cat <<EOF > "$VALIDATING_RESPONSE_PATH"
{"allowed":false, "message":"$classKind \"$classToDelete\" cannot be deleted because it is being used by NodeGroup: $nodeGroups"}
EOF
        return 0
    fi

    cat <<EOF > "$VALIDATING_RESPONSE_PATH"
{"allowed":true}
EOF
}

hook::run "$@" 