#!/usr/bin/env bash

# Copyright 2023 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /shell_lib.sh

function __config__(){
  cat <<EOF
configVersion: v1
kubernetes:
  - name: instances
    apiVersion: deckhouse.io/v1alpha1
    kind: StaticInstance
    queue: "instances"
    group: main
    executeHookOnEvent: []
    executeHookOnSynchronization: false
    keepFullObjectsInMemory: false
    jqFilter: |
      {
        "name": .metadata.name,
        "address": .spec.address,
      }
kubernetesValidating:
- name: staticinstances-unique.deckhouse.io
  group: main
  rules:
  - apiGroups:   ["deckhouse.io"]
    apiVersions: ["*"]
    operations:  ["CREATE", "UPDATE"]
    resources:   ["staticinstances"]
    scope:       "Cluster"
EOF
}

function __main__() {
  name=$(context::jq -r '.review.request.object.metadata.name')
  address=$(context::jq -r '.review.request.object.spec.address')
  credentialsName=$(context::jq -r '.review.request.object.spec.credentialsRef.name')

  instanceWithTheSameAddress=$(context::jq -r '.snapshots.instances[].filterResult' | python3 -c '
import sys, json, ipaddress
try:
    target_ip = ipaddress.ip_address(sys.argv[1])
except:
    sys.exit(0)

for line in sys.stdin:
    if not line.strip(): continue
    try:
        inst = json.loads(line)
        if inst.get("name") != sys.argv[2]:
            if ipaddress.ip_address(inst.get("address")) == target_ip:
                print(inst.get("name"))
                sys.exit(0)
    except:
        pass
' "$address" "$name")

  if [[ -n "$instanceWithTheSameAddress" ]]; then
    cat <<EOF > "$VALIDATING_RESPONSE_PATH"
{"allowed":false, "message":"staticinstances.deckhouse.io \"$name\", static instance \"$instanceWithTheSameAddress\" is already using the address \"$address\"" }
EOF
    return 0
  fi

  cat <<EOF > "$VALIDATING_RESPONSE_PATH"
{"allowed":true}
EOF

}

hook::run "$@"
