#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: deckhouse_secret
      group: main
      queue: /modules/$(module::name::kebab_case)
      keepFullObjectsInMemory: false
      apiVersion: v1
      kind: Secret
      executeHookOnEvent: ["Added", "Modified"]
      namespace:
        nameSelector:
          matchNames: ["d8-system"]
      nameSelector:
        matchNames: ["d8-deckhouse-flant-pricing"]
      allowFailure: true
      jqFilter: '
        {
          "bundle": .data.bundle | @base64d,
          "releaseChannel": .data.releaseChannel | @base64d
        }'
EOF
}

function __main__() {
  if ! context::has snapshots.deckhouse_secret.0; then
    return 0
  fi

  deckhouse_secret=$(context::get snapshots.deckhouse_secret.0.filterResult)
  values::set flantPricing.internal.bundle "$(echo "$deckhouse_secret" | jq -r .bundle)"
  values::set flantPricing.internal.releaseChannel "$(echo "$deckhouse_secret" | jq -r .releaseChannel)"
}

hook::run "$@"
