#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  legacy::common_hooks::certificates::order_certificate::config
}

function __main__() {
  legacy::common_hooks::certificates::order_certificate::main "d8-flant-pricing" "flant-pricing-prometheus-api-client-tls" "d8-flant-pricing:flant-pricing:prometheus-api-client" "internal.prometheusAPIClientTLS" "prometheus:auth"
}

hook::run "$@"
