#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  common_hooks::certificates::order_certificate::config
}

function __main__() {
  common_hooks::certificates::order_certificate::main "kube-nginx-ingress" "nginx-auth-tls" "nginx-ingress:main" "internal.nginxAuthTLS"
  if values::has nginxIngress.additionalControllers ; then
    for additional_controller in $(values::get nginxIngress.additionalControllers | jq '.[].name' -r) ; do
      common_hooks::certificates::order_certificate::main "kube-nginx-ingress-${additional_controller}" "nginx-auth-tls" "nginx-ingress:${additional_controller}" "internal.nginxAuthTLS${additional_controller}"
    done
  fi
}

hook::run "$@"
