#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  echo '
{
  "afterHelm": 5
}'
}

function __main__() {
  if values::is_false nginxIngress.rewriteTargetMigration; then
    kill_list=$(kubectl get ing --all-namespaces -o json | jq -r '.items[] | "-n \(.metadata.namespace) \(.metadata.name)"' | (grep -P '^.*-rwr$' || true) | sort -u)
    IFS=$'\n'
    for i in $kill_list; do
      unset IFS
      kubectl delete ing $i
    done
    unset IFS
    exit 0
  fi


  # remove already created -rwr Ingresses with Labels and/or OwnerReferences
  kill_list=$(kubectl get ing --all-namespaces -o json | jq -r '.items[] | select(.metadata.labels or .metadata.ownerReferences) | "-n \(.metadata.namespace) \(.metadata.name)"' | (grep -P '^.*-rwr$' || true)  | sort -u)
  IFS=$'\n'
  for i in $kill_list; do
    unset IFS
    kubectl delete ing $i
  done
  unset IFS


  non_rwr=$(kubectl get ing --all-namespaces -o json | jq -r '.items[] | "-n \(.metadata.namespace) \(.metadata.name)"' | (grep -Pv '^.*-rwr$' || true) | sort -u)
  rwr=$(kubectl get ing --all-namespaces -o json | jq -r '.items[] | "-n \(.metadata.namespace) \(.metadata.name)"' | (grep -P '^.*-rwr$' || true) | sed s/-rwr//g | sort -u)
  trigger_list=$(comm -23 <(echo "$non_rwr") <(echo "$rwr"))

  IFS=$'\n'
  for i in $trigger_list; do
    unset IFS
    kubectl annotate ingress $i webhook.flant.com/trigger= --overwrite
    kubectl annotate ingress $i webhook.flant.com/trigger-
  done
  unset IFS
}

hook::run "$@"
