#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p afterHelm=1
}

function __main__() {
  if ! kubectl -n d8-system wait --for=condition=Ready pod -l app=ingress-conversion-webhook --timeout=120s ; then
    >&2 echo "Timeout waiting for webhook pod in d8-system namesapce"
    return 1
  fi
}

hook::run "$@"
