#!/bin/bash
# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -Eeo pipefail
packages_to_install=""
package_cri_tools="cri-tools"
package_file_cri_tools="${package_cri_tools}.x86_64.rpm"
rpm_name_cri_tools="$(rpm -qip ${package_file_cri_tools} 2>/dev/null | grep Name | awk '{print $3}')"
rpm_version_cri_tools="$(rpm -qip ${package_file_cri_tools} 2>/dev/null | grep Version | awk '{print $3}')"

if ! rpm --quiet -q "${rpm_name_cri_tools}-${rpm_version_cri_tools}"; then
  packages_to_install="${packages_to_install} ${package_file_cri_tools}"
else
  echo "RPM ${package_file_cri_tools} already installed."
fi

package_kubeadm="kubeadm"
package_file_kubeadm="${package_kubeadm}.x86_64.rpm"
rpm_name_kubeadm="$(rpm -qip ${package_file_kubeadm} 2>/dev/null | grep Name | awk '{print $3}')"
rpm_version_kubeadm="$(rpm -qip ${package_file_kubeadm} 2>/dev/null | grep Version | awk '{print $3}')"

if ! rpm --quiet -q "${rpm_name_kubeadm}-${rpm_version_kubeadm}"; then
  packages_to_install="${packages_to_install} ${package_file_kubeadm}"
else
  echo "RPM ${package_file_kubeadm} already installed."
fi

if [[ -n "${packages_to_install}" ]]; then
  rpm -U --oldpackage ${packages_to_install}
fi
yum versionlock add ${package_cri_tools} ${package_kubeadm}
