{
 "title": "Elasticsearch",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(elasticsearch_cluster_health_status, namespace)"
   },
   {
    "name": "cluster",
    "label": "Cluster name",
    "query": "label_values(elasticsearch_cluster_health_status{namespace=~\"$namespace\"},cluster)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(elasticsearch_transport_rx_packets_total{namespace=~\"$namespace\", cluster=~\"$cluster\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "General statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_number_of_nodes{namespace=\"$namespace\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Health",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_status{namespace=\"$namespace\", cluster=~\"$cluster\", color=\"red\"} * 4 + on (namespace)\nelasticsearch_cluster_health_status{namespace=\"$namespace\", cluster=~\"$cluster\", color=\"yellow\"} * 2 + on (namespace)\nelasticsearch_cluster_health_status{namespace=\"$namespace\", cluster=~\"$cluster\", color=\"green\"}"
    }
   ]
  },
  {
   "title": "Maximum Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_jvm_memory_max_bytes{namespace=\"$namespace\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_jvm_memory_used_bytes{namespace=~\"$namespace\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Memory Free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_jvm_memory_max_bytes{namespace=~\"$namespace\", cluster=~\"$cluster\"}) - sum(elasticsearch_jvm_memory_used_bytes{namespace=~\"$namespace\", cluster=~\"$cluster\"}) "
    }
   ]
  },
  {
   "title": "Stacked index stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Documents Indexed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (elasticsearch_indices_docs{namespace=\"$namespace\", cluster=~\"$cluster\", name=~\"$node\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Index Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (elasticsearch_indices_store_size_bytes{namespace=\"$namespace\", cluster=~\"$cluster\", name=~\"$node\"})",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "System stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg. CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg(rate(elasticsearch_process_cpu_time_seconds_sum{namespace=~\"$namespace\", cluster=~\"$cluster\", name=~\"$node\"}[$__interval_rv])) by (name)",
       "legendFormat": "{{ name }}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "failure_tstamp"
      }
     ]
    },
    {
     "title": "RX/TX Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "Kbits" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (rate(elasticsearch_transport_rx_size_bytes_total{namespace=\"$namespace\", cluster=~\"$cluster\", name=~\"$node\"}[$__interval_rv]))",
       "legendFormat": "{{ name }} RX"
      },
      {
       "expr": "sum by (name)  (rate(elasticsearch_transport_tx_size_bytes_total{namespace=\"$namespace\", cluster=~\"$cluster\", name=~\"$node\"}[$__interval_rv])) * -1",
       "legendFormat": "{{ name }} TX"
      }
     ]
    },
    {
     "title": "Filesystem free",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (elasticsearch_filesystem_data_free_bytes{namespace=\"$namespace\", cluster=~\"$cluster\", name=~\"$node\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filesystem available",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (elasticsearch_filesystem_data_available_bytes{namespace=\"$namespace\", cluster=~\"$cluster\", name=~\"$node\"})",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (name, type, cluster) (elasticsearch_thread_pool_active_count{name=~\"$node\", namespace=~\"$namespace\", cluster=~\"$cluster\", type!=\"management\"})",
       "legendFormat": "{{ name }} / {{ type }}"
      }
     ]
    },
    {
     "title": "Completed",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (name, type, cluster) (rate(elasticsearch_thread_pool_completed_count{name=~\"$node\", namespace=~\"$namespace\", cluster=~\"$cluster\", type!=\"management\"}[$__interval_rv]))",
       "legendFormat": "{{ name }} / {{ type }}"
      }
     ]
    },
    {
     "title": "Queued",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(elasticsearch_thread_pool_queue_count{name=~\"$node\", namespace=\"$namespace\", cluster=~\"$cluster\", type!=\"management\"}) by (name, cluster, type)",
       "legendFormat": "{{ name }} / {{type}}"
      }
     ]
    },
    {
     "title": "Rejections",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (name, type, cluster) (rate(elasticsearch_thread_pool_rejected_count{name=~\"$node\", namespace=~\"$namespace\", cluster=~\"$cluster\", type!=\"management\"}[$__interval_rv]))",
       "legendFormat": "{{ name }} / {{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Translog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (elasticsearch_indices_translog_size_in_bytes{namespace=\"$namespace\", cluster=~\"$cluster\", name=~\"$node\"})",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (rate(elasticsearch_indices_translog_size_in_bytes{namespace=\"$namespace\", cluster=~\"$cluster\", name=~\"$node\"}[$__interval_rv]))",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC periods",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (rate(elasticsearch_jvm_gc_collection_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", name=~\"$node\"}[$__interval_rv]))",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Breakers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size limit",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (name, breaker) (elasticsearch_breakers_limit_size_bytes{namespace=\"$namespace\", cluster=~\"$cluster\", name=~\"$node\"})",
       "legendFormat": "{{ name }} / {{ breaker }}"
      }
     ]
    },
    {
     "title": "Current size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (name, breaker) (elasticsearch_breakers_estimated_size_bytes{namespace=\"$namespace\", cluster=~\"$cluster\", name=~\"$node\"})",
       "legendFormat": "{{ name }} / {{ breaker }}"
      }
     ]
    },
    {
     "title": "Tripped",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (name, breaker) (rate(elasticsearch_breakers_tripped{namespace=\"$namespace\", cluster=~\"$cluster\", name=~\"$node\"}[$__interval_rv]))",
       "legendFormat": "{{ name }} / {{ breaker }}"
      }
     ]
    }
   ]
  }
 ]
}