---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - multitenancy.deckhouse.io
  resources:
  - clusterobjectgrantpolicies
  - clusterobjectgrants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multitenancy.deckhouse.io
  resources:
  - clusterobjectgrantpolicies/finalizers
  - clusterobjectgrants/finalizers
  verbs:
  - update
- apiGroups:
  - multitenancy.deckhouse.io
  resources:
  - clusterobjectgrantpolicies/status
  - clusterobjectgrants/status
  verbs:
  - get
  - patch
  - update
