#!/bin/bash

source /deckhouse/shell_lib.sh

function __main__() {
  enabled::disable_module_if_cluster_is_not_bootstraped
  enabled::disable_module_in_kubernetes_versions_less_than 1.9.0

  if values::array_has global.enabledModules "prometheus" ; then
    echo "true" > $MODULE_ENABLED_RESULT
  else
    echo "false" > $MODULE_ENABLED_RESULT
  fi
}

enabled::run $@
