{
 "title": "registry-modules-watcher stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(registry_modules_watcher_registry_requests_count,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Registry stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backends count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "registry_modules_watcher_registry_watcher_backends_total{namespace=\"$namespace\"}",
     "legendFormat": "total-{{pod}}"
    },
    {
     "expr": "registry_modules_watcher_registry_watcher_new_backends_total{namespace=\"$namespace\"}",
     "legendFormat": "new-{{pod}}"
    }
   ]
  },
  {
   "title": "Cache length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (registry_modules_watcher_registry_scanner_cache_length{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request count by status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(registry_modules_watcher_registry_requests_count{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pull time by quantile (fully downloaded images)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, max by(le) (increase(registry_modules_watcher_registry_pull_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, max by(le) (increase(registry_modules_watcher_registry_pull_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request time by quantile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, pod) (rate(registry_modules_watcher_registry_request_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "0.95-{{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, pod) (rate(registry_modules_watcher_registry_request_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "0.99-{{pod}}"
    }
   ]
  },
  { "title": "Sender upload/build/delete", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Sender timeout requests count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod)(increase(registry_modules_watcher_sender_timeout_requests_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(registry_modules_watcher_sender_upload_requests_count{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload time by bucket",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, max by(le,pod) (rate(registry_modules_watcher_sender_upload_requests_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "0.99-{{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, max by(le,pod) (rate(registry_modules_watcher_sender_upload_requests_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "0.95-{{pod}}"
    }
   ]
  },
  {
   "title": "Build count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(registry_modules_watcher_sender_build_requests_count{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build time by bucket",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, max by(le,pod) (rate(registry_modules_watcher_sender_build_requests_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "0.99-{{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, max by(le,pod) (rate(registry_modules_watcher_sender_upload_requests_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "0.95-{{pod}}"
    }
   ]
  },
  {
   "title": "Delete count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(registry_modules_watcher_sender_delete_requests_count{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delete time by bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, max by(le,pod) (rate(registry_modules_watcher_sender_delete_requests_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "0.99-{{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, max by(le,pod) (rate(registry_modules_watcher_sender_delete_requests_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "0.95-{{pod}}"
    }
   ]
  }
 ]
}