#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
# Костыль 2019-07-19: пока не разберёмся как правильно создавать CRD
kubectl apply -f $(module::path)/crds/ >/dev/null 2>&1

  cat << EOF
{
  "onKubernetesEvent": [
    {
      "kind": "PodMetric",
      "event": ["delete"]
    },
    {
      "kind": "DeploymentMetric",
      "event": ["delete"]
    },
    {
      "kind": "StatefulSetMetric",
      "event": ["delete"]
    },
    {
      "kind": "DaemonSetMetric",
      "event": ["delete"]
    },
    {
      "kind": "IngressMetric",
      "event": ["delete"]
    },
    {
      "kind": "ServiceMetric",
      "event": ["delete"]
    },
    {
      "kind": "NamespaceMetric",
      "event": ["delete"]
    },
    {
      "kind": "ClusterPodMetric",
      "event": ["delete"]
    },
    {
      "kind": "ClusterDeploymentMetric",
      "event": ["delete"]
    },
    {
      "kind": "ClusterStatefulSetMetric",
      "event": ["delete"]
    },
    {
      "kind": "ClusterDaemonSetMetric",
      "event": ["delete"]
    },
    {
      "kind": "ClusterIngressMetric",
      "event": ["delete"]
    },
    {
      "kind": "ClusterServiceMetric",
      "event": ["delete"]
    }
  ]
}
EOF
}

function __main__() {
  RESOURCE_KIND=`hook::context_jq -r '.[0].resourceKind'`
  RESOURCE_NAME=`hook::context_jq -r '.[0].resourceName'`
  RESOURCE=$(echo $RESOURCE_KIND | sed -r -e 's/^(Cluster)?(.*)Metric$/\2/')
  RESOURCE=${RESOURCE,,} #lowercase

  WHOLE_METRIC_PATH=prometheusMetricsAdapter.customMetrics.${RESOURCE}.\"${RESOURCE_NAME}\"
  if [[ "$RESOURCE_KIND" =~ ^Cluster ]]; then
    PARTICULAR_METRIC_PATH="${WHOLE_METRIC_PATH}.cluster"
  else
    RESOURCE_NAMESPACE=`hook::context_jq -r '.[0].resourceNamespace'`
    PARTICULAR_METRIC_PATH="${WHOLE_METRIC_PATH}.namespaced.\"${RESOURCE_NAMESPACE}\""
  fi

  if values::has $PARTICULAR_METRIC_PATH ; then
    if values::get $WHOLE_METRIC_PATH | jq -e '((if has("cluster") then 1 else 0 end) + (.namespaced | to_entries | length)) == 1'; then
      # there is no other metrics with our name but particular
      values::unset $WHOLE_METRIC_PATH
    else
      values::unset $PARTICULAR_METRIC_PATH
    fi
  fi
}

hook::run $@
