#!/bin/bash

# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    onStartup: 20
EOF
}

function __main__() {
  RESOURCES="pod deployment statefulset daemonset ingress service namespace"
  CUSTOM_METRICS=$(echo $RESOURCES | jq -R '[. | split(" ") | .[] | {(.): {}}] | add') # {pod: {}, ingress: {}, ...}

  for r in $RESOURCES; do
    NAMESPACED_METRICS=$(
      kubectl get ${r}Metrics --all-namespaces -o json | jq -c --arg r "${r}" '
        [
          {($r): (.items[] | {(.metadata.name): {namespaced: {(.metadata.namespace): .spec.query}}})}
        ] | reduce .[] as $item ({}; . * $item)
      '
    )
    if [[ $r != "namespace" ]]; then
      CLUSTER_METRICS=$(
        kubectl get Cluster${r}Metrics -o json | jq -c --arg r "${r}" '
          [
            {($r): (.items[] | {(.metadata.name): {cluster: .spec.query}})}
          ] | reduce .[] as $item ({}; . * $item)
        '
      )
    else
      CLUSTER_METRICS="{}"
    fi


    CUSTOM_METRICS=$(jq -n --argjson a "$CUSTOM_METRICS" --argjson b "$NAMESPACED_METRICS" --argjson c "$CLUSTER_METRICS" '$a * $b * $c')
  done

  values::set prometheusMetricsAdapter.internal.customMetrics "$CUSTOM_METRICS"
}

hook::run $@
