#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  common_hooks::certificates::order_certificate::config
}

function __main__() {
  common_hooks::certificates::order_certificate::main "kube-prometheus" "prometheus-metrics-adapter-prometheus-api-client-cert" "kube-prometheus:prometheus-metrics-adapter:prometheus-api-client"
}

hook::run "$@"
