#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  common_hooks::certificates::order_certificate::config
}

function __main__() {
  common_hooks::certificates::order_certificate::main "d8-monitoring" "prometheus-metrics-adapter-prometheus-api-client-tls" "d8-monitoring:prometheus-metrics-adapter:prometheus-api-client" "internal.prometheusAPIClientTLS"
}

hook::run "$@"
