{
 "title": "uWSGI",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "controller_kind",
    "label": "Controller Kind",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_name!=\"<none>\", created_by_kind!=\"<none>\"}, created_by_kind)"
   },
   {
    "name": "controller_name",
    "label": "Controller Name",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_name!=\"<none>\", created_by_kind!=\"<none>\", created_by_kind=~\"$controller_kind\"}, created_by_name)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_name=~\"$controller_name\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "uWSGI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, namespace) (rate(uwsgi_worker_average_response_time_seconds{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{ namespace }} / {{ pod }}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, namespace) (rate(uwsgi_worker_requests_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{ namespace }} / {{ pod }}"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, pod) (uwsgi_worker_accepting{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{ namespace }} / {{ pod }} idle"
    },
    {
     "expr": "sum by (namespace, pod) (uwsgi_workers{namespace=~\"$namespace\", pod=~\"$pod\"}) - sum by (namespace, pod) (uwsgi_worker_accepting{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{ namespace }} / {{ pod }} busy"
    }
   ]
  },
  {
   "title": "Socket queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, pod) (uwsgi_socket_queue_length{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{ namespace }} / {{ pod }} length"
    },
    {
     "expr": "sum by (namespace, pod) (uwsgi_socket_max_queue_length{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{ namespace }} / {{ pod }} max"
    }
   ]
  }
 ]
}