#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  legacy::common_hooks::https::copy_custom_certificate::config "kube-openvpn"
}

function __main__() {
  legacy::common_hooks::https::copy_custom_certificate::main "kube-openvpn" "ingress-tls"
}

hook::run "$@"
