#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  common_hooks::https::delete_not_matching_certificate_secret::config
}

function __main__() {
  common_hooks::https::delete_not_matching_certificate_secret::main "kube-openvpn"
}

hook::run "$@"
