/*
Copyright 2024 Flant JSC
Licensed under the Deckhouse Platform Enterprise Edition (EE) license.
See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE
*/

package hooks

import (
	_ "github.com/flant/addon-operator/sdk"
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"

	. "github.com/deckhouse/deckhouse/testing/hooks"
)

var _ = Describe("Metallb hooks :: migrate MC to MetalLoadBalancerClass ::", func() {
	f := HookExecutionConfigInit(`{"metallb":{"internal":{}}}`, "")
	f.RegisterCRD("deckhouse.io", "v1alpha1", "ModuleConfig", false)
	f.RegisterCRD("network.deckhouse.io", "v1alpha1", "MetalLoadBalancerClass", false)
	f.RegisterCRD("metallb.io", "v1beta1", "L2Advertisement", true)
	f.RegisterCRD("metallb.io", "v1beta1", "IPAddressPool", true)

	Context("Cluster with Metallb ModuleConfig", func() {
		BeforeEach(func() {
			f.BindingContexts.Set(f.KubeStateSet(`
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: metallb
spec:
  enabled: true
  version: 1
  settings:
    speaker:
      nodeSelector:
        node-role.deckhouse.io/metallb: ""
    addressPools:
      - name: nginx-loadbalancer-pool1
        protocol: layer2
        addresses:
          - 192.168.70.100-192.168.70.110
      - name: nginx-loadbalancer-pool2
        protocol: layer2
        addresses:
          - 192.168.71.100-192.168.72.110
`))
			f.RunHook()
		})

		It("Created a new Default MLBC based on ModuleConfig", func() {
			Expect(f).To(ExecuteSuccessfully())

			MLBC := f.KubernetesResource("MetalLoadBalancerClass", "", "l2-default")
			Expect(MLBC.ToYaml()).To(MatchYAML(`
---
apiVersion: network.deckhouse.io/v1alpha1
kind: MetalLoadBalancerClass
metadata:
  labels:
    auto-generated-by: d8-migration-hook
  name: l2-default
spec:
  isDefault: true
  type: L2
  addressPool:
  - 192.168.70.100-192.168.70.110
  - 192.168.71.100-192.168.72.110
  nodeSelector:
    node-role.deckhouse.io/metallb: ""
`))
		})
	})

	Context("Metallb ModuleConfig with 'bgp' addressPool", func() {
		BeforeEach(func() {
			f.BindingContexts.Set(f.KubeStateSet(`
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: metallb
spec:
  enabled: true
  version: 1
  settings:
    speaker:
      nodeSelector:
        node-role.deckhouse.io/metallb: ""
    addressPools:
      - name: nginx-loadbalancer-pool1
        protocol: layer2
        addresses:
          - 192.168.70.100-192.168.70.110
      - name: nginx-loadbalancer-pool2
        protocol: bgp
        addresses:
          - 192.168.71.100-192.168.72.110
`))
			f.RunHook()
		})

		It("Default MLBC should not be created", func() {
			Expect(f).To(ExecuteSuccessfully())

			MLBC := f.KubernetesResource("MetalLoadBalancerClass", "", "l2-default")
			Expect(MLBC.Exists()).To(BeFalse())
		})
	})

	Context("Cluster with some IPAddressPools and L2Advertisement", func() {
		BeforeEach(func() {
			f.BindingContexts.Set(f.KubeStateSet(`
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: metallb
spec:
  enabled: true
  version: 1
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: zone-a
  namespace: d8-metallb
  labels:
    module: metallb
spec:
  ipAddressPools:
  - pool-1
  - pool-2
  interfaces:
  - eth0
  - eth1
  nodeSelectors:
  - matchLabels:
      zone: a
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-1
  namespace: d8-metallb
  labels:
    module: metallb
spec:
  addresses:
  - 11.11.11.11/32
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-2
  namespace: d8-metallb
  labels:
    module: metallb
spec:
  addresses:
  - 22.22.22.22/32
  - 33.33.33.33/32
---
apiVersion: network.deckhouse.io/v1alpha1
kind: MetalLoadBalancerClass
metadata:
  name: zone-b
  labels:
    auto-generated-by: d8-migration-hook
spec:
  isDefault: false
  type: L2
  addressPool:
    - 44.44.44.44/32
`))
			f.RunHook()
		})

		It("Created a new MLBC based from L2Advertisement, deleted orphan MLBC", func() {
			Expect(f).To(ExecuteSuccessfully())

			MLBC := f.KubernetesResource("MetalLoadBalancerClass", "", "autogenerated-zone-a")
			Expect(MLBC.ToYaml()).To(MatchYAML(`
---
apiVersion: network.deckhouse.io/v1alpha1
kind: MetalLoadBalancerClass
metadata:
  labels:
    auto-generated-by: d8-migration-hook
  name: autogenerated-zone-a
spec:
  isDefault: false
  type: L2
  l2:
    interfaces:
      - eth0
      - eth1
  addressPool:
    - 11.11.11.11/32
    - 22.22.22.22/32
    - 33.33.33.33/32
  nodeSelector:
    zone: a
`))
			MLBC2 := f.KubernetesResource("MetalLoadBalancerClass", "", "zone-b")
			Expect(MLBC2.Exists()).To(BeFalse())
		})

		It("ipAddressPoolToMLBCMap must be present in internal values", func() {
			Expect(f).To(ExecuteSuccessfully())
			Expect(f.BindingContexts.Array()).ShouldNot(BeEmpty())

			Expect(f.ValuesGet("metallb.internal.ipAddressPoolToMLBCMap").String()).
				To(MatchYAML(`
pool-1: autogenerated-zone-a
pool-2: autogenerated-zone-a
`))
		})
	})

	Context("Cluster with two IPAddressPools and two L2Advertisements", func() {
		BeforeEach(func() {
			f.BindingContexts.Set(f.KubeStateSet(`
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: metallb
spec:
  enabled: true
  version: 1
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: zone-a
  namespace: d8-metallb
  labels:
    module: metallb
spec:
  ipAddressPools:
  - pool-1
  interfaces:
  - eth10
  - eth11
  nodeSelectors:
  - matchLabels:
      zone: a
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: zone-b
  namespace: d8-metallb
  labels:
    module: metallb
spec:
  ipAddressPools:
  - pool-2
  interfaces:
  - eth20
  - eth21
  nodeSelectors:
  - matchLabels:
      zone: b
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-1
  namespace: d8-metallb
  labels:
    module: metallb
spec:
  addresses:
  - 11.11.11.11/32
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-2
  namespace: d8-metallb
  labels:
    module: metallb
spec:
  addresses:
  - 22.22.22.22/32
  - 33.33.33.33/32
`))
			f.RunHook()
		})

		It("Created two MLBCs with different ", func() {
			Expect(f).To(ExecuteSuccessfully())

			MLBC := f.KubernetesResource("MetalLoadBalancerClass", "", "autogenerated-zone-a")
			Expect(MLBC.ToYaml()).To(MatchYAML(`
---
apiVersion: network.deckhouse.io/v1alpha1
kind: MetalLoadBalancerClass
metadata:
  labels:
    auto-generated-by: d8-migration-hook
  name: autogenerated-zone-a
spec:
  isDefault: false
  type: L2
  l2:
    interfaces:
      - eth10
      - eth11
  addressPool:
    - 11.11.11.11/32
  nodeSelector:
    zone: a
`))
			MLBC2 := f.KubernetesResource("MetalLoadBalancerClass", "", "autogenerated-zone-b")
			Expect(MLBC2.ToYaml()).To(MatchYAML(`
---
apiVersion: network.deckhouse.io/v1alpha1
kind: MetalLoadBalancerClass
metadata:
  labels:
    auto-generated-by: d8-migration-hook
  name: autogenerated-zone-b
spec:
  isDefault: false
  type: L2
  l2:
    interfaces:
      - eth20
      - eth21
  addressPool:
    - 22.22.22.22/32
    - 33.33.33.33/32
  nodeSelector:
    zone: b
`))
		})
	})
})
