apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:subsystem:kubernetes:manager
  annotations:
    en.meta.deckhouse.io/title: "Kubernetes: Manager"
    ru.meta.deckhouse.io/title: "Управление подсистемы Kubernetes"
    en.meta.deckhouse.io/description: "Management of the Kubernetes subsystem configuration."
    ru.meta.deckhouse.io/description: "Управление конфигурацией подсистемы Kubernetes."
  labels:
    heritage: deckhouse
    module: user-authz
    rbac.deckhouse.io/use-role: user
    rbac.deckhouse.io/kind: role
    rbac.deckhouse.io/scope: subsystem
    rbac.deckhouse.io/subsystem: kubernetes
    rbac.deckhouse.io/aggregate-to-kubernetes-as: superadmin
    rbac.deckhouse.io/aggregate-to-system-as: manager
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.deckhouse.io/aggregate-to-kubernetes-as: manager
rules: []
