#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p beforeHelm=10 onStartup=10
}

function __main__() {
    KUBE_DNS=$(kubectl get services -n kube-system kube-dns -o=jsonpath='{.spec.clusterIP}')
    values::set nodeLocalDns.clusterDnsIP "$KUBE_DNS"

    if kubectl -n kube-system get cm kube-proxy -o yaml | grep 'mode: "ipvs"' > /dev/null 2>&1; then
      values::set nodeLocalDns.kubeProxyMode "ipvs"
    else
      values::set nodeLocalDns.kubeProxyMode "iptables"
    fi
}

hook::run $@
