#!/bin/bash

### Миграция 2019-09-09: https://github.com/deckhouse/deckhouse/merge_requests/1114
# Данный хук можно удалить после выката релиза с данным хуком

source /antiopa/shell_lib.sh

function __config__() {
  echo '
{
  "beforeHelm": 5
}'
}

function __main__() {
  if kubectl -n kube-system get vpa node-local-dns 2>/dev/null >/dev/null ; then
    kubectl -n kube-system delete vpa node-local-dns
  fi

  if kubectl -n kube-system get svc node-local-dns 2>/dev/null >/dev/null ; then
    kubectl -n kube-system delete svc node-local-dns
  fi

  if kubectl -n kube-system get ds node-local-dns 2>/dev/null >/dev/null ; then
    kubectl -n kube-system delete ds node-local-dns
  fi

  if kubectl -n kube-system get sa node-local-dns 2>/dev/null >/dev/null ; then
    kubectl -n kube-system delete sa node-local-dns
  fi

  if kubectl -n kube-system get role node-local-dns:sidecar 2>/dev/null >/dev/null ; then
    kubectl -n kube-system delete role node-local-dns:sidecar
  fi

  if kubectl -n kube-system get rolebinding node-local-dns:sidecar 2>/dev/null >/dev/null ; then
    kubectl -n kube-system delete rolebinding node-local-dns:sidecar
  fi
}

hook::run "$@"
