#!/bin/bash

### Миграция 2019-12-30: https://github.com/deckhouse/deckhouse/merge_requests/1524
###
### Этот хук можно удалить, после выката данного MR'а на все инсталяции.

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  jo -p onStartup=0
}

function __main__() {
  if kubectl -n kube-prometheus get servicemonitors.monitoring.coreos.com node-local-dns >/dev/null 2>/dev/null ; then
    kubectl -n kube-prometheus delete servicemonitors.monitoring.coreos.com node-local-dns
  fi
}

hook::run $@
