#!/bin/bash

source /antiopa/shell_lib.sh

function __config__ () {
  echo '
{
  "beforeHelm": 20,
  "onKubernetesEvent": [
    {
      "kind": "secret",
      "name": "kubernetes-dex-client-app-secret",
      "event": [
        "add",
        "update"
      ],
      "namespaceSelector": {
        "matchNames": [
          "kube-user-authn"
        ]
      }
    }
  ]
}'
}

function __main__() {
  module_name=$(module::name)
  if values::array_has global.enabledModules "user-authn" ; then

    if ! values::has --config ${module_name}.dexAuthenticator ; then
      values::set --config ${module_name}.dexAuthenticator "{}"
    fi

    if ! values::has --config ${module_name}.dexAuthenticator.cookieSecret ; then
      values::set --config ${module_name}.dexAuthenticator.cookieSecret $(values::generate_password)
    fi

    kubernetes_dex_client_app_secret=$(kubectl -n kube-user-authn get secret kubernetes-dex-client-app-secret -o json | jq '.data.secret' -r | base64 -d)
    values::set --config ${module_name}.dexAuthenticator.dexSecret "${kubernetes_dex_client_app_secret}"
  else
    values::unset --config ${module_name}.dexAuthenticator.dexSecret
    values::unset --config ${module_name}.dexAuthenticator.cookieSecret
    values::unset --config ${module_name}.dexAuthenticator
  fi
}

hook::run "$@"
