#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p beforeHelm=20
}

function __main__() {
  module_name=$(module::name)
  if values::array_has global.enabledModules "user-authn" ; then
    if values::has ${module_name}.certificateForIngress.customCertificateSecretName && \
       values::is_false ${module_name}.certificateForIngress.customCertificateSecretName && \
       values::has ${module_name}.certificateForIngress.certmanagerClusterIssuerName && \
       values::is_false ${module_name}.certificateForIngress.certmanagerClusterIssuerName ; then

        values::unset --config ${module_name}.dexAuthenticator.dexSecret
        values::unset --config ${module_name}.dexAuthenticator.cookieSecret
        values::unset --config ${module_name}.dexAuthenticator
    else
      if ! values::has --config ${module_name}.dexAuthenticator ; then
        values::set --config ${module_name}.dexAuthenticator "{}"
      fi

      if ! values::has ${module_name}.dexAuthenticator.dexSecret ; then
        values::set --config ${module_name}.dexAuthenticator.dexSecret $(values::generate_password)
      fi

      if ! values::has ${module_name}.dexAuthenticator.cookieSecret ; then
        values::set --config ${module_name}.dexAuthenticator.cookieSecret $(values::generate_password)
      fi
    fi
  else
    values::unset --config ${module_name}.dexAuthenticator.dexSecret
    values::unset --config ${module_name}.dexAuthenticator.cookieSecret
    values::unset --config ${module_name}.dexAuthenticator
  fi
}

hook::run "$@"
