#!/bin/bash

cp /var/lib/bashible/ca.crt /etc/kubernetes/pki/

cat << "EOF" > /etc/kubernetes/bootstrap-kubelet.conf
apiVersion: v1
kind: Config
current-context: kubelet-bootstrap@default
clusters:
- cluster:
    certificate-authority-data: {{ .Values.cloudInstanceManager.internal.clusterCA | b64enc | quote }}
    server: https://{{ .Values.cloudInstanceManager.internal.clusterMasterAddresses | first }}:6443/
  name: default
contexts:
- context:
    cluster: default
    user: kubelet-bootstrap
  name: kubelet-bootstrap@default
users:
- name: kubelet-bootstrap
  user:
    as-user-extra: {}
    token: {{ .Values.cloudInstanceManager.internal.bootstrapToken }}
EOF

chmod 0600 /etc/kubernetes/bootstrap-kubelet.conf

systemctl daemon-reload

units="kubelet.service"

for unit in $units; do
  systemctl enable "$unit" && systemctl restart "$unit"
done
