{
 "title": "Node Local DNS",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(coredns_build_info, node)"
   },
   {
    "name": "rcode",
    "query": "label_values(coredns_dns_response_rcode_count_total{rcode!=\"NOERROR\"}, rcode)"
   },
   {
    "name": "upstream",
    "query": "label_values(coredns_forward_request_duration_seconds_sum,to)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Incoming requests count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_count_total{node=~\"$node\"}[$__interval_rv])) by (node)",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "sum(rate(coredns_dns_request_count_total{node=~\"$node\"}[$__interval_rv]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Incoming requests duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_duration_seconds_sum{node=~\"$node\"}[$__interval_rv])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_duration_seconds_bucket{node=~\"$node\"}[$__interval_rv])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Forwarded requests count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_request_count_total{node=~\"$node\"}[$__interval_rv])) by (node)",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "sum(rate(coredns_forward_request_count_total{node=~\"$node\"}[$__interval_rv]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Forwarded requests duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_request_duration_seconds_sum{node=~\"$node\"}[$__interval_rv])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Forward duration",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_request_duration_seconds_bucket{node=~\"$node\"}[$__interval_rv])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Cache hit rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{node=~\"$node\"}[$__interval_rv])) by (node)\n/\n(\nsum(rate(coredns_cache_hits_total{node=~\"$node\"}[$__interval_rv])) by (node) +\nsum(rate(coredns_cache_misses_total{node=~\"$node\"}[$__interval_rv])) by (node) \n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Cache size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(coredns_cache_size{node=~\"$node\"}[$__interval_rv])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$rcode",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 32 },
   "repeat": "rcode",
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_response_rcode_count_total{node=~\"$node\", rcode=~\"$rcode\"}[$__interval_rv])) by (node)",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "sum(rate(coredns_dns_response_rcode_count_total{node=~\"$node\", rcode=~\"$rcode\"}[$__interval_rv]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "$rcode",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_response_rcode_count_total{node=~\"$node\", rcode=~\"$rcode\"}[$__interval_rv])) by (node)",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "sum(rate(coredns_dns_response_rcode_count_total{node=~\"$node\", rcode=~\"$rcode\"}[$__interval_rv]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "TCP/UDP requests ratio",
   "type": "graph",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_count_total{node=~\"$node\",proto=\"tcp\"}[$__interval_rv]))\n/\nsum(rate(coredns_dns_request_count_total{node=~\"$node\"}[$__interval_rv]))",
     "legendFormat": "TCP"
    },
    {
     "expr": "sum(rate(coredns_dns_request_count_total{node=~\"$node\",proto=\"udp\"}[$__interval_rv]))\n/\nsum(rate(coredns_dns_request_count_total{node=~\"$node\"}[$__interval_rv]))",
     "legendFormat": "UDP"
    }
   ]
  },
  {
   "title": "Node $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "repeat": "node",
   "collapsed": true,
   "panels": [
    {
     "title": "Requests (by qtype)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_request_type_count_total{node=~\"$node\"}[$__interval_rv])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Responses (by rcode)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_response_rcode_count_total{node=~\"$node\"}[5m])) by (rcode)",
       "legendFormat": "{{rcode}}"
      }
     ]
    },
    {
     "title": "Forwarded requests count (by upstream)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_request_count_total{node=~\"$node\"}[$__interval_rv])) by (to)",
       "legendFormat": "{{to}}"
      },
      {
       "expr": "sum(rate(coredns_forward_request_count_total{node=~\"$node\"}[$__interval_rv]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Forwarded requests count (by rcode)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_response_rcode_count_total{node=~\"$node\"}[$__interval_rv])) by (rcode)",
       "legendFormat": "{{rcode}}"
      },
      {
       "expr": "sum(rate(coredns_forward_response_rcode_count_total{node=~\"$node\"}[$__interval_rv]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "TCP/UDP requests ratio",
     "type": "graph",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_request_count_total{node=~\"$node\",proto=\"tcp\"}[$__interval_rv]))\n/\nsum(rate(coredns_dns_request_count_total{node=~\"$node\"}[$__interval_rv]))",
       "legendFormat": "TCP"
      },
      {
       "expr": "sum(rate(coredns_dns_request_count_total{node=~\"$node\",proto=\"udp\"}[$__interval_rv]))\n/\nsum(rate(coredns_dns_request_count_total{node=~\"$node\"}[$__interval_rv]))",
       "legendFormat": "UDP"
      }
     ]
    },
    {
     "title": "Cache hit rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_cache_hits_total{node=~\"$node\"}[$__interval_rv]))\n/\n(\nsum(rate(coredns_cache_hits_total{node=~\"$node\"}[$__interval_rv])) +\nsum(rate(coredns_cache_misses_total{node=~\"$node\"}[$__interval_rv]))\n)"
      }
     ]
    },
    {
     "title": "Cache size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(max_over_time(coredns_cache_size{node=~\"$node\"}[$__interval_rv])) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(max_over_time(coredns_cache_size{node=~\"$node\"}[$__interval_rv]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Requests (by zone)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_request_count_total{node=~\"$node\"}[$__interval_rv])) by (zone)",
       "legendFormat": "{{zone}}"
      },
      {
       "expr": "sum(rate(coredns_dns_request_count_total{node=~\"node\"}[$__interval_rv]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Request duration",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_request_duration_seconds_bucket{node=~\"$node\"}[$__interval_rv])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Forward duration",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_request_duration_seconds_bucket{node=~\"$node\"}[$__interval_rv])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests (by qtype)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_request_type_count_total{node=~\"$node\"}[$__interval_rv])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Responses (by rcode)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_response_rcode_count_total{node=~\"$node\"}[5m])) by (rcode)",
       "legendFormat": "{{rcode}}"
      }
     ]
    },
    {
     "title": "Forwarded requests count (by upstream)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_request_count_total{node=~\"$node\"}[$__interval_rv])) by (to)",
       "legendFormat": "{{to}}"
      },
      {
       "expr": "sum(rate(coredns_forward_request_count_total{node=~\"$node\"}[$__interval_rv]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Forwarded requests count (by rcode)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_response_rcode_count_total{node=~\"$node\"}[$__interval_rv])) by (rcode)",
       "legendFormat": "{{rcode}}"
      },
      {
       "expr": "sum(rate(coredns_forward_response_rcode_count_total{node=~\"$node\"}[$__interval_rv]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "TCP/UDP requests ratio",
     "type": "graph",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_request_count_total{node=~\"$node\",proto=\"tcp\"}[$__interval_rv]))\n/\nsum(rate(coredns_dns_request_count_total{node=~\"$node\"}[$__interval_rv]))",
       "legendFormat": "TCP"
      },
      {
       "expr": "sum(rate(coredns_dns_request_count_total{node=~\"$node\",proto=\"udp\"}[$__interval_rv]))\n/\nsum(rate(coredns_dns_request_count_total{node=~\"$node\"}[$__interval_rv]))",
       "legendFormat": "UDP"
      }
     ]
    },
    {
     "title": "Cache hit rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_cache_hits_total{node=~\"$node\"}[$__interval_rv]))\n/\n(\nsum(rate(coredns_cache_hits_total{node=~\"$node\"}[$__interval_rv])) +\nsum(rate(coredns_cache_misses_total{node=~\"$node\"}[$__interval_rv]))\n)"
      }
     ]
    },
    {
     "title": "Cache size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(max_over_time(coredns_cache_size{node=~\"$node\"}[$__interval_rv])) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(max_over_time(coredns_cache_size{node=~\"$node\"}[$__interval_rv]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Requests (by zone)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_request_count_total{node=~\"$node\"}[$__interval_rv])) by (zone)",
       "legendFormat": "{{zone}}"
      },
      {
       "expr": "sum(rate(coredns_dns_request_count_total{node=~\"node\"}[$__interval_rv]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Request duration",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_request_duration_seconds_bucket{node=~\"$node\"}[$__interval_rv])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Forward duration",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_request_duration_seconds_bucket{node=~\"$node\"}[$__interval_rv])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests (by qtype)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_request_type_count_total{node=~\"$node\"}[$__interval_rv])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Responses (by rcode)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_response_rcode_count_total{node=~\"$node\"}[5m])) by (rcode)",
       "legendFormat": "{{rcode}}"
      }
     ]
    },
    {
     "title": "Forwarded requests count (by upstream)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_request_count_total{node=~\"$node\"}[$__interval_rv])) by (to)",
       "legendFormat": "{{to}}"
      },
      {
       "expr": "sum(rate(coredns_forward_request_count_total{node=~\"$node\"}[$__interval_rv]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Forwarded requests count (by rcode)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_response_rcode_count_total{node=~\"$node\"}[$__interval_rv])) by (rcode)",
       "legendFormat": "{{rcode}}"
      },
      {
       "expr": "sum(rate(coredns_forward_response_rcode_count_total{node=~\"$node\"}[$__interval_rv]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "TCP/UDP requests ratio",
     "type": "graph",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_request_count_total{node=~\"$node\",proto=\"tcp\"}[$__interval_rv]))\n/\nsum(rate(coredns_dns_request_count_total{node=~\"$node\"}[$__interval_rv]))",
       "legendFormat": "TCP"
      },
      {
       "expr": "sum(rate(coredns_dns_request_count_total{node=~\"$node\",proto=\"udp\"}[$__interval_rv]))\n/\nsum(rate(coredns_dns_request_count_total{node=~\"$node\"}[$__interval_rv]))",
       "legendFormat": "UDP"
      }
     ]
    },
    {
     "title": "Cache hit rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_cache_hits_total{node=~\"$node\"}[$__interval_rv]))\n/\n(\nsum(rate(coredns_cache_hits_total{node=~\"$node\"}[$__interval_rv])) +\nsum(rate(coredns_cache_misses_total{node=~\"$node\"}[$__interval_rv]))\n)"
      }
     ]
    },
    {
     "title": "Cache size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(max_over_time(coredns_cache_size{node=~\"$node\"}[$__interval_rv])) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(max_over_time(coredns_cache_size{node=~\"$node\"}[$__interval_rv]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Requests (by zone)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_request_count_total{node=~\"$node\"}[$__interval_rv])) by (zone)",
       "legendFormat": "{{zone}}"
      },
      {
       "expr": "sum(rate(coredns_dns_request_count_total{node=~\"node\"}[$__interval_rv]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Request duration",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_request_duration_seconds_bucket{node=~\"$node\"}[$__interval_rv])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Forward duration",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_request_duration_seconds_bucket{node=~\"$node\"}[$__interval_rv])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstream $upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "repeat": "upstream",
   "collapsed": true,
   "panels": [
    {
     "title": "Forwarded requests count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_request_count_total{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(coredns_forward_request_count_total{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv])) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Forwarded requests count (by rcode)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_response_rcode_count_total{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv])) by (rcode)",
       "legendFormat": "{{rcode}}"
      },
      {
       "expr": "sum(rate(coredns_forward_response_rcode_count_total{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Forward duration",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 94 },
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_request_duration_seconds_bucket{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstream $upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Forwarded requests count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_request_count_total{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(coredns_forward_request_count_total{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv])) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Forwarded requests count (by rcode)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_response_rcode_count_total{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv])) by (rcode)",
       "legendFormat": "{{rcode}}"
      },
      {
       "expr": "sum(rate(coredns_forward_response_rcode_count_total{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Forward duration",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 94 },
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_request_duration_seconds_bucket{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstream $upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Forwarded requests count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_request_count_total{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(coredns_forward_request_count_total{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv])) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Forwarded requests count (by rcode)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_response_rcode_count_total{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv])) by (rcode)",
       "legendFormat": "{{rcode}}"
      },
      {
       "expr": "sum(rate(coredns_forward_response_rcode_count_total{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Forward duration",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 94 },
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_request_duration_seconds_bucket{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstream $upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Forwarded requests count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_request_count_total{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(coredns_forward_request_count_total{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv])) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Forwarded requests count (by rcode)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_response_rcode_count_total{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv])) by (rcode)",
       "legendFormat": "{{rcode}}"
      },
      {
       "expr": "sum(rate(coredns_forward_response_rcode_count_total{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Forward duration",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 94 },
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_request_duration_seconds_bucket{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstream $upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Forwarded requests count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_request_count_total{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(coredns_forward_request_count_total{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv])) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Forwarded requests count (by rcode)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_response_rcode_count_total{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv])) by (rcode)",
       "legendFormat": "{{rcode}}"
      },
      {
       "expr": "sum(rate(coredns_forward_response_rcode_count_total{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Forward duration",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 94 },
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_request_duration_seconds_bucket{node=~\"$node\", to=~\"$upstream\"}[$__interval_rv])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}