{
 "title": "Nodes ping",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "source_node",
    "label": "Source",
    "query": "label_values(kube_node_ping_packets_sent_total, node)"
   },
   {
    "name": "destination_node",
    "label": "Destination",
    "query": "label_values(kube_node_ping_packets_sent_total, node)"
   }
  ]
 },
 "panels": [
  { "title": "From all nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "description": "Средние значения измерений, сгруппированные по целям ping запросов",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
    },
    {
     "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
    },
    {
     "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Average mean RTT with min/max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
     "legendFormat": "RTT"
    },
    {
     "expr": "max (max_over_time(kube_node_ping_rtt_max{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
     "legendFormat": "RTT max"
    },
    {
     "expr": "min (min_over_time(kube_node_ping_rtt_min{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
     "legendFormat": "RTT min"
    }
   ]
  },
  {
   "title": "Mean packet loss",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "( \n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
     "legendFormat": "{{destination_node}}"
    }
   ]
  },
  {
   "title": "Mean RTT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
     "legendFormat": "{{destination_node}}"
    }
   ]
  },
  {
   "title": "Mean deviation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
     "legendFormat": "{{destination_node}}"
    }
   ]
  },
  {
   "title": "From $source_node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "source_node",
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Средние значения измерений, сгруппированные по источникам ping запросов",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
      },
      {
       "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))"
      },
      {
       "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Average mean RTT with min/max",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "RTT"
      },
      {
       "expr": "max (max_over_time(kube_node_ping_rtt_max{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "RTT max"
      },
      {
       "expr": "min (min_over_time(kube_node_ping_rtt_min{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "RTT min"
      }
     ]
    },
    {
     "title": "Mean packet loss",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    },
    {
     "title": "Mean RTT",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    },
    {
     "title": "Mean deviation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "From $source_node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Средние значения измерений, сгруппированные по источникам ping запросов",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
      },
      {
       "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))"
      },
      {
       "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Average mean RTT with min/max",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "RTT"
      },
      {
       "expr": "max (max_over_time(kube_node_ping_rtt_max{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "RTT max"
      },
      {
       "expr": "min (min_over_time(kube_node_ping_rtt_min{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "RTT min"
      }
     ]
    },
    {
     "title": "Mean packet loss",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    },
    {
     "title": "Mean RTT",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    },
    {
     "title": "Mean deviation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "From $source_node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Средние значения измерений, сгруппированные по источникам ping запросов",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
      },
      {
       "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))"
      },
      {
       "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Average mean RTT with min/max",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "RTT"
      },
      {
       "expr": "max (max_over_time(kube_node_ping_rtt_max{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "RTT max"
      },
      {
       "expr": "min (min_over_time(kube_node_ping_rtt_min{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "RTT min"
      }
     ]
    },
    {
     "title": "Mean packet loss",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    },
    {
     "title": "Mean RTT",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    },
    {
     "title": "Mean deviation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "From $source_node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Средние значения измерений, сгруппированные по источникам ping запросов",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
      },
      {
       "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))"
      },
      {
       "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Average mean RTT with min/max",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "RTT"
      },
      {
       "expr": "max (max_over_time(kube_node_ping_rtt_max{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "RTT max"
      },
      {
       "expr": "min (min_over_time(kube_node_ping_rtt_min{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "RTT min"
      }
     ]
    },
    {
     "title": "Mean packet loss",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    },
    {
     "title": "Mean RTT",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    },
    {
     "title": "Mean deviation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "From $source_node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Средние значения измерений, сгруппированные по источникам ping запросов",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
      },
      {
       "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))"
      },
      {
       "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Average mean RTT with min/max",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "RTT"
      },
      {
       "expr": "max (max_over_time(kube_node_ping_rtt_max{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "RTT max"
      },
      {
       "expr": "min (min_over_time(kube_node_ping_rtt_min{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "RTT min"
      }
     ]
    },
    {
     "title": "Mean packet loss",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    },
    {
     "title": "Mean RTT",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    },
    {
     "title": "Mean deviation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "From $source_node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Средние значения измерений, сгруппированные по источникам ping запросов",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
      },
      {
       "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))"
      },
      {
       "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Average mean RTT with min/max",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "RTT"
      },
      {
       "expr": "max (max_over_time(kube_node_ping_rtt_max{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "RTT max"
      },
      {
       "expr": "min (min_over_time(kube_node_ping_rtt_min{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "RTT min"
      }
     ]
    },
    {
     "title": "Mean packet loss",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    },
    {
     "title": "Mean RTT",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    },
    {
     "title": "Mean deviation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "From $source_node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Средние значения измерений, сгруппированные по источникам ping запросов",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
      },
      {
       "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))"
      },
      {
       "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Average mean RTT with min/max",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "RTT"
      },
      {
       "expr": "max (max_over_time(kube_node_ping_rtt_max{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "RTT max"
      },
      {
       "expr": "min (min_over_time(kube_node_ping_rtt_min{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "RTT min"
      }
     ]
    },
    {
     "title": "Mean packet loss",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    },
    {
     "title": "Mean RTT",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    },
    {
     "title": "Mean deviation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "From $source_node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Средние значения измерений, сгруппированные по источникам ping запросов",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
      },
      {
       "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))"
      },
      {
       "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Average mean RTT with min/max",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "RTT"
      },
      {
       "expr": "max (max_over_time(kube_node_ping_rtt_max{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "RTT max"
      },
      {
       "expr": "min (min_over_time(kube_node_ping_rtt_min{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "RTT min"
      }
     ]
    },
    {
     "title": "Mean packet loss",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    },
    {
     "title": "Mean RTT",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    },
    {
     "title": "Mean deviation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "From $source_node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Средние значения измерений, сгруппированные по источникам ping запросов",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
      },
      {
       "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))"
      },
      {
       "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Average mean RTT with min/max",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "RTT"
      },
      {
       "expr": "max (max_over_time(kube_node_ping_rtt_max{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "RTT max"
      },
      {
       "expr": "min (min_over_time(kube_node_ping_rtt_min{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "RTT min"
      }
     ]
    },
    {
     "title": "Mean packet loss",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    },
    {
     "title": "Mean RTT",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    },
    {
     "title": "Mean deviation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "From $source_node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Средние значения измерений, сгруппированные по источникам ping запросов",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
      },
      {
       "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))"
      },
      {
       "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Average mean RTT with min/max",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "RTT"
      },
      {
       "expr": "max (max_over_time(kube_node_ping_rtt_max{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "RTT max"
      },
      {
       "expr": "min (min_over_time(kube_node_ping_rtt_min{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "RTT min"
      }
     ]
    },
    {
     "title": "Mean packet loss",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    },
    {
     "title": "Mean RTT",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    },
    {
     "title": "Mean deviation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "From $source_node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Средние значения измерений, сгруппированные по источникам ping запросов",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
      },
      {
       "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))"
      },
      {
       "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Average mean RTT with min/max",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "RTT"
      },
      {
       "expr": "max (max_over_time(kube_node_ping_rtt_max{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "RTT max"
      },
      {
       "expr": "min (min_over_time(kube_node_ping_rtt_min{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "RTT min"
      }
     ]
    },
    {
     "title": "Mean packet loss",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    },
    {
     "title": "Mean RTT",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_received_total{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval_rv]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    },
    {
     "title": "Mean deviation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{node=~\"$source_node\", destination_node=~\"$destination_node\"}[$__interval]))",
       "legendFormat": "{{destination_node}}"
      }
     ]
    }
   ]
  }
 ]
}