{
 "title": "Nodes",
 "description": "Dashboard to get an overview of one server",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(up{job=\"node-exporter\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Idle cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (rate(node_cpu{mode=\"idle\", node=\"$node\"}[$__interval_rv])) * 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load1{node=\"$node\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{node=\"$node\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{node=\"$node\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{node=\"$node\"} - node_memory_MemFree{node=\"$node\"} - node_memory_Buffers{node=\"$node\"} - node_memory_Cached{node=\"$node\"}",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers{node=\"$node\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached{node=\"$node\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree{node=\"$node\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((node_memory_MemTotal{node=\"$node\"} - node_memory_MemFree{node=\"$node\"}  - node_memory_Buffers{node=\"$node\"} - node_memory_Cached{node=\"$node\"}) / node_memory_MemTotal{node=\"$node\"}) * 100"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (rate(node_disk_bytes_read{node=\"$node\"}[$__interval_rv]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (node) (rate(node_disk_bytes_written{node=\"$node\"}[$__interval_rv]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum by (node) (rate(node_disk_io_time_ms{node=\"$node\"}[$__interval_rv]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size{device!=\"rootfs\",node=\"$node\"}) - sum(node_filesystem_free{device!=\"rootfs\",node=\"$node\"})) / sum(node_filesystem_size{device!=\"rootfs\",node=\"$node\"})"
    }
   ]
  },
  {
   "title": "Network received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes{node=\"$node\",device!~\"lo\"}[$__interval_rv])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes{node=\"$node\",device!~\"lo\"}[$__interval_rv])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}