#!/bin/bash
# Copyright 2024 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

d8_share_ca_dir="/opt/deckhouse/share/ca-certificates/mozilla"

set -Eeo pipefail

if [ -d "$d8_share_ca_dir" ]; then
  #Delete certificates from previous version
  find "$d8_share_ca_dir" -name '*.crt' -exec rm -rf {} +

  if [ -d "/etc/pki/ca-trust/source/anchors" ]; then
    find "/etc/pki/ca-trust/source/anchors" -type l -lname "$d8_share_ca_dir/*.crt" -exec rm -f {} + 
  fi
  if [ -d "/usr/local/share/ca-certificates" ]; then
    find "/usr/local/share/ca-certificates" -type l -lname "$d8_share_ca_dir/*.crt" -exec rm -f {} + 
  fi
fi

mkdir -p /opt/deckhouse/bin "$d8_share_ca_dir"/ca-bundle
cp -f d8-ca-updater /opt/deckhouse/bin
cp certs/* "$d8_share_ca_dir"/
cp -f ca-bundle.crt "$d8_share_ca_dir"/ca-bundle/ca-certificates.crt

/opt/deckhouse/bin/d8-ca-updater
