#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  echo '
{
  "beforeHelm": 10
}'
}

function __main__() {
### Миграция 2019-09-17 переезд из kube-system в d8-user-authz
### Helm глючит и не удаляет ресурсы в старом ns
### Важно запустить эту миграцию после gen-webhook-cert
  kubectl -n kube-system delete secret user-authz-webhook > /dev/null 2> /dev/null || true
  kubectl -n kube-system delete cm user-authz-webhook > /dev/null 2> /dev/null || true
  kubectl -n kube-system delete vpa user-authz-webhook > /dev/null 2> /dev/null || true
  kubectl -n kube-system delete ds user-authz-webhook > /dev/null 2> /dev/null || true
  kubectl -n kube-system delete vpa user-authz-webhook-configurator > /dev/null 2> /dev/null || true
  kubectl -n kube-system delete ds user-authz-webhook-configurator > /dev/null 2> /dev/null || true
}

hook::run "$@"
