{
 "title": "NATS Legacy",
 "description": "NATS Server Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(nats_up, namespace)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(nats_up{namespace=~\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(nats_up{namespace=~\"$namespace\", service=~\"$service\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Routes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nats_routes{namespace=~\"$namespace\", service=~\"$service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "OS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Server CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nats_cpu{namespace=~\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Server Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nats_mem{namespace=~\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Bytes In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nats_bytes_in{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "NATS Msgs In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nats_msgs_in{namespace=~\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nats_bytes_out{namespace=~\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "NATS Msgs Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nats_msgs_out{namespace=~\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Client Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nats_connections{namespace=~\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Subscriptions Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nats_subscriptions_total{namespace=~\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Slow Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nats_slow_consumers{namespace=~\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}