{
 "title": "NATS",
 "description": "NATS Server Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(up{job=\"nats\"}, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "OS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "gnatsd_varz_cpu{namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace }}-{{pod}}"
    }
   ]
  },
  {
   "title": "Server Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "gnatsd_varz_mem{namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace }}-{{pod}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Bytes In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "gnatsd_varz_in_bytes{namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace }}-{{pod}}"
    }
   ]
  },
  {
   "title": "NATS Msgs In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gnatsd_varz_in_msgs{namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace }}-{{pod}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "gnatsd_varz_out_bytes{namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace }}-{{pod}}"
    }
   ]
  },
  {
   "title": "NATS Msgs Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gnatsd_varz_out_msgs{namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace }}-{{pod}}"
    }
   ]
  },
  { "title": "Client Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gnatsd_varz_connections{namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace }}-{{pod}}"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gnatsd_varz_subscriptions{namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace }}-{{pod}}"
    }
   ]
  },
  {
   "title": "Slow Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gnatsd_varz_slow_consumers{namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace }}-{{pod}}"
    }
   ]
  }
 ]
}