// Copyright 2025 Flant JSC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/deckhouse/deckhouse/deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ApplicationPackageLister helps list ApplicationPackages.
// All objects returned here must be treated as read-only.
type ApplicationPackageLister interface {
	// List lists all ApplicationPackages in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ApplicationPackage, err error)
	// Get retrieves the ApplicationPackage from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ApplicationPackage, error)
	ApplicationPackageListerExpansion
}

// applicationPackageLister implements the ApplicationPackageLister interface.
type applicationPackageLister struct {
	indexer cache.Indexer
}

// NewApplicationPackageLister returns a new ApplicationPackageLister.
func NewApplicationPackageLister(indexer cache.Indexer) ApplicationPackageLister {
	return &applicationPackageLister{indexer: indexer}
}

// List lists all ApplicationPackages in the indexer.
func (s *applicationPackageLister) List(selector labels.Selector) (ret []*v1alpha1.ApplicationPackage, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ApplicationPackage))
	})
	return ret, err
}

// Get retrieves the ApplicationPackage from the index for a given name.
func (s *applicationPackageLister) Get(name string) (*v1alpha1.ApplicationPackage, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("applicationpackage"), name)
	}
	return obj.(*v1alpha1.ApplicationPackage), nil
}
