{{- $providerID := "yandex" }}
{{- define "registration_values" }}
{{- $context := index . 0 }}
# obligatory
type: {{ b64enc "yandex" | quote }}
region: {{ $context.Values.cloudProviderYandex.internal.providerDiscoveryData.region | b64enc | quote }}
zones: {{ $context.Values.cloudProviderYandex.internal.providerDiscoveryData.zones | toJson | b64enc | quote }}
instanceClassKind: {{ b64enc "YandexInstanceClass" | quote }}
machineClassKind: {{ b64enc "YandexMachineClass" | quote }}
capiClusterKind: {{ b64enc "YandexCluster" | quote }}
capiClusterAPIVersion: {{ b64enc "infrastructure.cluster.x-k8s.io/v1alpha1" | quote }}
capiClusterAPIGroup: {{ b64enc "infrastructure.cluster.x-k8s.io" | quote }}
capiClusterName: {{ b64enc "yandex" | quote }}
capiMachineTemplateKind: {{ b64enc "YandexMachineTemplate" | quote }}
capiMachineTemplateAPIVersion: {{ b64enc "infrastructure.cluster.x-k8s.io/v1alpha1" | quote }}
capiMachineTemplateAPIGroup: {{ b64enc "infrastructure.cluster.x-k8s.io" | quote }}
sshPublicKey: {{ $context.Values.cloudProviderYandex.internal.providerClusterConfiguration.sshPublicKey | b64enc | quote }}

# Yandex
{{- $yandexValues := dict }}
{{- $_ := set $yandexValues "serviceAccountJSON" $context.Values.cloudProviderYandex.internal.providerClusterConfiguration.provider.serviceAccountJSON }}
{{- $_ := set $yandexValues "region" $context.Values.cloudProviderYandex.internal.providerDiscoveryData.region }}
{{- $_ := set $yandexValues "folderID" $context.Values.cloudProviderYandex.internal.providerClusterConfiguration.provider.folderID }}
{{- $_ := set $yandexValues "sshKey" $context.Values.cloudProviderYandex.internal.providerClusterConfiguration.sshPublicKey }}
{{- $_ := set $yandexValues "shouldAssignPublicIPAddress" $context.Values.cloudProviderYandex.internal.providerDiscoveryData.shouldAssignPublicIPAddress }}
{{- $_ := set $yandexValues "zoneToSubnetIdMap" $context.Values.cloudProviderYandex.internal.providerDiscoveryData.zoneToSubnetIdMap }}
{{- $_ := set $yandexValues "labels" ($context.Values.cloudProviderYandex.internal.providerClusterConfiguration.labels | default dict) }}
{{- $_ := set $yandexValues "nodeNetworkCIDR" $context.Values.cloudProviderYandex.internal.providerClusterConfiguration.nodeNetworkCIDR }}

{{- $_ := set $yandexValues "instanceClassDefaults" dict }}
{{- $_ := set $yandexValues.instanceClassDefaults "imageID" $context.Values.cloudProviderYandex.internal.providerClusterConfiguration.masterNodeGroup.instanceClass.imageID }}
yandex: {{ $yandexValues | toJson | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: d8-node-manager-cloud-provider
  namespace: kube-system
  {{- include "helm_lib_module_labels" (list . (dict
    "cloud-provider.deckhouse.io/registration" ""
    "cloud-provider.deckhouse.io/name" $providerID
    )) | nindent 2 }}
type: Opaque
data: {{- include "registration_values" (list . ) | nindent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "d8-node-manager-cloud-provider-%s" $providerID }}
  namespace: kube-system
  {{- include "helm_lib_module_labels" (list . (dict
    "cloud-provider.deckhouse.io/registration" ""
    "cloud-provider.deckhouse.io/name" $providerID
    )) | nindent 2 }}
type: Opaque
data: {{- include "registration_values" (list . ) | nindent 2 }}
