#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    afterHelm: 10
EOF
}

function __main__() {
  if values::has dashboard.internal.deployDexAuthenticator ; then
    cat <<EOF | kubectl apply -f -
apiVersion: deckhouse.io/v1alpha1
kind: DexAuthenticator
metadata:
 name: dashboard
 namespace: d8-dashboard
 labels:
   heritage: deckhouse
   module: dashboard
   app: dex-authenticator
 annotations:
   dexauthenticator.deckhouse.io/allow-access-to-kubernetes: "true"
spec:
  applicationDomain: "$(module::public_domain dashboard)"
  sendAuthorizationHeader: true
  applicationIngressCertificateSecretName: "ingress-tls"
  applicationIngressClassName: "$(module::ingress_class)"
EOF
  else
    if kubectl -n d8-dashboard get dexauthenticator dashboard >/dev/null 2>/dev/null ; then
      kubectl -n d8-dashboard delete dexauthenticator dashboard >/dev/null 2>/dev/null
    fi
  fi
}

hook::run "$@"
