#!/bin/bash

# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /deckhouse/shell_lib.sh

function __config__() {
  cat <<EOF
    configVersion: v1
    afterHelm: 10
EOF
}

function __main__() {
  if values::has dashboard.internal.deployDexAuthenticator; then
    cat <<EOF | kubectl apply -f -
apiVersion: deckhouse.io/v1
kind: DexAuthenticator
metadata:
 name: dashboard
 namespace: d8-dashboard
 labels:
   heritage: deckhouse
   module: dashboard
   app: dex-authenticator
 annotations:
   dexauthenticator.deckhouse.io/allow-access-to-kubernetes: "true"
spec:
  applicationDomain: "$(module::public_domain dashboard)"
  sendAuthorizationHeader: true
  applicationIngressCertificateSecretName: "$(module::https_secret_name "ingress-tls")"
  applicationIngressClassName: "$(module::ingress_class)"
  signOutURL: "/logout"
EOF
  else
    if kubectl -n d8-dashboard get dexauthenticator dashboard >/dev/null 2>/dev/null; then
      kubectl -n d8-dashboard delete dexauthenticator dashboard >/dev/null 2>/dev/null
    fi
  fi
}

hook::run "$@"
