#!/bin/bash

# Во многих кластерах LE забанил домен дашборды. Это — решение для временного домена dashboard-tmp.mycluster.net

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  jo -p afterHelm=10
}

function __main__() {
  if values::has dashboard.internal.deployDexAuthenticator ; then
    cat <<EOF | kubectl apply -f -
apiVersion: deckhouse.io/v1alpha1
kind: DexAuthenticator
metadata:
 name: dashboard-tmp
 namespace: d8-dashboard
 labels:
   heritage: deckhouse
   module: dashboard
   app: dex-authenticator
 annotations:
   dex-authenticator.deckhouse.io/allow-access-to-kubernetes: "true"
spec:
  applicationDomain: "$(common::module_public_domain dashboard-tmp)"
  sendAuthorizationHeader: true
  applicationIngressCertificateSecretName: "ingress-tls-tmp"
  applicationIngressClassName: "$(common::module_ingress_class)"
EOF
  fi
}

hook::run "$@"
