#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  jo -p afterHelm=10
}

function __main__() {
  if values::has dashboard.internal.deployDexAuthenticator ; then
    cat <<EOF | kubectl apply -f -
apiVersion: deckhouse.io/v1alpha1
kind: DexAuthenticator
metadata:
 name: dashboard
 namespace: d8-dashboard
 labels:
   heritage: deckhouse
   module: dashboard
   app: dex-authenticator
 annotations:
   dex-authenticator.deckhouse.io/use-kubernetes-app-key: "true"
spec:
  applicationDomain: "$(common::module_public_domain dashboard)"
  sendAuthorizationHeader: true
  applicationIngressCertificateSecretName: "ingress-tls"
  applicationIngressClassName: "$(common::module_ingress_class)"
EOF
  else
    if kubectl -n d8-dashboard get dex-authenticator dashboard >/dev/null 2>/dev/null ; then
      kubectl -n d8-dashboard delete dex-authenticator dashboard >/dev/null 2>/dev/null
    fi
  fi
}

hook::run "$@"
