#!/bin/bash

### Миграция 2019-09-20
# Удалить хук после переезда dashboard в неймспейс d8-dashboard

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    afterHelm: 10
    kubernetes:
    - name: secret
      queue: /modules/$(module::name::kebab_case)/migrate_dex_certificate
      apiVersion: v1
      kind: Secret
      watchEvent: [Added, Modified]
      namespace:
        nameSelector:
          matchNames: [kube-system]
      nameSelector:
        matchNames: [ingress-tls]
EOF
}


function __on_kubernetes::secret::synchronization() {
  # Это ради сохранения legacy-логики
  return 0
}

function __main__() {
  if ! values::array_has global.enabledModules "user-authn"; then
    return 0
  fi

  if [[ "$(values::get dashboard.version)" == "2" ]]; then
    return 0
  fi

  if kubectl -n kube-system get secret ingress-tls > /dev/null 2>&1 ; then
    kubectl -n kube-system get secret ingress-tls -o json | jq '.metadata.namespace = "d8-dashboard"' | kubernetes::replace_or_create_json
  fi
}

hook::run $@
