#!/bin/bash

# Copyright 2021 Flant CJSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 9
EOF
}

function __main__() {
  if values::array_has global.enabledModules "user-authn" && [[ $(values::get_first_defined dashboard.https.mode global.modules.https.mode) != "Disabled" ]]
  then
    if ! values::has --config dashboard.auth.externalAuthentication ; then
      values::set dashboard.auth.externalAuthentication '{}'
      values::set dashboard.auth.externalAuthentication.authURL "https://dashboard-dex-authenticator.d8-dashboard.svc.$(values::get global.discovery.clusterDomain)/dex-authenticator/auth"
      values::set dashboard.auth.externalAuthentication.authSignInURL 'https://$host/dex-authenticator/sign_in'
      values::set dashboard.auth.externalAuthentication.useBearerTokens "true"
      values::set dashboard.internal.deployDexAuthenticator "true"
    else
      values::unset dashboard.internal.deployDexAuthenticator
      values::set dashboard.auth.externalAuthentication "$(values::get --config dashboard.auth.externalAuthentication)"
    fi
  else
    if ! values::has --config dashboard.auth.externalAuthentication ; then
      values::unset dashboard.auth.externalAuthentication
    else
      values::set dashboard.auth.externalAuthentication "$(values::get --config dashboard.auth.externalAuthentication)"
    fi
    values::unset dashboard.internal.deployDexAuthenticator
  fi
}

hook::run $@
