#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 9
EOF
}

function __main__() {
  if values::array_has global.enabledModules "user-authn" && [[ $(values::get_first_defined dashboard.https.mode global.modules.https.mode) != "Disabled" ]]
  then
    if ! values::has --config dashboard.auth.externalAuthentication ; then
      values::set dashboard.auth.externalAuthentication '{}'
      values::set dashboard.auth.externalAuthentication.authURL "https://dashboard-dex-authenticator.d8-dashboard.svc.$(values::get global.discovery.clusterDomain)/dex-authenticator/auth"
      values::set dashboard.auth.externalAuthentication.authSignInURL 'https://$host/dex-authenticator/sign_in'
      values::set dashboard.auth.externalAuthentication.useBearerTokens "true"
      values::set dashboard.internal.deployDexAuthenticator "true"
    else
      values::unset dashboard.internal.deployDexAuthenticator
      values::set dashboard.auth.externalAuthentication "$(values::get --config dashboard.auth.externalAuthentication)"
    fi
  else
    if ! values::has --config dashboard.auth.externalAuthentication ; then
      values::unset dashboard.auth.externalAuthentication
    else
      values::set dashboard.auth.externalAuthentication "$(values::get --config dashboard.auth.externalAuthentication)"
    fi
    values::unset dashboard.internal.deployDexAuthenticator
  fi
}

hook::run $@
