// Copyright 2025 Flant JSC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/deckhouse/deckhouse/deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1"
	deckhouseiov1alpha1 "github.com/deckhouse/deckhouse/deckhouse-controller/pkg/client/clientset/versioned/typed/deckhouse.io/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakePackageRepositoryOperations implements PackageRepositoryOperationInterface
type fakePackageRepositoryOperations struct {
	*gentype.FakeClientWithList[*v1alpha1.PackageRepositoryOperation, *v1alpha1.PackageRepositoryOperationList]
	Fake *FakeDeckhouseV1alpha1
}

func newFakePackageRepositoryOperations(fake *FakeDeckhouseV1alpha1) deckhouseiov1alpha1.PackageRepositoryOperationInterface {
	return &fakePackageRepositoryOperations{
		gentype.NewFakeClientWithList[*v1alpha1.PackageRepositoryOperation, *v1alpha1.PackageRepositoryOperationList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("packagerepositoryoperations"),
			v1alpha1.SchemeGroupVersion.WithKind("PackageRepositoryOperation"),
			func() *v1alpha1.PackageRepositoryOperation { return &v1alpha1.PackageRepositoryOperation{} },
			func() *v1alpha1.PackageRepositoryOperationList { return &v1alpha1.PackageRepositoryOperationList{} },
			func(dst, src *v1alpha1.PackageRepositoryOperationList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.PackageRepositoryOperationList) []*v1alpha1.PackageRepositoryOperation {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.PackageRepositoryOperationList, items []*v1alpha1.PackageRepositoryOperation) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
