// Copyright 2025 Flant JSC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/deckhouse/deckhouse/deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeModuleConfigs implements ModuleConfigInterface
type FakeModuleConfigs struct {
	Fake *FakeDeckhouseV1alpha1
}

var moduleconfigsResource = v1alpha1.SchemeGroupVersion.WithResource("moduleconfigs")

var moduleconfigsKind = v1alpha1.SchemeGroupVersion.WithKind("ModuleConfig")

// Get takes name of the moduleConfig, and returns the corresponding moduleConfig object, and an error if there is any.
func (c *FakeModuleConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ModuleConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(moduleconfigsResource, name), &v1alpha1.ModuleConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ModuleConfig), err
}

// List takes label and field selectors, and returns the list of ModuleConfigs that match those selectors.
func (c *FakeModuleConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ModuleConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(moduleconfigsResource, moduleconfigsKind, opts), &v1alpha1.ModuleConfigList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ModuleConfigList{ListMeta: obj.(*v1alpha1.ModuleConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.ModuleConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested moduleConfigs.
func (c *FakeModuleConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(moduleconfigsResource, opts))
}

// Create takes the representation of a moduleConfig and creates it.  Returns the server's representation of the moduleConfig, and an error, if there is any.
func (c *FakeModuleConfigs) Create(ctx context.Context, moduleConfig *v1alpha1.ModuleConfig, opts v1.CreateOptions) (result *v1alpha1.ModuleConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(moduleconfigsResource, moduleConfig), &v1alpha1.ModuleConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ModuleConfig), err
}

// Update takes the representation of a moduleConfig and updates it. Returns the server's representation of the moduleConfig, and an error, if there is any.
func (c *FakeModuleConfigs) Update(ctx context.Context, moduleConfig *v1alpha1.ModuleConfig, opts v1.UpdateOptions) (result *v1alpha1.ModuleConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(moduleconfigsResource, moduleConfig), &v1alpha1.ModuleConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ModuleConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeModuleConfigs) UpdateStatus(ctx context.Context, moduleConfig *v1alpha1.ModuleConfig, opts v1.UpdateOptions) (*v1alpha1.ModuleConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(moduleconfigsResource, "status", moduleConfig), &v1alpha1.ModuleConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ModuleConfig), err
}

// Delete takes name of the moduleConfig and deletes it. Returns an error if one occurs.
func (c *FakeModuleConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(moduleconfigsResource, name, opts), &v1alpha1.ModuleConfig{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeModuleConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(moduleconfigsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ModuleConfigList{})
	return err
}

// Patch applies the patch and returns the patched moduleConfig.
func (c *FakeModuleConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ModuleConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(moduleconfigsResource, name, pt, data, subresources...), &v1alpha1.ModuleConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ModuleConfig), err
}
