apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    heritage: deckhouse
    module: log-shipper
    rbac.deckhouse.io/aggregate-to-observability-as: viewer
    rbac.deckhouse.io/kind: capability
    rbac.deckhouse.io/capability: "system-capability.log-shipper.view"
    rbac.deckhouse.io/scope: system
    rbac.deckhouse.io/namespace: d8-log-shipper
  name: d8:system-capability:log-shipper:view
  annotations:
    en.meta.deckhouse.io/title: "Module log-shipper: view configuration"
    ru.meta.deckhouse.io/title: "Модуль log-shipper: просмотр конфигурации"
    en.meta.deckhouse.io/description: "Read-only access to the log-shipper module configuration."
    ru.meta.deckhouse.io/description: "Доступ только на чтение к конфигурации модуля log-shipper."
rules:
- apiGroups:
  - deckhouse.io
  resources:
  - clusterlogdestinations
  - clusterloggingconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deckhouse.io
  resourceNames:
  - log-shipper
  resources:
  - moduleconfigs
  verbs:
  - get
  - list
  - watch
