stages:
  - .pre
  - validate
  - build
  - test
  - deploy
  - e2e-ensure-build
  - e2e-prestart
  - e2e-create
  - e2e-update-deckhouse
  - e2e-tests
  - e2e-delete
  - .post

include:
  - .gitlab/*.yml

variables:
  CI_IMAGES_TAG: "8998a9af"

default:
  tags:
    - k8s-intteam-cloud-d8-ssdlc-runner
  interruptible: true
