[extend]
useDefault = false
path = "gitleaks.base.toml"

[allowlist]
regexes = [
  'kubernetesCni162'
]
paths = [
  'docs/site/_includes/getting_started/global/partials/installer/installer-steps-bare-metal.html',
]
