stages:
  - .pre
  - validate
  - build
  - test
  - deploy
  - .post

include:
  - .gitlab/**.yml

variables:
  CI_IMAGES_TAG: "2ca19f3f"

default:
  tags:
    - k8s-intteam-cloud-d8-ssdlc-runner
  interruptible: true
