#!/bin/bash

### Миграция 2019-08-02: https://github.com/deckhouse/deckhouse/merge_requests/978
#
# Этот хук можно удалить, после выката данного MR'а на все инсталяции.

source /antiopa/shell_lib.sh

function __config__() {
  jo -p onStartup=1
}

function __main__() {
  if values::has --config global.ingressClass ; then
    if ! values::has --config global.modules ; then
      values::set --config global.modules "{}"
    fi
    if ! values::has --config global.modules.ingressClass ; then
      values::set --config global.modules.ingressClass "$(values::get --config global.ingressClass)"
    fi

    values::unset --config global.ingressClass
  fi
}

hook::run $@
