#!/bin/bash

### Миграция 2019-09-12: https://github.com/deckhouse/deckhouse/merge_requests/1125
# Этот хук можно удалить, после выката данного MR'а на все инсталяции.

source /antiopa/shell_lib.sh

function __config__() {
  jo -p onStartup=1
}

function __main__() {
  if values::has --config global.modules.https.mode ; then
    https_mode=$(values::get --config global.modules.https.mode)
    if [[ "$https_mode" == "UriOnly" ]] ; then
      values::set --config global.modules.https.mode "OnlyInURI"
    fi
  fi
}

hook::run "$@"
