{
 "title": "DocsBuilderMetrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Upload metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(docs_builder_upload_total{d8_source=\"dkp\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload duration sum - 10 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(pod, le) (docs_builder_upload_duration_seconds_bucket{d8_source=\"dkp\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delete metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(docs_builder_delete_total{d8_source=\"dkp\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delete metrics duration - 10 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(pod, le) (docs_builder_delete_duration_seconds_bucket{d8_source=\"dkp\"}))\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(docs_builder_build_total{d8_source=\"dkp\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build duration sum 10min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(pod, le) (docs_builder_build_duration_seconds_bucket{d8_source=\"dkp\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Builder cached modules",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "docs_builder_cached_modules{d8_source=\"dkp\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}