{
 "title": "Nodes",
 "description": "Dashboard to get an overview of one server",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(up{job=\"node-exporter\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Average",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_node_info{node=~\"$node\"}",
     "legendFormat": "Node name"
    },
    {
     "expr": "count by (node) (node_cpu_seconds_total{node=~\"$node\", mode=\"idle\"})",
     "legendFormat": "Cores"
    },
    {
     "expr": "sum by (node) (avg_over_time(node_load1{node=~\"$node\"}[$__range]))",
     "legendFormat": "Load Average"
    },
    {
     "expr": "100 - (avg by (node) (rate(node_cpu_seconds_total{node=~\"$node\", mode=\"idle\"}[$__interval_rv])) * 100 )",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum by (node) (avg_over_time(node_memory_MemTotal_bytes{node=~\"$node\"}[$__range]))",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum by (node) \n  (\n    avg_over_time(node_memory_MemTotal_bytes{node=~\"$node\"}[$__range])\n    -\n    avg_over_time(node_memory_MemFree_bytes{node=~\"$node\"}[$__range])\n    -\n    avg_over_time(node_memory_Buffers_bytes{node=~\"$node\"}[$__range])\n    -\n    avg_over_time(node_memory_Cached_bytes{node=~\"$node\"}[$__range])\n  )",
     "legendFormat": "Memory RSS"
    },
    {
     "expr": "sum by (node) (avg_over_time(node_memory_Cached_bytes{node=~\"$node\"}[$__range]) + avg_over_time(node_memory_Buffers_bytes{node=~\"$node\"}[$__range]))",
     "legendFormat": "Memory cached + bufeer"
    },
    {
     "expr": "sum by (node) (rate(node_network_receive_bytes_total{node=~\"$node\", device!~\"lo\"}[$__range]))",
     "legendFormat": "RX Network"
    },
    {
     "expr": "sum by (node) (rate(node_network_transmit_bytes_total{node=~\"$node\", device!~\"lo\"}[$__range]))",
     "legendFormat": "TX Network"
    },
    {
     "expr": "sum by (node) (rate(node_disk_read_bytes_total{node=~\"$node\"}[$__range]))",
     "legendFormat": "Read bytes"
    },
    {
     "expr": "sum by (node) (rate(node_disk_written_bytes_total{node=~\"$node\"}[$__range]))",
     "legendFormat": "Write bytes"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (node) (rate(node_cpu_seconds_total{node=~\"$node\", mode=\"idle\"}[$__interval_rv])) * 100 )",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (avg_over_time(node_load1{node=~\"$node\"}[$__interval]))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Load Average %",
   "type": "graph",
   "description": "На данном графике отображается нагрузка в % от количества ядер на ноде.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (avg_over_time(node_load1{node=~\"$node\"}[$__interval])) / count by (node) (node_cpu_seconds_total{node=~\"$node\", mode=\"idle\"}) * 100",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "$node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
     "repeat": "node",
     "yaxes": [
      { "format": "percent", "label": "cpu usage" }
     ],
     "targets": [
      {
       "expr": "sum by (mode) (rate(node_cpu_seconds_total{node=~\"$node\"}[$__interval_rv])) * 100",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "$node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
     "yaxes": [
      { "format": "percent", "label": "cpu usage" }
     ],
     "targets": [
      {
       "expr": "sum by (mode) (rate(node_cpu_seconds_total{node=~\"$node\"}[$__interval_rv])) * 100",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "$node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "percent", "label": "cpu usage" }
     ],
     "targets": [
      {
       "expr": "sum by (mode) (rate(node_cpu_seconds_total{node=~\"$node\"}[$__interval_rv])) * 100",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "$node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
     "yaxes": [
      { "format": "percent", "label": "cpu usage" }
     ],
     "targets": [
      {
       "expr": "sum by (mode) (rate(node_cpu_seconds_total{node=~\"$node\"}[$__interval_rv])) * 100",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "$node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "percent", "label": "cpu usage" }
     ],
     "targets": [
      {
       "expr": "sum by (mode) (rate(node_cpu_seconds_total{node=~\"$node\"}[$__interval_rv])) * 100",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "$node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
     "yaxes": [
      { "format": "percent", "label": "cpu usage" }
     ],
     "targets": [
      {
       "expr": "sum by (mode) (rate(node_cpu_seconds_total{node=~\"$node\"}[$__interval_rv])) * 100",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "$node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "percent", "label": "cpu usage" }
     ],
     "targets": [
      {
       "expr": "sum by (mode) (rate(node_cpu_seconds_total{node=~\"$node\"}[$__interval_rv])) * 100",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "$node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 32 },
     "yaxes": [
      { "format": "percent", "label": "cpu usage" }
     ],
     "targets": [
      {
       "expr": "sum by (mode) (rate(node_cpu_seconds_total{node=~\"$node\"}[$__interval_rv])) * 100",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "$node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "percent", "label": "cpu usage" }
     ],
     "targets": [
      {
       "expr": "sum by (mode) (rate(node_cpu_seconds_total{node=~\"$node\"}[$__interval_rv])) * 100",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "$node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 39 },
     "yaxes": [
      { "format": "percent", "label": "cpu usage" }
     ],
     "targets": [
      {
       "expr": "sum by (mode) (rate(node_cpu_seconds_total{node=~\"$node\"}[$__interval_rv])) * 100",
       "legendFormat": "{{ mode }}"
      }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory RSS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node) \n  (\n    avg_over_time(node_memory_MemTotal_bytes{node=~\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_MemFree_bytes{node=~\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Buffers_bytes{node=~\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Cached_bytes{node=~\"$node\"}[$__interval])\n  )",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory RSS %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (node) \n  (\n    avg_over_time(node_memory_MemTotal_bytes{node=~\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_MemFree_bytes{node=~\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Buffers_bytes{node=~\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Cached_bytes{node=~\"$node\"}[$__interval])\n  )\n/\nsum by (node) (avg_over_time(node_memory_MemTotal_bytes{node=~\"$node\"}[$__interval]))\n* 100",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "$node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
     "repeat": "node",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (node) (avg_over_time(node_memory_MemTotal_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_MemFree_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Free"
      },
      {
       "expr": "sum by (node) \n  (\n    avg_over_time(node_memory_MemTotal_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_MemFree_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Buffers_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Cached_bytes{node=\"$node\"}[$__interval])\n  )",
       "legendFormat": "RSS"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_Cached_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Cached"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_Buffers_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Buffered"
      }
     ]
    },
    {
     "title": "$node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (node) (avg_over_time(node_memory_MemTotal_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_MemFree_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Free"
      },
      {
       "expr": "sum by (node) \n  (\n    avg_over_time(node_memory_MemTotal_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_MemFree_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Buffers_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Cached_bytes{node=\"$node\"}[$__interval])\n  )",
       "legendFormat": "RSS"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_Cached_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Cached"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_Buffers_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Buffered"
      }
     ]
    },
    {
     "title": "$node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (node) (avg_over_time(node_memory_MemTotal_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_MemFree_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Free"
      },
      {
       "expr": "sum by (node) \n  (\n    avg_over_time(node_memory_MemTotal_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_MemFree_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Buffers_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Cached_bytes{node=\"$node\"}[$__interval])\n  )",
       "legendFormat": "RSS"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_Cached_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Cached"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_Buffers_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Buffered"
      }
     ]
    },
    {
     "title": "$node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (node) (avg_over_time(node_memory_MemTotal_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_MemFree_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Free"
      },
      {
       "expr": "sum by (node) \n  (\n    avg_over_time(node_memory_MemTotal_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_MemFree_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Buffers_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Cached_bytes{node=\"$node\"}[$__interval])\n  )",
       "legendFormat": "RSS"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_Cached_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Cached"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_Buffers_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Buffered"
      }
     ]
    },
    {
     "title": "$node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (node) (avg_over_time(node_memory_MemTotal_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_MemFree_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Free"
      },
      {
       "expr": "sum by (node) \n  (\n    avg_over_time(node_memory_MemTotal_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_MemFree_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Buffers_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Cached_bytes{node=\"$node\"}[$__interval])\n  )",
       "legendFormat": "RSS"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_Cached_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Cached"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_Buffers_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Buffered"
      }
     ]
    },
    {
     "title": "$node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (node) (avg_over_time(node_memory_MemTotal_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_MemFree_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Free"
      },
      {
       "expr": "sum by (node) \n  (\n    avg_over_time(node_memory_MemTotal_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_MemFree_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Buffers_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Cached_bytes{node=\"$node\"}[$__interval])\n  )",
       "legendFormat": "RSS"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_Cached_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Cached"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_Buffers_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Buffered"
      }
     ]
    },
    {
     "title": "$node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (node) (avg_over_time(node_memory_MemTotal_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_MemFree_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Free"
      },
      {
       "expr": "sum by (node) \n  (\n    avg_over_time(node_memory_MemTotal_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_MemFree_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Buffers_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Cached_bytes{node=\"$node\"}[$__interval])\n  )",
       "legendFormat": "RSS"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_Cached_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Cached"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_Buffers_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Buffered"
      }
     ]
    },
    {
     "title": "$node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (node) (avg_over_time(node_memory_MemTotal_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_MemFree_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Free"
      },
      {
       "expr": "sum by (node) \n  (\n    avg_over_time(node_memory_MemTotal_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_MemFree_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Buffers_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Cached_bytes{node=\"$node\"}[$__interval])\n  )",
       "legendFormat": "RSS"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_Cached_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Cached"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_Buffers_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Buffered"
      }
     ]
    },
    {
     "title": "$node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (node) (avg_over_time(node_memory_MemTotal_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_MemFree_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Free"
      },
      {
       "expr": "sum by (node) \n  (\n    avg_over_time(node_memory_MemTotal_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_MemFree_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Buffers_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Cached_bytes{node=\"$node\"}[$__interval])\n  )",
       "legendFormat": "RSS"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_Cached_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Cached"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_Buffers_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Buffered"
      }
     ]
    },
    {
     "title": "$node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (node) (avg_over_time(node_memory_MemTotal_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_MemFree_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Free"
      },
      {
       "expr": "sum by (node) \n  (\n    avg_over_time(node_memory_MemTotal_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_MemFree_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Buffers_bytes{node=\"$node\"}[$__interval])\n    -\n    avg_over_time(node_memory_Cached_bytes{node=\"$node\"}[$__interval])\n  )",
       "legendFormat": "RSS"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_Cached_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Cached"
      },
      {
       "expr": "sum by (node) (avg_over_time(node_memory_Buffers_bytes{node=\"$node\"}[$__interval]))",
       "legendFormat": "Buffered"
      }
     ]
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Disk read bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (rate(node_disk_read_bytes_total{node=~\"$node\"}[$__interval_rv]))",
     "legendFormat": "{{ node }} read bytes"
    }
   ]
  },
  {
   "title": "Disk written bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (rate(node_disk_written_bytes_total{node=~\"$node\"}[$__interval_rv]))",
     "legendFormat": "{{ node }} written bytes"
    },
    {}
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Network received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (rate(node_network_receive_bytes_total{node=~\"$node\",device!~\"lo\"}[$__interval_rv]))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Network transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (rate(node_network_transmit_bytes_total{node=~\"$node\",device!~\"lo\"}[$__interval_rv]))",
     "legendFormat": "{{ node }}"
    }
   ]
  }
 ]
}