---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: public-service-valid.deckhouse.io
  {{- include "helm_lib_module_labels" (list $) | nindent 2 }}
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE", "UPDATE"]
        resources:   ["services"]
        scope:       "Namespaced"
    objectSelector:
      matchExpressions:
        - key: federation.istio.deckhouse.io/public-service
          operator: Exists
  variables:
    - name: portsWithoutName
      expression: "has(object.spec.ports) ? object.spec.ports.filter(p, !has(p.name)) : []"
  validations:
    - expression: "object.spec.type != 'ExternalName'"
      reason: Forbidden
      message: "A service labeled 'federation.istio.deckhouse.io/public-service' must not be of ExternalName type."
    - expression: "has(object.spec.ports)"
      reason: Forbidden
      message: "A service labeled 'federation.istio.deckhouse.io/public-service' must define the '.spec.ports' field."
    - expression: "variables.portsWithoutName.size() == 0"
      reason: Forbidden
      messageExpression: >
        "Port \"" + variables.portsWithoutName[0].protocol + " " + string(variables.portsWithoutName[0].port) +
        "\" of the service labeled 'federation.istio.deckhouse.io/public-service' has no 'name' field set. Please, define the port name " +
        "according to the following list of name suffixes supported by Istio: http, http2, https, tcp, tls, grpc, grpc-web."
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: public-service-valid.deckhouse.io
  {{- include "helm_lib_module_labels" (list $) | nindent 2 }}
spec:
  policyName: public-service-valid.deckhouse.io
  validationActions: [Deny]
