positive:
  values:
    - {}
  configValues:
    - {}
    - { allowNamespacesWithoutProjects: false }
    - { allowNamespacesWithoutProjects: true }
negative:
  configValues:
    - { somethingInConfig: yes }
    - { allowNamespacesWithoutProjects: "false" }
  values:
    - { somethingInConfig: yes }
