apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    heritage: deckhouse
    module: keepalived
    rbac.deckhouse.io/aggregate-to-infrastructure-as: manager
    rbac.deckhouse.io/kind: capability
    rbac.deckhouse.io/capability: "system-capability.keepalived.edit"
    rbac.deckhouse.io/scope: system
    rbac.deckhouse.io/namespace: d8-keepalived
  name: d8:system-capability:keepalived:edit
  annotations:
    en.meta.deckhouse.io/title: "Module keepalived: edit configuration"
    ru.meta.deckhouse.io/title: "Модуль keepalived: управление конфигурацией"
    en.meta.deckhouse.io/description: "Manage the keepalived module configuration."
    ru.meta.deckhouse.io/description: "Управление конфигурацией модуля keepalived."
rules:
- apiGroups:
  - deckhouse.io
  resources:
  - keepalivedinstances
  verbs:
  - create
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - deckhouse.io
  resourceNames:
  - keepalived
  resources:
  - moduleconfigs
  verbs:
  - create
  - update
  - patch
  - delete
