#!/bin/bash

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  jo -p afterHelm=10
}

function __main__() {
  if values::has openvpn.internal.deployDexAuthenticator ; then
    allowedGroups=""
    if values::has openvpn.auth.allowedUserGroups ; then
      allowedGroups="allowedGroups: $(values::get openvpn.auth.allowedUserGroups)"
    fi
    cat <<EOF | kubectl apply -f -
apiVersion: deckhouse.io/v1alpha1
kind: DexAuthenticator
metadata:
  name: openvpn
  namespace: kube-openvpn
  labels:
    heritage: deckhouse
    module: openvpn
    app: dex-authenticator
spec:
  applicationDomain: "$(common::module_public_domain openvpn-admin)"
  applicationIngressCertificateSecretName: "ingress-tls"
  applicationIngressClassName: "$(common::module_ingress_class)"
  $allowedGroups
EOF
  else
    if kubectl -n kube-openvpn get dex-authenticator openvpn >/dev/null 2>/dev/null ; then
      kubectl -n kube-openvpn delete dex-authenticator openvpn >/dev/null 2>/dev/null
    fi
  fi
}

hook::run "$@"
