#!/bin/bash

# Миграция 2019-09-17
# Удаляет не актуальные параметры dexAuthenticator из конфигураций модулей

source /deckhouse/shell_lib.sh

function __config__() {
  jo -p beforeHelm=10
}


function __main__() {
  if values::has --config openvpn.dexAuthenticator ; then
    values::unset --config openvpn.dexAuthenticator
  fi
}

hook::run "$@"
