#!/bin/bash

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  jo -p beforeHelm=9
}

function __main__() {
  if values::array_has global.enabledModules "user-authn" && [[ $(values::get_first_defined openvpn.https.mode global.modules.https.mode) != "Disabled" ]]; then
    if ! values::has --config openvpn.auth.externalAuthentication ; then
      values::set openvpn.auth.externalAuthentication '{}'
      values::set openvpn.auth.externalAuthentication.authURL "https://openvpn-dex-authenticator.kube-openvpn.svc.$(values::get global.discovery.clusterDomain)/dex-authenticator/auth"
      values::set openvpn.auth.externalAuthentication.authSignInURL 'https://$host/dex-authenticator/sign_in'
      values::set openvpn.internal.deployDexAuthenticator "true"
    else
      values::unset openvpn.internal.deployDexAuthenticator
      values::set openvpn.auth.externalAuthentication "$(values::get --config openvpn.auth.externalAuthentication)"
    fi
  else
    if ! values::has --config openvpn.auth.externalAuthentication ; then
      values::unset openvpn.auth.externalAuthentication
    else
      values::set openvpn.auth.externalAuthentication "$(values::get --config openvpn.auth.externalAuthentication)"
    fi
    values::unset openvpn.internal.deployDexAuthenticator
  fi
}

hook::run $@
