#!/bin/bash

# dependency: gamma
# dependency: epsilon

c=$(cat ${VALUES_PATH:-/dev/null} | jq .global.enabledModules[]  | grep -P '"gamma"|"epsilon"' | wc -l)
if [ "$c" == "2" ] ; then
  exit 0
fi

exit 1
