#!/bin/bash
# Copyright 2024 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -Eeo pipefail

# Stop/disable/remove old logrotate timer and service if they exist, now we use logpipe
# Delete this block after 1.73.1 CSE was released
systemctl stop containerd-deckhouse-logger-logrotate.timer 2>/dev/null || true
systemctl disable containerd-deckhouse-logger-logrotate.timer 2>/dev/null || true
systemctl stop containerd-deckhouse-logger-logrotate.service 2>/dev/null || true

rm -f /etc/systemd/system/containerd-deckhouse-logger-logrotate.timer
rm -f /etc/systemd/system/containerd-deckhouse-logger-logrotate.service
rm -f /etc/logrotate.d/containerd-integrity.conf
rm -f /var/lib/logrotate/containerd-deckhouse-logger-logrotate.status


mkdir -p /opt/deckhouse/bin
cp -f logpipe /opt/deckhouse/bin
