#!/bin/bash

source /deckhouse/shell_lib.sh

function __main__() {
  self_name=cloud-provider-vsphere
  if values::get global.enabledModules | jq '.[]' -r | grep -v -E '^'$self_name'$' | grep -E '^cloud-provider-[a-z-]+$' ; then
    >&2 echo "Unable to enable module $self_name: More than one cloud provider is enabled!"
    exit 1
  else
    echo "VsphereInstanceClass" > /tmp/cloud-instance-manager-instance-class-kind
    echo "true" > $MODULE_ENABLED_RESULT
  fi
}

hook::run $@
