{
 "title": "Namespace / Virtual Machine",
 "tags": [ "main" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(d8_virtualization_virtualmachine_status_phase,namespace)"
    }
   },
   {
    "name": "name",
    "label": "Machine name",
    "query": {
     "query": "label_values(d8_virtualization_virtualmachine_status_phase{namespace=\"$namespace\"},name)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(d8_virtualization_virtualmachine_network_receive_bytes_total{namespace=\"$namespace\", name=\"$name\"},network)"
    }
   },
   {
    "name": "mount_point",
    "label": "Mountpoint",
    "query": {
     "query": "label_values(d8_virtualization_virtualmachine_filesystem_capacity_bytes{namespace=\"$namespace\", name=\"$name\"},mount_point)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VM status ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) ((d8_virtualization_virtualmachine_status_phase{namespace=\"$namespace\", name=\"$name\"} == 1) * on(phase) group_left()\n    (\n      label_replace(vector(1), \"phase\", \"Degraded\", \"\", \"\") or\n      label_replace(vector(2), \"phase\", \"Migrating\", \"\", \"\") or\n      label_replace(vector(3), \"phase\", \"Pause\", \"\", \"\") or\n      label_replace(vector(4), \"phase\", \"Pending\", \"\", \"\") or\n      label_replace(vector(5), \"phase\", \"Running\", \"\", \"\") or\n      label_replace(vector(6), \"phase\", \"Starting\", \"\", \"\") or\n      label_replace(vector(7), \"phase\", \"Stopped\", \"\", \"\") or\n      label_replace(vector(8), \"phase\", \"Stopping\", \"\", \"\") or\n      label_replace(vector(9), \"phase\", \"Terminating\", \"\", \"\")\n    ))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Node name",
   "type": "stat",
   "description": "The node on which the VM is currently running",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "d8_virtualization_virtualmachine_pod{namespace=\"$namespace\", name=\"$name\"}==1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Instance CPU core count",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (namespace,name) (d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU core usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace,name) (rate(d8_virtualization_virtualmachine_cpu_usage_milliseconds_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval])) / 1000 \n/\n(\n    sum by (namespace,name) (d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"}) / 100\n)",
     "legendFormat": "OS Usage"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Instance memory",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (namespace,name) (d8_virtualization_virtualmachine_memory_size_bytes{namespace=\"$namespace\", name=\"$name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (namespace,name) (d8_virtualization_virtualmachine_os_memory_total_bytes - d8_virtualization_virtualmachine_os_memory_potentially_free_bytes{namespace=\"$namespace\", name=\"$name\"}) / (avg by (namespace,name) (d8_virtualization_virtualmachine_memory_size_bytes{namespace=\"$namespace\", name=\"$name\"}) / 100)",
     "legendFormat": "OS Usage"
    }
   ]
  },
  {
   "title": "Discs capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name, namespace) (\n  d8_virtualization_virtualmachine_filesystem_capacity_bytes{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\"}\n)\n",
     "legendFormat": "{{mount_point}}"
    }
   ]
  },
  {
   "title": "Total disks usage",
   "type": "gauge",
   "description": "This graph displays the total disk usage across all disks in the system as a percentage. It aggregates data from every filesystem, summing up used space and total capacity to provide an overall view of disk utilization. The calculation excludes temporary or cloud-init files to ensure accuracy.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name, namespace) (\n  d8_virtualization_virtualmachine_filesystem_used_bytes{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\"})\n/ \nsum by (name, namespace) (d8_virtualization_virtualmachine_filesystem_capacity_bytes / 100)\n\n",
     "legendFormat": "{{mount_point}}"
    }
   ]
  },
  {
   "title": "Agent",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (d8_virtualization_virtualmachine_agent_ready{namespace=\"$namespace\", name=\"$name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Configuration",
   "type": "stat",
   "description": "Whether the desired configuration is currently applied to a running VM",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (\n    last_over_time(\n        d8_virtualization_virtualmachine_configuration_applied{namespace=\"$namespace\", name=\"$name\"}[1m]\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Core usage in %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (namespace,name) (rate(d8_virtualization_virtualmachine_cpu_usage_milliseconds_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval])) / 1000 \n/\n(\n    sum by (namespace,name) (d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"}) / 100\n)",
     "legendFormat": "OS Usage"
    },
    {
     "expr": "(\n    sum by (namespace,name) (rate(d8_virtualization_virtualmachine_hypervisor_cpu_usage_milliseconds_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval])) / 1000 \n)\n/\n(\n    sum by (namespace,name) (d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"}) / 100\n)\n",
     "legendFormat": "Hypervisor overhead"
    },
    {
     "expr": "(\n    sum by (namespace,name) ((d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"} * d8_virtualization_virtualmachine_cpu_core_fraction) / 100)\n)\n/\n(\n    sum by (namespace,name) (d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"}) / 100\n)\n",
     "legendFormat": "Reservation"
    }
   ]
  },
  {
   "title": "Memory usage in %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (namespace,name) (d8_virtualization_virtualmachine_os_memory_total_bytes - d8_virtualization_virtualmachine_os_memory_potentially_free_bytes{namespace=\"$namespace\", name=\"$name\"}) / (avg by (namespace,name) (d8_virtualization_virtualmachine_memory_size_bytes{namespace=\"$namespace\", name=\"$name\"}) / 100)",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Network bandwidth usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(d8_virtualization_virtualmachine_network_receive_bytes_total{namespace=\"$namespace\", name=\"$name\", network=\"$network\"}[$__rate_interval])*8)",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(d8_virtualization_virtualmachine_network_transmit_bytes_total{namespace=\"$namespace\", name=\"$name\", network=\"$network\"}[$__rate_interval])*8)",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Disk read IOPS",
   "type": "timeseries",
   "description": "Disk read I/O operations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(d8_virtualization_virtualmachine_block_device_iops_read_total{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(d8_virtualization_virtualmachine_block_device_iops_write_total{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\"}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  { "title": "VM status details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Configuration",
   "type": "state-timeline",
   "description": "Whether the desired configuration is currently applied to a running VM",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum by (name) (d8_virtualization_virtualmachine_configuration_applied{namespace=\"$namespace\", name=\"$name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM status timeline",
   "type": "state-timeline",
   "description": "Timeline with information on VM statuses",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum by (name) ((d8_virtualization_virtualmachine_status_phase{namespace=\"$namespace\", name=\"$name\"} == 1) * on(phase) group_left()\n    (\n      label_replace(vector(1), \"phase\", \"Degraded\", \"\", \"\") or\n      label_replace(vector(2), \"phase\", \"Migrating\", \"\", \"\") or\n      label_replace(vector(3), \"phase\", \"Pause\", \"\", \"\") or\n      label_replace(vector(4), \"phase\", \"Pending\", \"\", \"\") or\n      label_replace(vector(5), \"phase\", \"Running\", \"\", \"\") or\n      label_replace(vector(6), \"phase\", \"Starting\", \"\", \"\") or\n      label_replace(vector(7), \"phase\", \"Stopped\", \"\", \"\") or\n      label_replace(vector(8), \"phase\", \"Stopping\", \"\", \"\") or\n      label_replace(vector(9), \"phase\", \"Terminating\", \"\", \"\")\n    ))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Live migration memory metrics",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(d8_virtualization_virtualmachine_migration_data_processed_bytes{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval])",
     "legendFormat": "Processed memory rate"
    },
    {
     "expr": "rate(d8_virtualization_virtualmachine_migration_data_remaining_bytes{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval])",
     "legendFormat": "Remaining memory rate"
    },
    {
     "expr": "d8_virtualization_virtualmachine_migration_dirty_memory_rate_bytes{namespace=\"$namespace\", name=\"$name\"}",
     "legendFormat": "Dirty memory rate"
    }
   ]
  },
  {
   "title": "CPU details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Core usage",
     "type": "timeseries",
     "description": "`Current cores` - The amount of computing resources allocated to the virtual machine.\n\n`Guaranteed cores` - The minimum amount of resources (in fractions of CPUs) guaranteed to be available to the VM. Calculated as `Current cores` × `Reservation`\n\n`Hypervisor overhead` - The value of the fraction of CPU used by the hypervisor.\n\n`OS Usage` - The level of utilization of allocated compute resources of the guest OS. If `Reservation < 100%`, it is allowed to exceed `OS Usage` up to the value of `Current cores`.\n\n`Steal cores` - The value of CPU share that the virtual machine was waiting to access physical resources due to competition with other VMs (“noisy neighbors”).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (namespace,name) (rate(d8_virtualization_virtualmachine_cpu_usage_milliseconds_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval])) / 1000",
       "legendFormat": "OS Usage"
      },
      {
       "expr": "sum by (namespace,name) (rate(d8_virtualization_virtualmachine_hypervisor_cpu_usage_milliseconds_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval])) / 1000\n",
       "legendFormat": "Hypervisor overhead"
      },
      {
       "expr": "sum by (namespace,name) ((d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"} * d8_virtualization_virtualmachine_cpu_core_fraction) / 100)\n",
       "legendFormat": "Guaranteed cores"
      },
      {
       "expr": "sum by (namespace,name) (d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"})\n",
       "legendFormat": "Current cores"
      },
      {
       "expr": "sum by (namespace,name) (rate(d8_virtualization_virtualmachine_cpu_steal_milliseconds_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval])) / 1000",
       "legendFormat": "Steal cores"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "timeseries",
     "description": "`Current cores` - The amount of computing resources allocated to a virtual machine.\n\n`Current cores guaranteed` - The minimum amount of resources (in fractions of CPUs) guaranteed to be available to the VM. Calculated as `Current cores` × `Reservation`.\n\n`Configured cores` - The amount of computing resources configured in the virtual machine which will be aplied after VM restart.\n\n`Configured cores guaranteed` - The minimum amount of resources (in CPU fractions) guaranteed to be available to the VM that will be available after the configuration is applied.\n\n`Demand cores` - The number of CPU shares by which it is recommended to increase `Current cores` based on the current load\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (namespace,name) ((d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"} * d8_virtualization_virtualmachine_cpu_core_fraction) / 100)\n",
       "legendFormat": "Current cores guaranteed "
      },
      {
       "expr": "sum by (namespace,name) ((d8_virtualization_virtualmachine_configuration_cpu_cores{namespace=\"$namespace\", name=\"$name\"} * d8_virtualization_virtualmachine_configuration_cpu_core_fraction) / 100)\n",
       "legendFormat": "Configured cores guaranteed "
      },
      {
       "expr": "sum by (namespace,name) (d8_virtualization_virtualmachine_configuration_cpu_cores{namespace=\"$namespace\", name=\"$name\"})\n",
       "legendFormat": "Configured cores"
      },
      {
       "expr": "sum by (namespace,name) (d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"})\n",
       "legendFormat": "Current cores"
      },
      {
       "expr": "sum without (pod) (\n  max(kube_controller_pod{namespace=\"$namespace\", controller=~\"InternalVirtualizationVirtualMachineInstance/${name}\", pod=~\"virt-launcher-${name}.*\"}) by(pod)\n  * on (pod)\n  sum by (pod) (\n    (\n      sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"virt-launcher-${name}.*\"}[$__rate_interval]))\n      -\n      sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\", namespace=\"$namespace\", pod=~\"virt-launcher-${name}.*\", container!=\"POD\"}[$__rate_interval]))\n    )\n    or\n    sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"virt-launcher-${name}.*\"}[$__rate_interval]))\n  )\n) > 0",
       "legendFormat": "Demand cores "
      }
     ]
    },
    {
     "title": "CPU usage per core",
     "type": "timeseries",
     "description": "`Current cores` - The amount of computing resources allocated to the virtual machine.\n\n`Guaranteed cores` - The minimum amount of resources (in fractions of CPUs) guaranteed to be available to the VM. Calculated as `Current cores` × `Reservation`\n\n`Hypervisor overhead` - The value of the fraction of CPU used by the hypervisor.\n\n`OS Usage` - The level of utilization of allocated compute resources of the guest OS. If `Reservation < 100%`, it is allowed to exceed `OS Usage` up to the value of `Current cores`.\n\n`Steal cores` - The value of CPU share that the virtual machine was waiting to access physical resources due to competition with other VMs (“noisy neighbors”).",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (namespace,name,core) (rate(d8_virtualization_virtualmachine_cpu_usage_milliseconds_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval])) / 1000",
       "legendFormat": "OS Usage core {{ core }}"
      },
      {
       "expr": "sum by (namespace,name) (rate(d8_virtualization_virtualmachine_hypervisor_cpu_usage_milliseconds_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval])) / 1000\n",
       "legendFormat": "Hypervisor overhead"
      },
      {
       "expr": "sum by (namespace,name) ((d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"} * d8_virtualization_virtualmachine_cpu_core_fraction) / 100)\n",
       "legendFormat": "Guaranteed cores"
      },
      {
       "expr": "sum by (namespace,name) (d8_virtualization_virtualmachine_cpu_cores{namespace=\"$namespace\", name=\"$name\"})\n",
       "legendFormat": "Current cores"
      },
      {
       "expr": "sum by (namespace,name,core) (rate(d8_virtualization_virtualmachine_cpu_steal_milliseconds_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval])) / 1000",
       "legendFormat": "Steal core {{ core }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (namespace,name) (d8_virtualization_virtualmachine_memory_size_bytes{namespace=\"$namespace\", name=\"$name\"})",
       "legendFormat": "Configured memory"
      },
      {
       "expr": "avg by (namespace,name) (d8_virtualization_virtualmachine_os_memory_total_bytes - d8_virtualization_virtualmachine_os_memory_potentially_free_bytes{namespace=\"$namespace\", name=\"$name\"})",
       "legendFormat": "OS used"
      }
     ]
    },
    {
     "title": "Memory ",
     "type": "timeseries",
     "description": "The current and configured amount of the memory to be applied after restart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (namespace,name) (d8_virtualization_virtualmachine_memory_size_bytes{namespace=\"$namespace\", name=\"$name\"})",
       "legendFormat": "Memory current"
      },
      {
       "expr": "avg by (namespace,name) (d8_virtualization_virtualmachine_configuration_memory_size_bytes{namespace=\"$namespace\", name=\"$name\"})",
       "legendFormat": "Memory configured"
      }
     ]
    },
    {
     "title": "Page faults",
     "type": "timeseries",
     "description": "Memory page faults for the VM instance",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "avg(rate(d8_virtualization_virtualmachine_os_memory_pgminfault_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval]))",
       "legendFormat": "Minor"
      },
      {
       "expr": "avg(rate(d8_virtualization_virtualmachine_os_memory_pgmajfault_total{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval]))",
       "legendFormat": "Major"
      }
     ]
    },
    {
     "title": "Swap traffic",
     "type": "timeseries",
     "description": "Amount of data swapped in/out by the VM instance",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg(rate(d8_virtualization_virtualmachine_os_memory_swap_in_traffic_bytes{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval]))",
       "legendFormat": "IN"
      },
      {
       "expr": "avg(rate(d8_virtualization_virtualmachine_os_memory_swap_out_traffic_bytes{namespace=\"$namespace\", name=\"$name\"}[$__rate_interval]))",
       "legendFormat": "OUT"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage capacity details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mount point \"$mount_point\"",
     "type": "timeseries",
     "description": "Mount point usage and capacity",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 33 },
     "repeat": "mount_point",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(mount_point) (d8_virtualization_virtualmachine_filesystem_capacity_bytes{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\", mount_point=~\"$mount_point\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum by (mount_point) (d8_virtualization_virtualmachine_filesystem_used_bytes{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\", mount_point=~\"$mount_point\"})",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage I/O details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk read IOPS",
     "type": "timeseries",
     "description": "Disk read I/O operations",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg by (block_device_name) (rate(d8_virtualization_virtualmachine_block_device_iops_read_total{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\"}[$__rate_interval]))",
       "legendFormat": "{{block_device_name}}"
      }
     ]
    },
    {
     "title": "Disk write IOPS",
     "type": "timeseries",
     "description": "Disk write I/O operations",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg by (block_device_name) (rate(d8_virtualization_virtualmachine_block_device_iops_write_total{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\"}[$__rate_interval]))",
       "legendFormat": "{{block_device_name}}"
      }
     ]
    },
    {
     "title": "Disk read latency",
     "type": "timeseries",
     "description": "Disk read operations latency",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (block_device_name) (\n    rate(d8_virtualization_virtualmachine_block_device_read_times_seconds_total{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\"}[$__rate_interval])\n    /\n    rate(d8_virtualization_virtualmachine_block_device_iops_read_total{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\"}[$__rate_interval])\n)\n",
       "legendFormat": "{{block_device_name}}"
      }
     ]
    },
    {
     "title": "Disk write throughput",
     "type": "timeseries",
     "description": "Disk write traffic in bytes per second",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg by (block_device_name) (rate(d8_virtualization_virtualmachine_block_device_write_traffic_bytes_total{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\"}[$__rate_interval]))",
       "legendFormat": "{{block_device_name}}"
      }
     ]
    },
    {
     "title": "Disk read throughput",
     "type": "timeseries",
     "description": "Disk read traffic in bytes per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg by (block_device_name) (rate(d8_virtualization_virtualmachine_block_device_read_traffic_bytes_total{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\"}[$__rate_interval]))",
       "legendFormat": "{{block_device_name}}"
      }
     ]
    },
    {
     "title": "Disk write latency",
     "type": "timeseries",
     "description": "Disk write operations latency",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (block_device_name) (\n    rate(d8_virtualization_virtualmachine_block_device_write_times_seconds_total{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\"}[$__rate_interval])\n    /\n    rate(d8_virtualization_virtualmachine_block_device_iops_write_total{namespace=\"$namespace\", name=\"$name\", type!=\"cloudinit\"}[$__rate_interval])\n    )",
       "legendFormat": "{{block_device_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network \"$network\" details ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "repeat": "network",
   "collapsed": true,
   "panels": [
    {
     "title": "Bandwidth - $network",
     "type": "timeseries",
     "description": "Interface bandwidth",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "avg by (network) (rate(d8_virtualization_virtualmachine_network_receive_bytes_total{namespace=\"$namespace\", name=\"$name\", network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "RX bps"
      },
      {
       "expr": "avg by (network) (rate(d8_virtualization_virtualmachine_network_transmit_bytes_total{namespace=\"$namespace\", name=\"$name\", network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "TX bps"
      }
     ]
    },
    {
     "title": "Packet rate - $network",
     "type": "timeseries",
     "description": "Packet rate on the interface",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "avg by (network) (rate(d8_virtualization_virtualmachine_network_receive_packets_total{namespace=\"$namespace\", name=\"$name\", network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "RX pps"
      },
      {
       "expr": "avg by (network) (rate(d8_virtualization_virtualmachine_network_transmit_packets_total{namespace=\"$namespace\", name=\"$name\", network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "TX pps"
      }
     ]
    },
    {
     "title": "Packet drops - $network",
     "type": "timeseries",
     "description": "Packets dropped by the interface",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "avg by (network) (rate(d8_virtualization_virtualmachine_network_receive_packets_dropped_total{namespace=\"$namespace\", name=\"$name\", network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "RX drops"
      },
      {
       "expr": "avg by (network) (rate(d8_virtualization_virtualmachine_network_transmit_packets_dropped_total{namespace=\"$namespace\", name=\"$name\", network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "TX drops"
      }
     ]
    },
    {
     "title": "Interface errors - $network",
     "type": "timeseries",
     "description": "Interface transmit and receive errors",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "avg by (network) (rate(d8_virtualization_virtualmachine_network_receive_errors_total{namespace=\"$namespace\", name=\"$name\", network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "RX errors"
      },
      {
       "expr": "avg by (network) (rate(d8_virtualization_virtualmachine_network_transmit_errors_total{namespace=\"$namespace\", name=\"$name\", network=\"$network\"}[$__rate_interval])*8)",
       "legendFormat": "TX errors"
      }
     ]
    }
   ]
  }
 ]
}