apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    heritage: deckhouse
    module: metallb
    rbac.deckhouse.io/aggregate-to-networking-as: manager
    rbac.deckhouse.io/kind: capability
    rbac.deckhouse.io/capability: "system-capability.metallb.edit"
    rbac.deckhouse.io/scope: system
    rbac.deckhouse.io/namespace: d8-metallb
  name: d8:system-capability:metallb:edit
  annotations:
    en.meta.deckhouse.io/title: "Module metallb: edit configuration"
    ru.meta.deckhouse.io/title: "Модуль metallb: управление конфигурацией"
    en.meta.deckhouse.io/description: "Manage the metallb module configuration."
    ru.meta.deckhouse.io/description: "Управление конфигурацией модуля metallb."
rules:
- apiGroups:
  - deckhouse.io
  resourceNames:
  - metallb
  resources:
  - moduleconfigs
  verbs:
  - create
  - update
  - patch
  - delete
