// Copyright 2026 Flant JSC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package config

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"sigs.k8s.io/yaml"

	"github.com/deckhouse/deckhouse/go_lib/registry/models/initconfig"
	"github.com/deckhouse/deckhouse/go_lib/registry/models/moduleconfig"
	dhlog "github.com/deckhouse/lib-dhctl/pkg/logger"
	"github.com/deckhouse/lib-dhctl/pkg/retry"
	libdhctlyaml "github.com/deckhouse/lib-dhctl/pkg/yaml"

	"github.com/deckhouse/deckhouse/dhctl/pkg/app/options"
	"github.com/deckhouse/deckhouse/dhctl/pkg/config/digests"
	"github.com/deckhouse/deckhouse/dhctl/pkg/config/registry"
	"github.com/deckhouse/deckhouse/dhctl/pkg/infrastructureprovider/providerdir"
	"github.com/deckhouse/deckhouse/dhctl/pkg/kubernetes/actions/registrydata"
	"github.com/deckhouse/deckhouse/dhctl/pkg/kubernetes/client"
	"github.com/deckhouse/deckhouse/dhctl/pkg/util/fs"
	"github.com/deckhouse/deckhouse/dhctl/pkg/util/image"
	"github.com/deckhouse/deckhouse/dhctl/pkg/util/input"
)

var (
	// This value is set on the dhctl build in the dhctl/Makefile script.
	// Do not touch it !!!
	DefaultKubernetesVersion = "<autogenerated on the build stage>"
	RppSignCheck             = "false"
	Edition                  = "FE"
	CommaSeparatedEEEditions = "EE,FE,CSE"
)

// ErrParseConfigTransient marks a transport/API-level failure while reading the cluster
// configuration, as opposed to a permanent parse/schema-validation failure that will fail
// identically on every attempt.
var ErrParseConfigTransient = errors.New("parse cluster config: transient error, may succeed on retry")

func LoadConfigFromFile(
	ctx context.Context,
	paths []string,
	validatorProvider MetaConfigValidatorProvider,
	globalOptions *options.GlobalOptions,
	opts ...ValidateOption,
) (*MetaConfig, error) {
	docs, err := FetchDocuments(ctx, paths)
	if err != nil {
		return nil, err
	}

	if globalOptions.EnsureCandiAvailable {
		registryConf, err := buildRegistryConfig(docs)
		if err != nil {
			return nil, err
		}
		if err = prepareCandiDir(ctx, registryConf, globalOptions); err != nil {
			return nil, err
		}
	}

	metaConfig, err := ParseConfig(ctx, fs.RevealWildcardPaths(paths), validatorProvider, globalOptions, opts...)
	if err != nil {
		return nil, err
	}

	metaConfig.ShowProgress = globalOptions.ShowProgress

	versionMapFile := options.DefaultVersionMap
	if globalOptions.VersionMap != "" {
		versionMapFile = globalOptions.VersionMap
	}

	if err := metaConfig.LoadVersionMap(versionMapFile); err != nil {
		return nil, err
	}

	if err := metaConfig.LoadImagesDigests(); err != nil {
		return nil, err
	}

	if err := metaConfig.LoadInstallerVersion(); err != nil {
		return nil, err
	}

	if metaConfig.ClusterType == CloudClusterType && len(metaConfig.ProviderClusterConfig) == 0 {
		if ProviderRequiresClusterConfig(metaConfig.ProviderName) {
			return nil, fmt.Errorf("ProviderClusterConfiguration section is required for a Cloud cluster.")
		}
	}

	return metaConfig, nil
}

func numerateManifestLines(manifest []byte) string {
	manifestLines := strings.Split(string(manifest), "\n")
	builder := strings.Builder{}

	for index, line := range manifestLines {
		fmt.Fprintf(&builder, "%d\t%s\n", index+1, line)
	}

	return builder.String()
}

func ParseConfig(
	ctx context.Context,
	paths []string,
	validatorProvider MetaConfigValidatorProvider,
	globalOptions *options.GlobalOptions,
	opts ...ValidateOption,
) (*MetaConfig, error) {
	globalOptions = withDownloadDir(globalOptions)

	content := ""
	for _, path := range paths {
		if strings.Contains(path, "*") {
			continue // skip wildcard paths, we revealed them in the previous step
		}

		dhlog.FromContext(ctx).DebugContext(ctx, fmt.Sprintf("Have config file %s", path))
		fileContent, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("loading config file: %v", err)
		}
		content = content + "\n\n---\n\n" + string(fileContent)
	}

	bundleDir, err := ensureProviderBundleFromConfig(ctx, libdhctlyaml.SplitYAML(content), globalOptions)
	if err != nil {
		return nil, fmt.Errorf("prepare provider bundle: %w", err)
	}
	opts = append(opts, ValidateOptionProviderBundleDir(bundleDir), ValidateOptionDownloadRootDir(globalOptions.DownloadDir))

	// Every problem in the file, not the first one. This is the path an operator takes with a
	// config they wrote: three mistakes in it used to cost three runs, each finding one — and on
	// a cloud cluster a run that gets past this creates infrastructure.
	//
	// Commander already asked for this explicitly; the caller that passes it again is harmless,
	// since the option is idempotent.
	opts = append(opts, ValidateOptionCollectAllErrors(true))

	metaConfig, err := ParseConfigFromData(ctx, content, validatorProvider, globalOptions, opts...)
	if err != nil {
		return metaConfig, err
	}

	metaConfig.VersionFilePath = filepath.Join(options.DefaultDeckhouseDir, "version")
	if globalOptions.DeckhouseDir != "" {
		metaConfig.VersionFilePath = filepath.Join(globalOptions.DeckhouseDir, "version")
	}

	return metaConfig, nil
}

func ParseConfigFromCluster(
	ctx context.Context,
	kubeCl *client.KubernetesClient,
	validatorProvider MetaConfigValidatorProvider,
	globalOptions *options.GlobalOptions,
	operation string,
) (*MetaConfig, error) {
	var metaConfig *MetaConfig
	var err error

	// Scope the whole retry loop: a retried attempt re-validates the same documents, and the
	// deferred flush lands after the process block below closes.
	ctx, flushDeprecations := withDeprecationCollector(ctx)
	defer flushDeprecations(ctx)

	loopParams := retry.NewEmptyParams(
		retry.WithName("Get cluster configuration from Kubernetes cluster"),
		retry.WithAttempts(50),
		retry.WithWait(1*time.Second),
		retry.WithWhitelist(ErrParseConfigTransient, registrydata.ErrRegistryDataTransient),
	)

	return metaConfig, dhlog.RunProcess(ctx, dhlog.FromContext(ctx), "Get cluster configuration", func(ctx context.Context) error {
		return retry.NewLoopWithParams(loopParams).
			RunContext(ctx, func() error {
				metaConfig, err = parseConfigFromCluster(ctx, kubeCl, validatorProvider, globalOptions, operation)
				return err
			})
	})
}

func ParseConfigInCluster(
	ctx context.Context,
	kubeCl *client.KubernetesClient,
	validatorProvider MetaConfigValidatorProvider,
	globalOptions *options.GlobalOptions,
	operation string,
) (*MetaConfig, error) {
	var (
		metaConfig *MetaConfig
		err        error
	)

	// Scope the whole retry loop: a retried attempt re-validates the same documents.
	ctx, flushDeprecations := withDeprecationCollector(ctx)
	defer flushDeprecations(ctx)

	loopParams := retry.NewEmptyParams(
		retry.WithName("Get cluster configuration from inside Kubernetes cluster"),
		retry.WithAttempts(25),
		retry.WithWait(1*time.Second),
		retry.WithWhitelist(ErrParseConfigTransient, registrydata.ErrRegistryDataTransient),
	)

	err = retry.NewSilentLoopWithParams(loopParams).
		RunContext(ctx, func() error {
			metaConfig, err = parseConfigFromCluster(ctx, kubeCl, validatorProvider, globalOptions, operation)
			return err
		})
	if err != nil {
		return nil, err
	}
	return metaConfig, nil
}

// clusterRegistryData reads the cluster's registry on the first caller that needs it and hands the
// same answer, error included, to every caller after.
func clusterRegistryData(kubeCl *client.KubernetesClient, inCluster bool) func(ctx context.Context) (*image.RegistryConfig, string, error) {
	var (
		once      sync.Once
		conf      *image.RegistryConfig
		dockerCfg string
		err       error
	)

	return func(ctx context.Context) (*image.RegistryConfig, string, error) {
		once.Do(func() {
			conf, dockerCfg, err = registrydata.GetRegistryDataPreferUpstream(ctx, kubeCl, inCluster)
		})
		return conf, dockerCfg, err
	}
}

func parseConfigFromCluster(ctx context.Context, kubeCl *client.KubernetesClient, validatorProvider MetaConfigValidatorProvider, globalOptions *options.GlobalOptions, operation string) (*MetaConfig, error) {
	metaConfig := &MetaConfig{Operation: operation}

	// Non-nil, and with a dir to unpack the provider bundle into even when DownloadDir was left empty.
	globalOptions = withDownloadDir(globalOptions)

	clusterConfig, err := readClusterConfigFromCluster(ctx, kubeCl)
	if err != nil {
		return nil, err
	}
	cloudProvider := clusterConfig.Provider
	registryData := clusterRegistryData(kubeCl, globalOptions.KubeInCluster)

	if globalOptions.EnsureCandiAvailable {
		conf, _, err := registryData(ctx)
		if err != nil {
			return nil, err
		}
		if err := prepareCandiDir(ctx, conf, globalOptions); err != nil {
			return nil, err
		}
	}

	if !IsInternalCloudProviderBundle(cloudProvider, globalOptions) {
		lookup := clusterModuleDocs(
			func(context.Context) (*client.KubernetesClient, error) { return kubeCl, nil },
			cloudProvider,
			globalOptions.KubeInCluster,
		)

		registry := func(ctx context.Context) (*image.RegistryConfig, error) {
			conf, _, err := registryData(ctx)
			return conf, err
		}

		bundleDir, _, err := updateProviderBundle(
			ctx,
			cloudProvider,
			lookup,
			registry,
			globalOptions,
		)
		if err != nil {
			return nil, fmt.Errorf("prepare provider bundle: %w", err)
		}
		metaConfig.ProviderBundleDir = bundleDir
	}

	// The lazy provider-plugin and terraform-manager pulls read these off DeckhouseConfig long after
	// this parse, so a cloud cluster needs them whether or not anything was downloaded above.
	if clusterConfig.Type == CloudClusterType {
		conf, dockerCfg, err := registryData(ctx)
		if err != nil {
			return nil, fmt.Errorf("read registry data from cluster: %w", err)
		}

		metaConfig.DeckhouseConfig.RegistryDockerCfg = dockerCfg
		metaConfig.DeckhouseConfig.ImagesRepo = conf.GetRegistry()
		metaConfig.DeckhouseConfig.RegistryCA = conf.GetCA()
		metaConfig.DeckhouseConfig.RegistryScheme = conf.GetScheme()
	}

	metaConfig.DownloadRootDir = globalOptions.DownloadDir
	metaConfig.VersionFilePath = filepath.Join(globalOptions.DeckhouseDir, "version")
	metaConfig.ShowProgress = globalOptions.ShowProgress

	schemaStore := NewSchemaStore(globalOptions)

	_, err = schemaStore.Validate(ctx, &clusterConfig.Raw)
	if err != nil {
		return nil, err
	}

	metaConfig.ClusterConfig = clusterConfig.Parsed
	metaConfig.ClusterType = clusterConfig.Type

	_, err = DoByClusterType(ctx, metaConfig, newFromClusterMetaConfigFiller(kubeCl, schemaStore))
	if err != nil {
		return nil, err
	}

	// For cloud clusters, pre-load provider resources from the cluster so that
	// CloudProviderVars is available when the provider validator runs. The Cloud filler
	// above has already populated ProviderName (and the mc-flow ModuleConfig or
	// legacy ProviderClusterConfig).
	if clusterConfig.Type == CloudClusterType {
		cv, err := CloudProviderVarsFromCluster(ctx, kubeCl, metaConfig.ProviderName)
		if err != nil {
			return nil, fmt.Errorf("read cloud provider resources: %w", err)
		}
		metaConfig.CloudProviderVars = cv
	}

	return metaConfig.Prepare(ctx, validatorProvider)
}

// parseDocument
//
// parse and validate one document of
//
//		InitConfiguration
//		ClusterConfiguration
//		StaticClusterConfiguration
//		ClusterConfiguration
//	    ModuleConfig
//
// if validation schema for ModuleConfig or another resources not found returns ErrSchemaNotFound error
func parseDocument(ctx context.Context, doc string, metaConfig *MetaConfig, schemaStore *SchemaStore, opts ...ValidateOption) (bool, error) {
	doc = strings.TrimSpace(doc)
	if doc == "" {
		return false, nil
	}

	options := applyOptions(opts...)
	docData := []byte(doc)

	var index SchemaIndex
	err := yaml.Unmarshal(docData, &index)
	if err != nil {
		return false, fmt.Errorf("Config document unmarshal failed: %v\ndata: \n%s", err, numerateManifestLines(docData))
	}

	if index.Kind == ModuleConfigKind {
		moduleConfig := ModuleConfig{}
		err = yaml.Unmarshal(docData, &moduleConfig)
		if err != nil {
			return false, fmt.Errorf("Module config document unmarshal failed: %v\ndata: \n%s", err, numerateManifestLines(docData))
		}

		dhlog.FromContext(ctx).DebugContext(ctx, fmt.Sprintf("Found ModuleConfig in config file %s", moduleConfig.Name))

		if !options.skipSchemaValidation {
			// omitDocInError: the numbered copy below is the one worth reading, and without this
			// the document is printed twice — once raw by the validator and once here with line
			// numbers, which is how a three-document config produced screens of YAML.
			_, err = schemaStore.Validate(ctx, &docData, append(opts, ValidateOptionOmitDocInError(true))...)
			if err != nil {
				if errors.Is(err, ErrSchemaNotFound) {
					dhlog.FromContext(ctx).DebugContext(ctx, fmt.Sprintf("Schema not found for module %s", moduleConfig.Name))
					return false, nil
				}
				return false, fmt.Errorf("Module config validation failed: %w\ndata: \n%s", err, numerateManifestLines(docData))
			}
		}

		metaConfig.ModuleConfigs = append(metaConfig.ModuleConfigs, &moduleConfig)
		return true, nil
	}

	if !options.skipSchemaValidation {
		// Same here: the caller prints the document with line numbers, so the validator must not
		// print it again without them.
		_, err = schemaStore.Validate(ctx, &docData, append(opts, ValidateOptionOmitDocInError(true))...)
		if err != nil {
			if errors.Is(err, ErrSchemaNotFound) {
				return false, nil
			}
			return false, fmt.Errorf("Config document validation failed: %v\ndata: \n%s", err, numerateManifestLines(docData))
		}
	}

	var data map[string]json.RawMessage
	if err = yaml.Unmarshal(docData, &data); err != nil {
		return false, fmt.Errorf("Config document unmarshal failed: %v\ndata: \n%s", err, numerateManifestLines(docData))
	}

	found := false
	switch {
	case index.Kind == "InitConfiguration":
		dhlog.FromContext(ctx).DebugContext(ctx, "Found InitConfiguration")
		metaConfig.InitClusterConfig = data
		found = true
	case index.Kind == "ClusterConfiguration":
		dhlog.FromContext(ctx).DebugContext(ctx, "Found ClusterConfiguration")
		metaConfig.ClusterConfig = data
		found = true
	case index.Kind == "StaticClusterConfiguration":
		dhlog.FromContext(ctx).DebugContext(ctx, "Found StaticClusterConfiguration")
		metaConfig.StaticClusterConfig = data
		found = true
	case strings.HasSuffix(index.Kind, "ClusterConfiguration"):
		dhlog.FromContext(ctx).DebugContext(ctx, fmt.Sprintf("Found %s", index.Kind))
		metaConfig.ProviderClusterConfig = data
		found = true
	}

	return found, nil
}

// detectMergedDocuments checks if a document contains multiple YAML documents merged together
// (indicated by multiple top-level "kind:" or "apiVersion:" fields). This happens when the "---" separator is missing.
// When multiple apiVersion fields exist at root level, yaml.Unmarshal will overwrite previous values,
// causing the first document to be lost. This function detects such cases before parsing.
func detectMergedDocuments(doc string) error {
	doc = strings.TrimSpace(doc)
	if doc == "" {
		return nil
	}

	// First, try to unmarshal to see if it fails due to duplicate keys
	// Go's yaml library doesn't error on duplicate keys, but we can detect them by checking
	// if we have multiple root-level apiVersion/kind fields
	var rootLevelKinds []string
	var rootLevelAPIVersions []string
	lines := strings.SplitSeq(doc, "\n")

	for line := range lines {
		trimmed := strings.TrimSpace(line)
		// Skip comments and empty lines
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}

		// Calculate current indent level (number of leading spaces/tabs)
		leadingWhitespace := len(line) - len(strings.TrimLeft(line, " \t"))

		// Only consider fields at root level (indent 0)
		if leadingWhitespace == 0 {
			if after, ok := strings.CutPrefix(trimmed, "apiVersion:"); ok {
				apiVersionValue := strings.TrimSpace(after)
				if apiVersionValue != "" {
					rootLevelAPIVersions = append(rootLevelAPIVersions, apiVersionValue)
				}
			} else if after, ok := strings.CutPrefix(trimmed, "kind:"); ok {
				kindValue := strings.TrimSpace(after)
				if kindValue != "" {
					rootLevelKinds = append(rootLevelKinds, kindValue)
				}
			}
		}
	}

	// If we have multiple root-level apiVersion or kind fields, documents are likely merged
	// When unmarshaling, duplicate keys will overwrite previous values, causing data loss
	// We check for multiple of both to avoid false positives from nested structures
	if len(rootLevelAPIVersions) > 1 && len(rootLevelKinds) > 1 {
		return fmt.Errorf(
			"invalid config.yml format: missing '---' separator between documents. "+
				"Found multiple root-level 'kind' fields: %v. "+
				"Please ensure each YAML document is separated by '---' on its own line.",
			rootLevelKinds,
		)
	}

	return nil
}

func ParseConfigFromData(
	ctx context.Context,
	configData string,
	validatorProvider MetaConfigValidatorProvider,
	globalOptions *options.GlobalOptions,
	opts ...ValidateOption,
) (*MetaConfig, error) {
	// Report every deprecated option found across the documents as one block instead of a
	// banner per field. The flush is deferred so it also covers metaConfig.Prepare below, and
	// runs outside any process block this parse is nested in.
	ctx, flushDeprecations := withDeprecationCollector(ctx)
	defer flushDeprecations(ctx)

	options := applyOptions(opts...)
	schemaStore := NewSchemaStore(globalOptions)

	bigFileTmp := strings.TrimSpace(configData)
	docs := input.YAMLSplitRegexp.Split(bigFileTmp, -1)

	resourcesDocs := make([]string, 0, len(docs))
	errs := &ValidationError{}

	metaConfig := MetaConfig{}
	for _, doc := range docs {
		// Check for merged documents before parsing
		if err := detectMergedDocuments(doc); err != nil {
			wrapped := fmt.Errorf("config validation failed: %w\ndata:\n%s\n", err, numerateManifestLines([]byte(doc)))
			if !options.collectAllErrors {
				return nil, wrapped
			}
			errs.Append(ErrKindInvalidYAML, Error{Messages: []string{wrapped.Error()}})
			continue
		}

		found, err := parseDocument(ctx, doc, &metaConfig, schemaStore, opts...)
		if err != nil {
			if !options.collectAllErrors {
				return nil, err
			}
			errs.Append(ErrKindValidationFailed, Error{Messages: []string{err.Error()}})
			continue
		}
		if !found && strings.TrimSpace(doc) != "" {
			var index SchemaIndex
			_ = yaml.Unmarshal([]byte(doc), &index)
			if index.Kind != "" && index.Version != "" {
				dhlog.FromContext(ctx).DebugContext(ctx, fmt.Sprintf("Found resource for resourcesYaml %s/%s", index.Kind, index.Version))
			}
			resourcesDocs = append(resourcesDocs, doc)
		}
	}

	if options.collectAllErrors && len(errs.Errors) > 0 {
		// Return the partially-built MetaConfig together with accumulated
		// errors. Callers (e.g. validateCNIBootstrap) can keep analyzing on
		// top of the partial result, so a parse error in one document does
		// not hide a semantic problem in another.
		return &metaConfig, errs
	}

	metaConfig.ResourcesYAML = strings.TrimSpace(strings.Join(resourcesDocs, "\n\n---\n\n"))

	// init configuration can be empty, but we need default from openapi spec
	// Note: InitConfiguration can also be provided via ModuleConfig deckhouse (registry settings)
	if len(metaConfig.InitClusterConfig) == 0 {
		dhlog.FromContext(ctx).DebugContext(ctx, "Init configuration not found, using empty")
		doc := `
apiVersion: deckhouse.io/v1
kind: InitConfiguration
deckhouse: {}
`
		found, err := parseDocument(ctx, doc, &metaConfig, schemaStore, opts...)
		if err != nil {
			return nil, err
		}
		if !found {
			return nil, fmt.Errorf("init configuration index not found")
		}
	}

	if options.operation != "" {
		metaConfig.Operation = options.operation
	}
	if options.downloadRootDir != "" {
		metaConfig.DownloadRootDir = options.downloadRootDir
	}
	if options.providerBundleDir != "" {
		metaConfig.ProviderBundleDir = options.providerBundleDir
	}
	for _, mc := range options.clusterModuleConfigs {
		if metaConfig.FindModuleConfig(mc.GetName()) == nil {
			metaConfig.ModuleConfigs = append(metaConfig.ModuleConfigs, mc)
		}
	}

	return metaConfig.Prepare(ctx, validatorProvider)
}

// ParseConfigFromDataEnsureProvider is ParseConfigFromData that first prepares the provider bundle
// configData names, unless a bundle dir is passed in with ValidateOptionProviderBundleDir. Registry
// access found in configData is copied onto DeckhouseConfig for the lazy provider downloads.
func ParseConfigFromDataEnsureProvider(
	ctx context.Context,
	configData string,
	validatorProvider MetaConfigValidatorProvider,
	globalOptions *options.GlobalOptions,
	opts ...ValidateOption,
) (*MetaConfig, error) {
	globalOptions = withDownloadDir(globalOptions)

	docs := input.YAMLSplitRegexp.Split(strings.TrimSpace(configData), -1)

	// Whoever delivered the bundle chose the build. This parse prepares one only when none was handed in.
	if applyOptions(opts...).providerBundleDir == "" {
		bundleDir, err := ensureProviderBundleFromConfig(ctx, docs, globalOptions)
		if err != nil {
			return nil, fmt.Errorf("prepare provider bundle: %w", err)
		}
		opts = append(opts, ValidateOptionProviderBundleDir(bundleDir))
	}

	opts = append(opts, ValidateOptionDownloadRootDir(globalOptions.DownloadDir))

	metaConfig, err := ParseConfigFromData(ctx, configData, validatorProvider, globalOptions, opts...)
	if err != nil {
		return nil, err
	}

	// Lazy provider-plugin / terraform-manager downloads read registry creds
	// from DeckhouseConfig. When configData itself carries an InitConfiguration
	// or a deckhouse ModuleConfig (CLI paths), copy them onto DeckhouseConfig so
	// the cold-pod download has credentials; commander operations resolve the
	// registry from the target cluster instead. No-op when the docs hold none.
	if err := applyRegistryToDeckhouseConfig(metaConfig, docs); err != nil {
		return nil, err
	}

	return metaConfig, nil
}

// applyRegistryToDeckhouseConfig fills registry access on
// metaConfig.DeckhouseConfig from the parsed docs (an InitConfiguration and/or a
// deckhouse ModuleConfig) when configData itself did not supply it, so the lazy
// provider-plugin / terraform-manager download has working credentials. No-op
// when DeckhouseConfig already carries a dockercfg or the docs hold no registry
// data.
func applyRegistryToDeckhouseConfig(metaConfig *MetaConfig, docs []string) error {
	if metaConfig.DeckhouseConfig.RegistryDockerCfg != "" {
		return nil
	}

	provider, err := RegistryConfigProvider(docs)
	if err != nil {
		return err
	}
	remoteData, err := provider.RemoteData()
	if err != nil {
		return fmt.Errorf("registry data for provider plugin download: %w", err)
	}
	if remoteData.ImagesRepo == "" {
		return nil
	}

	dockerCfg, err := remoteData.DockerCfgBase64()
	if err != nil {
		return fmt.Errorf("encode registry dockercfg: %w", err)
	}

	metaConfig.DeckhouseConfig.RegistryDockerCfg = dockerCfg
	metaConfig.DeckhouseConfig.ImagesRepo = remoteData.ImagesRepo
	metaConfig.DeckhouseConfig.RegistryScheme = string(remoteData.Scheme)
	metaConfig.DeckhouseConfig.RegistryCA = remoteData.CA
	return nil
}

// withDownloadDir returns globalOptions guaranteed non-nil and with a non-empty DownloadDir
// (falling back to the default tmp dir). It copies when it must change so the shared server
// GlobalOptions is never mutated.
func withDownloadDir(globalOptions *options.GlobalOptions) *options.GlobalOptions {
	if globalOptions == nil {
		return &options.GlobalOptions{DownloadDir: options.DefaultTmpDir()}
	}
	if globalOptions.DownloadDir != "" {
		return globalOptions
	}

	cp := *globalOptions
	cp.DownloadDir = options.DefaultTmpDir()

	return &cp
}

func FetchDocuments(ctx context.Context, paths []string) ([]string, error) {
	paths = fs.RevealWildcardPaths(paths)
	content := ""

	for _, path := range paths {
		if strings.Contains(path, "*") {
			continue // skip wildcard paths, we revealed them in the previous step
		}

		dhlog.FromContext(ctx).DebugContext(ctx, fmt.Sprintf("Have config file %s", path))
		fileContent, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("loading config file: %w", err)
		}
		content = content + "\n\n---\n\n" + string(fileContent)
	}

	bigFileTmp := strings.TrimSpace(content)
	docs := input.YAMLSplitRegexp.Split(bigFileTmp, -1)

	for _, doc := range docs {
		if err := detectMergedDocuments(doc); err != nil {
			return nil, fmt.Errorf("config validation failed: %w\ndata:\n%s", err, numerateManifestLines([]byte(doc)))
		}
	}
	return docs, nil
}

// The modules directory is filled by werf from the edition built, and every cloud-provider module
// carries openapi/config-values.yaml, so no directory here means the build does not ship it. An
// unreadable directory answers "shipped": otherwise an empty filesystem externalises every module.
func moduleShippedInImage(moduleName string, globalOptions *options.GlobalOptions) bool {
	modulesDir := options.DefaultModulesDir
	if globalOptions != nil && globalOptions.ModulesDir != "" {
		modulesDir = globalOptions.ModulesDir
	}

	entries, err := os.ReadDir(modulesDir)
	if err != nil {
		return true
	}

	for _, e := range entries {
		if e.IsDir() && strings.TrimLeft(e.Name(), "0123456789-") == moduleName {
			return true
		}
	}

	return false
}

// buildRegistryConfig derives an OCI registry config from the input documents
// (InitConfiguration and/or ModuleConfig "deckhouse"). Only called when
// candi or provider schemas need to be downloaded.
func buildRegistryConfig(docs []string) (*image.RegistryConfig, error) {
	provider, err := RegistryConfigProvider(docs)
	if err != nil {
		return nil, err
	}
	remoteData, err := provider.RemoteData()
	if err != nil {
		return nil, err
	}
	return image.NewRegistryConfig(
		string(remoteData.Scheme),
		remoteData.ImagesRepo,
		remoteData.Username,
		remoteData.Password,
		remoteData.CA,
	)
}

func RegistryConfigProvider(docs []string) (*registry.ConfigProvider, error) {
	var (
		initConfig        *initconfig.Config
		deckhouseSettings *moduleconfig.DeckhouseSettings
		bundleFacts       registry.BundleBootstrapInputs
	)

	for _, doc := range docs {
		var obj unstructured.Unstructured
		if err := yaml.Unmarshal([]byte(doc), &obj); err != nil {
			return nil, err
		}

		switch obj.GetKind() {
		case InitConfigurationKind:
			ret, err := registry.ParseYAMLInitConfig([]byte(doc))
			if err != nil {
				return nil, err
			}

			initConfig = ret

		case ModuleConfigKind:
			switch obj.GetName() {
			case "deckhouse":
				ret, err := registry.ParseYAMLDeckhouseMC([]byte(doc))
				if err != nil {
					return nil, err
				}

				deckhouseSettings = ret

			case "registry":
				// An installation whose images come from a bundle, recognised from the registry
				// module's own configuration: a cache to hold them and no upstream to fetch them
				// from. The bundle itself arrives by --img-bundle-path, and the absence of that flag
				// is refused further down by the code that needs it, with a message that already
				// says so.
				//
				// Read here, in the one function all three callers go through, and not only where
				// the bootstrap starts its bundle registry: the same local registry also serves the
				// candi schemas and the provider plugins, and a caller that did not know about the
				// bundle would go looking for those in a registry an air-gapped operator does not
				// have — failing somewhere far from the reason.
				facts, err := registry.BundleFactsFromModuleConfig([]byte(doc))
				if err != nil {
					return nil, err
				}

				bundleFacts = facts
			}
		}
	}

	// Before Resolve, so that a cluster carrying both this section and a registry ModuleConfig is
	// installed from the latter: the module's own configuration is the deliberate statement, and
	// until now the deckhouse ModuleConfig took precedence over it.
	initConfig, deckhouseSettings, err := registry.FoldLegacyDirectIntoInit(initConfig, deckhouseSettings)
	if err != nil {
		return nil, err
	}

	deckhouseSettings, opts := bundleFacts.Resolve(deckhouseSettings)

	return registry.NewConfigProvider(initConfig, deckhouseSettings, opts...), nil
}

// downloadCandi replaces the registry pull in tests.
var downloadCandi image.DownloadFunc

func prepareCandiDir(ctx context.Context, conf *image.RegistryConfig, globalOptions *options.GlobalOptions) error {
	digest, err := digests.GetImage(digests.CandiSection, digests.CandiImage)
	if err != nil {
		return fmt.Errorf("get candi image digest: %w", err)
	}

	// The paths are rooted before the download. A mismatch would leave candi where nothing reads it.
	want := filepath.Join(providerdir.DigestDir(globalOptions.DownloadDir, digests.CandiImage, digest), "deckhouse")
	if globalOptions.DeckhouseDir != want {
		return fmt.Errorf("candi is unpacked into %s, but the install paths are rooted at %s: resolve the paths again after changing the download dir", want, globalOptions.DeckhouseDir)
	}

	_, err = image.EnsureUnpacked(ctx, image.UnpackRequest{
		Root:     globalOptions.DownloadDir,
		Name:     digests.CandiImage,
		Digest:   digest,
		Registry: func(context.Context) (*image.RegistryConfig, error) { return conf, nil },
	}, image.EnsureUnpackedOptions{
		Download:     downloadCandi,
		ShowProgress: globalOptions.ShowProgress,
		Prepare: func(ctx context.Context, stagingDir, finalDir string) error {
			return image.PrepareFiles(ctx, filepath.Join(stagingDir, "deckhouse"), filepath.Join(finalDir, "deckhouse"))
		},
	})
	if err != nil {
		return fmt.Errorf("unpack candi image: %w", err)
	}

	return os.MkdirAll(filepath.Join(globalOptions.DownloadDir, "plugins"), 0o755)
}

// prepare CandiDir if not exists
func PrepareCandiDir(ctx context.Context, kubeCl *client.KubernetesClient, globalOptions *options.GlobalOptions) error {
	// test only
	if globalOptions == nil {
		return nil
	}

	if !globalOptions.EnsureCandiAvailable {
		return nil
	}

	conf, _, err := registrydata.GetRegistryDataPreferUpstream(ctx, kubeCl, globalOptions.KubeInCluster)
	if err != nil {
		return err
	}

	return prepareCandiDir(ctx, conf, globalOptions)
}

func GetRPPSignCheck() bool {
	return RppSignCheck == "true"
}

// GetEdition
// returns edition in lower case
func GetEdition() string {
	return strings.ToLower(Edition)
}

// GetEdition
// returns editions map in lower case
func EEEditions() map[string]struct{} {
	editions := strings.Split(CommaSeparatedEEEditions, ",")

	res := make(map[string]struct{})
	for _, e := range editions {
		e = strings.TrimSpace(e)
		if e != "" {
			res[strings.ToLower(e)] = struct{}{}
		}
	}

	return res
}

func IsEEEdition(ed string) bool {
	ed = strings.ToLower(ed)
	editions := EEEditions()
	_, ok := editions[ed]
	return ok
}

func IsCSEdition(ed string) bool {
	return strings.ToLower(ed) == "cse"
}
