// Copyright 2026 Flant JSC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package config

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"sigs.k8s.io/yaml"

	"github.com/deckhouse/deckhouse/go_lib/registry/models/initconfig"
	"github.com/deckhouse/deckhouse/go_lib/registry/models/moduleconfig"

	"github.com/deckhouse/deckhouse/dhctl/pkg/config/digests"
	"github.com/deckhouse/deckhouse/dhctl/pkg/config/directoryconfig"
	"github.com/deckhouse/deckhouse/dhctl/pkg/config/registry"
	"github.com/deckhouse/deckhouse/dhctl/pkg/global"
	"github.com/deckhouse/deckhouse/dhctl/pkg/kubernetes/actions/registrydata"
	"github.com/deckhouse/deckhouse/dhctl/pkg/kubernetes/client"
	"github.com/deckhouse/deckhouse/dhctl/pkg/log"
	"github.com/deckhouse/deckhouse/dhctl/pkg/util/fs"
	"github.com/deckhouse/deckhouse/dhctl/pkg/util/image"
	"github.com/deckhouse/deckhouse/dhctl/pkg/util/input"
	"github.com/deckhouse/deckhouse/dhctl/pkg/util/retry"
)

var (
	deckhouseDir      = "/deckhouse"
	candiDir          = deckhouseDir + "/candi"
	modulesDir        = deckhouseDir + "/modules"
	globalHooksModule = deckhouseDir + "/global-hooks"
	versionMap        = candiDir + "/version_map.yml"

	// This value is set on the dhctl build in the dhctl/Makefile script.
	// Do not touch it !!!
	DefaultKubernetesVersion = "<autogenerated on the build stage>"
	RppSignCheck             = "false"
)

func LoadConfigFromFile(
	ctx context.Context,
	paths []string,
	preparatorProvider MetaConfigPreparatorProvider,
	dc *directoryconfig.DirectoryConfig,
	opts ...ValidateOption,
) (*MetaConfig, error) {
	if dc == nil {
		return nil, fmt.Errorf("directory config is nil")
	}

	if err := checkDirs(); err != nil {
		// download and init schemaStore
		// get registry setting first
		provider, err := RegistryConfigProvider(func() ([]string, error) {
			return FetchDocuments(paths)
		})
		if err != nil {
			return nil, err
		}
		remoteData, err := provider.RemoteData()
		if err != nil {
			return nil, err
		}

		conf, err := image.NewRegistryConfig(
			string(remoteData.Scheme),
			remoteData.ImagesRepo,
			remoteData.Username,
			remoteData.Password,
			remoteData.CA,
		)
		if err != nil {
			return nil, err
		}

		if err = prepareCandiDir(ctx, conf, dc); err != nil {
			return nil, err
		}

		// reinitialize vars and continue config parsing
		deckhouseDir = filepath.Join(dc.DownloadDir, "deckhouse")
		candiDir = filepath.Join(deckhouseDir, "candi")
		modulesDir = filepath.Join(deckhouseDir, "modules")
		globalHooksModule = filepath.Join(deckhouseDir, "global-hooks")
		versionMap = filepath.Join(candiDir, "version_map.yml")
	}
	metaConfig, err := ParseConfig(ctx, fs.RevealWildcardPaths(paths), preparatorProvider, dc, opts...)
	if err != nil {
		return nil, err
	}
	metaConfig.DownloadRootDir = dc.DownloadDir
	metaConfig.DownloadCacheDir = dc.DownloadCacheDir
	metaConfig.VersionFilePath = dc.VersionFilePath

	if metaConfig.ClusterConfig == nil {
		return nil, fmt.Errorf("ClusterConfiguration must be provided")
	}

	if err := metaConfig.LoadVersionMap(versionMap); err != nil {
		return nil, err
	}

	if err := metaConfig.LoadImagesDigests(); err != nil {
		return nil, err
	}

	if err := metaConfig.LoadInstallerVersion(); err != nil {
		return nil, err
	}

	if metaConfig.ClusterType == CloudClusterType && len(metaConfig.ProviderClusterConfig) == 0 {
		return nil, fmt.Errorf("ProviderClusterConfiguration section is required for a Cloud cluster.")
	}

	return metaConfig, nil
}

func numerateManifestLines(manifest []byte) string {
	manifestLines := strings.Split(string(manifest), "\n")
	builder := strings.Builder{}

	for index, line := range manifestLines {
		builder.WriteString(fmt.Sprintf("%d\t%s\n", index+1, line))
	}

	return builder.String()
}

func ParseConfig(
	ctx context.Context,
	paths []string,
	preparatorProvider MetaConfigPreparatorProvider,
	dc *directoryconfig.DirectoryConfig,
	opts ...ValidateOption,
) (*MetaConfig, error) {
	content := ""
	for _, path := range paths {
		if strings.Contains(path, "*") {
			continue // skip wildcard paths, we revealed them in the previous step
		}

		log.DebugF("Have config file %s\n", path)
		fileContent, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("loading config file: %v", err)
		}
		content = content + "\n\n---\n\n" + string(fileContent)
	}

	return ParseConfigFromData(ctx, content, preparatorProvider, dc, opts...)
}

func ParseConfigFromCluster(
	ctx context.Context,
	kubeCl *client.KubernetesClient,
	preparatorProvider MetaConfigPreparatorProvider,
	dc *directoryconfig.DirectoryConfig,
) (*MetaConfig, error) {
	var metaConfig *MetaConfig
	var err error

	return metaConfig, log.ProcessCtx(ctx, "common", "Get Cluster configuration", func(ctx context.Context) error {
		return retry.NewLoop("Get Cluster configuration from Kubernetes cluster", 10, 5*time.Second).
			RunContext(ctx, func() error {
				metaConfig, err = parseConfigFromCluster(ctx, kubeCl, preparatorProvider, dc)
				return err
			})
	})
}

func ParseConfigInCluster(
	ctx context.Context,
	kubeCl *client.KubernetesClient,
	preparatorProvider MetaConfigPreparatorProvider,
	dc *directoryconfig.DirectoryConfig,
) (*MetaConfig, error) {
	var (
		metaConfig *MetaConfig
		err        error
	)

	err = retry.NewSilentLoop("Get Cluster configuration from inside Kubernetes cluster", 5, 5*time.Second).
		RunContext(ctx, func() error {
			metaConfig, err = parseConfigFromCluster(ctx, kubeCl, preparatorProvider, dc)
			return err
		})
	if err != nil {
		return nil, err
	}
	return metaConfig, nil
}

func parseConfigFromCluster(ctx context.Context, kubeCl *client.KubernetesClient, preparatorProvider MetaConfigPreparatorProvider, dc *directoryconfig.DirectoryConfig) (*MetaConfig, error) {
	metaConfig := &MetaConfig{}

	if err := checkDirs(); err != nil {
		conf, b64dc, err := registrydata.GetRegistryData(ctx, kubeCl)
		if err != nil {
			return nil, err
		}

		if err = prepareCandiDir(ctx, conf, dc); err != nil {
			return nil, err
		}
		if dc == nil {
			return nil, fmt.Errorf("directory config is nil")
		}

		deckhouseDir = filepath.Join(dc.DownloadDir, "deckhouse")
		candiDir = filepath.Join(deckhouseDir, "candi")
		modulesDir = filepath.Join(deckhouseDir, "modules")
		globalHooksModule = filepath.Join(deckhouseDir, "global-hooks")
		versionMap = filepath.Join(candiDir, "version_map.yml")
		metaConfig.DeckhouseConfig.RegistryDockerCfg = b64dc
		metaConfig.DeckhouseConfig.ImagesRepo = conf.GetRegistry()
		metaConfig.DeckhouseConfig.RegistryCA = conf.GetCA()
		metaConfig.DownloadRootDir = dc.DownloadDir
		metaConfig.DownloadCacheDir = dc.DownloadCacheDir
		metaConfig.VersionFilePath = dc.VersionFilePath
	}

	schemaStore := NewSchemaStore(dc)

	clusterConfig, err := kubeCl.CoreV1().Secrets(global.ConfigsNS).Get(ctx, "d8-cluster-configuration", metav1.GetOptions{})
	if err != nil {
		return nil, err
	}

	clusterConfigData := clusterConfig.Data["cluster-configuration.yaml"]
	_, err = schemaStore.Validate(&clusterConfigData)
	if err != nil {
		return nil, err
	}

	var parsedClusterConfig map[string]json.RawMessage
	if err := yaml.Unmarshal(clusterConfigData, &parsedClusterConfig); err != nil {
		return nil, err
	}

	metaConfig.ClusterConfig = parsedClusterConfig

	var clusterType string
	if err := json.Unmarshal(parsedClusterConfig["clusterType"], &clusterType); err != nil {
		return nil, err
	}

	metaConfig.ClusterType = clusterType

	_, err = DoByClusterType(ctx, metaConfig, newFromClusterMetaConfigFiller(kubeCl, schemaStore))
	if err != nil {
		return nil, err
	}

	return metaConfig.Prepare(ctx, preparatorProvider)
}

// parseDocument
//
// parse and validate one document of
//
//		InitConfiguration
//		ClusterConfiguration
//		StaticClusterConfiguration
//		ClusterConfiguration
//	    ModuleConfig
//
// if validation schema for ModuleConfig or another resources not found returns ErrSchemaNotFound error
func parseDocument(doc string, metaConfig *MetaConfig, schemaStore *SchemaStore, opts ...ValidateOption) (bool, error) {
	doc = strings.TrimSpace(doc)
	if doc == "" {
		return false, nil
	}

	docData := []byte(doc)

	var index SchemaIndex
	err := yaml.Unmarshal(docData, &index)
	if err != nil {
		return false, fmt.Errorf("Config document unmarshal failed: %v\ndata: \n%s\n", err, numerateManifestLines(docData))
	}

	if index.Kind == ModuleConfigKind {
		moduleConfig := ModuleConfig{}
		err = yaml.Unmarshal(docData, &moduleConfig)
		if err != nil {
			return false, fmt.Errorf("Module config document unmarshal failed: %v\ndata: \n%s\n", err, numerateManifestLines(docData))
		}

		log.DebugF("Found ModuleConfig in config file %s\n", moduleConfig.Name)

		_, err = schemaStore.Validate(&docData, opts...)
		if err != nil {
			if errors.Is(err, ErrSchemaNotFound) {
				log.DebugF("Schema not found for module %s\n", moduleConfig.Name)
				return false, nil
			}
			return false, fmt.Errorf("Module config validation failed: %w\ndata: \n%s\n", err, numerateManifestLines(docData))
		}

		metaConfig.ModuleConfigs = append(metaConfig.ModuleConfigs, &moduleConfig)
		return true, nil
	}

	_, err = schemaStore.Validate(&docData, opts...)
	if err != nil {
		if errors.Is(err, ErrSchemaNotFound) {
			return false, nil
		}
		return false, fmt.Errorf("Config document validation failed: %v\ndata: \n%s\n", err, numerateManifestLines(docData))
	}

	var data map[string]json.RawMessage
	if err = yaml.Unmarshal(docData, &data); err != nil {
		return false, fmt.Errorf("Config document unmarshal failed: %v\ndata: \n%s\n", err, numerateManifestLines(docData))
	}

	found := false
	switch {
	case index.Kind == "InitConfiguration":
		log.DebugLn("Found InitConfiguration")
		metaConfig.InitClusterConfig = data
		found = true
	case index.Kind == "ClusterConfiguration":
		log.DebugLn("Found ClusterConfiguration")
		metaConfig.ClusterConfig = data
		found = true
	case index.Kind == "StaticClusterConfiguration":
		log.DebugLn("Found StaticClusterConfiguration")
		metaConfig.StaticClusterConfig = data
		found = true
	case strings.HasSuffix(index.Kind, "ClusterConfiguration"):
		log.DebugF("Found %s\n", index.Kind)
		metaConfig.ProviderClusterConfig = data
		found = true
	}

	return found, nil
}

// detectMergedDocuments checks if a document contains multiple YAML documents merged together
// (indicated by multiple top-level "kind:" or "apiVersion:" fields). This happens when the "---" separator is missing.
// When multiple apiVersion fields exist at root level, yaml.Unmarshal will overwrite previous values,
// causing the first document to be lost. This function detects such cases before parsing.
func detectMergedDocuments(doc string) error {
	doc = strings.TrimSpace(doc)
	if doc == "" {
		return nil
	}

	// First, try to unmarshal to see if it fails due to duplicate keys
	// Go's yaml library doesn't error on duplicate keys, but we can detect them by checking
	// if we have multiple root-level apiVersion/kind fields
	var rootLevelKinds []string
	var rootLevelAPIVersions []string
	lines := strings.Split(doc, "\n")

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		// Skip comments and empty lines
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}

		// Calculate current indent level (number of leading spaces/tabs)
		leadingWhitespace := len(line) - len(strings.TrimLeft(line, " \t"))

		// Only consider fields at root level (indent 0)
		if leadingWhitespace == 0 {
			if strings.HasPrefix(trimmed, "apiVersion:") {
				apiVersionValue := strings.TrimSpace(strings.TrimPrefix(trimmed, "apiVersion:"))
				if apiVersionValue != "" {
					rootLevelAPIVersions = append(rootLevelAPIVersions, apiVersionValue)
				}
			} else if strings.HasPrefix(trimmed, "kind:") {
				kindValue := strings.TrimSpace(strings.TrimPrefix(trimmed, "kind:"))
				if kindValue != "" {
					rootLevelKinds = append(rootLevelKinds, kindValue)
				}
			}
		}
	}

	// If we have multiple root-level apiVersion or kind fields, documents are likely merged
	// When unmarshaling, duplicate keys will overwrite previous values, causing data loss
	// We check for multiple of both to avoid false positives from nested structures
	if len(rootLevelAPIVersions) > 1 && len(rootLevelKinds) > 1 {
		return fmt.Errorf(
			"invalid config.yml format: missing '---' separator between documents. "+
				"Found multiple root-level 'kind' fields: %v. "+
				"Please ensure each YAML document is separated by '---' on its own line.",
			rootLevelKinds,
		)
	}

	return nil
}

func ParseConfigFromData(
	ctx context.Context,
	configData string, preparatorProvider MetaConfigPreparatorProvider,
	dc *directoryconfig.DirectoryConfig,
	opts ...ValidateOption,
) (*MetaConfig, error) {
	schemaStore := NewSchemaStore(dc)

	bigFileTmp := strings.TrimSpace(configData)
	docs := input.YAMLSplitRegexp.Split(bigFileTmp, -1)

	resourcesDocs := make([]string, 0, len(docs))

	metaConfig := MetaConfig{}
	for _, doc := range docs {
		// Check for merged documents before parsing
		if err := detectMergedDocuments(doc); err != nil {
			return nil, fmt.Errorf("config validation failed: %w\ndata:\n%s\n", err, numerateManifestLines([]byte(doc)))
		}

		found, err := parseDocument(doc, &metaConfig, schemaStore, opts...)
		if err != nil {
			return nil, err
		}
		if !found && strings.TrimSpace(doc) != "" {
			var index SchemaIndex
			_ = yaml.Unmarshal([]byte(doc), &index)
			if index.Kind != "" && index.Version != "" {
				log.DebugF("Found resource for resourcesYaml %s/%s\n", index.Kind, index.Version)
			}
			resourcesDocs = append(resourcesDocs, doc)
		}
	}

	metaConfig.ResourcesYAML = strings.TrimSpace(strings.Join(resourcesDocs, "\n\n---\n\n"))

	// init configuration can be empty, but we need default from openapi spec
	// Note: InitConfiguration can also be provided via ModuleConfig deckhouse (registry settings)
	if len(metaConfig.InitClusterConfig) == 0 {
		log.DebugF("Init configuration not found use empty")
		doc := `
apiVersion: deckhouse.io/v1
kind: InitConfiguration
deckhouse: {}
`
		found, err := parseDocument(doc, &metaConfig, schemaStore, opts...)
		if err != nil {
			return nil, err
		}
		if !found {
			return nil, fmt.Errorf("init configuration index not found")
		}
	}

	return metaConfig.Prepare(ctx, preparatorProvider)
}

func InitGlobalVars(pwd string) {
	deckhouseDir = pwd + "/deckhouse"
	candiDir = deckhouseDir + "/candi"
	modulesDir = deckhouseDir + "/modules"
	globalHooksModule = deckhouseDir + "/global-hooks"
	versionMap = candiDir + "/version_map.yml"
}

// check for existance deckhouse dir
func checkDirs() error {
	absDh, err := os.Stat("/deckhouse")
	if err != nil {
		return err
	}
	if !absDh.IsDir() {
		return fmt.Errorf("%s is not a directory", deckhouseDir)
	}

	dh, err := os.Stat(deckhouseDir)
	if err != nil {
		return err
	}
	if !dh.IsDir() {
		return fmt.Errorf("%s is not a directory", deckhouseDir)
	}

	candi, err := os.Stat(candiDir)
	if err != nil {
		return err
	}
	if !candi.IsDir() {
		return fmt.Errorf("%s is not a directory", candiDir)
	}

	return nil
}

func FetchDocuments(paths []string) ([]string, error) {
	paths = fs.RevealWildcardPaths(paths)

	content := ""
	for _, path := range paths {
		if strings.Contains(path, "*") {
			continue // skip wildcard paths, we revealed them in the previous step
		}

		log.DebugF("Have config file %s\n", path)
		fileContent, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("loading config file: %w", err)
		}
		content = content + "\n\n---\n\n" + string(fileContent)
	}

	bigFileTmp := strings.TrimSpace(content)
	docs := input.YAMLSplitRegexp.Split(bigFileTmp, -1)

	for _, doc := range docs {
		if err := detectMergedDocuments(doc); err != nil {
			return nil, fmt.Errorf("config validation failed: %w\ndata:\n%s\n", err, numerateManifestLines([]byte(doc)))
		}
	}
	return docs, nil
}

func RegistryConfigProvider(docsFetcher func() ([]string, error)) (*registry.ConfigProvider, error) {
	docs, err := docsFetcher()
	if err != nil {
		return nil, err
	}

	var (
		initConfig        *initconfig.Config
		deckhouseSettings *moduleconfig.DeckhouseSettings
	)

	for _, doc := range docs {
		var obj unstructured.Unstructured
		if err := yaml.Unmarshal([]byte(doc), &obj); err != nil {
			return nil, err
		}

		switch obj.GetKind() {
		case InitConfigurationKind:
			ret, err := registry.ParseYAMLInitConfig([]byte(doc))

			if err != nil {
				return nil, err
			}

			initConfig = ret

		case ModuleConfigKind:
			if obj.GetName() != "deckhouse" {
				continue
			}

			ret, err := registry.ParseYAMLDeckhouseMC([]byte(doc))
			if err != nil {
				return nil, err
			}

			deckhouseSettings = ret
		}
	}
	return registry.NewConfigProvider(initConfig, deckhouseSettings), nil
}

func prepareCandiDir(ctx context.Context, conf *image.RegistryConfig, dc *directoryconfig.DirectoryConfig) error {
	candiImage, err := digests.GetImage("common", "candi")
	if err != nil {
		return err
	}

	if dc == nil {
		return fmt.Errorf("directory config is nil")
	}

	imgName := conf.GetRegistry() + "@" + candiImage

	if err = image.DownloadAndUnpackImage(ctx, imgName, dc.DownloadDir, dc.DownloadCacheDir, *conf); err != nil {
		return err
	}

	err = image.PrepareFiles(filepath.Join(dc.DownloadDir, "deckhouse"))
	if err != nil {
		return err
	}

	return os.MkdirAll(filepath.Join(dc.DownloadDir, "plugins"), 0o755)
}

// prepare CandiDir if not exists
func PrepareCandiDir(ctx context.Context, kubeCl *client.KubernetesClient, logger log.Logger, dc *directoryconfig.DirectoryConfig) error {
	if err := checkDirs(); err == nil {
		return nil
	}

	conf, _, err := registrydata.GetRegistryData(ctx, kubeCl)
	if err != nil {
		return err
	}

	return prepareCandiDir(ctx, conf, dc)
}

func GetRPPSignCheck() bool {
	return RppSignCheck == "true"
}
