{{- if and (include "helm_lib_kind_exists" (list . "ValidatingAdmissionPolicy")) (include "helm_lib_kind_exists" (list . "ValidatingAdmissionPolicyBinding")) }}
{{- $policyName := "capi-cluster-deletion.deckhouse.io" }}
---
apiVersion: {{ include "helm_lib_get_api_version_by_kind" (list . "ValidatingAdmissionPolicy") }}
kind: ValidatingAdmissionPolicy
metadata:
  name: {{ $policyName }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "deckhouse") ) | nindent 2 }}
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: ["cluster.x-k8s.io"]
        apiVersions: ["*"]
        operations: ["DELETE"]
        resources: ["clusters"]
        scope: Namespaced
  validations:
    - expression: |
        request.namespace != "d8-cloud-instance-manager"
        || request.userInfo.username == "dhctl"
      reason: Forbidden
      message: "Deleting a CAPI Cluster from the d8-cloud-instance-manager namespace is forbidden."
---
apiVersion: {{ include "helm_lib_get_api_version_by_kind" (list . "ValidatingAdmissionPolicyBinding") }}
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: {{ $policyName }}-binding
  {{- include "helm_lib_module_labels" (list . (dict "app" "deckhouse") ) | nindent 2 }}
spec:
  policyName: {{ $policyName }}
  validationActions: [Deny, Audit]
{{- end }}
