// Copyright 2025 Flant JSC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	deckhouseiov1alpha1 "github.com/deckhouse/deckhouse/deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1"
	scheme "github.com/deckhouse/deckhouse/deckhouse-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ModuleUpdatePoliciesGetter has a method to return a ModuleUpdatePolicyInterface.
// A group's client should implement this interface.
type ModuleUpdatePoliciesGetter interface {
	ModuleUpdatePolicies() ModuleUpdatePolicyInterface
}

// ModuleUpdatePolicyInterface has methods to work with ModuleUpdatePolicy resources.
type ModuleUpdatePolicyInterface interface {
	Create(ctx context.Context, moduleUpdatePolicy *deckhouseiov1alpha1.ModuleUpdatePolicy, opts v1.CreateOptions) (*deckhouseiov1alpha1.ModuleUpdatePolicy, error)
	Update(ctx context.Context, moduleUpdatePolicy *deckhouseiov1alpha1.ModuleUpdatePolicy, opts v1.UpdateOptions) (*deckhouseiov1alpha1.ModuleUpdatePolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*deckhouseiov1alpha1.ModuleUpdatePolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*deckhouseiov1alpha1.ModuleUpdatePolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *deckhouseiov1alpha1.ModuleUpdatePolicy, err error)
	ModuleUpdatePolicyExpansion
}

// moduleUpdatePolicies implements ModuleUpdatePolicyInterface
type moduleUpdatePolicies struct {
	*gentype.ClientWithList[*deckhouseiov1alpha1.ModuleUpdatePolicy, *deckhouseiov1alpha1.ModuleUpdatePolicyList]
}

// newModuleUpdatePolicies returns a ModuleUpdatePolicies
func newModuleUpdatePolicies(c *DeckhouseV1alpha1Client) *moduleUpdatePolicies {
	return &moduleUpdatePolicies{
		gentype.NewClientWithList[*deckhouseiov1alpha1.ModuleUpdatePolicy, *deckhouseiov1alpha1.ModuleUpdatePolicyList](
			"moduleupdatepolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *deckhouseiov1alpha1.ModuleUpdatePolicy { return &deckhouseiov1alpha1.ModuleUpdatePolicy{} },
			func() *deckhouseiov1alpha1.ModuleUpdatePolicyList {
				return &deckhouseiov1alpha1.ModuleUpdatePolicyList{}
			},
		),
	}
}
