// Copyright 2025 Flant JSC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	deckhouseiov1alpha1 "github.com/deckhouse/deckhouse/deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1"
	scheme "github.com/deckhouse/deckhouse/deckhouse-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ModuleSettingsDefinitionsGetter has a method to return a ModuleSettingsDefinitionInterface.
// A group's client should implement this interface.
type ModuleSettingsDefinitionsGetter interface {
	ModuleSettingsDefinitions() ModuleSettingsDefinitionInterface
}

// ModuleSettingsDefinitionInterface has methods to work with ModuleSettingsDefinition resources.
type ModuleSettingsDefinitionInterface interface {
	Create(ctx context.Context, moduleSettingsDefinition *deckhouseiov1alpha1.ModuleSettingsDefinition, opts v1.CreateOptions) (*deckhouseiov1alpha1.ModuleSettingsDefinition, error)
	Update(ctx context.Context, moduleSettingsDefinition *deckhouseiov1alpha1.ModuleSettingsDefinition, opts v1.UpdateOptions) (*deckhouseiov1alpha1.ModuleSettingsDefinition, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*deckhouseiov1alpha1.ModuleSettingsDefinition, error)
	List(ctx context.Context, opts v1.ListOptions) (*deckhouseiov1alpha1.ModuleSettingsDefinitionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *deckhouseiov1alpha1.ModuleSettingsDefinition, err error)
	ModuleSettingsDefinitionExpansion
}

// moduleSettingsDefinitions implements ModuleSettingsDefinitionInterface
type moduleSettingsDefinitions struct {
	*gentype.ClientWithList[*deckhouseiov1alpha1.ModuleSettingsDefinition, *deckhouseiov1alpha1.ModuleSettingsDefinitionList]
}

// newModuleSettingsDefinitions returns a ModuleSettingsDefinitions
func newModuleSettingsDefinitions(c *DeckhouseV1alpha1Client) *moduleSettingsDefinitions {
	return &moduleSettingsDefinitions{
		gentype.NewClientWithList[*deckhouseiov1alpha1.ModuleSettingsDefinition, *deckhouseiov1alpha1.ModuleSettingsDefinitionList](
			"modulesettingsdefinitions",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *deckhouseiov1alpha1.ModuleSettingsDefinition {
				return &deckhouseiov1alpha1.ModuleSettingsDefinition{}
			},
			func() *deckhouseiov1alpha1.ModuleSettingsDefinitionList {
				return &deckhouseiov1alpha1.ModuleSettingsDefinitionList{}
			},
		),
	}
}
