// Copyright 2025 Flant JSC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	deckhouseiov1alpha1 "github.com/deckhouse/deckhouse/deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1"
	scheme "github.com/deckhouse/deckhouse/deckhouse-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ModulePackagesGetter has a method to return a ModulePackageInterface.
// A group's client should implement this interface.
type ModulePackagesGetter interface {
	ModulePackages() ModulePackageInterface
}

// ModulePackageInterface has methods to work with ModulePackage resources.
type ModulePackageInterface interface {
	Create(ctx context.Context, modulePackage *deckhouseiov1alpha1.ModulePackage, opts v1.CreateOptions) (*deckhouseiov1alpha1.ModulePackage, error)
	Update(ctx context.Context, modulePackage *deckhouseiov1alpha1.ModulePackage, opts v1.UpdateOptions) (*deckhouseiov1alpha1.ModulePackage, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, modulePackage *deckhouseiov1alpha1.ModulePackage, opts v1.UpdateOptions) (*deckhouseiov1alpha1.ModulePackage, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*deckhouseiov1alpha1.ModulePackage, error)
	List(ctx context.Context, opts v1.ListOptions) (*deckhouseiov1alpha1.ModulePackageList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *deckhouseiov1alpha1.ModulePackage, err error)
	ModulePackageExpansion
}

// modulePackages implements ModulePackageInterface
type modulePackages struct {
	*gentype.ClientWithList[*deckhouseiov1alpha1.ModulePackage, *deckhouseiov1alpha1.ModulePackageList]
}

// newModulePackages returns a ModulePackages
func newModulePackages(c *DeckhouseV1alpha1Client) *modulePackages {
	return &modulePackages{
		gentype.NewClientWithList[*deckhouseiov1alpha1.ModulePackage, *deckhouseiov1alpha1.ModulePackageList](
			"modulepackages",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *deckhouseiov1alpha1.ModulePackage { return &deckhouseiov1alpha1.ModulePackage{} },
			func() *deckhouseiov1alpha1.ModulePackageList { return &deckhouseiov1alpha1.ModulePackageList{} },
		),
	}
}
