#!/usr/bin/env bash

# Copyright 2024 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /shell_lib.sh

function __config__(){
  cat <<EOF
configVersion: v1
kubernetes:
  - name: clusterRoles
    apiVersion: rbac.authorization.k8s.io
    kind: ClusterRole
    queue: authorization
    group: authorization
    executeHookOnEvent: []
    executeHookOnSynchronization: false
    keepFullObjectsInMemory: false
    labelSelector:
      matchLabels:
        rbac.deckhouse.io/kind: use
    jqFilter: |
      {
        "name": .metadata.name
      }
kubernetesValidating:
- name: rbac-use-validating.deckhouse.io
  group: authorization
  rules:
  - apiGroups:   ["rbac.authorization.k8s.io"]
    apiVersions: ["*"]
    operations:  ["CREATE"]
    resources:   ["clusterrolebindings"]
    scope:       "Cluster"
EOF
}

function __main__() {
  clusterRoleName=$(context::jq -r '.review.request.object.roleRef.name')
  if foundName="$(context::jq -er --arg roleName "$clusterRoleName" '[.snapshots.clusterRoles[] | select(.name == $roleName) | .name] | first' 2>&1)"; then
        cat <<EOF > "$VALIDATING_RESPONSE_PATH"
{"allowed":false, "message":"Role \"$foundName\" cannot be used in ClusterRoleBinding.}
EOF
  fi
  cat <<EOF > "$VALIDATING_RESPONSE_PATH"
{"allowed":true}
EOF
}

hook::run "$@"