{
 "title": "Home",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\n  <img src=/public/img/deckhouse-logo.svg/>\n</center>\n"
   }
  },
  {
   "title": "Deckhouse",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (version, edition) (deckhouse_build_info{job=\"deckhouse\"})",
     "legendFormat": "{{ version }} {{ edition }}"
    }
   ]
  },
  {
   "title": "Release Channel",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (release_channel) (label_replace(deckhouse_release_channel{job=\"deckhouse\"}, \"release_channel\", \"Undefined\", \"release_channel\", \"\"))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CRI Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (container_runtime_version) (kube_node_info)",
     "legendFormat": "{{ container_runtime_version }}"
    }
   ]
  },
  {
   "title": "OS Image",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (os_image) (kube_node_info)",
     "legendFormat": "{{ git_version }}"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (phase) (kube_pod_status_phase == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (label_node_deckhouse_io_group) (label_replace(kube_node_labels, \"label_node_deckhouse_io_group\", \"unknown\", \"label_node_deckhouse_io_group\", \"\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Controllers",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (controller_type) (count by (controller_type, controller_name, namespace) (kube_controller_pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (type) (kube_service_spec_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (version) (deckhouse_kubernetes_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by (server_version) (etcd_server_version{job=\"kube-etcd3\"})",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by (version, namespace) (prometheus_build_info{service=\"prometheus\", namespace=\"d8-monitoring\"})",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by (version, namespace) (grafana_build_info{service=\"grafana-v10\", namespace=\"d8-monitoring\"})",
     "legendFormat": "{{ version }} {{ edition }}"
    }
   ]
  },
  {
   "title": "Overview of Deckhouse controller",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 }
  },
  { "title": "Prometheus Metrics", "type": "dashlist", "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 } },
  {
   "title": "Main",
   "type": "dashlist",
   "description": "Drill down is an analytics capability that allows users to instantly shift from an overview of data to a more detailed and granular view within the same dataset they are analyzing by clicking on a metric in a dashboard or report.\n\nNamespaces -> Namespace -> Namespace / Controller -> Namespace / Controller / Pod",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 6 }
  },
  { "title": "Nodes", "type": "dashlist", "gridPos": { "h": 12, "w": 4, "x": 12, "y": 6 } },
  { "title": "Ingress Nginx", "type": "dashlist", "gridPos": { "h": 12, "w": 4, "x": 16, "y": 6 } },
  {
   "title": "Enabled modules",
   "type": "table",
   "description": "List of all enabled modules (explicitly enabled and enabled by default).  If you click on a module name, the documentation for the module will be opened.",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 6 },
   "targets": [
    {
     "expr": "(\nmax by (module, module_name, docs_url) (\n(\n    label_replace(deckhouse_web_interfaces{job=\"deckhouse\", name=\"docs\"}, \"docs_url\", \"$1/en\", \"url\", \"(.*)\")\n)\n    + on (job) group_right(docs_url)\n(\n    label_replace(deckhouse_binding_count{module!=\"\", module!~\".+-crd\", module!=\"helm\", module!=\"deckhouse-config\", module!=\"basic-auth\", module!=\"monitoring-applications\"}, \"module_name\", \"$1\", \"hook\", \"([0-9]+[A-Za-z-]+).*\")\n)\n)\nand on() (deckhouse_web_interfaces{job=\"deckhouse\", name=\"docs\"} >0)\n)\nor on()\n(max by (module, module_name, docs_url) (\nlabel_replace(label_replace(deckhouse_binding_count{module!=\"\", module!~\".+-crd\", module!=\"helm\", module!=\"deckhouse-config\", module!=\"basic-auth\", module!=\"monitoring-applications\"}, \"module_name\", \"$1\", \"hook\", \"([0-9]+[A-Za-z-]+).*\"), \"docs_url\", \"deckhouse.io/documentation/v1\", \"\", \"\")\n))\n",
     "legendFormat": "{{ module }}"
    }
   ]
  },
  {
   "title": "Web Interfaces",
   "type": "table",
   "description": "Links to web interfaces of Deckhouse modules. An interface is added to the list automatically if module is enabled.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (icon, name, url) (deckhouse_web_interfaces{job=\"deckhouse\"})"
    }
   ]
  },
  {
   "title": "Oldest metrics in Prometheus",
   "type": "table",
   "description": "Difference between the oldest timestamp in the Prometheus tsdb and the current time. It shows how far in the past Prometheus instance collect the stats.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "targets": [
    {
     "expr": "max by (service) (time() - prometheus_tsdb_lowest_timestamp_seconds{service=~\"prometheus|prometheus-longterm\", namespace=\"d8-monitoring\"}) / 60 / 60 / 24",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update Mode",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (mode) (label_replace(d8_telemetry_update_window_approval_mode, \"mode\", \"Auto\", \"mode\", \"\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update Windows",
   "type": "table",
   "description": "Intervals in which Deckhouse can start its updating. No Data means that Deckhouse can be updated anytime.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "targets": [
    {
     "expr": "max by (from, to, days) (d8_telemetry_update_window)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources management", "type": "dashlist", "gridPos": { "h": 3, "w": 4, "x": 8, "y": 14 } }
 ]
}