{{- define "yandex_cdd_pod_annotations" -}}
checksum/config: {{ include (print $.Template.BasePath "/cloud-controller-manager/secret.yaml") . | sha256sum }}
{{- end -}}

{{- define "yandex_cdd_envs" -}}
- name: YC_FOLDER_ID
  value: {{ .Values.cloudProviderYandex.internal.providerClusterConfiguration.provider.folderID }}
- name: YC_SA_KEY_JSON
  valueFrom:
    secretKeyRef:
      name: cloud-controller-manager
      key: service-acount-json
- name: CLUSTER_UUID
  value: {{ .Values.global.discovery.clusterUUID | quote }}
{{- end -}}

{{- define "yandex_cdd_init_containers" -}}
- name: migrator
  {{- include "helm_lib_module_container_security_context_read_only_root_filesystem_capabilities_drop_all" . | nindent 2 }}
  image: {{ include "helm_lib_module_image" (list . "cloudMigrator") }}
  env:
  - name: YC_FOLDER_ID
    value: {{ .Values.cloudProviderYandex.internal.providerClusterConfiguration.provider.folderID }}
  - name: YC_SA_KEY_JSON
    valueFrom:
      secretKeyRef:
        name: cloud-controller-manager
        key: service-acount-json
  - name: CLUSTER_UUID
    value: {{ .Values.global.discovery.clusterUUID | quote }}
  resources:
    requests:
      {{- include "helm_lib_module_ephemeral_storage_logs_with_extra" 10 | nindent 6 }}
{{- end -}}

{{- $cddConfig := dict -}}
{{- $_ := set $cddConfig "fullname" "cloud-data-discoverer" -}}
{{- $_ := set $cddConfig "image" (include "helm_lib_module_image" (list . "cloudDataDiscoverer")) -}}
{{- $_ := set $cddConfig "additionalEnv" (include "yandex_cdd_envs" . | fromYamlArray) -}}
{{- $_ := set $cddConfig "additionalPodAnnotations" (include "yandex_cdd_pod_annotations" . | fromYaml) -}}
{{- $_ := set $cddConfig "additionalInitContainers" (include "yandex_cdd_init_containers" . | fromYamlArray) -}}
{{- $_ := set $cddConfig "vpaEnabled" true -}}

{{- include "helm_lib_cloud_data_discoverer_manifests" (list . $cddConfig) }}
