source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-assets'
gem 'html-proofer'
gem 'jekyll-regex-replace'
gem 'kramdown-parser-gfm'
gem 'jekyll_include_plugin'

gem "sprockets", "~> 3.7"
gem "nokogiri", ">= 1.10.8"
