source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-regex-replace'
gem 'kramdown-parser-gfm'
gem 'jekyll_include_plugin'
gem "jekyll_asset_pipeline"
gem "sass"
gem 'cssminify2'
gem "octicons"
gem "nokogiri"
