#!/bin/bash

MODULES_DIR=${MODULES_DIR:modules}

if [ -f modules_menu_skip ]; then
  modules_skip_list=$(cat modules_menu_skip)
fi

modules_list=$(find $MODULES_DIR -regex '.*/docs/README.md' -print | cut -d\/ -f2 | sort | uniq)
echo
# construct documentation menu
echo "modules_items: &modules_items"
#cat << YAML
#  - title: Общие сведения
#    url: /modules/
#YAML
for module in $modules_list ; do
  skip=false
  for el in $modules_skip_list ; do
    if [[ $el == $module ]] ; then skip=true; break; fi
  done
  # Skip modules with README without front matter
  head -n 1 ./$MODULES_DIR/$module/docs/README.md | grep -q "^---" &> /dev/null
  if [ $? -ne 0 ]; then skip=true; fi
  if [[ $skip == 'false' ]]; then
    subfolders=""
    subfolders_rawset=$(find $MODULES_DIR/$module/docs/ -regex '.*.md' -print | sed -E "s#modules(_en|_ru)/$module/docs/##" | sort | uniq | grep -ivE '^features.md|^readme.md')
    for subfolder_item in $subfolders_rawset ; do
      head -n 1 ./$MODULES_DIR/$module/docs/$subfolder_item | grep -l "^---" &> /dev/null
      if [ $? -eq 0 ]; then
        subfolders="${subfolders}${subfolders:+ }${subfolder_item}"
      fi
    done
    cat << YAML
  - title: $(echo $module | cut -d- -f2-)
    url: /$MODULES_DIR/$module/
YAML
    if [[ ${#subfolders} -gt 0 ]]; then
      # Construct submenu
      cat << YAML
    subfolderitems:
    - title: Описание модуля
      url: /$MODULES_DIR/$module/
YAML
      for subfolder_item in $subfolders ; do
        subfolder_item_title=$(cat ./$MODULES_DIR/$module/docs/$subfolder_item | grep -i 'sidebartitle:' | cut -d: -f2- | sed -e 's/^[[:space:]]*//')
        if [[ ${#subfolder_item_title} -lt 1 ]]; then
          subfolder_item_title=$(cat ./$MODULES_DIR/$module/docs/$subfolder_item | grep -i 'title:' | cut -d: -f2- | sed -e 's/^[[:space:]]*//')
        fi
        subfolder_item_url=$(cat ./$MODULES_DIR/$module/docs/$subfolder_item | grep -i 'permalink:' | cut -d: -f2- | sed -e 's/^[[:space:]]*//')
    cat << YAML
    - title: $subfolder_item_title
      url: $subfolder_item_url
YAML
      done
    fi
    # Move files from docs/ directory up one level to preserve relative assets link
    #if [ -d ./$MODULES_DIR/$module/docs/ ] && [ -n "$(ls -A ./$MODULES_DIR/$module/docs/)" ]; then mv -f ./$MODULES_DIR/$module/docs/* ./$MODULES_DIR/$module/ ; fi
  fi
done
