#!/bin/bash

if [ -f modules_menu_skip ]; then
  modules_skip_list=$(cat modules_menu_skip)
fi

modules_list=$(find modules -regex '.*/docs/README.md' -print | grep -iv '/docs/features.md' | cut -d\/ -f2 | sort | uniq)

echo "modules_items: &modules_items"
for module in $modules_list ; do
  skip=false
  for el in $modules_skip_list ; do
    if [[ $el == $module ]] ; then skip=true; break; fi
  done
  # Skip modules with README without front matter
  head -n 1 ./modules/$module/docs/README.md | grep -q "^---" &> /dev/null
  if [ $? -ne 0 ]; then skip=true; fi
  if [[ $skip == 'false' ]]; then
    subfolders=""
    subfolders_raw=$(find modules/$module/docs/ -regex '.*.md' -print | sed "s#modules/$module/docs/##" | sort | uniq | grep -ivE '^features.md|^readme.md')
    for subfolder_item in $subfolders_raw ; do
      head -n 1 ./modules/$module/docs/$subfolder_item | grep -l "^---" &> /dev/null
      if [ $? -eq 0 ]; then
        subfolders="${subfolders}${subfolders:+ }${subfolder_item}"
      fi
    done
    cat << YAML
  - title: $module
    url: /modules/$module/
YAML
    if [[ ${#subfolders} -gt 0 ]]; then
      # Construct submenu
      cat << YAML
    subfolderitems:
    - title: Описание модуля
      url: /modules/$module/
YAML
      for subfolder_item in $subfolders ; do
        subfolder_item_title=$(cat ./modules/$module/docs/$subfolder_item | grep -i 'sidebartitle:' | cut -d: -f2- | sed -e 's/^[[:space:]]*//')
        if [[ ${#subfolder_item_title} -lt 1 ]]; then
          subfolder_item_title=$(cat ./modules/$module/docs/$subfolder_item | grep -i 'title:' | cut -d: -f2- | sed -e 's/^[[:space:]]*//')
        fi
        subfolder_item_url=$(cat ./modules/$module/docs/$subfolder_item | grep -i 'permalink:' | cut -d: -f2- | sed -e 's/^[[:space:]]*//')
    cat << YAML
    - title: $subfolder_item_title
      url: $subfolder_item_url
YAML
      done
    fi
    # Move files from docs/ directory up one level to preserve relative assets link
    if [ -d ./modules/$module/docs/ ] && [ -n "$(ls -A ./modules/$module/docs/)" ]; then mv -f ./modules/$module/docs/* ./modules/$module/ ; fi
  fi
done
