#!/bin/bash
# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -Eeo pipefail
PACKAGES_TO_INSTALL=""
if ! rpm --quiet -q "$(rpm -qip container-selinux.x86_64.rpm | grep Name | awk '{print $3}')"; then
  PACKAGES_TO_INSTALL="container-selinux.x86_64.rpm"
fi
if ! rpm --quiet -q "$(rpm -qip containerd.io.x86_64.rpm | grep Name | awk '{print $3}')"; then
  PACKAGES_TO_INSTALL="${PACKAGES_TO_INSTALL} containerd.io.x86_64.rpm"
fi
if [[ -n "${PACKAGES_TO_INSTALL}" ]]; then
  rpm -U ${PACKAGES_TO_INSTALL}
fi
yum versionlock add container-selinux containerd.io
