#!/bin/bash

# Copyright 2021 Flant CJSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: antiopa_secrets
      group: main
      keepFullObjectsInMemory: false
      waitForSynchronization: false
      apiVersion: v1
      kind: Secret
      namespace:
        nameSelector:
          matchNames: ["antiopa"]
      jqFilter: |
        {
          "name": .metadata.name,
          "labels": .metadata.labels
        }
EOF
}

function __main__() {
  secrets="$(context::jq -r '
    .snapshots.antiopa_secrets[].filterResult | select(
      (.labels."antiopa-secret-copier" == "yes" | not) and
      (.labels."secret-copier.deckhouse.io/enabled" == "" | not) and
      (.name|test("default-token.") | not) and
      (.name|test("antiopa-token.") | not) and 
      (.name|test("antiopa-registry") | not)
    ) | .name'
  )"
  if [ ! -z "$secrets" ] ; then
    echo '{"name":"d8_secrets_from_antiopa_namespace_should_be_migrated", "set": 1}' >> $METRICS_PATH
  else
    echo '{"name":"d8_secrets_from_antiopa_namespace_should_be_migrated", "set": 0}' >> $METRICS_PATH
  fi
}

hook::run $@
