#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: antiopa_secrets
      includeSnapshotsFrom: ["antiopa_secrets"]
      waitForSynchronization: false
      apiVersion: v1
      kind: Secret
      namespace:
        nameSelector:
          matchNames: ["antiopa"]
EOF
}

function __main__() {
  secrets="$(context::jq -r '.snapshots.antiopa_secrets' | jq '.[].object | select((.metadata.labels."antiopa-secret-copier" == "yes" | not) and (.metadata.labels."secret-copier.deckhouse.io/enabled" == "" | not) and (.metadata.name|test("default-token.") | not) and (.metadata.name|test("antiopa-token.") | not) and (.metadata.name|test("antiopa-registry") | not)) | .metadata.name' -r)"
  if [ ! -z "$secrets" ] ; then
    echo '{"name":"d8_secrets_from_antiopa_namespace_should_be_migrated", "set": 1}' >> $METRICS_PATH
  else
    echo '{"name":"d8_secrets_from_antiopa_namespace_should_be_migrated", "set": 0}' >> $METRICS_PATH
  fi
}

hook::run $@
