#!/bin/bash

# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Hook detects how dns is implemented in the cluster. Basically it just detects deployment name with labels `k8s-app: kube-dns`

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 10
    kubernetes:
    - name: kube_dns_deployment
      group: main
      queue: /modules/$(module::name::kebab_case)
      keepFullObjectsInMemory: false
      apiVersion: apps/v1
      kind: Deployment
      namespace:
        nameSelector:
          matchNames: [kube-system]
      labelSelector:
        matchExpressions:
        - key: k8s-app
          operator: In
          values:
          - kube-dns
          - coredns
      jqFilter: '.metadata.name'
      executeHookOnEvent: ["Added", "Modified"]
EOF
}

function __main__() {
  if values::array_has global.enabledModules "kube-dns" ; then
    values::set monitoringKubernetes.internal.clusterDNSImplementation "coredns"
    return 0
  fi

  if ! context::jq -rce '.snapshots.kube_dns_deployment | length == 1'; then
    >&2 echo "ERROR: can't determine cluster DNS implementation."
    return 1
  fi

  values::set monitoringKubernetes.internal.clusterDNSImplementation "$(context::get snapshots.kube_dns_deployment.0.filterResult)"
}

hook::run "$@"
