#!/bin/bash

# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


source /deckhouse/shell_lib.sh

function __config__() {
# TODO
#{
#  "beforeHelm": 20,
#   "onKubernetesEvent": [
#      {
#         "kind": "node",
#         "event": [
#            "add",
#            "update",
#            "delete"
#         ],
#         "jqFilter": ".status.capacity.pods"
#      }
#   ]
#}'

  cat << EOF
    configVersion: v1
    beforeHelm: 20
    schedule:
    - name: detect_vpa_max
      queue: /modules/$(module::name::kebab_case)/detect_vpa_max
      crontab: "*/10 * * * *"
EOF
}

function __main__() {
  # Kube-state-metrics resources
  memory_per_node="30"
  cpu_per_node="15"
  node_count=$(kubectl get nodes -o json | jq '.items | length')
  max_memory="$(bc -l <<< "scale=0; 150 + ($node_count * $memory_per_node / 1)")Mi"
  max_cpu="$(bc -l <<< "scale=0; 100 + ($node_count * $cpu_per_node / 1)")"
  values::set monitoringKubernetes.internal.vpa.kubeStateMetricsMaxMemory "$max_memory"
  values::set monitoringKubernetes.internal.vpa.kubeStateMetricsMaxCPU "$max_cpu"
}

hook::run "$@"
