#!/bin/bash

# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: storageclasses
      group: main
      queue: /modules/$(module::name::kebab_case)
      apiVersion: storage.k8s.io/v1
      kind: Storageclass
      keepFullObjectsInMemory: false
      jqFilter: |
        {
          "name": .metadata.name,
          "isDefault": (
            (.metadata.annotations."storageclass.beta.kubernetes.io/is-default-class" == "true") or
            (.metadata.annotations."storageclass.kubernetes.io/is-default-class" == "true")
          )
        }
EOF
}

function __main__() {
  group="/modules/$(module::name::kebab_case)/storage_class_default_duplicate"
  jq -c --arg group "$group" '.group = $group' <<< '{"action":"expire"}' >> $METRICS_PATH
  if context::jq -er '([.snapshots.storageclasses[].filterResult | select(.isDefault == true)] | length) > 1'; then
    context::jq -c --arg group "$group" '
      .snapshots.storageclasses[].filterResult | select(.isDefault == true) |
      {
        "name": "storage_class_default_duplicate",
        "group": "\($group)",
        "set": 1,
        "labels":
        {
          "name": .name
        }
      }
      ' >> $METRICS_PATH
  fi
}

hook::run $@
