# frozen_string_literal: true

require "digest"
require "fileutils"
require "json"
require "yaml"

require_relative "html_to_markdown"
require_relative "navigation_helper"

module Jekyll
  # Publishes the AI-friendly exports of the documentation:
  #
  #   <lang>/<page path>.md              per-page Markdown body
  #   <lang>/<ai_export.corpusFileName> RAG corpus: metadata + Markdown + chunks
  #   <lang>/<ai_export.llmsFileName>   llms.txt index, grouped by the sidebar tree
  #
  # All settings live under the `ai_export` mapping in the site config. Disabled
  # unless `ai_export.enabled` is true, and the two file names come from the
  # config as well: the same source tree is built several times (the
  # documentation itself and the embedded modules, see
  # `werf-documentation-static.inc.yaml` and `werf-modules-static.inc.yaml`),
  # and those builds publish their indexes side by side under different names.
  # `ai_export.root` marks the build whose llms.txt is the entry point of the
  # site, the one that points an agent at the corpora. (Not to be confused with
  # the per-page `ai_export: false` front-matter flag, which excludes a page.)
  #
  # It runs on `site, :post_write` rather than as a Liquid template (the way
  # `search.json` is built) because `page.content` inside Liquid depends on the
  # page render order, while `page.output` is guaranteed to be complete here.
  module AiExport
    CORPUS_VERSION = 1
    PRODUCT_CODE = "kubernetes-platform"
    GENERATOR = "jekyll"

    # Settings mapping in the site config and its subkeys.
    CONFIG_KEY = "ai_export"
    ENABLED_KEY = "enabled"
    ROOT_KEY = "root"
    LLMS_NAME_KEY = "llmsFileName"
    CORPUS_NAME_KEY = "corpusFileName"

    DEFAULT_LLMS_NAME = "llms.txt"
    DEFAULT_CORPUS_NAME = "corpus.json"

    # `--config a.yml,b.yml` deep-merges plain YAML, so a flag arrives as a real
    # boolean; a string is accepted too, since an `enabled` that reads as "true"
    # and silently exports nothing would be baffling.
    def self.truthy?(value)
      value == true || value.to_s.strip.casecmp("true").zero?
    end

    def self.config(site)
      cfg = site.config[CONFIG_KEY]
      cfg.is_a?(Hash) ? cfg : {}
    end

    def self.enabled?(site)
      truthy?(config(site)[ENABLED_KEY])
    end

    # An H2 section longer than this is split further, by H3.
    MAX_CHUNK_CHARS = 6000

    # Pages generated by `render-jsonschema.rb`. `custom_hooks.rb` drops them
    # from the search index (`searchable: false`), but for an agent they are the
    # single most valuable reference on the site, so they are exported anyway.
    REFERENCE_PAGE_NAMES = /(CONFIGURATION|CR|CLUSTER_CONFIGURATION)(\.ru|_RU)?\.md\z/i.freeze

    HEADING_LINE = /\A(\#{1,6})\s+(.*)\z/.freeze
    # heading() appends the anchor as ` {#id}`; strip it back off before matching
    # a heading line to the Heading collected during conversion.
    HEADING_ANCHOR = /\s*\{#[^}]*\}\s*\z/.freeze
    FENCE_START = /\A(`{3,}|~{3,})/.freeze

    LANG_PREFIX = %r{\A/(en|ru)}.freeze
    # Embedded module pages are published outside the versioned documentation
    # prefix: `/en/modules/user-authn/` is served as `/modules/user-authn/`.
    MODULE_PREFIX = %r{\A/(en|ru)/modules/}.freeze
    # The URL templates whose directory links are rewritten to `index.md` — the
    # documentation and the modules library.
    INDEX_MD_PATH = %r{\A/(?:products/[^/]+/documentation|modules)/}.freeze

    class Exporter
      def initialize(site)
        @site = site
        @doc_prefix = site.config["canonical_url_prefix_documentation"].to_s.sub(%r{/+\z}, "")
        @urls = site.config["urls"] || {}
        cfg = AiExport.config(site)
        @llms_name = file_name(cfg[LLMS_NAME_KEY], DEFAULT_LLMS_NAME)
        @corpus_name = file_name(cfg[CORPUS_NAME_KEY], DEFAULT_CORPUS_NAME)
        @root = AiExport.truthy?(cfg[ROOT_KEY])
      end

      def run
        pages = @site.pages.select { |page| exportable?(page) }
        return if pages.empty?

        pages.group_by { |page| lang_of(page) }.each do |lang, lang_pages|
          documents = lang_pages.filter_map { |page| export_page(page, lang) }
          next if documents.empty?

          documents.sort_by! { |doc| doc["path"] }
          write_corpus(lang, documents)
          write_llms_txt(lang, documents)
        end
      end

      private

      # A name is a single file name, not a path: the exports always land next
      # to each other in `<dest>/<lang>/`, and the URLs published in llms.txt
      # are built from it.
      def file_name(value, fallback)
        name = File.basename(value.to_s.strip)
        return fallback if name.empty? || name == "."

        name
      end

      # --- page selection --------------------------------------------------

      def exportable?(page)
        return false if page.data["ai_export"] == false
        return false unless page.output.is_a?(String)
        return false unless page.url.end_with?("/") || page.url.end_with?(".html")
        return false if page.data["layout"].to_s == "none"
        return false unless page.url.match?(%r{\A/(en|ru)/})
        return true if page.data["searchable"] == true

        # Pages dropped from the search index but valuable to an agent: the FAQ
        # index (its answers are assembled from an include) and the OpenAPI
        # reference pages.
        return true if page.data["faqIndexPage"] == true

        page.name.to_s.match?(REFERENCE_PAGE_NAMES)
      end

      def lang_of(page)
        page.data["lang"] || (page.url.start_with?("/ru/") ? "ru" : "en")
      end

      # --- per-page export -------------------------------------------------

      def export_page(page, lang)
        url = public_url(page)
        converted = convert(page, lang, url)
        return nil if converted.nil?

        markdown = converted.markdown
        return nil if markdown.strip.empty?

        doc = document(page, lang, url, converted)

        # The `.md` carries a frontmatter header; the corpus keeps the bare body
        # (and hashes it), because every frontmatter field is already a column of
        # the corpus document — duplicating them would only desync the two.
        md_path = page.destination(@site.dest).sub(/\.html\z/, ".md")
        FileUtils.mkdir_p(File.dirname(md_path))
        File.write(md_path, "#{frontmatter(doc, lang, url)}#{markdown}\n")

        doc
      rescue StandardError => e
        Jekyll.logger.warn "AI export:", "failed to export #{page.url}: #{e.class}: #{e.message}"
        nil
      end

      def convert(page, lang, url)
        Jekyll::HtmlToMarkdown.convert_page(
          page.output,
          base_url: @urls[lang].to_s,
          page_url: url,
          link_rewriter: method(:rewrite_link),
        )
      end

      # Root-relative links of the rendered site carry the build-time language
      # prefix (`/en/…`); the published documentation lives under the versioned
      # documentation prefix instead. On top of that, an internal link is pointed
      # at the `.md` twin so an agent following it stays in Markdown.
      def rewrite_link(path)
        head, tail = split_link_tail(path)
        head = public_path(head) if head.match?(%r{\A/(en|ru)/})

        "#{md_link(head)}#{tail}"
      end

      # md_link rewrites an internal link to its Markdown twin: `/a/b.html` ->
      # `/a/b.md`, and a directory `/a/b/` -> `/a/b/index.md`. A directory is
      # rewritten only under the documentation and modules templates (see
      # INDEX_MD_PATH). The `.html` rewrite is
      # unconditional (it keeps a cross-build link — a module page into the
      # documentation — working); a non-page link (an asset, or an extensionless
      # path) is left alone.
      def md_link(path)
        if path.end_with?("/")
          path.match?(INDEX_MD_PATH) ? "#{path}index.md" : path
        elsif path.end_with?(".html")
          path.sub(/\.html\z/, ".md")
        else
          path
        end
      end

      # Separates the path from a trailing `?query`/`#fragment` so the path can
      # be rewritten while the tail is preserved.
      def split_link_tail(link)
        index = link.index(/[?#]/)
        return [link, ""] if index.nil?

        [link[0...index], link[index..]]
      end

      def document(page, lang, url, converted)
        title = converted.title.empty? ? page.data["title"].to_s : converted.title
        module_name = page.data["module-kebab-name"]
        doc_id = Digest::SHA1.hexdigest(url)

        doc = {
          "id" => doc_id,
          "title" => title,
          "description" => description_of(page),
          "url" => url,
          "mdUrl" => md_url(url),
          "path" => url.delete_prefix(@doc_prefix).sub(%r{\A/}, "").sub(%r{/\z}, "").sub(/\.html\z/, ""),
          "lang" => lang,
          "breadcrumbs" => Array(breadcrumbs_of(page, lang, module_name)),
          "keywords" => keywords_of(page),
          "module" => module_name,
          "moduleType" => module_name ? "embedded" : nil,
          "editions" => editions_of(module_name),
          "stage" => stage_of(module_name),
          "contentHash" => "sha256:#{Digest::SHA256.hexdigest(converted.markdown)}",
          "markdown" => converted.markdown,
          "chunks" => Chunker.new(doc_id, url, title).call(converted.markdown, converted.headings),
        }

        # Drop the optional fields that do not apply to this page (a
        # documentation page has no module or stage), mirroring the omitempty
        # contract of the Go structs so the embedded schema validates the output
        # of both generators. `version` is omitted on the whole Jekyll side: the
        # real content version (a git tag/branch) is not available at build time,
        # unlike the external modules built by Hugo.
        doc.compact
      end

      # frontmatter is the YAML header prepended to each per-page `.md`: enough
      # to keep a chunk's provenance once the file is split for retrieval. The
      # field names match the corpus document, so the two artifacts share one
      # vocabulary; empty values are dropped so a page without a module or
      # editions gets a clean header.
      def frontmatter(doc, lang, url)
        data = {
          "title" => doc["title"],
          "description" => doc["description"],
          "canonical" => absolute(lang, url),
          "lang" => lang,
          "module" => doc["module"],
          "moduleType" => doc["moduleType"],
          "editions" => doc["editions"],
          "stage" => doc["stage"],
        }
        data.reject! { |_, value| value.nil? || (value.respond_to?(:empty?) && value.empty?) }

        # `line_width: -1` disables Psych's line folding, so a long title or
        # description stays on one line — valid YAML either way, but friendlier
        # to consumers that read the header line by line rather than with a YAML
        # parser. The Go exporter's yaml.v3 does not fold, so this matches it.
        "#{data.to_yaml(line_width: -1)}---\n\n"
      end

      def description_of(page)
        value = page.data["description"] || page.data["summary"]
        # Kept on a single line: llms.txt entries are line-based.
        value.to_s.gsub(/\s+/, " ").strip
      end

      def keywords_of(page)
        value = page.data["search"]
        case value
        when Array then value.map(&:to_s).map(&:strip).reject(&:empty?)
        when String then value.split(",").map(&:strip).reject(&:empty?)
        else []
        end
      end

      def breadcrumbs_of(page, lang, module_name)
        return [@site.data.dig("i18n", "common", "modules", lang).to_s.capitalize, module_name] if module_name

        Jekyll::NavigationHelper.find_breadcrumb_titles_for_page(@site, page, page.data["sidebar"] || "main")
      end

      def editions_of(module_name)
        return [] if module_name.nil?

        Array(@site.data.dig("modules", "all", module_name, "editions"))
      end

      def stage_of(module_name)
        return nil if module_name.nil?

        @site.data.dig("modules", "metadata", "modules", module_name, "stage")
      end

      # --- URLs ------------------------------------------------------------

      # `/en/admin/configuration/` => `/products/…/v1/admin/configuration/`
      def public_url(page)
        public_path(page.url)
      end

      def public_path(path)
        stripped = path.sub(LANG_PREFIX, "")
        return stripped if path.match?(MODULE_PREFIX)

        "#{@doc_prefix}#{stripped}"
      end

      def md_url(url)
        url.end_with?("/") ? "#{url}index.md" : url.sub(/\.html\z/, ".md")
      end

      def absolute(lang, path)
        "#{@urls[lang].to_s.sub(%r{/+\z}, '')}#{path}"
      end

      # --- artifacts -------------------------------------------------------

      def write_corpus(lang, documents)
        corpus = {
          "version" => CORPUS_VERSION,
          "productCode" => PRODUCT_CODE,
          "lang" => lang,
          "generator" => GENERATOR,
          "baseUrl" => @urls[lang].to_s,
        }
        # The JSON Schema is generated from the Go structs and checked in as a
        # data file (see `_data/corpus_schema.json` and the docs-builder
        # `schema_test.go`); embedding it makes the corpus describe itself.
        corpus["schema"] = @site.data["corpus_schema"] if @site.data["corpus_schema"]
        corpus["documents"] = documents

        write(lang, @corpus_name, JSON.generate(corpus))
        Jekyll.logger.info "AI export:", "#{lang}/#{@corpus_name} — #{documents.length} documents"
      end

      def write_llms_txt(lang, documents)
        lines = ["# #{site_title(lang)}", "", "> #{site_summary(lang)}", ""]

        lines << @site.data.dig("i18n", "common", "aiLlmsNoteRoot", lang).to_s
        lines << ""

        groups(lang, documents).each do |group|
          next if group[:documents].empty?

          lines << "## #{group[:title]}"
          lines << ""
          group[:documents].each do |doc|
            entry = "- [#{group[:label].call(doc)}](#{absolute(lang, doc['mdUrl'])})"
            entry += ": #{doc['description']}" unless doc["description"].to_s.empty?
            lines << entry
          end
          lines << ""
        end

        if @root
          lines << "## #{@site.data.dig("i18n", "common", "modules_embedded", lang).to_s.capitalize} (llms.txt)"
          lines << ""
          lines << "- [embedded-llms.txt](#{absolute(lang, "/modules/embedded-llms.txt")}): #{@site.data.dig("i18n", "common", "aiLlmsRefDescriptionEmbeddedModules", lang).to_s}"
          lines << "- [external-llms.txt](#{absolute(lang, "/modules/external-llms.txt")}): #{@site.data.dig("i18n", "common", "aiLlmsRefDescriptionExternalModules", lang).to_s}"
          lines << ""

          lines << "## Optional"
          lines << ""
          lines << "- [#{@corpus_name}](#{absolute(lang, "#{@doc_prefix}/#{@corpus_name}")}): #{@site.data.dig("i18n", "common", "aiCorpusLlmsDescriptionRoot", lang).to_s}"
          lines << "- [embedded-corpus.json](#{absolute(lang, "/modules/embedded-corpus.json")}): #{@site.data.dig("i18n", "common", "aiCorpusLlmsDescriptionEmbeddedModules", lang).to_s}"
          lines << "- [external-corpus.json](#{absolute(lang, "/modules/external-corpus.json")}): #{@site.data.dig("i18n", "common", "aiCorpusLlmsDescriptionExternalModules", lang).to_s}"
          lines << ""
        end

        write(lang, @llms_name, lines.join("\n"))
      end

      def site_title(lang)
        title = @site.config.dig("ai_export", "title")
        title = title[lang] if title.is_a?(Hash)
        title.to_s.empty? ? @site.config["site_title"].to_s : title.to_s
      end

      # The llms.txt summary. `ai_export.summaryI18nKey` names an entry under
      # `i18n.common` (per-language), so the text lives with the other AI strings
      # and a build can point at its own — e.g. the embedded-modules build to a
      # module-specific summary. Falls back to `site_description` when the key is
      # unset or resolves to nothing.
      def site_summary(lang)
        key = @site.config.dig("ai_export", "summaryI18nKey").to_s
        unless key.empty?
          summary = @site.data.dig("i18n", "common", key, lang).to_s
          return summary unless summary.empty?
        end

        @site.config.dig("site_description", lang).to_s
      end

      def write(lang, name, content)
        path = File.join(@site.dest, lang, name)
        FileUtils.mkdir_p(File.dirname(path))
        File.write(path, content)
      end

      # --- llms.txt grouping -----------------------------------------------

      # Groups follow the sidebar tree, so the index reads in the same order as
      # the site navigation. Module pages and anything the sidebar does not
      # reference are appended as their own groups.
      def groups(lang, documents)
        by_url = documents.each_with_object({}) do |doc, acc|
          acc[sidebar_key(doc["url"])] = doc
        end
        used = {}
        title_label = ->(doc) { doc["title"] }

        result = []

        # Every top-level sidebar entry becomes its own section titled by its
        # sidebar title, in sidebar order — a folder gathers its whole subtree, a
        # bare page (the docs index, FAQ, release notes) is a section of one.
        (@site.data.dig("sidebars", "main", "entries") || []).each do |entry|
          next if entry["draft"] == true

          title = entry.dig("title", lang) || entry["title"]
          collected = collect_entry(entry, by_url, used)
          next if collected.empty?

          result << { title: title.to_s, documents: collected, label: title_label }
        end

        modules = documents.reject { |doc| used[doc["url"]] }.select { |doc| doc["module"] }
        unless modules.empty?
          modules.sort_by! { |doc| [doc["module"], doc["path"]] }
          modules.each { |doc| used[doc["url"]] = true }
          result << {
            title: @site.data.dig("i18n", "common", "modules", lang).to_s.capitalize,
            documents: modules,
            label: ->(doc) { "#{doc['module']}: #{doc['title']}" },
          }
        end

        rest = documents.reject { |doc| used[doc["url"]] }
        result << { title: @site.data.dig("i18n", "common", "other_documentation", lang).to_s.capitalize, documents: rest, label: title_label } unless rest.empty?

        result
      end

      def collect_entry(entry, by_url, used, acc = [])
        if entry["url"]
          doc = by_url[sidebar_key(entry["url"])]
          if doc && !used[doc["url"]]
            used[doc["url"]] = true
            acc << doc
          end
        end

        Array(entry["folders"]).each do |child|
          next if child["draft"] == true

          collect_entry(child, by_url, used, acc)
        end

        acc
      end

      # Normalizes both sidebar entries (`/admin/configuration/`) and document
      # URLs (`/products/…/v1/admin/configuration/`) to a comparable key.
      def sidebar_key(url)
        Jekyll::NavigationHelper.normalize_sidebar_url(url.to_s.delete_prefix(@doc_prefix)).to_s
      end
    end

    # Splits a page's Markdown into retrieval-sized chunks: one per H2 section,
    # with oversized sections split further by H3, plus the preamble before the
    # first H2.
    class Chunker
      def initialize(doc_id, url, title)
        @doc_id = doc_id
        @url = url
        @title = title
      end

      def call(markdown, headings)
        lines = markdown.split("\n", -1)
        marks = scan(lines, headings)
        sections = marks.select { |mark| mark[:level] == 2 }

        chunks = []
        preamble = slice(lines, 0, sections.first ? sections.first[:line] : lines.length)
        chunks << chunk(nil, 1, [@title], preamble, chunks.length) unless preamble.empty?

        sections.each_with_index do |mark, index|
          stop = sections[index + 1] ? sections[index + 1][:line] : lines.length
          body = slice(lines, mark[:line], stop)
          next if body.empty?

          subsections = marks.select { |m| m[:level] == 3 && m[:line] > mark[:line] && m[:line] < stop }

          if body.length <= MAX_CHUNK_CHARS || subsections.empty?
            chunks << chunk(mark[:id], 2, [@title, mark[:text]], body, chunks.length)
            next
          end

          head = slice(lines, mark[:line], subsections.first[:line])
          chunks << chunk(mark[:id], 2, [@title, mark[:text]], head, chunks.length) unless head.empty?

          subsections.each_with_index do |sub, sub_index|
            sub_stop = subsections[sub_index + 1] ? subsections[sub_index + 1][:line] : stop
            sub_body = slice(lines, sub[:line], sub_stop)
            next if sub_body.empty?

            chunks << chunk(sub[:id], 3, [@title, mark[:text], sub[:text]], sub_body, chunks.length)
          end
        end

        chunks
      end

      private

      def slice(lines, from, to)
        lines[from...to].join("\n").strip
      end

      def chunk(anchor, level, heading_path, markdown, ordinal)
        # The preamble chunk has no anchor; drop the key rather than emit null,
        # to match the omitempty `anchor` of the Go Chunk struct.
        {
          "id" => "#{@doc_id}##{anchor || ordinal}",
          "anchor" => anchor,
          "url" => anchor ? "#{@url}##{anchor}" : @url,
          "level" => level,
          "headingPath" => heading_path,
          "markdown" => markdown,
          "charCount" => markdown.length,
          "approxTokens" => (markdown.length / 4.0).ceil,
        }.compact
      end

      # Locates the heading lines of the Markdown and re-attaches the HTML
      # anchors collected during conversion. Matching is sequential, so a `#`
      # inside a fenced block cannot steal an anchor.
      def scan(lines, headings)
        found = []
        cursor = 0
        fence = nil

        lines.each_with_index do |line, index|
          stripped = line.strip

          if fence
            fence = nil if stripped.start_with?(fence)
            next
          end

          opening = stripped[FENCE_START, 1]
          if opening
            fence = opening
            next
          end

          match = HEADING_LINE.match(line)
          next if match.nil?

          level = match[1].length
          text = match[2].sub(HEADING_ANCHOR, "").strip
          id = nil

          scan_index = cursor
          while scan_index < headings.length
            heading = headings[scan_index]
            if heading.level == level && heading.text == text
              id = heading.id
              cursor = scan_index + 1
              break
            end

            scan_index += 1
          end

          found << { line: index, level: level, text: text, id: id }
        end

        found
      end
    end
  end
end

Jekyll::Hooks.register :site, :post_write do |site|
  if Jekyll::AiExport.enabled?(site)
    Jekyll.logger.info "AI export:", "generating llms.txt, corpus.json and per-page Markdown..."
    Jekyll::AiExport::Exporter.new(site).run
  else
    Jekyll.logger.debug "AI export:", "disabled, set `#{Jekyll::AiExport::ENABLED_KEY}: true` to enable"
  end
end
