# frozen_string_literal: true

require "digest"
require "fileutils"
require "json"

require_relative "html_to_markdown"
require_relative "navigation_helper"

module Jekyll
  # Publishes the AI-friendly exports of the documentation:
  #
  #   <lang>/<page path>.md         per-page Markdown body
  #   <lang>/<AIcorpusFileName>     RAG corpus: metadata + Markdown + chunks
  #   <lang>/<AIllmsFileName>       llms.txt index, grouped by the sidebar tree
  #
  # Disabled unless `AIExport: true` is set in the site config, and the two file
  # names are taken from the config as well: the same source tree is built
  # several times (the documentation itself and the embedded modules, see
  # `werf-documentation-static.inc.yaml` and `werf-modules-static.inc.yaml`),
  # and those builds publish their indexes side by side under different names.
  # `AIRoot: true` marks the build whose llms.txt is the entry point of the
  # site, the one that points an agent at the corpora.
  #
  # It runs on `site, :post_write` rather than as a Liquid template (the way
  # `search.json` is built) because `page.content` inside Liquid depends on the
  # page render order, while `page.output` is guaranteed to be complete here.
  module AiExport
    CORPUS_VERSION = 1
    PRODUCT_CODE = "kubernetes-platform"
    GENERATOR = "jekyll"

    ENABLED_KEY = "AIExport"
    ROOT_KEY = "AIRoot"
    LLMS_NAME_KEY = "AIllmsFileName"
    CORPUS_NAME_KEY = "AIcorpusFileName"

    DEFAULT_LLMS_NAME = "llms.txt"
    DEFAULT_CORPUS_NAME = "corpus.json"

    # `--config a.yml,b.yml` merges plain YAML, so a flag arrives as a real
    # boolean; a string is accepted too, since an `AIExport` that reads as
    # "true" and silently exports nothing would be baffling.
    def self.truthy?(value)
      value == true || value.to_s.strip.casecmp("true").zero?
    end

    def self.enabled?(site)
      truthy?(site.config[ENABLED_KEY])
    end

    # An H2 section longer than this is split further, by H3.
    MAX_CHUNK_CHARS = 6000

    # Pages generated by `render-jsonschema.rb`. `custom_hooks.rb` drops them
    # from the search index (`searchable: false`), but for an agent they are the
    # single most valuable reference on the site, so they are exported anyway.
    REFERENCE_PAGE_NAMES = /(CONFIGURATION|CR|CLUSTER_CONFIGURATION)(\.ru|_RU)?\.md\z/i.freeze

    HEADING_LINE = /\A(\#{1,6})\s+(.*)\z/.freeze
    FENCE_START = /\A(`{3,}|~{3,})/.freeze

    LANG_PREFIX = %r{\A/(en|ru)}.freeze
    # Embedded module pages are published outside the versioned documentation
    # prefix: `/en/modules/user-authn/` is served as `/modules/user-authn/`.
    MODULE_PREFIX = %r{\A/(en|ru)/modules/}.freeze

    class Exporter
      def initialize(site)
        @site = site
        @doc_prefix = site.config["canonical_url_prefix_documentation"].to_s.sub(%r{/+\z}, "")
        @urls = site.config["urls"] || {}
        @llms_name = file_name(LLMS_NAME_KEY, DEFAULT_LLMS_NAME)
        @corpus_name = file_name(CORPUS_NAME_KEY, DEFAULT_CORPUS_NAME)
        @root = AiExport.truthy?(site.config[ROOT_KEY])
      end

      def run
        pages = @site.pages.select { |page| exportable?(page) }
        return if pages.empty?

        pages.group_by { |page| lang_of(page) }.each do |lang, lang_pages|
          documents = lang_pages.filter_map { |page| export_page(page, lang) }
          next if documents.empty?

          documents.sort_by! { |doc| doc["path"] }
          write_corpus(lang, documents)
          write_llms_txt(lang, documents)
        end
      end

      private

      # A name is a single file name, not a path: the exports always land next
      # to each other in `<dest>/<lang>/`, and the URLs published in llms.txt
      # are built from it.
      def file_name(key, fallback)
        name = File.basename(@site.config[key].to_s.strip)
        return fallback if name.empty? || name == "."

        name
      end

      # --- page selection --------------------------------------------------

      def exportable?(page)
        return false if page.data["ai_export"] == false
        return false unless page.output.is_a?(String)
        return false unless page.url.end_with?("/") || page.url.end_with?(".html")
        return false if page.data["layout"].to_s == "none"
        return false unless page.url.match?(%r{\A/(en|ru)/})
        return true if page.data["searchable"] == true

        page.name.to_s.match?(REFERENCE_PAGE_NAMES)
      end

      def lang_of(page)
        page.data["lang"] || (page.url.start_with?("/ru/") ? "ru" : "en")
      end

      # --- per-page export -------------------------------------------------

      def export_page(page, lang)
        url = public_url(page)
        converted = convert(page, lang, url)
        return nil if converted.nil?

        markdown = converted.markdown
        return nil if markdown.strip.empty?

        md_path = page.destination(@site.dest).sub(/\.html\z/, ".md")
        FileUtils.mkdir_p(File.dirname(md_path))
        File.write(md_path, "#{markdown}\n")

        document(page, lang, url, converted)
      rescue StandardError => e
        Jekyll.logger.warn "AI export:", "failed to export #{page.url}: #{e.class}: #{e.message}"
        nil
      end

      def convert(page, lang, url)
        Jekyll::HtmlToMarkdown.convert_page(
          page.output,
          base_url: @urls[lang].to_s,
          page_url: url,
          link_rewriter: method(:rewrite_link),
        )
      end

      # Root-relative links of the rendered site carry the build-time language
      # prefix (`/en/…`); the published documentation lives under the versioned
      # documentation prefix instead.
      def rewrite_link(path)
        return path unless path.match?(%r{\A/(en|ru)/})

        public_path(path)
      end

      def document(page, lang, url, converted)
        title = converted.title.empty? ? page.data["title"].to_s : converted.title
        module_name = page.data["module-kebab-name"]
        doc_id = Digest::SHA1.hexdigest(url)

        doc = {
          "id" => doc_id,
          "title" => title,
          "description" => description_of(page),
          "url" => url,
          "mdUrl" => md_url(url),
          "path" => url.delete_prefix(@doc_prefix).sub(%r{\A/}, "").sub(%r{/\z}, "").sub(/\.html\z/, ""),
          "lang" => lang,
          "breadcrumbs" => breadcrumbs_of(page, lang, module_name),
          "keywords" => keywords_of(page),
          "moduleType" => module_name ? "embedded" : nil,
          "editions" => editions_of(module_name),
          "stage" => stage_of(module_name),
          "searchBoost" => page.data["searchBoost"],
          "contentHash" => "sha256:#{Digest::SHA256.hexdigest(converted.markdown)}",
          "markdown" => converted.markdown,
          "chunks" => Chunker.new(doc_id, url, title).call(converted.markdown, converted.headings),
        }
        doc["module"] = module_name if module_name

        doc
      end

      def description_of(page)
        value = page.data["description"] || page.data["summary"]
        # Kept on a single line: llms.txt entries are line-based.
        value.to_s.gsub(/\s+/, " ").strip
      end

      def keywords_of(page)
        value = page.data["search"]
        case value
        when Array then value.map(&:to_s).map(&:strip).reject(&:empty?)
        when String then value.split(",").map(&:strip).reject(&:empty?)
        else []
        end
      end

      def breadcrumbs_of(page, lang, module_name)
        return [@site.data.dig("i18n", "common", "modules", lang).to_s.capitalize, module_name] if module_name

        Jekyll::NavigationHelper.find_breadcrumb_titles_for_page(@site, page, page.data["sidebar"] || "main")
      end

      def editions_of(module_name)
        return [] if module_name.nil?

        Array(@site.data.dig("modules", "all", module_name, "editions"))
      end

      def stage_of(module_name)
        return nil if module_name.nil?

        @site.data.dig("modules", "metadata", "modules", module_name, "stage")
      end

      # --- URLs ------------------------------------------------------------

      # `/en/admin/configuration/` => `/products/…/v1/admin/configuration/`
      def public_url(page)
        public_path(page.url)
      end

      def public_path(path)
        stripped = path.sub(LANG_PREFIX, "")
        return stripped if path.match?(MODULE_PREFIX)

        "#{@doc_prefix}#{stripped}"
      end

      def md_url(url)
        url.end_with?("/") ? "#{url}index.md" : url.sub(/\.html\z/, ".md")
      end

      def absolute(lang, path)
        "#{@urls[lang].to_s.sub(%r{/+\z}, '')}#{path}"
      end

      # --- artifacts -------------------------------------------------------

      def write_corpus(lang, documents)
        corpus = {
          "version" => CORPUS_VERSION,
          "productCode" => PRODUCT_CODE,
          "lang" => lang,
          "generator" => GENERATOR,
          "baseUrl" => @urls[lang].to_s,
          "documents" => documents,
        }

        write(lang, @corpus_name, JSON.generate(corpus))
        Jekyll.logger.info "AI export:", "#{lang}/#{@corpus_name} — #{documents.length} documents"
      end

      def write_llms_txt(lang, documents)
        lines = ["# #{site_title(lang)}", "", "> #{site_summary(lang)}", ""]

        lines << ""
        lines << "> Note, that described Deckhouse Platform version can differ from the version actually used in a cluster."
        lines << ""

        groups(lang, documents).each do |group|
          next if group[:documents].empty?

          lines << "## #{group[:title]}"
          group[:documents].each do |doc|
            entry = "- [#{group[:label].call(doc)}](#{absolute(lang, doc['mdUrl'])})"
            entry += ": #{doc['description']}" unless doc["description"].to_s.empty?
            lines << entry
          end
          lines << ""
        end

        if @root
          lines << "## Optional"
          lines << "- [#{@corpus_name}](#{absolute(lang, "#{@doc_prefix}/#{@corpus_name}")}): RAG corpus with page Markdown and chunks for documentation pages."
          lines << ""

          lines << "## Modules"
          lines << "- [embedded-llms.txt](#{absolute(lang, "/modules/embedded-llms.txt")}): LLM index of embedded modules."
          lines << "- [external-llms.txt](#{absolute(lang, "/modules/external-llms.txt")}): LLM index of external modules."
          lines << ""

          lines << "## Modules optional"
          lines << "- [embedded-corpus.json](#{absolute(lang, "/modules/embedded-corpus.json")}): RAG corpus with page Markdown and chunks for embedded modules."
          lines << "- [external-corpus.json](#{absolute(lang, "/modules/external-corpus.json")}): RAG corpus with page Markdown and chunks for external modules."
          lines << ""
        end

        write(lang, @llms_name, lines.join("\n"))
      end

      def site_title(lang)
        title = @site.config.dig("ai_export", "title")
        title = title[lang] if title.is_a?(Hash)
        title.to_s.empty? ? @site.config["site_title"].to_s : title.to_s
      end

      def site_summary(lang)
        summary = @site.config.dig("ai_export", "summary")
        summary = summary[lang] if summary.is_a?(Hash)
        return summary.to_s unless summary.to_s.empty?

        @site.config.dig("site_description", lang).to_s
      end

      def write(lang, name, content)
        path = File.join(@site.dest, lang, name)
        FileUtils.mkdir_p(File.dirname(path))
        File.write(path, content)
      end

      # --- llms.txt grouping -----------------------------------------------

      # Groups follow the sidebar tree, so the index reads in the same order as
      # the site navigation. Module pages and anything the sidebar does not
      # reference are appended as their own groups.
      def groups(lang, documents)
        by_url = documents.each_with_object({}) do |doc, acc|
          acc[sidebar_key(doc["url"])] = doc
        end
        used = {}
        title_label = ->(doc) { doc["title"] }

        result = []
        loose = []

        (@site.data.dig("sidebars", "main", "entries") || []).each do |entry|
          next if entry["draft"] == true

          title = entry.dig("title", lang) || entry["title"]
          collected = collect_entry(entry, by_url, used)
          next if collected.empty?

          if entry["folders"].is_a?(Array)
            result << { title: title.to_s, documents: collected, label: title_label }
          else
            loose.concat(collected)
          end
        end

        result.unshift({ title: site_title(lang), documents: loose, label: title_label }) unless loose.empty?

        modules = documents.reject { |doc| used[doc["url"]] }.select { |doc| doc["module"] }
        unless modules.empty?
          modules.sort_by! { |doc| [doc["module"], doc["path"]] }
          modules.each { |doc| used[doc["url"]] = true }
          result << {
            title: @site.data.dig("i18n", "common", "modules", lang).to_s.capitalize,
            documents: modules,
            label: ->(doc) { "#{doc['module']}: #{doc['title']}" },
          }
        end

        rest = documents.reject { |doc| used[doc["url"]] }
        result << { title: "Other", documents: rest, label: title_label } unless rest.empty?

        result
      end

      def collect_entry(entry, by_url, used, acc = [])
        if entry["url"]
          doc = by_url[sidebar_key(entry["url"])]
          if doc && !used[doc["url"]]
            used[doc["url"]] = true
            acc << doc
          end
        end

        Array(entry["folders"]).each do |child|
          next if child["draft"] == true

          collect_entry(child, by_url, used, acc)
        end

        acc
      end

      # Normalizes both sidebar entries (`/admin/configuration/`) and document
      # URLs (`/products/…/v1/admin/configuration/`) to a comparable key.
      def sidebar_key(url)
        Jekyll::NavigationHelper.normalize_sidebar_url(url.to_s.delete_prefix(@doc_prefix)).to_s
      end
    end

    # Splits a page's Markdown into retrieval-sized chunks: one per H2 section,
    # with oversized sections split further by H3, plus the preamble before the
    # first H2.
    class Chunker
      def initialize(doc_id, url, title)
        @doc_id = doc_id
        @url = url
        @title = title
      end

      def call(markdown, headings)
        lines = markdown.split("\n", -1)
        marks = scan(lines, headings)
        sections = marks.select { |mark| mark[:level] == 2 }

        chunks = []
        preamble = slice(lines, 0, sections.first ? sections.first[:line] : lines.length)
        chunks << chunk(nil, 1, [@title], preamble, chunks.length) unless preamble.empty?

        sections.each_with_index do |mark, index|
          stop = sections[index + 1] ? sections[index + 1][:line] : lines.length
          body = slice(lines, mark[:line], stop)
          next if body.empty?

          subsections = marks.select { |m| m[:level] == 3 && m[:line] > mark[:line] && m[:line] < stop }

          if body.length <= MAX_CHUNK_CHARS || subsections.empty?
            chunks << chunk(mark[:id], 2, [@title, mark[:text]], body, chunks.length)
            next
          end

          head = slice(lines, mark[:line], subsections.first[:line])
          chunks << chunk(mark[:id], 2, [@title, mark[:text]], head, chunks.length) unless head.empty?

          subsections.each_with_index do |sub, sub_index|
            sub_stop = subsections[sub_index + 1] ? subsections[sub_index + 1][:line] : stop
            sub_body = slice(lines, sub[:line], sub_stop)
            next if sub_body.empty?

            chunks << chunk(sub[:id], 3, [@title, mark[:text], sub[:text]], sub_body, chunks.length)
          end
        end

        chunks
      end

      private

      def slice(lines, from, to)
        lines[from...to].join("\n").strip
      end

      def chunk(anchor, level, heading_path, markdown, ordinal)
        {
          "id" => "#{@doc_id}##{anchor || ordinal}",
          "anchor" => anchor,
          "url" => anchor ? "#{@url}##{anchor}" : @url,
          "level" => level,
          "headingPath" => heading_path,
          "markdown" => markdown,
          "charCount" => markdown.length,
          "approxTokens" => (markdown.length / 4.0).ceil,
        }
      end

      # Locates the heading lines of the Markdown and re-attaches the HTML
      # anchors collected during conversion. Matching is sequential, so a `#`
      # inside a fenced block cannot steal an anchor.
      def scan(lines, headings)
        found = []
        cursor = 0
        fence = nil

        lines.each_with_index do |line, index|
          stripped = line.strip

          if fence
            fence = nil if stripped.start_with?(fence)
            next
          end

          opening = stripped[FENCE_START, 1]
          if opening
            fence = opening
            next
          end

          match = HEADING_LINE.match(line)
          next if match.nil?

          level = match[1].length
          text = match[2].strip
          id = nil

          scan_index = cursor
          while scan_index < headings.length
            heading = headings[scan_index]
            if heading.level == level && heading.text == text
              id = heading.id
              cursor = scan_index + 1
              break
            end

            scan_index += 1
          end

          found << { line: index, level: level, text: text, id: id }
        end

        found
      end
    end
  end
end

Jekyll::Hooks.register :site, :post_write do |site|
  if Jekyll::AiExport.enabled?(site)
    Jekyll.logger.info "AI export:", "generating llms.txt, corpus.json and per-page Markdown..."
    Jekyll::AiExport::Exporter.new(site).run
  else
    Jekyll.logger.debug "AI export:", "disabled, set `#{Jekyll::AiExport::ENABLED_KEY}: true` to enable"
  end
end
