# frozen_string_literal: true

require "nokogiri"
require "uri"

module Jekyll
  # Converts rendered documentation HTML back into clean Markdown for the
  # AI-friendly exports (per-page `.md`, `corpus.json`, `llms.txt`).
  #
  # The source Markdown cannot be reused directly: it still carries Liquid tags,
  # and the CONFIGURATION/CR pages are generated by `render-jsonschema.rb` and
  # exist as HTML only. Rendered HTML is also the only place where kramdown's
  # `auto_ids` anchors are available, which the corpus chunker needs.
  #
  # The module deliberately has no Jekyll dependency: it takes an HTML string
  # and returns Markdown, so it can be unit-tested standalone, reused by
  # `docs/site` and mirrored by the Go implementation used for external modules
  # (`docs/site/backends/docs-builder/internal/aiexport`).
  module HtmlToMarkdown
    # A heading emitted into the Markdown, in document order. `id` comes from
    # the rendered HTML (kramdown `auto_ids`) and is used as a chunk anchor.
    Heading = Struct.new(:level, :text, :id)

    # Result of converting a whole page.
    Page = Struct.new(:title, :markdown, :headings)

    # Elements that never contribute to the export.
    DROPPED_TAGS = %w[script style svg noscript iframe form button template link meta].freeze

    # Class names marking interactive chrome rather than documentation content.
    DROPPED_CLASSES = %w[
      tags githubEditButton anchorjs-link anchor
      plus-icon minus-icon
      breadcrumbs__container navigation feedback
      copy-code copy-button
    ].freeze

    DROPPED_IDS = %w[toc].freeze

    # `div.alert__wrap` level class => Markdown blockquote label.
    ALERT_LABELS = { "info" => "NOTE", "warning" => "WARNING", "danger" => "DANGER" }.freeze

    INLINE_TAGS = %w[
      a abbr b br cite code del em i img ins kbd mark q s samp small span
      strong sub sup time tt u var wbr
    ].freeze

    DEFAULT_CODE_LANGUAGE = "plaintext"

    # Stands in for a `<br>` while a run of inline content is assembled, so that
    # collapsing whitespace can tell an intentional line break from the
    # incidental newlines of the HTML source layout. A NUL never occurs in the
    # rendered documentation; it becomes a real newline (or a space, in headings
    # and table cells) once the surrounding whitespace is collapsed.
    HARD_BREAK = "\u0000"

    module_function

    # Converts a full rendered page (`h1.docs__title` + `div.post-content`).
    def convert_page(html, base_url: nil, page_url: nil, link_rewriter: nil)
      Converter.new(base_url: base_url, page_url: page_url, link_rewriter: link_rewriter).convert_page(html)
    end

    # Converts an HTML fragment. Used by unit tests and by callers that already
    # extracted the content element.
    def convert_fragment(html, base_url: nil, page_url: nil, link_rewriter: nil)
      Converter.new(base_url: base_url, page_url: page_url, link_rewriter: link_rewriter).convert_fragment(html)
    end

    class Converter
      attr_reader :headings

      # base_url       - site origin (`https://deckhouse.io`), used to absolutize links
      # page_url       - public path of the page being converted, used as the base
      #                  for relative links (must be the *public* URL, not the
      #                  `/en/...` build path)
      # link_rewriter  - optional callable applied to root-relative paths before
      #                  they are prefixed with base_url
      def initialize(base_url: nil, page_url: nil, link_rewriter: nil)
        @base_url = base_url.to_s.sub(%r{/+\z}, "")
        @page_url = page_url.to_s
        @link_rewriter = link_rewriter
        @headings = []
      end

      def convert_page(html)
        doc = Nokogiri::HTML(html)
        @headings = []

        title_node = doc.at_css("h1.docs__title")
        title = title_node ? flow_inline(inline(title_node)).strip : ""
        @headings << Heading.new(1, title, title_node && title_node["id"]) unless title.empty?

        body_node = doc.at_css("div.post-content")
        body = body_node ? blocks(body_node) : ""

        parts = []
        parts << "# #{title}" unless title.empty?
        parts << body unless body.strip.empty?

        HtmlToMarkdown::Page.new(title, normalize(parts.join("\n\n")), @headings)
      end

      def convert_fragment(html)
        @headings = []
        normalize(blocks(Nokogiri::HTML::DocumentFragment.parse(html)))
      end

      private

      # --- block level -----------------------------------------------------

      # Renders the children of `node` as a sequence of Markdown blocks joined
      # by a blank line. Consecutive inline children are merged into one
      # paragraph; `<!--noindex-->…<!--/noindex-->` regions are skipped.
      def blocks(node)
        out = []
        pending = +""
        skipping = false

        flush = lambda do
          text = flow_text(pending).strip
          out << text unless text.empty?
          pending = +""
        end

        node.children.each do |child|
          if child.comment?
            marker = child.text.strip
            skipping = true if marker == "noindex"
            skipping = false if marker == "/noindex"
            next
          end

          next if skipping

          if child.text?
            pending << child.text
            next
          end

          next unless child.element?
          next if dropped?(child)

          if inline?(child)
            pending << inline_for(child)
            next
          end

          flush.call
          block_for(child).each { |b| out << b unless b.nil? || b.strip.empty? }
        end

        flush.call
        out.join("\n\n")
      end

      def block_for(el)
        case el.name
        when "h1", "h2", "h3", "h4", "h5", "h6" then [heading(el)]
        when "p" then [paragraph(el)]
        when "pre" then [code_block(el)]
        when "ul", "ol" then [list(el)]
        when "dl" then [definition_list(el)]
        when "table" then [table(el)]
        when "blockquote" then [blockquote(el)]
        when "hr" then ["---"]
        when "details" then [native_details(el)]
        else
          [special_block(el) || blocks(el)]
        end
      end

      # Deckhouse-specific block constructs. Returns nil when `el` is a plain
      # wrapper that should just be recursed into.
      def special_block(el)
        classes = class_list(el)

        return alert(el) if classes.include?("alert__wrap")
        return details(el) if classes.include?("details") && el.at_css(".details__summary")
        return tabs(el) if classes.include?("tabs-block")
        return highlight(el) if classes.include?("highlight") || classes.include?("highlighter-rouge")

        nil
      end

      def heading(el)
        level = el.name[1].to_i
        text = flow_inline(inline(el)).strip
        return "" if text.empty?

        id = el["id"].to_s
        @headings << Heading.new(level, text, id)

        line = "#{'#' * level} #{text}"
        # Publish the HTML anchor as a kramdown/Pandoc heading attribute so an
        # in-page link (`cr.md#customresourcedefinition`) resolves. The text
        # alone is not enough: for Cyrillic the HTML slug is not what a Markdown
        # renderer would derive from the heading.
        line += " {##{id}}" unless id.empty?
        line
      end

      # A `<p>` normally holds inline content only, but `render-jsonschema.rb`
      # occasionally emits block markup inside one.
      def paragraph(el)
        return blocks(el) if el.element_children.any? { |child| !inline?(child) && !dropped?(child) }

        flow_text(inline(el)).strip
      end

      def alert(el)
        level = (class_list(el) & ALERT_LABELS.keys).first || "info"
        body = blocks(el).strip
        return "" if body.empty?

        lines = body.split("\n", -1)
        lines[0] = "**#{ALERT_LABELS[level]}:** #{lines[0]}"
        lines.map { |line| line.empty? ? ">" : "> #{line}" }.join("\n")
      end

      def details(el)
        summary = collapse(el.at_css(".details__summary").text).strip
        summary = "Details" if summary.empty?
        content = el.at_css(".details__content") || el
        body = blocks(content).strip

        ["#### #{summary}", body].reject(&:empty?).join("\n\n")
      end

      def native_details(el)
        summary_el = el.at_css("summary")
        summary = summary_el ? flow_inline(inline(summary_el)).strip : ""
        summary = "Details" if summary.empty?

        body_source = el.dup
        body_source.css("summary").each(&:remove)
        body = blocks(body_source).strip

        ["#### #{summary}", body].reject(&:empty?).join("\n\n")
      end

      # `div.tabs-block` holds a list of tab labels followed by one panel per
      # tab. All tabs are included in the export: an agent has no way to click.
      def tabs(el)
        labels = el.css("> ul > li").map { |li| collapse(li.text).strip }
        panels = el.css("> div.tabs__container--descr")
        panels = el.css("> div.tabs__container").reject { |d| class_list(d).include?("tabs__container--title") } if panels.empty?

        sections = panels.each_with_index.map do |panel, index|
          label = labels[index].to_s
          label = "Tab #{index + 1}" if label.empty?
          body = blocks(panel).strip
          ["#### #{label}", body].reject(&:empty?).join("\n\n")
        end

        sections.reject(&:empty?).join("\n\n")
      end

      # Rouge (`div.language-yaml.highlighter-rouge`) and Chroma
      # (`div.highlight > table.lntable`) wrappers around a code block.
      def highlight(el)
        pre = el.at_css("td.lntd:last-child pre") || el.at_css("pre")
        return blocks(el) unless pre

        code_block(pre, language: detect_language(el) || detect_language(pre))
      end

      def code_block(pre, language: nil)
        code = pre.at_css("code") || pre
        text = code.text.sub(/\n+\z/, "")
        return "" if text.strip.empty?

        lang = language || detect_language(pre) || DEFAULT_CODE_LANGUAGE
        fence = "`" * [3, (text.scan(/`+/).map(&:length).max || 0) + 1].max

        "#{fence}#{lang}\n#{text}\n#{fence}"
      end

      def detect_language(node)
        current = node
        4.times do
          break if current.nil? || !current.element?

          lang = class_list(current).find { |c| c.start_with?("language-") }
          return lang.delete_prefix("language-") if lang

          data_lang = current["data-lang"]
          return data_lang unless data_lang.nil? || data_lang.empty?

          current = current.parent
        end

        code = node.at_css("code")
        return nil if code.nil?

        lang = class_list(code).find { |c| c.start_with?("language-") }
        lang&.delete_prefix("language-")
      end

      def list(el)
        ordered = el.name == "ol"
        items = el.element_children.select { |c| c.name == "li" }
        return "" if items.empty?

        start = (el["start"] || 1).to_i
        items.each_with_index.map do |li, index|
          # Nested `ul`s of a JSON-schema reference carry no `.resources`
          # class, so the parameter rows are detected per list item.
          body = li.at_css("> div.resources__prop_wrap") ? resource_item(li) : blocks(li)
          marker = ordered ? "#{start + index}. " : "- "
          indent(body, marker)
        end.reject { |item| item.strip.empty? }.join("\n")
      end

      # A parameter row of a JSON-schema reference page (`ul.resources`), as
      # produced by `render-jsonschema.rb` and the Hugo `openapi/*` partials.
      def resource_item(li)
        wrap = li.at_css("> div.resources__prop_wrap")
        return blocks(li) if wrap.nil?

        name_el = wrap.at_css(".resources__prop_name")
        name = resource_name(name_el)
        type = wrap.at_css("> span.resources__prop_type")&.text.to_s.strip

        attributes = []
        attributes << "`#{type}`" unless type.empty?
        attributes << "required" if wrap.at_css("span.resources__attrs_name.required")
        attributes << "deprecated" if wrap.at_css(".resources__prop_is_deprecated")

        header = name.empty? ? "" : "**#{name}**"
        header += " (#{attributes.join(', ')})" unless attributes.empty?

        rest = wrap.dup
        rest.css(".resources__prop_name").each(&:remove)
        rest.css("> span.resources__prop_type").each(&:remove)
        rest.css("p.resources__attrs.required").each(&:remove)

        parts = [header.strip, blocks(rest).strip]
        li.css("> ul").each { |nested| parts << list(nested) }

        parts.reject { |part| part.nil? || part.strip.empty? }.join("\n\n")
      end

      def resource_name(name_el)
        return "" if name_el.nil?

        ancestors = name_el.at_css("span.ancestors")&.text.to_s.strip
        holder = name_el.at_css("div")
        own = if holder
                holder.css("> span").reject { |s| class_list(s).include?("ancestors") }.map(&:text).join
              else
                name_el.text
              end

        "#{ancestors}#{collapse(own).strip}".strip
      end

      def definition_list(el)
        items = []
        el.element_children.each do |child|
          case child.name
          when "dt"
            items << { term: flow_inline(inline(child)).strip, definitions: [] }
          when "dd"
            items << { term: "", definitions: [] } if items.empty?
            items.last[:definitions] << blocks(child).strip
          end
        end

        items.map do |item|
          body = ([item[:term].empty? ? nil : "**#{item[:term]}**"] + item[:definitions])
                 .compact.reject(&:empty?).join("\n\n")
          indent(body, "- ")
        end.reject { |item| item.strip.empty? }.join("\n")
      end

      def table(el)
        # Chroma renders line numbers as a two-column table; only the code matters.
        return highlight(el) if class_list(el).include?("lntable")

        rows = el.css("tr").map { |tr| tr.css("th, td").map { |cell| table_cell(cell) } }
        rows.reject!(&:empty?)
        return "" if rows.empty?

        width = rows.map(&:size).max
        rows.each { |row| row.fill("", row.size...width) }

        header = rows.shift
        lines = ["| #{header.join(' | ')} |", "| #{Array.new(width, '---').join(' | ')} |"]
        rows.each { |row| lines << "| #{row.join(' | ')} |" }
        lines.join("\n")
      end

      def table_cell(cell)
        flow_inline(inline(cell)).strip.gsub("|", "\\|")
      end

      def blockquote(el)
        body = blocks(el).strip
        return "" if body.empty?

        body.split("\n", -1).map { |line| line.empty? ? ">" : "> #{line}" }.join("\n")
      end

      # --- inline level ----------------------------------------------------

      def inline(node)
        buffer = +""
        skipping = false

        node.children.each do |child|
          if child.comment?
            marker = child.text.strip
            skipping = true if marker == "noindex"
            skipping = false if marker == "/noindex"
            next
          end

          next if skipping

          if child.text?
            buffer << child.text
          elsif child.element? && !dropped?(child)
            buffer << inline_for(child)
          end
        end

        buffer
      end

      def inline_for(el)
        case el.name
        when "br" then HARD_BREAK
        when "code", "kbd", "samp", "tt" then code_span(el)
        when "strong", "b" then emphasize(inline(el), "**")
        when "em", "i", "var", "cite" then emphasize(inline(el), "*")
        when "del", "s" then emphasize(inline(el), "~~")
        when "a" then link(el)
        when "img" then image(el)
        when "wbr" then ""
        else
          text = inline(el)
          # Attribute captions of JSON-schema pages ("Default:", "Pattern:").
          return emphasize(text, "**") if class_list(el).include?("resources__attrs_name")

          text
        end
      end

      def code_span(el)
        text = el.text.gsub(/\r?\n/, " ")
        return "" if text.strip.empty?

        ticks = "`" * ((text.scan(/`+/).map(&:length).max || 0) + 1)
        pad = text.start_with?("`") || text.end_with?("`") ? " " : ""
        "#{ticks}#{pad}#{text}#{pad}#{ticks}"
      end

      def emphasize(text, marker)
        match = text.match(/\A(\s*)(.*?)(\s*)\z/m)
        return text if match.nil? || match[2].empty?

        "#{match[1]}#{marker}#{match[2]}#{marker}#{match[3]}"
      end

      def link(el)
        href = el["href"].to_s.strip
        text = flow_inline(inline(el)).strip

        return text if href.empty? || href.start_with?("javascript:")

        url = absolutize(href)
        text = url if text.empty?

        "[#{text}](#{url})"
      end

      def image(el)
        src = el["src"].to_s.strip
        return "" if src.empty?

        alt = el["alt"].to_s.strip
        "![#{alt}](#{absolutize(src)})"
      end

      # --- helpers ---------------------------------------------------------

      def absolutize(href)
        # A link to this same site, written out in full, is still an internal
        # link: reduce it to a root-relative path so it is rewritten like any
        # other. Only the remaining absolute URLs (other hosts) are left as-is.
        same_site = same_site_path(href)
        href = same_site unless same_site.nil?

        return href if href.match?(%r{\A[a-z][a-z0-9+.\-]*:}i) || href.start_with?("//")

        path =
          if href.start_with?("#")
            "#{@page_url}#{href}"
          elsif href.start_with?("/")
            href
          else
            begin
              resolved = URI.join("https://example.invalid#{@page_url}", href)
              fragment = resolved.fragment ? "##{resolved.fragment}" : ""
              "#{resolved.path}#{resolved.query ? "?#{resolved.query}" : ''}#{fragment}"
            rescue URI::Error, ArgumentError
              return href
            end
          end

        path = @link_rewriter.call(path) if @link_rewriter
        @base_url.empty? ? path : "#{@base_url}#{path}"
      end

      # Returns the root-relative path of an absolute link that points back at
      # this site (`@base_url`), or nil when it does not. A host that merely
      # starts with @base_url (`deckhouse.iodev`) is not this site.
      def same_site_path(href)
        return nil if @base_url.empty? || !href.start_with?(@base_url)

        rest = href[@base_url.length..]
        return "/" if rest.empty?

        rest.start_with?("/", "#", "?") ? rest : nil
      end

      # Prefixes the first line with `marker` and aligns the rest under it, so
      # that nested blocks stay inside the list item.
      def indent(text, marker)
        pad = " " * marker.length
        first = true

        text.split("\n", -1).map do |line|
          if first
            first = false
            "#{marker}#{line}".rstrip
          elsif line.empty?
            ""
          else
            "#{pad}#{line}"
          end
        end.join("\n")
      end

      def dropped?(el)
        return true if DROPPED_TAGS.include?(el.name)
        return true if DROPPED_IDS.include?(el["id"].to_s)

        (class_list(el) & DROPPED_CLASSES).any?
      end

      def inline?(el)
        INLINE_TAGS.include?(el.name)
      end

      def class_list(el)
        el["class"].to_s.split(/\s+/)
      end

      def collapse(text)
        text.gsub(/[ \t\r\f\v]*\n[ \t\r\f\v]*/, "\n").gsub(/[ \t]{2,}/, " ")
      end

      # Renders a run of inline content as a single paragraph: the newlines of
      # the HTML source layout collapse to spaces, and only an explicit `<br>`
      # (carried through as HARD_BREAK) becomes a real line break.
      def flow_text(text)
        collapse(text).gsub(/\s*\n\s*/, " ").gsub(/[ \t]*#{HARD_BREAK}[ \t]*/, "\n")
      end

      # flow_text for contexts that cannot hold a line break — headings and
      # table cells — where a `<br>` degrades to a space.
      def flow_inline(text)
        collapse(text).gsub(/\s*\n\s*/, " ").gsub(HARD_BREAK, " ").gsub(/[ \t]{2,}/, " ")
      end

      # Trims trailing whitespace and collapses runs of blank lines, leaving
      # fenced code blocks untouched.
      def normalize(text)
        # Any HARD_BREAK that escaped flow_text/flow_inline would print as a NUL;
        # drop it as a last resort (the flow helpers cover every real path).
        text = text.delete(HARD_BREAK)

        fence = nil
        blank = 0
        lines = []

        text.split("\n", -1).each do |line|
          if fence
            lines << line
            fence = nil if line.strip.start_with?(fence)
            next
          end

          opening = line.strip[/\A(`{3,}|~{3,})/, 1]
          if opening
            fence = opening
            blank = 0
            lines << line.rstrip
            next
          end

          stripped = line.rstrip
          if stripped.empty?
            blank += 1
            lines << "" if blank <= 1
          else
            blank = 0
            lines << stripped
          end
        end

        lines.join("\n").strip
      end
    end
  end
end
