#!/bin/bash

source /deckhouse/shell_lib.sh

function __main__() {
  enabled::disable_module_in_kubernetes_versions_less_than 1.15.0
  enabled::fail_if_values_are_not_set global.discovery.podSubnet
  echo "true" > "$MODULE_ENABLED_RESULT"
}

enabled::run "$@"
