#!/bin/bash

# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /deckhouse/shell_lib.sh

function __main__() {
  enabled::disable_module_if_cluster_is_not_bootstraped

  if values::has global.modules.publicDomainTemplate ; then
    https_mode=$(values::get_first_defined userAuthn.https.mode global.modules.https.mode)
    if [ "$https_mode" != "Disabled" ] ; then
      echo "true" > $MODULE_ENABLED_RESULT
    else
      echo "false" > $MODULE_ENABLED_RESULT
      echo "https.mode is set to 'Disabled' - set it in ModuleConfig/global." > $MODULE_ENABLED_REASON
    fi
  else
    echo "false" > $MODULE_ENABLED_RESULT
    echo "spec.settings.modules.publicDomainTemplate is not set in the global configuration, configure it in ModuleConfig/global." > $MODULE_ENABLED_REASON
  fi
}

enabled::run $@
