#!/bin/bash

source /deckhouse/shell_lib.sh

function __main__() {
  enabled::disable_module_if_cluster_is_not_bootstraped
  if ! values::array_has global.enabledModules "user-authn-crd" ; then
    echo "You must enable the user-authn-crd module for the module to work."
    exit 1
  fi

  if values::has global.modules.publicDomainTemplate ; then
    https_mode=$(values::get_first_defined userAuthn.https.mode global.modules.https.mode)
    if [ "$https_mode" != "Disabled" ] ; then
      echo "true" > $MODULE_ENABLED_RESULT
    else
      echo "false" > $MODULE_ENABLED_RESULT
    fi
  else
    echo "false" > $MODULE_ENABLED_RESULT
  fi
}

enabled::run $@
