#!/bin/bash

source /antiopa/shell_lib.sh

function __main__() {
  module::disable_if_cluster_is_not_bootstraped

  if values::get global.modules.publicDomainTemplate ; then
    https_mode=$(values::get_first_defined userAuthn.https.mode global.modules.https.mode)
    if [ "$https_mode" == "Disabled" ] ; then
      echo "false" > $MODULE_ENABLED_RESULT
    else
      echo "true" > $MODULE_ENABLED_RESULT
    fi
  else
    echo "false" > $MODULE_ENABLED_RESULT
  fi
}

hook::run $@
