{{- $moduleGateway := dict }}
{{- include "helm_lib_module_gateway" (list . $moduleGateway) }}
{{- if and $moduleGateway .Values.global.modules.publicDomainTemplate (include "helm_lib_kind_exists" (list . "ListenerSet")) }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  {{- include "helm_lib_module_labels" (list . (dict "app" "upmeter")) | nindent 2 }}
  name: upmeter
  namespace: d8-cni-cilium
spec:
  listeners:
  {{- if (include "helm_lib_module_https_route_tls_enabled" .) }}
  - allowedRoutes:
      namespaces:
        from: Same
    hostname: {{ include "helm_lib_module_public_domain" (list . "status") }}
    name: status
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: {{ include "helm_lib_module_https_secret_name" (list . "httproute-tls-status") }}
        namespace: d8-{{ .Chart.Name }}
      mode: Terminate
  - allowedRoutes:
      namespaces:
        from: Same
    hostname: {{ include "helm_lib_module_public_domain" (list . "status") }}
    name: status-redirect
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: Same
    hostname: {{ include "helm_lib_module_public_domain" (list . .Chart.Name) }}
    name: upmeter
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: {{ include "helm_lib_module_https_secret_name" (list . "httproute-tls-webui") }}
        namespace: d8-{{ .Chart.Name }}
      mode: Terminate
  - allowedRoutes:
      namespaces:
        from: Same
    hostname: {{ include "helm_lib_module_public_domain" (list . .Chart.Name) }}
    name: upmeter-redirect
    port: 80
    protocol: HTTP
  {{- else }}
  - allowedRoutes:
      namespaces:
        from: Same
    hostname: {{ include "helm_lib_module_public_domain" (list . "status") }}
    name: status
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: Same
    hostname: {{ include "helm_lib_module_public_domain" (list . .Chart.Name) }}
    name: upmeter
    port: 80
    protocol: HTTP
  {{- end }}
  parentRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ $moduleGateway.name }}
    namespace: {{ $moduleGateway.namespace }}
{{- end }}
