---
apiVersion: v1
kind: Namespace
metadata:
  name: d8-{{ .Chart.Name }}
  {{- $namespaceLabels := dict
    "prometheus.deckhouse.io/rules-watcher-enabled" "true"
    "security.deckhouse.io/pod-policy" "restricted"
  }}
  {{- if .Values.global.enabledModules | has "admission-policy-engine-crd" }}
    {{- $_ := set $namespaceLabels "security.deckhouse.io/enable-security-policy-check" "true" }}
  {{- end }}
  {{- include "helm_lib_module_labels" (list . $namespaceLabels) | nindent 2 }}
---
{{- include "helm_lib_kube_rbac_proxy_ca_certificate" (list . (printf "d8-%s" .Chart.Name)) }}
