#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: service_monitors
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      group: main
      keepFullObjectsInMemory: false
      labelSelector:
        matchLabels:
          prometheus: main
        matchExpressions:
        - key: heritage
          operator: NotIn
          values: ["deckhouse"]
      namespace:
        labelSelector:
          matchLabels:
            heritage: deckhouse
      jqFilter: .metadata.name
    - name: pod_monitors
      apiVersion: monitoring.coreos.com/v1
      kind: PodMonitor
      group: main
      keepFullObjectsInMemory: false
      labelSelector:
        matchLabels:
          prometheus: main
        matchExpressions:
        - key: heritage
          operator: NotIn
          values: ["deckhouse"]
      namespace:
        labelSelector:
          matchLabels:
            heritage: deckhouse
      jqFilter: .metadata.name
    - name: rules
      apiVersion: monitoring.coreos.com/v1
      kind: PrometheusRule
      group: main
      keepFullObjectsInMemory: false
      labelSelector:
        matchLabels:
          prometheus: main
          component: rules
        matchExpressions:
        - key: heritage
          operator: NotIn
          values: ["deckhouse"]
      namespace:
        labelSelector:
          matchLabels:
            heritage: deckhouse
      jqFilter: .metadata.name
    - name: custom_services
      apiVersion: v1
      kind: Service
      group: main
      keepFullObjectsInMemory: false
      labelSelector:
        matchExpressions:
        - key: prometheus-custom-target
          operator: Exists
      jqFilter: .metadata.name
EOF
}


function __main__() {
  context::jq -rc ' .snapshots.service_monitors | length | {"name":"d8_monitoring_custom_unknown_service_monitor_total", "set": . }' >> $METRICS_PATH
  context::jq -rc ' .snapshots.pod_monitors | length | {"name":"d8_monitoring_custom_unknown_pod_monitor_total", "set": . }' >> $METRICS_PATH
  context::jq -rc ' .snapshots.rules | length | {"name":"d8_monitoring_custom_unknown_prometheus_rules_total", "set": . }' >> $METRICS_PATH
  context::jq -rc ' .snapshots.custom_services | length | {"name":"d8_monitoring_custom_old_prometheus_custom_targets_total", "set": . }' >> $METRICS_PATH
}

hook::run "$@"
