#!/bin/bash

### Migration 23.10.2020: Remove in final `domain migration` release

source /deckhouse/shell_lib.sh

function __config__() {
  modules=$({ deckhouse-controller module list 2>/dev/null || echo ""; } | jq -Rr '. | [inputs | .[:-1]][:-1] + ["monitoring", "system", "frontend"] | join("|")')

  cat << EOF
    configVersion: v1
    kubernetes:
    - name: deployments
      group: main
      queue: /modules/$(module::name::kebab_case)
      apiVersion: apps/v1
      kind: Deployment
      keepFullObjectsInMemory: false
      labelSelector:
        matchExpressions:
        - key: heritage
          operator: NotIn
          values: ["deckhouse"]
      jqFilter: &filter |
        if
        (
          [
            .spec.template.spec.nodeSelector // {} | to_entries[] |
            select((.key | test("^node-role\\\.flant\\\.com/(${modules})$")) and .value == "")
          ] +
          [
            (.spec.template.spec.affinity.nodeAffinity | .. | .matchExpressions? // []) | .[] |
            select(.key | test("^node-role\\\.flant\\\.com/(${modules})$"))
          ] +
          [
            (.spec.template.spec.tolerations // []) | .[] |
            select(.key=="dedicated.flant.com" and (.value // "" | test("^(${modules}|)$")))
          ]
          | length > 0
        )
        then
        {
          "name": "migrate_domain_controllers",
          "group": "/modules/$(module::name::kebab_case)/migrate_domain_alert#migrate_domain_controllers",
          "set": 1,
          "labels":
          {
            "name": .metadata.name,
            "controller": .kind,
            "namespace": .metadata.namespace
          }
        }
        else null end
    - name: daemonsets
      group: main
      queue: /modules/$(module::name::kebab_case)
      apiVersion: apps/v1
      kind: DaemonSet
      keepFullObjectsInMemory: false
      labelSelector:
        matchExpressions:
        - key: heritage
          operator: NotIn
          values: ["deckhouse"]
      jqFilter: *filter
    - name: statefulsets
      group: main
      queue: /modules/$(module::name::kebab_case)
      apiVersion: apps/v1
      kind: StatefulSet
      keepFullObjectsInMemory: false
      labelSelector:
        matchExpressions:
        - key: heritage
          operator: NotIn
          values: ["deckhouse"]
      jqFilter: *filter
EOF
}

function __main__() {
  context::jq -c '.. | .filterResult? | select(.)' >> $METRICS_PATH
  # Used to hack metrics deletion
  group="/modules/$(module::name::kebab_case)/migrate_domain_alert#migrate_domain_controllers"
  jq -c --arg group "$group" '.group = $group' <<< '{"name": "migrate_domain_controllers", "set": 0, "labels": {"name": "none", "controller": "none", "namespace": "none"}}' >> $METRICS_PATH
}

hook::run $@
