#!/usr/bin/env bash

source /shell_lib.sh

function config() {
cat <<EOF
configVersion: v1
kubernetesCustomResourceConversion:
- name: v1alpha1_to_v1alpha2
  crdName: clusterloggingconfigs.deckhouse.io
  conversions:
  - fromVersion: deckhouse.io/v1alpha1
    toVersion: deckhouse.io/v1alpha2
EOF
}

function __on_conversion::v1alpha1_to_v1alpha2() {
  if converted=$(context::jq -r '.review.request.objects // [] | map(
    if .apiVersion == "deckhouse.io/v1alpha1" then
      .apiVersion = "deckhouse.io/v1alpha2" |
      if .spec.kubernetesPods.namespaceSelector then
        .spec.kubernetesPods.namespaceSelector -= { matchNames: .spec.kubernetesPods.namespaceSelector.matchNames } |
        .spec.kubernetesPods.namespaceSelector -= { excludeNames: .spec.kubernetesPods.namespaceSelector.excludeNames }
      else . end
    else . end
  )'); then
    cat <<EOF >"$CONVERSION_RESPONSE_PATH"
{"convertedObjects": $converted}
EOF
  else
    cat <<EOF >"$CONVERSION_RESPONSE_PATH"
{"failedMessage":"Conversion of clusterloggingconfigs.deckhouse.io from v1alpha1 to v1alpha2 failed"}
EOF
  fi
}

hook::run "$@"
