#!/usr/bin/env bash

# Copyright 2023 Flant JSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE

source /shell_lib.sh

function __config__(){
  cat <<EOF
configVersion: v1
kubernetes:
  - name: operator_trivy_module_config
    apiVersion: deckhouse.io/v1alpha1
    kind: ModuleConfig
    queue: operator_trivy_module_config
    group: main
    executeHookOnEvent: []
    executeHookOnSynchronization: false
    keepFullObjectsInMemory: false
    nameSelector:
      matchNames:
      - operator-trivy
    jqFilter: |
      {
        "enabled": .spec.enabled,
      }
kubernetesValidating:
- name: ape-moduleconfig.deckhouse.io
  group: main
  rules:
  - apiGroups:   ["deckhouse.io"]
    apiVersions: ["*"]
    operations:  ["CREATE", "UPDATE]
    resources:   ["moduleconfigs"]
    scope:       "Cluster"
EOF
}

function __main__() {
  mcName=$(context::jq -r '.review.request.object.metadata.name')
  if [[ "$mcName" == "admission-policy-engine" ]]; then
    denyVulnerableImagesEnabled="$(context::jq -r '.review.request.object.spec.settings.denyVulnerableImages.enabled')"
    operatorTrivyEnabled="$(context::jq -r '.snapshots.operator_trivy_module_config[].filterResult.enabled')"
    if [[ "$denyVulnerableImagesEnabled" == "true" ]] && [[ "$operatorTrivyEnabled" != "true" ]]; then
      cat <<EOF > "$VALIDATING_RESPONSE_PATH"
{"allowed":false, "message":"moduleconfigs.deckhouse.io \"$mcName\", .spec.settings.denyVulnerableImages can't be enabled when operator-trivy module is disabled" }
EOF
      return 0
    fi
  fi

  cat <<EOF > "$VALIDATING_RESPONSE_PATH"
{"allowed":true}
EOF

}

hook::run "$@"
