diff --git a/Makefile b/Makefile
index b1c90e0..9127bf8 100644
--- a/Makefile
+++ b/Makefile
@@ -77,6 +77,7 @@ clean-image: ## Removes local image
 
 .PHONY: build
 build:  ## Build ingress controller, debug tool and pre-stop hook.
+  ifeq ($(USE_DOCKER), true)
 	@build/run-in-docker.sh \
 		PKG=$(PKG) \
 		ARCH=$(ARCH) \
@@ -85,6 +86,9 @@ build:  ## Build ingress controller, debug tool and pre-stop hook.
 		TAG=$(TAG) \
 		GOBUILD_FLAGS=$(GOBUILD_FLAGS) \
 		build/build.sh
+  else
+	@build/build.sh
+  endif
 
 .PHONY: build-plugin
 build-plugin:  ## Build ingress-nginx krew plugin.
