Index: Makefile
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/Makefile b/Makefile
--- a/Makefile	(revision 162b3700db1ddf75248d683f03162dd247f5610d)
+++ b/Makefile	(revision ef82c35371a4a2091e459afb8b2dba87f1a83083)
@@ -77,6 +77,7 @@

 .PHONY: build
 build:  ## Build ingress controller, debug tool and pre-stop hook.
+ifeq ($(USE_DOCKER), true)
 	@build/run-in-docker.sh \
 		PKG=$(PKG) \
 		ARCH=$(ARCH) \
@@ -85,6 +86,9 @@
 		TAG=$(TAG) \
 		GOBUILD_FLAGS=$(GOBUILD_FLAGS) \
 		build/build.sh
+else
+	@build/build.sh
+endif

 .PHONY: build-plugin
 build-plugin:  ## Build ingress-nginx krew plugin.
