#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  jo -p afterHelm=10
}

function __main__() {
  if values::has prometheus.internal.deployDexAuthenticator ; then
    allowedGroups=""
    if values::has prometheus.allowedUserGroups ; then
      allowedGroups="allowedGroups: $(values::get prometheus.allowedUserGroups)"
    fi
    cat <<EOF | kubectl apply -f -
apiVersion: deckhouse.io/v1alpha1
kind: DexAuthenticator
metadata:
  name: grafana
  namespace: kube-prometheus
  labels:
    heritage: deckhouse
    module: grafana
    app: dex-authenticator
spec:
  applicationDomain: "$(common::module_public_domain grafana)"
  applicationIngressCertificateSecretName: "ingress-tls"
  applicationIngressClassName: "$(common::module_ingress_class)"
  $allowedGroups
EOF
  else
     kubectl -n kube-prometheus delete dex-authenticator grafana >/dev/null 2>&1 || true
  fi
}

hook::run $@
