{{- $telemetryAPI := $.Values.istio.telemetryAPI | default dict }}
{{- $globalVersionInfo := get .Values.istio.internal.versionMap .Values.istio.internal.globalVersion }}
{{- $operatorFreeControlPlane := not (get $globalVersionInfo "supportsOperator") }}
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: d8-main
  namespace: d8-istio
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
spec:
  accessLogging:
  - disabled: false
    providers:
    - name: d8-main
{{- if or $telemetryAPI.enabled $operatorFreeControlPlane }}
  metrics:
  - providers:
    - name: prometheus
{{- if (include "istioTracingProvider" .) }}
  tracing:
  - providers:
    - name: deckhouse-tracing
    randomSamplingPercentage: {{ .Values.istio.tracing.sampling | default 1.0 }}
{{- end }}
{{- end }}
