#!/bin/bash -e

export DEBIAN_FRONTEND=noninteractive

apt -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade -y
apt -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install -qy apt-transport-https
apt -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" remove -y unattended-upgrades

curl -fsSL "https://packages.cloud.google.com/apt/doc/apt-key.gpg" | apt-key add -
curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | sudo apt-key add -
echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
echo "deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

apt update
