#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

apt -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install -qy linux-generic-hwe-18.04 linux-headers-generic-hwe-18.04 linux-image-generic-hwe-18.04
touch /var/lib/bashible/reboot
