#!/bin/bash -e

apt -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install -qy "docker.io=18.09.*"
apt-mark hold "docker.io"

cat << "EOF" > /etc/docker/daemon.json
{
        "log-driver": "json-file",
        "log-opts": {
                "max-file": "5",
                "max-size": "10m"
        }
}
EOF
systemctl restart docker

units="docker.service"

for unit in $units; do
  systemctl enable "$unit" && systemctl restart "$unit"
done
