#!/bin/bash

package=kubernetes-cni
version=0.7.5

if ! apt list --installed $package | grep -F $version; then
  apt-mark unhold $package
  apt install -qy "$package=$version-*"
  apt-mark hold $package
fi
