#!/bin/bash

{{- if eq .bashibleBundle "ubuntu-18.04" }}
export DEBIAN_FRONTEND=noninteractive

if ! apt -qq list nginx >/dev/null | grep installed >/dev/null 2>/dev/null ; then
  apt -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install -qy "nginx=1.14.0-*" "libnginx-mod-stream=1.14.0-*"
  apt-mark hold nginx libnginx-mod-stream
fi
{{- else if eq .bashibleBundle "centos-7" }}
if ! rpm -q nginx >/dev/null >/dev/null ; then
  yum install -y "nginx-1:1.16.1-*" "nginx-mod-stream-1:1.16.1-*"
  yum versionlock "nginx-1:1.16.1-*" "nginx-mod-stream-1:1.16.1-*"
fi
{{- end }}

if [ ! -f "/etc/systemd/system/kubernetes-api-proxy.service" ] ; then
  cat << "EOF" > /etc/systemd/system/kubernetes-api-proxy.service
[Unit]
Description=nginx TCP stream proxy for kubernetes-api-servers
After=network.target

[Service]
Type=forking
PIDFile=/var/run/kubernetes-api-proxy.pid
ExecStartPre=/usr/sbin/nginx -t -c /etc/kubernetes/kubernetes-api-proxy/nginx.conf
ExecStart=/usr/sbin/nginx -c /etc/kubernetes/kubernetes-api-proxy/nginx.conf
ExecReload=/usr/sbin/nginx -c /etc/kubernetes/kubernetes-api-proxy/nginx.conf -s reload
ExecStop=/bin/kill -s QUIT $MAINPID
TimeoutStopSec=5
KillMode=mixed

[Install]
WantedBy=multi-user.target
EOF
fi

if systemctl is-active --quiet nginx ; then
  systemctl stop nginx
  systemctl disable nginx
fi

if [ ! -d "/etc/kubernetes/kubernetes-api-proxy" ] ; then
  mkdir -p /etc/kubernetes/kubernetes-api-proxy
fi

if [ ! -n "$(grep -P '^127.0.0.1 kubernetes$' /etc/hosts)" ] ; then
  echo '127.0.0.1 kubernetes' >> /etc/hosts
fi

if [ ! -f "/etc/systemd/system/kubernetes-api-proxy-configurator.timer" ] ; then
  cat << "EOF" > /etc/systemd/system/kubernetes-api-proxy-configurator.timer
[Unit]
Description=kubernetes api proxy timer

[Timer]
OnBootSec=1m
OnUnitActiveSec=1m

[Install]
WantedBy=multi-user.target
EOF
fi

if [ ! -f "/etc/systemd/system/kubernetes-api-proxy-configurator.service" ] ; then
  cat << "EOF" > /etc/systemd/system/kubernetes-api-proxy-configurator.service
[Unit]
Description=Bashible service

[Service]
EnvironmentFile=/etc/environment
ExecStart=/var/lib/bashible/kubernetes-api-proxy-configurator.sh
EOF
fi

systemctl daemon-reload
