{
 "title": "Control Plane Status",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"kube-apiserver\"}, instance)"
    }
   },
   {
    "name": "resource",
    "label": "Resource",
    "query": {
     "query": "label_values(apiserver_request_total, resource)"
    }
   },
   {
    "name": "verb",
    "label": "VERB",
    "query": {
     "query": "label_values(apiserver_request_total{verb!~\"CONNECT|WATCH\"}, verb)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "API Servers UP",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(up{source=\"deckhouse\", job=\"kube-apiserver\"} == 1) / sum(up{source=\"deckhouse\", job=\"kube-apiserver\"})) * 100"
    }
   ]
  },
  {
   "title": "Controller Managers UP",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(up{source=\"deckhouse\", job=\"kube-controller-manager\"} == 1) / sum(up{source=\"deckhouse\", job=\"kube-controller-manager\"})) * 100"
    }
   ]
  },
  {
   "title": "Schedulers UP",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(up{source=\"deckhouse\", job=\"kube-scheduler\"} == 1) / sum(up{source=\"deckhouse\", job=\"kube-scheduler\"})) * 100"
    }
   ]
  },
  {
   "title": "Kubernetes Resources Count",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_created{source=\"deckhouse\"})",
     "legendFormat": "Namespaces"
    },
    {
     "expr": "count(kube_daemonset_created{source=\"deckhouse\"})",
     "legendFormat": "DaemonSets"
    },
    {
     "expr": "count(kube_deployment_created{source=\"deckhouse\"})",
     "legendFormat": "Deployments"
    },
    {
     "expr": "count(kube_statefulset_created{source=\"deckhouse\"})",
     "legendFormat": "StatefulSets"
    },
    {
     "expr": "count(kube_replicaset_created{source=\"deckhouse\"})",
     "legendFormat": "ReplicaSets"
    },
    {
     "expr": "count(kube_pod_created{source=\"deckhouse\"})",
     "legendFormat": "Pods"
    },
    {
     "expr": "count(kube_verticalpodautoscaler_labels{source=\"deckhouse\"})",
     "legendFormat": "VPA"
    },
    {
     "expr": "count(kube_poddisruptionbudget_created{source=\"deckhouse\"})",
     "legendFormat": "PDB"
    },
    {
     "expr": "count(kube_persistentvolumeclaim_info{source=\"deckhouse\"})",
     "legendFormat": "PVC"
    },
    {
     "expr": "count(kube_persistentvolume_info{source=\"deckhouse\"})",
     "legendFormat": "PV"
    },
    {
     "expr": "count(kube_cronjob_created{source=\"deckhouse\"})",
     "legendFormat": "CronJobs"
    },
    {
     "expr": "count(kube_job_created{source=\"deckhouse\"})",
     "legendFormat": "Jobs"
    },
    {
     "expr": "count(kube_secret_created{source=\"deckhouse\"})",
     "legendFormat": "Secrets"
    },
    {
     "expr": "count(kube_configmap_created{source=\"deckhouse\"})",
     "legendFormat": "ConfigMaps"
    },
    {
     "expr": "count(kube_service_created{source=\"deckhouse\"})",
     "legendFormat": "Services"
    },
    {
     "expr": "count(kube_endpoint_created{source=\"deckhouse\"})",
     "legendFormat": "Endpoints"
    },
    {
     "expr": "count(kube_node_created{source=\"deckhouse\"})",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "API Servers count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(up{source=\"deckhouse\", job=\"kube-apiserver\"})"
    }
   ]
  },
  {
   "title": "Controller Managers count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(up{source=\"deckhouse\", job=\"kube-controller-manager\"})"
    }
   ]
  },
  {
   "title": "Schedulers count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(up{source=\"deckhouse\", job=\"kube-scheduler\"})"
    }
   ]
  },
  { "title": "Kube-apiserver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Kube-apiserver CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kube-apiserver\", instance=~\"$instance:.*\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kube-apiserver Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kube-apiserver\", instance=~\"$instance:.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kube-apiserver requests rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(verb) (rate(apiserver_request_total{source=\"deckhouse\", verb!~\"CONNECT|WATCH\", verb=~\"$verb\", instance=~\"$instance:.*\", resource=~\"$resource\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Kube-apiserver requests rate",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by(verb, resource, subresource) (rate(apiserver_request_total{source=\"deckhouse\", verb!~\"CONNECT|WATCH\", verb=~\"$verb\", instance=~\"$instance:.*\", resource=~\"$resource\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Kube-apiserver response sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max by (verb) (rate(apiserver_response_sizes_sum{source=\"deckhouse\", verb!~\"CONNECT|WATCH\", verb=~\"$verb\", instance=~\"$instance:.*\", resource=~\"$resource\"}[$__rate_interval])/rate(apiserver_response_sizes_count{source=\"deckhouse\", verb!~\"CONNECT|WATCH\", verb=~\"$verb\", instance=~\"$instance:.*\", resource=~\"$resource\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Kube-apiserver response sizes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "max by (verb, resource, subresource) (rate(apiserver_response_sizes_sum{source=\"deckhouse\", verb!~\"CONNECT|WATCH\", verb=~\"$verb\", instance=~\"$instance:.*\", resource=~\"$resource\"}[$__rate_interval])/rate(apiserver_response_sizes_count{source=\"deckhouse\", verb!~\"CONNECT|WATCH\", verb=~\"$verb\", instance=~\"$instance:.*\", resource=~\"$resource\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Kube-apiserver latency bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_bucket{source=\"deckhouse\", verb!~\"CONNECT|WATCH\", job=\"kube-apiserver\", instance=~\"$instance:6443\", verb=~\"$verb\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Kube-apiserver latency",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "max by (verb, resource, subresource) (rate(apiserver_request_duration_seconds_sum{source=\"deckhouse\", verb!~\"CONNECT|WATCH\", subresource!~\"exec|log\", verb=~\"$verb\", instance=~\"$instance:.*\", resource=~\"$resource\"}[$__range])/rate(apiserver_request_duration_seconds_count{source=\"deckhouse\", verb!~\"CONNECT|WATCH\", subresource!~\"exec|log\", verb=~\"$verb\", instance=~\"$instance:.*\", resource=~\"$resource\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Kube-apiserver latency bucket %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_bucket{source=\"deckhouse\", verb!~\"CONNECT|WATCH\", job=\"kube-apiserver\", instance=~\"$instance:6443\", verb=~\"$verb\"}[$__rate_interval])) by (le) / scalar(sum(rate(apiserver_request_duration_seconds_count{source=\"deckhouse\", verb!~\"CONNECT|WATCH\", job=\"kube-apiserver\", instance=~\"$instance:6443\", verb=~\"$verb\"}[$__rate_interval])))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Kube-apiserver latency time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{source=\"deckhouse\", verb!~\"CONNECT|WATCH\", job=\"kube-apiserver\", instance=~\"$instance:6443\", verb=~\"$verb\"}[$__rate_interval])) by (instance, le))"
    }
   ]
  },
  {
   "title": "Etcd requests latency bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_request_duration_seconds_bucket{source=\"deckhouse\", job=\"kube-apiserver\", instance=~\"$instance:6443\", verb=~\"$verb\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Etcd latency time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_request_duration_seconds_bucket{source=\"deckhouse\", job=\"kube-apiserver\", instance=~\"$instance:6443\"}[$__rate_interval])) by (instance, le))"
    }
   ]
  },
  { "title": "Kube-scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Kube-scheduler CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kube-scheduler\", instance=~\"$instance:.*\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kube-scheduler Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kube-scheduler\", instance=~\"$instance:.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Kube-controller-manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Kube-controller-manager CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kube-controller-manager\", instance=~\"$instance:.*\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kube-controller-manager Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kube-controller-manager\", instance=~\"$instance:.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}