#!/bin/bash
# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -Eeo pipefail
package="kubectl"
package_file="${package}.x86_64.rpm"
rpm_name="$(rpm -qip ${package_file} 2>/dev/null | grep Name | awk '{print $3}')"
rpm_version="$(rpm -qip ${package_file} 2>/dev/null | grep Version | awk '{print $3}')"

if ! rpm --quiet -q "${rpm_name}-${rpm_version}"; then
  rpm -U --oldpackage $package_file
else
  echo "RPM ${package_file} already installed."
fi

yum versionlock add ${package}
