#!/bin/bash

source /deckhouse/shell_lib.sh

function __main__() {
  module::disable_if_cluster_is_not_bootstraped

  if ! values::array_has global.enabledModules "operator-prometheus-crd" ; then
    echo "You must enable the operator-prometheus-crd module for the module to work."
    exit 1
  fi

  echo "true" > $MODULE_ENABLED_RESULT
}

hook::run $@
