#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p afterHelm=20
}

function __main__() {
  if [[ "$(kubectl get ns kube-dashboard --no-headers 2> /dev/null |wc -l)" -eq "1" ]] && [[ "$(kubectl get ns kube-dashboard -o json |jq .metadata.labels.heritage -r)" != "antiopa" ]]; then
    kubectl delete clusterrolebinding kubernetes-dashboard || true
    kubectl delete clusterrole dashboard || true
    kubectl delete ns kube-dashboard
    echo "Delete old ns kube-dashboard"
    for i in `seq 1 6`; do
      echo "wait ${i}0 second for terminating namespace"
      sleep 10
      if [[ "$(kubectl get ns kube-dashboard --no-headers 2> /dev/null |wc -l)" -eq "0" ]]; then
        exit 0
      fi
    done
    exit 1
  fi
}

function __main_old__() {
  __main__ $@
}

hook::run $@

