#!/bin/sh

# Current wrapper
SELF="$(readlink -f "$0")"

# Are looking for the real clang, skipping ourselves
REAL=""
for p in $(echo "$PATH" | tr ':' ' '); do
    CAND="$p/clang"
    if [ -x "$CAND" ]; then
        CAND_REAL="$(readlink -f "$CAND")"
        if [ "$CAND_REAL" != "$SELF" ]; then
            REAL="$CAND_REAL"
            break
        fi
    fi
done

if [ -z "$REAL" ]; then
    echo "clang wrapper: not found" >&2
    exit 1
fi

# Logging
echo "[CC] clang $@" >&2

# Transfer control
exec "$REAL" "$@"
