#!/bin/bash

# Copyright 2021 Flant CJSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    afterHelm: 15
EOF
}

function __main__() {
  for i in $(seq 1 120); do
    if kubectl -n kube-system get pod -l k8s-app=kube-dns -o json | jq -e '[
      .items[].metadata | select(.name|startswith("coredns"))
    ] | length == 0' >/dev/null; then
      kubernetes::delete_if_exists "" clusterrole/system:coredns
      kubernetes::delete_if_exists "" clusterrolebinding/system:coredns
      kubernetes::delete_if_exists kube-system serviceaccount/coredns
      kubernetes::delete_if_exists kube-system configmap/coredns
      return 0
    fi

    echo "Waiting until all CoreDNS Pods are terminated..."
    sleep 1
  done

  if [[ $i -ge 120 ]] ; then
    >&2 echo "Timeout waiting until all CoreDNS Pods are terminated"
    return 1
  fi
}

hook::run "$@"
