#!/bin/bash

# Copyright 2021 Flant CJSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 10
    kubernetes:
    - name: kube_dns_svc
      group: main
      keepFullObjectsInMemory: false
      executeHookOnEvent: []
      executeHookOnSynchronization: false
      apiVersion: v1
      kind: Service
      namespace:
        nameSelector:
          matchNames: [kube-system]
      nameSelector:
        matchNames: [kube-dns]
      jqFilter: '.spec.type == "ClusterIP"'
EOF
}

function __main__() {
  kubernetes::delete_if_exists::non_cascading kube-system deployment/coredns

  # we'll recreate a kube-dns Service with "type: ExternalName" to support legacy code in client applications
  if context::is_true 'snapshots.kube_dns_svc.0.filterResult'; then
    kubernetes::delete_if_exists kube-system service/kube-dns
  fi
}

hook::run "$@"
