#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    afterHelm: 15
EOF
}

function __main__() {
  for i in $(seq 1 120); do
    if kubectl -n kube-system get pod -l k8s-app=kube-dns -o json | jq -e '[
      .items[].metadata | select(.name|startswith("coredns"))
    ] | length == 0' >/dev/null; then
      kubernetes::delete_if_exists "" clusterrole/system:coredns
      kubernetes::delete_if_exists "" clusterrolebinding/system:coredns
      kubernetes::delete_if_exists kube-system serviceaccount/coredns
      kubernetes::delete_if_exists kube-system configmap/coredns
      return 0
    fi

    echo "Waiting until all CoreDNS Pods are terminated..."
    sleep 1
  done

  if [[ $i -ge 120 ]] ; then
    >&2 echo "Timeout waiting until all CoreDNS Pods are terminated"
    return 1
  fi
}

hook::run "$@"
