#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 10
EOF
}

function __main__() {
  kubernetes::delete_if_exists::non_cascading kube-system deployment/coredns
  kubernetes::delete_if_exists kube-system configmap/coredns
  kubernetes::delete_if_exists kube-system service/kube-dns
}

hook::run "$@"
