#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 5
EOF
}

function __main__() {
  if values::has --config kubeDns.clusterDomain; then
    values::unset --config kubeDns.clusterDomain
  fi
}

hook::run "$@"
