{{- if .Values.controlPlaneManager.apiserver.publishAPI.ingress.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: d8-publish-api-master-ca
  namespace: kube-system
data:
  publishedAPIKubeconfigGeneratorMasterCA: |
    {{ .Values.controlPlaneManager.internal.authn.publishedAPIKubeconfigGeneratorMasterCA | nindent 4 }}
{{- end }}