{{- if .Values.controlPlaneManager.apiserver.publishAPI.ingress.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: d8-publish-api-config
  namespace: kube-system
data:
  publishedAPIKubeconfigGeneratorMasterCA: {{ .Values.controlPlaneManager.internal.authn.publishedAPIKubeconfigGeneratorMasterCA | b64enc }}
  addKubeconfigGeneratorEntry: {{ .Values.controlPlaneManager.apiserver.publishAPI.ingress.addKubeconfigGeneratorEntry | toString | b64enc }}
  httpsMode: {{ .Values.controlPlaneManager.apiserver.publishAPI.ingress.https.mode | b64enc }}
  {{- if .Values.controlPlaneManager.apiserver.publishAPI.ingress.ingressClass }}
  ingressClass: {{ .Values.controlPlaneManager.apiserver.publishAPI.ingress.ingressClass | b64enc }}
  {{- end }}
  {{- if .Values.controlPlaneManager.apiserver.publishAPI.ingress.whitelistSourceRanges }}
  whitelistSourceRanges: {{ .Values.controlPlaneManager.apiserver.publishAPI.ingress.whitelistSourceRanges | toString |  b64enc }}
  {{- end }}
{{- end }}