#!/bin/bash
# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -Eeo pipefail
packages_to_install=""
package_docker_ce="docker-ce"
package_file_docker_ce="${package_docker_ce}.x86_64.rpm"
rpm_name_docker_ce="$(rpm -qip ${package_file_docker_ce} 2>/dev/null | grep Name | awk '{print $3}')"
rpm_version_docker_ce="$(rpm -qip ${package_file_docker_ce} 2>/dev/null | grep Version | awk '{print $3}')"

if ! rpm --quiet -q "${rpm_name_docker_ce}-${rpm_version_docker_ce}"; then
  packages_to_install="${packages_to_install} ${package_file_docker_ce}"
else
  echo "RPM ${package_file_docker_ce} already installed."
fi

package_docker_ce_cli="docker-ce-cli"
package_file_docker_ce_cli="${package_docker_ce_cli}.x86_64.rpm"
rpm_name_docker_ce_cli="$(rpm -qip ${package_file_docker_ce_cli} 2>/dev/null | grep Name | awk '{print $3}')"
rpm_version_docker_ce_cli="$(rpm -qip ${package_file_docker_ce_cli} 2>/dev/null | grep Version | awk '{print $3}')"

if ! rpm --quiet -q "${rpm_name_docker_ce_cli}-${rpm_version_docker_ce_cli}"; then
  packages_to_install="${packages_to_install} ${package_file_docker_ce_cli}"
else
  echo "RPM ${package_file_docker_ce_cli} already installed."
fi

if [[ -n "${packages_to_install}" ]]; then
  rpm -U --oldpackage ${packages_to_install}
fi
yum versionlock add ${package_docker_ce} ${package_docker_ce_cli}
