#!/bin/bash

# Copyright 2023 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /deckhouse/shell_lib.sh

function __main__() {
  if values::array_has global.enabledModules "virtualization"; then
    enabled=true
  else
    enabled=false
  fi
  if [ "$enabled" = "false" ]; then
    # workaround: allow explicit enabling of the module
    case "$(kubectl get moduleconfig containerized-data-importer -o jsonpath={.spec.enabled} 2>/dev/null)" in
      # match all cases of true|y|yes|1
      [Tt][Rr][Uu][Ee]|[Yy]|[Yy][Ee][Ss]|1)
        enabled=true
        ;;
    esac
  fi
  echo "$enabled" > $MODULE_ENABLED_RESULT
}

enabled::run "$@"
