#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: d8_deployment
      apiVersion: apps/v1
      kind: Deployment
      watchEvent: ["Added", "Modified"]
      namespace:
        nameSelector:
          matchNames: ["d8-system"]
      nameSelector:
        matchNames: ["deckhouse"]
      allowFailure: true
      jqFilter: '.spec.template.spec  .containers[0].image | split(":")[1]'
EOF
}

function __on_kubernetes::d8_deployment() {

  if context::has objects.0; then
    if [[ "$(values::get deckhouseWeb.deckhouseTag)" != "$(context::get objects.0.filterResult)" ]] ; then
      values::set deckhouseWeb.deckhouseTag "$(context::get objects.0.filterResult)"
    fi
  fi

}

hook::run $@
