#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  echo '
{
  "afterHelm": 10,
  "onKubernetesEvent": [
    {
      "kind": "secret",
      "event": [
        "update"
      ],
      "namespaceSelector": {
        "matchNames": [
          "antiopa"
        ]
      },
      "jqFilter": "[.data.\"tls.crt\", .data.\"tls.key\"]"
    }
  ]
}'
}

function __main__() {
  secret_name=$(values::get_first_defined dashboard.certificateForIngress.customCertificateSecretName global.certificateForIngress.customCertificateSecretName)
  if [ "${secret_name}" != "false" ] && [ ! -z "${secret_name}" ] ; then
    if kubectl -n antiopa get secret ${secret_name} ; then
      kubectl -n antiopa get secret ${secret_name} -o json | \
        jq -r ".metadata.namespace=\"kube-system\" | .metadata.name=\"ingress-tls\" |
          .metadata |= with_entries(select([.key] | inside([\"name\", \"namespace\", \"labels\"])))" \
        | kubectl::replace_or_create
    else
      >&2 echo "You use the certificateForIngress.customCertificateSecretName, but there is no ${secret_name} secret in antiopa namespace"
      exit 1
    fi
  fi
}

hook::run $@
