#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p afterHelm=10
}

function __main__() {
  if kubectl -n kube-system get certificate dashboard > /dev/null 2>&1 ; then
    certificate_issuer_name=$(kubectl -n kube-system get certificate dashboard -o json | jq -r '.spec.issuerRef.name')
    secret_issuer_name=$(kubectl -n kube-system get secret ingress-tls -o json | jq -r '.metadata.annotations."certmanager.k8s.io/issuer-name"')
    if [ "${secret_issuer_name}" != "${certificate_issuer_name}" ] ; then
      kubectl -n kube-system delete secret ingress-tls > /dev/null 2>&1
    fi
  fi
}

hook::run $@
