#!/bin/bash

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  jo -p beforeHelm=20
}

function __main__() {
  if ! values::has dashboard.auth.externalAuthentication ; then
    if ! values::has dashboard.auth.password ; then
      values::set --config dashboard.auth.password $(values::generate_password)
    fi
  else
    values::unset --config dashboard.auth.password
  fi
}

hook::run $@
