#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p beforeHelm=20
}

function __main__() {
  if values::has dashboard.gitlabBaseUrl ; then
    if ! values::has dashboard.oauth2ProxyCookieSecret ; then
      values::set --config dashboard.oauth2ProxyCookieSecret $(values::generate_password)
    fi
  else
    values::unset --config dashboard.oauth2ProxyCookieSecret
  fi
}

hook::run $@
