#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p beforeHelm=20
}

function __main__() {
  if ! values::get dashboard.externalAuthentication ; then
    if ! values::has dashboard.password ; then
      values::set --config dashboard.password $(values::generate_password)
    fi
  else
    values::unset --config dashboard.password
  fi
}

hook::run $@
