#!/bin/bash

source /deckhouse/shell_lib.sh


### Миграция 2020-01-20
# Удалить после выката версии на все инстансы

function __config__() {
  jo -p onStartup=10 configVersion=v1
}

function __main__() {
  if ! values::has --config dashboard.externalAuthentication && ! values::has --config dashboard.password && ! values::has --config dashboard.allowScale ; then
    return 0
  fi

  values::set --config dashboard.auth {}

  if values::has --config dashboard.externalAuthentication ; then
    values::set --config dashboard.auth.externalAuthentication "$(values::get --config dashboard.externalAuthentication)"
    values::unset --config dashboard.externalAuthentication
  fi

  if values::has --config dashboard.password ; then
    values::set --config dashboard.auth.password "$(values::get --config dashboard.password)"
    values::unset --config dashboard.password
  fi

  if values::has --config dashboard.allowScale ; then
    values::set --config dashboard.auth.allowScale $(values::get --config dashboard.allowScale)
    values::unset --config dashboard.allowScale
  fi
}

hook::run $@
