#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p beforeHelm=10
}

### Миграция 2018-04-25: https://github.com/deckhouse/deckhouse/merge_requests/211
function __main__() {
  if kubectl get ns kube-dashboard > /dev/null 2> /dev/null && [[ "$(kubectl get ns kube-dashboard -o json | jq .metadata.labels.heritage -r)" != "antiopa" ]] ; then
    if ! values::has dashboard.gitlabBaseUrl ; then
      if gitlab_base_url=$(kubectl -n kube-dashboard get deploy/oauth2-proxy -o json | jq '.spec.template.spec.containers[0].args' | grep 'login-url' | sed -e 's/.*=//;s#/oauth/authorize.*##') && [[ -n $gitlab_base_url ]] ; then
        oauth2_proxy_client_id=$(kubectl -n kube-dashboard get deploy/oauth2-proxy -o json | jq '.spec.template.spec.containers[0].env[]  | select(.name=="OAUTH2_PROXY_CLIENT_ID") | .value' -r)
        oauth2_proxy_client_secret=$(kubectl -n kube-dashboard get deploy/oauth2-proxy -o json | jq '.spec.template.spec.containers[0].env[]  | select(.name=="OAUTH2_PROXY_CLIENT_SECRET") | .value' -r)

        values::set --config dashboard.gitlabBaseUrl $gitlab_base_url
        values::set --config dashboard.oauth2ProxyClientId $oauth2_proxy_client_id
        values::set --config dashboard.oauth2ProxyClientSecret $oauth2_proxy_client_secret
      fi
    fi

    # Удаляем старые данные
    for resource in clusterrolebinding/kubernetes-dashboard clusterrole/dashboard ns/kube-dashboard ; do
      if kubectl get $resource > /dev/null 2> /dev/null ; then
        kubectl delete $resource
      fi
    done

    # Ждем терминацию ns
    for i in $(seq 1 120); do
      if ! kubectl get ns kube-dashboard > /dev/null 2> /dev/null ; then
        return 0
      fi

      echo "Waiting for the kube-dashboard namespace termination"
      sleep 10
    done

    return 1
  fi
}

hook::run $@
