apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    heritage: deckhouse
    module: cilium-hubble
    rbac.deckhouse.io/aggregate-to-networking-as: manager
    rbac.deckhouse.io/kind: capability
    rbac.deckhouse.io/scope: system
    rbac.deckhouse.io/namespace: d8-cni-cilium
  name: d8:system-capability:cilium-hubble:edit
  annotations:
    en.meta.deckhouse.io/title: "Module cilium-hubble: edit configuration"
    ru.meta.deckhouse.io/title: "Модуль cilium-hubble: управление конфигурацией"
    en.meta.deckhouse.io/description: "Manage the cilium-hubble module configuration."
    ru.meta.deckhouse.io/description: "Управление конфигурацией модуля cilium-hubble."
rules:
- apiGroups:
  - deckhouse.io
  resourceNames:
  - cilium-hubble
  resources:
  - moduleconfigs
  verbs:
  - create
  - update
  - patch
  - delete
