#!/bin/bash

# Copyright 2021 Flant JSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE

# current revision of vsphere CSI driver isn't supported, so this hook hack around a bug in it
source /deckhouse/shell_lib.sh

function __config__() {
  execute_hook_on_synchronization="false"
  if [ -n "${D8_IS_TESTS_ENVIRONMENT-}" ]; then
    # The current test suite does not support snapshots while running
    # `beforeHelm` with `executeHookOnSynchronization: false`.
    execute_hook_on_synchronization="true"
  fi
  cat << EOF
    configVersion: v1
    beforeHelm: 10
    kubernetes:
    - name: finalizers
      group: main
      queue: /modules/$(module::name::kebab_case)
      executeHookOnSynchronization: ${execute_hook_on_synchronization}
      keepFullObjectsInMemory: false
      apiVersion: storage.k8s.io/v1
      kind: VolumeAttachment
      jqFilter: |
        {
          "name": .metadata.name,
          "message": (.status.detachError.message // null)
        }
EOF
}

function __main__() {
  for volumeattachment in $(context::jq -r '.snapshots.finalizers[].filterResult | select(.message=="rpc error: code = Unknown desc = No VM found").name'); do
    kubernetes::patch_jq "" "VolumeAttachment/$volumeattachment" "del(.metadata.finalizers)"
  done
}

hook::run "$@"
