@startuml
!theme bluegray
skinparam DefaultFontSize 16
skinparam ArrowFontStyle italic
skinparam DefaultTextAlignment center
skinparam backgroundColor transparent
skinparam Shadowing false

[Integrity control] --> [Integrity control\n when starting containers]
[Integrity control] --> [Integrity control\n of running containers]
[Integrity control\n of running containers] <-- [Using the DM-Verity\n control mechanism]
[Integrity control\n when starting containers] <-- [Using the DM-Verity\n control mechanism]

[Integrity control\n when starting containers] <-- [Signature verification\n when loading the image]
[Integrity control\n when starting containers] <-- [Using EROFS-snapshotter,\n RW upperdir rejection]
@enduml