@startuml
!theme bluegray
skinparam DefaultFontSize 16
skinparam ArrowFontStyle italic
skinparam DefaultTextAlignment center
skinparam backgroundColor transparent
skinparam Shadowing false
skinparam componentStyle rectangle

component "<color:navy>Using the DM-Verity\n <color:navy>control mechanism" as DMV #LightBlue
component "<color:navy>Signature verification\n <color:navy>when loading the image" as CS #LightBlue
component "<color:navy>Using EROFS-snapshotter,\n <color:navy>RW upperdir rejection" as EROFS #LightBlue

[Integrity control] --> [Integrity control\n when starting containers]
[Integrity control] --> [Integrity control\n of running containers]
[Integrity control\n of running containers] <.. DMV
[Integrity control\n when starting containers] <.. DMV

[Integrity control\n when starting containers] <.. CS
[Integrity control\n when starting containers] <.. EROFS
@enduml