@startuml
!theme bluegray
skinparam DefaultFontSize 16
skinparam ArrowFontStyle italic
skinparam DefaultTextAlignment center
skinparam backgroundColor transparent
skinparam Shadowing false

[Контроль целостности] --> [Контроль целостности\n при запуске контейнеров]
[Контроль целостности] --> [Контроль целостности\n работающих контейнеров]
[Контроль целостности\n работающих контейнеров] <-- [Встроенные правила]
[Контроль целостности\n работающих контейнеров] <-- [Пользовательские правила]
@enduml