{
 "title": "Control Plane Status",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "API Servers UP",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-apiserver\"} == 1) / sum(up{job=\"kube-apiserver\"})) * 100"
    }
   ]
  },
  {
   "title": "Controller Mangers UP",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-controller-manager\"} == 1) / sum(up{job=\"kube-controller-manager\"})) * 100"
    }
   ]
  },
  {
   "title": "Schedulers UP",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-scheduler\"} == 1) / sum(up{job=\"kube-scheduler\"})) * 100"
    }
   ]
  },
  {
   "title": "API Server Request Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "topk(1, (sum by(node) (rate(apiserver_request_count{code!~\"2..\"}[$__range])) / sum by(node) (rate(apiserver_request_count[$__range]))) * 100)"
    }
   ]
  },
  {
   "title": "API Server Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(verb) (rate(apiserver_latency_seconds:quantile[$__interval_rv]) >= 0)"
    }
   ]
  },
  {
   "title": "End to end scheduling latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cluster:scheduler_e2e_scheduling_latency_seconds:quantile"
    }
   ]
  },
  {
   "title": "API Server Request Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(node) (rate(apiserver_request_count{code!~\"2..\"}[$__interval_rv]))",
     "legendFormat": "Error Rate"
    },
    {
     "expr": "sum by(node) (rate(apiserver_request_count[$__interval_rv]))",
     "legendFormat": "Request Rate"
    }
   ]
  }
 ]
}