#!/bin/bash

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  common_hooks::certificates::order_certificate::config
}

function __main__() {
  common_hooks::certificates::order_certificate::main "kube-system" "vpa-prometheus-api-client-tls" "kube-system:vpa:prometheus-api-client" "internal.prometheusAPIClientTLS" "prometheus:auth"
}

hook::run "$@"
