#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  common_hooks::certificates::order_certificate::config
}

function __main__() {
  common_hooks::certificates::order_certificate::main "kube-system" "vpa-prometheus-api-client-tls" "kube-system:vpa:prometheus-api-client" "internal.prometheusAPIClientTLS"
}

hook::run "$@"
