#!/bin/bash

### Миграция 2020-04-22
# Этот хук скейлит vpa-recommender в 1 после обновления

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    afterHelm: 10
EOF
}

function __main__() {
  if kubectl -n kube-system get deploy vpa-recommender >/dev/null 2>/dev/null ; then
    kubectl -n kube-system scale deploy vpa-recommender --replicas=1
  fi
}

hook::run $@
