{
 "title": "Cilium Nodes Connectivity Status&Latency",
 "tags": [ "nodes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "source_node",
    "label": "Source",
    "query": "label_values(cilium_node_connectivity_latency_seconds{d8_source=\"dkp\"}, source_node_name)"
   },
   {
    "name": "destination_node",
    "label": "Destination",
    "query": "label_values(cilium_node_connectivity_latency_seconds{d8_source=\"dkp\"}, target_node_name)"
   },
   {
    "name": "protocol",
    "label": "Protocol",
    "query": "label_values(cilium_node_connectivity_latency_seconds{d8_source=\"dkp\"}, protocol)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "From all nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node Connectivity Status Matrix",
   "type": "esnet-matrix-panel",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(cilium_node_connectivity_status{d8_source=\"dkp\", type=\"node\",source_node_name=~\"${source_node}\",target_node_name=~\"${destination_node}\"}[$__range]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint Connectivity Status Matrix",
   "type": "esnet-matrix-panel",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(cilium_node_connectivity_status{d8_source=\"dkp\", type=\"endpoint\",source_node_name=~\"${source_node}\",target_node_name=~\"${destination_node}\"}[$__range]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "From $source_node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "source_node",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Node ICMP Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (target_node_name) (cilium_node_connectivity_latency_seconds{d8_source=\"dkp\", source_node_name=~\"$source_node\", target_node_name=~\"$destination_node\", type=\"node\", protocol=\"icmp\"})",
       "legendFormat": "{{target_node_name}}"
      }
     ]
    },
    {
     "title": "Node HTTP Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (target_node_name) (cilium_node_connectivity_latency_seconds{d8_source=\"dkp\", source_node_name=~\"$source_node\", target_node_name=~\"$destination_node\", type=\"node\", protocol=\"http\"})",
       "legendFormat": "{{target_node_name}}"
      }
     ]
    },
    {
     "title": "Endpoint ICMP Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (target_node_name) (cilium_node_connectivity_latency_seconds{d8_source=\"dkp\", source_node_name=~\"$source_node\", target_node_name=~\"$destination_node\", type=\"endpoint\", protocol=\"icmp\"})",
       "legendFormat": "{{target_node_name}}"
      }
     ]
    },
    {
     "title": "Endpoint HTTP Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (target_node_name) (cilium_node_connectivity_latency_seconds{d8_source=\"dkp\", source_node_name=~\"$source_node\", target_node_name=~\"$destination_node\", type=\"endpoint\", protocol=\"http\"})",
       "legendFormat": "{{target_node_name}}"
      }
     ]
    }
   ]
  }
 ]
}