{
 "title": "GPU Nodes",
 "tags": [ "GPU" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(DCGM_FI_DEV_POWER_USAGE{d8_source=\"dkp\"},Hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "table",
   "description": "Сводная таблица утилизации GPU по устройствам\n\nРесурсы GPU запрашиваются использую PodSpec K8s для ресурса типа `nvidia.com/gpu`",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_GPU_UTIL{d8_source=\"dkp\"})) by (Hostname) / count(sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_GPU_UTIL{d8_source=\"dkp\"})) by(Hostname, device)) by(Hostname)) or (sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_SM_ACTIVE{d8_source=\"dkp\"}) * 100) by(Hostname) / count(sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_SM_ACTIVE{d8_source=\"dkp\"})) by(Hostname, gpu)) by(Hostname)) or (sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_GR_ENGINE_ACTIVE{d8_source=\"dkp\"}) * 100) by(Hostname) / count(sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_GR_ENGINE_ACTIVE{d8_source=\"dkp\"})) by(Hostname, gpu)) by(Hostname))",
     "legendFormat": "Compute Utilization"
    },
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_SM_CLOCK{d8_source=\"dkp\"}) * 1000000) by (Hostname)",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_MEM_CLOCK{d8_source=\"dkp\"}) * 1000000) by (Hostname)",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "100 * sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\"})) by (Hostname) / clamp_min(sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\"})) by (Hostname) + sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_FB_FREE{d8_source=\"dkp\"})) by (Hostname), 1)",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_PCIE_TX_BYTES{d8_source=\"dkp\"})) by (Hostname)",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_PCIE_RX_BYTES{d8_source=\"dkp\"})) by (Hostname)",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "sum(max(DCGM_FI_DEV_POWER_USAGE{d8_source=\"dkp\"}) by(Hostname, gpu)) by (Hostname)",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "description": "Потребляемая мощность вычислительных едениц",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(max(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_POWER_USAGE{d8_source=\"dkp\", Hostname=~\"$node\"})) by(Hostname, gpu)) by(Hostname)",
     "legendFormat": "{{ Hostname }}"
    }
   ]
  },
  {
   "title": "Compute Utilization",
   "type": "timeseries",
   "description": "GPU compute utilization (%).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_GPU_UTIL{d8_source=\"dkp\", Hostname=~\"$node\"})) by(Hostname) / count(sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_GPU_UTIL{d8_source=\"dkp\", Hostname=~\"$node\"})) by(Hostname, device)) by(Hostname)) or (sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_SM_ACTIVE{d8_source=\"dkp\", Hostname=~\"$node\"}) * 100) by(Hostname) / count(sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_SM_ACTIVE{d8_source=\"dkp\", Hostname=~\"$node\"})) by(Hostname, gpu)) by(Hostname)) or (sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_GR_ENGINE_ACTIVE{d8_source=\"dkp\", Hostname=~\"$node\"}) * 100) by(Hostname) / count(sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_GR_ENGINE_ACTIVE{d8_source=\"dkp\", Hostname=~\"$node\"})) by(Hostname, gpu)) by(Hostname))",
     "legendFormat": "Compute Utilization"
    }
   ]
  },
  {
   "title": "GPU Tensor Core Utilization",
   "type": "timeseries",
   "description": "Утилизация тензорных ядер использующих HMMA*, основанная на продолжительности циклов их работы\n\n*Half matrix multiplication and accumulation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{d8_source=\"dkp\", Hostname=~\"$node\"})) by(Hostname) / count(sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{d8_source=\"dkp\", Hostname=~\"$node\"}))by(Hostname, gpu)) by(Hostname)",
     "legendFormat": "{{ Hostname }}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Memory Used",
   "type": "timeseries",
   "description": "Потребление кадрового буффера",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", Hostname=~\"$node\"})) by(Hostname)",
     "legendFormat": "{{ Hostname }}"
    },
    {
     "expr": "max by (Hostname, gpu, GPU_I_PROFILE, GPU_I_ID) (max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", Hostname=~\"$node\", GPU_I_PROFILE=~\".+\"}))",
     "legendFormat": "{{Hostname}} - GPU {{gpu}} {{GPU_I_PROFILE}} (ID {{GPU_I_ID}})"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", Hostname=~\"$node\"})) by(Hostname) / clamp_min(sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", Hostname=~\"$node\"})) by(Hostname) + sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_FB_FREE{d8_source=\"dkp\", Hostname=~\"$node\"})) by(Hostname), 1)",
     "legendFormat": "{{Hostname}}"
    },
    {
     "expr": "100 * max by (Hostname, gpu, GPU_I_PROFILE, GPU_I_ID) (max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", Hostname=~\"$node\", GPU_I_PROFILE=~\".+\"})) / clamp_min(max by (Hostname, gpu, GPU_I_PROFILE, GPU_I_ID) (max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", Hostname=~\"$node\", GPU_I_PROFILE=~\".+\"})) + max by (Hostname, gpu, GPU_I_PROFILE, GPU_I_ID) (max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_FB_FREE{d8_source=\"dkp\", Hostname=~\"$node\", GPU_I_PROFILE=~\".+\"})), 1)",
     "legendFormat": "{{Hostname}} - GPU {{gpu}} {{GPU_I_PROFILE}} (ID {{GPU_I_ID}})"
    }
   ]
  },
  {
   "title": "GPU Memory Bandwidth Utilization",
   "type": "timeseries",
   "description": "Утилизация чипов памяти",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_DRAM_ACTIVE{d8_source=\"dkp\", Hostname=~\"$node\"})) by(Hostname)",
     "legendFormat": "{{ Hostname }}"
    }
   ]
  },
  {
   "title": "GPU Graphics Engine Utilization",
   "type": "timeseries",
   "description": "Утилизация графического движка, основанная на продолжительности его работы",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_GR_ENGINE_ACTIVE{d8_source=\"dkp\", Hostname=~\"$node\"})) by(Hostname)  / count(sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_GR_ENGINE_ACTIVE{d8_source=\"dkp\", Hostname=~\"$node\"})) by(Hostname, gpu)) by(Hostname)",
     "legendFormat": "{{ Hostname }}"
    }
   ]
  },
  {
   "title": "GPU NVLink Activity",
   "type": "timeseries",
   "description": "Скорость передачи данных между графическими процессорами",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (rate(DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL{d8_source=\"dkp\", Hostname=~\"$node\"}[$__rate_interval]))) by(Hostname)",
     "legendFormat": "{{ Hostname }}"
    }
   ]
  },
  {
   "title": "GPU PCIe Receive",
   "type": "timeseries",
   "description": "Скорость передачи данных через линию шины PCIe RX используя NVML*\n\n*NVIDIA Management Library",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_PCIE_RX_BYTES{d8_source=\"dkp\", Hostname=~\"$node\"})) by(Hostname)",
     "legendFormat": "{{ Hostname }}"
    }
   ]
  },
  {
   "title": "GPU PCIe Transmit",
   "type": "timeseries",
   "description": "Скорость передачи данных через линию шины PCIe TX используя NVML*\n\n*NVIDIA Management Library",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_PCIE_TX_BYTES{d8_source=\"dkp\", Hostname=~\"$node\"})) by(Hostname)",
     "legendFormat": "{{ Hostname }}"
    }
   ]
  },
  {
   "title": "GPU SM Clock",
   "type": "timeseries",
   "description": "Тактовая частота потокового мультипроцессора",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_SM_CLOCK{d8_source=\"dkp\", Hostname=~\"$node\"})) by(Hostname) * 1000000",
     "legendFormat": "{{ Hostname }}"
    }
   ]
  },
  {
   "title": "GPU Memory Clock",
   "type": "timeseries",
   "description": "Тактовая частота чипов памяти",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_MEM_CLOCK{d8_source=\"dkp\", Hostname=~\"$node\"})) by(Hostname) * 1000000",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  }
 ]
}