{
 "title": "GPU Overview",
 "description": "This dashboard displays metrics from a DCGM Exporter on a Kubernetes cluster.",
 "tags": [ "GPU" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(DCGM_FI_DEV_POWER_USAGE{d8_source=\"dkp\"},Hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Avgerage Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(max by (Hostname, gpu) (DCGM_FI_DEV_GPU_TEMP{d8_source=\"dkp\", Hostname=~\"$node\"}))",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Power Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(max by (Hostname, gpu) (DCGM_FI_DEV_POWER_USAGE{d8_source=\"dkp\", Hostname=~\"$node\"}))",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Energy Draw Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(max by (Hostname, gpu) (increase(DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION{d8_source=\"dkp\", Hostname=~\"$node\"}[1h]) / 3600000))",
     "legendFormat": "Last 1h"
    },
    {
     "expr": "sum(max by (Hostname, gpu) (increase(DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION{d8_source=\"dkp\", Hostname=~\"$node\"}[24h]) / 3600000))",
     "legendFormat": "Last 24h"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "max by (Hostname, gpu) (DCGM_FI_DEV_POWER_USAGE{d8_source=\"dkp\", Hostname=~\"$node\"})",
     "legendFormat": "{{Hostname}} - GPU {{gpu}} (full)"
    }
   ]
  },
  {
   "title": "GPU Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(max by (Hostname, gpu) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", Hostname=~\"$node\", GPU_I_PROFILE!~\".+\"})) or on(Hostname, gpu) (sum by (Hostname, gpu) (max by (Hostname, gpu, GPU_I_PROFILE, GPU_I_ID) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", Hostname=~\"$node\", GPU_I_PROFILE=~\".+\"})))",
     "legendFormat": "{{Hostname}} - GPU {{gpu}} (full)"
    },
    {
     "expr": "avg by (Hostname, gpu, GPU_I_PROFILE, GPU_I_ID) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", Hostname=~\"$node\", GPU_I_PROFILE=~\".+\"})",
     "legendFormat": "{{Hostname}} - GPU {{gpu}} {{GPU_I_PROFILE}} (ID {{GPU_I_ID}})"
    }
   ]
  },
  {
   "title": "GPU Memory Used Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((max by (Hostname, gpu) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", Hostname=~\"$node\", GPU_I_PROFILE!~\".+\"})) or on(Hostname, gpu) (sum by (Hostname, gpu) (max by (Hostname, gpu, GPU_I_PROFILE, GPU_I_ID) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", Hostname=~\"$node\", GPU_I_PROFILE=~\".+\"})))) / (((max by (Hostname, gpu) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", Hostname=~\"$node\", GPU_I_PROFILE!~\".+\"})) or on(Hostname, gpu) (sum by (Hostname, gpu) (max by (Hostname, gpu, GPU_I_PROFILE, GPU_I_ID) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", Hostname=~\"$node\", GPU_I_PROFILE=~\".+\"})))) + ((max by (Hostname, gpu) (DCGM_FI_DEV_FB_FREE{d8_source=\"dkp\", Hostname=~\"$node\", GPU_I_PROFILE!~\".+\"})) or on(Hostname, gpu) (sum by (Hostname, gpu) (max by (Hostname, gpu, GPU_I_PROFILE, GPU_I_ID) (DCGM_FI_DEV_FB_FREE{d8_source=\"dkp\", Hostname=~\"$node\", GPU_I_PROFILE=~\".+\"})))))",
     "legendFormat": "{{Hostname}} - GPU {{gpu}} (full)"
    },
    {
     "expr": "avg by (Hostname, gpu, GPU_I_PROFILE, GPU_I_ID) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", Hostname=~\"$node\", GPU_I_PROFILE=~\".+\"}) / (avg by (Hostname, gpu, GPU_I_PROFILE, GPU_I_ID) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", Hostname=~\"$node\", GPU_I_PROFILE=~\".+\"}) + avg by (Hostname, gpu, GPU_I_PROFILE, GPU_I_ID) (DCGM_FI_DEV_FB_FREE{d8_source=\"dkp\", Hostname=~\"$node\", GPU_I_PROFILE=~\".+\"}))",
     "legendFormat": "{{Hostname}} - GPU {{gpu}} {{GPU_I_PROFILE}} (ID {{GPU_I_ID}})"
    }
   ]
  },
  {
   "title": "Compute Utilization",
   "type": "timeseries",
   "description": "GPU compute utilization (%).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (Hostname, gpu) (DCGM_FI_DEV_GPU_UTIL{d8_source=\"dkp\", Hostname=~\"$node\"}) or max by (Hostname, gpu) (DCGM_FI_PROF_SM_ACTIVE{d8_source=\"dkp\", Hostname=~\"$node\"}) * 100 or max by (Hostname, gpu) (DCGM_FI_PROF_GR_ENGINE_ACTIVE{d8_source=\"dkp\", Hostname=~\"$node\"}) * 100",
     "legendFormat": "{{Hostname}} - GPU {{gpu}} (full)"
    },
    {
     "expr": "max by (Hostname, gpu, GPU_I_PROFILE, GPU_I_ID) (DCGM_FI_DEV_GPU_UTIL{d8_source=\"dkp\", Hostname=~\"$node\", GPU_I_PROFILE=~\".+\"}) or max by (Hostname, gpu, GPU_I_PROFILE, GPU_I_ID) (DCGM_FI_PROF_SM_ACTIVE{d8_source=\"dkp\", Hostname=~\"$node\", GPU_I_PROFILE=~\".+\"}) * 100 or max by (Hostname, gpu, GPU_I_PROFILE, GPU_I_ID) (DCGM_FI_PROF_GR_ENGINE_ACTIVE{d8_source=\"dkp\", Hostname=~\"$node\", GPU_I_PROFILE=~\".+\"}) * 100",
     "legendFormat": "{{Hostname}} - GPU {{gpu}} {{GPU_I_PROFILE}} (ID {{GPU_I_ID}})"
    }
   ]
  },
  {
   "title": "Tensor Core Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (Hostname, gpu) (DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{d8_source=\"dkp\", Hostname=~\"$node\"})",
     "legendFormat": "{{Hostname}} - GPU {{gpu}} (full)"
    },
    {
     "expr": "max by (Hostname, gpu, GPU_I_PROFILE, GPU_I_ID) (DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{d8_source=\"dkp\", Hostname=~\"$node\", GPU_I_PROFILE=~\".+\"})",
     "legendFormat": "{{Hostname}} - GPU {{gpu}} {{GPU_I_PROFILE}} (ID {{GPU_I_ID}})"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (Hostname, gpu) (DCGM_FI_DEV_GPU_TEMP{d8_source=\"dkp\", Hostname=~\"$node\"})",
     "legendFormat": "{{Hostname}} - GPU {{gpu}} (full)"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "max by (Hostname, gpu) (DCGM_FI_DEV_SM_CLOCK{d8_source=\"dkp\", Hostname=~\"$node\"}) * 1000000",
     "legendFormat": "{{Hostname}} - GPU {{gpu}} (full)"
    },
    {
     "expr": "max by (Hostname, gpu, GPU_I_PROFILE, GPU_I_ID) (DCGM_FI_DEV_SM_CLOCK{d8_source=\"dkp\", Hostname=~\"$node\", GPU_I_PROFILE=~\".+\"}) * 1000000",
     "legendFormat": "{{Hostname}} - GPU {{gpu}} {{GPU_I_PROFILE}} (ID {{GPU_I_ID}})"
    }
   ]
  }
 ]
}