{
 "title": "GPU Node",
 "tags": [ "GPU" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(DCGM_FI_DEV_POWER_USAGE{d8_source=\"dkp\"},Hostname)"
    }
   },
   {
    "name": "gpu",
    "label": "GPU",
    "query": {
     "query": "label_values(DCGM_FI_DEV_POWER_USAGE{d8_source=\"dkp\", Hostname=\"$node\"},gpu)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "table",
   "description": "Сводная таблица утилизации GPU по устройствам\n\nРесурсы GPU запрашиваются использую PodSpec K8s для ресурса типа `nvidia.com/gpu`",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (Hostname, gpu) (avg_over_time(DCGM_FI_DEV_POWER_USAGE{d8_source=\"dkp\", Hostname=\"$node\", gpu=~\"$gpu\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_GPU_UTIL{d8_source=\"dkp\", Hostname=\"$node\", gpu=~\"$gpu\"})) by (Hostname, gpu) or sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_SM_ACTIVE{d8_source=\"dkp\", Hostname=\"$node\", gpu=~\"$gpu\"}) * 100) by (Hostname, gpu) or sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_GR_ENGINE_ACTIVE{d8_source=\"dkp\", Hostname=\"$node\", gpu=~\"$gpu\"}) * 100) by (Hostname, gpu)",
     "legendFormat": "Compute Utilization"
    },
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_SM_CLOCK{d8_source=\"dkp\", Hostname=\"$node\", gpu=~\"$gpu\"}) * 1000000) by (Hostname, gpu)",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_MEM_CLOCK{d8_source=\"dkp\", Hostname=\"$node\", gpu=~\"$gpu\"}) * 1000000) by (Hostname, gpu)",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "100 * sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", Hostname=\"$node\", gpu=~\"$gpu\"})) by (Hostname, gpu) / clamp_min(sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", Hostname=\"$node\", gpu=~\"$gpu\"})) by (Hostname, gpu) + sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_FB_FREE{d8_source=\"dkp\", Hostname=\"$node\", gpu=~\"$gpu\"})) by (Hostname, gpu), 1)",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_PCIE_TX_BYTES{d8_source=\"dkp\", Hostname=\"$node\", gpu=~\"$gpu\"})) by (Hostname, gpu)",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_PCIE_RX_BYTES{d8_source=\"dkp\", Hostname=\"$node\", gpu=~\"$gpu\"})) by (Hostname, gpu)",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "max(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_GPU_TEMP{d8_source=\"dkp\", Hostname=\"$node\", gpu=~\"$gpu\"})) by(Hostname, gpu)",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "sum(max(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_POWER_USAGE{d8_source=\"dkp\", Hostname=\"$node\", gpu=~\"$gpu\"})) by(Hostname, gpu)) by (Hostname, gpu)",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage: ${node}",
   "type": "timeseries",
   "description": "Потребляемая мощность вычислительных едениц",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(max(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_POWER_USAGE{d8_source=\"dkp\", Hostname=~\"$node\", gpu=~\"$gpu\"})) by(Hostname, gpu)) by(Hostname, gpu)",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Temperature: ${node}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_GPU_TEMP{d8_source=\"dkp\", Hostname=\"$node\"})) by (Hostname, gpu)",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Compute Utilization: ${node}",
   "type": "timeseries",
   "description": "GPU compute utilization (%).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_GPU_UTIL{d8_source=\"dkp\", Hostname=~\"$node\", gpu=~\"$gpu\"})) by(Hostname, gpu) or sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_SM_ACTIVE{d8_source=\"dkp\", Hostname=~\"$node\", gpu=~\"$gpu\"}) * 100) by(Hostname, gpu) or sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_GR_ENGINE_ACTIVE{d8_source=\"dkp\", Hostname=~\"$node\", gpu=~\"$gpu\"}) * 100) by(Hostname, gpu)",
     "legendFormat": "Compute Utilization"
    }
   ]
  },
  {
   "title": "GPU Tensor Core Utilization: ${node}",
   "type": "timeseries",
   "description": "Утилизация тензорных ядер использующих HMMA*, основанная на продолжительности циклов их работы\n\n*Half matrix multiplication and accumulation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{d8_source=\"dkp\", Hostname=~\"$node\", gpu=~\"$gpu\"})) by(Hostname, gpu) / count(sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{d8_source=\"dkp\", Hostname=~\"$node\", gpu=~\"$gpu\"}))by(Hostname, gpu)) by(Hostname, gpu)",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization: ${node}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", Hostname=~\"$node\", gpu=~\"$gpu\"})) by(Hostname, gpu) / clamp_min(sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", Hostname=~\"$node\", gpu=~\"$gpu\"})) by(Hostname, gpu) + sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_FB_FREE{d8_source=\"dkp\", Hostname=~\"$node\", gpu=~\"$gpu\"})) by(Hostname, gpu), 1)",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "100 * max by (Hostname, gpu, GPU_I_PROFILE, GPU_I_ID) (max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", Hostname=~\"$node\", gpu=~\"$gpu\", GPU_I_PROFILE=~\".+\"})) / clamp_min(max by (Hostname, gpu, GPU_I_PROFILE, GPU_I_ID) (max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", Hostname=~\"$node\", gpu=~\"$gpu\", GPU_I_PROFILE=~\".+\"})) + max by (Hostname, gpu, GPU_I_PROFILE, GPU_I_ID) (max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_FB_FREE{d8_source=\"dkp\", Hostname=~\"$node\", gpu=~\"$gpu\", GPU_I_PROFILE=~\".+\"})), 1)",
     "legendFormat": "GPU {{gpu}} {{GPU_I_PROFILE}} (ID {{GPU_I_ID}})"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Memory Used: ${node}",
   "type": "timeseries",
   "description": "Потребление кадрового буффера",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", Hostname=~\"$node\", gpu=~\"$gpu\"})) by(Hostname, gpu)",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "max by (Hostname, gpu, GPU_I_PROFILE, GPU_I_ID) (max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", Hostname=~\"$node\", gpu=~\"$gpu\", GPU_I_PROFILE=~\".+\"}))",
     "legendFormat": "GPU {{gpu}} {{GPU_I_PROFILE}} (ID {{GPU_I_ID}})"
    }
   ]
  },
  {
   "title": "GPU Graphics Engine Utilization: ${node}",
   "type": "timeseries",
   "description": "Утилизация графического движка, основанная на продолжительности его работы",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_GR_ENGINE_ACTIVE{d8_source=\"dkp\", Hostname=~\"$node\", gpu=~\"$gpu\"})) by(Hostname, gpu)  / count(sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_GR_ENGINE_ACTIVE{d8_source=\"dkp\", Hostname=~\"$node\", gpu=~\"$gpu\"})) by(Hostname, gpu)) by(Hostname, gpu)",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Bandwidth Utilization: ${node}",
   "type": "timeseries",
   "description": "Утилизация чипов памяти",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_DRAM_ACTIVE{d8_source=\"dkp\", Hostname=~\"$node\", gpu=~\"$gpu\"})) by(Hostname, gpu)",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU NVLink Activity: ${node}",
   "type": "timeseries",
   "description": "Скорость передачи данных между графическими процессорами",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (rate(DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL{d8_source=\"dkp\", Hostname=~\"$node\", gpu=~\"$gpu\"}[$__rate_interval]))) by(Hostname, gpu)",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU PCIe Receive: ${node}",
   "type": "timeseries",
   "description": "Скорость передачи данных через линию шины PCIe RX используя NVML*\n\n*NVIDIA Management Library",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_PCIE_RX_BYTES{d8_source=\"dkp\", Hostname=~\"$node\", gpu=~\"$gpu\"})) by(Hostname, gpu)",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU PCIe Transmit: ${node}",
   "type": "timeseries",
   "description": "Скорость передачи данных через линию шины PCIe TX используя NVML*\n\n*NVIDIA Management Library",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_PROF_PCIE_TX_BYTES{d8_source=\"dkp\", Hostname=~\"$node\", gpu=~\"$gpu\"})) by(Hostname, gpu)",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU SM Clock: ${node}",
   "type": "timeseries",
   "description": "Тактовая частота потокового мультипроцессора",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_SM_CLOCK{d8_source=\"dkp\", Hostname=~\"$node\", gpu=~\"$gpu\"})) by(Hostname, gpu) * 1000000",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Clock",
   "type": "timeseries",
   "description": "Тактовая частота чипов памяти",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "sum(max without (exported_namespace, exported_pod, exported_container, container) (DCGM_FI_DEV_MEM_CLOCK{d8_source=\"dkp\", Hostname=~\"$node\", gpu=~\"$gpu\"})) by(Hostname, gpu) * 1000000",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  }
 ]
}