{
 "title": "GPU Namespaces",
 "tags": [ "GPU" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "table",
   "description": "Сводная таблица утилизации GPU по подам\n\nРесурсы GPU запрашиваются использую PodSpec K8s для ресурса типа `nvidia.com/gpu`",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(avg(label_replace(DCGM_FI_DEV_GPU_UTIL{d8_source=\"dkp\", exported_namespace!=\"\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (namespace)) or (avg(label_replace(DCGM_FI_PROF_SM_ACTIVE{d8_source=\"dkp\", exported_namespace!=\"\"} * 100, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (namespace)) or (avg(label_replace(DCGM_FI_PROF_GR_ENGINE_ACTIVE{d8_source=\"dkp\", exported_namespace!=\"\"} * 100, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (namespace))",
     "legendFormat": "Compute Utilization"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{d8_source=\"dkp\", namespace!=\"\",resource=~\"nvidia_com_gpu|nvidia_com_mig_.*\"}) by (namespace)",
     "legendFormat": "Requested"
    },
    {
     "expr": "100 * sum(label_replace(DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", exported_namespace!=\"\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (namespace) / clamp_min(sum(label_replace(DCGM_FI_DEV_FB_USED{d8_source=\"dkp\", exported_namespace!=\"\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (namespace) + sum(label_replace(DCGM_FI_DEV_FB_FREE{d8_source=\"dkp\", exported_namespace!=\"\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.+)\")) by (namespace), 1)",
     "legendFormat": "GPU Memory Utilization"
    }
   ]
  },
  {
   "title": "Compute Utilization",
   "type": "timeseries",
   "description": "GPU compute utilization (%).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg(DCGM_FI_DEV_GPU_UTIL{d8_source=\"dkp\", exported_namespace!=\"\", GPU_I_PROFILE=~\".+\"}) by (exported_namespace, gpu, GPU_I_PROFILE, GPU_I_ID)) or (avg(DCGM_FI_PROF_SM_ACTIVE{d8_source=\"dkp\", exported_namespace!=\"\", GPU_I_PROFILE=~\".+\"}) by (exported_namespace, gpu, GPU_I_PROFILE, GPU_I_ID) * 100) or (avg(DCGM_FI_PROF_GR_ENGINE_ACTIVE{d8_source=\"dkp\", exported_namespace!=\"\", GPU_I_PROFILE=~\".+\"}) by (exported_namespace, gpu, GPU_I_PROFILE, GPU_I_ID) * 100)",
     "legendFormat": "{{exported_namespace}} - GPU {{gpu}} {{GPU_I_PROFILE}} (ID {{GPU_I_ID}})"
    },
    {
     "expr": "(avg(DCGM_FI_DEV_GPU_UTIL{d8_source=\"dkp\", exported_namespace!=\"\", GPU_I_PROFILE!~\".+\"}) by (exported_namespace, gpu)) or (avg(DCGM_FI_PROF_SM_ACTIVE{d8_source=\"dkp\", exported_namespace!=\"\", GPU_I_PROFILE!~\".+\"}) by (exported_namespace, gpu) * 100) or (avg(DCGM_FI_PROF_GR_ENGINE_ACTIVE{d8_source=\"dkp\", exported_namespace!=\"\", GPU_I_PROFILE!~\".+\"}) by (exported_namespace, gpu) * 100)",
     "legendFormat": "{{exported_namespace}} - GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{d8_source=\"dkp\",  exported_namespace!=\"\"}) by(exported_namespace)",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  },
  { "title": "PCIe ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "GPU PCIe Receive",
   "type": "timeseries",
   "description": "PCIe throughput (bytes/s).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_PROF_PCIE_RX_BYTES{d8_source=\"dkp\", exported_namespace!=\"\"}) by(exported_namespace)",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  },
  {
   "title": "GPU PCIe Transmit",
   "type": "timeseries",
   "description": "PCIe throughput (bytes/s).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_PROF_PCIE_TX_BYTES{d8_source=\"dkp\", exported_namespace!=\"\"}) by(exported_namespace)",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  },
  { "title": "SM Clock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "GPU SM Clock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_SM_CLOCK{d8_source=\"dkp\", exported_namespace!=\"\"}) by(exported_namespace) * 1000000",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  },
  {
   "title": "GPU Memory Clock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_MEM_CLOCK{d8_source=\"dkp\", exported_namespace!=\"\"}) by(exported_namespace) * 1000000",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Tensor Utilization",
   "type": "timeseries",
   "description": "Tensor Core utilization by namespace (%).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg(DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{d8_source=\"dkp\", exported_namespace!=\"\", GPU_I_PROFILE=~\".+\"}) by (exported_namespace, gpu, GPU_I_PROFILE, GPU_I_ID) * 100)",
     "legendFormat": "{{exported_namespace}} - GPU {{gpu}} {{GPU_I_PROFILE}} (ID {{GPU_I_ID}})"
    },
    {
     "expr": "(avg(DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{d8_source=\"dkp\", exported_namespace!=\"\", GPU_I_PROFILE!~\".+\"}) by (exported_namespace, gpu) * 100)",
     "legendFormat": "{{exported_namespace}} - GPU {{gpu}}"
    }
   ]
  }
 ]
}