{
 "title": "DNS (coredns)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(up{d8_source=\"dkp\", job=\"kube-dns\"}, pod)"
   },
   {
    "name": "rcode",
    "query": "label_values(coredns_dns_responses_total{d8_source=\"dkp\", rcode!=\"NOERROR\"}, rcode)"
   },
   {
    "name": "upstream",
    "query": {
     "query": "label_values(coredns_proxy_request_duration_seconds_sum{d8_source=\"dkp\", proxy_name=\"forward\"},to)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CoreDNS panic count",
   "type": "timeseries",
   "description": "If the graph is non-empty, it means that some CoreDNS requests resulted in panic. You can see a specific error in the container logs.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_panics_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(coredns_panics_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Incoming requests count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(coredns_dns_requests_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Incoming requests duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_duration_seconds_sum{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval])) by (pod) / sum(rate(coredns_dns_requests_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_duration_seconds_bucket{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Forwarded requests count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_proxy_request_duration_seconds_count{d8_source=\"dkp\", proxy_name=\"forward\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(coredns_proxy_request_duration_seconds_count{d8_source=\"dkp\", proxy_name=\"forward\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Forwarded requests duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_proxy_request_duration_seconds_sum{d8_source=\"dkp\", proxy_name=\"forward\", job=\"kube-dns\", pod=~\"()\"}[$__rate_interval])) by (pod)  / sum(rate(coredns_proxy_request_duration_seconds_count{d8_source=\"dkp\", proxy_name=\"forward\", job=\"kube-dns\", pod=~\"()\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Forward duration",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(coredns_proxy_request_duration_seconds_bucket{d8_source=\"dkp\", proxy_name=\"forward\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CoreDNS Forward Healthcheck Failure Count",
   "type": "timeseries",
   "description": "If the graph is non-empty, it means that some CoreDNS requests resulted in panic. You can see a specific error in the container logs.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_proxy_healthcheck_failures_total{d8_source=\"dkp\", proxy_name=\"forward\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(coredns_proxy_healthcheck_failures_total{d8_source=\"dkp\", proxy_name=\"forward\",job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cache hit rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval])) by (pod)\n/\n(\nsum(rate(coredns_cache_hits_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval])) by (pod) +\nsum(rate(coredns_cache_misses_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval])) by (pod) \n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cache size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(max_over_time(coredns_cache_entries{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "$rcode",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 38 },
   "repeat": "rcode",
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\", rcode=~\"$rcode\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(coredns_dns_responses_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\", rcode=~\"$rcode\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "TCP/UDP requests ratio",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\",proto=\"tcp\"}[$__rate_interval]))\n/\nsum(rate(coredns_dns_requests_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "TCP"
    },
    {
     "expr": "sum(rate(coredns_dns_requests_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\",proto=\"udp\"}[$__rate_interval]))\n/\nsum(rate(coredns_dns_requests_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "UDP"
    }
   ]
  },
  {
   "title": "Pod $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "repeat": "pod",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requests (by qtype)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_requests_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Responses (by rcode)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_responses_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval])) by (rcode)",
       "legendFormat": "{{rcode}}"
      }
     ]
    },
    {
     "title": "Forwarded requests count (by upstream)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_proxy_request_duration_seconds_count{d8_source=\"dkp\", proxy_name=\"forward\",job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval])) by (to)",
       "legendFormat": "{{to}}"
      },
      {
       "expr": "sum(rate(coredns_proxy_request_duration_seconds_count{d8_source=\"dkp\", proxy_name=\"forward\",job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Forwarded requests count (by rcode)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_proxy_request_duration_seconds_count{d8_source=\"dkp\", proxy_name=\"forward\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval])) by (rcode)",
       "legendFormat": "{{rcode}}"
      },
      {
       "expr": "sum(rate(coredns_proxy_request_duration_seconds_count{d8_source=\"dkp\", proxy_name=\"forward\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "CoreDNS Forward Healthcheck Failure Count",
     "type": "timeseries",
     "description": "If the graph is non-empty, it means that some CoreDNS requests resulted in panic. You can see a specific error in the container logs.",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_proxy_healthcheck_failures_total{d8_source=\"dkp\", proxy_name=\"forward\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval])) by (upstream)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(rate(coredns_proxy_healthcheck_failures_total{d8_source=\"dkp\", proxy_name=\"forward\",job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "TCP/UDP requests ratio",
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_requests_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\",proto=\"tcp\"}[$__rate_interval]))\n/\nsum(rate(coredns_dns_requests_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "TCP"
      },
      {
       "expr": "sum(rate(coredns_dns_requests_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\",proto=\"udp\"}[$__rate_interval]))\n/\nsum(rate(coredns_dns_requests_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "UDP"
      }
     ]
    },
    {
     "title": "Cache hit rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_cache_hits_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval]))\n/\n(\nsum(rate(coredns_cache_hits_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval])) +\nsum(rate(coredns_cache_misses_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval]))\n)"
      }
     ]
    },
    {
     "title": "Cache size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(max_over_time(coredns_cache_entries{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(max_over_time(coredns_cache_entries{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Requests (by zone)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_requests_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval])) by (zone)",
       "legendFormat": "{{zone}}"
      },
      {
       "expr": "sum(rate(coredns_dns_requests_total{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Request duration",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_request_duration_seconds_bucket{d8_source=\"dkp\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Forward duration",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "sum(rate(coredns_proxy_request_duration_seconds_bucket{d8_source=\"dkp\", proxy_name=\"forward\", job=\"kube-dns\", pod=~\"$pod\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}