positive:
  configValues:
    # empty configuration is valid
    - {}

    # empty storage class is valid
    - "storageClass": {}

    # only exclude
    - storageClass:
        exclude: ["disk-type", "ssd-.*"]

    # only default
    - storageClass:
        default: "ssd"

    # only provision
    - storageClass:
        provision:
        - name: "network-ssd-64k"
          type: "network-ssd"
          blockSize: "64Ki"
        - name: "network-hdd"
          type: "network-hdd"

    # all in
    - storageClass:
        default: "ssd"
        exclude: ["disk-type", "ssd-.*"]
        provision:
        - name: "network-ssd-64k"
          type: "network-ssd"
          blockSize: "64Ki"
negative:
  configValues:
    - storageClass:
        exclude: "must be array"
    - storageClass:
        exclude: {"key": "must be array"}
    - storageClass:
        default: ["must be string"]
    - storageClass:
        default: {"key": "must be string"}
    - storageClass:
        provision:
        - name: "no-type-provided"
    - storageClass:
        provision:
        - name: "unknown-disk-type"
          type: "network-ssd-unknown"
    - storageClass:
        provision:
        - name: "unsupported-block-size"
          type: "network-ssd"
          blockSize: "256Ki"
    - storageClass:
        provision:
        - name: "unknown-field"
          type: "network-ssd"
          iops: "6000"
