#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  legacy::common_hooks::https::copy_custom_certificate::config "d8-system"
}

function __main__() {
  legacy::common_hooks::https::copy_custom_certificate::main "d8-system" "ingress-tls"
}

hook::run "$@"
