/*
Copyright 2021 Flant JSC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"text/template"

	audit "k8s.io/apiserver/pkg/apis/audit/v1"
	yamlv3 "gopkg.in/yaml.v3"

	cpmhooks "github.com/deckhouse/deckhouse/modules/040-control-plane-manager/hooks"
)

var variablesTemplate = `// Code generated by "tools/audit_policy.go" DO NOT EDIT.
package hooks

var auditPolicyBasicNamespaces = []string{
{{- range $value := .Namespace }}
	"{{ $value }}",
{{- end }}
}
var auditPolicyBasicServiceAccounts = []string{
{{- range $value := .ServiceAccount }}
	"{{ $value }}",
{{- end }}
}
`

const (
	autogenBlockStart = "<!-- BEGIN AUTOGENERATED: KUBERNETES API AUDIT POLICY -->"
	autogenBlockEnd   = "<!-- END AUTOGENERATED: KUBERNETES API AUDIT POLICY -->"
)

func main() {
	workDir := cwd()

	var (
		outputGo        string
		outputDocEN     string
		outputDocRU     string
		outputDocEN2    string
		outputDocRU2    string
		outputRulesEN   string
		outputRulesRU   string
	)
	flag.StringVar(&outputGo, "output", "", "(deprecated) output file for generated code")
	flag.StringVar(&outputGo, "output-go", "", "output file for generated Go code")
	flag.StringVar(&outputDocEN, "output-doc-en", "", "output markdown file (EN) to update autogenerated block")
	flag.StringVar(&outputDocRU, "output-doc-ru", "", "output markdown file (RU) to update autogenerated block")
	flag.StringVar(&outputDocEN2, "output-doc-en-2", "", "second output markdown file (EN) to update autogenerated block")
	flag.StringVar(&outputDocRU2, "output-doc-ru-2", "", "second output markdown file (RU) to update autogenerated block")
	flag.StringVar(&outputRulesEN, "output-rules-en", "", "output full autogenerated detailed audit rules page (EN)")
	flag.StringVar(&outputRulesRU, "output-rules-ru", "", "output full autogenerated detailed audit rules page (RU)")
	flag.Parse()

	if outputGo == "" {
		panic("missing required -output-go flag")
	}

	if err := generateBasicTargetsCode(workDir, outputGo); err != nil {
		panic(err)
	}

	if outputDocEN != "" {
		if err := generateAuditPolicyDocs(outputDocEN, "en"); err != nil {
			panic(err)
		}
	}

	if outputDocRU != "" {
		if err := generateAuditPolicyDocs(outputDocRU, "ru"); err != nil {
			panic(err)
		}
	}

	if outputDocEN2 != "" {
		if err := generateAuditPolicyDocs(outputDocEN2, "en"); err != nil {
			panic(err)
		}
	}

	if outputDocRU2 != "" {
		if err := generateAuditPolicyDocs(outputDocRU2, "ru"); err != nil {
			panic(err)
		}
	}

	if outputRulesEN != "" {
		if err := generateDetailedAuditRulesDoc(outputRulesEN, "en"); err != nil {
			panic(err)
		}
	}

	if outputRulesRU != "" {
		if err := generateDetailedAuditRulesDoc(outputRulesRU, "ru"); err != nil {
			panic(err)
		}
	}
}

func generateBasicTargetsCode(workDir string, output string) error {
	stream, err := os.Create(output)
	if err != nil {
		return err
	}
	defer stream.Close()

	var namespacesMap = make(map[string]struct{})
	var sasMap = make(map[string]struct{})

	res, err := findModules(workDir)
	if err != nil {
		return err
	}

	for moduleYamlPath, moduleDirName := range res {
		err = processModule(workDir, moduleYamlPath, moduleDirName, sasMap, namespacesMap)
		if err != nil {
			return fmt.Errorf("moduleYamlPath %s: %w", moduleYamlPath, err)
		}
	}

	namespaces := make([]string, 0, len(namespacesMap))
	sas := make([]string, 0, len(sasMap))

	for namespace := range namespacesMap {
		namespaces = append(namespaces, namespace)
	}
	for sa := range sasMap {
		sas = append(sas, sa)
	}

	sort.Strings(namespaces)
	sort.Strings(sas)

	t := template.New("variables")
	t, err = t.Parse(variablesTemplate)
	if err != nil {
		return err
	}

	type Data struct {
		Namespace, ServiceAccount []string
	}
	data := Data{
		Namespace:      uniqueNonEmptyElementsOf(namespaces),
		ServiceAccount: uniqueNonEmptyElementsOf(sas),
	}

	if err = t.Execute(stream, data); err != nil {
		return err
	}

	return nil
}

func generateAuditPolicyDocs(path, lang string) error {
	rules, err := cpmhooks.BuiltInAuditPolicyRulesForDocumentation()
	if err != nil {
		return err
	}

	autogenBlock, err := buildShortAutogeneratedAuditPolicyBlock(rules, lang)
	if err != nil {
		return err
	}

	content, err := os.ReadFile(path)
	if err != nil {
		return err
	}

	replaced, err := replaceAutogeneratedBlock(string(content), autogenBlock)
	if err != nil {
		return err
	}

	return os.WriteFile(path, []byte(replaced), 0o644)
}

func replaceAutogeneratedBlock(content, block string) (string, error) {
	startIdx := strings.Index(content, autogenBlockStart)
	if startIdx < 0 {
		return "", fmt.Errorf("autogenerated block start marker is missing: %s", autogenBlockStart)
	}
	endIdx := strings.Index(content, autogenBlockEnd)
	if endIdx < 0 {
		return "", fmt.Errorf("autogenerated block end marker is missing: %s", autogenBlockEnd)
	}
	endIdx += len(autogenBlockEnd)
	if endIdx < startIdx {
		return "", errors.New("invalid autogenerated block markers order")
	}

	for endIdx < len(content) && (content[endIdx] == '\n' || content[endIdx] == '\r') {
		endIdx++
	}

	normalizedBlock := strings.TrimRight(block, "\r\n")
	return content[:startIdx] + normalizedBlock + "\n\n" + content[endIdx:], nil
}

func renderTemplateFromFile(path string, data any) (string, error) {
	tpl, err := template.New(filepath.Base(path)).ParseFiles(path)
	if err != nil {
		return "", err
	}

	var b bytes.Buffer
	if err := tpl.Execute(&b, data); err != nil {
		return "", err
	}

	return b.String(), nil
}

type shortAutogeneratedBlockTemplateData struct {
	Rules []string
}

func buildShortAutogeneratedAuditPolicyBlock(rules []cpmhooks.AuditPolicyRuleWithDescription, lang string) (string, error) {
	if lang != "en" && lang != "ru" {
		return "", fmt.Errorf("unsupported language %q", lang)
	}

	descriptions := make([]string, 0, len(rules))
	for _, item := range rules {
		description := item.Description.EN
		if lang == "ru" {
			description = item.Description.RU
		}
		descriptions = append(descriptions, description)
	}

	data := shortAutogeneratedBlockTemplateData{Rules: descriptions}

	tplName := "short_block_en.gotmpl"
	if lang == "ru" {
		tplName = "short_block_ru.gotmpl"
	}
	tplPath := filepath.Join(cwd(), "tools", "audit_policy", "templates", tplName)
	return renderTemplateFromFile(tplPath, data)
}

func generateDetailedAuditRulesDoc(path, lang string) error {
	rules, err := cpmhooks.BuiltInAuditPolicyRulesForDocumentation()
	if err != nil {
		return err
	}

	content, err := buildDetailedAuditRulesPage(rules, lang)
	if err != nil {
		return err
	}

	return os.WriteFile(path, []byte(content), 0o644)
}

type detailedRuleTemplateData struct {
	Index       int
	Description string
	RuleYAML    string
}

type fullPolicyRuleTemplateData struct {
	Index                     int
	Description               string
	ListYAML                  string
	InsertCustomCommentBefore bool
}

type detailedAuditRulesPageTemplateData struct {
	Rules           []string
	DetailedRules   []detailedRuleTemplateData
	FullPolicyRules []fullPolicyRuleTemplateData
}

func buildDetailedAuditRulesPage(rules []cpmhooks.AuditPolicyRuleWithDescription, lang string) (string, error) {
	if lang != "en" && lang != "ru" {
		return "", fmt.Errorf("unsupported language %q", lang)
	}

	summaryRules := make([]string, 0, len(rules))
	detailedRules := make([]detailedRuleTemplateData, 0, len(rules))
	fullPolicyRules := make([]fullPolicyRuleTemplateData, 0, len(rules))

	for i, item := range rules {
		description := item.Description.EN
		if lang == "ru" {
			description = item.Description.RU
		}
		summaryRules = append(summaryRules, description)

		ruleYAML, err := compactRuleYAML(item.Rule)
		if err != nil {
			return "", err
		}
		detailedRules = append(detailedRules, detailedRuleTemplateData{
			Index:       i + 1,
			Description: description,
			RuleYAML:    ruleYAML,
		})

		listYAML, err := compactRuleYAMLAsListItem(item.Rule)
		if err != nil {
			return "", err
		}

		insertComment := false
		if item.Section == cpmhooks.AuditPolicySectionUnauthenticated && i > 0 {
			insertComment = rules[i-1].Section != cpmhooks.AuditPolicySectionUnauthenticated
		}

		fullPolicyRules = append(fullPolicyRules, fullPolicyRuleTemplateData{
			Index:                     i + 1,
			Description:               description,
			ListYAML:                  listYAML,
			InsertCustomCommentBefore: insertComment,
		})
	}

	data := detailedAuditRulesPageTemplateData{
		Rules:           summaryRules,
		DetailedRules:   detailedRules,
		FullPolicyRules: fullPolicyRules,
	}

	tplName := "detailed_rules_page_en.gotmpl"
	if lang == "ru" {
		tplName = "detailed_rules_page_ru.gotmpl"
	}
	tplPath := filepath.Join(cwd(), "tools", "audit_policy", "templates", tplName)
	return renderTemplateFromFile(tplPath, data)
}

type compactGroupResources struct {
	Group         string   `yaml:"group,omitempty"`
	Resources     []string `yaml:"resources,omitempty"`
	ResourceNames []string `yaml:"resourceNames,omitempty"`
}

type compactPolicyRule struct {
	Level           audit.Level            `yaml:"level"`
	Users           []string               `yaml:"users,omitempty"`
	UserGroups      []string               `yaml:"userGroups,omitempty"`
	Verbs           []string               `yaml:"verbs,omitempty"`
	Resources       []compactGroupResources `yaml:"resources,omitempty"`
	Namespaces      []string               `yaml:"namespaces,omitempty"`
	NonResourceURLs []string               `yaml:"nonResourceURLs,omitempty"`
	OmitStages      []audit.Stage          `yaml:"omitStages,omitempty"`
	OmitManaged     *bool                  `yaml:"omitManagedFields,omitempty"`
}

func toCompactPolicyRule(in audit.PolicyRule) compactPolicyRule {
	out := compactPolicyRule{Level: in.Level}
	if len(in.Users) > 0 {
		out.Users = in.Users
	}
	if len(in.UserGroups) > 0 {
		out.UserGroups = in.UserGroups
	}
	if len(in.Verbs) > 0 {
		out.Verbs = in.Verbs
	}
	if len(in.Namespaces) > 0 {
		out.Namespaces = in.Namespaces
	}
	if len(in.NonResourceURLs) > 0 {
		out.NonResourceURLs = in.NonResourceURLs
	}
	if len(in.OmitStages) > 0 {
		out.OmitStages = in.OmitStages
	}
	if in.OmitManagedFields != nil {
		out.OmitManaged = in.OmitManagedFields
	}
	if len(in.Resources) > 0 {
		out.Resources = make([]compactGroupResources, 0, len(in.Resources))
		for _, r := range in.Resources {
			cr := compactGroupResources{}
			if r.Group != "" {
				cr.Group = r.Group
			}
			if len(r.Resources) > 0 {
				cr.Resources = r.Resources
			}
			if len(r.ResourceNames) > 0 {
				cr.ResourceNames = r.ResourceNames
			}
			out.Resources = append(out.Resources, cr)
		}
	}
	return out
}

func marshalYAMLWithIndent(v any, indent int) (string, error) {
	var b bytes.Buffer
	enc := yamlv3.NewEncoder(&b)
	enc.SetIndent(indent)
	if err := enc.Encode(v); err != nil {
		_ = enc.Close()
		return "", err
	}
	if err := enc.Close(); err != nil {
		return "", err
	}

	out := strings.TrimPrefix(b.String(), "---\n")
	return out, nil
}

func compactRuleYAML(rule audit.PolicyRule) (string, error) {
	c := toCompactPolicyRule(rule)
	return marshalYAMLWithIndent(c, 2)
}

func compactRuleYAMLAsListItem(rule audit.PolicyRule) (string, error) {
	c := toCompactPolicyRule(rule)
	raw, err := marshalYAMLWithIndent(c, 2)
	if err != nil {
		return "", err
	}

	lines := strings.Split(strings.TrimRight(raw, "\n"), "\n")
	if len(lines) == 0 {
		return "", nil
	}

	var b strings.Builder
	b.WriteString("  - " + lines[0] + "\n")
	for _, line := range lines[1:] {
		b.WriteString("    " + line + "\n")
	}
	return b.String(), nil
}

func cwd() string {
	_, f, _, ok := runtime.Caller(1)
	if !ok {
		panic("cannot get caller")
	}

	dir, err := filepath.Abs(f)
	if err != nil {
		panic(err)
	}

	for i := 0; i < 3; i++ { // ../../
		dir = filepath.Dir(dir)
	}

	// If deckhouse repo directory is symlinked (e.g. to /deckhouse), resolve the real path.
	// Otherwise, filepath.Walk will ignore all subdirectories.
	dir, err = filepath.EvalSymlinks(dir)
	if err != nil {
		panic(err)
	}

	return dir
}

type moduleMetadata struct {
	Name      string `yaml:"name"`
	Namespace string `yaml:"namespace"`
}

func processModuleDefinition(path string) ( /*name*/ string /*namespace*/, string, error) {
	// if file exists
	var s moduleMetadata
	c, err := os.Open(path)
	if err != nil {
		return "", "", err
	}
	defer c.Close()

	err = yamlv3.NewDecoder(c).Decode(&s)
	if err != nil {
		return "", "", err
	}

	if s.Namespace == "" {
		// trim file name from path
		dir := filepath.Dir(path)
		ns, err := os.ReadFile(filepath.Join(dir, ".namespace"))
		if err != nil {
			if errors.Is(err, os.ErrNotExist) {
				return s.Name, "", nil
			}
			return "", "", err
		}
		s.Namespace = strings.Trim(string(ns), "\r\n")
	}

	return s.Name, s.Namespace, nil
}

func processServiceAccounts(templatesDir string) ([]string, error) {
	serviceAccounts := make([]string, 0)
	err := filepath.Walk(templatesDir, func(path string, f os.FileInfo, err error) error {
		if f != nil && f.IsDir() {
			return nil
		}

		if filepath.Base(path) != "rbac-for-us.yaml" {
			return nil
		}

		rbac, err := os.ReadFile(path)
		if err != nil {
			return err
		}

		r := regexp.MustCompile(`apiVersion: v1
kind: ServiceAccount
metadata:
\s*name:\s*(.*)
`)
		match := r.FindAllStringSubmatch(string(rbac), -1)
		for _, m := range match {
			saName := strings.TrimSpace(m[1])
			if strings.HasPrefix(saName, "\"") {
				saName, err = unquote(saName)
				if err != nil {
					return err
				}
			}

			serviceAccounts = append(serviceAccounts, saName)
		}

		return nil
	})

	return serviceAccounts, err
}

func handleServiceAccounts(templatesDir string, modulePath string, name string, ns string, sas map[string]struct{}) error {
	serviceAccounts, err := processServiceAccounts(templatesDir)
	if err != nil {
		return err
	}

	for _, saName := range serviceAccounts {
		// ServiceAccounts for istiod will be added to audit rules in
		// modules/040-control-plane-manager/hooks/audit_policy.go
		if strings.HasPrefix(saName, "istiod-") {
			continue
		}

		saName = strings.Replace(saName, "{{ .Chart.Name }}", name, 1)
		saName = strings.Replace(saName, "{{ $.Chart.Name }}", name, 1)
		if strings.Contains(saName, "{{") || strings.Contains(saName, "}}") {
			continue
		}
		if len(saName) == 0 && len(name) == 0 {
			return fmt.Errorf("empty final SA name, seems chartName didnt resolve for module: %s", modulePath)
		}

		finalName := fmt.Sprintf("system:serviceaccount:%s:%s", ns, saName)
		sas[finalName] = struct{}{}
	}

	return nil
}

func unquote(s string) (string, error) {
	var err error
	if strings.HasPrefix(s, `"`) && strings.HasSuffix(s, `"`) || strings.HasPrefix(s, `'`) && strings.HasSuffix(s, `'`) {
		s, err = strconv.Unquote(s)
		if err != nil {
			return "", err
		}
	}

	return s, err
}

// findModules find all directories, contains module.yaml
// return map of absoulute path to module.yaml -> last directory, where module.yaml is located (xxx-module-name)
func findModules(root string) (map[string]string, error) {
	modulesMap := make(map[string]string)

	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if !info.IsDir() {
			return nil
		}

		modulePath := filepath.Join(path, "module.yaml")
		if _, err := os.Stat(modulePath); err != nil {
			return nil
		}

		relPath, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}

		parts := strings.Split(filepath.ToSlash(relPath), "/")
		for _, part := range parts {
			if part == "modules" {
				dirName := filepath.Base(path)
				modulesMap[modulePath] = dirName
				break
			}
		}

		return nil
	})

	if err != nil {
		return nil, fmt.Errorf("error walking the path %s: %v", root, err)
	}

	return modulesMap, nil
}

func processModule(workDir, moduleYamlPath, moduleDirName string, sas, namespacesMap map[string]struct{}) error {
	name, namespace, err := processModuleDefinition(moduleYamlPath)
	if err != nil {
		return err
	}

	templateDirs, err := findModuleTemplatesDirs(workDir, moduleDirName)
	if err != nil {
		return err
	}

	// namespace is required only if module has templates
	if len(templateDirs) > 0 && namespace == "" {
		panic("Empty namespace for module " + moduleYamlPath)
	}

	for _, td := range templateDirs {
		err = handleServiceAccounts(td, moduleYamlPath, name, namespace, sas)
		if err != nil {
			return err
		}
	}

	if name == "node-manager" && namespace == "d8-cloud-instance-manager" {
		sas["system:serviceaccount:d8-cloud-instance-manager:cluster-autoscaler"] = struct{}{}
	}

	if strings.HasPrefix(namespace, "d8-") || namespace == "kube-system" {
		namespacesMap[namespace] = struct{}{}
	}

	return nil
}

func uniqueNonEmptyElementsOf(s []string) []string {
	unique := make(map[string]bool, len(s))
	us := make([]string, len(unique))
	for _, elem := range s {
		if len(elem) != 0 {
			if !unique[elem] {
				us = append(us, elem)
				unique[elem] = true
			}
		}
	}

	return us
}

// findModuleTemplatesDirs finds all templates directories within moduleDir
// under workDir. Returns a slice of absolute paths to templates directories.
func findModuleTemplatesDirs(workDir, moduleDir string) ([]string, error) {
	var templatesDirs []string

	checkTemplates := func(modulePath string) error {
		templatesPath := filepath.Join(modulePath, "templates")

		info, err := os.Stat(templatesPath)
		if err != nil {
			if !os.IsNotExist(err) {
				return fmt.Errorf("error checking templates dir %s: %v", templatesPath, err)
			}

			return nil
		}

		if info.IsDir() {
			templatesDirs = append(templatesDirs, templatesPath)
		}

		return nil
	}

	// recursive find moduleDir
	err := filepath.Walk(workDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if info.IsDir() && filepath.Base(path) == moduleDir {
			if err := checkTemplates(path); err != nil {
				return err
			}
		}
		return nil
	})

	if err != nil {
		return nil, fmt.Errorf("error searching for module dirs: %v", err)
	}

	return templatesDirs, nil
}
