#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p onStartup=5
}

function __main__() {
  if values::has global.certificateForIngress.customCertificateSecretName && ! values::is_false global.certificateForIngress.customCertificateSecretName && \
     values::has global.certificateForIngress.certmanagerClusterIssuerName && ! values::is_false global.certificateForIngress.certmanagerClusterIssuerName
     then
       >&2 echo "You need to use only one of the parameters: global.certificateForIngress.certmanagerClusterIssuerName or global.certificateForIngress.customCertificateSecretName"
       exit 1
  fi
}

hook::run $@
