#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  jo -p configVersion=v1 onStartup=0
}

function __main__() {
  values::require_in_config global.project
  values::require_in_config global.clusterName
}

hook::run "$@"
