{
 "title": "MetalLB L2",
 "tags": [ "main" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "layer2instance",
    "label": "Layer 2 instance",
    "query": {
     "query": "label_values(metallb_layer2_gratuitous_sent{d8_source=\"dkp\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pools in usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(metallb_allocator_addresses_total{d8_source=\"dkp\", job=\"l2lb-controller\"} unless metallb_allocator_addresses_total{d8_source=\"dkp\", job=\"controller\"}) > 0 and (metallb_allocator_addresses_in_use_total{d8_source=\"dkp\", job=\"l2lb-controller\"} unless metallb_allocator_addresses_in_use_total{d8_source=\"dkp\", job=\"controller\"}) > 0"
    },
    {
     "expr": "(metallb_allocator_addresses_in_use_total{d8_source=\"dkp\", job=\"l2lb-controller\"} unless metallb_allocator_addresses_in_use_total{d8_source=\"dkp\", job=\"controller\"}) > 0"
    }
   ]
  },
  {
   "title": "Pools usage (Total)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((metallb_allocator_addresses_in_use_total{d8_source=\"dkp\", job=\"l2lb-controller\"} unless metallb_allocator_addresses_in_use_total{d8_source=\"dkp\", job=\"controller\"}) > 0) / ((metallb_allocator_addresses_total{d8_source=\"dkp\", job=\"l2lb-controller\"} unless metallb_allocator_addresses_total{d8_source=\"dkp\", job=\"controller\"}) > 0) * 100"
    }
   ]
  },
  {
   "title": "Pools usage (Total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(metallb_allocator_addresses_total{d8_source=\"dkp\", job=\"l2lb-controller\"} unless metallb_allocator_addresses_total{d8_source=\"dkp\", job=\"controller\"}) > 0 and (metallb_allocator_addresses_in_use_total{d8_source=\"dkp\", job=\"l2lb-controller\"} unless metallb_allocator_addresses_in_use_total{d8_source=\"dkp\", job=\"controller\"}) > 0",
     "legendFormat": "Total addresses in pool: {{pool}}"
    },
    {
     "expr": "(metallb_allocator_addresses_in_use_total{d8_source=\"dkp\", job=\"l2lb-controller\"} unless metallb_allocator_addresses_in_use_total{d8_source=\"dkp\", job=\"controller\"}) > 0",
     "legendFormat": "Used addresses in pool: {{pool}}"
    }
   ]
  },
  {
   "title": "Announced by speakers",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by(pod, ip, node) (metallb_speaker_announced{d8_source=\"dkp\", protocol=\"layer2\"})"
    }
   ]
  },
  {
   "title": "L2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "ARP packets",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(metallb_layer2_gratuitous_sent{d8_source=\"dkp\", instance=~\"$layer2instance\"}[5m])",
       "legendFormat": "gratuitous_sent instance={{instance}} ip={{ip}} "
      },
      {
       "expr": "rate(metallb_layer2_requests_received{d8_source=\"dkp\", instance=~\"$layer2instance\",namespace=\"d8-metallb\"}[5m])",
       "legendFormat": "requests_received instance={{instance}} ip={{ip}} "
      },
      {
       "expr": "rate(metallb_layer2_responses_sent{d8_source=\"dkp\", instance=~\"$layer2instance\",namespace=\"d8-metallb\"}[5m])",
       "legendFormat": "responses_sent instance={{instance}} ip={{ip}} "
      }
     ]
    }
   ]
  }
 ]
}