---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: docs-builder
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: modules-watcher
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: leases-admin
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: leases-reader
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: docs-builder
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: docs-builder
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: leases-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modules-watcher
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: modules-watcher
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: leases-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: configmap-installer-updater-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: embedded-modules-history-sync-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: configmap-installer-updater-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "update", "patch"]
    resourceNames: ["doc-installer-version"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: embedded-modules-history-sync-role
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "update", "patch"]
    resourceNames: ["embedded-modules-history-data"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-installer-updater
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: configmap-installer-updater-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: configmap-installer-updater-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: embedded-modules-history-sync
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
subjects:
  - kind: ServiceAccount
    name: embedded-modules-history-sync-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: embedded-modules-history-sync-role
  apiGroup: rbac.authorization.k8s.io
