{{- if (pluck $.Values.web.env .Values.observability.enable | first | default .Values.observability.enable._default) }}
apiVersion: deckhouse.io/v1
kind: CustomPrometheusRules
metadata:
  name: registry-modules-watcher
spec:
  groups:
  - name: d8.registry-modules-watcher.alerts
    rules:
    - alert: D8RegistryScannerModuleWithoutTags
      expr: d8_telemetry_registry_scanner_module_without_tags > 0
      labels:
        severity_level: "7"
        d8_component: registry-modules-watcher
      annotations:
        plk_protocol_version: "1"
        plk_markup_format: "markdown"
        summary: |
          Module `{{ $labels.module }}` has no tags in registry `{{ $labels.registry }}`.
        description: |
          The registry scanner detected that module `{{ $labels.module }}` has no tags in registry `{{ $labels.registry }}`.

    - alert: D8RegistryScannerRegistryUnavailable
      expr: d8_telemetry_registry_scanner_registry_unavailable > 0
      labels:
        severity_level: "7"
        d8_component: registry-modules-watcher
      annotations:
        plk_protocol_version: "1"
        plk_markup_format: "markdown"
        summary: |
          Registry `{{ $labels.registry }}` is unavailable.
        description: |
          The registry scanner cannot connect to registry `{{ $labels.registry }}`.
{{- end }}