---
{{/* TODO: remove this after tests
{{- if eq $.Values.web.env "web-production" }}
 */}}
{{- if (pluck $.Values.web.env .Values.observability.enable | first | default .Values.observability.enable._default) }}
apiVersion: deckhouse.io/v1
kind: PrometheusRemoteWrite
metadata:
  name: docs-telemetry-dev-remote-write
  labels:
    app.kubernetes.io/part-of: deckhouse-web-docs-telemetry
spec:
  customAuthToken: "{{ .Values.dop.authToken }}"
  url: "{{ .Values.dop.url }}"
  writeRelabelConfigs:
  - action: keep
    regex: (d8_telemetry_.*)
    sourceLabels:
    - __name__
{{- end }}
{{/* TODO: remove this after tests
{{- end }} 
*/}}
