{
 "title": "Namespace",
 "tags": [ "main" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kubernetes_build_info{source=\"deckhouse\"}, node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{source=\"deckhouse\", node=~\"$node\"}, namespace)"
    }
   },
   {
    "name": "controller_type",
    "label": "Controller Type",
    "query": {
     "query": "label_values(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=~\"$namespace\"}, controller_type{source=\"deckhouse\"})"
    }
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": {
     "query": "label_values(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=~\"$namespace\", controller_type=~\"$controller_type\"}, controller)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=\"$controller\"}, pod)"
    }
   },
   {
    "name": "persistentvolumeclaim",
    "label": "PersistentVolumeClaim",
    "query": {
     "query": "query_result(max_over_time(kubelet_volume_stats_capacity_bytes{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__range]))"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Controllers",
   "type": "table",
   "description": "Note that this table shows the average values for the entire period selected in the dashboard. Consequently, it may contain information about Pods or namespaces that were changed or deleted during the selected period.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (job, namespace, controller, controller_name) (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range]))",
     "legendFormat": "Controller"
    },
    {
     "expr": "sum by (controller) (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range]) * on (controller_type, controller_name) group_left() sum by (controller_type, controller_name) (avg_over_time(vpa_target_recommendation{source=\"deckhouse\", namespace=\"$namespace\", update_mode=\"Off\"}[$__range]))) * 0\nor\nsum by (controller) (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range]) * on (controller_type, controller_name) group_left() sum by (controller_type, controller_name) (avg_over_time(vpa_target_recommendation{source=\"deckhouse\", namespace=\"$namespace\", update_mode=\"Initial\"}[$__range]))) * 0 + 1\nor\nsum by (controller) (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range]) * on (controller_type, controller_name) group_left() sum by (controller_type, controller_name) (avg_over_time(vpa_target_recommendation{source=\"deckhouse\", namespace=\"$namespace\", update_mode=\"Auto\"}[$__range]))) * 0 + 2\nor\nsum by (controller) (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range]) * on (controller_type, controller_name) group_left() sum by (controller_type, controller_name) (avg_over_time(vpa_target_recommendation{source=\"deckhouse\", namespace=\"$namespace\", update_mode=\"Recreate\"}[$__range]))) * 0 + 3\nor\nsum by (controller) (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])) * 0 + 5",
     "legendFormat": "VPA Mode"
    },
    {
     "expr": "sum by (controller) (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range]) * on (pod) group_left() sum by (pod) (rate(container_cpu_usage_seconds_total{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__range])))\nor\ncount (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])) by (controller) * 0",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum by (controller)\n  (\n    avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])\n    * on (pod) group_left()\n    sum by (pod) (avg_over_time(kube_pod_container_resource_requests{source=\"deckhouse\", resource=\"cpu\",unit=\"core\",node=~\"$node\", namespace=\"$namespace\"}[$__range]))\n  )\nor\ncount (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])) by (controller) * 0",
     "legendFormat": "Req CPU"
    },
    {
     "expr": "sum by (controller)\n  (\n    avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])\n    * on (controller_type, controller_name) group_left()\n    sum by(controller_type, controller_name) (avg_over_time(vpa_target_recommendation{source=\"deckhouse\", container!=\"POD\",namespace=\"$namespace\", resource=\"cpu\"}[$__range]))\n  ) \nor\ncount (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])) by (controller) * 0",
     "legendFormat": "VPA CPU"
    },
    {
     "expr": "sum by (controller)\n  (\n    avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])\n    * on (namespace, pod) group_left()\n    sum by (namespace, pod)\n      (\n        (\n          sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests{source=\"deckhouse\", resource=\"cpu\",unit=\"core\",node=~\"$node\", namespace=\"$namespace\"}[$__range]))\n          -\n          sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{source=\"deckhouse\", node=~\"$node\", container!=\"POD\", namespace=\"$namespace\"}[$__range]))\n        ) > 0\n      )\n  )\nor\ncount (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])) by (controller) * 0",
     "legendFormat": "Over-req CPU"
    },
    {
     "expr": "sum by (controller)\n  (\n    avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])\n    * on (namespace, pod) group_left()\n    sum by (namespace, pod)\n      (\n        (\n          (\n            sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__range]))\n            -\n            sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests{source=\"deckhouse\", resource=\"cpu\",unit=\"core\",node=~\"$node\", container!=\"POD\", namespace=\"$namespace\"}[$__range]))\n          ) or sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{source=\"deckhouse\", node=~\"$node\", container!=\"POD\", namespace=\"$namespace\"}[$__range]))\n        ) > 0\n      )\n  )\nor\ncount (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])) by (controller) * 0",
     "legendFormat": "Under-req CPU"
    },
    {
     "expr": "sum by (controller) (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range]) * on (pod) group_left() ((sum by (pod) (rate(container_cpu_cfs_throttled_periods_total{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__range])) / sum by (pod) (rate(container_cpu_cfs_periods_total{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__range]))) * sum by (pod) (rate(kube_pod_container_resource_limits{source=\"deckhouse\", resource=\"cpu\",unit=\"core\",node=~\"$node\", namespace=\"$namespace\"}[$__range]))))\nor\ncount (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])) by (controller) * 0",
     "legendFormat": "Throttling cores"
    },
    {
     "expr": "sum by (controller) (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range]) * on (pod) group_left() sum by (pod) (avg_over_time(container_memory_working_set_bytes:without_kmem{node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__range])))\nor\ncount (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])) by (controller) * 0",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum by (controller)\n  (\n    avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])\n    * on (pod) group_left()\n    sum by (namespace, pod)\n      (\n        avg_over_time(kube_pod_container_resource_requests{source=\"deckhouse\", resource=\"memory\",unit=\"byte\",node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__range])\n      )\n    )\n  or\n  count (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])) by (controller) * 0",
     "legendFormat": "Req Memory"
    },
    {
     "expr": "sum by (controller)\n  (\n    avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])\n    * on (controller_type, controller_name) group_left()\n    sum by(controller_type, controller_name) (avg_over_time(vpa_target_recommendation{source=\"deckhouse\", container!=\"POD\",namespace=\"$namespace\", resource=\"memory\"}[$__range]))\n  ) \n  or  \ncount (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])) by (controller) * 0",
     "legendFormat": "VPA Memory"
    },
    {
     "expr": "sum by (controller)\n  (\n    avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])\n    * on (namespace, pod) group_left()\n    sum by (namespace, pod)\n      (\n        (\n          sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests{source=\"deckhouse\", resource=\"memory\",unit=\"byte\",node=~\"$node\", namespace=\"$namespace\"}[$__range]))\n          -\n          sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes:without_kmem{node=~\"$node\", container!=\"POD\", namespace=\"$namespace\"}[$__range]))\n        ) > 0\n      )\n  )\nor\ncount (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])) by (controller) * 0",
     "legendFormat": "Over-req Memory"
    },
    {
     "expr": "sum by (controller)\n  (\n    avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])\n    * on (namespace, pod) group_left()\n    sum by (namespace, pod)\n      (\n        (\n          (\n            sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes:without_kmem{node=~\"$node\", namespace=\"$namespace\"}[$__range]))\n            -\n            sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests{source=\"deckhouse\", resource=\"memory\",unit=\"byte\",node=~\"$node\", container!=\"POD\", namespace=\"$namespace\"}[$__range]))\n          ) or sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes:without_kmem{node=~\"$node\", container!=\"POD\", namespace=\"$namespace\"}[$__range]))\n        ) > 0\n      )\n  )\nor\ncount (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])) by (controller) * 0",
     "legendFormat": "Under-req Memory"
    },
    {
     "expr": "sum by(controller) (  # Data rate of the controller is a sum of data rates from its Pods.\n  kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"} \n  * on(pod)\n  group_left() # Do not drop controller label from kube_controller_pod{source=\"deckhouse\"}.\n  sum by(pod)  # Use sum if there are multiple interaces in the Pod.\n  (\n    max(rate(container_network_receive_bytes_total{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__range])) by(pod)\n    *   # Select only Pods with 'hostNetwork: false', because receive_bytes{source=\"deckhouse\"} values are meaningful only for Pods with hostNetwork:{source=\"deckhouse\"} false.\n    on(pod)\n    kube_pod_info{source=\"deckhouse\", host_network=\"false\", namespace=\"$namespace\"}\n  )\n)\nor # Return -1 value for Pods with 'hostNetwork: true' to rewrite by value mapping.\n# Use max to get one '-1' per controller\n(max by(controller) (\n  kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}\n  * on(pod)\n  group_left() # Do not drop controller label from kube_controller_pod{source=\"deckhouse\"}.\n  (kube_pod_info{source=\"deckhouse\", host_network=\"true\", namespace=\"$namespace\"})\n) * -1)",
     "legendFormat": "RX Network"
    },
    {
     "expr": "sum by(controller) (  # Data rate of the controller is a sum of data rates from its Pods.\n  kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"} \n  * on(pod)\n  group_left() # Do not drop controller label from kube_controller_pod{source=\"deckhouse\"}.\n  sum by(pod)  # Use sum if there are multiple interaces in the Pod.\n  (\n    max(rate(container_network_transmit_bytes_total{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__range])) by(pod)\n    *   # Select only Pods with 'hostNetwork: false', because receive_bytes{source=\"deckhouse\"} values are meaningful only for Pods with hostNetwork:{source=\"deckhouse\"} false.\n    on(pod)\n    kube_pod_info{source=\"deckhouse\", host_network=\"false\", namespace=\"$namespace\"}\n  )\n)\nor # Return -1 value for Pods with 'hostNetwork: true' to rewrite by value mapping.\n# Use max to get one '-1' per controller\n(max by(controller) (\n  kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}\n  * on(pod)\n  group_left() # Do not drop controller label from kube_controller_pod{source=\"deckhouse\"}.\n  (kube_pod_info{source=\"deckhouse\", host_network=\"true\", namespace=\"$namespace\"})\n) * -1)",
     "legendFormat": "TX Network"
    },
    {
     "expr": "sum by (controller) (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range]) * on (pod) group_left() sum by (pod) (rate(container_fs_reads_total{source=\"deckhouse\", node=~\"$node\", container!=\"POD\", namespace=\"$namespace\"}[$__range])))\nor\ncount (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])) by (controller) * 0",
     "legendFormat": "Read IOPS"
    },
    {
     "expr": "sum by (controller) (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range]) * on (pod) group_left() sum by (pod) (rate(container_fs_writes_total{source=\"deckhouse\", node=~\"$node\", container!=\"POD\", namespace=\"$namespace\"}[$__range])))\nor\ncount (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])) by (controller) * 0",
     "legendFormat": "Write IOPS"
    },
    {
     "expr": "max by (controller) (max by (namespace, controller_type, controller_name, controller) (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])) * on (namespace, controller_type, controller_name) group_left() max by (namespace, controller_type, controller_name) (avg_over_time(kube_controller_replicas{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__range])))\nor\ncount (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])) by (controller) * 0",
     "legendFormat": "Total replicas count"
    },
    {
     "expr": "max by (job, namespace, controller_type, controller_name, controller) ((max by (job, namespace, controller_type, controller_name, controller) (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range]))) *  on (job, namespace, controller_type, controller_name) group_right(controller)\n(avg_over_time(kube_controller_replicas{source=\"deckhouse\"}[$__range]) - avg_over_time(kube_controller_replicas_ready{source=\"deckhouse\"}[$__range])))\nor\nmax by (job, namespace, controller_type, controller_name, controller) (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])) * 0",
     "legendFormat": "Not ready replicas"
    },
    {
     "expr": "sum by (controller) \n  (\n    avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])\n    * on (pod) group_left()\n    sum by (pod) (increase(kube_pod_container_status_restarts_total{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__range]))\n  )\nor\ncount (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])) by (controller) * 0",
     "legendFormat": "Pod restart count"
    },
    {
     "expr": "sum by (controller) (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range]) * on (pod) group_left() sum by (pod) (avg_over_time(container_memory:kmem{node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__range])))\nor\ncount (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range])) by (controller) * 0",
     "legendFormat": "Memory"
    },
    {
     "expr": "max by (job, namespace, controller, controller_name) (avg_over_time(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}[$__range]))",
     "legendFormat": "URL"
    }
   ]
  },
  {
   "title": "Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "kube_controller_replicas_ready{source=\"deckhouse\", namespace=~\"$namespace\", controller_type=~\"$controller_type\", controller_type != \"ReplicaSet\", controller_name=~\"$controller\"}/kube_controller_replicas{source=\"deckhouse\", namespace=~\"$namespace\", controller_type=~\"$controller_type\", controller_type != \"ReplicaSet\", controller_name=~\"$controller\"}*100",
     "legendFormat": "{{controller_type}}/{{ controller_name }}"
    }
   ]
  },
  {
   "title": "Pods count",
   "type": "timeseries",
   "description": "The number of Pods controlled by the Controller",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (controller) \n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller_type!=\"VirtualMachine\", controller=~\"$controller\"}\n    * on (pod) group_left()\n    sum by (pod) (max_over_time(kube_pod_info{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__rate_interval]))\n  )",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  {
   "title": "VM pods count",
   "type": "timeseries",
   "description": "The number of VM pods",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (controller) \n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=\"VirtualMachine\", controller=~\"$controller\"}\n    * on (pod) group_left()\n    sum by (pod) (max_over_time(kube_pod_info{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__rate_interval]))\n    unless on (pod)\n    (kube_pod_status_phase{source=\"deckhouse\", phase=~\"Succeeded|Failed\"} == 1)\n  )",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  {
   "title": "Pods restarts",
   "type": "timeseries",
   "description": "The number of Pod restarts",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (controller) \n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}\n    * on (pod) group_left()\n    sum by (pod) (increase(kube_pod_container_status_restarts_total{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__rate_interval]))\n  )",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Usage by controller",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (controller) (kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_usage_seconds_total{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__rate_interval])))",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  {
   "title": "Usage by state",
   "type": "timeseries",
   "description": "The total value may not equal the sum of system and user times because of the kernel's cgroup accounting peculiarities. Read more here: https://www.kernel.org/doc/Documentation/cgroup-v1/cpuacct.txt",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (sum by (controller) (kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_system_seconds_total{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__rate_interval]))))",
     "legendFormat": "System"
    },
    {
     "expr": "sum (sum by (controller) (kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_user_seconds_total{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__rate_interval]))))",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "Over-requested by controller",
   "type": "timeseries",
   "description": "This graph shows the requested CPU resources higher than the actual CPU consumption. In other words, it shows CPU resources that can be \"freed\" without affecting the service.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (controller)\n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}\n    * on (namespace, pod) group_left()\n    sum by (namespace, pod)\n      (\n        (\n          sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests{source=\"deckhouse\", resource=\"cpu\",unit=\"core\",node=~\"$node\", namespace=\"$namespace\"}[$__rate_interval]))\n          -\n          sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{source=\"deckhouse\", node=~\"$node\", container!=\"POD\", namespace=\"$namespace\"}[$__rate_interval]))\n        ) > 0\n      )\n  )",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  {
   "title": "Under-requested by controller",
   "type": "timeseries",
   "description": "This graph shows the requested CPU resources lower than the actual CPU consumption. In other words, it shows CPU resources that need to be \"reserved\" for the service to run smoothly.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (controller)\n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}\n    * on (namespace, pod) group_left()\n    sum by (namespace, pod)\n      (\n        (\n          (\n            sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__rate_interval]))\n            -\n            sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests{source=\"deckhouse\", resource=\"cpu\",unit=\"core\",node=~\"$node\", container!=\"POD\", namespace=\"$namespace\"}[$__rate_interval]))\n          ) or sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{source=\"deckhouse\", node=~\"$node\", container!=\"POD\", namespace=\"$namespace\"}[$__rate_interval]))\n        ) > 0\n      )\n  )",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  {
   "title": "Throttling",
   "type": "timeseries",
   "description": "The absence of data on the graph means that container resources are not set",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (controller) (kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"} * on (pod) group_left() ((sum by (pod) (rate(container_cpu_cfs_throttled_periods_total{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__rate_interval])) / sum by (pod) (rate(container_cpu_cfs_periods_total{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__rate_interval]))) * sum by (pod) (kube_pod_container_resource_limits{source=\"deckhouse\", resource=\"cpu\",unit=\"core\",node=~\"$node\", namespace=\"$namespace\"})))",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  {
   "title": "Controllers CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "$controller",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 47 },
     "repeat": "controller",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (controller) (kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_usage_seconds_total{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__rate_interval])))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (controller)\n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by(pod) (avg_over_time(kube_pod_container_resource_requests{source=\"deckhouse\", resource=\"cpu\",unit=\"core\",node=~\"$node\", container!=\"POD\",namespace=\"$namespace\"}[$__rate_interval]))\n  )",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (controller)\n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by(pod) (avg_over_time(kube_pod_container_resource_limits{source=\"deckhouse\", resource=\"cpu\",unit=\"core\",node=~\"$node\", container!=\"POD\",namespace=\"$namespace\"}[$__rate_interval]))\n  )",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (controller)\n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=\"$controller\"}\n    * on (controller_type, controller_name) group_left()\n    sum by(controller_type, controller_name) (avg_over_time(vpa_target_recommendation{source=\"deckhouse\", container!=\"POD\",namespace=\"$namespace\", resource=\"cpu\"}[$__rate_interval]))\n  )",
       "legendFormat": "VPA Target"
      }
     ]
    }
   ]
  },
  {
   "title": "Controllers CPU by state",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "$controller",
     "type": "timeseries",
     "description": "The total value may not equal the sum of system and user times because of the kernel's cgroup accounting peculiarities. Read more here: https://www.kernel.org/doc/Documentation/cgroup-v1/cpuacct.txt",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 48 },
     "repeat": "controller",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (controller) (kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_system_seconds_total{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__rate_interval])))",
       "legendFormat": "System"
      },
      {
       "expr": "sum by (controller) (kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_user_seconds_total{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__rate_interval])))",
       "legendFormat": "User"
      }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Usage by controller",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (controller)\n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}\n    * on (pod) group_left()\n    sum by (pod) (avg_over_time(container_memory_working_set_bytes:without_kmem{node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__rate_interval]))\n  )",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  {
   "title": "Usage by state",
   "type": "timeseries",
   "description": "The Working set bytes metric is the actual memory used by the container, as it includes active file memory. When its value approaches the limit, the container can be killed by the OOM killer. This value can be higher than the sum RSS and Cache since not all active file memory is Cache.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum\n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}\n    * on (pod) group_left()\n    sum by (pod) (avg_over_time(container_memory_rss{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__rate_interval]))\n  )",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum \n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}\n    * on (pod) group_left()\n    sum by (pod) (avg_over_time(container_memory_cache{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__rate_interval]))\n  )",
     "legendFormat": "Cache"
    },
    {
     "expr": "sum \n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}\n    * on (pod) group_left()\n    sum by (pod) (avg_over_time(container_memory_swap{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__rate_interval]))\n  )",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum \n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}\n    * on (pod) group_left()\n    sum by (pod) (avg_over_time(container_memory_working_set_bytes:without_kmem{node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__rate_interval]))\n  )",
     "legendFormat": "Working set bytes without kmem"
    },
    {
     "expr": "sum \n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}\n    * on (pod) group_left()\n    sum by (pod) (avg_over_time(container_memory:kmem{node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__rate_interval]))\n  )",
     "legendFormat": "Kmem"
    }
   ]
  },
  {
   "title": "Over-requested by controller",
   "type": "timeseries",
   "description": "This graph shows the requested Memory resources higher than the actual Memory consumption. In other words, it shows Memory resources that can be \"freed\" without affecting the service.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (controller)\n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}\n    * on (namespace, pod) group_left()\n    sum by (namespace, pod)\n      (\n        (\n          sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests{source=\"deckhouse\", resource=\"memory\",unit=\"byte\",node=~\"$node\", namespace=\"$namespace\"}[$__rate_interval]))\n          -\n          sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes:without_kmem{node=~\"$node\", container!=\"POD\", namespace=\"$namespace\"}[$__rate_interval]))\n        ) > 0\n      )\n  )",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  {
   "title": "Under-requested by controller",
   "type": "timeseries",
   "description": "This graph shows the requested Memory resources higher than the actual Memory consumption. In other words, it shows Memory resources that need to be \"reserved\" for the service to run smoothly.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (controller)\n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}\n    * on (namespace, pod) group_left()\n    sum by (namespace, pod)\n      (\n        (\n          (\n            sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes:without_kmem{node=~\"$node\", namespace=\"$namespace\"}[$__rate_interval]))\n            -\n            sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests{source=\"deckhouse\", resource=\"memory\",unit=\"byte\",node=~\"$node\", container!=\"POD\", namespace=\"$namespace\"}[$__rate_interval]))\n          )\n          or\n          (\n            sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes:without_kmem{node=~\"$node\", container!=\"POD\", namespace=\"$namespace\"}[$__rate_interval]))\n            +\n            sum by(namespace, pod, container) (avg_over_time(container_memory:kmem{node=~\"$node\", container!=\"POD\", namespace=\"$namespace\"}[$__rate_interval]))\n          )\n        ) > 0\n      )\n  )",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  {
   "title": "Controllers Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "$controller",
     "type": "timeseries",
     "description": "The Working set bytes metric is the actual memory used by the container, as it includes active file memory. When its value approaches the limit, the container can be killed by the OOM killer. This value can be higher than the sum RSS and Cache since not all active file memory is Cache.",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 67 },
     "repeat": "controller",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum \n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left() \n    sum by (pod) (avg_over_time(container_memory_rss{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__rate_interval]))\n  )",
       "legendFormat": "RSS"
      },
      {
       "expr": "sum\n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=\"$controller\"} \n    * on (pod) group_left() \n    sum by (pod) (avg_over_time(container_memory_cache{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__rate_interval]))\n  )",
       "legendFormat": "Cache"
      },
      {
       "expr": "sum \n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left() \n    sum by (pod) (avg_over_time(container_memory_swap{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__rate_interval]))\n  )",
       "legendFormat": "Swap"
      },
      {
       "expr": "sum \n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by (pod) (avg_over_time(container_memory_working_set_bytes:without_kmem{node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__rate_interval]))\n  )",
       "legendFormat": "Working set bytes without kmem"
      },
      {
       "expr": "sum \n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by(pod) (avg_over_time(kube_pod_container_resource_requests{source=\"deckhouse\", resource=\"memory\",unit=\"byte\",node=~\"$node\", container!=\"POD\",namespace=\"$namespace\"}[$__rate_interval]))\n  ) ",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum\n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=\"$controller\"} \n    * on (pod) group_left() \n    sum by(pod) (avg_over_time(kube_pod_container_resource_limits{source=\"deckhouse\", resource=\"memory\",unit=\"byte\",node=~\"$node\", container!=\"POD\",namespace=\"$namespace\"}[$__rate_interval]))\n  )",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum \n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=\"$controller\"}\n    * on (controller_type, controller_name) group_left()\n    sum by(controller_type, controller_name) (avg_over_time(vpa_target_recommendation{source=\"deckhouse\", container!=\"POD\",namespace=\"$namespace\", resource=\"memory\"}[$__rate_interval]))\n  )",
       "legendFormat": "VPA Target"
      },
      {
       "expr": "sum \n  (\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by (pod) (avg_over_time(container_memory:kmem{node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__rate_interval]))\n  )",
       "legendFormat": "Kmem"
      }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Receive",
   "type": "timeseries",
   "description": "This graph shows Network Receive (except for the hostNetwork Pods)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "# Data rate for the controller is a sum of data rates of its Pods.\nsum by (controller) (\n  # Select Pods by controller_type and controller.\n  kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"}\n  * on (pod)\n  group_left() # Preserve controller label from the 'kube_controller_pod{source=\"deckhouse\"}' metric.\n  (\n    # Select Pods with hostNetwork:{source=\"deckhouse\"} false.\n    max(kube_pod_info{source=\"deckhouse\", host_network=\"false\",namespace=\"$namespace\"}) by(pod)\n    * on(pod)\n    # Sum data rate for all interfaces in the Pod. \n    sum by (pod) (rate(container_network_receive_bytes_total{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__rate_interval]) * 8)\n  )\n)",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  {
   "title": "Transmit",
   "type": "timeseries",
   "description": "This graph shows Network Transmit (except for the hostNetwork Pods)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "# Data rate for the controller is a sum of data rates of its Pods.\nsum by (controller) (\n  # Select Pods by controller_type and controller.\n  kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"} \n  * on (pod)\n  group_left() # Preserve controller label from the 'kube_controller_pod{source=\"deckhouse\"}' metric.\n  (\n    # Select Pods with hostNetwork:{source=\"deckhouse\"} false.\n    max(kube_pod_info{source=\"deckhouse\", host_network=\"false\",namespace=\"$namespace\"}) by(pod)\n    * on(pod)\n    # Sum data rate for all interfaces in the Pod. \n    sum by (pod) (rate(container_network_transmit_bytes_total{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__rate_interval]) * 8)\n  )\n)",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  { "title": "IOPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by (controller) (kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_fs_reads_total{source=\"deckhouse\", node=~\"$node\", container!=\"POD\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  {
   "title": "Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by (controller) (kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller_type=~\"$controller_type\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_fs_writes_total{source=\"deckhouse\", node=~\"$node\", container!=\"POD\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  { "title": "PVC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "PVC Provisioned (except local storage classes)",
   "type": "timeseries",
   "description": "This graph does not show any localstorage-related information due to incorrectly calculating the occupied space on localstorage disks",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, controller) (\n  max by (namespace, controller, persistentvolumeclaim)\n  (\n    sum by (namespace, persistentvolumeclaim) (\n        max_over_time(kubelet_volume_stats_capacity_bytes{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__rate_interval])\n    ) \n\n    * max by (namespace, persistentvolumeclaim) (\n      label_replace(\n        max_over_time(kube_persistentvolumeclaim_info{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval]),\n        \"persistentvolume\", \"$1\", \"volumename\", \"(.*)\")\n      + on (persistentvolume) group_left() max by (persistentvolume) (kube_persistentvolume_is_local{source=\"deckhouse\"} == 0)\n    )\n\n        * on (namespace, persistentvolumeclaim) group_left(pod) \n    max by (namespace, persistentvolumeclaim, pod) (\n         max_over_time(kube_pod_spec_volumes_persistentvolumeclaims_info{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])\n    ) \n\n       * on (namespace, pod) group_left(controller)\n      kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=~\"$controller\"} \n  )\n)",
     "legendFormat": "Provisioned {{ controller }}"
    },
    {
     "expr": "sum (\n  sum by (namespace, persistentvolumeclaim) (\n    max_over_time(kube_persistentvolumeclaim_resource_requests_storage_bytes{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])\n  ) \n  * \n  sum by (namespace, persistentvolumeclaim) (\n    label_replace(\n      max_over_time(kube_persistentvolumeclaim_info{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval]),\n      \"persistentvolume\", \"$1\", \"volumename\", \"(.*)\")\n    + on (persistentvolume) group_left() max by (persistentvolume) (kube_persistentvolume_is_local{source=\"deckhouse\"} == 0)\n\n  )\n  unless\n  sum by (namespace, persistentvolumeclaim) (\n    max_over_time(kube_pod_spec_volumes_persistentvolumeclaims_info{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])\n  ) \n) \nand (count (kube_node_info{source=\"deckhouse\"}) == count (kube_node_info{source=\"deckhouse\", node=~\"$node\"}))",
     "legendFormat": "Unused PVC"
    }
   ]
  },
  {
   "title": "PVC Usage (except local storage classes)",
   "type": "timeseries",
   "description": "This graph does not show any localstorage-related information due to incorrectly calculating the occupied space on localstorage disks",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, controller) (\n  max by (namespace, controller, persistentvolumeclaim)\n  (\n    sum by (namespace, persistentvolumeclaim) (\n        max_over_time(kubelet_volume_stats_capacity_bytes{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__rate_interval]) - max_over_time(kubelet_volume_stats_available_bytes{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__rate_interval])\n    ) \n\n    * max by (namespace, persistentvolumeclaim) (\n      label_replace(\n        max_over_time(kube_persistentvolumeclaim_info{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval]),\n        \"persistentvolume\", \"$1\", \"volumename\", \"(.*)\")\n      + on (persistentvolume) group_left() max by (persistentvolume) (kube_persistentvolume_is_local{source=\"deckhouse\"} == 0)\n    )\n\n        * on (namespace, persistentvolumeclaim) group_left(pod) \n    max by (namespace, persistentvolumeclaim, pod) (\n         max_over_time(kube_pod_spec_volumes_persistentvolumeclaims_info{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])\n    ) \n\n       * on (namespace, pod) group_left(controller)\n      kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=~\"$controller\"} \n  )\n)",
     "legendFormat": "Usage {{ controller }}"
    }
   ]
  },
  {
   "title": "PVC Usage in % (except local storage classes)",
   "type": "timeseries",
   "description": "This graph does not show any localstorage-related information due to incorrectly calculating the occupied space on localstorage disks",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (namespace, controller) (\n  max by (namespace, controller, persistentvolumeclaim)\n  (\n    sum by (namespace, persistentvolumeclaim) (\n        max_over_time(kubelet_volume_stats_capacity_bytes{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__rate_interval]) - max_over_time(kubelet_volume_stats_available_bytes{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__rate_interval])\n    ) \n\n    * max by (namespace, persistentvolumeclaim) (\n      label_replace(\n        max_over_time(kube_persistentvolumeclaim_info{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval]),\n        \"persistentvolume\", \"$1\", \"volumename\", \"(.*)\")\n      + on (persistentvolume) group_left() max by (persistentvolume) (kube_persistentvolume_is_local{source=\"deckhouse\"} == 0)\n    )\n\n        * on (namespace, persistentvolumeclaim) group_left(pod) \n    max by (namespace, persistentvolumeclaim, pod) (\n         max_over_time(kube_pod_spec_volumes_persistentvolumeclaims_info{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])\n    ) \n\n       * on (namespace, pod) group_left(controller)\n      kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=~\"$controller\"} \n  )\n)\n/\nsum by (namespace, controller) (\n  max by (namespace, controller, persistentvolumeclaim)\n  (\n    sum by (namespace, persistentvolumeclaim) (\n        max_over_time(kubelet_volume_stats_capacity_bytes{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__rate_interval])\n    ) \n\n    * max by (namespace, persistentvolumeclaim) (\n      label_replace(\n        max_over_time(kube_persistentvolumeclaim_info{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval]),\n        \"persistentvolume\", \"$1\", \"volumename\", \"(.*)\")\n      + on (persistentvolume) group_left() max by (persistentvolume) (kube_persistentvolume_is_local{source=\"deckhouse\"} == 0)\n    )\n\n        * on (namespace, persistentvolumeclaim) group_left(pod) \n    max by (namespace, persistentvolumeclaim, pod) (\n         max_over_time(kube_pod_spec_volumes_persistentvolumeclaims_info{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])\n    ) \n\n       * on (namespace, pod) group_left(controller)\n      kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=~\"$controller\"} \n  )\n)",
     "legendFormat": "Usage {{ controller }}"
    }
   ]
  },
  {
   "title": "PVC Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overview",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (persistentvolumeclaim, storageclass) (\n  max by (namespace, persistentvolumeclaim) (\n    max by (namespace, persistentvolumeclaim, pod) (\n      max_over_time(kube_pod_spec_volumes_persistentvolumeclaims_info{source=\"deckhouse\", namespace=\"$namespace\"}[$__range])\n    ) \n    * on (namespace, pod) group_left(controller)\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=~\"$controller\"}\n  )\n* on (namespace, persistentvolumeclaim) group_right() kube_persistentvolumeclaim_info{source=\"deckhouse\", namespace=\"$namespace\"})",
       "legendFormat": "Name, StorageClass"
      },
      {
       "expr": "max by (persistentvolumeclaim) (\n  max by (namespace, persistentvolumeclaim) (\n    max by (namespace, persistentvolumeclaim, pod) (\n      max_over_time(kube_pod_spec_volumes_persistentvolumeclaims_info{source=\"deckhouse\", namespace=\"$namespace\"}[$__range])\n    ) \n    * on (namespace, pod) group_left(controller)\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=~\"$controller\"}\n  )\n* on (namespace, persistentvolumeclaim) group_right() kube_persistentvolumeclaim_resource_requests_storage_bytes{source=\"deckhouse\", namespace=\"$namespace\"})",
       "legendFormat": "Requested (pvc)"
      },
      {
       "expr": "max by (persistentvolumeclaim) (\n  max by (namespace, persistentvolumeclaim) (\n    max by (namespace, persistentvolumeclaim, pod) (\n      max_over_time(kube_pod_spec_volumes_persistentvolumeclaims_info{source=\"deckhouse\", namespace=\"$namespace\"}[$__range])\n    ) \n    * on (namespace, pod) group_left(controller)\n    kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=~\"$controller\"}\n  )\n)\n* on (persistentvolumeclaim) group_right()\n(\nmax by (persistentvolumeclaim) (\n  max by (persistentvolume) (max_over_time(kube_persistentvolume_capacity_bytes{source=\"deckhouse\"}[$__range])) \n  * on (persistentvolume) group_right() \n  max by (persistentvolume, persistentvolumeclaim) (\n    label_replace(\n      max_over_time(kube_persistentvolumeclaim_info{source=\"deckhouse\", namespace=\"$namespace\"}[$__range]),\n      \"persistentvolume\", \"$1\", \"volumename\", \"(.*)\")\n  )\n)\n)",
       "legendFormat": "Provisioned (pv)"
      },
      {
       "expr": "max by (persistentvolumeclaim) (\n  max_over_time(kubelet_volume_stats_capacity_bytes{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__range])\n)",
       "legendFormat": "Capacity (real)"
      },
      {
       "expr": "max by (persistentvolumeclaim) (\n  max_over_time(kubelet_volume_stats_capacity_bytes{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__range]) - max_over_time(kubelet_volume_stats_available_bytes{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__range])\n)",
       "legendFormat": "used bytes"
      },
      {
       "expr": "max by (persistentvolumeclaim) (\n  max_over_time(kubelet_volume_stats_inodes_used{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__range])\n)",
       "legendFormat": "used inodes"
      },
      {
       "expr": "max by (persistentvolumeclaim) (\n  (max_over_time(kubelet_volume_stats_capacity_bytes{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__range]) - max_over_time(kubelet_volume_stats_available_bytes{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__range]))\n  / \n  max_over_time(kubelet_volume_stats_capacity_bytes{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__range])\n)",
       "legendFormat": "used bytes %"
      },
      {
       "expr": "max by (persistentvolumeclaim) (\n  max_over_time(kubelet_volume_stats_inodes_used{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__range]) \n  / \n  max_over_time(kubelet_volume_stats_inodes{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\"}[$__range])\n)",
       "legendFormat": "used inodes %"
      },
      {
       "expr": "sum by (persistentvolumeclaim, controller) (\n  max by (namespace, persistentvolumeclaim, pod) (\n    max_over_time(kube_pod_spec_volumes_persistentvolumeclaims_info{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])\n  ) \n  * on (namespace, pod) group_left(controller)\n  kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=~\"$controller\"} \n)",
       "legendFormat": "used by controller"
      }
     ]
    },
    {
     "title": "$persistentvolumeclaim",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 107 },
     "repeat": "persistentvolumeclaim",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(max by (persistentvolumeclaim) (\n  max by (namespace, persistentvolumeclaim) (\n    max by (namespace, persistentvolumeclaim, pod) (\n      max_over_time(kube_pod_spec_volumes_persistentvolumeclaims_info{source=\"deckhouse\", namespace=\"$namespace\"}[$__range])\n    ) \n    * on (namespace, pod) group_left(controller)\n    max(kube_controller_pod{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", controller=~\"$controller\"}) by(namespace, pod)\n  )\n)\n* on (persistentvolumeclaim) group_right()\nmax by (persistentvolumeclaim) (\n  max_over_time(kube_persistentvolume_capacity_bytes{source=\"deckhouse\"}[$__rate_interval]) \n  * on (persistentvolume) group_right() \n  (\n    label_replace(\n      max_over_time(kube_persistentvolumeclaim_info{source=\"deckhouse\", namespace=\"$namespace\", persistentvolumeclaim=~\"$persistentvolumeclaim\"}[$__rate_interval]),\n      \"persistentvolume\", \"$1\", \"volumename\", \"(.*)\")\n  )\n))",
       "legendFormat": "Provisioned"
      },
      {
       "expr": "sum(max by (persistentvolumeclaim) (\n  max_over_time(kubelet_volume_stats_capacity_bytes{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", persistentvolumeclaim=\"$persistentvolumeclaim\"}[$__rate_interval])\n))",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum(max by (persistentvolumeclaim) (\n  max_over_time(kubelet_volume_stats_capacity_bytes{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", persistentvolumeclaim=\"$persistentvolumeclaim\"}[$__rate_interval]) - max_over_time(kubelet_volume_stats_available_bytes{source=\"deckhouse\", node=~\"$node\", namespace=\"$namespace\", persistentvolumeclaim=\"$persistentvolumeclaim\"}[$__rate_interval])\n))",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  }
 ]
}