{
 "title": "Deckhouse-fix",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Heartbeat",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ceil(max by (job) (increase(deckhouse_live_ticks[1m]) > 5))^0",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Main queue length",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "deckhouse_tasks_queue_length{queue=\"main\"}"
    }
   ]
  },
  {
   "title": "Last startup converge duration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "deckhouse_convergence_seconds{activation=\"OperatorStartup\"}"
    }
   ]
  },
  { "title": "Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Queue length",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (queue) (deckhouse_tasks_queue_length{queue!~\"main|main-subqueue.*\"})"
    }
   ]
  },
  {
   "title": "Queue rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(deckhouse_tasks_queue_length[$__rate_interval]) > 0",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Snapshots objects",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum by (hook, binding) (deckhouse_kube_snapshot_objects)",
       "legendFormat": "{{ hook }} - {{ binding}}"
      }
     ]
    },
    {
     "title": "Snapshots size",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (hook, binding) (deckhouse_kube_snapshot_bytes)",
       "legendFormat": "{{ hook }} - {{ binding }}"
      }
     ]
    }
   ]
  },
  { "title": "Go process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total CPU time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"deckhouse\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"deckhouse\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"deckhouse\"}",
     "legendFormat": "{{pod}} - resident"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"deckhouse\"}",
     "legendFormat": "{{pod}} - virtual"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"deckhouse\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Opened file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"deckhouse\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Object allocations rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=\"deckhouse\"}[$__rate_interval])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max by (job, quantile) (go_gc_duration_seconds{job=\"deckhouse\"})",
     "legendFormat": "Quantile - {{ quantile }}"
    }
   ]
  },
  { "title": "Frequency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Events frequency by Kind",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (kind) (rate(deckhouse_kube_event_duration_seconds_count[$__rate_interval])) > 0",
     "legendFormat": " {{ kind }}"
    }
   ]
  },
  {
   "title": "Hook run frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (hook) (rate(deckhouse_module_hook_run_seconds_count[$__rate_interval])) > 0",
     "legendFormat": " {{ hook }}"
    },
    {
     "expr": "sum by (hook) (rate(deckhouse_glob_hook_run_seconds_count[$__rate_interval])) > 0"
    }
   ]
  },
  {
   "title": "JQ Filter frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (hook, binding) (rate(deckhouse_kube_jq_filter_duration_seconds_count[$__rate_interval])) > 0",
     "legendFormat": "{{ hook }} - {{ binding }}"
    }
   ]
  },
  {
   "title": "Helm run frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (module) (rate(deckhouse_helm_operation_seconds_count[$__rate_interval])) > 0",
     "legendFormat": "{{ module }}"
    }
   ]
  },
  {
   "title": "Kubernetes client requests frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(sum by (module) (increase(deckhouse_kubernetes_client_request_result_total[$__rate_interval]))) > 0",
     "legendFormat": "{{ module }}"
    }
   ]
  },
  {
   "title": "Operator startup duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Global hooks duration",
     "type": "table",
     "description": "5 top global hooks that have lognest duration on startup",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5, deckhouse_global_hook_run_seconds_sum{activation=\"OperatorStartup\"} / deckhouse_global_hook_run_seconds_count{activation=\"OperatorStartup\"})",
       "legendFormat": "{{module}}"
      }
     ]
    },
    {
     "title": "Module hooks duration",
     "type": "table",
     "description": "5 top module hooks that have lognest duration on startup",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5, deckhouse_module_hook_run_seconds_sum{activation=\"OperatorStartup\"} / deckhouse_module_hook_run_seconds_count{activation=\"OperatorStartup\"})",
       "legendFormat": "{{module}}"
      }
     ]
    },
    {
     "title": "Helm template duration",
     "type": "table",
     "description": "5 top global hooks that have longest helm render duration on startup",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5, deckhouse_helm_operation_seconds_sum{activation=\"OperatorStartup\",operation=\"template\"} / deckhouse_helm_operation_seconds_count{activation=\"OperatorStartup\",operation=\"template\"})"
      }
     ]
    },
    {
     "title": "Helm check-upgrade duration",
     "type": "table",
     "description": "5 top global hooks that have the longest helm check duration on startup",
     "gridPos": { "h": 7, "w": 6, "x": 5, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5, deckhouse_helm_operation_seconds_sum{activation=\"OperatorStartup\",operation=\"check-upgrade\"} / deckhouse_helm_operation_seconds_count{activation=\"OperatorStartup\",operation=\"check-upgrade\"})"
      }
     ]
    },
    {
     "title": "Helm upgrade duration",
     "type": "table",
     "description": "5 top global hooks that have the longest helm upgrade duration on startup",
     "gridPos": { "h": 7, "w": 6, "x": 11, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5, deckhouse_helm_operation_seconds_sum{activation=\"OperatorStartup\",operation=\"upgrade\"} / deckhouse_helm_operation_seconds_count{activation=\"OperatorStartup\",operation=\"upgrade\"})"
      }
     ]
    },
    {
     "title": "Helm module duration",
     "type": "table",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5, deckhouse_module_helm_seconds_sum{activation=\"OperatorStartup\"} / deckhouse_module_helm_seconds_count{activation=\"OperatorStartup\"})"
      }
     ]
    }
   ]
  }
 ]
}