#!/bin/bash

# Copyright 2025 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# 	 http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /deckhouse/shell_lib.sh
# The Registry module runs only in Deckhouse-managed clusters.
# It is not supported in cloud-managed environments like AWS, Yandex Cloud, etc.
# Enablement is based on the presence of global.clusterConfiguration.
# Its absence means the cluster is externally managed and the module will be disabled.
# This check is similar to the one performed during the startup of the control-plane-manager.
function __main__() {
  if values::has global.clusterConfiguration ; then
    echo "true" > "$MODULE_ENABLED_RESULT"
  else
    echo "false" > "$MODULE_ENABLED_RESULT"
  fi
}

enabled::run "$@"
