{{- if and
  (include "istioSupportsAmbient" .)
  (.Values.istio.ambient.enabled)
  (.Values.istio.dataPlane.waypoint.enabled)
}}
---
apiVersion: v1
kind: Service
metadata:
  name: waypoint
  namespace: d8-{{ .Chart.Name }}
  annotations:
    networking.istio.io/traffic-distribution: PreferClose
  {{- include "helm_lib_module_labels" (list . (dict
    "app" "waypoint"
    "gateway.istio.io/managed" "istio.io-mesh-controller"
    "gateway.networking.k8s.io/gateway-name" "waypoint"
    "istio.io/rev" (include "istioGlobalRevision" .)
    "istio.io/waypoint-for" "all"
    "topology.istio.io/network" (include "istioNetworkName" .)
  )) | nindent 2 }}
spec:
  ports:
  - appProtocol: tcp
    name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
  - appProtocol: hbone
    name: mesh
    port: 15008
    protocol: TCP
    targetPort: 15008
  selector:
    app: waypoint
    gateway.networking.k8s.io/gateway-name: waypoint
  type: ClusterIP
{{- end }}
