#!/bin/bash

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  echo '
{
  "beforeHelm": 20,
  "schedule": [
    {
      "crontab": "53 * * * *"
    }
  ]
}'
}

function __main__() {
  AWS_ACCESS_KEY_ID="$(values::get --required cloudProviderAws.providerAccessKeyId)"
  export AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY="$(values::get --required cloudProviderAws.providerSecretAccessKey)"
  export AWS_SECRET_ACCESS_KEY
  AWS_REGION="$(values::get --required cloudProviderAws.region)"
  export AWS_REGION
  CLUSTER_ID="$(values::get --required cloudProviderAws.keyName)"
  export CLUSTER_ID

  result="$(deckhouse-controller helper aws map-zone-to-subnets)"

  values::set cloudProviderAws.internal.zoneToSubnetIdMap "$result"

  if ! values::has --config cloudProviderAws.zones ; then
    values::set cloudProviderAws.zones "$(echo "$result" | jq -r '. | keys')"
  fi
}

hook::run "$@"
