#!/bin/bash

# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: aws_instance_classes
      group: main
      keepFullObjectsInMemory: false
      apiVersion: deckhouse.io/v1
      kind: AWSInstanceClass
      jqFilter: |
        {
          "name": (.metadata.name),
          "hasSpotPrice": (.spec | has("spotPrice"))
        }
EOF
}

function __main__() {
  readarray -t -d $'\n' unpatched_ics < <(context::jq -rc '.snapshots.aws_instance_classes[].filterResult | select(.hasSpotPrice) | .name')

  if [[ ${#unpatched_ics[@]} == "0" ]]; then
    return 0
  fi

  for ic_name in "${unpatched_ics[@]}" ; do
    kubernetes::patch_jq "" "awsinstanceclasses/$ic_name" "del(.spec.spotPrice) | .spec.spot = true"
  done
}

hook::run "$@"
