#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: kpds
      apiVersion: apps/v1
      kind: DaemonSet
      includeSnapshotsFrom: ["kpds"]
      watchEvent: ["Added", "Modified"]
      namespace:
        nameSelector:
          matchNames: [kube-system]
      nameSelector:
        matchNames: [kube-proxy]
      jqFilter: '.spec.template.spec.tolerations'
EOF
}

function __on_kubernetes::kpds() {
  # Policy: kube-proxy must work on every node regardles of taints.
  #
  # Even if some node is dedicated to special task we still need network and services working.

  if context::has snapshots.kpds.0; then
    kubernetes::patch_jq kube-system daemonset/kube-proxy '. | .spec.template.spec.tolerations = [{"operator":"Exists"}]'
  fi
}

hook::run $@
