{{- range $bgpPeer := .Values.metallb.internal.bgpPeers }}
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: {{ $bgpPeer.name }}
  namespace: d8-{{ $.Chart.Name }}
  {{- include "helm_lib_module_labels" (list $ (dict "app" "speaker")) | nindent 2 }}
spec:
  myASN: {{ $bgpPeer.myASN }}
  peerASN: {{ $bgpPeer.peerASN }}
  peerAddress: {{ $bgpPeer.peerAddress }}
  {{- if $bgpPeer.routerID }}
  routerID: {{ $bgpPeer.routerID }}
  {{- end }}
  {{- if $bgpPeer.peerPort }}
  peerPort: {{ $bgpPeer.peerPort }}
  {{- end }}
  {{- if $bgpPeer.sourceAddress }}
  sourceAddress: {{ $bgpPeer.sourceAddress }}
  {{- end }}
  {{- if $bgpPeer.holdTime }}
  holdTime: {{ $bgpPeer.holdTime }}
  {{- end }}
  {{- if $bgpPeer.passwordSecret }}
  passwordSecret:
    name: {{ $bgpPeer.passwordSecret }}
  {{- end }}
  {{- if $bgpPeer.bfdProfile }}
  bfdProfile: {{ $bgpPeer.bfdProfile }}
  {{- end }}
  {{- if $bgpPeer.nodeSelectors }}
  nodeSelectors:
  {{- $bgpPeer.nodeSelectors | toYaml | nindent 2 }}
  {{- end }}
{{- end }}
