#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    onStartup: 10
EOF
}

function __main__() {
  # TODO remove this hook as soon as all clusters will be adopted
  # Set labels and annotations for Helm
  kubernetes::patch_jq d8-system deployment/deckhouse ".metadata.labels += {\"app.kubernetes.io/managed-by\":\"Helm\"}"
  kubernetes::patch_jq d8-system serviceaccount/deckhouse ".metadata.labels += {\"app.kubernetes.io/managed-by\":\"Helm\"}"
  kubernetes::patch_jq d8-system deployment/deckhouse ".metadata.annotations += {\"meta.helm.sh/release-name\":\"deckhouse\", \"meta.helm.sh/release-namespace\":\"d8-system\"}"
  kubernetes::patch_jq d8-system serviceaccount/deckhouse ".metadata.annotations += {\"meta.helm.sh/release-name\":\"deckhouse\", \"meta.helm.sh/release-namespace\":\"d8-system\"}"
}

hook::run "$@"
