#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    afterDeleteHelm: 10
EOF
}

function __main__() {
  kubectl get secret --all-namespaces | grep "istio.io/key-and-cert" |  while read -r entry; do
    ns=$(echo $entry | awk '{print $1}');
    name=$(echo $entry | awk '{print $2}');
    kubectl delete secret $name -n $ns;
  done
}

hook::run $@
