#!/bin/bash

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  jo -p afterDeleteHelm=10
}

function __main__() {
  kubectl get secret --all-namespaces | grep "istio.io/key-and-cert" |  while read -r entry; do
    ns=$(echo $entry | awk '{print $1}');
    name=$(echo $entry | awk '{print $2}');
    kubectl delete secret $name -n $ns;
  done
}

hook::run $@
