#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 10
EOF
}

function __main__() {
  kubernetes::delete_if_exists "" clusterrolebinding/kubeadm:node-proxier
  kubernetes::delete_if_exists kube-system role/kube-proxy
  kubernetes::delete_if_exists kube-system rolebinding/kube-proxy
  kubernetes::delete_if_exists kube-system serviceaccount/kube-proxy
  kubernetes::delete_if_exists kube-system configmap/kube-proxy
  kubernetes::delete_if_exists kube-system daemonset/kube-proxy
}

hook::run "$@"
