#!/bin/bash
# Copyright 2022 Flant JSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE

set -Eeo pipefail
packages_to_install=""
package_container_selinux="container-selinux"
package_file_container_selinux="${package_container_selinux}.x86_64.rpm"
rpm_name_container_selinux="$(rpm -qip ${package_file_container_selinux} 2>/dev/null | grep Name | awk '{print $3}')"
rpm_version_container_selinux="$(rpm -qip ${package_file_container_selinux} 2>/dev/null | grep Version | awk '{print $3}')"

if ! rpm --quiet -q "${rpm_name_container_selinux}-${rpm_version_container_selinux}"; then
  packages_to_install="${packages_to_install} ${package_file_container_selinux}"
else
  echo "RPM ${package_file_container_selinux} already installed."
fi

package_containerd_io="containerd.io"
package_file_containerd_io="${package_containerd_io}.x86_64.rpm"
rpm_name_containerd_io="$(rpm -qip ${package_file_containerd_io} 2>/dev/null | grep Name | awk '{print $3}')"
rpm_version_containerd_io="$(rpm -qip ${package_file_containerd_io} 2>/dev/null | grep Version | awk '{print $3}')"

if ! rpm --quiet -q "${rpm_name_containerd_io}-${rpm_version_containerd_io}"; then
  packages_to_install="${packages_to_install} ${package_file_containerd_io}"
else
  echo "RPM ${package_file_containerd_io} already installed."
fi

if [[ -n "${packages_to_install}" ]]; then
  rpm -U ${packages_to_install}
fi
yum versionlock add ${package_container_selinux} ${package_containerd_io}
