#!/bin/bash

source /antiopa/shell_lib.sh

function __main__() {
  if values::array_has global.enabledModules "cert-manager-crd" ; then
    echo "true" > $MODULE_ENABLED_RESULT
  else
    echo "false" > $MODULE_ENABLED_RESULT
  fi
}

hook::run $@
