#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 10
EOF
}

function __main__() {
  if values::is_true global.clusterIsBootstrapped ; then
    fltr='.spec.template.spec.dnsPolicy = "ClusterFirstWithHostNet"'
    kubernetes::patch_jq d8-system deployment/deckhouse "$fltr"
  fi
}

hook::run "$@"
