#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p beforeHelm=30
}

function __main__() {
  fltr='.'

  fltr=$fltr' | .spec.template.spec.dnsPolicy = "ClusterFirstWithHostNet"'
  fltr=$fltr' | .spec.template.spec.hostNetwork = true'
  fltr=$fltr' | .spec.strategy = {"rollingUpdate":{"maxSurge":0,"maxUnavailable":1}, "type":"RollingUpdate"}'

  kubectl::jq_patch antiopa deploy/antiopa "$fltr"
}

hook::run "$@"
