#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 0
EOF
}

function __main__() {
  log_level=$(values::get --required deckhouse.logLevel)

  if [[ "$log_level" != "Debug" && "$log_level" != "Info" && "$log_level" != "Error" ]] ; then
    >&2 echo "Bad deckhouse.logLevel value \"$log_level\", should be Debug, Info or Error."
    return 1
  fi

  kubernetes::patch_jq d8-system deployment/deckhouse '.spec.template.spec.containers[0].env |= (. | map(if .name == "RLOG_LOG_LEVEL" then .value = "'${log_level^^}'" else . end))'
}

hook::run $@
