#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    onStartup: 10
EOF
}

function __main__() {
  if [[ $(values::get --config deckhouse.releaseChannel) == "RC" ]]; then
    values::set --config deckhouse.releaseChannel EarlyAccess
  fi
}

hook::run $@
