#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    onStartup: 10
EOF
}

function __main__() {
  if kubectl -n d8-monitoring get secret deckhouse-registry >/dev/null 2>&1 ; then
    if [[ $(kubectl -n d8-monitoring get secret deckhouse-registry -o json | jq -rc '.metadata.annotations."meta.helm.sh/release-name"') == "prometheus" ]] ; then
      kubectl annotate -n d8-monitoring secret deckhouse-registry meta.helm.sh/release-name=deckhouse --overwrite=true
      kubectl annotate -n d8-monitoring secret deckhouse-registry helm.sh/resource-policy=keep --overwrite=true
    fi
  fi
}

hook::run $@
