#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  jo -p beforeHelm=30
}

function __main__() {
  # Миграция 2019-09-15: https://github.com/deckhouse/deckhouse/merge_requests/1133

  fltr='.'
  # Простановка nodeSelector и tolerations
  fltr=$fltr' | del(.spec.template.spec.affinity)'
  fltr=$fltr' | .spec.template.spec.nodeSelector = {"node-role.kubernetes.io/master":""}'
  fltr=$fltr' | .spec.template.spec.tolerations = [{"operator":"Exists"}]'

  # Переводим на hostNetwork
  fltr=$fltr' | .spec.template.spec.dnsPolicy = "ClusterFirstWithHostNet"'
  fltr=$fltr' | .spec.template.spec.hostNetwork = true'

  # Меняем strategy на Recreate
  fltr=$fltr' | if (.spec.strategy.type == "RollingUpdate") then del (.spec.strategy.rollingUpdate) else . end | .spec.strategy.type = "Recreate"'

  # Добавляем порт для экспорта метрик
  fltr=$fltr' | .spec.template.spec.containers[0].ports[0].containerPort = 9650'

  # Проставляем переменные окружения необходимые для нового addon-operator
  fltr=$fltr' | if (any(.spec.template.spec.containers[0].env[]; .name == "ADDON_OPERATOR_NAMESPACE") | not) then (.spec.template.spec.containers[0].env += [{"name": "ADDON_OPERATOR_NAMESPACE", "valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}]) else . end'
  fltr=$fltr' | if any(.spec.template.spec.containers[0].env[]; .name == "ADDON_OPERATOR_NAMESPACE" and (.valueFrom.fieldRef.fieldPath == "metadata.namespace" | not)) then .spec.template.spec.containers[0].env |= (map(select(.name != "ADDON_OPERATOR_NAMESPACE")) | . + [{"name": "ADDON_OPERATOR_NAMESPACE", "valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}]) else . end'
  fltr=$fltr' | if (any(.spec.template.spec.containers[0].env[]; .name == "ADDON_OPERATOR_PROMETHEUS_METRICS_PREFIX") | not) then (.spec.template.spec.containers[0].env += [{"name": "ADDON_OPERATOR_PROMETHEUS_METRICS_PREFIX", "value": "antiopa_"}]) else . end'
  fltr=$fltr' | if (any(.spec.template.spec.containers[0].env[]; .name == "ADDON_OPERATOR_CONFIG_MAP") | not) then (.spec.template.spec.containers[0].env += [{"name": "ADDON_OPERATOR_CONFIG_MAP", "value": "antiopa"}]) else . end'
  fltr=$fltr' | if (any(.spec.template.spec.containers[0].env[]; .name == "ADDON_OPERATOR_LISTEN_ADDRESS") | not) then (.spec.template.spec.containers[0].env += [{"name": "ADDON_OPERATOR_LISTEN_ADDRESS", "valueFrom":{"fieldRef":{"fieldPath":"status.podIP"}}}]) else . end'
  fltr=$fltr' | if (any(.spec.template.spec.containers[0].env[]; .name == "DECKHOUSE_POD") | not) then (.spec.template.spec.containers[0].env += [{"name": "DECKHOUSE_POD", "valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}}]) else . end'

  kubectl::jq_patch d8-system deploy/deckhouse "$fltr"
}

hook::run "$@"
