#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 10
EOF
}

function __main__() {
  # По новой политике мы убираем все лимиты для служебных комонентов
  #
  # Важно! Изменять необходимо синхронно и здесь и в install.sh!
  #
  fltr='.'
  fltr=$fltr' | .spec.template.spec.containers[0].resources.requests = {"cpu":"50m","memory":"512Mi"}'
  if kubectl -n d8-system get deploy deckhouse -o json | jq -e '.spec.template.spec.containers[0].resources.limits' >/dev/null ; then
    fltr=$fltr' | .spec.template.spec.containers[0].resources.limits = {}'
  fi
  kubernetes::patch_jq d8-system deployment/deckhouse "$fltr"
}

hook::run $@
