#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  jo -p beforeHelm=10
}

function __main__() {
  # По новой политике мы убираем все лимиты для служебных комонентов
  #
  # Важно! Изменять необходимо синхронно и здесь и в install.sh!
  #
  fltr='.'
  fltr=$fltr' | .spec.template.spec.containers[0].resources.requests = {"cpu":"50m","memory":"512Mi"}'
  if kubectl -n d8-system get deploy deckhouse -o json | jq -e '.spec.template.spec.containers[0].resources.limits' >/dev/null ; then
    fltr=$fltr' | .spec.template.spec.containers[0].resources.limits = {}'
  fi
  kubectl::jq_patch d8-system deploy/deckhouse "$fltr"
}

hook::run $@
