#!/bin/bash

### Костыль 2019-10-15
# Так как deckhouse течет, то нам необходимо его рестартить раз в 2 часа.
# Этот костыль временный и вследующем релизе будет удален.

source /deckhouse/shell_lib.sh

function __config__() {
  echo '
{
  "schedule": [
    {
      "crontab": "0 */2 * * *"
    }
  ]
}'
}

function __main__() {
  # Рестартим процесс deckhouse/antiopa
  kill 1
}

hook::run "$@"
