#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  jo -p afterHelm=10
}

function __main__() {
  cluster_version=$(values::get global.discovery.clusterVersion)
  if [ "$(semver compare $cluster_version 1.11.0)" -ne "-1" ] ; then
    # Необходимо проставить priorityClassName антиопе
    fltr='.'
    fltr=$fltr' | .spec.template.spec.priorityClassName = "cluster-medium"'
    kubectl::jq_patch d8-system deploy/deckhouse "$fltr"
  fi
}

hook::run $@
