#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 10
EOF
}

function __main__() {
  # TODO Remove this hook after adding OpenAPI validations
  deckhouse_bundle=$(values::get deckhouse.bundle)
  if [[ "$deckhouse_bundle" != "Default" ]] && [[ "$deckhouse_bundle" != "Minimal" ]] && [[ "$deckhouse_bundle" != "Managed" ]]; then
    echo "Deckhouse bundle \"$deckhouse_bundle\" doesn't exists."
    return 1
  fi

  log_level=$(values::get --required deckhouse.logLevel)
  if [[ "$log_level" != "Debug" && "$log_level" != "Info" && "$log_level" != "Error" ]] ; then
    >&2 echo "Bad deckhouse.logLevel value \"$log_level\", should be Debug, Info or Error."
    return 1
  fi
}

hook::run "$@"
