properties:
  deschedulingInterval:
    description: |
      Интервал между запусками цикла перераспределения подов.

      Поддерживаются следующие значения:

      - `Frequent` — запуск каждые 5 минут. Подходит для кластеров, где важно быстрее перераспределять поды;
      - `Moderate` — запуск каждые 15 минут (по умолчанию);
      - `Rare` — запуск каждые 30 минут. Подходит для кластеров, где важно минимизировать количество перераспределений подов.
  logLevel:
    description: |
      Уровень логирования descheduler.

      Каждый уровень включает сообщения менее подробных уровней. Некоторые информационные сообщения и предупреждения, например сообщения при запуске, записываются в лог при любом уровне.

      Поддерживаются следующие значения:

      - `Error` — только ошибки;
      - `Warning` — предупреждения о конфигурации, вытесненные поды и итоги циклов перераспределения (по умолчанию);
      - `Info` — ход каждого цикла перераспределения, например обрабатываемые узлы;
      - `Debug` — подробная информация о решениях по вытеснению, например почему под не был вытеснен, а также каждый запрос к Kubernetes API. Создаёт очень большой объём логов, поэтому используйте его только для диагностики проблем.
