---
apiVersion: deckhouse.io/v1alpha1
kind: ValidationWebhook
metadata:
  name: admission-policy-engine-security-policy
  {{- include "helm_lib_module_labels" (list . (dict "app" "webhook-handler")) | nindent 2 }}
validationObject:
  name: securitypolicies.deckhouse.io
  group: main
  rules:
  - apiGroups:   ["deckhouse.io"]
    apiVersions: ["*"]
    operations:  ["CREATE", "UPDATE"]
    resources:   ["securitypolicies"]
    scope:       "Cluster"
context:
  - name: policies
    kubernetes:
      apiVersion: deckhouse.io/v1alpha1
      kind: SecurityPolicy
      jqFilter: |
        {
          "name": .metadata.name,
          "references": [.spec.policies.verifyImageSignatures[]?.reference]
        }
handler:
  python: |
    def validate(ctx: DotMap) -> tuple[Optional[str], bool]:
        error = check_verify_image_signatures(ctx)
        if error is not None:
            return error, False

        return None, True


    # check that all image references don't have intersection, it's required by ratify
    # https://ratify.dev/docs/plugins/verifier/cosign/#scopes
    def check_verify_image_signatures(ctx: DotMap) -> Optional[str]:
        references = [item.reference for item in ctx.review.request.object.spec.policies.verifyImageSignatures]
        if len(references) == 0:
            return None

        existing_references = [obj.filterResult for obj in ctx.snapshots.policies if obj.filterResult.references is not None]

        for exobj in existing_references:
            # On update skip self intersection
            if exobj.name == ctx.review.request.object.metadata.name:
                continue
            for exref in exobj.references:
                for ref in references:
                    ref_clean = ref.replace("*", '').strip()
                    exref_clean = exref.replace("*", '').strip()
                    if ref_clean == "" or exref_clean == "":
                        # Skip `*` references, they are treat as default
                        continue
                    min_length = min(len(ref_clean), len(exref_clean))
                    # Check intersection but ignore fully equal references
                    if ref_clean[:min_length] == exref_clean[:min_length] and ref_clean != exref_clean:
                        return f"ImageReference \"{ref}\" has intersection in the SecurityPolicy \"{exobj.name}\""

        return None
