#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  yq r -j - << EOF
   configVersion: v1
   kubernetes:
   - name: cluster-autoscaler
     apiVersion: apps/v1
     kind: Deployment
     watchEvent: [Added, Modified]
     namespace:
       nameSelector:
         matchNames: [kube-system]
     nameSelector:
       matchNames: [cluster-autoscaler]
     jqFilter: '[.spec.template.spec.containers[0].resources]'
EOF
}

function __on_kubernetes::cluster-autoscaler::synchronization() {
  if context::has objects.0; then
    kubernetes::patch_jq kube-system deployment/cluster-autoscaler 'del(.spec.template.spec.containers[0].resources.limits)'
  fi
}

function __on_kubernetes::cluster-autoscaler::added_or_modified() {
  kubernetes::patch_jq kube-system deployment/cluster-autoscaler 'del(.spec.template.spec.containers[0].resources.limits)'
}

hook::run $@
