#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p onStartup=350
}

function __main__() {
  # flannel есть только в Manual кластерах
  cluster_type=$(values::get --required global.discovery.clusterType)
  [[ "$cluster_type" != "Manual" ]] && return 0

  # Проверяем, что у flannel выставлены лимиты
  if kubectl -n kube-system get ds kube-flannel-ds -o json | jq -e '.spec.template.spec.containers[0].resources.limits' > /dev/null ; then
    fltr='.'
    fltr=$fltr' | .spec.template.spec.containers[0].resources.limits = {}'
    kubectl::jq_patch "kube-system" "ds/kube-flannel-ds" "$fltr"
  fi
}

hook::run $@

