{
 "title": "Node controller metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "rest_client_requests_total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\nrate(\nrest_client_requests_total{\nnamespace=\"d8-cloud-instance-manager\",\njob=\"node-controller\"\n}[5m]\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_memstats_heap_alloc_bytes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{\n\npod=~\"node-controller.*\"\n\n} /1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "reconcile per second",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  rate(controller_runtime_reconcile_total{\n    namespace=\"d8-cloud-instance-manager\",\n    job=\"node-controller\"\n  }[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "workqueue depth",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  workqueue_depth{\n    namespace=\"d8-cloud-instance-manager\",\n    job=\"node-controller\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "reconcile duration p99",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (\n    rate(controller_runtime_reconcile_time_seconds_bucket{\n      namespace=\"d8-cloud-instance-manager\",\n      job=\"node-controller\"\n    }[1m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cache size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "objects" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\nnode_controller_cache_objects{\nnamespace=\"d8-cloud-instance-manager\",\njob=\"node-controller\"\n}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_memstats_heap_objects",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_objects{namespace=\"d8-cloud-instance-manager\", pod=~\"node-controller.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Num_of_goroutines",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_goroutines{namespace=\"d8-cloud-instance-manager\", pod=~\"node-controller.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process_resident_memory_bytes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{namespace=\"d8-cloud-instance-manager\", pod=~\"node-controller.*\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "erros coint",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  rate(controller_runtime_reconcile_errors_total{\n    namespace=\"d8-cloud-instance-manager\",\n    job=\"node-controller\"\n  }[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cache size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "objects" } },
   "targets": [
    {
     "expr": "sum by (kind, api_group)(\nnode_controller_cache_objects{\nnamespace=\"d8-cloud-instance-manager\",\njob=\"node-controller\"\n}\n)",
     "legendFormat": "{{api_group}}/{{kind}}"
    }
   ]
  },
  {
   "title": "rest_client_request_duration_seconds_bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(rest_client_request_duration_seconds_bucket{\n      job=\"kube-apiserver\",\n      host=\"node-controller-webhook.d8-cloud-instance-manager.svc:443\"\n    }[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_gc_duration_seconds p75",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(\n  go_gc_duration_seconds{\n    namespace=\"d8-cloud-instance-manager\",\n    pod=~\"node-controller.*\",\n    quantile=\"0.75\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconcile duration p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (controller, le) (\n    rate(controller_runtime_reconcile_time_seconds_bucket{\n      namespace=\"d8-cloud-instance-manager\",\n      job=\"node-controller\"\n    }[1m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconcile errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by (controller) (\n  rate(controller_runtime_reconcile_errors_total{\n    namespace=\"d8-cloud-instance-manager\",\n    job=\"node-controller\"\n  }[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconcile total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (controller) (\n  rate(controller_runtime_reconcile_total{\n    namespace=\"d8-cloud-instance-manager\",\n    job=\"node-controller\"\n  }[1m])\n)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Workqueue depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by (name) (\n  workqueue_depth{\n    namespace=\"d8-cloud-instance-manager\",\n    job=\"node-controller\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}