# Copyright 2020 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### Dockerfile for building a Debian buster image for testing

FROM debian:buster

ARG INSTALL_ARGS=
ARG REPO=buster

RUN echo deb http://deb.debian.org/debian buster-backports main >> /etc/apt/sources.list; \
    apt-get update; \
    apt-get -t ${REPO} -y --no-install-recommends install iptables

COPY iptables-wrapper-installer.sh /
COPY bin/iptables-wrapper /
RUN /iptables-wrapper-installer.sh ${INSTALL_ARGS}
COPY test/test.sh /
