# Copyright 2020 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### Dockerfile for building a Fedora 35 image for testing

FROM fedora:35

RUN dnf install -y iptables iptables-legacy iptables-nft
COPY iptables-wrapper-installer.sh /
COPY bin/iptables-wrapper /
RUN /iptables-wrapper-installer.sh
COPY test/test.sh /
