apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    heritage: deckhouse
    module: monitoring-kubernetes-control-plane
    rbac.deckhouse.io/aggregate-to-observability-as: manager
    rbac.deckhouse.io/kind: capability
    rbac.deckhouse.io/capability: "system-capability.monitoring-kubernetes-control-plane.edit"
    rbac.deckhouse.io/scope: system
    rbac.deckhouse.io/namespace: d8-monitoring
  name: d8:system-capability:monitoring-kubernetes-control-plane:edit
  annotations:
    en.meta.deckhouse.io/title: "Module monitoring-kubernetes-control-plane: edit configuration"
    ru.meta.deckhouse.io/title: "Модуль monitoring-kubernetes-control-plane: управление конфигурацией"
    en.meta.deckhouse.io/description: "Manage the monitoring-kubernetes-control-plane module configuration."
    ru.meta.deckhouse.io/description: "Управление конфигурацией модуля monitoring-kubernetes-control-plane."
rules:
- apiGroups:
  - deckhouse.io
  resourceNames:
  - monitoring-kubernetes-control-plane
  resources:
  - moduleconfigs
  verbs:
  - create
  - update
  - patch
  - delete
