{{- if and ($.Values.istio.enableAmbientMode) (eq (first $.Values.istio.internal.operatorVersionsToInstall) "1.25") }}
    {{- $versions := .Values.istio.internal.operatorVersionsToInstall }}
    {{- range $version := .Values.istio.internal.operatorVersionsToInstall }}
        {{- $versionInfo := get $.Values.istio.internal.versionMap $version }}
        {{ $imageSuffix := get $versionInfo "imageSuffix" }}
        {{- $revision := get $versionInfo "revision" }}
        {{- $fullVersion := get $versionInfo "fullVersion" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ztunnel
  namespace: d8-{{ $.Chart.Name }}
  {{- $baseLabels := include "helm_lib_module_labels" (list $ (dict "app" "ztunnel")) | fromYaml }}
  {{- $customLabels := dict 
      "app.kubernetes.io/name" "ztunnel"
      "app.kubernetes.io/instance" (printf "%s-ztunnel" $revision)
      "app.kubernetes.io/version" $fullVersion
      "app.kubernetes.io/part-of" "istio"
  }}
  {{- merge $baseLabels $customLabels | toYaml | nindent 4 }}
---
  {{- end }}
{{- end }}