#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  echo '
{
  "beforeHelm": 100
}'
}

function __main__() {
  if ! values::is_empty "$(values::get cloudProviderVsphere.internalSubnet)"; then
    subnet_regex="$(rgxg cidr "$(values::get cloudProviderVsphere.internalSubnet)")"
    values::set cloudProviderVsphere.internal.internalSubnetRegex "$subnet_regex"
  fi
}

hook::run "$@"
