#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 20
    schedule:
    - crontab: "53 * * * *"
      queue: /modules/$(module::name::kebab_case)
EOF
}

function __main__() {
  GOVC_URL="$(values::get --required cloudProviderVsphere.internal.server)"
  export GOVC_URL
  GOVC_USERNAME="$(values::get --required cloudProviderVsphere.internal.username)"
  export GOVC_USERNAME
  GOVC_PASSWORD="$(values::get --required cloudProviderVsphere.internal.password)"
  export GOVC_PASSWORD
  GOVC_INSECURE="$(values::get --required cloudProviderVsphere.internal.insecure)"
  export GOVC_INSECURE

  VSPHERE_REGION_TAG_NAME="$(values::get --required cloudProviderVsphere.internal.region)"
  export VSPHERE_REGION_TAG_NAME
  VSPHERE_REGION_TAG_CATEGORY_NAME="$(values::get --required cloudProviderVsphere.internal.regionTagCategory)"
  export VSPHERE_REGION_TAG_CATEGORY_NAME
  VSPHERE_ZONE_TAG_CATEGORY_NAME="$(values::get --required cloudProviderVsphere.internal.zoneTagCategory)"
  export VSPHERE_ZONE_TAG_CATEGORY_NAME

  if values::get --required cloudProviderVsphere.internal.datacenter >/dev/null 2>&1 ||
        values::get --required cloudProviderVsphere.internal.zones >/dev/null 2>&1 ||
        values::get --required cloudProviderVsphere.internal.datastores >/dev/null 2>&1 ; then
    result="$(timeout -s ABRT -k 5 30 deckhouse-controller helper vsphere get-zones-datastores)" || { echo 'vsphere-cli-helper exited by timeout, preserving old discovery information' && exit 0; }
    else
    result="$(timeout -s ABRT -k 5 30 deckhouse-controller helper vsphere get-zones-datastores)"
  fi

  datacenter="$(echo "$result" | jq -re '.datacenter')"
  datastores="$(echo "$result" | jq -re '.datastores')"
  zones="$(echo "$result" | jq -re '.zones')"

  values::set cloudProviderVsphere.internal.datacenter "$datacenter"
  values::set cloudProviderVsphere.internal.zones "$zones"
  values::set cloudProviderVsphere.internal.datastores "$datastores"
}

hook::run "$@"
