#!/bin/bash

### Миграция 2019-11-13: https://github.com/deckhouse/deckhouse/merge_requests/1377
# Удалить данный хук после выката MR'а

source /deckhouse/shell_lib.sh

function __config__() {
  jo -p beforeHelm=200
}

function __main__() {
  old_datastores="$(values::get cloudProviderVsphere.internal.datastores | jq -r 'map(.name)')"
  read -ra wrong_scs <<<$(kubectl get sc -o json | jq -r --argjson old_datastores "$old_datastores" '.items[] |
                                                select((.volumeBindingMode != "Immediate") and ([.metadata.name] | inside($old_datastores // []))) | .metadata.name')

  if (( ${#wrong_scs[@]} )); then
    kubectl delete sc "${wrong_scs[@]}"
  fi
}

hook::run "$@"
