#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
{
  "onKubernetesEvent": [
    {
      "kind": "Node"
    }
  ]
}
EOF
}

function __main__() {
  node_name=$(hook::context_jq -r '.[0].resourceName')
  node_json=$(kubectl get node "$node_name" -o json)
  if jq -re '.spec.taints | any(.key == "node.cloudprovider.kubernetes.io/uninitialized") | not' >/dev/null 2>&1 <<<"$node_json"; then
    if jq -re '.spec.providerID // "" | length == 0' >/dev/null 2>&1 <<<"$node_json"; then
      if jq -re '.metadata.labels."cloud-instance-manager.deckhouse.io/cloud-instance-group" | not' >/dev/null 2>&1 <<<"$node_json"; then
        kubectl patch node "$node_name" -p '{"spec":{"providerID": "static://"}}' >/dev/null 2>&1
      fi
    fi
  fi
}

hook::run "$@"
