#!/bin/bash
# Copyright 2024 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kubeletChainsRegex='(?m)^:(KUBE-IPTABLES-HINT|KUBE-KUBELET-CANARY)'
cmds="iptables iptables-save iptables-restore ip6tables ip6tables-save ip6tables-restore"

set -Eeo pipefail
mkdir -p /opt/deckhouse/bin
cp -f xtables-legacy-multi /opt/deckhouse/bin
cp -f xtables-nft-multi /opt/deckhouse/bin

IPTABLES_LEGACY_SAVE=$(/opt/deckhouse/bin/xtables-legacy-multi iptables-legacy-save)
if [[ ${IPTABLES_LEGACY_SAVE} =~ ${kubeletChainsRegex} ]]; then
  iptablesMode="/opt/deckhouse/bin/xtables-legacy-multi"
else
  iptablesMode="/opt/deckhouse/bin/xtables-nft-multi"
fi

for cmd in $cmds; do
  ln -sf $iptablesMode /opt/deckhouse/bin/$cmd
done
