- name: d8.l2-load-balancer.services
  rules:
    - alert: L2LoadBalancerIrrelevantServiceFound
      expr: max by (namespace, name) (d8_istio_irrelevant_service == 1)
      for: 5m
      labels:
        severity_level: "4"
        tier: application
      annotations:
        plk_markup_format: "markdown"
        plk_protocol_version: "1"
        plk_create_group_if_not_exists__istio_irrelevant_external_services: L2LoadBalancerIrrelevantServices,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes
        plk_grouped_by__istio_irrelevant_external_services: L2LoadBalancerIrrelevantServices,tier=~tier,prometheus=deckhouse,kubernetes=~kubernetes
        summary: Found service with irrelevant L2LoadBalancer name
        description: |
          There is service in the namespace: `{{$labels.namespace}}` with the name: `{{$labels.name}}` which has irrelevant L2LoadBalancer name.

          It is recommended to check L2LoadBalancer name in annotations (`network.deckhouse.io/l2-load-balancer-name`).
