#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 10
EOF
}

function __main__() {
  if ! values::has basicAuth.locations ; then
    values::set --config basicAuth "{\"locations\":[{\"location\":\"/\",\"users\":{\"admin\":\"$(tools::generate_password)\"}}]}"
  fi
}

hook::run $@
