#!/bin/bash

# Copyright 2021 Flant CJSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/ee/LICENSE


source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 10
EOF
}

function __main__() {
  if ! values::has basicAuth.locations ; then
    values::set --config basicAuth "{\"locations\":[{\"location\":\"/\",\"users\":{\"admin\":\"$(tools::generate_password)\"}}]}"
  fi
}

hook::run $@
