#!/bin/bash

### Migration 03.02.2021: Remove after this commit reached RockSolid

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 10
    kubernetes:
    - name: service
      group: main
      keepFullObjectsInMemory: false
      executeHookOnEvent: []
      waitForSynchronization: false
      apiVersion: v1
      kind: Service
      namespace:
        nameSelector:
          matchNames: [kube-basic-auth]
      nameSelector:
        matchNames: [basic-auth]
      jqFilter: |
        {
          "isMigrated": (.spec.clusterIP != "None")
        }
EOF
}

function __main__() {
  if ! context::has snapshots.service.0; then
    return 0
  fi

  if context::jq -e '.snapshots.service[0] | select(.filterResult.isMigrated == true)' >/dev/null; then
    return 0
  fi

  kubernetes::delete_if_exists kube-basic-auth service/basic-auth
}

hook::run "$@"
