{{- $moduleGateway := dict }}
{{- include "helm_lib_module_gateway" (list . $moduleGateway) }}
{{- if and (or .Values.istio.federation.enabled .Values.istio.multicluster.enabled) $moduleGateway .Values.global.modules.publicDomainTemplate (include "helm_lib_kind_exists" (list . "HTTPRoute")) (include "helm_lib_kind_exists" (list . "ListenerSet")) }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: metadata-exporter
  namespace: d8-{{ $.Chart.Name }}
  {{- if or (eq (include "helm_lib_module_https_mode" .) "CertManager") (eq (include "helm_lib_module_https_mode" .) "CustomCertificate") }}
  annotations:
    alb.network.deckhouse.io/response-headers-to-add: '{"Strict-Transport-Security":"max-age=31536000; includeSubDomains"}'
  {{- end }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "metadata-exporter")) | nindent 2 }}
spec:
  hostnames:
  - {{ include "helm_lib_module_public_domain" (list . "istio") }}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: ListenerSet
    name: istio
    namespace: d8-{{ $.Chart.Name }}
    sectionName: istio
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: metadata-exporter
      port: 8080
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /metadata/
{{- end }}
