#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: helm_releases
      group: main
      waitForSynchronization: false
      keepFullObjectsInMemory: false
      executeHookOnEvent: ["Added"]
      apiVersion: v1
      kind: ConfigMap
      labelSelector:
        matchLabels:
          OWNER: TILLER
      jqFilter: |
        {
          "metadata": .metadata
        }
    schedule:
    - group: main
      queue: /modules/$(module::name::kebab_case)/helm_releases
      crontab: "*/20 * * * *"
EOF
}

function __main__() {
  unsupported_versions='
    {
      "Deployment": {
        "apps/v1beta1": "",
        "apps/v1beta2": "",
        "extensions/v1beta1": ""
      },
      "StatefulSet": {
        "apps/v1beta1": "",
        "apps/v1beta2": ""
      },
      "DaemonSet": {
        "apps/v1beta1": "",
        "apps/v1beta2": "",
        "extensions/v1beta1": ""
      },
      "ReplicaSet": {
        "apps/v1beta1": "",
        "apps/v1beta2": "",
        "extensions/v1beta1": ""
      },
      "NetworkPolicy": {
        "extensions/v1beta1": ""
      },
      "PodSecurityPolicy": {
        "extensions/v1beta1": ""
      }
    }
  '


  D8_HELM_HOST="$HELM_HOST"
  metrics=""

  namespaces="$(context::jq -r '.snapshots.helm_releases[].filterResult.metadata.namespace' | sort | uniq)"
  for namespace in $namespaces; do
    if [ "$namespace" != "d8-system" ]; then
      HELM_HOST=""
    else
      HELM_HOST="$D8_HELM_HOST"
    fi
    if release_names="$(context::jq -rec --arg ns "$namespace" '.snapshots.helm_releases | map(select(.filterResult.metadata.namespace == $ns and .filterResult.metadata.labels.STATUS == "DEPLOYED") | .filterResult.metadata.labels.NAME) | unique []')"; then
      for release_name in $release_names; do
        if manifest="$(helm --tiller-namespace "$namespace" get manifest "$release_name" 2>/dev/null | yq read -d"*" -j -)"; then
          metrics="$metrics\n$(jq -rc --arg release_name "$release_name" --argjson d "$unsupported_versions" '
            .[] | select(.kind != null) |
            {
              "name": "resource_versions_compatibility",
              "set": 0,
              "group": "/modules/'$(module::name::kebab_case)'/metrics",
              "labels": {
                "helm_release_name": $release_name,
                "resource_name": .metadata.name,
                "kind": .kind,
                "api_version": .apiVersion,
                "namespace": .metadata.namespace
              }
            }
            | . as $in
            | if $d[.labels.kind] != null then if $d[$in.labels.kind] | has($in.labels.api_version) then .set = 1 else . end else . end
          ' <<< "$manifest")"
        else
          echo "WARNING: <helm --tiller-namespace $namespace get manifest $release_name> failed"
        fi
      done
    fi
  done

  echo -e "$metrics" >> $METRICS_PATH
}

hook::run "$@"
