#!/bin/bash

# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    onStartup: 5
    schedule:
    - group: main
      queue: /modules/$(module::name::kebab_case)/releases_count_metrics
      crontab: "*/20 * * * *"
EOF
}

function __main__() {
  metrics=""

  # helm 2
  if helm_releases_count="$(kubectl get configmaps -l OWNER=TILLER,STATUS=DEPLOYED --no-headers --all-namespaces 2>/dev/null | wc -l)"; then
    metrics="$metrics\n$(jq -nc --argjson count "$helm_releases_count" '
      {
        "name": "helm_releases_count",
        "set": $count,
        "group": "/modules/'$(module::name::kebab_case)'/releases_count_metrics",
        "labels": {
          "helm_version": "2"
        }
      }
    ')"
  fi

  # helm 3
  if helm_releases_count="$(kubectl get secret -l owner=helm,status=deployed --no-headers --all-namespaces 2>/dev/null | wc -l)"; then
    metrics="$metrics\n$(jq -nc --argjson count "$helm_releases_count" '
      {
        "name": "helm_releases_count",
        "set": $count,
        "group": "/modules/'$(module::name::kebab_case)'/releases_count_metrics",
        "labels": {
          "helm_version": "3"
        }
      }
    ')"
  fi

  echo -e "$metrics" >> $METRICS_PATH
}

hook::run "$@"
