#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 10
    kubernetes:
    - name: services_old
      includeSnapshotsFrom: ["services", "services_old"]
      apiVersion: v1
      kind: Service
      labelSelector:
        matchExpressions:
        - key: prometheus-target
          operator: Exists
    - name: services
      includeSnapshotsFrom: ["services", "services_old"]
      apiVersion: v1
      kind: Service
      labelSelector:
        matchExpressions:
        - key: prometheus.deckhouse.io/target
          operator: Exists
EOF
}

function __main__() {
  enabledApplications=$(context::jq -r '[.snapshots.services_old + .snapshots.services | .[] | (.object.metadata.labels."prometheus-target" // .object.metadata.labels."prometheus.deckhouse.io/target")] | sort | unique')
  values::set monitoringApplications.discovery.enabledApplications "$enabledApplications"
}

function __on_before_helm() {
  enabledApplicationsSummary=$(values::jq -r '.monitoringApplications.discovery.enabledApplications + .monitoringApplications.enabledApplications | unique')
  values::set monitoringApplications.internal.enabledApplicationsSummary "${enabledApplicationsSummary}"
}

hook::run $@

jq -r '[.snapshots.services_old + .snapshots.services | .[] | (.object.metadata.labels."prometheus-target" // .object.metadata.labels."prometheus.deckhouse.io/target")] | sort | unique' <<< '{"binding":"services_old","object":{"apiVersion":"v1","kind":"Service","metadata":{"labels":{"prometheus.deckhouse.io/target":"test"},"name":"new","namespace":"default"}},"snapshots":{"services":[],"services_old":[{"object":{"apiVersion":"v1","kind":"Service","metadata":{"labels":{"prometheus.deckhouse.io/target":"test"},"name":"new","namespace":"default"}}}]},"type":"Event","watchEvent":"Added"}'
