#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  echo '
{
   "onStartup": 100,
   "schedule": [
      {
         "allowFailure": true,
         "crontab": "0 3 * * *"
      }
   ],
   "onKubernetesEvent": [
      {
         "kind": "secret",
         "event": [
            "add",
            "update"
         ],
         "selector": {
            "matchLabels": {
               "antiopa-secret-copier": "yes"
            }
         },
         "namespaceSelector": {
            "matchNames": [
               "default"
            ]
         }
      }
   ]
}'
}

function __main__() {
  for secret in $(kubectl -n default get secret -l antiopa-secret-copier=yes -o name);
  do
    # для каждого Namespace с лейблом "antiopa-secret-copier=yes", кроме "default"
    for namespace in $(kubectl get namespace -o json |
                        jq -r '.items[] |
                          select((.metadata.labels."antiopa-secret-copier"=="yes") and (.metadata.name == "default" | not)) |
                          .metadata.name')
    do
      # копируем секрет, предварительно удалив лишние поля из metadata
      kubectl -n default get $secret -o json | \
        jq -r ".metadata.namespace=\"${namespace}\" |
                .metadata |= with_entries(select([.key] | inside([\"name\", \"namespace\", \"labels\"])))" \
        | kubectl::replace_or_create
    done
  done
}

hook::run $@
