#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  echo '
{
   "onKubernetesEvent": [
      {
         "kind": "secret",
         "event": [
            "add",
            "update"
         ],
         "selector": {
            "matchLabels": {
               "antiopa-secret-copier": "yes"
            }
         },
         "namespaceSelector": {
            "matchNames": [
               "default"
            ]
         }
      }
   ]
}'
}

function __main__() {
  for secret in $(hook::context_jq -r '.[] | .resourceName')
  do
    # для каждого Namespace , кроме "default"
    for namespace in $(kubectl get namespace -o json |
                      jq -r '.items[] |
                        select((.metadata.name == "default" | not) and .status.phase == "Active") | .metadata.name')
    do
      # копируем секрет, предварительно удалив лишние поля из metadata
      kubectl -n default get secret $secret -o json | \
        jq -r ".metadata.namespace=\"${namespace}\" |
                .metadata |= with_entries(select([.key] | inside([\"name\", \"namespace\", \"labels\"])))" \
        | kubectl::replace_or_create
    done
  done
}

hook::run $@
