#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p onKubernetesEvent="$(jo -a "$(jo kind=namespace event='["add"]')")"
}

function __main__() {
  for namespace in $(hook::context_jq -r '.[] | select((.resourceName == "default" | not ) and .status.phase == "Active") | .resourceName');
  do
    if ! $(kubectl get namespace $namespace > /dev/null 2> /dev/null) ; then
      continue
    fi

    for secret in $(kubectl -n default get secret -l antiopa-secret-copier=yes -o name);
    do
      kubectl -n default get $secret -o json | \
        jq -r "include \"remove_empty\"; .metadata.namespace=\"${namespace}\" | remove_empty |
                .metadata |= with_entries(select([.key] | inside([\"name\", \"namespace\", \"labels\"])))" \
        | kubectl::replace_or_create
    done
  done
}

hook::run $@
