#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  echo '
{
   "onStartup": 150,
   "schedule": [
      {
         "allowFailure": true,
         "crontab": "0 3 * * *"
      }
   ],
   "onKubernetesEvent": [
      {
         "kind": "secret",
         "event": [
            "delete"
         ],
         "selector": {
            "matchLabels": {
               "antiopa-secret-copier": "yes"
            }
         },
         "namespaceSelector": {
            "matchNames": [
               "default"
            ]
         }
      }
   ]
}'
}

function __main__() {
  # Получаем список имён из default Namespace с лейблами, проходимся далее по всем секретам в кластере и получаем список тех,
  # у которых лейбл присутствует, а имя не входит в массив имён, полученных из default Namespace.
  # Финальный список скармливаем `kubectl delete`
  kubectl get secret --all-namespaces -o json | \
    jq -r '([.items[] | select(.metadata.labels."antiopa-secret-copier"=="yes" and .metadata.namespace=="default").metadata.name]) as $secrets |
              .items[] | select(.metadata.labels."antiopa-secret-copier"=="yes" and .metadata.namespace!="default" and ([.metadata.name] | inside($secrets) | not)) |
              "\(.metadata.namespace) secret \(.metadata.name)"' | \
    while read -r secret
      do
        kubectl delete -n $secret
      done
}

hook::run $@
