#!/bin/bash

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  echo '
{
   "onKubernetesEvent": [
      {
         "kind": "secret",
         "event": [
            "delete"
         ],
         "selector": {
            "matchLabels": {
               "antiopa-secret-copier": "yes"
            }
         },
         "namespaceSelector": {
            "matchNames": [
               "default"
            ]
         }
      }
   ]
}'
}

function __main__() {
  for secret in $(hook::context_jq -r '.[] | .resourceName')
  do
    for namespace in $(kubectl get namespace -o json |
                        jq -r '.items[] |
                          select((.metadata.name == "default" | not) and .status.phase == "Active") | .metadata.name')
    do
      if ! $(kubectl -n $namespace get secret $secret > /dev/null 2> /dev/null) ; then
        continue
      fi

      kubectl -n $namespace delete secret $secret || echo "Deletion of secret $secret in namespace $namespace failed. Skipping... "
    done
  done
}

hook::run $@
