#!/bin/bash

# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 20
EOF
}

function __main__() {
  storage_classes='[
    {
      "name": "pd-standard-not-replicated",
      "type": "pd-standard",
      "replicationType": "none"
    },
    {
      "name": "pd-standard-replicated",
      "type": "pd-standard",
      "replicationType": "regional-pd"
    },
    {
      "name": "pd-balanced-not-replicated",
      "type": "pd-balanced",
      "replicationType": "none"
    },
    {
      "name": "pd-balanced-replicated",
      "type": "pd-balanced",
      "replicationType": "regional-pd"
    },
    {
      "name": "pd-ssd-not-replicated",
      "type": "pd-ssd",
      "replicationType": "none"
    },
    {
      "name": "pd-ssd-replicated",
      "type": "pd-ssd",
      "replicationType": "regional-pd"
    }
  ]'

  if values::has cloudProviderGcp.storageClass.exclude; then
    storage_classes="$(jq --arg exclude "$(values::get cloudProviderGcp.storageClass.exclude | jq -r 'join("|")')" '
      map(select(.name | test("^(\($exclude))$") | not))
      ' <<< "$storage_classes")"
  fi
  values::set cloudProviderGcp.internal.storageClasses "$storage_classes"

  if values::has cloudProviderGcp.storageClass.default; then
    values::set cloudProviderGcp.internal.defaultStorageClass "$(values::get cloudProviderGcp.storageClass.default)"
  else
    values::unset cloudProviderGcp.internal.defaultStorageClass
  fi
}

hook::run "$@"
