#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    afterHelm: 10
EOF
}

function __main__() {
  for i in $(seq 1 120); do
    master_nodes=$(kubectl get node -l node-role.kubernetes.io/master="" -o json)

    all_initialized=$(echo "$master_nodes" | jq '[(.items[].spec.taints // []) | [(.[] | select(.key == "node.cloudprovider.kubernetes.io/uninitialized"))] | length == 0] | all')

    if [[ "x$all_initialized" == "xfalse" ]] ; then
      echo "Waiting for master nodes to become initialized by cloud provider"
    else
      return 0
    fi

    sleep 1
  done
  if [[ $i -ge 120 ]] ; then
    >&2 echo "Timeout waiting for master nodes"
    return 1
  fi
}

hook::run $@
