{{- define "gpu_operator_resources" }}
cpu: 200m
memory: 100Mi
{{- end }}
---

{{- if (.Values.global.enabledModules | has "vertical-pod-autoscaler") }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: nvidia-gpu-operator
  namespace: d8-nvidia-gpu
  {{- include "helm_lib_module_labels" (list . (dict "app" "nvidia-gpu-operator")) | nindent 2 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: nvidia-gpu-operator
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: gpu-operator
      minAllowed:
        cpu: 200m
        memory: 100Mi
      maxAllowed:
        cpu: 500m
        memory: 350Mi
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvidia-gpu-operator
  namespace: d8-nvidia-gpu
  {{- include "helm_lib_module_labels" (list . (dict "app" "nvidia-gpu-operator")) | nindent 2 }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: "nvidia-gpu-operator"
      app: "nvidia-gpu-operator"
  template:
    metadata:
      labels:
        app.kubernetes.io/component: "nvidia-gpu-operator"
        app: "nvidia-gpu-operator"
    spec:
      affinity:
      {{- include "helm_lib_node_selector" (tuple . "system") | nindent 6 }}
      {{- include "helm_lib_tolerations" (tuple . "system") | nindent 6 }}
      {{- include "helm_lib_module_pod_security_context_run_as_user_deckhouse" . | nindent 6 }}
      serviceAccountName: nvidia-gpu-operator
      imagePullSecrets:
      - name: deckhouse-registry
      {{- include "helm_lib_priority_class" (tuple . "cluster-medium") | nindent 6 }}
      containers:
      - name: gpu-operator
        {{- include "helm_lib_module_container_security_context_privileged_read_only_root_filesystem" . | nindent 8 }}
        image: {{ include "helm_lib_module_common_image" (list . "nvidiaGpu") }}
        command: ["/gpu-operator"]
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
          - name: host-os-release
            mountPath: "/host-etc/os-release"
            readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            {{- include "helm_lib_module_ephemeral_storage_only_logs" . | nindent 12 }}
  {{- if not ( .Values.global.enabledModules | has "vertical-pod-autoscaler") }}
            {{- include "gpu_operator_resources" . | nindent 12 }}
  {{- end }}
        ports:
          - name: metrics
            containerPort: 8080
      volumes:
        - name: host-os-release
          hostPath:
            path: "/etc/os-release"
