apiVersion: v1
kind: ConfigMap
metadata:
  name: device-plugin-config
  namespace: d8-nvidia-gpu
  {{- include "helm_lib_module_labels" (list . (dict "app" "nvidia-gpu")) | nindent 2 }}
data:
  default: |-
    version: v1
    flags:
      migStrategy: none
  mig-single: |-
    version: v1
    flags:
      migStrategy: single
  mig-mixed: |-
    version: v1
    flags:
      migStrategy: mixed
  time-slicing: |-
    version: v1
    flags:
      migStrategy: none
    sharing:
      timeSlicing:
        renameByDefault: false
        failRequestsGreaterThanOne: true
        resources:
          - name: nvidia.com/gpu
            replicas: 4
