// Code generated by "go generate ./tools/register.go". DO NOT EDIT!
package main

import (
	_ "github.com/deckhouse/deckhouse/go_lib/deckhouse-config/conversion"

	_ "github.com/deckhouse/deckhouse/ee/modules/110-istio/config-values-conversion"
	_ "github.com/deckhouse/deckhouse/modules/300-prometheus/config-values-conversion"
	_ "github.com/deckhouse/deckhouse/modules/500-cilium-hubble/config-values-conversion"
	_ "github.com/deckhouse/deckhouse/modules/500-dashboard/config-values-conversion"
	_ "github.com/deckhouse/deckhouse/modules/500-openvpn/config-values-conversion"
	_ "github.com/deckhouse/deckhouse/modules/500-upmeter/config-values-conversion"
	_ "github.com/deckhouse/deckhouse/modules/810-deckhouse-web/config-values-conversion"
)
