#!/bin/bash

source /deckhouse/shell_lib.sh

function __main__() {
  enabled::disable_module_in_kubernetes_versions_less_than 1.15.0

  if [[ $(values::get global.clusterConfiguration.clusterType) == "Cloud" && $(values::get global.clusterConfiguration.cloud.provider) == "OpenStack" ]]; then
    echo "true" > $MODULE_ENABLED_RESULT
  else
    echo "false" > $MODULE_ENABLED_RESULT
  fi
}

enabled::run $@
