{
 "title": "VPA Recommendations",
 "description": "A dashboard to visualize metrics about the Vertical Pod Autoscalar (https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler)",
 "tags": [
  "Autoscaling",
  "VPA"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{d8_source=\"dkp\", node=~\".*\"},namespace)"
    }
   },
   {
    "name": "targetName",
    "label": "Target",
    "query": {
     "query": "label_values(vpa_target_recommendation{namespace=\"$namespace\"},target_name)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_controller_pod{d8_source=\"dkp\", namespace=\"$namespace\", controller_name=~\"$targetName\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{d8_source=\"dkp\", namespace=\"$namespace\", pod=~\"$pod\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Recommender", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Target recommendations",
   "type": "timeseries",
   "description": "Shows the recommendations that the VPA gives as target usage.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(vpa_target_recommendation{d8_source=\"dkp\", resource=\"memory\", namespace=\"$namespace\", target_name=~\"$targetName\", container=~\"$container\", job=\"kube-state-metrics\"}) by (controller_type, controller_name, container)",
     "legendFormat": "{{controller_type}}/{{controller_name}}, container: {{container}}"
    }
   ]
  },
  {
   "title": "Memory Actual Usage vs Requests & Limits",
   "type": "timeseries",
   "description": "Shows the actual usage of each container and also request and limit for each container",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{d8_source=\"dkp\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", job=\"kubelet\"}) by (container,pod)",
     "legendFormat": "usage: {{pod}}/{{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{d8_source=\"dkp\", resource=\"memory\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"kube-state-metrics\"}) by (container,pod)",
     "legendFormat": "request: {{pod}}/{{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{d8_source=\"dkp\", resource=\"memory\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"kube-state-metrics\"}) by (container,pod)",
     "legendFormat": "limit: {{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "CPU Target recommendations",
   "type": "timeseries",
   "description": "Shows the recommendations that the VPA gives as target usage.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vpa_target_recommendation{d8_source=\"dkp\", resource=\"cpu\", namespace=\"$namespace\", target_name=~\"$targetName\", container=~\"$container\", job=\"kube-state-metrics\"}) by (controller_type, controller_name, container) * 1000",
     "legendFormat": "{{controller_type}}/{{controller_name}}, container: {{container}}"
    }
   ]
  },
  {
   "title": "CPU Actual Usage vs Requests & Limits",
   "type": "timeseries",
   "description": "Shows the actual usage of each container and also request and limit for each container",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{d8_source=\"dkp\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", job=\"kubelet\"}[$__rate_interval])) by (container,pod) * 1000",
     "legendFormat": "usage: {{pod}}/{{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{d8_source=\"dkp\", resource=\"cpu\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"kube-state-metrics\"}) by (container,pod) * 1000",
     "legendFormat": "request: {{pod}}/{{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{d8_source=\"dkp\", resource=\"cpu\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"kube-state-metrics\"}) by (container,pod) * 1000",
     "legendFormat": "limit: {{pod}}/{{container}}"
    }
   ]
  },
  { "title": "Updater", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Evicted pods",
   "type": "timeseries",
   "description": "Shows the count of pods that was evicted by VPA updater based on VPA recommendations",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(vpa_updater_evicted_pods_total{d8_source=\"dkp\"}[$__rate_interval])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}