@startuml
!theme bluegray
skinparam DefaultFontSize 16
skinparam ArrowFontStyle italic
skinparam DefaultTextAlignment center
skinparam backgroundColor transparent
skinparam Shadowing false

start

:Исходное состояние:\nv0.3.33 (Deployed);

if (В кластере есть релизы\nс update.versions?) then (Да)
  :Доступные релизы и правила:\n• v0.6.11 — from 0.2 → to 0.5\n• v0.7.25 — from 0.3 → to 0.7;
  if (Одно из значений to\nсовпадает с версией этого релиза?) then (Да)
    :Кандидаты после проверки совпадения to — 0.7 (v0.7.25);
    :Выбрана максимальная версия 0.7 (v0.7.25);
    if (Текущая 0.3.33\nниже from 0.3?) then (Да)
      :Обычное обновление по порядку\n(без пропуска);
      :Установлена версия v0.4.1;
      stop
    else (Нет)
      :DKP выбирает цель — последнюю доступную версию\nв пределах 0.7 → v0.7.25 (Pending);
      if (Требуется подтверждение?) then (Да)
        :Ожидается подтверждение — аннотация\nmodules.deckhouse.io/approved="true";
      else (Нет)
      endif
      :Установлена версия v0.7.25 (Deployed);
      stop
    endif
  else (Нет)
    :Обычное обновление по порядку\n(без пропуска);
    :Установлена версия v0.4.1;
    stop
  endif
else (Нет)
  :Обычное обновление по порядку\n(без пропуска);
  :Установлена версия v0.4.1;
  stop
endif

@enduml
