@startuml
!theme bluegray
skinparam DefaultFontSize 16
skinparam handwritten false
skinparam ArrowFontStyle italic
skinparam DefaultTextAlignment center
skinparam backgroundColor transparent
skinparam Shadowing false

start

:Модуль включён;
:ModuleRelease v1.0.0 развёрнут;
:Модуль отключён;

if (Прошло 72 часа?) then (Нет)
  if (Модуль\nповторно включён?) then (Да)
    :ModuleRelease v1.0.0 активирован;
    :Загружены ModuleRelease\nv1.1.0 и v1.1.1;
    :Обновление модуля до v1.1.1;
  else (Нет)
    stop
  endif
else (Да)
  :ModuleRelease v1.0.0 удалён;

  if (Модуль\nповторно включён?) then (Да)
    :ModuleRelease v1.1.1 развёрнут;
    :Обновление модуля до v1.1.1;
  else (Нет)
    stop
  endif
endif

:Модуль обновлён;
stop
@enduml
