#!/bin/bash

# Copyright 2021 Flant JSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE

source /deckhouse/shell_lib.sh

function __config__() {
  common_hooks::https::copy_custom_certificate::config
}

function __main__() {
   common_hooks::https::copy_custom_certificate::main
}

hook::run "$@"
