#!/bin/bash

# Copyright 2021 Flant CJSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/ee/LICENSE

source /deckhouse/shell_lib.sh

function __config__() {
  legacy::common_hooks::https::delete_not_matching_certificate_secret::config
}

function __main__() {
  legacy::common_hooks::https::delete_not_matching_certificate_secret::main "d8-openvpn"
}

hook::run "$@"
