#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  jo -p afterHelm=10
}

function __main__() {
  for i in $(seq 1 120); do
    if kubectl -n d8-cert-manager get pod -l app=webhook -o json  | jq -e '.items[].status.conditions | select(.) | all(.[] ; .status == "True")' > /dev/null
    then
      return 0
    fi

    echo "Waiting for webhook pod in d8-cert-manager namespace"
    sleep 1
  done
  if [[ $i -ge 120 ]] ; then
    >&2 echo "Timeout waiting for webhook pod in d8-cert-manager namespace"
    return 1
  fi
}

hook::run $@
