#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  jo -p beforeHelm=10
}

function __main__() {

  if ! values::has basicAuth.locations ; then
    values::set --config basicAuth "{\"locations\":[{\"location\":\"/\",\"users\":{\"admin\":\"$(values::generate_password)\"}}]}"
  fi

}

hook::run $@
