#!/bin/sh

# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

HOSTS_FILE=/mnt/hosts

cat > $HOSTS_FILE << EOF
127.0.0.1	localhost
::1		localhost ip6-localhost ip6-loopback
fe00::0		ip6-localnet
fe00::0		ip6-mcastprefix
fe00::1		ip6-allnodes
fe00::2		ip6-allrouters
${POD_IP}	${POD_HOSTNAME}.${POD_SUBDOMAIN}.${POD_NAMESPACE}.svc.${CLUSTER_DOMAIN}	${POD_HOSTNAME}
EOF

for alias in ${CLUSTER_DOMAIN_ALIASES}; do
  echo "${POD_IP}	${POD_HOSTNAME}.${POD_SUBDOMAIN}.${POD_NAMESPACE}.svc.${alias}" >> $HOSTS_FILE
done
