#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p afterHelm=10
}

function __main__() {
  for i in $(seq 1 120); do
    if kubectl -n kube-cert-manager get pod -l app=webhook -o json  | jq -e '.items[].status.conditions | all(.[] ; .status == "True")' ; then
      return 0
    fi

    echo "Waiting for webhook pod in kube-cert-manager namespace"
    sleep 1
  done
  if [[ $i -gt 120 ]] ; then
    >&2 echo "Timeout waiting for webhook pod in kube-cert-manager namespace"
    return 1
  fi
}

hook::run $@
