#!/bin/bash
# Copyright 2022 Flant JSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE.

set -Eeo pipefail
dpkg -i -E kubernetes-cni_amd64.deb
[[ -e flannel ]] && cp -f flannel /opt/cni/bin/flannel
apt-mark hold kubernetes-cni

[[ -e flannel ]] && cp -f flannel /opt/cni/bin/flannel
