#!/bin/bash
# Copyright 2022 Flant JSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE.

set -Eeo pipefail
apt-mark unhold kubernetes-cni
dpkg -r kubernetes-cni
rm -f /opt/cni/bin/flannel
