#!/bin/bash

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  common_hooks::https::delete_not_matching_certificate_secret::config
}

function __main__() {
  common_hooks::https::delete_not_matching_certificate_secret::main "d8-monitoring"
}

hook::run "$@"
