#!/bin/bash

### Миграция 2018-11-13: https://github.com/deckhouse/deckhouse/merge_requests/534
#
# Этот хук можно удалить, после того как все переедут на использование этого
# модуля и установленные вручную okmeter'ы будут удалены во всех кластерах.

source /antiopa/shell_lib.sh

function __config__() {
  jo -p afterHelm=10
}

function __main__() {
  # Удаляем старый okmeter в kubernetes, который был установлен руками
  for namespace in $(kubectl get ds  --all-namespaces -o json  | jq -r '.items[] | select(.metadata.name == "okagent") | .metadata.namespace')
  do
    if [ "$namespace" == "default" ];
    then
      kubectl delete -n $namespace ds okagent
      kubectl delete -n $namespace serviceaccount okagent
    else
      kubectl delete ns $namespace
    fi
    kubectl delete clusterrolebinding okagent
  done
}

hook::run $@
