#!/bin/bash

### Миграция 2019-05-07: https://github.com/deckhouse/deckhouse/merge_requests/769
# Этот хук нужен для пересоздания подов okmeter и создания подов с новой cluster role

source /antiopa/shell_lib.sh

function __config__() {
  jo -p afterHelm=10
}

function __main__() {
  clusterRoleBindingCreationTimestamp=$(kubectl get clusterrolebinding kube-okmeter -o json | jq '.metadata.creationTimestamp' -r | sed 's/\([0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\)T\([0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\).*/\1 \2/')
  clusterRoleBindingDate=$(date --date="$clusterRoleBindingCreationTimestamp" +%s)
  for pod in $(kubectl -n kube-okmeter get pod --no-headers | awk '{print $1}'); do
    podCreationTimestamp=$(kubectl -n kube-okmeter  get pod $pod -o json | jq -r '.metadata.creationTimestamp' | sed 's/\([0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\)T\([0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\).*/\1 \2/')
    podDate=$(date --date="$podCreationTimestamp" +%s)
    if [ $clusterRoleBindingDate -gt $podDate ] ; then
      kubectl -n kube-okmeter delete pod $pod > /dev/null 
    fi
  done
}

hook::run $@
