#!/bin/bash

### Миграция 2019-05-07: https://github.com/deckhouse/deckhouse/merge_requests/769
# Этот хук нужен для пересоздания корректного ClusterRoleBinding для okmeter

source /antiopa/shell_lib.sh

function __config__() {
  jo -p beforeHelm=10
}

function __main__() {
  # Удаляем старый ClusterRoleBinding
  if kubectl get clusterrolebinding kube-okmeter -o json | jq -e '. | select(.roleRef.name == "view") | .metadata.name' > /dev/null ; then
    kubectl delete clusterrolebinding kube-okmeter
  fi
}

hook::run $@
