apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    heritage: deckhouse
    module: prometheus-metrics-adapter
    rbac.deckhouse.io/aggregate-to-observability-as: viewer
    rbac.deckhouse.io/kind: capability
    rbac.deckhouse.io/scope: system
    rbac.deckhouse.io/namespace: d8-monitoring
  name: d8:system-capability:prometheus-metrics-adapter:view
  annotations:
    en.meta.deckhouse.io/title: "Module prometheus-metrics-adapter: view configuration"
    ru.meta.deckhouse.io/title: "Модуль prometheus-metrics-adapter: просмотр конфигурации"
    en.meta.deckhouse.io/description: "Read-only access to the prometheus-metrics-adapter module configuration."
    ru.meta.deckhouse.io/description: "Доступ только на чтение к конфигурации модуля prometheus-metrics-adapter."
rules:
- apiGroups:
  - deckhouse.io
  resources:
  - clusterdaemonsetmetrics
  - clusterdeploymentmetrics
  - clusteringressmetrics
  - clusterpodmetrics
  - clusterservicemetrics
  - clusterstatefulsetmetrics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deckhouse.io
  resourceNames:
  - prometheus-metrics-adapter
  resources:
  - moduleconfigs
  verbs:
  - get
  - list
  - watch
