/*
Copyright 2025 Flant JSC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	 http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package helpers

import (
	"crypto/x509"

	"github.com/flant/addon-operator/pkg/module_manager/go_hook"

	registry_pki "github.com/deckhouse/deckhouse/go_lib/registry/pki"
)

const (
	// ingressClientCAPath is the path to the Kube RBAC Proxy CA certificate in the values store.
	// This value is generated by "global-hooks/generate_kube_rbac_proxy_ca.go".
	ingressClientCAPath = "global.internal.modules.kubeRBACProxyCA.cert"

	// clusterIsBootstrappedPath is the path to the cluster bootstrap status flag in the values store.
	// This value is generated by "global-hooks/cluster_is_bootstrapped.go".
	clusterIsBootstrappedPath = "global.clusterIsBootstrapped"
)

// IngressClientCA retrieves the ingress CA certificate from the hook input values.
//
// Returns:
//   - *x509.Certificate: the decoded CA certificate, or nil if it doesn't exist or is empty
//   - error: decoding error if the certificate is malformed
func IngressClientCA(input *go_hook.HookInput) (*x509.Certificate, error) {
	certValue, exists := input.Values.GetOk(ingressClientCAPath)
	if !exists {
		return nil, nil
	}
	certStr := certValue.String()
	if certStr == "" {
		return nil, nil
	}
	return registry_pki.DecodeCertificate([]byte(certStr))
}

// ClusterIsBootstrapped checks whether the cluster has completed initial bootstrapping.
//
// Returns:
//   - bool: true if the cluster is bootstrapped, else false
func ClusterIsBootstrapped(input *go_hook.HookInput) bool {
	if isBootstrapped, exists := input.Values.GetOk(clusterIsBootstrappedPath); exists {
		return isBootstrapped.Bool()
	}
	return false
}
