#!/bin/bash
# Copyright 2022 Flant JSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE

set -Eeo pipefail
package="kubernetes-cni"
package_file="${package}.x86_64.rpm"
rpm_name="$(rpm -qip ${package_file} 2>/dev/null | grep Name | awk '{print $3}')"
rpm_version="$(rpm -qip ${package_file} 2>/dev/null | grep Version | awk '{print $3}')"

if ! rpm --quiet -q "${rpm_name}-${rpm_version}"; then
  rpm -U --nodeps --oldpackage $package_file
else
  echo "RPM ${package_file} already installed."
fi
[[ -e flannel ]] && cp -f flannel /opt/cni/bin/flannel

yum versionlock add ${package}
