#!/bin/bash

# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /deckhouse/shell_lib.sh

function __main__() {
  enabled::disable_module_if_cluster_is_not_bootstraped

  # Check if publicDomainTemplate is set
  if ! values::has global.modules.publicDomainTemplate ; then
    echo "false" > "$MODULE_ENABLED_RESULT"
    echo "spec.settings.modules.publicDomainTemplate is not set in the global configuration, configure it in ModuleConfig/global." > "$MODULE_ENABLED_REASON"
    return
  fi

  # Check HTTPS mode
  https_mode=$(values::get_first_defined dashboard.https.mode global.modules.https.mode)
  if [ "$https_mode" = "Disabled" ]; then
    echo "false" > "$MODULE_ENABLED_RESULT"
    echo "https.mode is set to 'Disabled' - set it in ModuleConfig/global or ModuleConfig/dashboard." > "$MODULE_ENABLED_REASON"
    return
  fi

  # If user-authn is enabled
  if values::array_has global.enabledModules "user-authn"; then
    echo "true" > $MODULE_ENABLED_RESULT
    return
  fi

  # If user-authn is not enabled, check for external authentication URLs
  if values::has dashboard.auth.externalAuthentication.authSignInURL && \
      values::has dashboard.auth.externalAuthentication.authURL ; then
    echo "true" > $MODULE_ENABLED_RESULT
    return
  fi

  echo "false" > "$MODULE_ENABLED_RESULT"
  echo "required values settings.auth.externalAuthentication.authSignInURL and settings auth.externalAuthentication.authURL - set it in ModuleConfig/dashboard. " > "$MODULE_ENABLED_REASON"
}


enabled::run "$@"
