#!/bin/bash
# Copyright 2022 Flant JSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE.

set -Eeo pipefail
dpkg -i -E docker-ce_amd64.deb docker-ce-cli_amd64.deb
apt-mark hold docker-ce docker-ce-cli
