{
 "title": "Loki Disk Utilization",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Disk Usage Evaluation Duration",
   "type": "stat",
   "description": "Time took to evaluate Loki disk utilization",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(force_expiration_hook_dir_usage_evaluation_duration_sum{source=\"deckhouse\"}[1m])/rate(force_expiration_hook_dir_usage_evaluation_duration_count{source=\"deckhouse\"}[1m])) by (working_dir)",
     "legendFormat": "{{ working_dir }}"
    }
   ]
  },
  {
   "title": "Last Chunk Expiration Delta",
   "type": "stat",
   "description": "Time passed since last forcibly expired chunk",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - force_expiration_hook_last_expired_chunk_timestamp_seconds{source=\"deckhouse\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "description": "Disk utilization by Loki",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "force_expiration_hook_dir_usage_bytes{source=\"deckhouse\"}",
     "legendFormat": "{{ working_dir }}"
    },
    {
     "expr": "force_expiration_hook_dir_usage_threshold_bytes{source=\"deckhouse\"}",
     "legendFormat": "threshold"
    }
   ]
  },
  {
   "title": "Expired Chunks",
   "type": "timeseries",
   "description": "Number of currently expired chunks",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "targets": [
    {
     "expr": "sum(increase(force_expiration_hook_expired_chunks_count{source=\"deckhouse\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Expired Chunks Size",
   "type": "timeseries",
   "description": "Size of currently expired chunks",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(force_expiration_hook_expired_chunks_size_bytes{source=\"deckhouse\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}