{
 "title": "Loki",
 "description": "Loki metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(loki_build_info{source=\"deckhouse\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Loki Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "loki_build_info{source=\"deckhouse\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Message Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(loki_log_messages_total{source=\"deckhouse\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Current Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cortex_prometheus_notifications_alertmanagers_discovered{source=\"deckhouse\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Alerts Event Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cortex_prometheus_notifications_sent_total{source=\"deckhouse\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Store Series Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(loki_store_series_total{source=\"deckhouse\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Store Chunks Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(loki_ingester_chunk_stored_bytes_total{source=\"deckhouse\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Rules Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(cortex_prometheus_rule_group_rules{source=\"deckhouse\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Panic ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "loki_panic_total{source=\"deckhouse\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Discarded Lines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,sum by (reason) (rate(loki_discarded_samples_total{source=\"deckhouse\"}[1m])))",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Discarded Lines Per Interval",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum by (reason) (sum_over_time(increase(loki_discarded_samples_total{source=\"deckhouse\", namespace=\"$namespace\"}[1m])[$__range:1m])))",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Messages Input",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(loki_log_messages_total{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])) by (level)",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "S3 Request Durations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_s3_request_duration_seconds_bucket{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])) by (le,operation))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "API Request Durations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_request_duration_seconds_bucket{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])) by (le,route))",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "LogQL Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_latency_seconds_bucket{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])) by (le,type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "LogQL  Processed bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_bytes_processed_per_seconds_bucket{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])) by (le,type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum by (service) (rate(process_cpu_seconds_total{source=\"deckhouse\", namespace=\"$namespace\",job=~\".*loki.*\"}[$__rate_interval]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Distributor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received Lines / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (tenant) (rate(loki_distributor_lines_received_total{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{ tenant }}"
      }
     ]
    },
    {
     "title": "Distributor  Received bytes / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_bytes_received_total{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])) by (tenant)",
       "legendFormat": "{{ tenant }}"
      }
     ]
    },
    {
     "title": "batch appends sent to ingesters / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_ingester_appends_total{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "successed"
      },
      {
       "expr": "sum(rate(loki_distributor_ingester_append_failures_total{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "failed"
      }
     ]
    },
    {
     "title": "Store Series / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (status) (rate(loki_store_series_total{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingester",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blocks / Chunk",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_blocks_per_chunk_bucket{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": "blocks"
      }
     ]
    },
    {
     "title": "Chunk Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_size_bytes_bucket{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": "chunk size"
      }
     ]
    },
    {
     "title": "Chunk Age",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_age_seconds_bucket{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": "age"
      }
     ]
    },
    {
     "title": "Chunk Compression Ratios",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_compression_ratio_bucket{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": "ratio"
      }
     ]
    },
    {
     "title": "Chunk Encode Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_encode_time_seconds_bucket{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": "duration"
      }
     ]
    },
    {
     "title": "Lines / Chunk",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_entries_bucket{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": "lines"
      }
     ]
    },
    {
     "title": "Chunk Status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(loki_ingester_chunks_created_total{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])",
       "legendFormat": "create"
      },
      {
       "expr": "sum by (reason) (rate(loki_ingester_chunks_flushed_total{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "flush / {{ reason }}"
      },
      {
       "expr": "sum by (fake) (rate(loki_ingester_chunks_stored_total{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "stored"
      }
     ]
    },
    {
     "title": "Chunks in Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "loki_ingester_memory_chunks{source=\"deckhouse\", namespace=\"$namespace\"}",
       "legendFormat": "chunks"
      }
     ]
    },
    {
     "title": "Chunks in Streams",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (tenan) (loki_ingester_memory_streams{source=\"deckhouse\", namespace=\"$namespace\"})",
       "legendFormat": "streams"
      }
     ]
    },
    {
     "title": "Strams Stats",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(loki_ingester_streams_created_total{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])",
       "legendFormat": "create"
      },
      {
       "expr": "rate(loki_ingester_streams_removed_total{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])",
       "legendFormat": "delete"
      }
     ]
    }
   ]
  },
  {
   "title": "Index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cassandra Request Durations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(cortex_cassandra_request_duration_seconds_bucket{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])) by (le,operation))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Chunk Store Chunks",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_chunk_store_chunks_per_query_bucket{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": "chunks"
      }
     ]
    },
    {
     "title": "Table-Manager Sync Durations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(cortex_table_manager_sync_duration_seconds_bucket{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])) by (le))"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Request  Duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_cache_request_duration_seconds_bucket{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])) by (le,name,method))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Cache Value Size bytes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_cache_value_size_bytes_bucket{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])) by (le,name,method))",
       "legendFormat": "{{name}} / {{method}}"
      }
     ]
    },
    {
     "title": "Hits Keys",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(loki_cache_hits{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Background Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 10, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "loki_cache_background_queue_length{source=\"deckhouse\", namespace=\"$namespace\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Fetched Keys",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(loki_cache_fetched_keys{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ruler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rules Status ",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cortex_prometheus_rule_evaluations_total{source=\"deckhouse\", namespace=\"$namespace\"}",
       "legendFormat": "Evaluations"
      },
      {
       "expr": "cortex_prometheus_notifications_sent_total{source=\"deckhouse\", namespace=\"$namespace\"}",
       "legendFormat": "Notifications"
      }
     ]
    },
    {
     "title": "Notifications Latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 7, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(cortex_prometheus_notifications_latency_seconds{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval]))  by (quantile)",
       "legendFormat": "TP {{quantile}}"
      }
     ]
    },
    {
     "title": "Rule Evaluations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(cortex_prometheus_rule_evaluation_duration_seconds{source=\"deckhouse\", namespace=\"$namespace\"}[$__rate_interval]))  by (quantile)",
       "legendFormat": "TP {{quantile}}"
      }
     ]
    }
   ]
  }
 ]
}