//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutomaticDisruptionSpec) DeepCopyInto(out *AutomaticDisruptionSpec) {
	*out = *in
	if in.DrainBeforeApproval != nil {
		in, out := &in.DrainBeforeApproval, &out.DrainBeforeApproval
		*out = new(bool)
		**out = **in
	}
	if in.Windows != nil {
		in, out := &in.Windows, &out.Windows
		*out = make([]DisruptionWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutomaticDisruptionSpec.
func (in *AutomaticDisruptionSpec) DeepCopy() *AutomaticDisruptionSpec {
	if in == nil {
		return nil
	}
	out := new(AutomaticDisruptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRISpec) DeepCopyInto(out *CRISpec) {
	*out = *in
	if in.Containerd != nil {
		in, out := &in.Containerd, &out.Containerd
		*out = new(ContainerdSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerdV2 != nil {
		in, out := &in.ContainerdV2, &out.ContainerdV2
		*out = new(ContainerdSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Docker != nil {
		in, out := &in.Docker, &out.Docker
		*out = new(DockerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NotManaged != nil {
		in, out := &in.NotManaged, &out.NotManaged
		*out = new(NotManagedCRISpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRISpec.
func (in *CRISpec) DeepCopy() *CRISpec {
	if in == nil {
		return nil
	}
	out := new(CRISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaosSpec) DeepCopyInto(out *ChaosSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaosSpec.
func (in *ChaosSpec) DeepCopy() *ChaosSpec {
	if in == nil {
		return nil
	}
	out := new(ChaosSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClassReference) DeepCopyInto(out *ClassReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClassReference.
func (in *ClassReference) DeepCopy() *ClassReference {
	if in == nil {
		return nil
	}
	out := new(ClassReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInstancesSpec) DeepCopyInto(out *CloudInstancesSpec) {
	*out = *in
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxUnavailablePerZone != nil {
		in, out := &in.MaxUnavailablePerZone, &out.MaxUnavailablePerZone
		*out = new(int32)
		**out = **in
	}
	if in.MaxSurgePerZone != nil {
		in, out := &in.MaxSurgePerZone, &out.MaxSurgePerZone
		*out = new(int32)
		**out = **in
	}
	if in.Standby != nil {
		in, out := &in.Standby, &out.Standby
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.StandbyHolder != nil {
		in, out := &in.StandbyHolder, &out.StandbyHolder
		*out = new(StandbyHolderSpec)
		(*in).DeepCopyInto(*out)
	}
	out.ClassReference = in.ClassReference
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int)
		**out = **in
	}
	if in.QuickShutdown != nil {
		in, out := &in.QuickShutdown, &out.QuickShutdown
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInstancesSpec.
func (in *CloudInstancesSpec) DeepCopy() *CloudInstancesSpec {
	if in == nil {
		return nil
	}
	out := new(CloudInstancesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionSummary) DeepCopyInto(out *ConditionSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionSummary.
func (in *ConditionSummary) DeepCopy() *ConditionSummary {
	if in == nil {
		return nil
	}
	out := new(ConditionSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerdSpec) DeepCopyInto(out *ContainerdSpec) {
	*out = *in
	if in.MaxConcurrentDownloads != nil {
		in, out := &in.MaxConcurrentDownloads, &out.MaxConcurrentDownloads
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerdSpec.
func (in *ContainerdSpec) DeepCopy() *ContainerdSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisruptionWindow) DeepCopyInto(out *DisruptionWindow) {
	*out = *in
	if in.Days != nil {
		in, out := &in.Days, &out.Days
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisruptionWindow.
func (in *DisruptionWindow) DeepCopy() *DisruptionWindow {
	if in == nil {
		return nil
	}
	out := new(DisruptionWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisruptionsSpec) DeepCopyInto(out *DisruptionsSpec) {
	*out = *in
	if in.Automatic != nil {
		in, out := &in.Automatic, &out.Automatic
		*out = new(AutomaticDisruptionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RollingUpdate != nil {
		in, out := &in.RollingUpdate, &out.RollingUpdate
		*out = new(RollingUpdateDisruptionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisruptionsSpec.
func (in *DisruptionsSpec) DeepCopy() *DisruptionsSpec {
	if in == nil {
		return nil
	}
	out := new(DisruptionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerSpec) DeepCopyInto(out *DockerSpec) {
	*out = *in
	if in.MaxConcurrentDownloads != nil {
		in, out := &in.MaxConcurrentDownloads, &out.MaxConcurrentDownloads
		*out = new(int)
		**out = **in
	}
	if in.Manage != nil {
		in, out := &in.Manage, &out.Manage
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerSpec.
func (in *DockerSpec) DeepCopy() *DockerSpec {
	if in == nil {
		return nil
	}
	out := new(DockerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExclusiveGPUSpec) DeepCopyInto(out *ExclusiveGPUSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExclusiveGPUSpec.
func (in *ExclusiveGPUSpec) DeepCopy() *ExclusiveGPUSpec {
	if in == nil {
		return nil
	}
	out := new(ExclusiveGPUSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FencingSpec) DeepCopyInto(out *FencingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FencingSpec.
func (in *FencingSpec) DeepCopy() *FencingSpec {
	if in == nil {
		return nil
	}
	out := new(FencingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUSpec) DeepCopyInto(out *GPUSpec) {
	*out = *in
	if in.MIG != nil {
		in, out := &in.MIG, &out.MIG
		*out = new(MIGSpec)
		**out = **in
	}
	if in.TimeSlicing != nil {
		in, out := &in.TimeSlicing, &out.TimeSlicing
		*out = new(TimeSlicingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Exclusive != nil {
		in, out := &in.Exclusive, &out.Exclusive
		*out = new(ExclusiveGPUSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUSpec.
func (in *GPUSpec) DeepCopy() *GPUSpec {
	if in == nil {
		return nil
	}
	out := new(GPUSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeletSpec) DeepCopyInto(out *KubeletSpec) {
	*out = *in
	if in.MaxPods != nil {
		in, out := &in.MaxPods, &out.MaxPods
		*out = new(int32)
		**out = **in
	}
	if in.ContainerLogMaxFiles != nil {
		in, out := &in.ContainerLogMaxFiles, &out.ContainerLogMaxFiles
		*out = new(int32)
		**out = **in
	}
	if in.ResourceReservation != nil {
		in, out := &in.ResourceReservation, &out.ResourceReservation
		*out = new(ResourceReservationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TopologyManager != nil {
		in, out := &in.TopologyManager, &out.TopologyManager
		*out = new(TopologyManagerSpec)
		**out = **in
	}
	if in.MemorySwap != nil {
		in, out := &in.MemorySwap, &out.MemorySwap
		*out = new(MemorySwapSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeletSpec.
func (in *KubeletSpec) DeepCopy() *KubeletSpec {
	if in == nil {
		return nil
	}
	out := new(KubeletSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitedSwapSpec) DeepCopyInto(out *LimitedSwapSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitedSwapSpec.
func (in *LimitedSwapSpec) DeepCopy() *LimitedSwapSpec {
	if in == nil {
		return nil
	}
	out := new(LimitedSwapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MIGSpec) DeepCopyInto(out *MIGSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MIGSpec.
func (in *MIGSpec) DeepCopy() *MIGSpec {
	if in == nil {
		return nil
	}
	out := new(MIGSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineFailure) DeepCopyInto(out *MachineFailure) {
	*out = *in
	if in.LastOperation != nil {
		in, out := &in.LastOperation, &out.LastOperation
		*out = new(MachineLastOperation)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineFailure.
func (in *MachineFailure) DeepCopy() *MachineFailure {
	if in == nil {
		return nil
	}
	out := new(MachineFailure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineLastOperation) DeepCopyInto(out *MachineLastOperation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineLastOperation.
func (in *MachineLastOperation) DeepCopy() *MachineLastOperation {
	if in == nil {
		return nil
	}
	out := new(MachineLastOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemorySwapSpec) DeepCopyInto(out *MemorySwapSpec) {
	*out = *in
	if in.Swappiness != nil {
		in, out := &in.Swappiness, &out.Swappiness
		*out = new(int)
		**out = **in
	}
	if in.LimitedSwap != nil {
		in, out := &in.LimitedSwap, &out.LimitedSwap
		*out = new(LimitedSwapSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemorySwapSpec.
func (in *MemorySwapSpec) DeepCopy() *MemorySwapSpec {
	if in == nil {
		return nil
	}
	out := new(MemorySwapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroup) DeepCopyInto(out *NodeGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroup.
func (in *NodeGroup) DeepCopy() *NodeGroup {
	if in == nil {
		return nil
	}
	out := new(NodeGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroupList) DeepCopyInto(out *NodeGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroupList.
func (in *NodeGroupList) DeepCopy() *NodeGroupList {
	if in == nil {
		return nil
	}
	out := new(NodeGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroupSpec) DeepCopyInto(out *NodeGroupSpec) {
	*out = *in
	if in.CRI != nil {
		in, out := &in.CRI, &out.CRI
		*out = new(CRISpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CloudInstances != nil {
		in, out := &in.CloudInstances, &out.CloudInstances
		*out = new(CloudInstancesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.StaticInstances != nil {
		in, out := &in.StaticInstances, &out.StaticInstances
		*out = new(StaticInstancesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeTemplate != nil {
		in, out := &in.NodeTemplate, &out.NodeTemplate
		*out = new(NodeTemplate)
		(*in).DeepCopyInto(*out)
	}
	if in.Chaos != nil {
		in, out := &in.Chaos, &out.Chaos
		*out = new(ChaosSpec)
		**out = **in
	}
	if in.OperatingSystem != nil {
		in, out := &in.OperatingSystem, &out.OperatingSystem
		*out = new(OperatingSystemSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Disruptions != nil {
		in, out := &in.Disruptions, &out.Disruptions
		*out = new(DisruptionsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Kubelet != nil {
		in, out := &in.Kubelet, &out.Kubelet
		*out = new(KubeletSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(UpdateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Fencing != nil {
		in, out := &in.Fencing, &out.Fencing
		*out = new(FencingSpec)
		**out = **in
	}
	if in.GPU != nil {
		in, out := &in.GPU, &out.GPU
		*out = new(GPUSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeDrainTimeoutSecond != nil {
		in, out := &in.NodeDrainTimeoutSecond, &out.NodeDrainTimeoutSecond
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroupSpec.
func (in *NodeGroupSpec) DeepCopy() *NodeGroupSpec {
	if in == nil {
		return nil
	}
	out := new(NodeGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroupStatus) DeepCopyInto(out *NodeGroupStatus) {
	*out = *in
	if in.LastMachineFailures != nil {
		in, out := &in.LastMachineFailures, &out.LastMachineFailures
		*out = make([]MachineFailure, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConditionSummary != nil {
		in, out := &in.ConditionSummary, &out.ConditionSummary
		*out = new(ConditionSummary)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroupStatus.
func (in *NodeGroupStatus) DeepCopy() *NodeGroupStatus {
	if in == nil {
		return nil
	}
	out := new(NodeGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeTemplate) DeepCopyInto(out *NodeTemplate) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]corev1.Taint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeTemplate.
func (in *NodeTemplate) DeepCopy() *NodeTemplate {
	if in == nil {
		return nil
	}
	out := new(NodeTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotHeldResourcesSpec) DeepCopyInto(out *NotHeldResourcesSpec) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotHeldResourcesSpec.
func (in *NotHeldResourcesSpec) DeepCopy() *NotHeldResourcesSpec {
	if in == nil {
		return nil
	}
	out := new(NotHeldResourcesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotManagedCRISpec) DeepCopyInto(out *NotManagedCRISpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotManagedCRISpec.
func (in *NotManagedCRISpec) DeepCopy() *NotManagedCRISpec {
	if in == nil {
		return nil
	}
	out := new(NotManagedCRISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatingSystemSpec) DeepCopyInto(out *OperatingSystemSpec) {
	*out = *in
	if in.ManageKernel != nil {
		in, out := &in.ManageKernel, &out.ManageKernel
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatingSystemSpec.
func (in *OperatingSystemSpec) DeepCopy() *OperatingSystemSpec {
	if in == nil {
		return nil
	}
	out := new(OperatingSystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceReservationSpec) DeepCopyInto(out *ResourceReservationSpec) {
	*out = *in
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(StaticResourceReservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReservationSpec.
func (in *ResourceReservationSpec) DeepCopy() *ResourceReservationSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceReservationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingUpdateDisruptionSpec) DeepCopyInto(out *RollingUpdateDisruptionSpec) {
	*out = *in
	if in.Windows != nil {
		in, out := &in.Windows, &out.Windows
		*out = make([]DisruptionWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingUpdateDisruptionSpec.
func (in *RollingUpdateDisruptionSpec) DeepCopy() *RollingUpdateDisruptionSpec {
	if in == nil {
		return nil
	}
	out := new(RollingUpdateDisruptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StandbyHolderSpec) DeepCopyInto(out *StandbyHolderSpec) {
	*out = *in
	if in.OverprovisioningRate != nil {
		in, out := &in.OverprovisioningRate, &out.OverprovisioningRate
		*out = new(int)
		**out = **in
	}
	if in.NotHeldResources != nil {
		in, out := &in.NotHeldResources, &out.NotHeldResources
		*out = new(NotHeldResourcesSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StandbyHolderSpec.
func (in *StandbyHolderSpec) DeepCopy() *StandbyHolderSpec {
	if in == nil {
		return nil
	}
	out := new(StandbyHolderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticInstancesSpec) DeepCopyInto(out *StaticInstancesSpec) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticInstancesSpec.
func (in *StaticInstancesSpec) DeepCopy() *StaticInstancesSpec {
	if in == nil {
		return nil
	}
	out := new(StaticInstancesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticResourceReservation) DeepCopyInto(out *StaticResourceReservation) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.EphemeralStorage != nil {
		in, out := &in.EphemeralStorage, &out.EphemeralStorage
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticResourceReservation.
func (in *StaticResourceReservation) DeepCopy() *StaticResourceReservation {
	if in == nil {
		return nil
	}
	out := new(StaticResourceReservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSlicingSpec) DeepCopyInto(out *TimeSlicingSpec) {
	*out = *in
	if in.PartitionCount != nil {
		in, out := &in.PartitionCount, &out.PartitionCount
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSlicingSpec.
func (in *TimeSlicingSpec) DeepCopy() *TimeSlicingSpec {
	if in == nil {
		return nil
	}
	out := new(TimeSlicingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyManagerSpec) DeepCopyInto(out *TopologyManagerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyManagerSpec.
func (in *TopologyManagerSpec) DeepCopy() *TopologyManagerSpec {
	if in == nil {
		return nil
	}
	out := new(TopologyManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateSpec) DeepCopyInto(out *UpdateSpec) {
	*out = *in
	if in.MaxConcurrent != nil {
		in, out := &in.MaxConcurrent, &out.MaxConcurrent
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSpec.
func (in *UpdateSpec) DeepCopy() *UpdateSpec {
	if in == nil {
		return nil
	}
	out := new(UpdateSpec)
	in.DeepCopyInto(out)
	return out
}
