#!/usr/bin/env bash

# Copyright 2023 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /shell_lib.sh

function __config__(){
  cat <<EOF
configVersion: v1
kubernetesValidating:
- name: cni-cilium-module-config-policy.deckhouse.io
  group: main
  rules:
  - apiGroups:   ["deckhouse.io"]
    apiVersions: ["*"]
    operations:  ["CREATE", "UPDATE"]
    resources:   ["moduleconfigs"]
    scope:       "Cluster"
EOF
}

function __main__() {
  context::jq > /tmp/qqq

  bpfLBMode="$(context::jq  -r '.review.request.object.spec.settings.bpfLBMode // "Hybrid"')"
  tunnelMode="$(context::jq -r '.review.request.object.spec.settings.tunnelMode // "Disabled"')"

  if [[ "$tunnelMode" == "VXLAN" && "$bpfLBMode" != "SNAT" ]]; then
    cat <<EOF > "$VALIDATING_RESPONSE_PATH"
{"allowed":false, "message":"Can't use bpfLBMode '$bpfLBMode' with tunnelMode '$tunnelMode', the only option is 'SNAT'"}
EOF
    return 0
  fi

  cat <<EOF > "$VALIDATING_RESPONSE_PATH"
{"allowed":true}
EOF
}

hook::run "$@"
