{{- $moduleGateway := dict }}
{{- include "helm_lib_module_gateway" (list . $moduleGateway) }}
{{- if and $moduleGateway .Values.global.modules.publicDomainTemplate .Values.global.clusterIsBootstrapped }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  {{- include "helm_lib_module_labels" (list . (dict "app" "hubble-ui")) | nindent 2 }}
  name: hubble
  namespace: d8-cni-cilium
spec:
  listeners:
{{- if (include "helm_lib_module_https_route_tls_enabled" .) }}
  - allowedRoutes:
      namespaces:
        from: Same
    hostname: {{ include "helm_lib_module_public_domain" (list . "hubble") }}
    name: hubble
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: {{ include "helm_lib_module_https_secret_name" (list . "httproute-tls") }}
        namespace: d8-cni-cilium
      mode: Terminate
  - allowedRoutes:
      namespaces:
        from: Same
    hostname: {{ include "helm_lib_module_public_domain" (list . "hubble") }}
    name: hubble-redirect
    port: 80
    protocol: HTTP
{{- else }}
  - allowedRoutes:
      namespaces:
        from: Same
    hostname: {{ include "helm_lib_module_public_domain" (list . "hubble") }}
    name: hubble
    port: 80
    protocol: HTTP
{{- end }}
  parentRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ $moduleGateway.name }}
    namespace: {{ $moduleGateway.namespace }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hubble-ui
  namespace: d8-cni-cilium
  annotations:
    web.deckhouse.io/export-name: "cilium"
    web.deckhouse.io/export-icon: "https://cilium.io/icons/icon-144x144.png?v=81b4389fe4c26dfd1769148aa2f50bb0"
    alb.network.deckhouse.io/session-affinity: '{"mode":"cookie","path":"/","cookieName":"d8-hubble-affinity","ttl":0}'
    alb.network.deckhouse.io/backend-tls-settings: '{"mode": "MUTUAL", "caCertificates": "/etc/kube-rbac-proxy-client-ssl/ca.crt", "clientCertificate": "/etc/kube-rbac-proxy-client-ssl/client.crt", "privateKey": "/etc/kube-rbac-proxy-client-ssl/client.key", "insecureSkipVerify": true}'
  {{- if or (eq (include "helm_lib_module_https_mode" .) "CertManager") (eq (include "helm_lib_module_https_mode" .) "CustomCertificate") }}
    alb.network.deckhouse.io/response-headers-to-add: '{"Strict-Transport-Security":"max-age=31536000; includeSubDomains"}'
  {{- end }}
  {{- if and (ne (include "helm_lib_module_https_mode" .) "Disabled") .Values.ciliumHubble.auth.externalAuthentication }}
    alb.network.deckhouse.io/auth-signin: {{ replace "$host" (include "helm_lib_module_public_domain" (list . "hubble")) .Values.ciliumHubble.auth.externalAuthentication.authSignInURL | quote }}
    alb.network.deckhouse.io/auth-url: {{ .Values.ciliumHubble.auth.externalAuthentication.authURL | quote }}
  {{- else }}
    alb.network.deckhouse.io/basic-auth-secret: d8-cni-cilium/hubble-basic-auth
  {{- end }}
  {{- if .Values.ciliumHubble.auth.whitelistSourceRanges }}
    alb.network.deckhouse.io/whitelist-source-range: {{ .Values.ciliumHubble.auth.whitelistSourceRanges | join "," }}
  {{- end }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "hubble-ui")) | nindent 2 }}
spec:
  hostnames:
  - {{ include "helm_lib_module_public_domain" (list . "hubble") }}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: ListenerSet
    name: hubble
    namespace: d8-cni-cilium
    sectionName: hubble
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: hubble-ui
      port: 443
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
{{- if (include "helm_lib_module_https_route_tls_enabled" .) }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hubble-ui-redirect
  namespace: d8-cni-cilium
  {{- include "helm_lib_module_labels" (list . (dict "app" "hubble-ui")) | nindent 2 }}
spec:
  hostnames:
  - {{ include "helm_lib_module_public_domain" (list . "hubble") }}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: ListenerSet
    name: hubble
    namespace: d8-cni-cilium
    sectionName: hubble-redirect
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
    matches:
    - path:
        type: PathPrefix
        value: /
{{- end }}
{{- end }}
