positive:
  values:
  - kubeconfigGenerator:
    - id: abc-1
      masterURI: example.com
  - rateLimit:
      enabled: true
      perIP:
        requestsPerMinute: 30
        burst: 10
  - passwordPolicy:
      lockout:
        maxAttempts: 5
        lockDuration: 10m
        applyToConnectors: ["LDAP", "Crowd"]
  - passwordPolicy:
      complexityLevel: Custom
      custom:
        minLength: 10
        specialCharacters: true
        numbers: false
        capitalized: true
        repeatedChars: false
negative:
  values:
  - kubeconfigGenerator:
    - id: ABC-1
      masterURI: example.com
  - rateLimit:
      enabled: true
      perIP:
        requestsPerMinute: 0
        burst: 10
  - passwordPolicy:
      lockout:
        maxAttempts: 5
        lockDuration: 10m
        applyToConnectors: ["okta"]
  - passwordPolicy:
      complexityLevel: Custom
  - passwordPolicy:
      complexityLevel: Fair
      custom:
        minLength: 10
