apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: d8dnspolicy
  labels:
    heritage: deckhouse
    module: admission-policy-engine
    security.deckhouse.io: operation-policy
  annotations:
    metadata.gatekeeper.sh/title: "DNS Policy."
    metadata.gatekeeper.sh/version: 1.0.0
    description: "Pods with hostNetwork must have 'ClusterFirstWithHostNet' policy."
spec:
  crd:
    spec:
      names:
        kind: D8DNSPolicy
  targets:
    - target: admission.k8s.gatekeeper.sh
      code:
        - engine: Rego
          source:
            version: "v1"
            libs:
              - |
                {{- include "constraint-templates.lib.common.container-review" . | nindent 16 }}
            rego: |
              package d8.operation_policies

              import data.lib.common.pod_spec

              violation contains {"msg": msg} if {
                not input.review.operation == "DELETE"
                hostNetwork := object.get(pod_spec, "hostNetwork", false)
                hostNetwork == true
                dnsPolicy := object.get(pod_spec, "dnsPolicy", "")
                dnsPolicy != "ClusterFirstWithHostNet"
                msg := get_message(input.review.object.metadata.name)
              }

              get_message(name) := message if {
                message := sprintf("Workload <%v> with hostNetwork must have 'ClusterFirstWithHostNet' dnsPolicy", [name])
              }
