apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: d8imagepullpolicy
  labels:
    heritage: deckhouse
    module: admission-policy-engine
    security.deckhouse.io: operation-policy
  annotations:
    metadata.gatekeeper.sh/title: "Image Pull Policy"
    metadata.gatekeeper.sh/version: 1.0.0
    description: "Required image pull policy for containers."
spec:
  crd:
    spec:
      names:
        kind: D8ImagePullPolicy
      validation:
        openAPIV3Schema:
          type: object
          properties:
            policy:
              type: string
              description: "A list of available image pull policies."
              enum:
                - Always
                - IfNotPresent
  targets:
    - target: admission.k8s.gatekeeper.sh
      code:
        - engine: Rego
          source:
            version: "v1"
            libs:
              - |
                {{- include "constraint-templates.lib.common.container-review" . | nindent 16 }}
            rego: |
              package d8.operation_policies

              import data.lib.common.input_containers

              violation contains {"msg": msg} if {
                not input.review.operation == "DELETE"
                required := input.parameters.policy
                container := input_containers[_]
                provided := object.get(container, "imagePullPolicy", "")
                required != provided
                msg := sprintf("Container <%v> in your %v <%v> has invalid pull policy: <%v>", [container.name, input.review.kind.kind, input.review.object.metadata.name, provided])
              }
