#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 1
    kubernetes:
    - name: pvc
      includeSnapshotsFrom: ["pvc"]
      apiVersion: v1
      kind: PersistentVolumeClaim
      labelSelector:
        matchLabels:
          app: openvpn
      jqFilter: ".spec.storageClassName"
EOF
}

function __main__() {
  if context::has snapshots.pvc.0 ; then
    values::set openvpn.internal.currentStorageClass "$(context::get snapshots.pvc.0.object.spec.storageClassName)"
  else
    values::unset openvpn.internal.currentStorageClass
  fi
}

hook::run $@
