#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p beforeHelm=15
}

function __main__() {
  if ! values::array_has global.enabledModules "user-authn"; then
    if ! values::has openvpn.adminPassword ; then
      values::set --config openvpn.password $(values::generate_password)
    fi
  else
    values::unset --config openvpn.password
  fi
}

hook::run $@
