#!/bin/bash

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  jo -p beforeHelm=15
}

function __main__() {
  if ! values::has openvpn.auth.externalAuthentication ; then
    if ! values::has openvpn.auth.password ; then
      if ! values::has --config openvpn.auth ; then
        values::set --config openvpn.auth {}
      fi
      values::set --config openvpn.auth.password $(values::generate_password)
    fi
  else
    values::unset --config openvpn.auth.password
    if [[ $(values::get --config openvpn.auth) == '{}' ]]; then
      values::unset --config openvpn.auth {}
    fi
  fi
}

hook::run $@
