#!/bin/bash

### Миграция 2019-07-24: https://github.com/deckhouse/deckhouse/merge_requests/912
#
# Этот хук можно удалить, после выката на все кластера.

source /antiopa/shell_lib.sh

function __config__() {
  jo -p beforeHelm=10
}

function __main__() {
  if ! values::array_has global.enabledModules "user-authn"; then
    if values::has openvpn.adminPassword ; then
      values::set --config openvpn.password $(values::get --config openvpn.adminPassword)
      values::unset --config openvpn.adminPassword
    fi
  fi
}

hook::run $@
