#!/bin/bash

source /deckhouse/shell_lib.sh


### Миграция 2020-01-20
# Удалить после выката версии на все инстансы

function __config__() {
  jo -p onStartup=10 configVersion=v1
}

function __main__() {
  if ! values::has --config openvpn.externalAuthentication && ! values::has --config openvpn.password && ! values::has --config openvpn.allowedUserGroups ; then
    return 0
  fi

  values::set --config openvpn.auth {}

  if values::has --config openvpn.externalAuthentication ; then
    values::set --config openvpn.auth.externalAuthentication "$(values::get --config openvpn.externalAuthentication)"
    values::unset --config openvpn.externalAuthentication
  fi

  if values::has --config openvpn.password ; then
    values::set --config openvpn.auth.password "$(values::get --config openvpn.password)"
    values::unset --config openvpn.password
  fi

  if values::has --config openvpn.allowedUserGroups ; then
    values::set --config openvpn.auth.allowedUserGroups "$(values::get --config openvpn.allowedUserGroups)"
    values::unset --config openvpn.allowedUserGroups
  fi
}

hook::run $@
