#!/bin/bash

# Copyright 2021 Flant CJSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/ee/LICENSE

source /deckhouse/shell_lib.sh

function __main__() {
  enabled::disable_module_if_cluster_is_not_bootstraped
  enabled::fail_if_values_are_not_set global.discovery.serviceSubnet
  echo "true" > $MODULE_ENABLED_RESULT
}

enabled::run $@
