//go:build !ignore_autogenerated

/*
Copyright 2026 Flant JSC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicablePolicy) DeepCopyInto(out *ApplicablePolicy) {
	*out = *in
	if in.Allowed != nil {
		in, out := &in.Allowed, &out.Allowed
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicablePolicy.
func (in *ApplicablePolicy) DeepCopy() *ApplicablePolicy {
	if in == nil {
		return nil
	}
	out := new(ApplicablePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailableClusterObjectRef) DeepCopyInto(out *AvailableClusterObjectRef) {
	*out = *in
	if in.StatusFields != nil {
		in, out := &in.StatusFields, &out.StatusFields
		*out = make([]AvailableClusterObjectStatusField, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailableClusterObjectRef.
func (in *AvailableClusterObjectRef) DeepCopy() *AvailableClusterObjectRef {
	if in == nil {
		return nil
	}
	out := new(AvailableClusterObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailableClusterObjectStatusField) DeepCopyInto(out *AvailableClusterObjectStatusField) {
	*out = *in
	out.Descriptions = in.Descriptions
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailableClusterObjectStatusField.
func (in *AvailableClusterObjectStatusField) DeepCopy() *AvailableClusterObjectStatusField {
	if in == nil {
		return nil
	}
	out := new(AvailableClusterObjectStatusField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObjectGrantPolicy) DeepCopyInto(out *ClusterObjectGrantPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObjectGrantPolicy.
func (in *ClusterObjectGrantPolicy) DeepCopy() *ClusterObjectGrantPolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterObjectGrantPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterObjectGrantPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObjectGrantPolicyList) DeepCopyInto(out *ClusterObjectGrantPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterObjectGrantPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObjectGrantPolicyList.
func (in *ClusterObjectGrantPolicyList) DeepCopy() *ClusterObjectGrantPolicyList {
	if in == nil {
		return nil
	}
	out := new(ClusterObjectGrantPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterObjectGrantPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObjectGrantPolicySpec) DeepCopyInto(out *ClusterObjectGrantPolicySpec) {
	*out = *in
	out.GrantedResource = in.GrantedResource
	if in.UsageReferences != nil {
		in, out := &in.UsageReferences, &out.UsageReferences
		*out = make([]GrantedResourceUsageReference, len(*in))
		copy(*out, *in)
	}
	if in.ObjectPolicyStatusFields != nil {
		in, out := &in.ObjectPolicyStatusFields, &out.ObjectPolicyStatusFields
		*out = make(ObjectPolicyStatusFields, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObjectGrantPolicySpec.
func (in *ClusterObjectGrantPolicySpec) DeepCopy() *ClusterObjectGrantPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterObjectGrantPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObjectGrantPolicyStatus) DeepCopyInto(out *ClusterObjectGrantPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObjectGrantPolicyStatus.
func (in *ClusterObjectGrantPolicyStatus) DeepCopy() *ClusterObjectGrantPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterObjectGrantPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObjectsGrant) DeepCopyInto(out *ClusterObjectsGrant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObjectsGrant.
func (in *ClusterObjectsGrant) DeepCopy() *ClusterObjectsGrant {
	if in == nil {
		return nil
	}
	out := new(ClusterObjectsGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterObjectsGrant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObjectsGrantList) DeepCopyInto(out *ClusterObjectsGrantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterObjectsGrant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObjectsGrantList.
func (in *ClusterObjectsGrantList) DeepCopy() *ClusterObjectsGrantList {
	if in == nil {
		return nil
	}
	out := new(ClusterObjectsGrantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterObjectsGrantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObjectsGrantSpec) DeepCopyInto(out *ClusterObjectsGrantSpec) {
	*out = *in
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]ApplicablePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObjectsGrantSpec.
func (in *ClusterObjectsGrantSpec) DeepCopy() *ClusterObjectsGrantSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterObjectsGrantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObjectsGrantStatus) DeepCopyInto(out *ClusterObjectsGrantStatus) {
	*out = *in
	if in.Available != nil {
		in, out := &in.Available, &out.Available
		*out = make(map[string][]AvailableClusterObjectRef, len(*in))
		for key, val := range *in {
			var outVal []AvailableClusterObjectRef
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]AvailableClusterObjectRef, len(*in))
				for i := range *in {
					(*in)[i].DeepCopyInto(&(*out)[i])
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObjectsGrantStatus.
func (in *ClusterObjectsGrantStatus) DeepCopy() *ClusterObjectsGrantStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterObjectsGrantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrantedResource) DeepCopyInto(out *GrantedResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.Defaults = in.Defaults
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrantedResource.
func (in *GrantedResource) DeepCopy() *GrantedResource {
	if in == nil {
		return nil
	}
	out := new(GrantedResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrantedResourceDefaultingCriteria) DeepCopyInto(out *GrantedResourceDefaultingCriteria) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrantedResourceDefaultingCriteria.
func (in *GrantedResourceDefaultingCriteria) DeepCopy() *GrantedResourceDefaultingCriteria {
	if in == nil {
		return nil
	}
	out := new(GrantedResourceDefaultingCriteria)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrantedResourceUsageReference) DeepCopyInto(out *GrantedResourceUsageReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrantedResourceUsageReference.
func (in *GrantedResourceUsageReference) DeepCopy() *GrantedResourceUsageReference {
	if in == nil {
		return nil
	}
	out := new(GrantedResourceUsageReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectPolicyStatusField) DeepCopyInto(out *ObjectPolicyStatusField) {
	*out = *in
	out.Descriptions = in.Descriptions
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectPolicyStatusField.
func (in *ObjectPolicyStatusField) DeepCopy() *ObjectPolicyStatusField {
	if in == nil {
		return nil
	}
	out := new(ObjectPolicyStatusField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ObjectPolicyStatusFields) DeepCopyInto(out *ObjectPolicyStatusFields) {
	{
		in := &in
		*out = make(ObjectPolicyStatusFields, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectPolicyStatusFields.
func (in ObjectPolicyStatusFields) DeepCopy() ObjectPolicyStatusFields {
	if in == nil {
		return nil
	}
	out := new(ObjectPolicyStatusFields)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStatusFieldDescription) DeepCopyInto(out *ObjectStatusFieldDescription) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStatusFieldDescription.
func (in *ObjectStatusFieldDescription) DeepCopy() *ObjectStatusFieldDescription {
	if in == nil {
		return nil
	}
	out := new(ObjectStatusFieldDescription)
	in.DeepCopyInto(out)
	return out
}
