#!/bin/bash

# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# shellcheck disable=SC2174

set -Eeuo pipefail
shopt -s inherit_errexit
shopt -s failglob

function nginx_reload() {
  if ! >&2 diff -u /etc/nginx/nginx.conf /etc/nginx/nginx_new.conf && nginx -t -c /etc/nginx/nginx_new.conf; then
    >&2 echo "nginx.conf changed!"
    cp /etc/nginx/nginx_new.conf /etc/nginx/nginx.conf
    kill -s SIGHUP $(pidof nginx)
  fi
}

while true; do
  nginx_reload
  inotifywait -q -e modify,move_self /etc/nginx/nginx_new.conf
done
