#!/bin/bash

# Copyright 2021 Flant CJSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    afterHelm: 10
    kubernetes:
    - name: secrets
      keepFullObjectsInMemory: false
      queue: /modules/$(module::name::kebab_case)
      apiVersion: v1
      kind: Secret
      namespace:
        nameSelector:
          matchNames: [d8-monitoring]
      labelSelector:
        matchLabels:
          additional-configs-for-prometheus: main
EOF
}

function __main__() {
  kubectl -n d8-monitoring get secret -ladditional-configs-for-prometheus=main -o json | \
  jq '[.items[].data]
    | reduce .[] as $i
      (
        {"alert-managers.yaml": "", "alert-relabels.yaml": "", "scrapes.yaml": ""};
          ."alert-managers.yaml" += "\n" + ($i."alert-managers.yaml" // "" | @base64d)
        | ."alert-relabels.yaml" += "\n" + ($i."alert-relabels.yaml" // "" | @base64d)
        | ."scrapes.yaml"        += "\n" + ($i."scrapes.yaml"        // "" | @base64d)
      )
    |
      {
        "apiVersion": "v1",
        "kind": "Secret",
        "metadata": {"name": "prometheus-main-additional-configs"},
        "type": "Opaque",
        "data":
        {
          "alert-managers.yaml": (."alert-managers.yaml" | @base64),
          "alert-relabels.yaml": (."alert-relabels.yaml" | @base64),
          "scrapes.yaml":        (."scrapes.yaml"        | @base64)
        }
      }' | \
  kubectl -n d8-monitoring apply -f -
}

hook::run "$@"
