#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  jo -p afterHelm=10
}

function __main__() {
  if kubectl -n d8-monitoring get statefulset/prometheus-main -o json 2>/dev/null | jq -e '.spec.volumeClaimTemplates' >/dev/null; then
    as_is=$(kubectl -n d8-monitoring get pvc prometheus-main-db-prometheus-main-0 -o json | jq -r '.spec.storageClassName')
    to_be=$(kubectl -n d8-monitoring get statefulset/prometheus-main -o json | jq '.spec.volumeClaimTemplates[0].spec.storageClassName' -r)

    if [[ "$as_is" != "$to_be" ]] ; then
      kubectl -n d8-monitoring delete statefulset/prometheus-main
      kubectl -n d8-monitoring delete pvc -l app=prometheus,prometheus=main
    fi
  fi

  if kubectl -n d8-monitoring get statefulset/prometheus-longterm -o json 2>/dev/null | jq -e '.spec.volumeClaimTemplates' >/dev/null; then
    as_is=$(kubectl -n d8-monitoring get pvc prometheus-longterm-db-prometheus-longterm-0 -o json | jq -r '.spec.storageClassName')
    to_be=$(kubectl -n d8-monitoring get statefulset/prometheus-longterm -o json | jq '.spec.volumeClaimTemplates[0].spec.storageClassName' -r)

    if [[ "$as_is" != "$to_be" ]] ; then
      kubectl -n d8-monitoring delete statefulset/prometheus-longterm
      kubectl -n d8-monitoring delete pvc -l app=prometheus,prometheus=longterm
    fi
  fi

  if kubectl -n d8-monitoring get statefulset/grafana -o json 2>/dev/null | jq -e '.spec.volumeClaimTemplates' >/dev/null; then
    as_is=$(kubectl -n d8-monitoring get pvc grafana-storage-grafana-0 -o json | jq -r '.spec.stprageClassName')
    to_be=$(kubectl -n d8-monitoring get statefulset/grafana -o json | jq '.spec.VolumeClaimTemplates[0].spec.storageClassName' -r)

    if [[ "$as_is" != "$to_be" ]] ; then
      kubectl -n d8-monitoring delete statefulset/grafana
      kubectl -n d8-monitoring delete pvc -l app=grafana
    fi
  fi
}

hook::run $@
