#!/bin/bash

### Миграция 2019-09-16: https://github.com/deckhouse/deckhouse/merge_requests/1100/
# Данный хук можно удалить, после выката на все инсталяции

source /antiopa/shell_lib.sh

function __config__() {
  jo -p beforeHelm=1
}

function __main__() {
  if kubectl -n kube-prometheus  get secret prometheus-api-client-cert 2>/dev/null >/dev/null ; then
    kubectl -n kube-prometheus delete secret prometheus-api-client-cert 2>/dev/null >/dev/null
  fi

  if kubectl -n kube-prometheus  get secret prometheus-scraper-cert 2>/dev/null >/dev/null ; then
    kubectl -n kube-prometheus delete secret prometheus-scraper-cert 2>/dev/null >/dev/null
  fi
}

hook::run "$@"

