#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p beforeHelm=10
}

function __main__() {
  if ! values::has prometheus.adminPassword ; then
    password=$(makepasswd -c 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ -l 20)
    values::set --config prometheus.adminPassword $password
  fi

  if ! values::has prometheus.userPassword ; then
    password=$(makepasswd -c 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ -l 20)
    values::set --config prometheus.userPassword $password
  fi
}

hook::run $@
