#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p beforeHelm=10
}

function __main__() {
  if ! values::has prometheus.adminPassword ; then
    values::set --config prometheus.adminPassword $(values::generate_password)
  fi

  if ! values::has prometheus.userPassword ; then
    values::set --config prometheus.userPassword $(values::generate_password)
  fi
}

hook::run $@
