#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 10
EOF
}

function __main__() {
  if ! values::has prometheus.auth.externalAuthentication ; then
    if ! values::has prometheus.auth.password ; then
      if ! values::has --config prometheus.auth ; then
        values::set --config prometheus.auth {}
      fi
      values::set --config prometheus.auth.password $(tools::generate_password)
    fi
  else
    values::unset --config prometheus.auth.password
    if [[ $(values::get --config prometheus.auth) == '{}' ]]; then
      values::unset --config prometheus.auth {}
    fi
  fi
}

hook::run $@
