#!/bin/bash

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  jo -p beforeHelm=10
}

function __main__() {
  if ! values::has prometheus.auth.externalAuthentication ; then
    if ! values::has prometheus.auth.password ; then
      if ! values::has --config prometheus.auth ; then
        values::set --config prometheus.auth {}
      fi
      values::set --config prometheus.auth.password $(values::generate_password)
    fi
  else
    values::unset --config prometheus.auth.password
    if [[ $(values::get --config prometheus.auth) == '{}' ]]; then
      values::unset --config prometheus.auth {}
    fi
  fi
}

hook::run $@
