#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  echo '
{
  "beforeHelm": 0,
  "schedule": [
    {
      "crontab": "*/5 * * * *"
    }
  ]
}'
}

function __main__() {
  project=$(values::get --required global.project)

  if values::has prometheus.madisonAuthKey ; then
    uri=/api/$project/self_status/$(values::get --required prometheus.madisonAuthKey)
    response=$(curl -s -w '\n{"http_code": "%{http_code}"}\n' https://madison.flant.com$uri | jq -s add)

    if [[ "$(echo "$response" | jq -r '.http_code')" == "401" ]] && [[ "$(echo "$response" | jq -r '.error')" == "Archived setup" ]] ; then
      values::set --config prometheus.madisonSelfSetupKey false
      values::unset --config prometheus.madisonAuthKey
    fi
  fi
}

hook::run $@
