#!/bin/bash

### Миграция 2019-08-02: https://github.com/deckhouse/deckhouse/merge_requests/978
#
# Этот хук можно удалить, после выката данного MR'а на все инсталяции.

source /antiopa/shell_lib.sh

function __config__() {
  jo -p onStartup=1
}

function __main__() {
  if values::has --config prometheus.certificateForIngress ; then
    values::set --config prometheus.https "{}"

    if values::has --config prometheus.certificateForIngress.certmanagerClusterIssuerName && values::is_false --config prometheus.certificateForIngress.certmanagerClusterIssuerName && values::has --config prometheus.certificateForIngress.customCertificateSecretName && values::is_false --config prometheus.certificateForIngress.customCertificateSecretName ; then
      values::set --config prometheus.https.mode "Disabled"
    elif values::has --config prometheus.certificateForIngress.certmanagerClusterIssuerName && ! values::is_false --config prometheus.certificateForIngress.certmanagerClusterIssuerName ; then
      values::set --config prometheus.https.certManager "{}"
      values::set --config prometheus.https.certManager.clusterIssuerName "$(values::get --config prometheus.certificateForIngress.certmanagerClusterIssuerName)"
      values::set --config prometheus.https.mode "CertManager"
    elif values::has --config prometheus.certificateForIngress.customCertificateSecretName && ! values::is_false --config prometheus.certificateForIngress.customCertificateSecretName ; then
      values::set --config prometheus.https.customCertificate "{}"
      values::set --config prometheus.https.customCertificate.secretName "$(values::get --config prometheus.certificateForIngress.customCertificateSecretName)"
      values::set --config prometheus.https.mode "CustomCertificate"
    fi

    values::unset --config prometheus.certificateForIngress
  fi
}

hook::run "$@"
