#!/bin/bash

source /deckhouse/shell_lib.sh


### Миграция 2020-01-20
# Удалить после выката версии на все инстансы

function __config__() {
  jo -p onStartup=10 configVersion=v1
}

function __main__() {
  if ! values::has --config prometheus.externalAuthentication && values::has --config prometheus.password && ! values::has --config prometheus.allowedUserGroups ; then
    return 0
  fi

  values::set --config prometheus.auth {}

  if values::has --config prometheus.externalAuthentication ; then
    values::set --config prometheus.auth.externalAuthentication "$(values::get --config prometheus.externalAuthentication)"
    values::unset --config prometheus.externalAuthentication
  fi

  if values::has --config prometheus.password ; then
    values::set --config prometheus.auth.password "$(values::get --config prometheus.password)"
    values::unset --config prometheus.password
  fi

  if values::has --config prometheus.allowedUserGroups ; then
    values::set --config prometheus.auth.allowedUserGroups "$(values::get --config prometheus.allowedUserGroups)"
    values::unset --config prometheus.allowedUserGroups
  fi
}

hook::run $@
