#!/bin/bash

### Миграция 2019-07-24: https://github.com/deckhouse/deckhouse/merge_requests/912
#
# Этот хук можно удалить, после выката на все кластера.

source /antiopa/shell_lib.sh

function __config__() {
  jo -p beforeHelm=5
}

function __main__() {
  if ! values::array_has global.enabledModules "user-authn" ; then
    if values::has prometheus.adminPassword ; then
      values::set --config prometheus.password $(values::get --config prometheus.adminPassword)
      values::unset --config prometheus.adminPassword
    fi

    if values::has prometheus.userPassword ; then
      values::unset --config prometheus.userPassword
    fi
  fi
}

hook::run "$@"
