#!/bin/bash

### Migration 23.10.2020: Remove in final `domain migration` release

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: alertmanagers
      group: main
      queue: /modules/$(module::name::kebab_case)
      apiVersion: monitoring.coreos.com/v1
      kind: Alertmanager
      keepFullObjectsInMemory: false
      labelSelector:
        matchExpressions:
        - key: heritage
          operator: NotIn
          values: ["deckhouse"]
      jqFilter: &filter |
        {
          "name": .metadata.name,
          "kind": .kind,
          "namespace": .metadata.namespace,
          "usedNodeSelectorsAndTolerations":
            (
              [.spec.nodeSelector // {} | to_entries[] | select((.key | startswith("node-role.flant.com/")) and .value == "") | .key | split("/")[1] | select(. // empty)] +
              [(.spec.affinity.nodeAffinity | .. | .matchExpressions? // []) | .[] | select(.key | startswith("node-role.flant.com/")) | .key | split("/")[1] | select(. // empty)] +
              [.spec.tolerations // [] | .[] | select(.key=="dedicated.flant.com") | .value // "_wildcard_"]
            ) | unique
        }
    - name: prometheuses
      group: main
      queue: /modules/$(module::name::kebab_case)
      apiVersion: monitoring.coreos.com/v1
      kind: Prometheus
      keepFullObjectsInMemory: false
      labelSelector:
        matchExpressions:
        - key: heritage
          operator: NotIn
          values: ["deckhouse"]
      jqFilter: *filter
EOF
}

function __main__() {
  reserved="$(values::get global.enabledModules | jq -r '. + ["monitoring", "system", "frontend"] + ["_wildcard_"] | join("|")')"
  group="/modules/$(module::name::kebab_case)/migrate_domain_alert#migrate_domain_resources"

  context::jq -c --arg reserved "$reserved" --arg group "$group" '
    .. | .filterResult? | select(.) |
    if ([.usedNodeSelectorsAndTolerations[] | select(.| test("^(\($reserved))$"))] | length > 0) then
      {
        "name": "migrate_domain_resources",
        "group": "\($group)",
        "set": 1,
        "labels":
        {
          "name": .name,
          "kind": .kind,
          "namespace": .namespace
        }
      }
    else empty end
    ' >> $METRICS_PATH

  # Used to hack metrics deletion
  jq -c --arg group "$group" '.group = $group' <<< '{"name": "migrate_domain_resources", "set": 0, "labels": {"name": "none", "kind": "none", "namespace": "none"}}' >> $METRICS_PATH
}

hook::run $@
