#!/bin/bash

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  common_hooks::certificates::order_certificate::config
}

function __main__() {
  common_hooks::certificates::order_certificate::main "d8-monitoring" "prometheus-scraper-tls" "d8-monitoring:scraper" "internal.prometheusScraperTLS"
}

hook::run "$@"
