#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  common_hooks::certificates::order_certificate::config
}

function __main__() {
  common_hooks::certificates::order_certificate::main "kube-prometheus" "prometheus-scraper-tls" "kube-prometheus:scraper" "internal.prometheusScraperTLS"
}

hook::run "$@"
