#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  legacy::common_hooks::certificates::order_certificate::config
}

function __main__() {
  legacy::common_hooks::certificates::order_certificate::main "d8-monitoring" "prometheus-scraper-tls" "d8-monitoring:scraper" "internal.prometheusScraperTLS"
}

hook::run "$@"
