#!/bin/bash

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  common_hooks::https::copy_custom_certificate::config
}

function __main__() {
  common_hooks::https::copy_custom_certificate::main "d8-user-authn" "ingress-tls"
}

hook::run "$@"
