#!/bin/bash

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  common_hooks::https::copy_custom_certificate::config
}

function __main__() {
  if ! values::is_true userAuthn.publishAPI.enable ; then
    return 0
  fi

  if [[ "$(values::get userAuthn.publishAPI.https.mode)" == "Global" ]]; then
    if [[ "$(values::get_first_defined userAuthn.https.mode global.modules.https.mode)" == "CustomCertificate" ]] ; then
      common_hooks::https::copy_custom_certificate::main "d8-user-authn" "kubernetes-tls"
    fi
  fi
}

hook::run "$@"
