#!/usr/bin/env python3

from deckhouse import hook
from dotmap import DotMap


config = f"""
configVersion: v1
kubernetes:
  - name: groups
    apiVersion: deckhouse.io/v1alpha1
    kind: Group
    queue: "groups"
    group: main
    executeHookOnEvent: []
    executeHookOnSynchronization: false
    keepFullObjectsInMemory: false
    jqFilter: |
      {
        "name": .metadata.name,
        "groupName": .spec.name
      }
kubernetesValidating:
- name: groups-unique.deckhouse.io
  group: main
  rules:
  - apiGroups:   ["deckhouse.io"]
    apiVersions: ["*"]
    operations:  ["CREATE", "UPDATE"]
    resources:   ["groups"]
    scope:       "Cluster"
"""


def main(ctx: hook.Context):
    print(ctx)


if __name__ == "__main__":
    hook.run(main, config=config)
