apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    heritage: deckhouse
    module: kube-proxy
    rbac.deckhouse.io/aggregate-to-kubernetes-as: viewer
    rbac.deckhouse.io/aggregate-to-networking-as: viewer
    rbac.deckhouse.io/kind: capability
    rbac.deckhouse.io/capability: "system-capability.kube-proxy.view"
    rbac.deckhouse.io/scope: system
    rbac.deckhouse.io/namespace: kube-system
  name: d8:system-capability:kube-proxy:view
  annotations:
    en.meta.deckhouse.io/title: "Module kube-proxy: view configuration"
    ru.meta.deckhouse.io/title: "Модуль kube-proxy: просмотр конфигурации"
    en.meta.deckhouse.io/description: "Read-only access to the kube-proxy module configuration."
    ru.meta.deckhouse.io/description: "Доступ только на чтение к конфигурации модуля kube-proxy."
rules:
- apiGroups:
  - deckhouse.io
  resourceNames:
  - kube-proxy
  resources:
  - moduleconfigs
  verbs:
  - get
  - list
  - watch
