#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
# TODO
#  jo -p beforeHelm=20 onKubernetesEvent="$(jo -a \
#    "$(jo kind=node jqFilter=".status.addresses" disableDebug=true)" \
#  )"
  cat << EOF
    configVersion: v1
    beforeHelm: 20
    schedule:
    - name: update_ds
      queue: /modules/$(module::name::kebab_case)/update_ds
      crontab: "* * * * *"
EOF
}

function __main__() {
  targets=$(kubectl get no -o json | jq -c '{cluster_targets:[.items[] | select(.status.addresses) | { name: (.metadata.name), ipAddress: (.status.addresses | map (select(.type=="InternalIP").address) | first) }] | sort}')

  external_targets=$(values::get --config monitoringPing.externalTargets | jq '{external_targets: .}')
  if [ -n "$external_targets" ]; then
    targets=$(jq -n --argjson cluster_targets "$targets" --argjson external_targets "$external_targets" '$cluster_targets + $external_targets')
  fi
  values::set monitoringPing.targets "$targets"
}

hook::run $@
