#!/bin/bash

source /antiopa/shell_lib.sh

# Миграция 2018-03-13, https://github.com/deckhouse/deckhouse/merge_requests/88
# Внимание! Все это нужно только на момент перехода и может быть полностью удалено после.
if [[ "$(kubectl -n kube-nginx-ingress get ds/nginx -o json | jq .metadata.labels.heritage -r)" == "antiopa" ]] ; then
  exit 0
fi

# inlet
if kubectl -n kube-nginx-ingress get ds/bm-fallback > /dev/null 2> /dev/null; then
  if [[ $(cluster::type) != "Manual" && $(cluster::type) != "ACS" ]] ; then
    inlet=Direct
  fi
fi

# config.hsts
res=$(kubectl -n kube-nginx-ingress get cm/nginx -o json | jq '.data.hsts' -r)
if [[ "$res" == "null" || "$res" == "true" ]] ; then
  hsts=true
fi

# config.setRealIPFrom
res=$(kubectl -n kube-nginx-ingress get cm/nginx -o json | jq '.data."proxy-real-ip-cidr"' -r)
if [[ "$res" != "0.0.0.0/32" ]] ; then
  if [[ $(cluster::type) != "AWS" ]] ; then
    set_real_ip_from=$res
  fi
fi

# render
if [[ -n $inlet || -n $hsts || -n $set_real_ip_from ]] ; then
  echo "nginxIngress:"

  if [[ -n $inlet ]] ; then
    echo "  inlet: $inlet"
  fi

  if [[ -n $hsts || -n $set_real_ip_from ]] ; then
    echo "  config:"

    if [[ -n $hsts ]] ; then
      echo "    hsts: $hsts"
    fi

    if [[ -n $set_real_ip_from ]] ; then
      echo "    setRealIPFrom: $set_real_ip_from"
    fi
  fi
fi
