{{- $moduleGateway := dict }}
{{- include "helm_lib_module_gateway" (list . $moduleGateway) }}
{{- if and $moduleGateway .Values.prometheus.internal.grafana.enabled .Values.global.modules.publicDomainTemplate (include "helm_lib_kind_exists" (list . "HTTPRoute")) }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    alb.network.deckhouse.io/rewrite-target: /\2
    alb.network.deckhouse.io/backend-tls-settings: '{"mode": "MUTUAL", "caCertificates": "/etc/kube-rbac-proxy-client-ssl/ca.crt", "clientCertificate": "/etc/kube-rbac-proxy-client-ssl/client.crt", "privateKey": "/etc/kube-rbac-proxy-client-ssl/client.key", "insecureSkipVerify": true}'
  {{- if or (eq (include "helm_lib_module_https_mode" .) "CertManager") (eq (include "helm_lib_module_https_mode" .) "CustomCertificate") }}
    alb.network.deckhouse.io/response-headers-to-add: '{"Strict-Transport-Security":"max-age=31536000; includeSubDomains"}'
  {{- end }}
    alb.network.deckhouse.io/session-affinity: '{"mode": "cookie", "path": "/", "ttl": 0}'
  {{- if and (ne (include "helm_lib_module_https_mode" .) "Disabled") .Values.prometheus.auth.externalAuthentication }}
    alb.network.deckhouse.io/auth-signin: {{ replace "$host" (include "helm_lib_module_public_domain" (list . "grafana")) .Values.prometheus.auth.externalAuthentication.authSignInURL | quote }}
    alb.network.deckhouse.io/auth-url: {{ .Values.prometheus.auth.externalAuthentication.authURL | quote }}
    {{- if .Values.prometheus.auth.satisfyAny }}
    alb.network.deckhouse.io/satisfy: "any"
    {{- end }}
  {{- else }}
    alb.network.deckhouse.io/basic-auth-secret: d8-monitoring/basic-auth
  {{- end }}
  {{- if .Values.prometheus.auth.whitelistSourceRanges }}
    alb.network.deckhouse.io/whitelist-source-range: {{ .Values.prometheus.auth.whitelistSourceRanges | join "," }}
  {{- end }}
  name: prometheus-rewrite
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" "prometheus")) | nindent 2 }}
spec:
  hostnames:
  - {{ include "helm_lib_module_public_domain" (list . "grafana") }}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: ListenerSet
    name: prometheus
    namespace: d8-monitoring
    sectionName: grafana
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: prometheus
      port: 9090
      weight: 1
    matches:
    - path:
        type: RegularExpression
        value: /prometheus(/|$)(.*)
  {{- if (include "helm_lib_ha_enabled" .) }}
  - backendRefs:
    - group: ""
      kind: Service
      name: prometheus-main-0
      port: 9090
      weight: 1
    matches:
    - path:
        type: RegularExpression
        value: /prometheus-main-0(/|$)(.*)
  - backendRefs:
    - group: ""
      kind: Service
      name: prometheus-main-1
      port: 9090
      weight: 1
    matches:
    - path:
        type: RegularExpression
        value: /prometheus-main-1(/|$)(.*)
  {{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
  {{- if (include "helm_lib_module_https_route_tls_enabled" .) }}
    alb.network.deckhouse.io/tls-disable-protocol: http2
  {{- end }}
  {{- if or (eq (include "helm_lib_module_https_mode" .) "CertManager") (eq (include "helm_lib_module_https_mode" .) "CustomCertificate") }}
    alb.network.deckhouse.io/response-headers-to-add: '{"Strict-Transport-Security":"max-age=31536000; includeSubDomains"}'
  {{- end }}
  {{- if and (ne (include "helm_lib_module_https_mode" .) "Disabled") .Values.prometheus.auth.externalAuthentication }}
    alb.network.deckhouse.io/auth-signin: {{ replace "$host" (include "helm_lib_module_public_domain" (list . "grafana")) .Values.prometheus.auth.externalAuthentication.authSignInURL | quote }}
    alb.network.deckhouse.io/auth-url: {{ .Values.prometheus.auth.externalAuthentication.authURL | quote }}
    {{- if .Values.prometheus.auth.satisfyAny }}
    alb.network.deckhouse.io/satisfy: "any"
    {{- end }}
  {{- else }}
    alb.network.deckhouse.io/basic-auth-secret: d8-monitoring/basic-auth
  {{- end }}
  {{- if .Values.prometheus.auth.whitelistSourceRanges }}
    alb.network.deckhouse.io/whitelist-source-range: {{ .Values.prometheus.auth.whitelistSourceRanges | join "," }}
  {{- end }}
  name: prometheus-redirect-to-grafana
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" "prometheus")) | nindent 2 }}
spec:
  hostnames:
  - {{ include "helm_lib_module_public_domain" (list . "prometheus") }}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: ListenerSet
    name: prometheus
    namespace: d8-monitoring
    sectionName: prometheus-redirect-to-grafana
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        hostname: {{ include "helm_lib_module_public_domain" (list . "grafana") }}
        statusCode: 301
  {{- if not (include "helm_lib_module_https_route_tls_enabled" .) }}
        scheme: http
  {{- else }}
        scheme: https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus-redirect
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" "prometheus")) | nindent 2 }}
spec:
  hostnames:
  - {{ include "helm_lib_module_public_domain" (list . "prometheus") }}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: ListenerSet
    name: prometheus
    namespace: d8-monitoring
    sectionName: prometheus-redirect
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
    matches:
    - path:
        type: PathPrefix
        value: /
  {{- end }}
{{- end }}
