#!/bin/bash

# Copyright 2021 Flant CJSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE


source /deckhouse/shell_lib.sh

function __config__() {
  cat <<EOF
    configVersion: v1
    kubernetes:
    - name: federations
      group: main
      queue: /modules/$(module::name::kebab_case)/remote-clusters
      apiVersion: deckhouse.io/v1alpha1
      kind: IstioFederation
      keepFullObjectsInMemory: false
      jqFilter: |
        {
          "name": .metadata.name,
          "trustDomain": .spec.trustDomain,
          "metadataPublicServicesEndpoint": ((.spec.metadataEndpoint | sub("/*$"; "")) + "/private/federation-services" ),
          "clusterUUID": .status.metadataCache.public.clusterUUID
        }
    schedule:
    - name: federations
      group: main
      queue: /modules/$(module::name::kebab_case)/remote-clusters
      crontab: "* * * * *"
EOF
}

function __main__() {
  if ! values::has istio.internal.remoteAuthnKeypair.priv; then
    >&2 echo "WARNING: Authn keypair for signing requests to remote metadata endpoints isn't discovered yet. Retry in 1min."
    return 0
  fi

  if values::is_true istio.federation.enabled; then
    for i in $(context::jq -r '.snapshots.federations | keys[]'); do
      federationSpec="$(context::jq --argjson i "$i" -c '.snapshots.federations[$i] | .filterResult')"
      federationName="$(jq                 -r '.name'                           <<< "$federationSpec")"
      trustDomain="$(jq                    -r '.trustDomain'                    <<< "$federationSpec")"
      metadataPublicServicesEndpoint="$(jq -r '.metadataPublicServicesEndpoint' <<< "$federationSpec")"
      clusterUUID="$(jq                    -r '.clusterUUID'                    <<< "$federationSpec")"

      if [[ "$trustDomain" == "$(values::get global.discovery.clusterDomain)" ]]; then continue; fi
      if [[ "$clusterUUID" == "null" ]];                                          then continue; fi

      token="$(
        deckhouse-controller helper crypto gen-jwt \
          --private-key-path <(values::get istio.internal.remoteAuthnKeypair.priv) \
          --claim iss=d8-istio \
          --claim aud="$clusterUUID" \
          --claim sub="$(values::get global.discovery.clusterUUID)" \
          --claim scope=federation-services \
          --ttl 1m
      )"
      if [ -n "${D8_IS_TESTS_ENVIRONMENT-}" ]; then
        echo $token > "/tmp/jwt-pss-$federationName"
      fi

      isError=0
      # try to fetch metadata from endpoint and try to unmarshal
      if publicServices="$(
        curl \
          -f -s -m 3 --show-error \
          --header "Authorization: Bearer $token" \
          "$metadataPublicServicesEndpoint" | jq -ec '.publicServices | sort'
      )"
      then
        patch="$(jq -n --argjson ps "$publicServices" '
          {"metadataCache": {"publicServices": $ps, "publicServicesLastFetchTimestamp": (now | todateiso8601)}}
        ')"
        kubernetes::status::merge_patch "" "deckhouse.io/v1alpha1" "istiofederations" "$federationName" "$patch"
      else
        isError=1
        echo >&2 "ERROR: Cannot fetch public services metadata endpoint $metadataPublicServicesEndpoint for IstioFederation $federationName."
      fi

      jq -n --argjson isError "$isError" --arg federationName "$federationName" --arg endpoint "$metadataPublicServicesEndpoint" '
        {
          "group":"federation_fetch_ps",
          "name": "d8_istio_federation_metadata_endpoints_fetch_error_count",
          "set": $isError,
          "labels": {"federation_name": $federationName, "endpoint": $endpoint}
        }
      ' >> "$METRICS_PATH"
    done
  fi
}

hook::run "$@"
