#!/bin/bash -e

for secret in $(kubectl get storageclass -o json | jq '.items[] | select(.provisioner == "kubernetes.io/rbd") | .parameters.userSecretName' -r) ; do
  if ! kubectl -n kube-prometheus get secret $secret > /dev/null 2> /dev/null ; then
    kubectl get secret --all-namespaces --sort-by='.metadata.creationTimestamp' -o json | jq '[.items[] | select(.metadata.name == "'$secret'")][-1] | del(.metadata.annotations,.metadata.uid,.metadata.resourceVersion,.metadata.selfLink,.metadata.creationTimestamp) | .metadata.namespace = "kube-prometheus"' | kubectl create -f -
  fi
done
