{{- define "dynamix_ccm_pdb_annotations" -}}
checksum/config: {{ include (print $.Template.BasePath "/cloud-controller-manager/secret.yaml") . | sha256sum }}
{{- end -}}

{{- define "dynamix_ccm_pod_annotations" -}}
checksum/config: {{ include (print $.Template.BasePath "/cloud-controller-manager/secret.yaml") . | sha256sum }}
{{- end -}}

{{- define "dynamix_ccm_args" -}}
- --cloud-provider=dynamix
- --allow-untagged-cloud=true
- --configure-cloud-routes=false
- --controllers=cloud-node,cloud-node-lifecycle,service-lb-controller
- --v=4
{{- end -}}

{{- define "dynamix_ccm_envs" -}}
- name: DYNAMIX_APP_ID
  valueFrom:
    secretKeyRef:
      name: dynamix-credentials
      key: appId
- name: DYNAMIX_APP_SECRET
  valueFrom:
    secretKeyRef:
      name: dynamix-credentials
      key: appSecret
- name: DYNAMIX_OAUTH2_URL
  valueFrom:
    secretKeyRef:
      name: dynamix-credentials
      key: oAuth2Url
- name: DYNAMIX_CONTROLLER_URL
  valueFrom:
    secretKeyRef:
      name: dynamix-credentials
      key: controllerUrl
- name: DYNAMIX_INSECURE
  valueFrom:
    secretKeyRef:
      name: dynamix-credentials
      key: insecure
- name: DYNAMIX_RESOURCE_GROUP_NAME
  value: "{{ .Values.global.clusterConfiguration.cloud.prefix }}-rg"
{{- end -}}

{{- $ccmConfig := dict -}}
{{- $_ := set $ccmConfig "image" (include "helm_lib_module_image" (list . "cloudControllerManager")) -}}
{{- $_ := set $ccmConfig "additionalEnvs" (include "dynamix_ccm_envs" . | fromYamlArray) -}}
{{- $_ := set $ccmConfig "additionalArgs" (include "dynamix_ccm_args" . | fromYamlArray) -}}
{{- $_ := set $ccmConfig "additionalPodAnnotations" (include "dynamix_ccm_pod_annotations" . | fromYaml) -}}
{{- $_ := set $ccmConfig "additionalPDBAnnotations" (include "dynamix_ccm_pdb_annotations" . | fromYaml) -}}
{{- $_ := set $ccmConfig "vpaEnabled" true -}}
{{- $_ := set $ccmConfig "securityPolicyExceptionEnabled" true -}}

{{- include "helm_lib_cloud_controller_manager_manifests" (list . $ccmConfig) }}
