#!/bin/bash

### Migration 23.10.2020: Remove in final `domain migration` release

source /deckhouse/shell_lib.sh

function __config__() {
  modules=$({ deckhouse-controller module list 2>/dev/null || echo ""; } | jq -Rr '. | [inputs | .[:-1]][:-1] + ["monitoring", "system", "frontend"] | join("|")')

  cat << EOF
    configVersion: v1
    kubernetes:
    - name: nodes
      group: main
      keepFullObjectsInMemory: false
      executeHookOnEvent: [Added, Modified]
      apiVersion: v1
      kind: Node
      jqFilter: |
        {
          "name": .metadata.name,
          "missing_labels":
            [
              .metadata.labels // {} | with_entries(select(.value == "")) | keys as \$keys | \$keys[] |
              select(. | test("^node-role\\\.flant\\\.com/(${modules})$")) |
              sub("node-role.flant.com/"; "node-role.deckhouse.io/") |
              select(. | IN(\$keys[]) | not)
            ]
        }
EOF
}

function __main__() {
  changed=0
  for i in $(context::jq -r '.snapshots.nodes | keys[]'); do
    if context::jq -er --argjson i "$i" '.snapshots.nodes[$i].filterResult.missing_labels | length > 0' > /dev/null; then
      node_name="$(context::jq -r --argjson i "$i" '.snapshots.nodes[$i].filterResult.name')"
      patch_set=". "
      for j in $(context::jq -r --argjson i "$i" '.snapshots.nodes[$i].filterResult.missing_labels | keys[]'); do
        label="$(context::jq -r --argjson i "$i" --argjson j "$j" '.snapshots.nodes[$i].filterResult.missing_labels[$j]')"
        patch_set="$patch_set | .metadata.labels += {\"$label\":\"\"}"
      done
      kubernetes::patch_jq "" "node/$node_name" "$patch_set"
      changed=1
    fi
  done
  if [ ! -v D8_IS_TESTS_ENVIRONMENT ] && [ $changed -eq 1 ]; then
    kill 1
  fi
}

hook::run $@
