#!/bin/bash

# Copyright 2021 Flant CJSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: d8cm
      keepFullObjectsInMemory: false
      waitForSynchronization: false
      executeHookOnSynchronization: true
      executeHookOnEvent: []
      group: main
      apiVersion: v1
      kind: ConfigMap
      namespace:
        nameSelector:
          matchNames: [d8-system]
      nameSelector:
        matchNames: [deckhouse]
      jqFilter: '.data'
EOF
}

function __main__() {
  if ! context::has snapshots.d8cm.0; then
    return 0
  fi

  clean_data=$(context::jq -rc '[
    .snapshots.d8cm.[0].filterResult
    | to_entries[]
    | select(.value != "{}\n")
  ] | from_entries')
  kubernetes::patch_jq "d8-system" "configmap/deckhouse" ".data = $clean_data"
}

hook::run $@
