#!/usr/bin/env bash

# Copyright 2024 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /shell_lib.sh

function __config__() {
  cat <<EOF
configVersion: v1
kubernetesCustomResourceConversion:
  - name: alpha1_to_alpha2
    crdName: deschedulers.deckhouse.io
    conversions:
    - fromVersion: deckhouse.io/v1alpha1
      toVersion: deckhouse.io/v1alpha2
  - name: alpha2_to_alpha1
    crdName: deschedulers.deckhouse.io
    conversions:
    - fromVersion: deckhouse.io/v1alpha2
      toVersion: deckhouse.io/v1alpha1
EOF
}

function __on_conversion::alpha1_to_alpha2() {
  if converted=$(context::jq -r '.review.request.objects//[] | map(
     if .apiVersion ==  "deckhouse.io/v1alpha1" then
       .apiVersion = "deckhouse.io/v1alpha2" |
       if .spec.deschedulerPolicy.globalParameters.nodeSelector then .spec.nodeLabelSelector.matchLabels = .spec.deschedulerPolicy.globalParameters.nodeSelector end |
       del(.spec.deschedulerPolicy.globalParameters) |
       del(.spec.deschedulerPolicy.strategies.removeFailedPods) |
       del(.spec.deschedulerPolicy.strategies.removePodsHavingTooManyRestarts) |
       del(.spec.deschedulerPolicy.strategies.removePodsViolatingNodeTaints) |
       del(.spec.deschedulerPolicy.strategies.removePodsViolatingTopologySpreadConstraint) |
       del(.spec.deschedulerPolicy.strategies.removeDuplicates.nodeFilter) |
       del(.spec.deschedulerPolicy.strategies.removeDuplicates.priorityFilter) |
       del(.spec.deschedulerPolicy.strategies.removeDuplicates.namespaceFilter) |
       del(.spec.deschedulerPolicy.strategies.removeDuplicates.nodeFit) |
       del(.spec.deschedulerPolicy.strategies.removePodsViolatingNodeAffinity.nodeFilter) |
       del(.spec.deschedulerPolicy.strategies.removePodsViolatingNodeAffinity.priorityFilter) |
       del(.spec.deschedulerPolicy.strategies.removePodsViolatingNodeAffinity.namespaceFilter) |
       del(.spec.deschedulerPolicy.strategies.removePodsViolatingNodeAffinity.nodeFit) |
       del(.spec.deschedulerPolicy.strategies.removePodsViolatingInterPodAntiAffinity.nodeFilter) |
       del(.spec.deschedulerPolicy.strategies.removePodsViolatingInterPodAntiAffinity.priorityFilter) |
       del(.spec.deschedulerPolicy.strategies.removePodsViolatingInterPodAntiAffinity.namespaceFilter) |
       del(.spec.deschedulerPolicy.strategies.removePodsViolatingInterPodAntiAffinity.nodeFit) |
       del(.spec.deschedulerPolicy.strategies.highNodeUtilization.nodeFilter) |
       del(.spec.deschedulerPolicy.strategies.highNodeUtilization.priorityFilter) |
       del(.spec.deschedulerPolicy.strategies.highNodeUtilization.namespaceFilter) |
       del(.spec.deschedulerPolicy.strategies.highNodeUtilization.nodeFit) |
       del(.spec.deschedulerPolicy.strategies.lowNodeUtilization.nodeFilter) |
       del(.spec.deschedulerPolicy.strategies.lowNodeUtilization.priorityFilter) |
       del(.spec.deschedulerPolicy.strategies.lowNodeUtilization.namespaceFilter) |
       del(.spec.deschedulerPolicy.strategies.lowNodeUtilization.nodeFit)
     else . end
  )')
  then
    cat <<EOF >"$CONVERSION_RESPONSE_PATH"
{"convertedObjects": $converted}
EOF
  else
    cat <<EOF >"$CONVERSION_RESPONSE_PATH"
{"failedMessage":"Conversion of deschedulers.deckhouse.io failed"}
EOF
  fi
}

function __on_conversion::alpha2_to_alpha1() {
  if converted=$(context::jq -r '.review.request.objects//[] | map(
     if .apiVersion ==  "deckhouse.io/v1alpha2" then
       .apiVersion = "deckhouse.io/v1alpha1" |
       if .spec.nodeLabelSelector.matchLabels then .spec.deschedulerPolicy.globalParameters.nodeSelector = .spec.nodeLabelSelector.matchLabels end |
       del(.spec.deschedulerPolicy.strategies.removePodsViolatingNodeAffinity.nodeAffinityType) |
       del(.spec.deschedulerPolicy.strategies.lowNodeUtilization.thresholds) |
       del(.spec.deschedulerPolicy.strategies.lowNodeUtilization.targetThresholds) |
       del(.spec.deschedulerPolicy.strategies.highNodeUtilization.thresholds)
     else . end
  )')
  then
    cat <<EOF >"$CONVERSION_RESPONSE_PATH"
{"convertedObjects": $converted}
EOF
  else
    cat <<EOF >"$CONVERSION_RESPONSE_PATH"
{"failedMessage":"Conversion of nodegroups.deckhouse.io failed"}
EOF
  fi
}

hook::run "$@"
