{
 "title": "Seaweedfs",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(SeaweedFS_master_is_leader, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(SeaweedFS_master_is_leader{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": {
     "query": "label_values(SeaweedFS_master_is_leader{namespace=~\"$namespace\", pod=~\"$pod\"}, endpoint)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Master Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Raft leader",
   "type": "stat",
   "description": "Whether master is leader or not",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (SeaweedFS_master_is_leader{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Master leader changes",
   "type": "timeseries",
   "description": "Count times leader changed",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (SeaweedFS_master_leader_changes{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\", type=~\".+\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Received heartbeats",
   "type": "timeseries",
   "description": "Heartbeats received from components",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (type) (increase(SeaweedFS_master_received_heartbeats{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Replica Placement Mismatch",
   "type": "timeseries",
   "description": "Count replica placement mismatch",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (SeaweedFS_master_replica_placement_mismatch{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"} > 0) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Raft leader count",
   "type": "timeseries",
   "description": "Total count of raft leaders",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (SeaweedFS_master_is_leader{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"})",
     "legendFormat": "Leaders"
    }
   ]
  },
  {
   "title": "Admin lock",
   "type": "stat",
   "description": "Whether cluster locked or not",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SeaweedFS_master_admin_lock{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}",
     "legendFormat": "Client IP: {{client}}"
    }
   ]
  },
  {
   "title": "Filer Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filer Request Duration 90th percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(SeaweedFS_filer_request_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (le))",
       "legendFormat": "average"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(SeaweedFS_filer_request_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Filer Request Duration 95th percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(SeaweedFS_filer_request_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (le))",
       "legendFormat": "average"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(SeaweedFS_filer_request_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Filer Request Duration 99th percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_filer_request_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (le))",
       "legendFormat": "average"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_filer_request_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Filer QPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(SeaweedFS_filer_request_total{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[1m]) * 5",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "S3 Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "S3 Request Duration 90th percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(SeaweedFS_s3_request_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (le))",
       "legendFormat": "average"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(SeaweedFS_s3_request_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (le, type, bucket))",
       "legendFormat": "{{bucket}} {{type}}"
      }
     ]
    },
    {
     "title": "S3 Request Duration 95th percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(SeaweedFS_s3_request_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (le))",
       "legendFormat": "average"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(SeaweedFS_s3_request_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (le, type, bucket))",
       "legendFormat": "{{bucket}} {{type}}"
      }
     ]
    },
    {
     "title": "S3 Request Duration 99th percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_s3_request_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (le))",
       "legendFormat": "average"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_s3_request_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (le, type, bucket))",
       "legendFormat": "{{bucket}} {{type}}"
      }
     ]
    },
    {
     "title": "S3 Request. Duration 99th percentile per instance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_s3_request_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (le))",
       "legendFormat": "average"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_s3_request_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (le, type, bucket, pod))",
       "legendFormat": "{{bucket}} {{type}} {{pod}}"
      }
     ]
    },
    {
     "title": "S3 API QPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum (rate(SeaweedFS_s3_request_total{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[1m]) * 5) by (bucket, type)",
       "legendFormat": "{{bucket}} {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Volume Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volume Server Request Duration 99th percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_volumeServer_request_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (le, exported_instance))",
       "legendFormat": "{{exported_instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_volumeServer_request_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (le))",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Volume Server QPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(SeaweedFS_volumeServer_request_total{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Volume Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(SeaweedFS_volumeServer_volumes{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}) by (collection, type)",
       "legendFormat": "{{collection}} {{type}}"
      },
      {
       "expr": "sum(SeaweedFS_volumeServer_volumes{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Used Disk Space by Collection and Type",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(SeaweedFS_volumeServer_total_disk_size{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}) by (collection, type)",
       "legendFormat": "{{collection}} {{type}}"
      },
      {
       "expr": "sum(SeaweedFS_volumeServer_total_disk_size{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Used Disk Space by Host",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(SeaweedFS_volumeServer_total_disk_size{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}) by (exported_instance)",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Filer Store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filer Store Request Duration 99th percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_filerStore_request_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Filer Store QPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(SeaweedFS_filerStore_request_total{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "process memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}",
       "legendFormat": "{{pod}} - resident"
      },
      {
       "expr": "process_virtual_memory_bytes{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}",
       "legendFormat": "{{pod}} - virtual"
      }
     ]
    },
    {
     "title": "process memory deriv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(process_resident_memory_bytes{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__interval])",
       "legendFormat": "{{pod}} - resident"
      },
      {
       "expr": "deriv(process_virtual_memory_bytes{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__interval])",
       "legendFormat": "{{pod}} - virtual"
      }
     ]
    },
    {
     "title": "go memstats",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}",
       "legendFormat": "{{pod}} - bytes allocated"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}[30s])",
       "legendFormat": "{{pod}} - alloc rate"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}",
       "legendFormat": "{{pod}} - stack inuse"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}",
       "legendFormat": "{{pod}} - heap inuse"
      }
     ]
    },
    {
     "title": "go memstats deriv",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "deriv(go_memstats_alloc_bytes{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__interval])",
       "legendFormat": "{{pod}} - bytes allocated"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__interval])",
       "legendFormat": "{{pod}} - alloc rate"
      },
      {
       "expr": "deriv(go_memstats_stack_inuse_bytes{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__interval])",
       "legendFormat": "{{pod}} - stack inuse"
      },
      {
       "expr": "deriv(go_memstats_heap_inuse_bytes{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__interval])",
       "legendFormat": "{{pod}} - heap inuse"
      }
     ]
    },
    {
     "title": "open fds",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_open_fds{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "open fds deriv",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "deriv(process_open_fds{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GC duration quantiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}",
       "legendFormat": "{{pod}}: {{quantile}}"
      }
     ]
    }
   ]
  }
 ]
}