{
 "title": "Deckhouse Console",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "external_service",
    "query": {
     "query": "label_values(deckhouse_console_backend_http_client_requests_total, service)"
    }
   },
   {
    "name": "cache",
    "query": {
     "query": "label_values(deckhouse_console_backend_caches_size, cache)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum without (code) (sum by (code) (rate(deckhouse_console_backend_http_requests_total{job=~\"(custom-)?(deckhouse-)?console-backend\", path!~\"/healthz|/readyz\", code=~'1..'}[$__rate_interval])))",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum without (code) (sum by (code) (rate(deckhouse_console_backend_http_requests_total{job=~\"(custom-)?(deckhouse-)?console-backend\", path!~\"/healthz|/readyz\", code=~'2..'}[$__rate_interval])))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum without (code) (sum by (code) (rate(deckhouse_console_backend_http_requests_total{job=~\"(custom-)?(deckhouse-)?console-backend\", path!~\"/healthz|/readyz\", code=~'3..'}[$__rate_interval])))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum without (code) (sum by (code) (rate(deckhouse_console_backend_http_requests_total{job=~\"(custom-)?(deckhouse-)?console-backend\", path!~\"/healthz|/readyz\", code=~'4..'}[$__rate_interval])))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum without (code) (sum by (code) (rate(deckhouse_console_backend_http_requests_total{job=~\"(custom-)?(deckhouse-)?console-backend\", path!~\"/healthz|/readyz\", code=~'5..'}[$__rate_interval])))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(deckhouse_console_backend_http_request_duration_seconds_sum{job=~\"(custom-)?(deckhouse-)?console-backend\", path!~\"/subscribe|/healthz|/readyz\"}[$__rate_interval]))\n  / sum(rate(deckhouse_console_backend_http_request_duration_seconds_count{job=~\"(custom-)?(deckhouse-)?console-backend\", path!~\"/subscribe|/healthz|/readyz\"}[$__rate_interval])) > 0",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Avg Request Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(deckhouse_console_backend_http_request_size_bytes_sum{job=~\"(custom-)?(deckhouse-)?console-backend\", path!~\"/healthz|/readyz\"}[$__rate_interval]))\n  / sum(rate(deckhouse_console_backend_http_request_size_bytes_count{job=~\"(custom-)?(deckhouse-)?console-backend\", path!~\"/healthz|/readyz\"}[$__rate_interval])) > 0",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "Avg Response Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(deckhouse_console_backend_http_response_size_bytes_sum{job=~\"(custom-)?(deckhouse-)?console-backend\", path!~\"/healthz|/readyz\"}[$__rate_interval]))\n  / sum(rate(deckhouse_console_backend_http_response_size_bytes_count{job=~\"(custom-)?(deckhouse-)?console-backend\", path!~\"/healthz|/readyz\"}[$__rate_interval])) > 0",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "Methods, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(deckhouse_console_backend_http_requests_total{job=~\"(custom-)?(deckhouse-)?console-backend\", path!~\"/healthz|/readyz\"}[$__rate_interval])) by (method)\n  / scalar(sum(rate(deckhouse_console_backend_http_requests_total{job=~\"(custom-)?(deckhouse-)?console-backend\", path!~\"/healthz|/readyz\"}[$__rate_interval])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Endpoints, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(deckhouse_console_backend_http_requests_total{job=~\"(custom-)?(deckhouse-)?console-backend\", path!~\"/healthz|/readyz\",}[$__rate_interval])) by (path)\n  / scalar(sum(rate(deckhouse_console_backend_http_requests_total{job=~\"(custom-)?(deckhouse-)?console-backend\", path!~\"/healthz|/readyz\",}[$__rate_interval])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Response Time Heatmap (GET)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(deckhouse_console_backend_http_request_duration_seconds_bucket{job=~\"(custom-)?(deckhouse-)?console-backend\", path!~\"/subscribe|/healthz|/readyz\", method=\"GET\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response Time Heatmap (DELETE, PUT, POST)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(deckhouse_console_backend_http_request_duration_seconds_bucket{job=~\"(custom-)?(deckhouse-)?console-backend\", path!~\"/subscribe|/healthz|/readyz\", method=~\"DELETE|PUT|POST\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Size Heatmap (GET)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(deckhouse_console_backend_http_request_size_bytes_bucket{job=~\"(custom-)?(deckhouse-)?console-backend\", path!~\"/subscribe|/healthz|/readyz\", method=\"GET\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Size Heatmap (DELETE, PUT, POST)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(deckhouse_console_backend_http_request_size_bytes_bucket{job=~\"(custom-)?(deckhouse-)?console-backend\", path!~\"/subscribe|/healthz|/readyz\", method=~\"DELETE|PUT|POST\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response Size Heatmap (GET)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(deckhouse_console_backend_http_response_size_bytes_bucket{job=~\"(custom-)?(deckhouse-)?console-backend\", path!~\"/subscribe|/healthz|/readyz\", method=\"GET\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response Size Heatmap (DELETE, PUT, POST)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(deckhouse_console_backend_http_response_size_bytes_bucket{job=~\"(custom-)?(deckhouse-)?console-backend\", path!~\"/subscribe|/healthz|/readyz\", method=~\"DELETE|PUT|POST\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Websocket",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (channel) (rate(deckhouse_console_backend_ws_messages_received_total{job=~\"(custom-)?(deckhouse-)?console-backend\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Messages Sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (channel) (rate(deckhouse_console_backend_ws_messages_sent_total{job=~\"(custom-)?(deckhouse-)?console-backend\", channel!=\"PingChannel\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pings Sent",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (channel) (rate(deckhouse_console_backend_ws_messages_sent_total{job=~\"(custom-)?(deckhouse-)?console-backend\", channel=\"PingChannel\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "K8s",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inflight Watchers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "sum by (group, resource) (deckhouse_console_backend_informer_inflight{job=~\"(custom-)?(deckhouse-)?console-backend\"})",
       "legendFormat": "{{resource}}.{{group}}"
      }
     ]
    },
    {
     "title": "Inflight Logs Consumers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "sum by (type) (deckhouse_console_backend_logs_consumer_inflight{job=~\"(custom-)?(deckhouse-)?console-backend\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Logs Consumers Starts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "sum by (type) (rate(deckhouse_console_backend_logs_consumer_total{job=~\"(custom-)?(deckhouse-)?console-backend\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Logs Consumers Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 51 },
     "targets": [
      {
       "expr": "sum by (type) (rate(deckhouse_console_backend_logs_consumer_errors_total{job=~\"(custom-)?(deckhouse-)?console-backend\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Inflight Pod Execs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "sum by (type) (deckhouse_console_backend_pod_exec_inflight{job=~\"(custom-)?(deckhouse-)?console-backend\"})",
       "legendFormat": "exec"
      }
     ]
    },
    {
     "title": "Pod Exec Starts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 59 },
     "targets": [
      {
       "expr": "sum by (type) (rate(deckhouse_console_backend_pod_exec_total{job=~\"(custom-)?(deckhouse-)?console-backend\"}[$__rate_interval]))",
       "legendFormat": "starts"
      }
     ]
    },
    {
     "title": "Pod Exec Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 59 },
     "targets": [
      {
       "expr": "sum by (type) (rate(deckhouse_console_backend_pod_exec_errors_total{job=~\"(custom-)?(deckhouse-)?console-backend\"}[$__rate_interval]))",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Resources availability",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "max by (group, resource) (deckhouse_console_backend_resource_manager_availability{job=~\"custom-(deckhouse-)?admin-backend\"})",
       "legendFormat": "{{group}}.{{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "External calls: $external_service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "repeat": "external_service",
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum without (code) (sum by (code) (rate(deckhouse_console_backend_http_client_requests_total{job=~\"(custom-)?(deckhouse-)?console-backend\", code=~'1..', service=\"$external_service\"}[$__rate_interval])))",
       "legendFormat": "1xx"
      },
      {
       "expr": "sum without (code) (sum by (code) (rate(deckhouse_console_backend_http_client_requests_total{job=~\"(custom-)?(deckhouse-)?console-backend\", code=~'2..', service=\"$external_service\"}[$__rate_interval])))",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum without (code) (sum by (code) (rate(deckhouse_console_backend_http_client_requests_total{job=~\"(custom-)?(deckhouse-)?console-backend\", code=~'3..', service=\"$external_service\"}[$__rate_interval])))",
       "legendFormat": "3xx"
      },
      {
       "expr": "sum without (code) (sum by (code) (rate(deckhouse_console_backend_http_client_requests_total{job=~\"(custom-)?(deckhouse-)?console-backend\", code=~'4..', service=\"$external_service\"}[$__rate_interval])))",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum without (code) (sum by (code) (rate(deckhouse_console_backend_http_client_requests_total{job=~\"(custom-)?(deckhouse-)?console-backend\", code=~'5..', service=\"$external_service\"}[$__rate_interval])))",
       "legendFormat": "5xx"
      }
     ]
    },
    {
     "title": "Avg Request Processing Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(deckhouse_console_backend_http_client_request_duration_seconds_sum{job=~\"(custom-)?(deckhouse-)?console-backend\", service=\"$external_service\"}[$__rate_interval]))\n  / sum(rate(deckhouse_console_backend_http_client_request_duration_seconds_count{job=~\"(custom-)?(deckhouse-)?console-backend\", service=\"$external_service\"}[$__rate_interval])) > 0",
       "legendFormat": "time"
      }
     ]
    },
    {
     "title": "Methods, %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(deckhouse_console_backend_http_client_requests_total{job=~\"(custom-)?(deckhouse-)?console-backend\", service=\"$external_service\"}[$__rate_interval])) by (method)\n  / scalar(sum(rate(deckhouse_console_backend_http_client_requests_total{job=~\"(custom-)?(deckhouse-)?console-backend\", service=\"$external_service\"}[$__rate_interval])))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Response Time Heatmap (GET)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 52 },
     "targets": [
      {
       "expr": "sum(rate(deckhouse_console_backend_http_client_request_duration_seconds_bucket{job=~\"(custom-)?(deckhouse-)?console-backend\", method=\"GET\", service=\"$external_service\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Time Heatmap (DELETE, PUT, POST)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 52 },
     "targets": [
      {
       "expr": "sum(rate(deckhouse_console_backend_http_client_request_duration_seconds_bucket{job=~\"(custom-)?(deckhouse-)?console-backend\", method=~\"DELETE|PUT|POST\", service=\"$external_service\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Caches: $cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "repeat": "cache",
   "collapsed": true,
   "panels": [
    {
     "title": "Cache size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "sum by (cache) (deckhouse_console_backend_caches_size{job=~\"custom-(deckhouse-)?admin-backend\", cache=\"$cache\"})",
       "legendFormat": "cache size"
      }
     ]
    },
    {
     "title": "Hit rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "targets": [
      {
       "expr": "sum by (cache) (rate(deckhouse_console_backend_caches_hits{job=~\"custom-(deckhouse-)?admin-backend\", cache=\"$cache\"}[$__rate_interval]))",
       "legendFormat": "hits"
      },
      {
       "expr": "sum by (cache) (rate(deckhouse_console_backend_caches_misses{job=~\"custom-(deckhouse-)?admin-backend\", cache=\"$cache\"}[$__rate_interval]))",
       "legendFormat": "misses"
      }
     ]
    }
   ]
  },
  {
   "title": "Go",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total CPU time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=~\"(custom-)?(deckhouse-)?console-backend\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{job=~\"(custom-)?(deckhouse-)?console-backend\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Process Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=~\"(custom-)?(deckhouse-)?console-backend\"}",
       "legendFormat": "{{pod}} - resident"
      },
      {
       "expr": "process_virtual_memory_bytes{job=~\"(custom-)?(deckhouse-)?console-backend\"}",
       "legendFormat": "{{pod}} - virtual"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=~\"(custom-)?(deckhouse-)?console-backend\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Panics Total",
     "type": "gauge",
     "description": "GTI",
     "gridPos": { "h": 5, "w": 4, "x": 10, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(deckhouse_console_backend_panics_total{job=~\"(custom-)?(deckhouse-)?console-backend\"})"
      }
     ]
    },
    {
     "title": "Opened file descriptors",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 10, "x": 14, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "process_open_fds{job=~\"(custom-)?(deckhouse-)?console-backend\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Object allocations rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{job=~\"(custom-)?(deckhouse-)?console-backend\"}[$__rate_interval])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "GC duration",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "max by (job, quantile) (go_gc_duration_seconds{job=~\"(custom-)?(deckhouse-)?console-backend\"})",
       "legendFormat": "Quantile - {{ quantile }}"
      }
     ]
    }
   ]
  }
 ]
}