#!/bin/bash

source /deckhouse/shell_lib.sh

function __main__() {
  module::disable_if_cluster_is_not_bootstraped

  if values::array_has global.enabledModules "operator-prometheus" ; then
    echo "true" > $MODULE_ENABLED_RESULT
  else
    echo "false" > $MODULE_ENABLED_RESULT
  fi
}

hook::run $@
