#!/bin/bash

echo 'prometheus:'
echo '  adminPassword: "'$(makepasswd -c 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ -l 20)'"'
echo '  userPassword: "'$(makepasswd -c 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ -l 20)'"'
