{
 "title": "Controller",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "controller",
    "label": "Controller",
    "query": "label_values(up{job=\"nginx-ingress-controller\"}, controller)"
   },
   {
    "name": "app",
    "label": "App",
    "query": "label_values(up{job=\"nginx-ingress-controller\", controller=~\"$controller\"}, app)"
   },
   { "name": "scheme", "label": "Scheme", "query": "http,https" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_labels{namespace=~\"kube-nginx-ingress.*\", label_controller=~\"$controller\"}, namespace)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(up{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\"}, instance)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_connections_total{type=\"active\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(nginx_connections_total{type=\"active\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod_name=~\"nginx-.*\", namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(container_memory_usage_bytes{pod_name=~\"nginx-.*\", namespace=~\"$namespace\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod_name=~\"nginx-.*\", namespace=~\"$namespace\"}[$__interval_rv])) ",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod_name=~\"nginx-.*\", namespace=~\"$namespace\"}[$__interval_rv]))  by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "direct-fallback",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "% of requests",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(nginx_requests_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=\"nginx-for-direct-fallback\", scheme=~\"$scheme\"}[$__interval_rv])) or vector(0)) / (sum(rate(nginx_requests_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", scheme=~\"$scheme\"}[$__interval_rv])) > 0)"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"$namespace\",pod_name=~\"direct-fallback.*\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"$namespace\",pod_name=~\"direct-fallback.*\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod_name=~\"direct-fallback.*\"}[$__interval_rv])) ",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod_name=~\"direct-fallback.*\"}[$__interval_rv]))  by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(nginx_connections_current{state=\"active\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(nginx_connections_current{state=\"active\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Accepted Connections",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "cps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_connections_processed_total{stage=\"accepted\"}[$__interval_rv]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(nginx_connections_processed_total{stage=\"accepted\"}[$__interval_rv])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_requests_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 2, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", server_zone=\"upstream_response_time_hist\", key=~\"0\\\\..*|1\\\\..*\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", server_zone=\"upstream_response_time_hist\", key=~\"[2-9]\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", server_zone=\"upstream_response_time_hist\", key=~\"10|>10\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", server_zone=\"request_time_hist\", key=~\"0\\\\..*|1\\\\..*\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", server_zone=\"request_time_hist\", key=~\"[2-9]\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", server_zone=\"request_time_hist\", key=~\"10|>10\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 17 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_bytes_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\"}[$__range]))"
    }
   ]
  },
  {
   "title": "HTTPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 19 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(nginx_requests_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=\"https\"}[$__interval_rv])) / (sum(increase(nginx_requests_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\"}[$__interval_rv])) > 0)"
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "instance" },
  {
   "title": "Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_requests_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", instance=~\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 2, "y": 22 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", instance=~\"$instance\", server_zone=\"upstream_response_time_hist\", key=~\"0\\\\..*|1\\\\..*\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", instance=~\"$instance\", server_zone=\"upstream_response_time_hist\", key=~\"[2-9]\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", instance=~\"$instance\", server_zone=\"upstream_response_time_hist\", key=~\"10|>10\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 22 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", instance=~\"$instance\", server_zone=\"request_time_hist\", key=~\"0\\\\..*|1\\\\..*\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", instance=~\"$instance\", server_zone=\"request_time_hist\", key=~\"[2-9]\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", instance=~\"$instance\", server_zone=\"request_time_hist\", key=~\"10|>10\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 24 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_bytes_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", instance=~\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "HTTPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 26 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(nginx_requests_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", instance=~\"$instance\", scheme=\"https\"}[$__interval_rv])) / (sum(increase(nginx_requests_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", instance=~\"$instance\", }[$__interval_rv])) > 0)"
    }
   ]
  },
  { "title": "Status Codes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "1xx|2xx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", status_code=~\"1xx|2xx\"}[$__interval_rv]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(nginx_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", status_code=~\"1xx|2xx\"}[$__interval_rv])) by (instance) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "3xx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", status_code=\"3xx\"}[$__interval_rv]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(nginx_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", status_code=\"3xx\"}[$__interval_rv])) by (instance) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "4xx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", status_code=\"4xx\"}[$__interval_rv]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(nginx_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", status_code=\"4xx\"}[$__interval_rv])) by (instance) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 29 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", status_code=\"5xx\"}[$__interval_rv]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(nginx_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", status_code=\"5xx\"}[$__interval_rv])) by (instance) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "1xx|2xx",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", status_code=~\"1xx|2xx\"}[$__interval_rv])) by (instance) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "3xx",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", status_code=\"3xx\"}[$__interval_rv])) by (instance) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "4xx",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", status_code=\"4xx\"}[$__interval_rv])) by (instance) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", status_code=\"5xx\"}[$__interval_rv])) by (instance) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "1xx|2xx",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", instance=~\"$instance\", scheme=~\"$scheme\", status_code=~\"1xx|2xx\"}[$__interval_rv]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(nginx_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", instance=~\"$instance\", scheme=~\"$scheme\", status_code=~\"1xx|2xx\"}[$__interval_rv])) by (namespace) > 0",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "3xx",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 25 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", instance=~\"$instance\", scheme=~\"$scheme\", status_code=\"3xx\"}[$__interval_rv]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(nginx_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", instance=~\"$instance\", scheme=~\"$scheme\", status_code=\"3xx\"}[$__interval_rv])) by (namespace) > 0",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "4xx",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", instance=~\"$instance\", scheme=~\"$scheme\", status_code=\"4xx\"}[$__interval_rv]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(nginx_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", instance=~\"$instance\", scheme=~\"$scheme\", status_code=\"4xx\"}[$__interval_rv])) by (namespace) > 0",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "5xx",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 25 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", instance=~\"$instance\", scheme=~\"$scheme\", status_code=\"5xx\"}[$__interval_rv]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(nginx_responses_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", instance=~\"$instance\", scheme=~\"$scheme\", status_code=\"5xx\"}[$__interval_rv])) by (namespace) > 0",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_requests_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\"}[$__interval_rv]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(nginx_requests_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\"}[$__interval_rv])) by (instance) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 40 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_bytes_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", direction=\"out\"}[$__interval_rv])) * 8",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(nginx_bytes_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", direction=\"out\"}[$__interval_rv])) by (instance) * 8 > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Incoming Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 40 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_bytes_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", direction=\"in\"}[$__interval_rv])) * 8",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(nginx_bytes_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", direction=\"in\"}[$__interval_rv])) by (instance) * 8 > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_requests_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\"}[$__interval_rv])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 45 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_bytes_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", direction=\"out\"}[$__interval_rv])) by(instance) * 8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Incoming Traffic",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 45 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_bytes_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", direction=\"in\"}[$__interval_rv])) by (instance) * 8 > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_requests_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", instance=~\"$instance\"}[$__interval_rv])) by (namespace) > 0",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Traffic",
     "type": "graph",
     "gridPos": { "h": 5, "w": 9, "x": 9, "y": 52 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_bytes_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", instance=~\"$instance\", direction=\"out\"}[$__interval_rv])) by (namespace) * 8 > 0",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Incoming Traffic",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 52 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_bytes_total:controller{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", scheme=~\"$scheme\", instance=~\"$instance\", direction=\"out\"}[$__interval_rv])) by (namespace) * 8 > 0",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  }
 ]
}