{
 "title": "Namespace",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace!=\"None\"}, namespace)"
   },
   {
    "name": "ingress_name",
    "label": "Ingress Name",
    "query": "label_values(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\"}, ingress_name)"
   },
   {
    "name": "scheme",
    "label": "Scheme",
    "query": "label_values(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\"}, scheme)"
   },
   {
    "name": "server_name",
    "label": "Server Name",
    "query": "label_values(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\"}, server_name)"
   },
   {
    "name": "upstream_address",
    "label": "Upstream Address",
    "query": "label_values(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", upstream_address!=\"None\"}, upstream_address)"
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", service_name!=\"None\"}, service_name)"
   },
   { "name": "show_cluster", "label": "Show Cluster", "query": "No" }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(avg_over_time(nginx_ingress:namespace:request_rate{job=\"nginx-ingress-controller\", namespace=\"$namespace\"}[$__range])) by (namespace)"
    },
    {
     "expr": "max(quantile_over_time(0.5, nginx_ingress:namespace:request_rate{job=\"nginx-ingress-controller\", namespace=\"$namespace\"}[$__range])) by (namespace)"
    },
    {
     "expr": "max(quantile_over_time(0.9, nginx_ingress:namespace:request_rate{job=\"nginx-ingress-controller\", namespace=\"$namespace\"}[$__range])) by (namespace)"
    },
    {
     "expr": "max(max_over_time(nginx_ingress:namespace:request_rate{job=\"nginx-ingress-controller\", namespace=\"$namespace\"}[$__range])) by (namespace)"
    },
    {
     "expr": "max(avg_over_time(nginx_ingress:namespace:traffic_bytes_rate{job=\"nginx-ingress-controller\", namespace=\"$namespace\", direction=\"out\"}[$__range])) by (namespace) * 8"
    },
    {
     "expr": "max(quantile_over_time(0.5, nginx_ingress:namespace:traffic_bytes_rate{job=\"nginx-ingress-controller\", namespace=\"$namespace\"}[$__range])) by (namespace) * 8"
    },
    {
     "expr": "max(quantile_over_time(0.9, nginx_ingress:namespace:traffic_bytes_rate{job=\"nginx-ingress-controller\", namespace=\"$namespace\"}[$__range])) by (namespace) * 8"
    },
    {
     "expr": "max(max_over_time(nginx_ingress:namespace:traffic_bytes_rate{job=\"nginx-ingress-controller\", namespace=\"$namespace\"}[$__range])) by (namespace) * 8"
    },
    {
     "expr": "sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=\"$namespace\", status_code=\"1xx\"}[$__range])) by (namespace) / (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=\"$namespace\"}[$__range])) by (namespace) > 0) or (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=\"$namespace\"}[$__range])) by (namespace) > bool 0)"
    },
    {
     "expr": "sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=\"$namespace\", status_code=\"2xx\"}[$__range])) by (namespace) / (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=\"$namespace\"}[$__range])) by (namespace) > 0) or (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=\"$namespace\"}[$__range])) by (namespace) > bool 0)"
    },
    {
     "expr": "sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=\"$namespace\", status_code=\"3xx\"}[$__range])) by (namespace) / (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=\"$namespace\"}[$__range])) by (namespace) > 0) or (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=\"$namespace\"}[$__range])) by (namespace) > bool 0)"
    },
    {
     "expr": "sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=\"$namespace\", status_code=\"4xx\"}[$__range])) by (namespace) / (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=\"$namespace\"}[$__range])) by (namespace) > 0) or (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=\"$namespace\"}[$__range])) by (namespace) > bool 0)"
    },
    {
     "expr": "sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=\"$namespace\", status_code=\"5xx\"}[$__range])) by (namespace) / (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=\"$namespace\"}[$__range])) by (namespace) > 0) or (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=\"$namespace\"}[$__range])) by (namespace) > bool 0)"
    },
    {
     "expr": "sum(increase(nginx_requests_total:overview{job=\"nginx-ingress-controller\", namespace=\"$namespace\", scheme=\"https\"}[$__range])) by (namespace) / (sum(increase(nginx_requests_total:overview{job=\"nginx-ingress-controller\", namespace=\"$namespace\"}[$__range])) by (namespace) > 0) or (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=\"$namespace\"}[$__range])) by (namespace) > bool 0)"
    },
    {
     "expr": "max(avg_over_time(nginx_ingress:namespace:traffic_bytes_rate{job=\"nginx-ingress-controller\", namespace=\"$namespace\", direction=\"in\"}[$__range])) by (namespace) * 8"
    },
    {
     "expr": "max(max_over_time(nginx_ingress:namespace:traffic_bytes_rate{job=\"nginx-ingress-controller\", namespace=\"$namespace\", direction=\"in\"}[$__range])) by (namespace) * 8"
    }
   ]
  },
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Upstream Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", server_zone=\"upstream_response_time_hist\", key=~\"0\\\\..*|1\\\\..*\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", server_zone=\"upstream_response_time_hist\", key=~\"[2-9]\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", server_zone=\"upstream_response_time_hist\", key=~\"10|>10\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", server_zone=\"request_time_hist\", key=~\"0\\\\..*|1\\\\..*\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", server_zone=\"request_time_hist\", key=~\"[2-9]\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", server_zone=\"request_time_hist\", key=~\"10|>10\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "HTTPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 6 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=\"https\", server_name=~\"$server_name\"}[$__interval_rv])) / (sum(increase(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", server_name=~\"$server_name\"}[$__interval_rv])) > 0)"
    }
   ]
  },
  {
   "title": "3xx",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", status_code=\"3xx\"}[$__interval_rv]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", status_code=\"3xx\"}[$__interval_rv])) by (server_name, location_path) > 0",
     "legendFormat": "{{server_name}}{{location_path}}"
    }
   ]
  },
  {
   "title": "3xx",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 8 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", status_code=\"3xx\"}[$__range])) / (sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\"}[$__range])) > 0)"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\"}[$__interval_rv]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\"}[$__interval_rv])) by (server_name, location_path) > 0",
     "legendFormat": "{{server_name}}{{location_path}}"
    },
    {
     "expr": "sum(rate(nginx_requests_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$show_cluster\"}[$__interval_rv]))",
     "legendFormat": "Cluster"
    }
   ]
  },
  {
   "title": "4xx",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", status_code=\"4xx\"}[$__interval_rv]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", status_code=\"4xx\"}[$__interval_rv])) by (server_name, location_path) > 0",
     "legendFormat": "{{server_name}}{{location_path}}"
    }
   ]
  },
  {
   "title": "4xx",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", status_code=\"4xx\"}[$__range])) / (sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\"}[$__range])) > 0)"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", status_code=\"5xx\"}[$__interval_rv]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", status_code=\"5xx\"}[$__interval_rv])) by (server_name, location_path) > 0",
     "legendFormat": "{{server_name}}{{location_path}}"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 16 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", status_code=\"5xx\"}[$__range])) / (sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\"}[$__range])) > 0)"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_bytes_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", direction=\"out\"}[$__interval_rv])) * 8",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(nginx_bytes_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", direction=\"out\"}[$__interval_rv])) by (server_name, location_path) * 8 > 0",
     "legendFormat": "{{server_name}}{{location_path}}"
    },
    {
     "expr": "sum(rate(nginx_bytes_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$show_cluster\", direction=\"out\"}[$__interval_rv])) * 8 > 0",
     "legendFormat": "Cluster"
    }
   ]
  },
  {
   "title": "Incoming Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_bytes_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", direction=\"in\"}[$__interval_rv])) * 8",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(nginx_bytes_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", direction=\"in\"}[$__interval_rv])) by (server_name, location_path) * 8 > 0",
     "legendFormat": "{{server_name}}{{location_path}}"
    },
    {
     "expr": "sum(rate(nginx_bytes_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$show_cluster\", direction=\"in\"}[$__interval_rv]))  * 8 > 0",
     "legendFormat": "Cluster"
    }
   ]
  },
  { "title": "Ingresses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Requests per Ingress",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\"}[$__interval_rv])) by (ingress_name)",
     "legendFormat": "{{ingress_name}}"
    }
   ]
  },
  {
   "title": "Traffic per Ingress",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_bytes_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", direction=\"out\"}[$__interval_rv])) by(ingress_name) * 8",
     "legendFormat": "{{ingress_name}}"
    }
   ]
  },
  {
   "title": "ingress/$ingress_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "ingress_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Requests",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 28 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Available Upstreams",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 28 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(\n  kube_endpoint_address_available{job=\"kube-state-metrics\", namespace=~\"$namespace\", endpoint=~\"$service_name\"} and on (namespace, endpoint) label_replace(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"http|https\", server_name=~\"$server_name\", service_name!=\"None\"}, \"endpoint\", \"$1\", \"service_name\", \"(.*)\")\n)"
      }
     ]
    },
    {
     "title": "3xx",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 28 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", status_code=\"3xx\"}[$__range])) / (sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\"}[$__range])) > 0)"
      }
     ]
    },
    {
     "title": "Upstream Response Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 13, "x": 6, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_filterzone_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", server_zone=\"upstream_response_time_hist\", key=~\"0\\\\..*|1\\\\..*\"}[$__interval_rv])) by (key) > 0",
       "legendFormat": "{{key}}"
      },
      {
       "expr": "sum(rate(nginx_filterzone_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", server_zone=\"upstream_response_time_hist\", key=~\"[2-9]\"}[$__interval_rv])) by (key) > 0",
       "legendFormat": "{{key}}"
      },
      {
       "expr": "sum(rate(nginx_filterzone_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", server_zone=\"upstream_response_time_hist\", key=~\"10|>10\"}[$__interval_rv])) by (key) > 0",
       "legendFormat": "{{key}}"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\"}[$__interval_rv])) by (server_name, location_path) > 0",
       "legendFormat": "{{server_name}}{{location_path}}"
      }
     ]
    },
    {
     "title": "Traffic",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 30 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(nginx_bytes_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Ready Upstreams",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 30 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(\n  (kube_endpoint_address_available{job=\"kube-state-metrics\", namespace=~\"$namespace\"} and on (namespace, endpoint) label_replace(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"http|https\", server_name=~\"$server_name\", service_name!=\"None\"}, \"endpoint\", \"$1\", \"service_name\", \"(.*)\"))\n  - (kube_endpoint_address_not_ready{job=\"kube-state-metrics\", namespace=~\"$namespace\"} and on (namespace, endpoint) label_replace(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"http|https\", server_name=~\"$server_name\", service_name!=\"None\"}, \"endpoint\", \"$1\", \"service_name\", \"(.*)\"))\n) / sum(\n  kube_endpoint_address_available{job=\"kube-state-metrics\", namespace=~\"$namespace\", endpoint=~\"$service_name\"} and on (namespace, endpoint) label_replace(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"http|https\", server_name=~\"$server_name\", service_name!=\"None\"}, \"endpoint\", \"$1\", \"service_name\", \"(.*)\") > 0\n)"
      }
     ]
    },
    {
     "title": "4xx",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 30 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", status_code=\"4xx\"}[$__range])) / (sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\"}[$__range])) > 0)"
      }
     ]
    },
    {
     "title": "Traffic",
     "type": "graph",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 31 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_bytes_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", direction=\"out\"}[$__interval_rv])) by (server_name, location_path) * 8 > 0",
       "legendFormat": "{{server_name}}{{location_path}}"
      }
     ]
    },
    {
     "title": "5xx",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 32 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", status_code=\"5xx\"}[$__range])) / (sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\"}[$__range])) > 0)"
      }
     ]
    }
   ]
  },
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests per Service",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\"}[$__interval_rv])) by (service_name)",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Traffic per Service",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_bytes_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", direction=\"out\"}[$__interval_rv])) by(service_name) * 8",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "service/$service_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "repeat": "service_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Requests",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 48 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", service_name=~\"$service_name\"}[$__range]))"
      }
     ]
    },
    {
     "title": "3xx",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 48 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", service_name=~\"$service_name\", status_code=\"3xx\"}[$__range])) / (sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", service_name=~\"$service_name\"}[$__range])) > 0)"
      }
     ]
    },
    {
     "title": "Upstream Response Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 15, "x": 4, "y": 48 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_filterzone_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", service_name=~\"$service_name\", server_zone=\"upstream_response_time_hist\", key=~\"0\\\\..*|1\\\\..*\"}[$__interval_rv])) by (key) > 0",
       "legendFormat": "{{key}}"
      },
      {
       "expr": "sum(rate(nginx_filterzone_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", service_name=~\"$service_name\", server_zone=\"upstream_response_time_hist\", key=~\"[2-9]\"}[$__interval_rv])) by (key) > 0",
       "legendFormat": "{{key}}"
      },
      {
       "expr": "sum(rate(nginx_filterzone_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", service_name=~\"$service_name\", server_zone=\"upstream_response_time_hist\", key=~\"10|>10\"}[$__interval_rv])) by (key) > 0",
       "legendFormat": "{{key}}"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 48 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", service_name=~\"$service_name\"}[$__interval_rv])) by (server_name, location_path) > 0",
       "legendFormat": "{{server_name}}{{location_path}}"
      }
     ]
    },
    {
     "title": "Traffic",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 50 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(nginx_bytes_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", service_name=~\"$service_name\"}[$__range]))"
      }
     ]
    },
    {
     "title": "4xx",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 50 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", service_name=~\"$service_name\", status_code=\"4xx\"}[$__range])) / (sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", service_name=~\"$service_name\"}[$__range])) > 0)"
      }
     ]
    },
    {
     "title": "Traffic",
     "type": "graph",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 51 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_bytes_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", service_name=~\"$service_name\", direction=\"out\"}[$__interval_rv])) by (server_name, location_path) * 8 > 0",
       "legendFormat": "{{server_name}}{{location_path}}"
      }
     ]
    },
    {
     "title": "5xx",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 52 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", service_name=~\"$service_name\", status_code=\"5xx\"}[$__range])) / (sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", service_name=~\"$service_name\"}[$__range])) > 0)"
      }
     ]
    }
   ]
  },
  { "title": "Backends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 126 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_endpoint_address_available{job=\"kube-state-metrics\", namespace=~\"$namespace\", endpoint=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Requests per Backend",
   "type": "graph",
   "gridPos": { "h": 4, "w": 11, "x": 2, "y": 126 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", upstream_address=~\"$upstream_address\"}[$__interval_rv])) by (upstream_address)",
     "legendFormat": "{{upstream_address}}"
    }
   ]
  },
  {
   "title": "Traffic per Backend",
   "type": "graph",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 126 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_bytes_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", upstream_address=~\"$upstream_address\", direction=\"out\"}[$__interval_rv])) by(upstream_address) * 8",
     "legendFormat": "{{upstream_address}}"
    }
   ]
  },
  {
   "title": "Ready",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 128 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(kube_endpoint_address_available{job=\"kube-state-metrics\", namespace=~\"$namespace\", endpoint=~\"$service_name\"}) - sum(kube_endpoint_address_not_ready{job=\"kube-state-metrics\", namespace=~\"$namespace\", endpoint=~\"$service_name\"})) / (sum(kube_endpoint_address_available{job=\"kube-state-metrics\", namespace=~\"$namespace\", endpoint=~\"$service_name\"}) > 0)"
    }
   ]
  },
  {
   "title": "$upstream_address",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 },
   "repeat": "upstream_address",
   "collapsed": true,
   "panels": [
    {
     "title": "Requests",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 38 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", upstream_address=~\"$upstream_address\"}[$__range]))"
      }
     ]
    },
    {
     "title": "3xx",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 38 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", upstream_address=~\"$upstream_address\", status_code=\"3xx\"}[$__range])) / (sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", upstream_address=~\"$upstream_address\"}[$__range])) > 0)"
      }
     ]
    },
    {
     "title": "Upstream Response Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 15, "x": 4, "y": 38 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_filterzone_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", upstream_address=~\"$upstream_address\", server_zone=\"upstream_response_time_hist\", key=~\"0\\\\..*|1\\\\..*\"}[$__interval_rv])) by (key) > 0",
       "legendFormat": "{{key}}"
      },
      {
       "expr": "sum(rate(nginx_filterzone_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", upstream_address=~\"$upstream_address\", server_zone=\"upstream_response_time_hist\", key=~\"[2-9]\"}[$__interval_rv])) by (key) > 0",
       "legendFormat": "{{key}}"
      },
      {
       "expr": "sum(rate(nginx_filterzone_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", upstream_address=~\"$upstream_address\", server_zone=\"upstream_response_time_hist\", key=~\"10|>10\"}[$__interval_rv])) by (key) > 0",
       "legendFormat": "{{key}}"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 38 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_requests_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", upstream_address=~\"$upstream_address\"}[$__interval_rv])) by (server_name, location_path) > 0",
       "legendFormat": "{{server_name}}{{location_path}}"
      }
     ]
    },
    {
     "title": "Traffic",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 40 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(nginx_bytes_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", upstream_address=~\"$upstream_address\"}[$__range]))"
      }
     ]
    },
    {
     "title": "4xx",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 40 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", upstream_address=~\"$upstream_address\", status_code=\"4xx\"}[$__range])) / (sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", upstream_address=~\"$upstream_address\"}[$__range])) > 0)"
      }
     ]
    },
    {
     "title": "Traffic",
     "type": "graph",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 41 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_bytes_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", upstream_address=~\"$upstream_address\", direction=\"out\"}[$__interval_rv])) by (server_name, location_path) * 8 > 0",
       "legendFormat": "{{server_name}}{{location_path}}"
      }
     ]
    },
    {
     "title": "5xx",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 42 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", upstream_address=~\"$upstream_address\", status_code=\"5xx\"}[$__range])) / (sum(increase(nginx_responses_total:details{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress_name=~\"$ingress_name\", scheme=~\"$scheme\", server_name=~\"$server_name\", upstream_address=~\"$upstream_address\"}[$__range])) > 0)"
      }
     ]
    }
   ]
  }
 ]
}