{
 "title": "Overview by Server Names",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "server_name",
    "label": "Server Name",
    "query": "label_values(nginx_requests_total:overview{job=\"nginx-ingress-controller\"}, server_name)"
   },
   {
    "name": "scheme",
    "label": "Scheme",
    "query": "label_values(nginx_requests_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\"}, scheme)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(nginx_requests_total:overview{job=\"nginx-ingress-controller\", server_name=~\"$server_name\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(avg_over_time(nginx_ingress:server_name:request_rate{job=\"nginx-ingress-controller\"}[$__range])) by (server_name)"
    },
    {
     "expr": "max(quantile_over_time(0.5, nginx_ingress:server_name:request_rate{job=\"nginx-ingress-controller\"}[$__range])) by (server_name)"
    },
    {
     "expr": "max(quantile_over_time(0.9, nginx_ingress:server_name:request_rate{job=\"nginx-ingress-controller\"}[$__range])) by (server_name)"
    },
    {
     "expr": "max(max_over_time(nginx_ingress:server_name:request_rate{job=\"nginx-ingress-controller\"}[$__range])) by (server_name)"
    },
    {
     "expr": "max(avg_over_time(nginx_ingress:server_name:traffic_bytes_rate{job=\"nginx-ingress-controller\", direction=\"out\"}[$__range])) by (server_name) * 8"
    },
    {
     "expr": "max(quantile_over_time(0.5, nginx_ingress:server_name:traffic_bytes_rate{job=\"nginx-ingress-controller\"}[$__range])) by (server_name) * 8"
    },
    {
     "expr": "max(quantile_over_time(0.9, nginx_ingress:server_name:traffic_bytes_rate{job=\"nginx-ingress-controller\"}[$__range])) by (server_name) * 8"
    },
    {
     "expr": "max(max_over_time(nginx_ingress:server_name:traffic_bytes_rate{job=\"nginx-ingress-controller\"}[$__range])) by (server_name) * 8"
    },
    {
     "expr": "sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", status_code=\"1xx\"}[$__range])) by (server_name) / (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\"}[$__range])) by (server_name) > 0) or (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\"}[$__range])) by (server_name) > bool 0)"
    },
    {
     "expr": "sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", status_code=\"2xx\"}[$__range])) by (server_name) / (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\"}[$__range])) by (server_name) > 0) or (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\"}[$__range])) by (server_name) > bool 0)"
    },
    {
     "expr": "sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", status_code=\"3xx\"}[$__range])) by (server_name) / (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\"}[$__range])) by (server_name) > 0) or (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\"}[$__range])) by (server_name) > bool 0)"
    },
    {
     "expr": "sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", status_code=\"4xx\"}[$__range])) by (server_name) / (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\"}[$__range])) by (server_name) > 0) or (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\"}[$__range])) by (server_name) > bool 0)"
    },
    {
     "expr": "sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", status_code=\"5xx\"}[$__range])) by (server_name) / (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\"}[$__range])) by (server_name) > 0) or (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\"}[$__range])) by (server_name) > bool 0)"
    },
    {
     "expr": "sum(increase(nginx_requests_total:overview{job=\"nginx-ingress-controller\", scheme=\"https\"}[$__range])) by (server_name) / (sum(increase(nginx_requests_total:overview{job=\"nginx-ingress-controller\"}[$__range])) by (server_name) > 0) or (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\"}[$__range])) by (server_name) > bool 0)"
    },
    {
     "expr": "max(avg_over_time(nginx_ingress:server_name:traffic_bytes_rate{job=\"nginx-ingress-controller\", direction=\"in\"}[$__range])) by (server_name) * 8"
    },
    {
     "expr": "max(max_over_time(nginx_ingress:server_name:traffic_bytes_rate{job=\"nginx-ingress-controller\", direction=\"in\"}[$__range])) by (server_name) * 8"
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\", server_zone=\"upstream_response_time_hist\", key=~\"0\\\\..*|1\\\\..*\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\", server_zone=\"upstream_response_time_hist\", key=~\"[2-9]\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\", server_zone=\"upstream_response_time_hist\", key=~\"10|>10\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_requests_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\", server_zone=\"request_time_hist\", key=~\"0\\\\..*|1\\\\..*\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\", server_zone=\"request_time_hist\", key=~\"[2-9]\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sum(rate(nginx_filterzone_responses_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\", server_zone=\"request_time_hist\", key=~\"10|>10\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "HTTPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 13 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(nginx_requests_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=\"https\", server_name=~\"$server_name\"}[$__interval_rv])) / (sum(rate(nginx_requests_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", server_name=~\"$server_name\"}[$__interval_rv])) > 0)"
    }
   ]
  },
  {
   "title": "3xx",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\", status_code=\"3xx\"}[$__interval_rv]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\", status_code=\"3xx\"}[$__interval_rv])) by (server_name) > 0",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "3xx",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 15 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\", status_code=\"3xx\"}[$__range])) / (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\"}[$__range])) > 0)"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_requests_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\"}[$__interval_rv]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(nginx_requests_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\"}[$__interval_rv])) by (server_name) > 0",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "4xx",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\", status_code=\"4xx\"}[$__interval_rv]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\", status_code=\"4xx\"}[$__interval_rv])) by (server_name) > 0",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "4xx",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 19 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\", status_code=\"4xx\"}[$__range])) / (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\"}[$__range])) > 0)"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\", status_code=\"5xx\"}[$__interval_rv]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\", status_code=\"5xx\"}[$__interval_rv])) by (server_name) > 0",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 23 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\", status_code=\"5xx\"}[$__range])) / (sum(increase(nginx_responses_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\"}[$__range])) > 0)"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_bytes_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\", direction=\"out\"}[$__interval_rv])) * 8",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(nginx_bytes_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\", direction=\"out\"}[$__interval_rv])) by (server_name) * 8 > 0",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Incoming Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_bytes_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\", direction=\"in\"}[$__interval_rv])) * 8",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(nginx_bytes_total:overview{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", scheme=~\"$scheme\", server_name=~\"$server_name\", direction=\"in\"}[$__interval_rv])) by (server_name) * 8 > 0",
     "legendFormat": "{{server_name}}"
    }
   ]
  }
 ]
}