{
 "title": "Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Upstream Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_filterzone_responses_total{server_zone=\"upstream_response_time_hist::*\",key=~\"0\\\\..*|1\\\\..*\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sum(rate(nginx_filterzone_responses_total{server_zone=\"upstream_response_time_hist::*\",key=~\"[2-9]\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sum(rate(nginx_filterzone_responses_total{server_zone=\"upstream_response_time_hist::*\",key=~\"10|>10\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_filterzone_responses_total{server_zone=\"upstream_response_time_hist::*\",key=~\"0\\\\..*|1\\\\..*\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sum(rate(nginx_filterzone_responses_total{server_zone=\"upstream_response_time_hist::*\",key=~\"[2-9]\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sum(rate(nginx_filterzone_responses_total{server_zone=\"upstream_response_time_hist::*\",key=~\"10|>10\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_filterzone_responses_total{server_zone=\"upstream_response_time_hist::*\",key=~\"0\\\\..*|1\\\\..*\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sum(rate(nginx_filterzone_responses_total{server_zone=\"upstream_response_time_hist::*\",key=~\"[2-9]\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "sum(rate(nginx_filterzone_responses_total{server_zone=\"upstream_response_time_hist::*\",key=~\"10|>10\"}[$__interval_rv])) by (key) > 0",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_requests_total{server_zone='*'}[$__interval_rv]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(nginx_requests_total{server_zone!~'\\\\*|_'}[$__interval_rv])) by (server_zone)",
     "legendFormat": "{{server_zone}}"
    },
    {
     "expr": "sum(rate(nginx_requests_total{server_zone='_'}[$__interval_rv])) > 0",
     "legendFormat": "default_vhost"
    }
   ]
  },
  {
   "title": "Average Upstream Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_upstream_response_msecs_avg * (sum(nginx_upstream_responses_total) without (status_code) > 0)) / sum(nginx_upstream_responses_total)",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_connections_total{type=~\"waiting|reading|writing\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(nginx_connections_total{type=~\"waiting|reading|writing\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_responses_total{server_zone!='*'}[$__interval_rv])) by (status_code) > 0",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "4xx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_responses_total{server_zone!~'\\\\*|_', status_code=\"4xx\"}[$__interval_rv])) by (server_zone) > 0",
     "legendFormat": "{{server_zone}}"
    },
    {
     "expr": "sum(rate(nginx_responses_total{server_zone='_', status_code=\"4xx\"}[$__interval_rv])) > 0",
     "legendFormat": "default_vhost"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_responses_total{server_zone!~'\\\\*|_', status_code=\"5xx\"}[$__interval_rv])) by (server_zone) > 0",
     "legendFormat": "{{server_zone}}"
    },
    {
     "expr": "sum(rate(nginx_responses_total{server_zone='_', status_code=\"5xx\"}[$__interval_rv])) > 0",
     "legendFormat": "default_vhost"
    }
   ]
  },
  {
   "title": "Trafic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_bytes_total{server_zone=\"*\",direction=\"out\"}[$__interval_rv])) * 8",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(nginx_bytes_total{server_zone!~\"\\\\*|_\",direction=\"out\"}[$__interval_rv])) by (server_zone) * 8 > 0",
     "legendFormat": "{{server_zone}}"
    },
    {
     "expr": "sum(rate(nginx_bytes_total{server_zone=\"_\",direction=\"out\"}[$__interval_rv])) by (server_zone) * 8 > 0",
     "legendFormat": "default_vhost"
    }
   ]
  },
  {
   "title": "Trafic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_bytes_total{server_zone=\"*\",direction=\"in\"}[$__interval_rv])) * 8",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(nginx_bytes_total{server_zone!~\"\\\\*|_\",direction=\"in\"}[$__interval_rv])) by (server_zone) * 8 > 0",
     "legendFormat": "{{server_zone}}"
    },
    {
     "expr": "sum(rate(nginx_bytes_total{server_zone=\"_\",direction=\"in\"}[$__interval_rv])) by (server_zone) * 8 > 0",
     "legendFormat": "default_vhost"
    }
   ]
  }
 ]
}