#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p beforeHelm=10
}

function __main__() {
  if values::has --config userAuthn.users ; then
    tmp_file=$(mktemp)
    users=$(values::get --config userAuthn.users)
    echo $users | jq -rc 'to_entries[]' | while read user; do
      password=$(echo $user | jq '.value' -r)
      hash=$(htpasswd -bnBC 10 "" $password | tr -d ':\n' | sed 's/$2y/$2a/')
      echo $user | jq --arg hash $hash '. + {value: $hash}' >> $tmp_file
    done

    values::set userAuthn.users "$(cat $tmp_file | jq -s '.')"
    rm $tmp_file
  fi
}

hook::run "$@"
