#!/bin/bash

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  jo -p beforeHelm=5
}

function __main__() {
  kubernetes_ca_for_kubeconfig_generator=$(cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt)
  values::set userAuthn.internal.kubernetesCA "$kubernetes_ca_for_kubeconfig_generator"
}

hook::run $@
