#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  echo '
{
  "onKubernetesEvent": [
    {
      "kind": "secret",
      "name": "kubernetes-tls",
      "event": [
        "add",
        "update"
      ],
      "namespaceSelector": {
        "matchNames": [
          "default"
        ]
      },
      "jqFilter": ".data.\"ca.crt\""
    }
  ]
}'
}

function __main__() {
  if values::is_true userAuthn.publishApi ; then
    if kubectl -n default get secret kubernetes-tls > /dev/null 2> /dev/null ; then
      published_api_ca=$(kubectl -n default get secret kubernetes-tls -o json | jq '.data."ca.crt"' -r | base64 -d)
      values::set userAuthn.publishedApiCa "$published_api_ca"
    fi
  fi
}

hook::run "$@"
