#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  cat << EOF
{
  "beforeHelm": 10,
  "onKubernetesEvent": [
    {
      "kind": "Endpoints",
      "objectName": "kubernetes",
      "namespaceSelector": {
        "matchNames": [
          "default"
        ]
      }
    }
  ]
}
EOF
}

function __main__() {
  if [[ $(values::get userAuthn.publishAPI.enable) != "true" ]]; then
    exit 0
  fi
  kubernetes_apiserver_addresses=$(kubectl -n default get ep kubernetes -o json | jq -r '[.subsets[].addresses[].ip]')
  values::set userAuthn.internal.kubernetesApiserverAddresses "$kubernetes_apiserver_addresses"
}

hook::run $@
