#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
   configVersion: v1
   kubernetes:
   - name: secret
     group: main
     keepFullObjectsInMemory: false
     apiVersion: v1
     kind: Secret
     executeHookOnEvent: ["Added", "Modified"]
     nameSelector:
       matchNames: ["kubernetes-tls", "kubernetes-tls-customcertificate"]
     namespace:
       nameSelector:
         matchNames: ["d8-user-authn"]
     jqFilter: |
       {
         name: .metadata.name,
         data: (.data."ca.crt" // "") | @base64d
       }
EOF
}

function __main__() {
  if context::has snapshots.secret.0; then
    secret_name="$(module::https_secret_name "kubernetes-tls")"
    # shellcheck disable=SC2016
    data="$(context::jq -r --arg secret_name "$secret_name" \
      '[.snapshots.secret[] | select(.filterResult.name==$secret_name)][0] | .filterResult.data')"
    if [ -n "$data" ]; then
      values::set "userAuthn.internal.publishedAPIKubeconfigGeneratorMasterCA" "$data"
    else
      values::unset "userAuthn.internal.publishedAPIKubeconfigGeneratorMasterCA"
    fi
  fi
}

hook::run "$@"
