#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  cat << EOF
{
  "beforeHelm": 10,
  "onKubernetesEvent": [
    {
      "kind": "secret",
      "event": [
        "add",
        "update",
        "delete"
      ],
      "namespaceSelector": {
        "matchNames": [
          "d8-user-authn"
        ]
      },
      "jqFilter": ".metadata.name | test(\".-dex-client-app\")"
    }
  ]
}
EOF
}

function __main__() {
  if kubectl -n d8-user-authn get secret -o json | jq '.items[] | select(.metadata.name|test(".-dex-client-app")) | .metadata.name' -e > /dev/null 2>&1 ; then
    dex_client_apps_names="$(kubectl -n d8-user-authn get secret -o json | jq '.items[] | select(.metadata.name|test(".-dex-client-app")) | .metadata.name' -r)"
    dex_client_apps_configs_sha256="$(kubectl -n d8-user-authn get secret -o json | jq '.items[] | select(.metadata.name|test(".-dex-client-app")) | .data' | sha256sum | awk '{print $1}')"
    values::set userAuthn.internal.dexClientAppsNames "$dex_client_apps_names"
    values::set userAuthn.internal.dexClientAppsConfigsSHA256 "$dex_client_apps_configs_sha256"
  else
    values::unset userAuthn.internal.dexClientAppsNames
    values::unset userAuthn.internal.dexClientsAppsConfigsSHA256
  fi
}

hook::run "$@"
