#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
   configVersion: v1
   kubernetes:
   - name: secret
     keepFullObjectsInMemory: false
     apiVersion: v1
     kind: Secret
     executeHookOnEvent: ["Added", "Modified"]
     nameSelector:
       matchNames: ["kubernetes-tls"]
     namespace:
       nameSelector:
         matchNames: ["d8-user-authn"]
     jqFilter: ".data.\"ca.crt\" | @base64d"
EOF
}

function __on_kubernetes::secret::synchronization() {
  if context::has objects.0; then
    values::set userAuthn.internal.publishedAPIKubeconfigGeneratorMasterCA "$(context::get objects.0.filterResult)"
  fi
}

function __on_kubernetes::secret::added_or_modified() {
  values::set userAuthn.internal.publishedAPIKubeconfigGeneratorMasterCA "$(context::get filterResult)"
}


hook::run $@
