#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  jo -p configVersion=v1 onStartup=5
}

function __on_startup() {
  kubernetes_ca_for_kubeconfig_generator=$(cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt)
  values::set userAuthn.internal.kubernetesCA "$kubernetes_ca_for_kubeconfig_generator"
}

hook::run $@
