#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  cat << EOF
{
  "beforeHelm": 10,
  "onKubernetesEvent": [
    {
      "kind": "configmap",
      "event": [
        "add",
        "update",
        "delete"
      ],
      "namespaceSelector": {
        "matchNames": [
          "kube-user-authn"
        ]
      },
      "jqFilter": ".metadata.name | test(\".-kubernetes-dex-client-app-redirect-uris\")"
    }
  ]
}
EOF
}

function __main__() {
  if kubectl -n kube-user-authn get configmap -o json | jq '.items[] | select(.metadata.name|test(".-kubernetes-dex-client-app-redirect-uris")) | .metadata.name' -e > /dev/null 2>&1 ; then
    kubernetes_dex_client_app_redirect_uris="$(kubectl -n kube-user-authn get configmap -o json | jq '.items[] | select(.metadata.name|test(".-kubernetes-dex-client-app-redirect-uris")) | .data' | jq '.[]' -r)"
    values::set userAuthn.kubernetesDexClientAppRedirectURIs "$kubernetes_dex_client_app_redirect_uris"
  else
    values::unset userAuthn.kubernetesDexClientAppRedirectURIs
  fi
}

hook::run "$@"
