#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  jo -p configVersion=v1 beforeHelm=10
}

function __on_before_helm() {
  if ! values::has --config userAuthn.kubeconfigGenerator ; then
    return 0
  fi
  kubeconfigGenerator=$(values::get --config userAuthn.kubeconfigGenerator)
  encodedNames=$(jq -rc 'to_entries[] | .key' <<< ${kubeconfigGenerator} | while read index ; do
    echo "\"$(fnv-encoder "kubeconfig-generator-$index")\""
  done | jq -s '.')

  values::set userAuthn.internal.kubeconfigEncodedNames "$encodedNames"
}

hook::run "$@"
