#!/bin/bash

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  jo -p beforeHelm=20
}

function __main__() {
  if ! values::has userAuthn.internal.kubernetesDexClientAppSecret ; then
    values::set userAuthn.internal.kubernetesDexClientAppSecret $(values::generate_password)
  fi
}

hook::run $@
