#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat <<EOF
    configVersion: v1
    beforeHelm: 10
    kubernetes:
    - name: kubernetes_secret
      apiVersion: v1
      kind: Secret
      watchEvent: ["Added", "Modified"]
      includeSnapshotsFrom:
      - kubernetes_secret
      nameSelector:
        matchNames: ["kubernetes-dex-client-app-secret"]
      namespace:
        nameSelector:
          matchNames: ["d8-user-authn"]
      jqFilter: '.data.secret | @base64d'
EOF
}

function __on_before_helm() {
  if ! values::has userAuthn.internal.kubernetesDexClientAppSecret ; then
    values::set userAuthn.internal.kubernetesDexClientAppSecret $(tools::generate_password)
  fi
}

function __main__(){
  if context::has snapshots.kubernetes_secret.0; then
    values::set userAuthn.internal.kubernetesDexClientAppSecret $(context::get snapshots.kubernetes_secret.0.filterResult)
  fi
}

hook::run $@
