#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p beforeHelm=20
}

function __main__() {
  if ! values::has userAuthn.kubernetesDexClientAppSecret ; then
    values::set --config userAuthn.kubernetesDexClientAppSecret $(values::generate_password)
  fi
}

hook::run $@
