#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p beforeHelm=5
}

function __main__() {
  if values::has --config userAuthn.users ; then
    users=$(values::get --config userAuthn.users)
    echo $users | jq -rc 'to_entries[]' | while read user; do
      password=$(echo $user | jq '.value' -r)
      if [ -z "$password" ] ; then
        generated_password=$(values::generate_password)
        values::set --config userAuthn.users.\'$(echo $user | jq '.key' -r)\' "$generated_password"
      fi
    done
  fi
}

hook::run "$@"
