#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
   configVersion: v1
   kubernetes:
   - name: user
     apiVersion: deckhouse.io/v1alpha1
     kind: User
     includeSnapshotsFrom:
     - user
     jqFilter: '.spec.userID = (.spec.userID // .metadata.name) | {"name": .metadata.name, "spec": .spec }'
EOF
}


function __main__() {
  crds=$(context::jq -rc '.snapshots.user | .[].filterResult' | while read userCRD ; do
    email=$(jq -rc '.spec.email' <<< ${userCRD})
    encodedName=$(deckhouse-controller helper fnv encode "$email")
    jq -rc " .encodedName |= \"$encodedName\"" <<< ${userCRD}
  done | jq -s '.')

  values::set userAuthn.internal.dexUsersCRDs "$crds"
}

hook::run "$@"
