#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  jo -p configVersion=v1 beforeHelm=10
}

function __on_before_helm() {
  if values::has --config userAuthn.users ; then
    users=$(values::get --config userAuthn.users)

    jq -rc 'to_entries[]' <<< ${users} | while read user; do
      password=$(jq '.value' -r <<< ${user})
      name=$(jq '.key' -r <<< ${user} | awk -F'@' '{print $1}')

      hash=$(htpasswd -bnBC 10 "" "$password" | tr -d ':\n' | sed 's/$2y/$2a/')
      kubernetes::create_yaml  << EOF
        apiVersion: deckhouse.io/v1alpha1
        kind: User
        metadata:
          name: "${name}"
        spec:
          email: "$(jq '.key' -r <<< ${user})"
          password: "${hash}"
EOF
    done
    values::unset --config userAuthn.users
  fi
}

hook::run $@
