#!/bin/bash

### Миграция 2019-09-12: https://github.com/deckhouse/deckhouse/merge_requests/1117
# Этот хук можно удалить, после выката данного MR'а на все инсталяции.

source /antiopa/shell_lib.sh

function __config__() {
  echo '
{
  "beforeHelm": 2
}'
}

function __main__() {
  if values::is_true --config userAuthn.publishApi ; then
    values::unset --config userAuthn.publishApi
    values::set --config userAuthn.publishAPI "{}"
    values::set --config userAuthn.publishAPI.enable "true"
  fi

  if values::has --config userAuthn.publishApiCert ; then
    values::set --config userAuthn.publishAPI.https "{}"
    values::set --config userAuthn.publishAPI.https.mode "Global"
    values::set --config userAuthn.publishAPI.https.global "{}"
    values::set --config userAuthn.publishAPI.https.global.kubeconfigGeneratorMasterCA "$(values::get --config userAuthn.publishApiCert)"
    values::unset --config userAuthn.publishApiCert
  fi
}

hook::run "$@"
