#!/bin/bash

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  jo -p configVersion=v1 beforeHelm=10
}

function __main__() {
  if values::has --config userAuthn.users ; then
    users=$(values::get --config userAuthn.users)

    echo "$users" | jq -rc 'to_entries[]' | while read user; do
      password=$(echo "$user" | jq '.value' -r)
      hash=$(htpasswd -bnBC 10 "" "$password" | tr -d ':\n' | sed 's/$2y/$2a/')
      name=$(echo "$user" | jq '.key' -r | awk -F'@' '{print $1}')
      cat <<EOF | kubectl create -f -
apiVersion: deckhouse.io/v1alpha1
kind: User
metadata:
  name: "$name"
spec:
  email: "$(echo "$user" | jq '.key' -r )"
  password: "$hash"
EOF
    done
    values::unset --config userAuthn.users
  fi
}

hook::run "$@"
