apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:project:admin
  annotations:
    en.meta.deckhouse.io/title: "Project Administrator"
    ru.meta.deckhouse.io/title: "Администратор проекта"
    en.meta.deckhouse.io/description: "Project Manager plus RBAC management within the project (ProjectRoleBinding)."
    ru.meta.deckhouse.io/description: "Права менеджера проекта плюс управление RBAC в пределах проекта (ProjectRoleBinding)."
    rbac.deckhouse.io/bindable-only-via: "ProjectRoleBinding,ClusterProjectRoleBinding"
  labels:
    heritage: deckhouse
    module: multitenancy-manager
    rbac.deckhouse.io/delegatable: "true"
    rbac.deckhouse.io/kind: role
    rbac.deckhouse.io/scope: project
    rbac.deckhouse.io/aggregate-to-project-as: superadmin
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.deckhouse.io/aggregate-to-project-as: admin
rules: []
