#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p onStartup=150 onKubernetesEvent="$(jo -a \
    "$(jo kind=node jqFilter=".metadata.labels")" \
  )"
}

function __main__() {
  if cluster::has_system_nodes ; then
    values::set global.discovery.clusterHasSystemNodes true
  else
    values::set global.discovery.clusterHasSystemNodes false
  fi
}

hook::run $@
