#!/bin/bash

# Copyright 2021 Flant CJSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: uuid_config
      keepFullObjectsInMemory: false
      apiVersion: v1
      kind: ConfigMap
      namespace:
        nameSelector:
          matchNames: [kube-system]
      nameSelector:
        matchNames: [d8-cluster-uuid]
      jqFilter: '.data."cluster-uuid"'
EOF
}

function __on_kubernetes::uuid_config::synchronization() {
  if context::has objects.0; then
    cluster_uuid="$(context::get objects.0.filterResult)"
  else
    cluster_uuid=$(uuidgen -r)
    kubernetes::create_yaml << EOF
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: d8-cluster-uuid
  namespace: kube-system
  labels:
    heritage: deckhouse
data:
  cluster-uuid: "${cluster_uuid}"
EOF
  fi

  values::set global.discovery.clusterUUID "${cluster_uuid}"
}

function __on_kubernetes::uuid_config::added_or_modified() {
  values::set global.discovery.clusterUUID "$(context::get filterResult)"
}

function __on_kubernetes::uuid_config::deleted() {
  >&2 echo "ERROR: CM kube-system/d8-cluster-uuid was deleted. Don't know what to do."
  return 1
}

hook::run "$@"
