#!/bin/bash
#TODO: Need SyncAll mode

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  yq r -j - << EOF
    configVersion: v1
    kubernetes:
    - name: node-roles
      apiVersion: v1
      kind: Node
      jqFilter: '
        .metadata.labels // {} | keys[] | select(startswith("node-role.flant.com/")) | split("/")[1] | gsub("-(?<a>[a-z])"; .a|ascii_upcase)
      '
EOF
}

function __main__() {
  node_counts=$(kubectl get node -o json | jq -r 'include "camel"; [.items[].metadata.labels | keys[] | select(startswith("node-role.flant.com/")) |
                                            split("/")[1]] | group_by(.) | map({(unique_by(.)[] | camel): length}) | add // {}')
  values::set global.discovery.nodeCountByRole "$node_counts"
}

hook::run "$@"
