#!/bin/bash

# Copyright 2021 Flant CJSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: kube_dns_svc
      group: main
      keepFullObjectsInMemory: false
      apiVersion: v1
      kind: Service
      namespace:
        nameSelector:
          matchNames: [kube-system]
      labelSelector:
        matchExpressions:
        - key: k8s-app
          operator: In
          values:
          - kube-dns
          - coredns
      jqFilter: '.spec.clusterIP'
EOF
}

function __main__() {
  dns_addresses=$(context::jq -rc '[.snapshots.kube_dns_svc | .[].filterResult | select(. and . != "None")] | unique')
  if ! jq -rce '. | length == 1' <<< ${dns_addresses} ; then
    >&2 echo "ERROR: can't find a single kube-dns service, found ${dns_addresses}"
    return 1
  fi

  values::set global.discovery.clusterDNSAddress $(jq -rc '.[0]' <<< ${dns_addresses})
}

hook::run "$@"
