#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: cluster_configuration
      includeSnapshotsFrom: ["cluster_configuration"]
      apiVersion: v1
      kind: Secret
      namespace:
        nameSelector:
          matchNames: [kube-system]
      nameSelector:
        matchNames: [d8-cluster-configuration]
      jqFilter: '.data."cluster-configuration.yaml" | @base64d'
EOF
}

function set_values_from_cluster_configuration_yaml() {
  cluster_configuration_json=$(echo "$1" | deckhouse-controller helper cluster-configuration | jq -r '.clusterConfig')

  values::set global.clusterConfiguration "$cluster_configuration_json"

  values::set global.discovery.podSubnet "$(echo "$cluster_configuration_json" | jq -r '.podSubnetCIDR')"
  values::set global.discovery.serviceSubnet "$(echo "$cluster_configuration_json" | jq -r '.serviceSubnetCIDR')"
}

function __main__() {
  if context::has snapshots.cluster_configuration.0; then
    set_values_from_cluster_configuration_yaml "$(context::get snapshots.cluster_configuration.0.filterResult)"
  else
    values::unset global.clusterConfiguration
  fi
}

hook::run "$@"
