#!/bin/bash

# Hook detects if control plane in the cluster configured as HA
# If there are more than one replicas of apiserver, someone has cared about it. It means that our cluster
# needs High Availability, for example, in modules.
# (Read more about global.highAvailability in /README.md).

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: master_nodes
      group: main
      keepFullObjectsInMemory: false
      apiVersion: v1
      kind: Node
      labelSelector:
        matchLabels:
          node-role.kubernetes.io/master: ""
      jqFilter: .metadata.name
EOF
}

function __main__() {
  master_nodes="$(context::jq -r '.snapshots.master_nodes | length')"

  values::set global.discovery.clusterMasterCount "$master_nodes"

  if [[ "$master_nodes" > 1 ]]; then
    values::set global.discovery.clusterControlPlaneIsHighlyAvailable "true"
  else
    values::set global.discovery.clusterControlPlaneIsHighlyAvailable "false"
  fi
}

hook::run $@
