#!/bin/bash

# Copyright 2021 Flant CJSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Hook detects if control plane in the cluster configured as HA
# If there are more than one replicas of apiserver, someone has cared about it. It means that our cluster
# needs High Availability, for example, in modules.
# (Read more about global.highAvailability in /README.md).

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: master_nodes
      group: main
      keepFullObjectsInMemory: false
      apiVersion: v1
      kind: Node
      labelSelector:
        matchLabels:
          node-role.kubernetes.io/master: ""
      jqFilter: .metadata.name
EOF
}

function __main__() {
  master_nodes="$(context::jq -r '.snapshots.master_nodes | length')"

  values::set global.discovery.clusterMasterCount "$master_nodes"

  if [[ "$master_nodes" > 1 ]]; then
    values::set global.discovery.clusterControlPlaneIsHighlyAvailable "true"
  else
    values::set global.discovery.clusterControlPlaneIsHighlyAvailable "false"
  fi
}

hook::run $@
