#!/bin/bash

# Возникла проблема: при обновлении кластера Kubernetes SemVer comparison не срабатывал, что приводило к отвалу etcd из мониторинга Prometheus.
# Не помогал рестарт deckhouse, а только полное удаление Helm релиза prometheus и последующая установка.
# Целью данного хука является введение независимого от Helm механизма определения версии кластера.

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - apiVersion: v1
      kind: pod
      watchEvent: [Added, Modified]
      labelSelector:
        matchLabels:
          component: kube-apiserver
          tier: control-plane
      namespace:
        nameSelector:
          matchNames: [kube-system]
      jqFilter: '.spec.containers[].image'
    - apiVersion: v1
      kind: pod
      watchEvent: [Added, Modified]
      labelSelector:
        matchLabels:
          k8s-app: kube-apiserver
      namespace:
        nameSelector:
          matchNames: [kube-system]
      jqFilter: '.spec.containers[].image'
EOF
}

function __main__() {
  cluster_version=$(kubectl version -o json | jq -er '.serverVersion.gitVersion[1:]')

  if [ -n "$cluster_version" ]; then
    values::set global.discovery.clusterVersion "$cluster_version"
  fi
}

hook::run $@
