#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: node_internal_ips
      includeSnapshotsFrom: ["node_internal_ips"]
      kind: Node
      apiVersion: v1
      jqFilter: '[.status.addresses[]? | select (.type == "InternalIP") | .address]'

    - name: pod_subnet_by_component
      includeSnapshotsFrom: ["pod_subnet_by_component", "pod_subnet_by_k8s_app", "cluster_configuration"]
      apiVersion: v1
      kind: Pod
      namespace:
        nameSelector:
          matchNames: [kube-system]
      labelSelector:
        matchLabels:
          component: kube-controller-manager
          tier: control-plane
      jqFilter: |
        .spec.containers[] | select(.name == "kube-controller-manager") |
        (.command + .args) | join(" ") |
        match( "(^|\\\\s+)--cluster-cidr=([0-9]+\\\\.[0-9]+\\\\.[0-9]+\\\\.[0-9]+\\\\/[0-9]+)(\\\\s+|$)") | .captures[1].string

    - name: pod_subnet_by_k8s_app
      includeSnapshotsFrom: ["pod_subnet_by_component", "pod_subnet_by_k8s_app", "cluster_configuration"]
      apiVersion: v1
      kind: Pod
      namespace:
        nameSelector:
          matchNames: [kube-system]
      labelSelector:
        matchLabels:
          k8s-app: kube-controller-manager
      jqFilter: |
        .spec.containers[] | select(.name == "kube-controller-manager") |
        (.command + .args) | join(" ") |
        match( "(^|\\\\s+)--cluster-cidr=([0-9]+\\\\.[0-9]+\\\\.[0-9]+\\\\.[0-9]+\\\\/[0-9]+)(\\\\s+|$)") | .captures[1].string

    - name: service_subnet_by_component
      includeSnapshotsFrom: ["service_subnet_by_component", "service_subnet_by_k8s_app", "cluster_configuration"]
      apiVersion: v1
      kind: Pod
      namespace:
        nameSelector:
          matchNames: [kube-system]
      labelSelector:
        matchLabels:
          component: kube-apiserver
          tier: control-plane
      jqFilter: |
        .spec.containers[] | select(.name == "kube-apiserver") |
        (.command + .args) | join(" ") |
        match( "(^|\\\\s+)--service-cluster-ip-range=([0-9]+\\\\.[0-9]+\\\\.[0-9]+\\\\.[0-9]+\\\\/[0-9]+)(\\\\s+|$)") | .captures[1].string

    - name: service_subnet_by_k8s_app
      includeSnapshotsFrom: ["service_subnet_by_component", "service_subnet_by_k8s_app", "cluster_configuration"]
      apiVersion: v1
      kind: Pod
      namespace:
        nameSelector:
          matchNames: [kube-system]
      labelSelector:
        matchLabels:
          k8s-app: kube-apiserver
      jqFilter: |
        .spec.containers[] | select(.name == "kube-apiserver") |
        (.command + .args) | join(" ") |
        match( "(^|\\\\s+)--service-cluster-ip-range=([0-9]+\\\\.[0-9]+\\\\.[0-9]+\\\\.[0-9]+\\\\/[0-9]+)(\\\\s+|$)") | .captures[1].string

    - name: cluster_configuration
      apiVersion: v1
      kind: Secret
      executeHookOnEvent: []
      executeHookOnSynchronization: false
      namespace:
        nameSelector:
          matchNames: [d8-system]
      nameSelector:
        matchNames: [d8-cluster-configuration]
      jqFilter: '.data."cluster-configuration.yaml"'
EOF

}

### nodeInternalIPs
function __on_kubernetes::node_internal_ips() {
  node_internal_ips="$(context::jq -r '[.snapshots.node_internal_ips[] | .filterResult] | add | sort')"
  values::set global.discovery.nodeInternalIPs "$node_internal_ips"
}


### podSubnet
function _pod_subnet() {
  if context::has 'snapshots.cluster_configuration[0].object'; then
    return 0
  fi

  pod_subnet="$(context::jq -er '(.snapshots.pod_subnet_by_component + .snapshots.pod_subnet_by_k8s_app)[0].filterResult')"
  values::set global.discovery.podSubnet "$pod_subnet"
}

function __on_kubernetes::pod_subnet_by_component() {
  _pod_subnet
}

function __on_kubernetes::pod_subnet_by_k8s_app() {
  _pod_subnet
}


### serviceSubnet
function _service_subnet() {
  if context::has 'snapshots.cluster_configuration[0].object'; then
    return 0
  fi

  service_subnet="$(context::jq -er '(.snapshots.service_subnet_by_component + .snapshots.service_subnet_by_k8s_app)[0].filterResult')"
  values::set global.discovery.serviceSubnet "$service_subnet"
}

function __on_kubernetes::service_subnet_by_component() {
  _service_subnet
}

function __on_kubernetes::service_subnet_by_k8s_app() {
  _service_subnet
}

hook::run "$@"
