#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: node_roles
      group: main
      keepFullObjectsInMemory: false
      apiVersion: v1
      kind: Node
      jqFilter: |
        [
          .metadata.labels // {} | keys[] |
          select(startswith("node-role.flant.com/")) |
          split("/")[1] | gsub("-(?<a>[a-z])"; .a|ascii_upcase)
        ]
EOF
}

function __main__() {
  node_counts="$(
    context::jq -r '
      [.snapshots.node_roles[] | select(.filterResult != null) | .filterResult] | add |
      group_by(.) | map({(.[0]): length}) | add // {}'
  )"
  values::set global.discovery.d8SpecificNodeCountByRole "$node_counts"
}

hook::run "$@"
