#!/bin/bash

source /deckhouse/shell_lib.sh


# Migration 2020-07-17: delete after deploying to all clusters
function __config__() {
  cat << EOF
    configVersion: v1
    onStartup: 10
EOF
}

function __main__() {
  if cluster_configuration=$(kubectl -n kube-system get secrets d8-cluster-configuration -o json) ; then
    updated_cluster_configuration=$(jq -rc '.data."cluster-configuration.yaml"' <<< ${cluster_configuration} \
      | base64 -d | yq r - --tojson | jq -rc '.sshPublicKeys //= []' | yq r - | base64 -w0)

    jq -rc --arg data "$updated_cluster_configuration" '.data."cluster-configuration.yaml" = $data' <<< ${cluster_configuration} \
      | kubernetes::replace_or_create_json
  fi
}

hook::run "$@"
