#!/bin/bash

# Hook detects how dns is implemented in the cluster. Basically it just detects deployment name with labels `k8s-app: kube-dns`

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: kube_dns_deployment
      group: main
      keepFullObjectsInMemory: false
      apiVersion: apps/v1
      kind: Deployment
      namespace:
        nameSelector:
          matchNames: [kube-system]
      labelSelector:
        matchLabels:
          k8s-app: kube-dns
      jqFilter: '.metadata.name'
      executeHookOnEvent: ["Added", "Modified"]
EOF
}

function __main__() {
  if values::array_has global.enabledModules "kube-dns" ; then
    values::set global.discovery.clusterDNSImplementation "coredns"
    return 0
  fi

  if ! context::has snapshots.kube_dns_deployment.0; then
    >&2 echo "ERROR: can't determine cluster DNS implementation"
    return 1
  fi

  values::set global.discovery.clusterDNSImplementation "$(context::get snapshots.kube_dns_deployment.0.filterResult)"
}

hook::run "$@"
