#!/bin/bash

# Автоопределятор внутреннего адреса DNS.

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  jo -p onStartup=50
}

function __main__() {
  cluster_dns_address=$(kubectl --namespace kube-system get service kube-dns -o json | jq -r '.spec.clusterIP')
  values::set global.discovery.clusterDNSAddress "${cluster_dns_address}"
}

hook::run "$@"
