#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  jo -p onStartup=150 onKubernetesEvent="$(jo -a \
    "$(jo kind=storageclass jqFilter='[.metadata.annotations."storageclass.beta.kubernetes.io/is-default-class", .metadata.annotations."storageclass.kubernetes.io/is-default-class", .metadata.name]')" \
  )"
}

function __main__() {
  if default_storage_class=$(kubectl get storageclass -o json | jq '.items[] | select ((.metadata.annotations."storageclass.beta.kubernetes.io/is-default-class" == "true") or (.metadata.annotations."storageclass.kubernetes.io/is-default-class" == "true")) | .metadata.name' -r | head -n 1) && [[ -n "$default_storage_class" ]] ; then
    values::set global.discovery.defaultStorageClass $default_storage_class
  else
    values::unset global.discovery.defaultStorageClass
  fi
}

hook::run $@
