#!/bin/bash

# Copyright 2021 Flant CJSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Возникла проблема: при обновлении кластера Kubernetes SemVer comparison не срабатывал, что приводило к отвалу etcd из мониторинга Prometheus.
# Не помогал рестарт deckhouse, а только полное удаление Helm релиза prometheus и последующая установка.
# Целью данного хука является введение независимого от Helm механизма определения версии кластера.

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - apiVersion: v1
      group: main
      keepFullObjectsInMemory: false
      kind: pod
      executeHookOnEvent: [Added, Modified]
      labelSelector:
        matchLabels:
          component: kube-apiserver
          tier: control-plane
      namespace:
        nameSelector:
          matchNames: [kube-system]
      jqFilter: '.spec.containers[].image'
    - apiVersion: v1
      group: main
      keepFullObjectsInMemory: false
      kind: pod
      executeHookOnEvent: [Added, Modified]
      labelSelector:
        matchLabels:
          k8s-app: kube-apiserver
      namespace:
        nameSelector:
          matchNames: [kube-system]
      jqFilter: '.spec.containers[].image'
    - name: endpoints
      group: main
      keepFullObjectsInMemory: false
      apiVersion: v1
      kind: Endpoints
      nameSelector:
        matchNames: [kubernetes]
      namespace:
        nameSelector:
          matchNames: [default]
      jqFilter: |
        [
          .subsets[] |
          (.ports[] | select(.name == "https") | .port | tostring) as \$port |
          .addresses[] | .ip + ":" + \$port
        ]
EOF
}

function __main__() {
  endpoints="$(context::jq -r '.snapshots.endpoints | first | .filterResult[]')"

  kubernetes_versions=( )
  for e in $endpoints; do
    v=$(curl -sk -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" "https://${e}/version?timeout=32s" |
      jq -er '.gitVersion[1:]' | grep -Po "\d+\.\d+\.\d+")
    kubernetes_versions+=( "$v" )
  done

  # shellcheck disable=SC2128
  if [ -n "$kubernetes_versions" ]; then
    kubernetes_version_min="$(semver::get_min "${kubernetes_versions[@]}")"

    if [ -n "$kubernetes_version_min" ]; then
      values::set global.discovery.kubernetesVersion "$kubernetes_version_min"
      echo "$kubernetes_version_min" > /tmp/kubectl_version
    fi

    values::set global.discovery.kubernetesVersions "$(echo -ne "${kubernetes_versions[@]}" | jq -rRs '[split(" ")[] | select(length > 0)]')"
  fi
}

hook::run "$@"
