#!/bin/bash

# Copyright 2021 Flant CJSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: prometheus_scrape_interval
      keepFullObjectsInMemory: false
      apiVersion: v1
      kind: ConfigMap
      namespace:
        nameSelector:
          matchNames: [d8-monitoring]
      nameSelector:
        matchNames: [prometheus-scrape-interval]
      jqFilter: '.data.scrapeInterval'
EOF
}

function __on_kubernetes::prometheus_scrape_interval::synchronization() {
  if context::has objects.0; then
    values::set global.discovery.prometheusScrapeInterval "$(context::get objects.0.filterResult | deckhouse-controller helper unit convert --mode duration)"
  else
    values::set global.discovery.prometheusScrapeInterval 30
  fi
}

function __on_kubernetes::prometheus_scrape_interval::added_or_modified() {
  values::set global.discovery.prometheusScrapeInterval "$(context::get filterResult | deckhouse-controller helper unit convert --mode duration)"
}

function __on_kubernetes::prometheus_scrape_interval::deleted() {
  values::set global.discovery.prometheusScrapeInterval 30
}

hook::run "$@"
