{{- $providerClusterConfiguration := .Values.cloudProviderDynamix.internal.providerClusterConfiguration | required "internal.providerClusterConfiguration is required" -}}

{{- define "dynamix_capd_envs" -}}
- name: DYNAMIX_APP_ID
  valueFrom:
    secretKeyRef:
      name: dynamix-credentials
      key: appId
- name: DYNAMIX_APP_SECRET
  valueFrom:
    secretKeyRef:
      name: dynamix-credentials
      key: appSecret
- name: DYNAMIX_OAUTH2_URL
  valueFrom:
    secretKeyRef:
      name: dynamix-credentials
      key: oAuth2Url
- name: DYNAMIX_CONTROLLER_URL
  valueFrom:
    secretKeyRef:
      name: dynamix-credentials
      key: controllerUrl
- name: DYNAMIX_INSECURE
  valueFrom:
    secretKeyRef:
      name: dynamix-credentials
      key: insecure
{{- end -}}

{{- $capiConfig := dict -}}
{{- $_ := set $capiConfig "fullname" "capd-controller-manager" -}}
{{- $_ := set $capiConfig "image" (include "helm_lib_module_image" (list . "capdControllerManager")) -}}
{{- $_ := set $capiConfig "capiProviderName" "infrastructure-dynamix" -}}
{{- $_ := set $capiConfig "additionalEnv" (include "dynamix_capd_envs" . | fromYamlArray) -}}
{{- $_ := set $capiConfig "vpaEnabled" true -}}

{{- include "helm_lib_capi_controller_manager_manifests" (list . $capiConfig) }}
