{{- if and (hasKey .Values "cloudProviderYandex") (hasKey .Values.cloudProviderYandex "internal") (hasKey .Values.cloudProviderYandex.internal "capyandexControllerManagerWebhookCert") }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: capyandex-controller-manager-webhook-tls
  namespace: d8-cloud-provider-yandex
  {{- include "helm_lib_module_labels" (list . (dict "app" "capyandex-controller-manager")) | nindent 2 }}
data:
  ca.crt: {{ .Values.cloudProviderYandex.internal.capyandexControllerManagerWebhookCert.ca | b64enc }}
  tls.crt: {{ .Values.cloudProviderYandex.internal.capyandexControllerManagerWebhookCert.crt | b64enc }}
  tls.key: {{ .Values.cloudProviderYandex.internal.capyandexControllerManagerWebhookCert.key | b64enc }}
{{- end }}
