#!/bin/bash -e

###
# Миграция 2018-03-19, https://github.com/deckhouse/deckhouse/merge_requests/132
if kubectl -n monitoring get deploy/prometheus-operator > /dev/null 2> /dev/null ; then
  for tpr in alertmanagers.monitoring.coreos.com prometheuses.monitoring.coreos.com servicemonitors.monitoring.coreos.com ; do
    if kubectl get thirdpartyresource/$tpr > /dev/null 2> /dev/null ; then
      kubectl delete thirdpartyresource/$tpr
    fi
  done

  for resource in service/prometheus-operator serviceaccount/prometheus-operator clusterrolebinding/prometheus-operator clusterrole/prometheus-operator deploy/prometheus-operator ; do
    if kubectl -n monitoring get $resource > /dev/null 2> /dev/null ; then
      kubectl -n monitoring delete $resource
    fi
  done
fi
