apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    heritage: deckhouse
    module: operator-prometheus
    rbac.deckhouse.io/aggregate-to-observability-as: manager
    rbac.deckhouse.io/kind: capability
    rbac.deckhouse.io/capability: "system-capability.operator-prometheus.edit"
    rbac.deckhouse.io/scope: system
    rbac.deckhouse.io/namespace: d8-operator-prometheus
  name: d8:system-capability:operator-prometheus:edit
  annotations:
    en.meta.deckhouse.io/title: "Module operator-prometheus: edit configuration"
    ru.meta.deckhouse.io/title: "Модуль operator-prometheus: управление конфигурацией"
    en.meta.deckhouse.io/description: "Manage the operator-prometheus module configuration."
    ru.meta.deckhouse.io/description: "Управление конфигурацией модуля operator-prometheus."
rules:
- apiGroups:
  - deckhouse.io
  resourceNames:
  - operator-prometheus
  resources:
  - moduleconfigs
  verbs:
  - create
  - update
  - patch
  - delete
