#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 0
    schedule:
    - name: madison_backends_discovery
      queue: /modules/prometheus-madison-integration/madison_backends_discovery
      crontab: "*/10 * * * *"
      allowFailure: true
EOF
}

function __main__() {
  if ! values::is_false prometheusMadisonIntegration.madisonSelfSetupKey ; then
    backends=$(getent ahosts madison.flant.com | grep STREAM | awk {'print $1'} | sort | jo -a)
    values::set prometheusMadisonIntegration.internal.madisonBackends "$backends"
  elif values::has prometheusMadisonIntegration.internal.madisonBackends ; then
    values::unset prometheusMadisonIntegration.internal.madisonBackends
  fi
}

hook::run "$@"
