#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    schedule:
    - name: madison_revoke
      queue: /modules/prometheus-madison-integration/madison_revoke
      crontab: "*/5 * * * *"
      allowFailure: true
EOF
}

function __main__() {
  project=$(values::get --required global.project)

  if values::has prometheusMadisonIntegration.madisonAuthKey ; then
    uri=/api/$project/self_status/$(values::get --required prometheusMadisonIntegration.madisonAuthKey)
    response=$(curl -s -w '\n{"http_code": "%{http_code}"}\n' https://madison.flant.com$uri | jq -s add)

    if [[ "$(echo "$response" | jq -r '.http_code')" == "401" ]] && [[ "$(echo "$response" | jq -r '.error')" == "Archived setup" ]] ; then
      values::set --config prometheusMadisonIntegration.madisonSelfSetupKey false
      values::unset --config prometheusMadisonIntegration.madisonAuthKey
    fi
  fi
}

hook::run "$@"
