#!/bin/bash

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  jo -p beforeHelm=0 schedule="$(jo -a \
    "$(jo allowFailure=true crontab="*/10 * * * *")"
  )"
}

function __main__() {
  if ! values::is_false prometheusMadisonIntegration.madisonSelfSetupKey ; then
    backends=$(getent ahosts madison.flant.com | grep STREAM | awk {'print $1'} | sort | jo -a)
    values::set prometheusMadisonIntegration.internal.madisonBackends "$backends"
  elif values::has prometheusMadisonIntegration.internal.madisonBackends ; then
    values::unset prometheusMadisonIntegration.internal..madisonBackends
  fi
}

hook::run "$@"
