{
 "title": "DNS (kube-dns)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(up{job=\"kube-dns\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "dnsmasq", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(kubedns_dnsmasq_hits{job=\"kube-dns\", pod=~\"$pod\"}[1m]) + rate(kubedns_dnsmasq_misses{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(kubedns_dnsmasq_hits{job=\"kube-dns\", pod=~\"$pod\"}[1m]) + rate(kubedns_dnsmasq_misses{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(kubedns_dnsmasq_errors{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(kubedns_dnsmasq_errors{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kubedns_dnsmasq_max_size{job=\"kube-dns\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubedns_dnsmasq_hits{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4])) / (sum(rate(kubedns_dnsmasq_hits{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4])) + sum(rate(kubedns_dnsmasq_misses{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4])))",
     "legendFormat": "Hits"
    },
    {
     "expr": " sum(rate(kubedns_dnsmasq_misses{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4])) / (sum(rate(kubedns_dnsmasq_hits{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4])) + sum(rate(kubedns_dnsmasq_misses{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4])))",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Cache Insertions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 11 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(kubedns_dnsmasq_insertions{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(kubedns_dnsmasq_insertions{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cache Evictions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 11 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(kubedns_dnsmasq_evictions{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(kubedns_dnsmasq_evictions{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4]))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "SkyDNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(skydns_skydns_dns_request_count_total{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(skydns_skydns_dns_request_count_total{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(skydns_skydns_dns_error_count_total{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(skydns_skydns_dns_error_count_total{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(skydns_skydns_dns_cachemiss_count_total{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(skydns_skydns_dns_cachemiss_count_total{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Avg Request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(skydns_skydns_dns_request_duration_seconds_sum{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4])) by (pod) / sum(rate(skydns_skydns_dns_request_duration_seconds_count{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4])) by (pod) * 1000000",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(skydns_skydns_dns_request_duration_seconds_sum{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4])) / sum(rate(skydns_skydns_dns_request_duration_seconds_count{job=\"kube-dns\", pod=~\"$pod\"}[$__interval_sx4])) * 1000000",
     "legendFormat": "Overall"
    }
   ]
  }
 ]
}