{
 "title": "Distribution",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(registry_storage_action_seconds_count, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(registry_storage_action_seconds_count{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": {
     "query": "label_values(registry_storage_action_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\"}, endpoint)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Registry storage (pods: $pod)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Distribution actions duration 90th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(registry_storage_action_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (le))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(registry_storage_action_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (le, action, driver))",
     "legendFormat": "{{action}} {{driver}}"
    }
   ]
  },
  {
   "title": "Distribution actions duration 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(registry_storage_action_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (le))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(registry_storage_action_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (le, action, driver))",
     "legendFormat": "{{action}} {{driver}}"
    }
   ]
  },
  {
   "title": "Distribution actions duration 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(registry_storage_action_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (le))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(registry_storage_action_seconds_bucket{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (le, action, driver))",
     "legendFormat": "{{action}} {{driver}}"
    }
   ]
  },
  {
   "title": "Distribution actions per seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(registry_storage_action_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__rate_interval])) by (action, driver)",
     "legendFormat": "{{action}} {{driver}}"
    }
   ]
  },
  {
   "title": "Registry http (pods: $pod)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distribution http requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(registry_http_in_flight_requests{namespace=~\"$namespace\", pod=~\"$pod\", endpoint=~\"$endpoint\"}) by (handler)",
       "legendFormat": "{{handler}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go (pods: $pod)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "process memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}",
       "legendFormat": "{{pod}} - resident"
      },
      {
       "expr": "process_virtual_memory_bytes{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}",
       "legendFormat": "{{pod}} - virtual"
      }
     ]
    },
    {
     "title": "process memory deriv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(process_resident_memory_bytes{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__interval])",
       "legendFormat": "{{pod}} - resident"
      },
      {
       "expr": "deriv(process_virtual_memory_bytes{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__interval])",
       "legendFormat": "{{pod}} - virtual"
      }
     ]
    },
    {
     "title": "go memstats",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}",
       "legendFormat": "{{pod}} - bytes allocated"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}[30s])",
       "legendFormat": "{{pod}} - alloc rate"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}",
       "legendFormat": "{{pod}} - stack inuse"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}",
       "legendFormat": "{{pod}} - heap inuse"
      }
     ]
    },
    {
     "title": "go memstats deriv",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "deriv(go_memstats_alloc_bytes{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__interval])",
       "legendFormat": "{{pod}} - bytes allocated"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__interval])",
       "legendFormat": "{{pod}} - alloc rate"
      },
      {
       "expr": "deriv(go_memstats_stack_inuse_bytes{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__interval])",
       "legendFormat": "{{pod}} - stack inuse"
      },
      {
       "expr": "deriv(go_memstats_heap_inuse_bytes{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__interval])",
       "legendFormat": "{{pod}} - heap inuse"
      }
     ]
    },
    {
     "title": "open fds",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_open_fds{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "open fds deriv",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "deriv(process_open_fds{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}[$__interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GC duration quantiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{namespace=~\"$namespace\",pod=~\"$pod\", endpoint=~\"$endpoint\"}",
       "legendFormat": "{{pod}}: {{quantile}}"
      }
     ]
    }
   ]
  }
 ]
}