#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  legacy::common_hooks::https::copy_custom_certificate::config
}

function __main__() {
  legacy::common_hooks::https::copy_custom_certificate::main "kube-system" "ingress-tls"
  legacy::common_hooks::https::copy_custom_certificate::main "d8-dashboard" "ingress-tls"
}

hook::run "$@"
