#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  legacy::common_hooks::https::delete_not_matching_certificate_secret::config
}

function __main__() {
  if [[ $(values::get dashboard.version) == "1" ]]; then
    legacy::common_hooks::https::delete_not_matching_certificate_secret::main "kube-system"
  else
    legacy::common_hooks::https::delete_not_matching_certificate_secret::main "d8-dashboard"
  fi
}

hook::run "$@"
