#!/bin/bash

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  common_hooks::https::delete_not_matching_certificate_secret::config
}

function __main__() {
  if [[ $(values::get dashboard.version) == "1" ]]; then
    common_hooks::https::delete_not_matching_certificate_secret::main "kube-system"
  else
    common_hooks::https::delete_not_matching_certificate_secret::main "d8-dashboard"
  fi
}

hook::run "$@"
