---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: node-controller-validating-webhook-configuration
  annotations:
    werf.io/deploy-dependency-deployment: state=ready,kind=Deployment,name=node-controller,namespace=d8-cloud-instance-manager
    werf.io/deploy-dependency-service: state=present,kind=Service,name=node-controller-webhook,namespace=d8-cloud-instance-manager
    werf.io/deploy-on: pre-install,pre-upgrade,pre-rollback
    werf.io/track-termination-mode: WaitUntilResourceReady
  {{- include "helm_lib_module_labels" (list . (dict "app" "node-controller")) | nindent 2 }}
webhooks:
- name: nodegroup.validation.node-controller.deckhouse.io
  admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ .Values.nodeManager.internal.nodeControllerWebhookCert.ca | b64enc }}
    service:
      name: node-controller-webhook
      namespace: d8-cloud-instance-manager
      path: /validate-deckhouse-io-v1-nodegroup
  failurePolicy: Fail
  matchPolicy: Equivalent
  sideEffects: None
  rules:
  - apiGroups:
    - deckhouse.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodegroups
    scope: Cluster
