#!/bin/bash

# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 10
EOF
}

function __main__() {
  if ! values::has upmeter.auth.webui.externalAuthentication ; then
    if ! values::has --config upmeter.auth ; then
      values::set --config upmeter.auth {}
    fi
    if ! values::has --config upmeter.auth.webui ; then
      values::set --config upmeter.auth.webui {}
    fi
    if ! values::has upmeter.auth.webui.password ; then
      values::set --config upmeter.auth.webui.password $(tools::generate_password)
    fi
  else
    values::unset --config upmeter.auth.webui.password
  fi

  if ! values::has upmeter.auth.status.externalAuthentication ; then
    if ! values::has --config upmeter.auth ; then
      values::set --config upmeter.auth {}
    fi
    if ! values::has --config upmeter.auth.status ; then
      values::set --config upmeter.auth.status {}
    fi
    if ! values::has upmeter.auth.status.password ; then
      values::set --config upmeter.auth.status.password $(tools::generate_password)
    fi
  else
    values::unset --config upmeter.auth.status.password
  fi
}

hook::run $@
