#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 10
EOF
}

function __main__() {
  if ! values::has upmeter.auth.webui.externalAuthentication ; then
    if ! values::has --config upmeter.auth ; then
      values::set --config upmeter.auth {}
    fi
    if ! values::has --config upmeter.auth.webui ; then
      values::set --config upmeter.auth.webui {}
    fi
    if ! values::has upmeter.auth.webui.password ; then
      values::set --config upmeter.auth.webui.password $(tools::generate_password)
    fi
  else
    values::unset --config upmeter.auth.webui.password
  fi

  if ! values::has upmeter.auth.status.externalAuthentication ; then
    if ! values::has --config upmeter.auth ; then
      values::set --config upmeter.auth {}
    fi
    if ! values::has --config upmeter.auth.status ; then
      values::set --config upmeter.auth.status {}
    fi
    if ! values::has upmeter.auth.status.password ; then
      values::set --config upmeter.auth.status.password $(tools::generate_password)
    fi
  else
    values::unset --config upmeter.auth.status.password
  fi
}

hook::run $@
