#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 1
    kubernetes:
    - name: helm_releases
      group: main
      keepFullObjectsInMemory: false
      waitForSynchronization: false
      apiVersion: v1
      kind: Secret
      namespace:
        nameSelector:
          matchNames: ["d8-smoke-mini"]
      labelSelector:
        matchLabels:
          name: smoke-mini
          owner: helm
      jqFilter: |
        {"secret_name": .metadata.name}
    - name: namespace
      group: main
      keepFullObjectsInMemory: false
      waitForSynchronization: false
      apiVersion: v1
      kind: Namespace
      nameSelector:
        matchNames:
        - d8-smoke-mini
      jqFilter: .metadata.name
    - name: d8cm
      keepFullObjectsInMemory: false
      waitForSynchronization: false
      executeHookOnSynchronization: false
      group: main
      apiVersion: v1
      kind: ConfigMap
      namespace:
        nameSelector:
          matchNames: [d8-system]
      nameSelector:
        matchNames: [deckhouse]
      jqFilter: |
        {
          "smokeMini": (.data.smokeMini // ""),
          "smokeMiniEnabled": (.data.smokeMiniEnabled // true)
        }

EOF
}

function __main__() {
  for secret_name in $(context::jq '.snapshots.helm_releases[].secret_name' -r); do
    kubernetes::delete_if_exists::non_blocking "d8-system" "secret/$secret_name"
  done

  if context::jq -er '.snapshots.d8cm[0].filterResult.smokeMini != ""' >/dev/null; then
    values::set --config upmeter.smokeMini "$(context::get snapshots.d8cm.0.filterResult.smokeMini | yq read -j -)"
  fi

  if context::jq -er '.snapshots.d8cm[0].filterResult.smokeMiniEnabled == false' >/dev/null; then
    values::set --config upmeter.smokeMiniDisabled "true"
  fi

  fltr='. | del(.data.smokeMiniEnabled) | del(.data.smokeMini)'
  kubernetes::patch_jq d8-system configmap/deckhouse "$fltr"

  if context::has snapshots.namespace.0 >/dev/null; then
    kubernetes::delete_if_exists::non_blocking "d8-smoke-mini" "ingress/smoke-mini"
    kubernetes::delete_if_exists::non_blocking "" "clusterrole/d8:smoke-mini:smoke-mini"
    kubernetes::delete_if_exists::non_blocking "" "clusterrolebinding/d8:smoke-mini:smoke-mini"
    kubectl delete namespace d8-smoke-mini --wait=false || true
  fi
}

hook::run "$@"
