#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 1
    kubernetes:
    # main
    - name: pvc
      group: main
      keepFullObjectsInMemory: true
      apiVersion: v1
      kind: PersistentVolumeClaim
      namespace:
        nameSelector:
          matchNames: ["d8-upmeter"]
      labelSelector:
        matchLabels:
          app: upmeter
      jqFilter: .spec.storageClassName
    - name: default_sc
      group: main
      keepFullObjectsInMemory: true
      apiVersion: storage.k8s.io/v1
      kind: Storageclass
      jqFilter: |
        (.metadata.annotations."storageclass.beta.kubernetes.io/is-default-class" == "true") or
        (.metadata.annotations."storageclass.kubernetes.io/is-default-class" == "true")
    # pvc_modified
    - name: pvc_modified
      keepFullObjectsInMemory: true
      executeHookOnEvent: ["Modified"]
      executeHookOnSynchronization: false
      group: pvc_modified
      apiVersion: v1
      kind: PersistentVolumeClaim
      namespace:
        nameSelector:
          matchNames: ["d8-upmeter"]
      labelSelector:
        matchLabels:
          app: upmeter
    - name: pods
      group: pvc_modified
      keepFullObjectsInMemory: true
      apiVersion: v1
      kind: Pod
      namespace:
        nameSelector:
          matchNames: ["d8-upmeter"]
      labelSelector:
        matchLabels:
          app: upmeter
      jqFilter: .metadata.name
      executeHookOnEvent: []
      executeHookOnSynchronization: false
    # pvc_deleted
    - name: pvc_deleted
      keepFullObjectsInMemory: true
      executeHookOnEvent: ["Deleted"]
      executeHookOnSynchronization: false
      group: pvc_deleted
      apiVersion: v1
      kind: PersistentVolumeClaim
      namespace:
        nameSelector:
          matchNames: ["d8-upmeter"]
      labelSelector:
        matchLabels:
          app: upmeter
    - name: pods
      group: pvc_deleted
      keepFullObjectsInMemory: true
      apiVersion: v1
      kind: Pod
      namespace:
        nameSelector:
          matchNames: ["d8-upmeter"]
      labelSelector:
        matchLabels:
          app: upmeter
      jqFilter: .metadata.name
      executeHookOnEvent: []
      executeHookOnSynchronization: false
EOF
}


function __on_group::pvc_modified() {
  if context::jq -er '.snapshots.pvc_modified[0].object.metadata | has("deletionTimestamp")' >/dev/null; then
    if context::has snapshots.pods.0; then
      pod_name="$(context::get snapshots.pods.0.object.metadata.name)"
      kubernetes::delete_if_exists::non_blocking "d8-upmeter" "pod/$pod_name"
      echo "!!! NOTICE: deleting pod/$pod_name because persistentvolumeclaim/data-upmeter-0 is Terminating !!!"
    fi
  fi
}

function __on_group::pvc_deleted() {
  if context::has snapshots.pods.0; then
    pod_name="$(context::get snapshots.pods.0.object.metadata.name)"
    kubernetes::delete_if_exists::non_blocking "d8-upmeter" "pod/$pod_name"
    echo "!!! NOTICE: deleting pod/$pod_name because persistentvolumeclaim/data-upmeter-0 was deleted !!!"
  fi
}

function __main__() {
  effective_storage_class="false"
  current_storage_class="false"

  if context::jq -er '.snapshots.default_sc[] | select(.filterResult == true)' >/dev/null; then
    effective_storage_class="$(context::jq -r '[.snapshots.default_sc[] | select(.filterResult == true)] | first | .object.metadata.name')"
  fi

  if values::has --config global.storageClass; then
    effective_storage_class="$(values::get --config global.storageClass)"
  fi

  if values::has --config upmeter.storageClass; then
    effective_storage_class="$(values::get --config upmeter.storageClass)"
  fi

  if context::has snapshots.pvc.0 ; then
    effective_storage_class="$(context::get snapshots.pvc.0.object.spec.storageClassName)"
    current_storage_class="$effective_storage_class"
  else
    current_storage_class="emptydir"
  fi

  if values::has --config upmeter.storageClass; then
    effective_storage_class="$(values::get --config upmeter.storageClass)"
  fi

  values::set upmeter.internal.effectiveStorageClass "$effective_storage_class"

  if [ "$current_storage_class" != "$effective_storage_class" ]; then
    if context::has snapshots.pvc.0 ; then
      kubernetes::delete_if_exists::non_blocking "d8-upmeter" "persistentvolumeclaim/data-upmeter-0"
      echo "!!! NOTICE: storage class changed, deleting persistentvolumeclaim/data-upmeter-0 !!!"
    fi
    kubernetes::delete_if_exists::non_blocking "d8-upmeter" "statefulset/upmeter"
    echo "!!! NOTICE: storage class changed, deleting statefulset/upmeter !!!"
  fi

  jq -nr --arg storage_class "$effective_storage_class" '
    {
      "name": "d8_emptydir_usage",
      "set": (if $storage_class == "false" then 1 else 0 end),
      "labels": {
        "app": "upmeter"
      }
    }
  ' >> $METRICS_PATH
}

hook::run $@
