{
 "title": "Upmeter",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Replicas Upmeter desired",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_controller_replicas{controller_name=\"upmeter\"}"
    }
   ]
  },
  {
   "title": "Replicas Upmeter alive",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_controller_replicas_ready{controller_name=\"upmeter\"}"
    }
   ]
  },
  {
   "title": "SLA by groups",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 14, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (group) (\n    sum_over_time(statustime{probe=\"__total__\", status=~\"up|unknown\"}[$__range])\n  )\n  /\n  sum by (group) (\n    sum_over_time(statustime{probe=\"__total__\", status=~\"up|unknown|down\"}[$__range])\n  )\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Current cumponents statuses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Namespace",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(statustime{group=\"control-plane\", probe=\"namespace\", status=\"up\"}[5m])[5m], 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deckhouse",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(statustime{group=\"deckhouse\", probe=\"cluster-configuration\", status=\"up\"}[5m])[5m], 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dex",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(statustime{group=\"extensions\", probe=\"dex\", status=\"up\"}[5m])[5m], 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Key metrics present",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(statustime{group=\"monitoring-and-autoscaling\", probe=\"key-metrics-present\", status=\"up\"}[5m])[5m], 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(statustime{group=\"nginx\", probe=\"nginx\", status=\"up\"}[5m])[5m], 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Synthetic probe: Access",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(statustime{group=\"synthetic\", probe=\"access\", status=\"up\"}[5m])[5m], 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Basic functionality status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(statustime{group=\"control-plane\", probe=\"basic-functionality\", status=\"up\"}[5m])[5m], 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafana-v10",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(statustime{group=\"extensions\", probe=\"grafana-v10\", status=\"up\"}[5m])[5m], 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metrics sources",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(statustime{group=\"monitoring-and-autoscaling\", probe=\"metrics-sources\", status=\"up\"}[5m])[5m], 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Synthetic probe: Neighbor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(statustime{group=\"synthetic\", probe=\"neighbor\", status=\"up\"}[5m])[5m], 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cert manager",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(statustime{group=\"control-plane\", probe=\"cert-manager\", status=\"up\"}[5m])[5m], 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus-longterm",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(statustime{group=\"extensions\", probe=\"prometheus-longterm\", status=\"up\"}[5m])[5m], 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(statustime{group=\"monitoring-and-autoscaling\", probe=\"prometheus\", status=\"up\"}[5m])[5m], 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Synthetic probe: DNS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(statustime{group=\"synthetic\", probe=\"dns\", status=\"up\"}[5m])[5m], 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Api server",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(statustime{group=\"control-plane\", probe=\"apiserver\", status=\"up\"}[5m])[5m], 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes dashboard",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(statustime{group=\"extensions\", probe=\"dashboard\", status=\"up\"}[5m])[5m], 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Horizontal pod autoscaler",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(statustime{group=\"monitoring-and-autoscaling\", probe=\"horizontal-pod-autoscaler\", status=\"up\"}[5m])[5m], 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Synthetic probe: Neighbor via Service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(statustime{group=\"synthetic\", probe=\"neighbor-via-service\", status=\"up\"}[5m])[5m], 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(statustime{group=\"control-plane\", probe=\"scheduler\", status=\"up\"}[5m])[5m], 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trickster",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(statustime{group=\"monitoring-and-autoscaling\", probe=\"trickster\", status=\"up\"}[5m])[5m], 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Controller manager",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(statustime{group=\"control-plane\", probe=\"controller-manager\", status=\"up\"}[5m])[5m], 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vertical pod autoscaler",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(statustime{group=\"monitoring-and-autoscaling\", probe=\"vertical-pod-autoscaler\", status=\"up\"}[5m])[5m], 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus-metrics-adapter",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(statustime{group=\"monitoring-and-autoscaling\", probe=\"prometheus-metrics-adapter\", status=\"up\"}[5m])[5m], 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster main probes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster main probes overall",
     "type": "bargauge",
     "description": "Control Plane is available. Self-healing is working.\n\nGroup result is a combination of probe results with the priority of the worst results.\n\nUp: all probes are up. \nDown: at least one probe is down. \nUnknown: uncertain result, see probe results for clues. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"control-plane\", probe=\"__total__\", probe_ref=\"control-plane/__total__\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Namespace\t",
     "type": "bargauge",
     "description": "Every 1 minute a Namespace is created and deleted\n\nUp: namespace successfully created and deleted. \nDown: created Namespace is not deleted after 1 minute. \nUnknown: error during create or delete  operations, kube-apiserver is not available or operations are slow. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"control-plane\", probe=\"namespace\", probe_ref=\"control-plane/namespace\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Basic Functionality\t",
     "type": "bargauge",
     "description": "Every 5s a ConfigMap is created and deleted.\n\nUp: configMap successfully created and deleted. \nDown: error occurred during the creation or deletion of the ConfigMap. \nUnknown: kube-apiserver is not available or probe execution is skipped because previous probe was not yet finished. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"control-plane\", probe=\"basic-functionality\", probe_ref=\"control-plane/basic-functionality\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cert Manager\t",
     "type": "bargauge",
     "description": "Every 1 minute a certificate is created and deleted to check the cert-manager handling of it\n\nUp: certificate secret was created, and after the certificate was deleted, the secret disappeared. \nDown: certificate secret was not created in 5 seconds, or was no deleted in 20 seconds. \nUnknown: error occurred during creation or deletion, or kube-apiserver is not available. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"control-plane\", probe=\"cert-manager\", probe_ref=\"control-plane/cert-manager\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Api Server\t",
     "type": "bargauge",
     "description": "The probe requests /version endpoint from kube-apiserver\n\nUp: /version returns 200 OK.\nDown: /version returns other codes or there is no connection to kube-apiserver.\nUnknown: connection to kube-apiserver is slow.\nNodata: agents were stopped",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"control-plane\", probe=\"apiserver\", probe_ref=\"control-plane/apiserver\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Scheduler\t",
     "type": "bargauge",
     "description": "Every 1 minute a Pod is created, scheduled to a matching node and deleted\n\nUp: pod successfully created and scheduled to a node. \nDown: created Pod is not scheduled within 20 seconds. \nUnknown: error during create or delete operations, kube-apiserver is not available or probe execution is skipped because previous probe was not yet finished. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"control-plane\", probe=\"scheduler\", probe_ref=\"control-plane/scheduler\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Controller Manager\t",
     "type": "bargauge",
     "description": "Every 1 minute a Deployment is created and deleted\n\nUp: deployment successfully created, and its Pod became Pending. Afterwards, the deployment successfully deleted. \nDown: created Pod has not become Pending  after 10 seconds. \nUnknown: error occurred during creation or deletion, or kube-apiserver is not available, or probe execution is skipped because previous probe was not yet finished. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"control-plane\", probe=\"controller-manager\", probe_ref=\"control-plane/controller-manager\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Deckhouse",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deckhouse overall",
     "type": "bargauge",
     "description": "Checks the availability of deckhouse and working hook.\n\nGroup result is a combination of probe results with the priority of the worst results.\n\nUp: all probes are up. \nDown: at least one probe is down. \nUnknown: uncertain result, see probe results for clues. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"deckhouse\", probe=\"__total__\", probe_ref=\"deckhouse/__total__\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cluster Configuration",
     "type": "bargauge",
     "description": "Cluster configurations is contolled by Deckhouse\n\nUp: Deckhouse pod is Ready state in 20 minutes, and test hook reacts on custom resourse changes. \nDown: Deckhouse pod is not in Ready state for more than 20 minutes, or hook does not react to custom resource. \nUnknown: error occurred during pod fetching, or pod is terminating, or kube-apiserver is not available, or probe execution is skipped because previous probe was not yet finished. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"deckhouse\", probe=\"cluster-configuration\", probe_ref=\"deckhouse/cluster-configuration\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Extensions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Extensions overall\t",
     "type": "bargauge",
     "description": "Checks the availability of various extensions apps.\n\nGroup result is a combination of probe results with the priority of the worst results.\n\nUp: all probes are up\nDown: at least one probe is down\nUnknown: uncertain result, see probe results for clues\nNodata: agents were stopped",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"extensions\", probe=\"__total__\", probe_ref=\"extensions/__total__\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Dex\t",
     "type": "bargauge",
     "description": "General-purpose web UI for the cluster\n\nUp: at least one Pod of Dex is in Ready state. \nDown: there are no pods of Dex in Ready state. \nUnknown: error occurred during pods fetching, or kube-apiserver is not available, or probe execution is skipped because previous probe was not yet finished. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"extensions\", probe=\"dex\", probe_ref=\"extensions/dex\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Grafana-v10\t",
     "type": "bargauge",
     "description": "General-purpose web UI for the cluster\n\nUp: at least one Pod of Dex is in Ready state. \nDown: there are no pods of Dex in Ready state. \nUnknown: error occurred during pods fetching, or kube-apiserver is not available, or probe execution is skipped because previous probe was not yet finished. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"extensions\", probe=\"grafana-v10\", probe_ref=\"extensions/grafana-v10\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Prometheus-longterm\t",
     "type": "bargauge",
     "description": "General-purpose web UI for the cluster\n\nUp: at least one Pod of Dex is in Ready state. \nDown: there are no pods of Dex in Ready state. \nUnknown: error occurred during pods fetching, or kube-apiserver is not available, or probe execution is skipped because previous probe was not yet finished. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"extensions\", probe=\"prometheus-longterm\", probe_ref=\"extensions/prometheus-longterm\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Kubernetes Dashboard\t",
     "type": "bargauge",
     "description": "General-purpose web UI for the cluster\n\nUp: at least one Pod of Dashboard is in Ready state. \nDown: there are no pods of Dashboard in Ready state. \nUnknown: error occurred during pods fetching, or kube-apiserver is not available, or probe execution is skipped because previous probe was not yet finished. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"extensions\", probe=\"dashboard\", probe_ref=\"extensions/dashboard\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Monitoring and Autoscaling\t",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Monitoring and Autoscaling overall",
     "type": "bargauge",
     "description": "Checks the availability of monitoring and autoscaling applications in the cluster.\n\nGroup result is a combination of probe results with the priority of the worst results.\n\nUp: all probes are up. \nDown: at least one probe is down. \nUnknown: uncertain result, see probe results for clues. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"monitoring-and-autoscaling\", probe=\"__total__\", probe_ref=\"monitoring-and-autoscaling/__total__\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Key Metrics Present",
     "type": "bargauge",
     "description": "Key cluster metrics are metrics from the Kubernetes, nodes and containers.\n\nUp: metrics from all key components are present in Prometheus and are non-zero. \nDown: at least one of metrics is absent or has zero value. \nUnknown: (unexpected). \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"monitoring-and-autoscaling\", probe=\"key-metrics-present\", probe_ref=\"monitoring-and-autoscaling/key-metrics-present\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Metrics Sources",
     "type": "bargauge",
     "description": "Key metric sources are from nodes and Kubernetes.\n\nUp: all pods of node-exporter, and at least one Pod of kube-state-metrics is in Ready state. \nDown: at least one Pod of node-exporter, or all pods of kube-state-metrics are not in Ready state. \nUnknown: kube-apiserver is not available. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"monitoring-and-autoscaling\", probe=\"metrics-sources\", probe_ref=\"monitoring-and-autoscaling/metrics-sources\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Prometheus",
     "type": "bargauge",
     "description": "Prometheus is a monitoring system.\n\nUp: at least one Pod is in Ready state, and the Prometheus API responds correctly. \nDown: either no ready Pods present, or Prometheus responds with invalid data. \nUnknown: kube-apiserver is not available. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"monitoring-and-autoscaling\", probe=\"prometheus\", probe_ref=\"monitoring-and-autoscaling/prometheus\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Horizontal Pod Autoscaler",
     "type": "bargauge",
     "description": "The Horizontal Pod Autoscaler automatically changes the number of replicas\n\nUp: both probes of Prometheus Metrics Adapter and Controller Manager are successful. \nDown: at least one of probes of Prometheus.  Metrics Adapter or Controller Manager failed. \nUnknown: at least one of probes of Prometheus Metrics Adapter or Controller Manager has unknown result but none of them failed. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"monitoring-and-autoscaling\", probe=\"horizontal-pod-autoscaler\", probe_ref=\"monitoring-and-autoscaling/horizontal-pod-autoscaler\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Trickster",
     "type": "bargauge",
     "description": "Trickster is an HTTP reverse proxy/cache for Prometheus\n\nUp: at least one Pod is in Ready state, and the Trickster API responds correctly. \nDown: either no ready Pods present, or Trickster responds with invalid data. \nUnknown: kube-apiserver is not available. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"monitoring-and-autoscaling\", probe=\"trickster\", probe_ref=\"monitoring-and-autoscaling/trickster\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Vertical Pod Autoscaler",
     "type": "bargauge",
     "description": "The Vertical Pod Autoscaler automatically changes resources acquired by pods (CPU, memory)\n\nUp: at least one Pod of a VPA component is in Ready state. \nDown: a Pod of at least one VPA component is not in Ready state. \nUnknown: kube-apiserver is not available. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"monitoring-and-autoscaling\", probe=\"vertical-pod-autoscaler\", probe_ref=\"monitoring-and-autoscaling/vertical-pod-autoscaler\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Prometheus-metrics-adapter",
     "type": "bargauge",
     "description": "Prometheus Metrics Adapter provides metrics for the cluster (nodes, containers, etc.)\n\nUp: at least one Pod is in Ready state and the custom metrics CR contains non-zero value. \nDown: either no ready Pods present, or adapter metrics response is invalid. \nUnknown: kube-apiserver is not available. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"monitoring-and-autoscaling\", probe=\"prometheus-metrics-adapter\", probe_ref=\"monitoring-and-autoscaling/prometheus-metrics-adapter\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nginx overall",
     "type": "bargauge",
     "description": "Checks the availability of Ingress Nginx Controller.\n\nGroup result is a combination of probe results with the priority of the worst results.\n\nUp: all probes are up. \nDown: at least one probe is down. \nUnknown: uncertain result, see probe results for clues. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"nginx\", probe=\"__total__\", probe_ref=\"nginx/__total__\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "nginx",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"nginx\", probe=\"nginx\", probe_ref=\"nginx/nginx\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Synthetic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Access",
     "type": "bargauge",
     "description": "Every 5 seconds resolve sample application IPs and request / endpoint until first success\n\nUp: resolve is successful and all IPs are responded with 200 OK. \nDown: some IP responded with other code. \nUnknown: error during resolve or application is responded slow. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"synthetic\", probe=\"access\", probe_ref=\"synthetic/access\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Neighbor",
     "type": "bargauge",
     "description": "Every 5 seconds resolve sample application IPs and request /neighbor endpoint until first success\n\nUp: resolve is successful and all IPs are responded with 200 OK. \nDown: some IP responded with other code. \nUnknown: error during resolve or application is responded slow. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"synthetic\", probe=\"neighbor\", probe_ref=\"synthetic/neighbor\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DNS",
     "type": "bargauge",
     "description": "Every 5 seconds resolve sample application IPs and request /dns endpoint until first success\n\nUp: resolve is successful and all IPs are responded with 200 OK. \nDown: some IP responded with other code. \nUnknown: error during resolve or application is responded slow. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"synthetic\", probe=\"dns\", probe_ref=\"synthetic/dns\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Neighbor via Service",
     "type": "bargauge",
     "description": "Every 5 seconds resolve sample application IPs and request /neighbor-via-service endpoint until first success\n\nUp: resolve is successful and all IPs are responded with 200 OK. \nDown: some IP responded with other code. \nUnknown: error during resolve or application is responded slow. \nNodata: agents were stopped. ",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (\n  sum_over_time(statustime{group=\"synthetic\", probe=\"neighbor-via-service\", probe_ref=\"synthetic/neighbor-via-service\"}[$__range])\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}