#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    afterHelm: 10
    afterDeleteHelm: 10
EOF
}

function __on_after_helm() {
  cluster_version=$(values::get global.discovery.kubernetesVersion)

  if [[ "$(semver compare $cluster_version 1.11.0)" -ne "-1" ]] ; then
    # Необходимо проставить priorityClassName антиопе
    fltr='. | .spec.template.spec.priorityClassName = "cluster-medium"'
    kubernetes::patch_jq d8-system deployment/deckhouse "$fltr"
  fi
}

function __on_after_delete_helm() {
  cluster_version=$(values::get global.discovery.kubernetesVersion)

  if [[ "$(semver compare $cluster_version 1.11.0)" -ne "-1" ]] ; then
    fltr='. | del(.spec.template.spec.priorityClassName)'
    kubernetes::patch_jq d8-system deployment/deckhouse "$fltr"
  fi
}

hook::run $@
