#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p afterHelm=10
}

function __main__() {
  cluster_version=$(values::get global.discovery.clusterVersion)
  if [ "$(semver compare $cluster_version 1.11.0)" -ne "-1" ] ; then
    cluster_type=$(values::get --required global.discovery.clusterType)
    # Подам kube-proxy необходимо задать максимальный priorityClass, так как без подов kube-proxy
    # работа всего кластера может быть нарушена

    # В AWS и GCE kube-proxy запущены, как static поды
    [[ "$cluster_type" == "AWS" || "$cluster_type" == "GCE" ]] && return 0

    fltr='.'

    # Необходимо проставить наивысший priorityClassName kube-proxy
    fltr=$fltr' | .spec.template.spec.priorityClassName = "system-cluster-critical"'

    # Применяем
    kubectl::jq_patch kube-system ds/kube-proxy "$fltr"
  fi
}

hook::run $@

