#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  echo '
{
  "beforeHelm": 30,
  "onKubernetesEvent": [
    {
      "kind": "deployment",
      "event": [
        "add",
        "update"
      ],
      "jqFilter": ".spec.template.spec.priorityClassName",
      "selector": {
        "matchLabels": {
          "app": "helm",
          "name": "tiller"
        }
      },
      "namespaceSelector": {
        "matchNames": [
          "kube-system"
        ]
      }
    }
  ]
}'
}

function __main__() {
  cluster_version=$(values::get global.discovery.clusterVersion)
  if [ "$(semver compare $cluster_version 1.11.0)" -ne "-1" ] ; then
    if kubectl -n kube-system get deploy tiller-deploy > /dev/null 2> /dev/null; then
      fltr='.'
      fltr=$fltr' | .spec.template.spec.priorityClassName = "deployment-machinery"'
      kubectl::jq_patch kube-system deploy/tiller-deploy "$fltr"
    fi
  fi
}

hook::run $@

