#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    afterHelm: 10
    afterDeleteHelm: 10
EOF
}

function __on_after_helm() {
  cluster_version=$(values::get global.discovery.kubernetesVersion)
  if [[ "$(semver compare $cluster_version 1.11.0)" -ne "-1" ]] ; then
    if kubectl -n kube-system get deploy kube-dns > /dev/null 2> /dev/null; then
      cluster_type=$(values::get --required global.discovery.clusterType)
      # Подам kube-dns необходимо задать максимальный priorityClass, так как без подов kube-dns
      # работа всего кластера может быть нарушена

      # В ACS (acs-engine) кластерах kube-dns создается из манифестов на kube-master
      [[ "$cluster_type" == "ACS" ]] && return 0

      # Необходимо проставить наивысший priorityClassName kube-dns
      fltr='. | .spec.template.spec.priorityClassName = "system-cluster-critical"'
      # Применяем
      kubernetes::patch_jq kube-system deployment/kube-dns "$fltr"
    fi
  fi
}

function __on_after_delete_helm() {
  cluster_version=$(values::get global.discovery.kubernetesVersion)
  if [[ "$(semver compare $cluster_version 1.11.0)" -ne "-1" ]] ; then
    if kubectl -n kube-system get deploy kube-dns > /dev/null 2> /dev/null; then
      cluster_type=$(values::get --required global.discovery.clusterType)
      # Подам kube-dns необходимо задать максимальный priorityClass, так как без подов kube-dns
      # работа всего кластера может быть нарушена

      # В ACS (acs-engine) кластерах kube-dns создается из манифестов на kube-master
      [[ "$cluster_type" == "ACS" ]] && return 0

      fltr='. | del(.spec.template.spec.priorityClassName)'
      # Применяем
      kubernetes::patch_jq kube-system deployment/kube-dns "$fltr"
    fi
  fi
}

hook::run $@
