#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    afterHelm: 10
    afterDeleteHelm: 10
EOF
}

function __on_after_helm() {
  cluster_version=$(values::get global.discovery.kubernetesVersion)
  if [[ "$(semver compare $cluster_version 1.11.0)" -ne "-1" ]] ; then
    if kubectl -n kube-system get ds kube-proxy >/dev/null 2>&1; then
      # Подам kube-proxy необходимо задать максимальный priorityClass, так как без подов kube-proxy
      # работа всего кластера может быть нарушена
      # Необходимо проставить наивысший priorityClassName kube-proxy
      fltr='. | .spec.template.spec.priorityClassName = "system-cluster-critical"'
      # Применяем
      kubernetes::patch_jq kube-system daemonset/kube-proxy "$fltr"
    fi
  fi
}

function __on_after_delete_helm() {
  cluster_version=$(values::get global.discovery.kubernetesVersion)
  if [[ "$(semver compare $cluster_version 1.11.0)" -ne "-1" ]] ; then
    if kubectl -n kube-system get ds kube-proxy >/dev/null 2>&1; then
      # Подам kube-proxy необходимо задать максимальный priorityClass, так как без подов kube-proxy
      # работа всего кластера может быть нарушена
      fltr='. | del(.spec.template.spec.priorityClassName)'
      # Применяем
      kubernetes::patch_jq kube-system daemonset/kube-proxy "$fltr"
    fi
  fi
}

hook::run $@
