#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    afterHelm: 10
    afterDeleteHelm: 10
EOF
}

function __on_after_helm() {
  if kubectl -n kube-system get ds kube-flannel-ds >/dev/null 2>&1; then
    cluster_version=$(values::get global.discovery.kubernetesVersion)
    if [[ "$(semver compare $cluster_version 1.11.0)" -ne "-1" ]] ; then
      cluster_type=$(values::get --required global.discovery.clusterType)
      # Подам kube-flannel необходимо задать максимальный priorityClass, так как без подов kube-flannel
      # работа всего кластера может быть нарушена

      # flannel есть только в Manual кластерах
      [[ "$cluster_type" != "Manual" ]] && return 0

      # Необходимо проставить наивысший priorityClassName kube-flannel
      fltr='. | .spec.template.spec.priorityClassName = "system-cluster-critical"'
      # Применяем
      kubernetes::patch_jq kube-system daemonset/kube-flannel-ds "$fltr"
    fi
  fi
}

function __on_after_delete_helm() {
  if kubectl -n kube-system get ds kube-flannel-ds >/dev/null 2>&1; then
    cluster_version=$(values::get global.discovery.kubernetesVersion)
    if [[ "$(semver compare $cluster_version 1.11.0)" -ne "-1" ]] ; then
      cluster_type=$(values::get --required global.discovery.clusterType)
      # Подам kube-flannel необходимо задать максимальный priorityClass, так как без подов kube-flannel
      # работа всего кластера может быть нарушена

      # flannel есть только в Manual кластерах
      [[ "$cluster_type" != "Manual" ]] && return 0

      fltr='. | del(.spec.template.spec.priorityClassName)'
      # Применяем
      kubernetes::patch_jq kube-system daemonset/kube-flannel-ds "$fltr"
    fi
  fi
}

hook::run $@
