#!/bin/bash
#
# Copyright 2023 Flant JSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE

source /deckhouse/shell_lib.sh

function __main__() {
  # Like control-plane
  if values::has global.clusterConfiguration ; then
    echo "true" > "$MODULE_ENABLED_RESULT"
  else
    echo "false" > "$MODULE_ENABLED_RESULT"
  fi

  # # Only for "Static"
  # if ! values::has global.clusterConfiguration.clusterType ; then
  #   echo "Unknown cluster type"
  #   echo "false" > "$MODULE_ENABLED_RESULT"
  #   return
  # fi
  # cluster_type=$(values::get global.clusterConfiguration.clusterType)
  # if [ "$cluster_type" != "Static" ]; then
  #   echo "false" > "$MODULE_ENABLED_RESULT"
  #   echo "The module is supported only for cluster type Static."
  #   return
  # fi
}

enabled::run "$@"
