{
 "title": "SeaweedFS",
 "time": { "from": "now-1d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Master", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Raft leader",
   "type": "stat",
   "description": "Whether master is leader or not",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (SeaweedFS_master_is_leader{job=\"system-registry\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Master leader changes",
   "type": "timeseries",
   "description": "Count times leader changed",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (SeaweedFS_master_leader_changes{job=\"system-registry\", type=~\".+\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Received heartbeats",
   "type": "timeseries",
   "description": "Heartbeats received from components",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (type) (increase(SeaweedFS_master_received_heartbeats{job=\"system-registry\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Replica Placement Mismatch",
   "type": "timeseries",
   "description": "Count replica placement mismatch",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (SeaweedFS_master_replica_placement_mismatch{job=\"system-registry\"} > 0) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Raft leader count",
   "type": "timeseries",
   "description": "Total count of raft leaders",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (SeaweedFS_master_is_leader{job=\"system-registry\"})",
     "legendFormat": "Leaders"
    }
   ]
  },
  {
   "title": "Admin lock",
   "type": "stat",
   "description": "Whether cluster locked or not",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SeaweedFS_master_admin_lock{job=\"system-registry\"}",
     "legendFormat": "Client IP: {{client}}"
    }
   ]
  },
  { "title": "Filer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Filer Request Duration 90th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(SeaweedFS_filer_request_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(SeaweedFS_filer_request_seconds_bucket[$__rate_interval])) by (le, type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Filer Request Duration 95th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(SeaweedFS_filer_request_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(SeaweedFS_filer_request_seconds_bucket[$__rate_interval])) by (le, type))",
     "legendFormat": "{{type}}"
    },
    {}
   ]
  },
  {
   "title": "Filer Request Duration 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_filer_request_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_filer_request_seconds_bucket[$__rate_interval])) by (le, type))",
     "legendFormat": "{{type}}"
    },
    {}
   ]
  },
  {
   "title": "Filer QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (rate(SeaweedFS_filer_request_total[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "S3 Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "S3 Request Duration 90th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(SeaweedFS_s3_request_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(SeaweedFS_s3_request_seconds_bucket[$__rate_interval])) by (le, type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "S3 Request Duration 95th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(SeaweedFS_s3_request_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(SeaweedFS_s3_request_seconds_bucket[$__rate_interval])) by (le, type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "S3 Request Duration 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_s3_request_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_s3_request_seconds_bucket[$__rate_interval])) by (le, type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "S3 Request. Duration 99th percentile per instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_s3_request_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_s3_request_seconds_bucket[$__rate_interval])) by (le, type, pod))",
     "legendFormat": "{{type}}-{{pod}}"
    }
   ]
  },
  {
   "title": "S3 Request Duration 99th percentile per bucket",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_s3_request_seconds_bucket[$__rate_interval])) by (le, type, bucket))",
     "legendFormat": "{{type}}-{{bucket}}"
    }
   ]
  },
  {
   "title": "S3 API QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(SeaweedFS_s3_request_total[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "S3 API Monthly Cost if on AWS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "currencyUSD", "label": "Cost in US$" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (SeaweedFS_s3_request_total{type=~'PUT|COPY|POST|LIST'})*0.000005",
     "legendFormat": "{{type}} requests"
    },
    {
     "expr": "sum (SeaweedFS_s3_request_total{type=~'PUT|COPY|POST|LIST'})*0.000005",
     "legendFormat": "All PUT, COPY, POST, LIST"
    },
    {
     "expr": "sum (SeaweedFS_s3_request_total{type!~'PUT|COPY|POST|LIST'})*0.0000004",
     "legendFormat": "GET and all other"
    },
    {
     "expr": "sum by (type) (SeaweedFS_s3_request_total{type!~'PUT|COPY|POST|LIST'})*0.0000004",
     "legendFormat": "{{type}} requests"
    }
   ]
  },
  { "title": "Volume Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Volume Server Request Duration 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_volumeServer_request_seconds_bucket[$__rate_interval])) by (le, exported_instance))",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_volumeServer_request_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Volume Server QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(SeaweedFS_volumeServer_request_total[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Volume Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(SeaweedFS_volumeServer_volumes) by (collection, type)",
     "legendFormat": "{{collection}} {{type}}"
    },
    {
     "expr": "sum(SeaweedFS_volumeServer_volumes)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Used Disk Space by Collection and Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(SeaweedFS_volumeServer_total_disk_size) by (collection, type)",
     "legendFormat": "{{collection}} {{type}}"
    },
    {
     "expr": "sum(SeaweedFS_volumeServer_total_disk_size)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Used Disk Space by Host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(SeaweedFS_volumeServer_total_disk_size) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  { "title": "Filer Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Filer Store Request Duration 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_filerStore_request_seconds_bucket[$__rate_interval])) by (le, type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Filer Store QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(SeaweedFS_filerStore_request_total [$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Filer Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Filer Go Memory Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"system-registry\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"system-registry\"}[$__rate_interval])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"system-registry\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"system-registry\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "Filer Go GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"system-registry\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Filer Go Routines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"system-registry\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  }
 ]
}