#!/bin/bash

source /deckhouse/shell_lib.sh

function __main__() {
  module::disable_if_cluster_is_not_bootstraped

  if kubectl get nodes -o json | jq -r '[.items[] | select(.status.nodeInfo.osImage | test("16.04"))] | any' -e > /dev/null; then
    echo "true" > "$MODULE_ENABLED_RESULT"
  else
    echo "false" > "$MODULE_ENABLED_RESULT"
  fi
}

hook::run "$@"
