apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    heritage: deckhouse
    module: user-authn
    rbac.deckhouse.io/aggregate-to-namespace-as: manager
    rbac.deckhouse.io/kind: capability
    rbac.deckhouse.io/capability: "namespace-capability.user-authn.edit"
    rbac.deckhouse.io/scope: namespace
  name: d8:namespace-capability:user-authn:edit
  annotations:
    en.meta.deckhouse.io/title: "Module user-authn: edit"
    ru.meta.deckhouse.io/title: "Модуль user-authn: редактирование"
    en.meta.deckhouse.io/description: "Manage user-authn resources in a namespace."
    ru.meta.deckhouse.io/description: "Управление ресурсами модуля user-authn в пространстве имён."
rules:
- apiGroups:
  - deckhouse.io
  resources:
  - dexauthenticators
  - dexclients
  verbs:
  - create
  - update
  - patch
  - delete
  - deletecollection
