# Based on https://github.com/argoproj/argo-cd/blob/v2.4.15/Dockerfile
# ARG BASE_ALPINE
FROM quay.io/argoproj/argocd:v2.5.2@sha256:9df610ec57cb8ec08001ffaeeedfe1c248e7906707a654801f8d7b4d07905693 as artifact
