# Based on https://github.com/argoproj/argo-cd/blob/v2.4.15/Dockerfile
# ARG BASE_ALPINE
FROM quay.io/argoproj/argocd:v2.4.16@sha256:53fb370a94ffca9cc5c3400abf9b0dc59544e23b1e411db4d52c05b001b3cc68 as artifact
