#!/bin/bash
# Copyright 2022 Flant JSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE

set -Eeo pipefail
packages_to_install=""
package_docker_ce="docker-ce"
package_file_docker_ce="${package_docker_ce}.x86_64.rpm"
rpm_name_docker_ce="$(rpm -qip ${package_file_docker_ce} 2>/dev/null | grep Name | awk '{print $3}')"
rpm_version_docker_ce="$(rpm -qip ${package_file_docker_ce} 2>/dev/null | grep Version | awk '{print $3}')"

if ! rpm --quiet -q "${rpm_name_docker_ce}-${rpm_version_docker_ce}"; then
  packages_to_install="${packages_to_install} ${package_file_docker_ce}"
else
  echo "RPM ${package_file_docker_ce} already installed."
fi

package_docker_ce_cli="docker-ce-cli"
package_file_docker_ce_cli="${package_docker_ce_cli}.x86_64.rpm"
rpm_name_docker_ce_cli="$(rpm -qip ${package_file_docker_ce_cli} 2>/dev/null | grep Name | awk '{print $3}')"
rpm_version_docker_ce_cli="$(rpm -qip ${package_file_docker_ce_cli} 2>/dev/null | grep Version | awk '{print $3}')"

if ! rpm --quiet -q "${rpm_name_docker_ce_cli}-${rpm_version_docker_ce_cli}"; then
  packages_to_install="${packages_to_install} ${package_file_docker_ce_cli}"
else
  echo "RPM ${package_file_docker_ce_cli} already installed."
fi

if [[ -n "${packages_to_install}" ]]; then
  rpm -U ${packages_to_install}
fi
yum versionlock add ${package_docker_ce} ${package_docker_ce_cli}
