{{- define "aws_cdd_envs" -}}
- name: AWS_ACCESS_KEY_ID
  valueFrom:
    secretKeyRef:
      name: cloud-controller-manager
      key: aws-access-key-id
- name: AWS_SECRET_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      name: cloud-controller-manager
      key: aws-secret-access-key
- name: AWS_REGION
  value: {{ .Values.cloudProviderAws.internal.region }}
{{- end -}}

{{- define "aws_cdd_pod_annotations" -}}
checksum/config: {{ include (print $.Template.BasePath "/cloud-controller-manager/secret.yaml") . | sha256sum }}
{{- end -}}

{{- $cddConfig := dict -}}
{{- $_ := set $cddConfig "fullname" "cloud-data-discoverer" -}}
{{- $_ := set $cddConfig "image" (include "helm_lib_module_image" (list . "cloudDataDiscoverer")) -}}
{{- $_ := set $cddConfig "additionalEnv" (include "aws_cdd_envs" . | fromYamlArray) -}}
{{- $_ := set $cddConfig "additionalPodAnnotations" (include "aws_cdd_pod_annotations" . | fromYaml) -}}
{{- $_ := set $cddConfig "vpaEnabled" true -}}

{{- include "helm_lib_cloud_data_discoverer_manifests" (list . $cddConfig) }}
