#!/bin/bash

# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    afterHelm: 10
EOF
}

function __main__() {
  for i in $(seq 1 120); do
    master_nodes=$(kubectl get node -l node-role.kubernetes.io/master="" -o json)

    all_initialized=$(echo "$master_nodes" | jq '[(.items[].spec.taints // []) | [(.[] | select(.key == "node.cloudprovider.kubernetes.io/uninitialized"))] | length == 0] | all')

    if [[ "x$all_initialized" == "xfalse" ]] ; then
      echo "Waiting for master nodes to become initialized by cloud provider"
    else
      return 0
    fi

    sleep 1
  done
  if [[ $i -ge 120 ]] ; then
    >&2 echo "Timeout waiting for master nodes"
    return 1
  fi
}

hook::run $@
