#!/bin/bash

source /antiopa/shell_lib.sh

function __config__ () {
  echo '
{
  "beforeHelm": 1
}'
}

function __main__() {
  ### Миграция 2019-09-05: https://github.com/deckhouse/deckhouse/merge_requests/
  # Этот хук можно удалить, после выката релиза с данным коммитом

  if values::has --config dynatrace.apiUrl ; then
    values::set --config dynatrace.apiURL $(values::get --config dynatrace.apiUrl)
    values::unset --config dynatrace.apiUrl
  fi

}

hook::run "$@"
