{{- define "vcd_cdd_pod_annotations" -}}
checksum/config: {{ printf "%s%s" (include (print $.Template.BasePath "/connection-info.yaml") . | toString) (include (print $.Template.BasePath "/secret.yaml") . | toString) | sha256sum }}
{{- end -}}

{{- define "vcd_cdd_envs" -}}
- name: VCD_INSECURE
  valueFrom:
    secretKeyRef:
      key: insecure
      name: vcd-connection-info
- name: VCD_HREF
  valueFrom:
    secretKeyRef:
      key: host
      name: vcd-connection-info
- name: VCD_VDC
  valueFrom:
    secretKeyRef:
      key: vdc
      name: vcd-connection-info
- name: VCD_ORG
  valueFrom:
    secretKeyRef:
      key: org
      name: vcd-connection-info
- name: VCD_NETWORK
  valueFrom:
    secretKeyRef:
      key: network
      name: vcd-connection-info
- name: VCD_USER
  valueFrom:
    secretKeyRef:
      key: username
      name: vcd-credentials
      optional: true
- name: VCD_PASSWORD
  valueFrom:
    secretKeyRef:
      key: password
      name: vcd-credentials
      optional: true
- name: VCD_TOKEN
  valueFrom:
    secretKeyRef:
      key: refreshToken
      name: vcd-credentials
      optional: true
{{- end -}}

{{- $cddImageName := "" -}}
{{- if eq .Values.cloudProviderVcd.internal.legacyMode true -}}
  {{- $cddImageName = "cloudDataDiscovererLegacy" -}}
{{- else -}}
  {{- $cddImageName = "cloudDataDiscoverer" -}}
{{- end -}}

{{- $cddConfig := dict -}}
{{- $_ := set $cddConfig "fullname" "cloud-data-discoverer" -}}
{{- $_ := set $cddConfig "image" (include "helm_lib_module_image" (list . $cddImageName)) -}}
{{- $_ := set $cddConfig "additionalEnv" (include "vcd_cdd_envs" . | fromYamlArray) -}}
{{- $_ := set $cddConfig "additionalPodAnnotations" (include "vcd_cdd_pod_annotations" . | fromYaml) -}}
{{- $_ := set $cddConfig "vpaEnabled" true -}}

{{- include "helm_lib_cloud_data_discoverer_manifests" (list . $cddConfig) }}