{
 "title": "Prometheus",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "pod",
    "query": "query_result(up{job=\"prometheus\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "at a glance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Percentage of uptime during the shown period.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{pod=~\"$pod\",job=\"prometheus\"}[$__range]) * 100)"
    }
   ]
  },
  {
   "title": "Currently Down",
   "type": "table",
   "description": "Servers which are DOWN RIGHT NOW! \nFIX THEM!!",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "up{pod=~\"$pod\",job=\"prometheus\"} < 1"
    }
   ]
  },
  {
   "title": "Total Series",
   "type": "stat",
   "description": "Total number of time series in prometheus",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{job=\"prometheus\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Memory Chunks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_chunks{job=\"prometheus\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "quick numbers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Missed Iterations",
     "type": "stat",
     "description": "The total number of rule group evaluations missed due to slow rule group evaluation.",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(prometheus_evaluator_iterations_missed_total{job=\"prometheus\",pod=~\"$pod\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Skipped Iterations",
     "type": "stat",
     "description": "The total number of rule group evaluations skipped due to throttled metric storage.",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(prometheus_evaluator_iterations_skipped_total{job=\"prometheus\",pod=~\"$pod\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Tardy Scrapes",
     "type": "stat",
     "description": "Total number of scrapes that hit the sample limit and were rejected.",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(prometheus_target_scrapes_exceeded_sample_limit_total{job=\"prometheus\",pod=~\"$pod\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Reload Failures",
     "type": "stat",
     "description": "Number of times the database failed to reload block data from disk.",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(prometheus_tsdb_reloads_failures_total{job=\"prometheus\",pod=~\"$pod\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Skipped Scrapes",
     "type": "stat",
     "description": "Sum of all skipped scrapes",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(prometheus_target_scrapes_exceeded_sample_limit_total{job=\"prometheus\",pod=~\"$pod\"}[$__range])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_duplicate_timestamp_total{job=\"prometheus\",pod=~\"$pod\"}[$__range])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_out_of_bounds_total{job=\"prometheus\",pod=~\"$pod\"}[$__range])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_out_of_order_total{job=\"prometheus\",pod=~\"$pod\"}[$__range])) "
      }
     ]
    }
   ]
  },
  {
   "title": "errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Failures and Errors",
     "type": "timeseries",
     "description": "All non-zero failures and errors",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(net_conntrack_dialer_conn_failed_total{pod=~\"$pod\"}[$__rate_interval])) > 0",
       "legendFormat": "Failed Connections"
      },
      {
       "expr": "sum(increase(prometheus_evaluator_iterations_missed_total{pod=~\"$pod\"}[$__rate_interval])) > 0",
       "legendFormat": "Missed Iterations"
      },
      {
       "expr": "sum(increase(prometheus_evaluator_iterations_skipped_total{pod=~\"$pod\"}[$__rate_interval])) > 0",
       "legendFormat": "Skipped Iterations"
      },
      {
       "expr": "sum(increase(prometheus_rule_evaluation_failures_total{pod=~\"$pod\"}[$__rate_interval])) > 0",
       "legendFormat": "Evaluation"
      },
      {
       "expr": "sum(increase(prometheus_sd_azure_refresh_failures_total{pod=~\"$pod\"}[$__rate_interval])) > 0",
       "legendFormat": "Azure Refresh"
      },
      {
       "expr": "sum(increase(prometheus_sd_consul_rpc_failures_total{pod=~\"$pod\"}[$__rate_interval])) > 0",
       "legendFormat": "Consul RPC"
      },
      {
       "expr": "sum(increase(prometheus_sd_dns_lookup_failures_total{pod=~\"$pod\"}[$__rate_interval])) > 0",
       "legendFormat": "DNS Lookup"
      },
      {
       "expr": "sum(increase(prometheus_sd_ec2_refresh_failures_total{pod=~\"$pod\"}[$__rate_interval])) > 0",
       "legendFormat": "EC2 Refresh"
      },
      {
       "expr": "sum(increase(prometheus_sd_gce_refresh_failures_total{pod=~\"$pod\"}[$__rate_interval])) > 0",
       "legendFormat": "GCE Refresh"
      },
      {
       "expr": "sum(increase(prometheus_sd_marathon_refresh_failures_total{pod=~\"$pod\"}[$__rate_interval])) > 0",
       "legendFormat": "Marathon Refresh"
      },
      {
       "expr": "sum(increase(prometheus_sd_openstack_refresh_failures_total{pod=~\"$pod\"}[$__rate_interval])) > 0",
       "legendFormat": "Openstack Refresh"
      },
      {
       "expr": "sum(increase(prometheus_sd_triton_refresh_failures_total{pod=~\"$pod\"}[$__rate_interval])) > 0",
       "legendFormat": "Triton Refresh"
      },
      {
       "expr": "sum(increase(prometheus_target_scrapes_exceeded_sample_limit_total{pod=~\"$pod\"}[$__rate_interval])) > 0",
       "legendFormat": "Sample Limit"
      },
      {
       "expr": "sum(increase(prometheus_target_scrapes_sample_duplicate_timestamp_total{pod=~\"$pod\"}[$__rate_interval])) > 0",
       "legendFormat": "Duplicate Timestamp"
      },
      {
       "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_bounds_total{pod=~\"$pod\"}[$__rate_interval])) > 0",
       "legendFormat": "Timestamp Out of Bounds"
      },
      {
       "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_order_total{pod=~\"$pod\"}[$__rate_interval])) > 0",
       "legendFormat": "Sample Out of Order"
      },
      {
       "expr": "sum(increase(prometheus_treecache_zookeeper_failures_total{pod=~\"$pod\"}[$__rate_interval])) > 0",
       "legendFormat": "Zookeeper"
      },
      {
       "expr": "sum(increase(prometheus_tsdb_compactions_failed_total{pod=~\"$pod\"}[$__rate_interval])) > 0",
       "legendFormat": "TSDB Compactions"
      },
      {
       "expr": "sum(increase(prometheus_tsdb_head_series_not_found{pod=~\"$pod\"}[$__rate_interval])) > 0",
       "legendFormat": "Series Not Found"
      },
      {
       "expr": "sum(increase(prometheus_tsdb_reloads_failures_total{pod=~\"$pod\"}[$__rate_interval])) > 0",
       "legendFormat": "Reload"
      }
     ]
    }
   ]
  },
  {
   "title": "up",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Upness (stacked)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "up{pod=~\"$pod\",job=\"prometheus\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Storage Memory Chunks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_chunks{job=\"prometheus\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "series",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Series Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_series{job=\"prometheus\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Series Created / Removed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum( increase(prometheus_tsdb_head_series_created_total{pod=~\"$pod\"}[$__rate_interval]) )",
       "legendFormat": "created"
      },
      {
       "expr": "sum( increase(prometheus_tsdb_head_series_removed_total{pod=~\"$pod\"}[$__rate_interval]) )",
       "legendFormat": "removed"
      }
     ]
    }
   ]
  },
  {
   "title": "appended samples",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Appended Samples per Second",
     "type": "timeseries",
     "description": "Rate of total number of appended samples",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=\"prometheus\",pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Scrape Sync Total",
     "type": "timeseries",
     "description": "Total number of syncs that were executed on a scrape pool.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(prometheus_target_scrape_pool_sync_total{job=\"prometheus\",pod=~\"$pod\"}) by (scrape_job)",
       "legendFormat": "{{scrape_job}}"
      }
     ]
    },
    {
     "title": "Target Sync",
     "type": "timeseries",
     "description": "Actual interval to sync the scrape pool.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{job=\"prometheus\",pod=~\"$pod\"}[$__rate_interval])) by (scrape_job) * 1000",
       "legendFormat": "{{scrape_job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "scrapes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Scrape Duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "scrape_duration_seconds{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rejected Scrapes",
     "type": "timeseries",
     "description": "Total number of rejected scrapes",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(prometheus_target_scrapes_exceeded_sample_limit_total{job=\"prometheus\",pod=~\"$pod\"})",
       "legendFormat": "exceeded sample limit"
      },
      {
       "expr": "sum(prometheus_target_scrapes_sample_duplicate_timestamp_total{job=\"prometheus\",pod=~\"$pod\"})",
       "legendFormat": "duplicate timestamp"
      },
      {
       "expr": "sum(prometheus_target_scrapes_sample_out_of_bounds_total{job=\"prometheus\",pod=~\"$pod\"})",
       "legendFormat": "out of bounds"
      },
      {
       "expr": "sum(prometheus_target_scrapes_sample_out_of_order_total{job=\"prometheus\",pod=~\"$pod\"}) ",
       "legendFormat": "out of order"
      }
     ]
    }
   ]
  },
  {
   "title": "durations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Average Rule Evaluation Duration",
     "type": "timeseries",
     "description": "The duration of rule group evaluations",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "1000 * rate(prometheus_evaluator_duration_seconds_sum{job=\"prometheus\", pod=~\"$pod\"}[$__rate_interval]) / rate(prometheus_evaluator_duration_seconds_count{job=\"prometheus\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "HTTP Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_microseconds_count{job=\"prometheus\",pod=~\"$pod\"}[$__rate_interval])) by (handler) > 0",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Prometheus Engine Query Duration Seconds",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(prometheus_engine_query_duration_seconds_sum{job=\"prometheus\",pod=~\"$pod\"}) by (slice)",
       "legendFormat": "{{slice}}"
      }
     ]
    },
    {
     "title": "Rule Evaluator Iterations",
     "type": "timeseries",
     "description": "Rule-group evaluations \n - total\n - missed due to slow rule group evaluation\n - skipped due to throttled metric storage",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(prometheus_evaluator_iterations_total{job=\"prometheus\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(prometheus_evaluator_iterations_missed_total{job=\"prometheus\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Missed"
      },
      {
       "expr": "sum(rate(prometheus_evaluator_iterations_skipped_total{job=\"prometheus\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Skipped"
      }
     ]
    }
   ]
  },
  {
   "title": "notifications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Notifications Sent",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_notifications_sent_total[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "config",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Minutes Since Successful Config Reload",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(time() - prometheus_config_last_reload_success_timestamp_seconds{job=\"prometheus\",pod=~\"$pod\"}) / 60",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Successful Config Reload",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_config_last_reload_successful{job=\"prometheus\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "garbage collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "GC Rate",
     "type": "timeseries",
     "description": "GC invocation durations",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(go_gc_duration_seconds_sum{pod=~\"$pod\",job=\"prometheus\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Broken, ignore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Go Memory Usage (FIXME)",
     "type": "timeseries",
     "description": "This is probably wrong!  Please help.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(go_memstats_alloc_bytes{job=\"prometheus\", pod=~\"$pod\"})",
       "legendFormat": "allocated"
      },
      {
       "expr": "sum(go_memstats_buck_hash_sys_bytes{job=\"prometheus\", pod=~\"$pod\"})",
       "legendFormat": "profiling bucket hash table"
      },
      {
       "expr": "sum(go_memstats_gc_sys_bytes{job=\"prometheus\", pod=~\"$pod\"})",
       "legendFormat": "GC metadata"
      },
      {
       "expr": "sum(go_memstats_heap_alloc_bytes{job=\"prometheus\", pod=~\"$pod\"})",
       "legendFormat": "heap in-use"
      },
      {
       "expr": "sum(go_memstats_heap_idle_bytes{job=\"prometheus\", pod=~\"$pod\"})",
       "legendFormat": "heap idle"
      },
      {
       "expr": "sum(go_memstats_heap_inuse_bytes{job=\"prometheus\", pod=~\"$pod\"})",
       "legendFormat": "heap in use"
      },
      {
       "expr": "sum(go_memstats_heap_released_bytes{job=\"prometheus\", pod=~\"$pod\"})",
       "legendFormat": "heap released"
      },
      {
       "expr": "sum(go_memstats_heap_sys_bytes{job=\"prometheus\", pod=~\"$pod\"})",
       "legendFormat": "heap system"
      },
      {
       "expr": "sum(go_memstats_mcache_inuse_bytes{job=\"prometheus\", pod=~\"$pod\"})",
       "legendFormat": "mcache in use"
      },
      {
       "expr": "sum(go_memstats_mcache_sys_bytes{job=\"prometheus\", pod=~\"$pod\"})",
       "legendFormat": "mcache sys"
      },
      {
       "expr": "sum(go_memstats_mspan_inuse_bytes{job=\"prometheus\", pod=~\"$pod\"})",
       "legendFormat": "mspan in use"
      },
      {
       "expr": "sum(go_memstats_mspan_sys_bytes{job=\"prometheus\", pod=~\"$pod\"})",
       "legendFormat": "mspan sys"
      },
      {
       "expr": "sum(go_memstats_next_gc_bytes{job=\"prometheus\", pod=~\"$pod\"})",
       "legendFormat": "heap next gc"
      },
      {
       "expr": "sum(go_memstats_other_sys_bytes{job=\"prometheus\", pod=~\"$pod\"})",
       "legendFormat": "other sys"
      },
      {
       "expr": "sum(go_memstats_stack_inuse_bytes{job=\"prometheus\", pod=~\"$pod\"})",
       "legendFormat": "stack in use"
      },
      {
       "expr": "sum(go_memstats_stack_sys_bytes{job=\"prometheus\", pod=~\"$pod\"})",
       "legendFormat": "stack sys"
      },
      {
       "expr": "sum(go_memstats_sys_bytes{job=\"prometheus\", pod=~\"$pod\"})",
       "legendFormat": "sys"
      }
     ]
    },
    {
     "title": "Scrape Duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_target_interval_length_seconds{pod=~\"$pod\", job=\"prometheus\"}",
       "legendFormat": "{{quantile}} {{interval}}"
      }
     ]
    },
    {
     "title": "Target Scrapes / 5m",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(prometheus_target_interval_length_seconds_count{job=\"prometheus\",pod=~\"$pod\"}[$__rate_interval])) by (interval)",
       "legendFormat": "{{interval}}"
      }
     ]
    }
   ]
  }
 ]
}