#!/bin/bash

# Copyright 2022 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Example usage:
# source ./tools/validation/run_env
# validation_go_run ./tools/validation --type copyright --file "$1"

# This snippet is needed because 'go run' still not in sync
# with other Go tools and considered a toy.
# See https://github.com/golang/go/issues/13440#issuecomment-218353305

if [[ -z $1 ]]; then
  echo -e "\nThere is no diff file."
  exit 1
fi

if [[ ! -f $1 ]]; then
  echo -e "\nDiff file '$1' is not found."
  exit 1
fi

for i in $(grep -E '^\+\+\+ b\/.*\.md$' $1 | sed -E 's#^\+\+\+ b\/##'); do
  markdownlint --config testing/markdownlint.yaml $i
done
