{
 "title": "Stronghold Replication Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "local_namespace",
    "query": {
     "query": "label_values(stronghold_core_replication_duration,local_namespace)"
    }
   },
   {
    "name": "local_mount_path",
    "query": {
     "query": "label_values(stronghold_core_replication_duration,local_mount_path)"
    }
   },
   {
    "name": "source_address",
    "query": {
     "query": "label_values(stronghold_core_replication_duration,source_address)"
    }
   },
   {
    "name": "source_namespace",
    "query": {
     "query": "label_values(stronghold_core_replication_duration,source_namespace)"
    }
   },
   {
    "name": "source_mount_path",
    "query": {
     "query": "label_values(stronghold_core_replication_duration,source_mount_path)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Replicated Records",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "stronghold_core_replication_records{local_namespace=~\"$local_namespace\", local_mount_path=~\"$local_mount_path\", source_address=~\"$source_address\", source_namespace=~\"$source_namespace\", source_mount_path=~\"$source_mount_path\", quantile=\"0.5\"}",
     "legendFormat": "{{source_address}}/{{source_namespace}}{{source_mount_path}}-->{{local_namespace}}{{local_mount_path}}"
    }
   ]
  },
  {
   "title": "Replication Source Address Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "stronghold_core_replication_source_addresses_count",
     "legendFormat": "source-addresses-count"
    }
   ]
  },
  {
   "title": "Replicated Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "stronghold_core_replication_bytes{local_namespace=~\"$local_namespace\", local_mount_path=~\"$local_mount_path\", source_address=~\"$source_address\", source_namespace=~\"$source_namespace\", source_mount_path=~\"$source_mount_path\", quantile=\"0.5\"}",
     "legendFormat": "{{source_address}}/{{source_namespace}}{{source_mount_path}}-->{{local_namespace}}{{local_mount_path}}"
    }
   ]
  },
  {
   "title": "Replication Source Mount Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "stronghold_core_replication_source_mounts_count",
     "legendFormat": "source-mount-count"
    }
   ]
  },
  {
   "title": "Replication Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "stronghold_core_replication_duration{local_namespace=~\"$local_namespace\", local_mount_path=~\"$local_mount_path\", source_address=~\"$source_address\", source_namespace=~\"$source_namespace\", source_mount_path=~\"$source_mount_path\", quantile=\"0.5\"}",
     "legendFormat": "{{source_address}}/{{source_namespace}}{{source_mount_path}}-->{{local_namespace}}{{local_mount_path}}"
    }
   ]
  },
  {
   "title": "Replication Local Mount Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "stronghold_core_replication_local_mount_count",
     "legendFormat": "local-mount-count"
    }
   ]
  },
  {
   "title": "Replication speed b/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(stronghold_core_replication_bytes_sum{local_namespace=~\"$local_namespace\", local_mount_path=~\"$local_mount_path\", source_address=~\"$source_address\", source_namespace=~\"$source_namespace\", source_mount_path=~\"$source_mount_path\"}[5m])\n/ \nrate(stronghold_core_replication_duration_sum{local_namespace=~\"$local_namespace\", local_mount_path=~\"$local_mount_path\", source_address=~\"$source_address\", source_namespace=~\"$source_namespace\", source_mount_path=~\"$source_mount_path\"}[5m])",
     "legendFormat": "{{source_address}}/{{source_namespace}}{{source_mount_path}}-->{{local_namespace}}{{local_mount_path}}"
    }
   ]
  },
  {
   "title": "Replication TTL per Namespace/Mount",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "stronghold_core_replication_ttl{local_namespace=~\"$local_namespace\", local_mount_path=~\"$local_mount_path\", source_address=~\"$source_address\", source_namespace=~\"$source_namespace\", source_mount_path=~\"$source_mount_path\"}",
     "legendFormat": "{{local_namespace}}{{local_mount_path}}"
    }
   ]
  },
  {
   "title": "Replication speed record/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(stronghold_core_replication_records_sum{local_namespace=~\"$local_namespace\", local_mount_path=~\"$local_mount_path\", source_address=~\"$source_address\", source_namespace=~\"$source_namespace\", source_mount_path=~\"$source_mount_path\"}[5m]) \n/ \nrate(stronghold_core_replication_duration_sum{local_namespace=~\"$local_namespace\", local_mount_path=~\"$local_mount_path\", source_address=~\"$source_address\", source_namespace=~\"$source_namespace\", source_mount_path=~\"$source_mount_path\"}[5m])",
     "legendFormat": "{{source_address}}/{{source_namespace}}{{source_mount_path}}-->{{local_namespace}}{{local_mount_path}}"
    }
   ]
  },
  {
   "title": "Replicated secret paths",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "stronghold_core_replication_secret_path_count{local_namespace=~\"$local_namespace\", local_mount_path=~\"$local_mount_path\", source_address=~\"$source_address\", source_namespace=~\"$source_namespace\", source_mount_path=~\"$source_mount_path\"}",
     "legendFormat": "{{source_address}}/{{source_namespace}}{{source_mount_path}}-->{{local_namespace}}{{local_mount_path}}"
    }
   ]
  },
  {
   "title": "Replication Errors per Namespace/Mount",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "stronghold_core_replication_errors{local_namespace=~\"$local_namespace\", local_mount_path=~\"$local_mount_path\", source_address=~\"$source_address\", source_namespace=~\"$source_namespace\", source_mount_path=~\"$source_mount_path\"}",
     "legendFormat": "{{source_address}}/{{source_namespace}}{{source_mount_path}}-->{{local_namespace}}{{local_mount_path}}"
    }
   ]
  }
 ]
}