{
 "title": "Stronghold",
 "description": "Stronghold Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(up{job=\"d8-monitoring/stronghold\"}, instance)"
    }
   },
   {
    "name": "port",
    "query": {
     "query": "label_values(up{job=\"d8-monitoring/stronghold\",instance=~\"$node:(.*)\"}, instance)"
    }
   },
   {
    "name": "mountpoint",
    "label": "Mount Point:",
    "query": {
     "query": "label_values(stronghold_secret_kv_count,mount_point)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace:",
    "query": {
     "query": "label_values(stronghold_identity_entity_count,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(stronghold_autopilot_failure_tolerance or vector(-1))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Number of Identity Entities",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(instance,node) (last_over_time(stronghold_identity_num_entities[10m]))",
     "legendFormat": "Entity"
    }
   ]
  },
  {
   "title": "Active Entity Count (per month)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(instance,node) (last_over_time(stronghold_identity_entity_active_partial_month[10m]))",
     "legendFormat": "Active Entity"
    }
   ]
  },
  {
   "title": "Identity Entities Aliases by Method",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(auth_method) (last_over_time(stronghold_identity_entity_alias_count{namespace=~\"$namespace\"}[10m]))",
     "legendFormat": "{{ auth_method }}"
    }
   ]
  },
  {
   "title": "Secrets",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (mount_point,namespace) (last_over_time(stronghold_secret_kv_count{namespace=~\"$namespace\",mount_point=~\"${mountpoint}/\"}[10m]))",
     "legendFormat": "{{ mount_point }}"
    }
   ]
  },
  {
   "title": "Number of Leases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(instance,node) (stronghold_expire_num_leases)",
     "legendFormat": "Leases"
    }
   ]
  },
  {
   "title": "Secrets usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Create Operations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by(mount_namespace,mount_path) (increase(stronghold_route_create_mount_count{mount_namespace=~\"$namespace\",mount_path=~\"$mountpoint\"}[5m]))",
       "legendFormat": "{{mount_namespace}}/{{mount_path}}"
      }
     ]
    },
    {
     "title": "Time of Create Operations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by(mount_namespace,mount_path) (rate(stronghold_route_create_mount_sum{mount_namespace=~\"$namespace\",mount_path=~\"$mountpoint\"}[1m]) / rate(stronghold_route_create_mount_count{mount_namespace=~\"$namespace\",mount_path=~\"$mountpoint\"}[1m]) * 1000)",
       "legendFormat": "{{mount_namespace}}/{{mount_path}}"
      }
     ]
    },
    {
     "title": "Number of Read Operations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by(mount_namespace,mount_path) (increase(stronghold_route_read_mount_count{mount_namespace=~\"$namespace\",mount_path=~\"$mountpoint\"}[5m]))",
       "legendFormat": "{{mount_namespace}}/{{mount_path}}"
      }
     ]
    },
    {
     "title": "Time of Read Operations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by(mount_namespace,mount_path) (rate(stronghold_route_read_mount_sum{mount_namespace=~\"$namespace\",mount_path=~\"$mountpoint\"}[1m]) / rate(stronghold_route_read_mount_count{mount_namespace=~\"$namespace\",mount_path=~\"$mountpoint\"}[1m]) * 1000)",
       "legendFormat": "{{mount_namespace}}/{{mount_path}}"
      }
     ]
    },
    {
     "title": "Number of Delete Operations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by(mount_namespace,mount_path) (increase(stronghold_route_delete_mount_count{mount_namespace=~\"$namespace\",mount_path=~\"$mountpoint\"}[5m]))",
       "legendFormat": "{{mount_namespace}}/{{mount_path}}"
      }
     ]
    },
    {
     "title": "Time of Delete Operations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by(mount_namespace,mount_path) (rate(stronghold_route_delete_mount_sum{mount_namespace=~\"$namespace\",mount_path=~\"$mountpoint\"}[1m]) / rate(stronghold_route_delete_mount_count{mount_namespace=~\"$namespace\",mount_path=~\"$mountpoint\"}[1m]) * 1000)",
       "legendFormat": "{{mount_namespace}}/{{mount_path}}"
      }
     ]
    },
    {
     "title": "Number of List Operations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by(mount_namespace,mount_path) (increase(stronghold_route_list_mount_count{mount_namespace=~\"$namespace\",mount_path=~\"$mountpoint\"}[5m]))",
       "legendFormat": "{{mount_namespace}}/{{mount_path}}"
      }
     ]
    },
    {
     "title": "Time of List Operations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by(mount_namespace,mount_path) (rate(stronghold_route_list_mount_sum{mount_namespace=~\"$namespace\",mount_path=~\"$mountpoint\"}[1m]) / rate(stronghold_route_list_mount_count{mount_namespace=~\"$namespace\",mount_path=~\"$mountpoint\"}[1m]) * 1000)",
       "legendFormat": "{{mount_namespace}}/{{mount_path}}"
      }
     ]
    },
    {
     "title": "Number of Rollback Operations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by(mount_namespace,mount_path) (increase(stronghold_route_rollback_mount_count{mount_namespace=~\"$namespace\",mount_path=~\"$mountpoint\"}[5m]))",
       "legendFormat": "{{mount_namespace}}/{{mount_path}}"
      }
     ]
    },
    {
     "title": "Time of Rollback Operations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by(mount_namespace,mount_path) (rate(stronghold_route_rollback_mount_sum{mount_namespace=~\"$namespace\",mount_path=~\"$mountpoint\"}[1m]) / rate(stronghold_route_rollback_mount_count{mount_namespace=~\"$namespace\",mount_path=~\"$mountpoint\"}[1m]) * 1000)",
       "legendFormat": "{{mount_namespace}}/{{mount_path}}"
      }
     ]
    },
    {
     "title": "Number of Update Operations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by(mount_namespace,mount_path) (increase(stronghold_route_update_mount_count{mount_namespace=~\"$namespace\",mount_path=~\"$mountpoint\"}[5m]))",
       "legendFormat": "{{mount_namespace}}/{{mount_path}}"
      }
     ]
    },
    {
     "title": "Time of Update Operations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by(mount_namespace,mount_path) (rate(stronghold_route_update_mount_sum{mount_namespace=~\"$namespace\",mount_path=~\"$mountpoint\"}[1m]) / rate(stronghold_route_update_mount_count{mount_namespace=~\"$namespace\",mount_path=~\"$mountpoint\"}[1m]) * 1000)",
       "legendFormat": "{{mount_namespace}}/{{mount_path}}"
      }
     ]
    }
   ]
  },
  { "title": "Cluster health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Nodes health status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "stronghold_autopilot_node_healthy * on(node_id) group_left(node) label_replace(max by (\"peer_id\",\"node\") (present_over_time(stronghold_raft_storage_stats_term[7d])), \"node_id\", \"$1\", \"peer_id\", \"(.*)\")",
     "legendFormat": "{{node}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Sealed Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1+min(stronghold_core_unsealed) by(node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "CPU/Mem Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Percentage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "avg by(node) (rate(container_cpu_usage_seconds_total{namespace=\"d8-stronghold\",container=\"stronghold\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Allocated MB",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by(node) (stronghold_runtime_alloc_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heap Objects Used",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "avg by(node) (stronghold_runtime_heap_objects{} / stronghold_runtime_malloc_count{})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "avg by(node) (stronghold_runtime_num_goroutines{})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Token", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Available Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(stronghold_token_count{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Tokens by Policy",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "last_over_time(stronghold_token_count_by_policy{namespace=~\"$namespace\"}[10m])",
     "legendFormat": "{{ policy }}"
    }
   ]
  },
  {
   "title": "Pending Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(stronghold_token_create_count - stronghold_token_store_count)"
    }
   ]
  },
  {
   "title": "Tokens by TTL",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(creation_ttl) (last_over_time(stronghold_token_count_by_ttl{namespace=~\"$namespace\"}[10m]))",
     "legendFormat": "{{ creation_ttl }}"
    }
   ]
  },
  {
   "title": "Tokens by Auth Method",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(auth_method) (last_over_time(stronghold_token_count_by_auth{namespace=~\"$namespace\"}[10m]))",
     "legendFormat": "{{ auth_method }}"
    }
   ]
  },
  {
   "title": "Tokens Creation by Method & TTL",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(auth_method, creation_ttl) (rate(stronghold_token_creation{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{ auth_method }} - {{ creation_ttl }}"
    }
   ]
  },
  {
   "title": "Token Creation/Storage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg without(instance) (stronghold_token_create_count)",
     "legendFormat": "Create"
    },
    {
     "expr": "avg without(instance) (stronghold_token_store_count)",
     "legendFormat": "Store"
    }
   ]
  },
  {
   "title": "Token Lookups",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(stronghold_token_lookup_count[1m]))",
     "legendFormat": "Lookups"
    }
   ]
  },
  { "title": "Audit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Log Request Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(stronghold_audit_log_request_failure[1m]))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Log Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 3, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(stronghold_audit_log_request_count[1m]))",
     "legendFormat": "Request "
    },
    {
     "expr": "avg(irate(stronghold_audit_log_response_count[1m]))",
     "legendFormat": "Response"
    },
    {
     "expr": "avg(irate(stronghold_core_handle_request_count[1m]))",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Raft Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(stronghold_raft_get_count[1m]))",
     "legendFormat": "GET"
    },
    {
     "expr": "avg(irate(stronghold_raft_put_count[1m]))",
     "legendFormat": "PUT"
    },
    {
     "expr": "avg(irate(stronghold_raft_delete_count[1m]))",
     "legendFormat": "DELETE"
    },
    {
     "expr": "irate(stronghold_raft_list_count{instance=\"$node:$port\"}[1m])",
     "legendFormat": "LIST"
    }
   ]
  },
  {
   "title": "Log Response Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(stronghold_audit_log_response_failure[1m]))",
     "legendFormat": "Request"
    }
   ]
  },
  { "title": "Policy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Policy Set",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(stronghold_policy_set_policy_count[1m]))",
     "legendFormat": "SET"
    }
   ]
  },
  {
   "title": "Policy Get",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(stronghold_policy_get_policy_count[1m]))",
     "legendFormat": "GET"
    }
   ]
  }
 ]
}