---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: validation-webhook
  namespace: d8-cloud-provider-dvp
  {{- include "helm_lib_module_labels" (list . (dict "app" "validation-webhook")) | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:cloud-provider-dvp:validation-webhook
  {{- include "helm_lib_module_labels" (list . (dict "app" "validation-webhook")) | nindent 2 }}
rules:
- apiGroups:
  - deckhouse.io
  resources:
  - moduleconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deckhouse.io
  resources:
  - nodegroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deckhouse.io
  resources:
  - dvpinstanceclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:cloud-provider-dvp:validation-webhook
  {{- include "helm_lib_module_labels" (list . (dict "app" "validation-webhook")) | nindent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: d8:cloud-provider-dvp:validation-webhook
subjects:
- kind: ServiceAccount
  name: validation-webhook
  namespace: d8-cloud-provider-dvp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:cloud-provider-dvp:validation-webhook:d8-rbac-proxy
  {{- include "helm_lib_module_labels" (list . (dict "app" "validation-webhook")) | nindent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: d8:rbac-proxy
subjects:
- kind: ServiceAccount
  name: validation-webhook
  namespace: d8-cloud-provider-dvp
