{{- define "openstack_cdd_pod_annotations" -}}
checksum/config: {{ include (print $.Template.BasePath "/cloud-data-discoverer/secret.yaml") . | sha256sum }}
{{- end -}}

{{- define "openstack_cdd_envs" -}}
- name: OS_AUTH_URL
  valueFrom:
    secretKeyRef:
      key: authURL
      name: cloud-data-discoverer
- name: OS_DOMAIN_NAME
  valueFrom:
    secretKeyRef:
      key: domainName
      name: cloud-data-discoverer
  {{- if hasKey .Values.cloudProviderOpenstack.internal.connection "tenantID" }}
- name: OS_TENANT_ID
  valueFrom:
    secretKeyRef:
      key: tenantID
      name: cloud-data-discoverer
  {{- end }}
  {{- if hasKey .Values.cloudProviderOpenstack.internal.connection "tenantName" }}
- name: OS_TENANT_NAME
  valueFrom:
    secretKeyRef:
      key: tenantName
      name: cloud-data-discoverer
  {{- end }}
  {{- if hasKey .Values.cloudProviderOpenstack.internal.connection "caCert" }}
- name: OS_CACERT
  value: /etc/config/ca.crt
  {{- end }}
- name: OS_USERNAME
  valueFrom:
    secretKeyRef:
      key: username
      name: cloud-data-discoverer
- name: OS_PASSWORD
  valueFrom:
    secretKeyRef:
      key: password
      name: cloud-data-discoverer
- name: OS_REGION
  valueFrom:
    secretKeyRef:
      key: region
      name: cloud-data-discoverer
- name: MODULE_CONFIG
  valueFrom:
    secretKeyRef:
      key: moduleConfig
      name: cloud-data-discoverer
- name: CLUSTER_UUID
  value: {{ .Values.global.discovery.clusterUUID | quote }}
{{- end -}}

{{- define "openstack_cdd_volume_mounts" -}}
- name: config
  mountPath: /etc/config
  readOnly: true
{{- end -}}

{{- define "openstack_cdd_volumes" -}}
- name: config
  secret:
    secretName: cloud-data-discoverer
{{- end -}}

{{- $cddConfig := dict -}}
{{- $_ := set $cddConfig "image" (include "helm_lib_module_image" (list . "cloudDataDiscoverer")) -}}
{{- $_ := set $cddConfig "additionalEnv" (include "openstack_cdd_envs" . | fromYamlArray) -}}
{{- $_ := set $cddConfig "additionalPodAnnotations" (include "openstack_cdd_pod_annotations" . | fromYaml) -}}
{{- $_ := set $cddConfig "additionalVolumeMounts" (include "openstack_cdd_volume_mounts" . | fromYamlArray) -}}
{{- $_ := set $cddConfig "additionalVolumes" (include "openstack_cdd_volumes" . | fromYamlArray) -}}
{{- $_ := set $cddConfig "vpaEnabled" true -}}

{{- include "helm_lib_cloud_data_discoverer_manifests" (list . $cddConfig) }}
