apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    heritage: deckhouse
    module: cloud-provider-gcp
    rbac.deckhouse.io/aggregate-to-infrastructure-as: viewer
    rbac.deckhouse.io/kind: capability
    rbac.deckhouse.io/capability: "system-capability.cloud-provider-gcp.view"
    rbac.deckhouse.io/scope: system
    rbac.deckhouse.io/namespace: d8-cloud-provider-gcp
  name: d8:system-capability:cloud-provider-gcp:view
  annotations:
    en.meta.deckhouse.io/title: "Module cloud-provider-gcp: view configuration"
    ru.meta.deckhouse.io/title: "Модуль cloud-provider-gcp: просмотр конфигурации"
    en.meta.deckhouse.io/description: "Read-only access to the cloud-provider-gcp module configuration."
    ru.meta.deckhouse.io/description: "Доступ только на чтение к конфигурации модуля cloud-provider-gcp."
rules:
- apiGroups:
  - deckhouse.io
  resourceNames:
  - cloud-provider-gcp
  resources:
  - moduleconfigs
  verbs:
  - get
  - list
  - watch
