#!/bin/bash
# Copyright 2026 Flant JSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE

set -Eeo pipefail
mkdir -p /opt/deckhouse/bin
cp -f d8-bcheck /opt/deckhouse/bin
