#!/bin/bash

# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /deckhouse/shell_lib.sh

function __main__() {
  # Disable module if dns-controller enabled in a cluster (it means that cluster is deployed by kops)
  if kubectl -n kube-system get deployment dns-controller >/dev/null 2>&1 ; then
    echo "false" > "$MODULE_ENABLED_RESULT"
  else
    echo "true" > "$MODULE_ENABLED_RESULT"
  fi
}

enabled::run "$@"
