#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    afterHelm: 10
EOF
}

function __main__() {
  if values::has deckhouseWeb.internal.deployDexAuthenticator && values::is_true global.clusterIsBootstrapped ; then
    allowedGroups=""
    if values::has deckhouseWeb.auth.allowedUserGroups ; then
      allowedGroups="allowedGroups: $(values::get deckhouseWeb.auth.allowedUserGroups)"
    fi
    cat <<EOF | kubectl apply -f -
apiVersion: deckhouse.io/v1alpha1
kind: DexAuthenticator
metadata:
 name: deckhouse-web
 namespace: d8-system
 labels:
   heritage: deckhouse
   module: deckhouse-web
   app: dex-authenticator
spec:
  applicationDomain: "$(module::public_domain deckhouse)"
  applicationIngressCertificateSecretName: "$(module::https_secret_name "ingress-tls")"
  applicationIngressClassName: "$(module::ingress_class)"
  $allowedGroups
EOF
  else
    if kubectl -n d8-system get dexauthenticator deckhouse-web >/dev/null 2>/dev/null ; then
      kubectl -n d8-system delete dexauthenticator deckhouse-web >/dev/null 2>/dev/null
    fi
  fi
}

hook::run "$@"
