{
 "title": "Registry Distribution",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "registry-distribution" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "description": "Up",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(\n    up{job=~\"$job\"},\n    \"host_ip\",\n    \"$1\",\n    \"instance\",\n    \"([^:]+):.*\"\n)\n* on (host_ip) group_left (pod, node)\nkube_pod_info{created_by_kind=\"Node\",namespace=\"d8-system\",pod=~\"^registry-.*$\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Registry storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": " 90th Percentile of Storage Action Duration",
     "type": "timeseries",
     "description": "This query calculates the 90th percentile of storage action durations in the Registry over a specified time interval.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(registry_storage_action_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "average"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(registry_storage_action_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le, action, driver))",
       "legendFormat": "{{action}} {{driver}}"
      }
     ]
    },
    {
     "title": "95th Percentile of Storage Action Duration",
     "type": "timeseries",
     "description": "This query calculates the 95th percentile of storage action durations in the Registry over a specified time interval.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(registry_storage_action_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "average"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(registry_storage_action_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le, action, driver))",
       "legendFormat": "{{action}} {{driver}}"
      }
     ]
    },
    {
     "title": "99th Percentile of Storage Action Duration",
     "type": "timeseries",
     "description": "This query calculates the 99th percentile of storage action durations in the Registry over a specified time interval.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(registry_storage_action_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "average"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(registry_storage_action_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le, action, driver))",
       "legendFormat": "{{action}} {{driver}}"
      }
     ]
    },
    {
     "title": "Storage Cache Operation Rate",
     "type": "timeseries",
     "description": "This query calculates the rate of storage actions in the Registry over a specified time interval, aggregated by action type and driver.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(registry_storage_cache_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Registry http",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "90th Percentile HTTP Request Duration",
     "type": "timeseries",
     "description": "90th Percentile HTTP Request Duration",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(registry_http_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le, method))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "95th Percentile HTTP Request Duration",
     "type": "timeseries",
     "description": "95th Percentile HTTP Request Duration",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(registry_http_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le, method))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "99th Percentile HTTP Request Duration",
     "type": "timeseries",
     "description": "99th Percentile HTTP Request Duration",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(registry_http_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le, method))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Registry request RPS",
     "type": "timeseries",
     "description": "Registry request RPS",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(registry_http_requests_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (method)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "90th Percentile HTTP Request size",
     "type": "timeseries",
     "description": "90th Percentile HTTP Request size",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(registry_http_request_size_bytes_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le, handler))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "90th Percentile HTTP Response size",
     "type": "timeseries",
     "description": "90th Percentile HTTP Response size",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(registry_http_response_size_bytes_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le, handler))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "In-Flight HTTP Requests by Handler",
     "type": "timeseries",
     "description": "This query calculates the current number of in-flight HTTP requests to the Registry, aggregated by request handler.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(registry_http_in_flight_requests{job=~\"$job\", instance=~\"$instance\"}) by (handler)",
       "legendFormat": "{{handler}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process memory",
     "type": "timeseries",
     "description": "This query shows the amount of physical memory (RAM) used by the process.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}} - resident"
      },
      {
       "expr": "process_virtual_memory_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}} - virtual"
      }
     ]
    },
    {
     "title": "Process memory deriv",
     "type": "timeseries",
     "description": "This query shows the rate of change in physical memory (RAM) usage by the process over a specified time interval.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(process_resident_memory_bytes{job=~\"$job\",instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{instance}} - resident"
      },
      {
       "expr": "deriv(process_virtual_memory_bytes{job=~\"$job\",instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{instance}} - virtual"
      }
     ]
    },
    {
     "title": "Go memstats",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}} - bytes allocated"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=~\"$job\",instance=~\"$instance\"}[30s])",
       "legendFormat": "{{instance}} - alloc rate"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}} - stack inuse"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}} - heap inuse"
      }
     ]
    },
    {
     "title": "Go memstats deriv",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "deriv(go_memstats_alloc_bytes{job=~\"$job\",instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{instance}} - bytes allocated"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{instance}} - alloc rate"
      },
      {
       "expr": "deriv(go_memstats_stack_inuse_bytes{job=~\"$job\",instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{instance}} - stack inuse"
      },
      {
       "expr": "deriv(go_memstats_heap_inuse_bytes{job=~\"$job\",instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{instance}} - heap inuse"
      }
     ]
    },
    {
     "title": "Open fds",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_open_fds{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Open fds deriv",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "deriv(process_open_fds{job=~\"$job\",instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC duration quantiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}: {{quantile}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}