{
 "title": "Registry Manager",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "registry-nodeservices-manager" },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(up{job=~\"$job\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "description": "Up",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (up{job=~\"$job\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "leader election",
   "type": "stat",
   "description": "leader election",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (leader_election_master_status{job=~\"$job\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Reconciliation Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of workers in use",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "controller_runtime_active_workers{job=\"$job\", pod=~\"$pod\"}",
       "legendFormat": "{{controller}} {{instance}}"
      }
     ]
    },
    {
     "title": "Total Reconciliation Count Per Controller",
     "type": "timeseries",
     "description": "Total number of reconciliations per controller",
     "gridPos": { "h": 8, "w": 11, "x": 3, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "sum(rate(controller_runtime_reconcile_total{job=\"$job\", pod=~\"$pod\"}[$__rate_interval])) by (instance, pod)",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    },
    {
     "title": "Reconciliation Error Count Per Controller",
     "type": "timeseries",
     "description": "Total number of reconciliation errors per controller",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "sum(rate(controller_runtime_reconcile_errors_total{job=\"$job\", pod=~\"$pod\"}[$__rate_interval])) by (instance, pod)",
       "legendFormat": "{{instance}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Work Queue Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "WorkQueue Depth",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "workqueue_depth{job=\"$job\", pod=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "Seconds For Items Stay In Queue (before being requested) (P50, P90, P99)",
     "type": "timeseries",
     "description": "How long in seconds an item stays in workqueue before being requested",
     "gridPos": { "h": 8, "w": 11, "x": 3, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"$job\", pod=~\"$pod\"}[$__rate_interval])) by (instance, name, le))",
       "legendFormat": "P50 {{name}} {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"$job\", pod=~\"$pod\"}[$__rate_interval])) by (instance, name, le))",
       "legendFormat": "P90 {{name}} {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"$job\", pod=~\"$pod\"}[$__rate_interval])) by (instance, name, le))",
       "legendFormat": "P99 {{name}} {{instance}} "
      }
     ]
    },
    {
     "title": "Work Queue Add Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(workqueue_adds_total{job=\"$job\", pod=~\"$pod\"}[$__rate_interval])) by (instance, name)",
       "legendFormat": "{{name}} {{instance}}"
      }
     ]
    },
    {
     "title": "Unfinished Seconds",
     "type": "gauge",
     "description": "How many seconds of work has done that is in progress and hasn't been observed by work_duration.\nLarge values indicate stuck threads.\nOne can deduce the number of stuck threads by observing the rate at which this increases.",
     "gridPos": { "h": 9, "w": 3, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(workqueue_unfinished_work_seconds{job=\"$job\", pod=~\"$pod\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Seconds Processing Items From WorkQueue (P50, P90, P99)",
     "type": "timeseries",
     "description": "How long in seconds processing an item from workqueue takes.",
     "gridPos": { "h": 9, "w": 11, "x": 3, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(workqueue_work_duration_seconds_bucket{job=\"$job\", pod=~\"$pod\"}[$__rate_interval])) by (instance, name, le))",
       "legendFormat": "P50 {{name}} {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(workqueue_work_duration_seconds_bucket{job=\"$job\", pod=~\"$pod\"}[5m])) by (instance, name, le))",
       "legendFormat": "P90 {{name}} {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(workqueue_work_duration_seconds_bucket{job=\"$job\", pod=~\"$pod\"}[5m])) by (instance, name, le))",
       "legendFormat": "P99 {{name}} {{instance}} "
      }
     ]
    },
    {
     "title": "Work Queue Retries Rate",
     "type": "timeseries",
     "description": "Total number of retries handled by workqueue",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(workqueue_retries_total{job=\"$job\", pod=~\"$pod\"}[$__rate_interval])) by (instance, name)",
       "legendFormat": "{{name}} {{instance}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Go",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process memory",
     "type": "timeseries",
     "description": "This query shows the amount of physical memory (RAM) used by the process.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=~\"$job\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}} - resident"
      },
      {
       "expr": "process_virtual_memory_bytes{job=~\"$job\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}} - virtual"
      }
     ]
    },
    {
     "title": "Process memory deriv",
     "type": "timeseries",
     "description": "This query shows the rate of change in physical memory (RAM) usage by the process over a specified time interval.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(process_resident_memory_bytes{job=~\"$job\",pod=~\"$pod\"}[$__interval])",
       "legendFormat": "{{pod}} - resident"
      },
      {
       "expr": "deriv(process_virtual_memory_bytes{job=~\"$job\",pod=~\"$pod\"}[$__interval])",
       "legendFormat": "{{pod}} - virtual"
      }
     ]
    },
    {
     "title": "Go memstats",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=~\"$job\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}} - bytes allocated"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=~\"$job\",pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} - alloc rate"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{job=~\"$job\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}} - stack inuse"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=~\"$job\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}} - heap inuse"
      }
     ]
    },
    {
     "title": "Go memstats deriv",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "deriv(go_memstats_alloc_bytes{job=~\"$job\",pod=~\"$pod\"}[$__interval])",
       "legendFormat": "{{pod}} - bytes allocated"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=~\"$job\",pod=~\"$pod\"}[$__interval])",
       "legendFormat": "{{pod}} - alloc rate"
      },
      {
       "expr": "deriv(go_memstats_stack_inuse_bytes{job=~\"$job\",pod=~\"$pod\"}[$__interval])",
       "legendFormat": "{{pod}} - stack inuse"
      },
      {
       "expr": "deriv(go_memstats_heap_inuse_bytes{job=~\"$job\",pod=~\"$pod\"}[$__interval])",
       "legendFormat": "{{pod}} - heap inuse"
      }
     ]
    },
    {
     "title": "Open fds",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_open_fds{job=~\"$job\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Open fds deriv",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "deriv(process_open_fds{job=~\"$job\",pod=~\"$pod\"}[$__interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GC duration quantiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=~\"$job\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}: {{quantile}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=~\"$job\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}