{
 "title": "Admission policy engine",
 "description": "Visualize violations from OPA Gatekeeper",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summaries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total constraint templates",
   "type": "stat",
   "description": "Description: Current number of constraint templates\n\"All NS\"\n\nUnderstanding this metric: Gatekeeper subscribes to a watch on all ConstraintTemplate resources. Whenever one is created or deleted on the cluster, this count gets updated.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (gatekeeper_constraint_templates{pod=~\"gatekeeper-controller-manager-.+\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total Violations",
   "type": "bargauge",
   "description": "Description: The number of audit violations per constraint detected in the last audit cycle\n\nUnderstanding this metric: During each run, the audit sums up all of the violations that it finds and reports these counts per-enforcement-mode.",
   "gridPos": { "h": 5, "w": 7, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (enforcement_action) (gatekeeper_violations)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Total Violations by kind",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (kind) (d8_gatekeeper_exporter_constraint_violations{violating_namespace=~\"$namespace\"})",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  { "title": "Constraint details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "OPA Violations",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "group(d8_gatekeeper_exporter_constraint_violations{violating_namespace=~\".*\"}) by (time, violating_kind, violating_namespace, violating_name, kind, violation_enforcement, violation_msg)"
    }
   ]
  },
  {
   "title": "OPA Violations Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (violating_name) (d8_gatekeeper_exporter_constraint_violations{violating_namespace=~\"$namespace\"})",
     "legendFormat": "{{violating_name}}"
    }
   ]
  },
  {
   "title": "Total Violations by kind",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (kind) (d8_gatekeeper_exporter_constraint_violations{violating_namespace=~\"$namespace\"})",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Enforcement Actions",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(d8_gatekeeper_exporter_constraint_violations{violation_enforcement=\"warn\",violating_namespace=~\"$namespace\"})",
     "legendFormat": "warn"
    },
    {
     "expr": "sum(d8_gatekeeper_exporter_constraint_violations{violation_enforcement=\"deny\",violating_namespace=~\"$namespace\"})",
     "legendFormat": "deny"
    },
    {
     "expr": "sum(d8_gatekeeper_exporter_constraint_violations{violation_enforcement=\"dryrun\",violating_namespace=~\"$namespace\"})",
     "legendFormat": "dryrun"
    },
    {
     "expr": "sum(d8_gatekeeper_exporter_constraint_violations{violation_enforcement=\"unrecognized\",violating_namespace=~\"$namespace\"})",
     "legendFormat": "unrecognized"
    }
   ]
  },
  { "title": "Audit process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Total Violations",
   "type": "bargauge",
   "description": "The number of audit violations per constraint detected in the last audit cycle",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (enforcement_action) (gatekeeper_violations)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Audit duration",
   "type": "stat",
   "description": "Latency of audit operation",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gatekeeper_audit_duration_seconds_count[10m])"
    }
   ]
  },
  {
   "title": "Audit last run time",
   "type": "stat",
   "description": "Description: Timestamp of last audit run time",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - gatekeeper_audit_last_run_time"
    }
   ]
  },
  {
   "title": "Total GroupVersionKinds",
   "type": "stat",
   "description": "Total number of watched GroupVersionKinds",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gatekeeper_watch_manager_watched_gvk{pod=~\"gatekeeper-controller.+\"}) / sum(gatekeeper_watch_manager_watched_gvk{pod=~\"gatekeeper-controller.+\"})"
    }
   ]
  },
  {
   "title": "Total GroupVersionKinds registered",
   "type": "stat",
   "description": "Total number of GroupVersionKinds with a registered watch intent",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gatekeeper_watch_manager_intended_watch_gvk{pod=~\"gatekeeper-controller.+\"}) / sum(gatekeeper_watch_manager_intended_watch_gvk{pod=~\"gatekeeper-controller.+\"})"
    }
   ]
  },
  { "title": "Admission webook", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Mutation request count",
   "type": "timeseries",
   "description": "Description: The number of requests that are routed to mutation webhook",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by (mutation_status, pod) (rate(gatekeeper_mutation_request_count[20m]))",
     "legendFormat": "{{mutation_status}}"
    }
   ]
  },
  {
   "title": "Validation request count",
   "type": "timeseries",
   "description": "Description: The number of requests that are routed to validation webhook",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum by (admission_status, pod) (rate(gatekeeper_validation_request_count[20m]))",
     "legendFormat": "{{admission_status}}"
    }
   ]
  },
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Constraint templates",
   "type": "stat",
   "description": "Description: Current number of constraint templates\n\nUnderstanding this metric: Gatekeeper subscribes to a watch on all ConstraintTemplate resources. Whenever one is created or deleted on the cluster, this count gets updated.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (gatekeeper_constraint_templates{pod=~\"gatekeeper-controller-manager-.+\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Constraints",
   "type": "bargauge",
   "description": "Current number of constraints\nUnderstanding this metric: Gatekeeper subscribes to a watch on all constraint resources. Whenever one is created or deleted on the cluster, this count gets updated.",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (enforcement_action) (gatekeeper_constraints)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Constraint template ingestion duration",
   "type": "histogram",
   "description": "Description: Constraint Template ingestion duration distribution\n\nUnderstanding this metric: When Gatekeeper is notified of a new constraint template, records the time from when it has loaded the resource from etcd to after OPA successfully returns from compiling the code. If there is a compilation error, the metric is not updated.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(gatekeeper_constraint_template_ingestion_count[10m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}