{{- if or (.Values.global.discovery.apiVersions | has "monitoring.coreos.com/v1/ServiceMonitor") (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") }}
---
apiVersion: v1
kind: Service
metadata:
  name: control-plane-proxy
  namespace: kube-system
  {{- include "helm_lib_module_labels" (list . (dict "app" "control-plane-proxy")) | nindent 2 }}
spec:
  selector:
    app: control-plane-proxy
  ports:
  - name: https-metrics
    port: 8080
    protocol: TCP
    targetPort: https-metrics
{{- end }}
