{
 "title": "Redis",
 "description": "Prometheus dashboard for Redis servers (by pod and alias)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(redis_connected_clients, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(redis_connected_clients{namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "alias",
    "query": "label_values(redis_connected_clients{pod=\"$pod\"}, alias)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{pod=\"$pod\",alias=\"$alias\",namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(redis_connected_clients{pod=\"$pod\",alias=\"$alias\",namespace=\"$namespace\"}[$__interval_sx3])"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 \n* \n  (\n    avg_over_time(redis_memory_used_bytes{namespace=\"$namespace\", pod=\"$pod\",alias=\"$alias\"}[$__interval_sx3]) \n    / \n    avg_over_time(redis_memory_max_bytes{namespace=\"$namespace\",pod=\"$pod\",alias=\"$alias\"}[$__interval_sx3])\n  )"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{namespace=\"$namespace\",pod=\"$pod\",alias=\"$alias\"}[$__interval_sx4])",
     "legendFormat": "Commands processed total sec"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_keyspace_hits_total{namespace=\"$namespace\",pod=\"$pod\",alias=\"$alias\"}[$__interval_sx4])",
     "legendFormat": "hits"
    },
    {
     "expr": "rate(redis_keyspace_misses_total{namespace=\"$namespace\",pod=\"$pod\",alias=\"$alias\"}[$__interval_sx4])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(redis_memory_used_bytes{namespace=\"$namespace\",pod=\"$pod\",alias=\"$alias\"}[$__interval_sx3])",
     "legendFormat": "used"
    },
    {
     "expr": "avg_over_time(redis_memory_max_bytes{namespace=\"$namespace\",pod=\"$pod\",alias=\"$alias\"}[$__interval_sx3])",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{namespace=\"$namespace\",pod=\"$pod\",alias=\"$alias\"}[$__interval_sx4])",
     "legendFormat": "input"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{namespace=\"$namespace\",pod=\"$pod\",alias=\"$alias\"}[$__interval_sx4])",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (avg_over_time(redis_db_keys{namespace=\"$namespace\",pod=\"$pod\",alias=\"$alias\"}[$__interval_sx3])) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (avg_over_time(redis_db_keys{namespace=\"$namespace\",pod=\"$pod\",alias=\"$alias\"}[$__interval_sx3])) - sum (avg_over_time(redis_db_keys_expiring{namespace=\"$namespace\",pod=\"$pod\",alias=\"$alias\"}[$__interval_sx3])) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (avg_over_time(redis_db_keys_expiring{namespace=\"$namespace\",pod=\"$pod\",alias=\"$alias\"}[$__interval_sx3])) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{namespace=\"$namespace\",pod=\"$pod\",alias=\"$alias\"}[$__interval_sx4])) by (addr)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{namespace=\"$namespace\",pod=\"$pod\",alias=\"$alias\"}[$__interval_sx4])) by (addr)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(redis_command_call_duration_seconds_count{namespace=\"$namespace\",pod=\"$pod\",alias=\"$alias\"}[$__interval_sx4]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  }
 ]
}