{{- define "zvirt_ccm_args" -}}
- --cloud-provider=zvirt
- --allow-untagged-cloud=true
- --configure-cloud-routes=false
- --controllers=cloud-node,cloud-node-lifecycle
- --v=4
{{- end -}}

{{- define "zvirt_ccm_pdb_annotations" -}}
checksum/config: {{ printf "%s%s" (include (print $.Template.BasePath "/cloud-controller-manager/secret.yaml") . | toString) (include (print $.Template.BasePath "/secret.yaml") . | toString) | sha256sum }}
{{- end -}}

{{- define "zvirt_ccm_pod_annotations" -}}
checksum/config: {{ include (print $.Template.BasePath "/cloud-controller-manager/secret.yaml") . | sha256sum }}
{{- end -}}

{{- define "zvirt_ccm_envs" -}}
- name: ZVIRT_API_URL
  valueFrom:
    secretKeyRef:
      name: ccm-zvirt-credentials
      key: server
- name: ZVIRT_USERNAME
  valueFrom:
    secretKeyRef:
      name: ccm-zvirt-credentials
      key: username
- name: ZVIRT_PASSWORD
  valueFrom:
    secretKeyRef:
      name: ccm-zvirt-credentials
      key: password
- name: ZVIRT_INSECURE
  valueFrom:
    secretKeyRef:
      name: ccm-zvirt-credentials
      key: insecure
- name: ZVIRT_CA_BUNDLE
  valueFrom:
    secretKeyRef:
      name: ccm-zvirt-credentials
      key: caBundle
{{- end -}}

{{- $ccmConfig := dict -}}
{{- $_ := set $ccmConfig "fullname" "cloud-controller-manager" -}}
{{- $_ := set $ccmConfig "image" (include "helm_lib_module_image" (list . "cloudControllerManager")) -}}
{{- $_ := set $ccmConfig "containerName" "zvirt-cloud-controller-manager" -}}
{{- $_ := set $ccmConfig "additionalArgs" (include "zvirt_ccm_args" . | fromYamlArray) -}}
{{- $_ := set $ccmConfig "additionalEnvs" (include "zvirt_ccm_envs" . | fromYamlArray) -}}
{{- $_ := set $ccmConfig "additionalPodAnnotations" (include "zvirt_ccm_pod_annotations" . | fromYaml) -}}
{{- $_ := set $ccmConfig "additionalPDBAnnotations" (include "zvirt_ccm_pdb_annotations" . | fromYaml) -}}
{{- $_ := set $ccmConfig "vpaEnabled" true -}}
{{- $_ := set $ccmConfig "securityPolicyExceptionEnabled" true -}}

{{- include "helm_lib_cloud_controller_manager_manifests" (list . $ccmConfig) }}
