#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  jo -p configVersion=v1 onStartup=11
}

function __on_startup() {
  kubectl apply -f $(module::path)/crds/
  kubectl apply -f $(module::path)/candi/openapi/node_group.yaml
}

hook::run "$@"
