#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: kube_api_ep
      queue: /modules/$(module::name::kebab_case)
      group: main
      keepFullObjectsInMemory: false
      apiVersion: v1
      kind: Endpoints
      namespace:
        nameSelector:
          matchNames: [default]
      nameSelector:
        matchNames: [kubernetes]
      jqFilter: '[.subsets[] | "\(.addresses[].ip):\(.ports[].port)"]'
EOF
}

function __main__() {
  values::set nodeManager.internal.clusterMasterAddresses "$(context::get snapshots.kube_api_ep.0.filterResult)"
}

hook::run "$@"
