#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: cloud_provider_secret
      queue: /modules/$(module::name::kebab_case)
      includeSnapshotsFrom: [cloud_provider_secret]
      apiVersion: v1
      kind: Secret
      namespace:
        nameSelector:
          matchNames: [kube-system]
      nameSelector:
        matchNames: [d8-node-manager-cloud-provider]
      jqFilter: |
        (.data | [to_entries[] | (.value |= (. | @base64d))] | from_entries)
        +
        (.data | [to_entries[] | try(.value |= (. | @base64d | fromjson))] | from_entries)
EOF
}

function __on_kubernetes::cloud_provider_secret() {
  if context::has snapshots.cloud_provider_secret.0.filterResult; then
    values::set nodeManager.internal.cloudProvider "$(context::get snapshots.cloud_provider_secret.0.filterResult)"
  else
    values::unset nodeManager.internal.cloudProvider
  fi
}

hook::run "$@"
