#!/bin/bash

### Migration 23.10.2020: Remove in final `domain migration` release

source /deckhouse/shell_lib.sh

function __config__() {
  modules=$({ deckhouse-controller module list 2>/dev/null || echo ""; } | jq -Rr '. | [inputs | .[:-1]][:-1] + ["monitoring", "system", "frontend"] | join("|")')

  cat << EOF
    configVersion: v1
    kubernetes:
    - name: nodegroups
      group: main
      queue: /modules/$(module::name::kebab_case)
      apiVersion: deckhouse.io/v1alpha1
      kind: NodeGroup
      keepFullObjectsInMemory: false
      jqFilter: |
        if
        (
          [
            .spec.nodeTemplate.labels // {} | to_entries[] |
            select((.key | test("^node-role\\\.flant\\\.com/(${modules})$")) and .value == "")
          ] +
          [
            .spec.nodeTemplate.taints // [] | .[] |
            select(.key=="dedicated.flant.com" and (.value // "" | test("^(${modules}|)$")))
          ]
          | length > 0
        )
        then
        {
          "name": "migrate_domain_nodegroups",
          "group": "/modules/$(module::name::kebab_case)/migrate_domain_alert#migrate_domain_nodegroups",
          "set": 1,
          "labels":
          {
            "name": .metadata.name
          }
        }
        else null end
EOF
}

function __main__() {
  context::jq -c '.. | .filterResult? | select(.)' >> $METRICS_PATH
  # Used to hack metrics deletion
  group="/modules/$(module::name::kebab_case)/migrate_domain_alert#migrate_domain_nodegroups"
  jq -c --arg group "$group" '.group = $group' <<< '{"name": "migrate_domain_nodegroups", "set": 0, "labels": {"name": "none"}}' >> $METRICS_PATH
}

hook::run $@
