#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: mds
      group: main
      queue: /modules/$(module::name::kebab_case)
      apiVersion: machine.sapcloud.io/v1alpha1
      kind: MachineDeployment
      namespace:
        nameSelector:
          matchNames: [d8-cloud-instance-manager]
      jqFilter: |
        {
          "nodeGroup": .metadata.labels."node-group",
          "data": {
            "bashibleBundle": .spec.template.metadata.annotations."bashible-bundle",
            "bashibleChecksum": .spec.template.metadata.annotations."checksum/bashible-bundles-options",
            "machineClassChecksumBeforeMigration": .metadata.annotations."checksum/machine-class-before-migration"
          }
        }
EOF
}

function __main__() {
  values::set nodeManager.internal.bashibleChecksumMigration "$(context::jq -rc '
    [
      .snapshots.mds[] | select(.filterResult.data.bashibleChecksum != null) |
      {(.filterResult.nodeGroup): .filterResult.data}
    ] | add // {}
  ')"
}

hook::run "$@"
