#!/bin/bash

### Migration 23.10.2020: Remove in final `domain migration` release

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: nodegroups
      group: main
      queue: /modules/$(module::name::kebab_case)
      apiVersion: deckhouse.io/v1alpha1
      kind: NodeGroup
      keepFullObjectsInMemory: false
      jqFilter: |
        {
          "name": .metadata.name,
          "usedLabelsAndTaints":
            (
              [.spec.nodeTemplate.labels // {} | to_entries[] | select((.key | startswith("node-role.flant.com/")) and .value == "") | .key | split("/")[1] | select(. // empty)] +
              [.spec.nodeTemplate.taints // [] | .[] | select(.key=="dedicated.flant.com" and (.value // empty)) | .value]
            ) | unique
        }
EOF
}

function __main__() {
  reserved="$(values::get global.enabledModules | jq -r '. + ["monitoring", "system", "frontend"] | join("|")')"
  group="/modules/$(module::name::kebab_case)/migrate_domain_alert#migrate_domain_nodegroups"

  context::jq -c --arg reserved "$reserved" --arg group "$group" '
    .. | .filterResult? | select(.) |
    if ([.usedLabelsAndTaints[] | select(.| test("^(\($reserved))$"))] | length > 0) then
      {
        "name": "migrate_domain_nodegroups",
        "group": "\($group)",
        "set": 1,
        "labels":
        {
          "name": .name
        }
      }
    else empty end
    ' >> $METRICS_PATH

  # Used to hack metrics deletion
  jq -c --arg group "$group" '.group = $group' <<< '{"name": "migrate_domain_nodegroups", "set": 0, "labels": {"name": "none"}}' >> $METRICS_PATH
}

hook::run $@
