#!/bin/bash

# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 1
    kubernetes:
    - name: ngs
      group: main
      keepFullObjectsInMemory: true
      executeHookOnEvent: []
      executeHookOnSynchronization: false
      apiVersion: deckhouse.io/v1
      kind: NodeGroup
      jqFilter: |
        {
          "migrated" : (if .spec | has("disruptions") then true else false end)
        }
EOF
}

function __main__ {
  for i in $(context::jq -r '.snapshots.ngs | keys[]'); do
    if context::jq -er --argjson i "$i" '.snapshots.ngs[$i].filterResult.migrated == false' >/dev/null 2>&1; then
      ng_name="$(context::jq -r --argjson i "$i" '.snapshots.ngs[$i].object.metadata.name')"
      fltr='.|
        .spec.disruptions.approvalMode = (
          if .spec | has("allowDisruptions") then
            if .spec.allowDisruptions == true then
              "Automatic"
            else
              "Manual"
            end
          else
            "Automatic"
          end
        ) |
        del(.spec.allowDisruptions)
      '
      kubernetes::patch_jq "" "NodeGroup/$ng_name" "$fltr"
    fi
  done
}

hook::run "$@"
