#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: nodes
      queue: /modules/$(module::name::kebab_case)/unmanaged-nodes
      group: main
      keepFullObjectsInMemory: false
      waitForSynchronization: false
      apiVersion: v1
      kind: Node
      jqFilter: |
        {
          "name":                   .metadata.name,
          "hasNodeGroup":           (.metadata.labels | has("node.deckhouse.io/group")),
        }
EOF
}

function __main__() {
  echo '{"group":"node_manager_unmanaged_nodes", "action":"expire"}' >> "$METRICS_PATH"
  for node in $(context::jq -r '.snapshots.nodes[].filterResult | select(.hasNodeGroup == false) | .name'); do
    echo '{"name":"d8_unmanaged_nodes_on_cluster", "group":"node_manager_unmanaged_nodes", "labels": {"node": "'"$node"'"}, "set": 1}' >> "$METRICS_PATH"
  done
}

hook::run "$@"
