#!/bin/bash

# Copyright 2021 Flant JSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE

source /deckhouse/shell_lib.sh

function __main__() {
  enabled::disable_module_in_kubernetes_versions_less_than 1.15.0
  echo "true" > $MODULE_ENABLED_RESULT
}

enabled::run $@
