#!/bin/bash -e

### Миграция, 2018-03-24: https://github.com/deckhouse/deckhouse/merge_requests/130
if kubectl -n monitoring get ds/node-exporter > /dev/null 2> /dev/null ; then
  kubectl -n monitoring delete ds/node-exporter --grace-period=1
fi
if kubectl -n monitoring get prometheus/k8s > /dev/null 2> /dev/null && [[ "$(kubectl -n monitoring get prometheus/k8s -o json 2> /dev/null | jq '.spec.serviceMonitorSelector')" != "null" ]] ; then
  kubectl -n monitoring patch prometheus/k8s --type=json -p '[{"op": "remove", "path": "/spec/serviceMonitorSelector"}]'
  kubectl -n monitoring patch secret/prometheus-k8s -p '{"data":{"prometheus.yaml":"Cg=="}}' 
fi
