#!/bin/bash -e

### Миграция, 2018-03-29: https://github.com/deckhouse/deckhouse/merge_requests/165
for res in svc/kube-controller-manager-prometheus-discovery svc/kube-dns-prometheus-discovery svc/kube-scheduler-prometheus-discovery role/prometheus-k8s rolebinding/prometheus-k8s; do
  if kubectl -n kube-system get $res > /dev/null 2> /dev/null ; then
    kubectl -n kube-system delete $res
  fi
done
for res in svc/kube-nginx-ingress-bmlb-prometheus-discovery svc/kube-nginx-ingress-prometheus-discovery role/prometheus-k8s rolebinding/prometheus-k8s; do
  if kubectl -n kube-nginx-ingress get $res > /dev/null 2> /dev/null ; then
    kubectl -n kube-nginx-ingress delete $res
  fi
done
for res in role/prometheus-k8s rolebinding/prometheus-k8s; do
  if kubectl -n default get $res > /dev/null 2> /dev/null ; then
    kubectl -n default delete $res
  fi
done
if kubectl get ns/monitoring > /dev/null 2> /dev/null ; then
  kubectl delete ns monitoring
fi
