type: object
properties:
  storageClass:
    description: |
      > **Устарел**. Используйте параметр [settings.modules.storageClass](#parameters-modules-storageclass).

      Имя StorageClass, который будет использоваться для всех компонентов Deckhouse Kubernetes Platform (Prometheus, Grafana, OpenVPN и т. д.).

        * Если значение не указано, то используется [StorageClass по умолчанию](https://kubernetes.io/docs/concepts/storage/storage-classes/#default-storageclass), установленный в кластере.
        * Этот параметр имеет смысл использовать только в исключительных ситуациях.
        * Этот параметр применяется в процессе включения модуля.
  defaultClusterStorageClass:
    type: string
    default: null
    description: |-
      Имя StorageClass, который DKP определит как StorageClass используемый в кластере по умолчанию.

      DKP запрещает вручную добавлять или изменять default-аннотацию (`storageclass.kubernetes.io/is-default-class='true'`) у StorageClass. Используйте параметр, чтобы определять или изменять StorageClass используемый в кластере по умолчанию.

      Если значение не указано, фактический StorageClass используемый в кластере по умолчанию будет определяться в следующем порядке:

       * StorageClass в кластере, имеющий default-аннотацию (`storageclass.kubernetes.io/is-default-class='true'`);
       * Первый (по алфавиту) StorageClass из создаваемых модулем облачного провайдера (если какой-либо модуль облачного провайдера используется).
  highAvailability:
    description: |
      Параметр глобального включения *режима отказоустойчивости* для модулей, которые его поддерживают.

      Если значение не указано, оно определяется автоматически как `true` для кластеров с более чем одним master-узлом. В остальных случаях значение определяется как `false`.
  modules:
    description: |
      Общие параметры модулей Deckhouse.
    properties:
      gatewayAPIGateway:
        description: |
          Имя объекта Gateway из Gateway API, используемого для модулей экосистемы Deckhouse.
      ingressClass:
        description: |
          Имя класса Ingress-контроллера ([IngressClass](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class)), используемого модулями экосистемы Deckhouse.

          Если в качестве имени IngressClass указано значение `nginx`, соответствующий Ingress-контроллер автоматически считается Ingress-контроллером по умолчанию для всех модулей.

          При использовании любого другого имени IngressClass такой Ingress-контроллер не будет использоваться по умолчанию.
      publicDomainTemplate:
        description: |
          Шаблон DNS-имен c ключом `%s` в качестве динамической части строки.

          Модули Deckhouse используют этот шаблон при создании Ingress-ресурсов.

          Например, для шаблона `%s.kube.company.my` модуль prometheus создаст Ingress-ресурс на адрес `grafana.kube.company.my` для доступа к Grafana.

          **Обратите внимание:**
          - Если параметр не указан, Ingress-ресурсы создаваться не будут.
          - Домен, указанный в шаблоне, не может совпадать или быть поддоменом домена, заданного в параметре [`clusterDomain`](/products/kubernetes-platform/documentation/v1/reference/api/cr.html#clusterconfiguration-clusterdomain). Мы не рекомендуем менять значение `clusterDomain` без особой необходимости.
          - Для корректной работы шаблона необходимо предварительно настроить службы DNS как в сетях, где будут располагаться узлы кластера, так и в сетях, из которых к служебным веб-интерфейсам платформы будут обращаться клиенты.
          - В случае, если шаблон совпадает с доменом сети узлов, используйте только А записи для назначения служебным веб-интерфейсам платформы адресов Frontend узлов. Например, для узлов заведена зона `company.my`, а шаблон имеет вид `%s.company.my`.
      placement:
        description: |
          Настройки, определяющие расположение компонентов модулей Deckhouse по умолчанию.
        properties:
          customTolerationKeys:
            description: |
              Список ключей пользовательских toleration.

              Необходимо указывать, чтобы позволить планировщику размещать критически важные компоненты Deckhouse, такие как cni и csi, на выделенных узлах.
      https:
        description: |
          Способ организации доступа по протоколу HTTPS для модулей экосистемы Deckhouse.
        properties:
          mode:
            description: |
              Режим работы HTTPS:

              * `CertManager` — модули работают по HTTPS и самостоятельно заказывают сертификаты с помощью ClusterIssuer, указанного [в параметре `certManager.clusterIssuerName`](#parameters-modules-https-certmanager-clusterissuername);
              * `CustomCertificate` — модули работают по HTTPS, используя сертификат из неймспейса `d8-system`;
              * `Disabled` — модули работают только по HTTP (при этом некоторые модули могут не работать — например, [`user-authn`](/modules/user-authn/));
              * `OnlyInURI` — модули работают по HTTP, подразумевая, что перед ними стоит внешний HTTPS-балансировщик, который терминирует HTTPS. Такой балансировщик должен обеспечивать перенаправление запросов с HTTP на HTTPS.
          certManager:
            properties:
              clusterIssuerName:
                description: |
                  Имя ClusterIssuer, используемого модулями для получения TLS-сертификатов.

                  Модуль [`cert-manager`](/modules/cert-manager/) предоставляет следующие ClusterIssuer: 

                  - `letsencrypt`;
                  - `letsencrypt-staging`;
                  - `selfsigned`;
                  - `clouddns`;
                  - `cloudflare`;
                  - `digitalocean`;
                  - `route53`.
                  
                  При необходимости вы можете использовать собственный `ClusterIssuer`.
          customCertificate:
            properties:
              secretName:
                description: |
                  Имя Secret в неймспейсе `d8-system`, содержащего TLS-сертификат, который будет использоваться модулями.

                  Указанный Secret должен быть в формате [`kubernetes.io/tls`](https://kubernetes.github.io/ingress-nginx/user-guide/tls/#tls-secrets).
      resourcesRequests:
        description: |
          Количество ресурсов (CPU и памяти), выделяемых для работы некоторых компонентов.

          [Подробнее](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-units-in-kubernetes) про единицы измерения ресурсов.
        properties:
          controlPlane:
            description: |
              > **Устарело**. Вместо этого используйте параметр `.spec.settings.resourcesRequests` в конфигурации модуля `control-plane-manager`.

              Объём ресурсов (CPU и памяти), выделяемых для компонентов control plane на каждом master-узле кластера.

              Настройки не применяются, если control plane кластера управляется облачным провайдером (например, Google Kubernetes Engine или Azure Kubernetes Service).
            properties:
              cpu:
                description: |
                  > **Устарело**. Вместо этого используйте параметр `controlPlaneManager.spec.settings.resourcesRequests.cpu`.

                  Количество CPU, выделяемых для компонентов control plane, работающих на каждом master-узле кластера.
              memory:
                description: |
                  > **Устарело**. Вместо этого используйте параметр `controlPlaneManager.spec.settings.resourcesRequests.memory`.

                  Объем памяти, выделяемой для компонентов control plane, работающих на каждом master-узле кластера.
      storageClass:
        description: |
          Имя StorageClass, который будет использоваться для всех компонентов Deckhouse Kubernetes Platform (Prometheus, Grafana, OpenVPN и т. д.).

            * Если значение не указано, то используется [StorageClass по умолчанию](https://kubernetes.io/docs/concepts/storage/storage-classes/#default-storageclass), установленный в кластере.
            * Этот параметр имеет смысл использовать только в исключительных ситуациях.
            * Этот параметр применяется в процессе включения модуля.
  applications:
    description: |
      Общие параметры приложений экосистемы Deckhouse.
    properties:
      ingressClass:
        description: |
          Имя класса Ingress-контроллера ([IngressClass](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class)), используемого приложениями экосистемы Deckhouse.

          Если в качестве имени IngressClass указано значение `nginx`, соответствующий Ingress-контроллер автоматически считается Ingress-контроллером по умолчанию для всех приложений.

          При использовании любого другого имени IngressClass такой Ingress-контроллер не будет использоваться по умолчанию.
      publicDomainTemplate:
        description: |
          Шаблон DNS-имён с тремя ключами `%s` в качестве динамических частей строки.
          
          При формировании DNS-имени:
          
          - первый ключ заменяется на имя компонента;
          - второй — на имя экземпляра приложения;
          - третий — на имя неймспейса приложения.

          Приложения экосистемы Deckhouse используют этот шаблон при создании Ingress-ресурсов.

          Например, для шаблона `%s.%s.%s.kube.company.my` компонент `web` экземпляра приложения `grafana`, работающего в неймспейсе `monitoring`, получит Ingress-ресурс на адрес `web.grafana.monitoring.kube.company.my`.

          **Особенности использования:**

          - Если параметр не указан, Ingress-ресурсы создаваться не будут.
          - Домен, указанный в шаблоне, не может совпадать или быть поддоменом домена, заданного в параметре [`clusterDomain`](cr.html#clusterconfiguration-clusterdomain). Не рекомендуется изменять значение `clusterDomain` без необходимости.
          - Перед использованием шаблона настройте службы DNS как в сетях, где будут располагаться узлы кластера, так и в сетях, из которых клиенты будут обращаться к служебным веб-интерфейсам.
          - Если домен шаблона совпадает с доменом сети узлов, используйте только А-записи для назначения служебным веб-интерфейсам платформы адресов frontend-узлов. Например, если для узлов заведена зона `company.my`, шаблон должен иметь вид `%s.%s.%s.company.my`.
      https:
        description: |
          Способ организации доступа по протоколу HTTPS для приложений экосистемы Deckhouse.
        properties:
          mode:
            description: |
              Режим работы HTTPS:

              * `CertManager` — приложения работают по HTTPS и самостоятельно заказывают сертификаты с помощью ClusterIssuer, указанного [в параметре `certManager.clusterIssuerName`](#parameters-applications-https-certmanager-clusterissuername);
              * `CustomCertificate` — приложения работают по HTTPS, используя сертификат из неймспейса `d8-system`;
              * `Disabled` — приложения работают только по HTTP;
              * `OnlyInURI` — приложения работают по HTTP, подразумевая, что перед ними стоит внешний HTTPS-балансировщик, который терминирует HTTPS. Балансировщик должен обеспечивать перенаправление запросов с HTTP на HTTPS.
          certManager:
            properties:
              clusterIssuerName:
                description: |
                  Имя ClusterIssuer, используемого приложениями для получения TLS-сертификатов.

                  Модуль [`cert-manager`](/modules/cert-manager/) предоставляет следующие ClusterIssuer:

                  - `letsencrypt`;
                  - `letsencrypt-staging`;
                  - `selfsigned`;
                  - `clouddns`;
                  - `cloudflare`;
                  - `digitalocean`;
                  - `route53`.

                  При необходимости вы можете использовать собственный ClusterIssuer.
          customCertificate:
            properties:
              secretName:
                description: |
                  Имя Secret в неймспейсе `d8-system`, содержащего TLS-сертификат, который будет использоваться приложениями.

                  Указанный Secret должен быть в формате [`kubernetes.io/tls`](https://kubernetes.github.io/ingress-nginx/user-guide/tls/#tls-secrets).
