// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package bootstrapped

//go:generate minimock -i github.com/deckhouse/deckhouse/go_lib/dependency/extenders/bootstrapped.IExtender -o extender_mock.go -n IExtenderMock -p bootstrapped

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/flant/addon-operator/pkg/module_manager/scheduler/extenders"
	"github.com/gojuno/minimock/v3"
)

// IExtenderMock implements IExtender
type IExtenderMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcAddFunctionalModule          func(moduleName string)
	funcAddFunctionalModuleOrigin    string
	inspectFuncAddFunctionalModule   func(moduleName string)
	afterAddFunctionalModuleCounter  uint64
	beforeAddFunctionalModuleCounter uint64
	AddFunctionalModuleMock          mIExtenderMockAddFunctionalModule

	funcFilter          func(moduleName string, logLabels map[string]string) (bp1 *bool, err error)
	funcFilterOrigin    string
	inspectFuncFilter   func(moduleName string, logLabels map[string]string)
	afterFilterCounter  uint64
	beforeFilterCounter uint64
	FilterMock          mIExtenderMockFilter

	funcIsTerminator          func() (b1 bool)
	funcIsTerminatorOrigin    string
	inspectFuncIsTerminator   func()
	afterIsTerminatorCounter  uint64
	beforeIsTerminatorCounter uint64
	IsTerminatorMock          mIExtenderMockIsTerminator

	funcName          func() (e1 extenders.ExtenderName)
	funcNameOrigin    string
	inspectFuncName   func()
	afterNameCounter  uint64
	beforeNameCounter uint64
	NameMock          mIExtenderMockName
}

// NewIExtenderMock returns a mock for IExtender
func NewIExtenderMock(t minimock.Tester) *IExtenderMock {
	m := &IExtenderMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AddFunctionalModuleMock = mIExtenderMockAddFunctionalModule{mock: m}
	m.AddFunctionalModuleMock.callArgs = []*IExtenderMockAddFunctionalModuleParams{}

	m.FilterMock = mIExtenderMockFilter{mock: m}
	m.FilterMock.callArgs = []*IExtenderMockFilterParams{}

	m.IsTerminatorMock = mIExtenderMockIsTerminator{mock: m}

	m.NameMock = mIExtenderMockName{mock: m}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mIExtenderMockAddFunctionalModule struct {
	optional           bool
	mock               *IExtenderMock
	defaultExpectation *IExtenderMockAddFunctionalModuleExpectation
	expectations       []*IExtenderMockAddFunctionalModuleExpectation

	callArgs []*IExtenderMockAddFunctionalModuleParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// IExtenderMockAddFunctionalModuleExpectation specifies expectation struct of the IExtender.AddFunctionalModule
type IExtenderMockAddFunctionalModuleExpectation struct {
	mock               *IExtenderMock
	params             *IExtenderMockAddFunctionalModuleParams
	paramPtrs          *IExtenderMockAddFunctionalModuleParamPtrs
	expectationOrigins IExtenderMockAddFunctionalModuleExpectationOrigins

	returnOrigin string
	Counter      uint64
}

// IExtenderMockAddFunctionalModuleParams contains parameters of the IExtender.AddFunctionalModule
type IExtenderMockAddFunctionalModuleParams struct {
	moduleName string
}

// IExtenderMockAddFunctionalModuleParamPtrs contains pointers to parameters of the IExtender.AddFunctionalModule
type IExtenderMockAddFunctionalModuleParamPtrs struct {
	moduleName *string
}

// IExtenderMockAddFunctionalModuleOrigins contains origins of expectations of the IExtender.AddFunctionalModule
type IExtenderMockAddFunctionalModuleExpectationOrigins struct {
	origin           string
	originModuleName string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmAddFunctionalModule *mIExtenderMockAddFunctionalModule) Optional() *mIExtenderMockAddFunctionalModule {
	mmAddFunctionalModule.optional = true
	return mmAddFunctionalModule
}

// Expect sets up expected params for IExtender.AddFunctionalModule
func (mmAddFunctionalModule *mIExtenderMockAddFunctionalModule) Expect(moduleName string) *mIExtenderMockAddFunctionalModule {
	if mmAddFunctionalModule.mock.funcAddFunctionalModule != nil {
		mmAddFunctionalModule.mock.t.Fatalf("IExtenderMock.AddFunctionalModule mock is already set by Set")
	}

	if mmAddFunctionalModule.defaultExpectation == nil {
		mmAddFunctionalModule.defaultExpectation = &IExtenderMockAddFunctionalModuleExpectation{}
	}

	if mmAddFunctionalModule.defaultExpectation.paramPtrs != nil {
		mmAddFunctionalModule.mock.t.Fatalf("IExtenderMock.AddFunctionalModule mock is already set by ExpectParams functions")
	}

	mmAddFunctionalModule.defaultExpectation.params = &IExtenderMockAddFunctionalModuleParams{moduleName}
	mmAddFunctionalModule.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmAddFunctionalModule.expectations {
		if minimock.Equal(e.params, mmAddFunctionalModule.defaultExpectation.params) {
			mmAddFunctionalModule.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAddFunctionalModule.defaultExpectation.params)
		}
	}

	return mmAddFunctionalModule
}

// ExpectModuleNameParam1 sets up expected param moduleName for IExtender.AddFunctionalModule
func (mmAddFunctionalModule *mIExtenderMockAddFunctionalModule) ExpectModuleNameParam1(moduleName string) *mIExtenderMockAddFunctionalModule {
	if mmAddFunctionalModule.mock.funcAddFunctionalModule != nil {
		mmAddFunctionalModule.mock.t.Fatalf("IExtenderMock.AddFunctionalModule mock is already set by Set")
	}

	if mmAddFunctionalModule.defaultExpectation == nil {
		mmAddFunctionalModule.defaultExpectation = &IExtenderMockAddFunctionalModuleExpectation{}
	}

	if mmAddFunctionalModule.defaultExpectation.params != nil {
		mmAddFunctionalModule.mock.t.Fatalf("IExtenderMock.AddFunctionalModule mock is already set by Expect")
	}

	if mmAddFunctionalModule.defaultExpectation.paramPtrs == nil {
		mmAddFunctionalModule.defaultExpectation.paramPtrs = &IExtenderMockAddFunctionalModuleParamPtrs{}
	}
	mmAddFunctionalModule.defaultExpectation.paramPtrs.moduleName = &moduleName
	mmAddFunctionalModule.defaultExpectation.expectationOrigins.originModuleName = minimock.CallerInfo(1)

	return mmAddFunctionalModule
}

// Inspect accepts an inspector function that has same arguments as the IExtender.AddFunctionalModule
func (mmAddFunctionalModule *mIExtenderMockAddFunctionalModule) Inspect(f func(moduleName string)) *mIExtenderMockAddFunctionalModule {
	if mmAddFunctionalModule.mock.inspectFuncAddFunctionalModule != nil {
		mmAddFunctionalModule.mock.t.Fatalf("Inspect function is already set for IExtenderMock.AddFunctionalModule")
	}

	mmAddFunctionalModule.mock.inspectFuncAddFunctionalModule = f

	return mmAddFunctionalModule
}

// Return sets up results that will be returned by IExtender.AddFunctionalModule
func (mmAddFunctionalModule *mIExtenderMockAddFunctionalModule) Return() *IExtenderMock {
	if mmAddFunctionalModule.mock.funcAddFunctionalModule != nil {
		mmAddFunctionalModule.mock.t.Fatalf("IExtenderMock.AddFunctionalModule mock is already set by Set")
	}

	if mmAddFunctionalModule.defaultExpectation == nil {
		mmAddFunctionalModule.defaultExpectation = &IExtenderMockAddFunctionalModuleExpectation{mock: mmAddFunctionalModule.mock}
	}

	mmAddFunctionalModule.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmAddFunctionalModule.mock
}

// Set uses given function f to mock the IExtender.AddFunctionalModule method
func (mmAddFunctionalModule *mIExtenderMockAddFunctionalModule) Set(f func(moduleName string)) *IExtenderMock {
	if mmAddFunctionalModule.defaultExpectation != nil {
		mmAddFunctionalModule.mock.t.Fatalf("Default expectation is already set for the IExtender.AddFunctionalModule method")
	}

	if len(mmAddFunctionalModule.expectations) > 0 {
		mmAddFunctionalModule.mock.t.Fatalf("Some expectations are already set for the IExtender.AddFunctionalModule method")
	}

	mmAddFunctionalModule.mock.funcAddFunctionalModule = f
	mmAddFunctionalModule.mock.funcAddFunctionalModuleOrigin = minimock.CallerInfo(1)
	return mmAddFunctionalModule.mock
}

// When sets expectation for the IExtender.AddFunctionalModule which will trigger the result defined by the following
// Then helper
func (mmAddFunctionalModule *mIExtenderMockAddFunctionalModule) When(moduleName string) *IExtenderMockAddFunctionalModuleExpectation {
	if mmAddFunctionalModule.mock.funcAddFunctionalModule != nil {
		mmAddFunctionalModule.mock.t.Fatalf("IExtenderMock.AddFunctionalModule mock is already set by Set")
	}

	expectation := &IExtenderMockAddFunctionalModuleExpectation{
		mock:               mmAddFunctionalModule.mock,
		params:             &IExtenderMockAddFunctionalModuleParams{moduleName},
		expectationOrigins: IExtenderMockAddFunctionalModuleExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmAddFunctionalModule.expectations = append(mmAddFunctionalModule.expectations, expectation)
	return expectation
}

// Then sets up IExtender.AddFunctionalModule return parameters for the expectation previously defined by the When method

func (e *IExtenderMockAddFunctionalModuleExpectation) Then() *IExtenderMock {
	return e.mock
}

// Times sets number of times IExtender.AddFunctionalModule should be invoked
func (mmAddFunctionalModule *mIExtenderMockAddFunctionalModule) Times(n uint64) *mIExtenderMockAddFunctionalModule {
	if n == 0 {
		mmAddFunctionalModule.mock.t.Fatalf("Times of IExtenderMock.AddFunctionalModule mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmAddFunctionalModule.expectedInvocations, n)
	mmAddFunctionalModule.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmAddFunctionalModule
}

func (mmAddFunctionalModule *mIExtenderMockAddFunctionalModule) invocationsDone() bool {
	if len(mmAddFunctionalModule.expectations) == 0 && mmAddFunctionalModule.defaultExpectation == nil && mmAddFunctionalModule.mock.funcAddFunctionalModule == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmAddFunctionalModule.mock.afterAddFunctionalModuleCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmAddFunctionalModule.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// AddFunctionalModule implements IExtender
func (mmAddFunctionalModule *IExtenderMock) AddFunctionalModule(moduleName string) {
	mm_atomic.AddUint64(&mmAddFunctionalModule.beforeAddFunctionalModuleCounter, 1)
	defer mm_atomic.AddUint64(&mmAddFunctionalModule.afterAddFunctionalModuleCounter, 1)

	mmAddFunctionalModule.t.Helper()

	if mmAddFunctionalModule.inspectFuncAddFunctionalModule != nil {
		mmAddFunctionalModule.inspectFuncAddFunctionalModule(moduleName)
	}

	mm_params := IExtenderMockAddFunctionalModuleParams{moduleName}

	// Record call args
	mmAddFunctionalModule.AddFunctionalModuleMock.mutex.Lock()
	mmAddFunctionalModule.AddFunctionalModuleMock.callArgs = append(mmAddFunctionalModule.AddFunctionalModuleMock.callArgs, &mm_params)
	mmAddFunctionalModule.AddFunctionalModuleMock.mutex.Unlock()

	for _, e := range mmAddFunctionalModule.AddFunctionalModuleMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmAddFunctionalModule.AddFunctionalModuleMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAddFunctionalModule.AddFunctionalModuleMock.defaultExpectation.Counter, 1)
		mm_want := mmAddFunctionalModule.AddFunctionalModuleMock.defaultExpectation.params
		mm_want_ptrs := mmAddFunctionalModule.AddFunctionalModuleMock.defaultExpectation.paramPtrs

		mm_got := IExtenderMockAddFunctionalModuleParams{moduleName}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.moduleName != nil && !minimock.Equal(*mm_want_ptrs.moduleName, mm_got.moduleName) {
				mmAddFunctionalModule.t.Errorf("IExtenderMock.AddFunctionalModule got unexpected parameter moduleName, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAddFunctionalModule.AddFunctionalModuleMock.defaultExpectation.expectationOrigins.originModuleName, *mm_want_ptrs.moduleName, mm_got.moduleName, minimock.Diff(*mm_want_ptrs.moduleName, mm_got.moduleName))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAddFunctionalModule.t.Errorf("IExtenderMock.AddFunctionalModule got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmAddFunctionalModule.AddFunctionalModuleMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		return

	}
	if mmAddFunctionalModule.funcAddFunctionalModule != nil {
		mmAddFunctionalModule.funcAddFunctionalModule(moduleName)
		return
	}
	mmAddFunctionalModule.t.Fatalf("Unexpected call to IExtenderMock.AddFunctionalModule. %v", moduleName)

}

// AddFunctionalModuleAfterCounter returns a count of finished IExtenderMock.AddFunctionalModule invocations
func (mmAddFunctionalModule *IExtenderMock) AddFunctionalModuleAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddFunctionalModule.afterAddFunctionalModuleCounter)
}

// AddFunctionalModuleBeforeCounter returns a count of IExtenderMock.AddFunctionalModule invocations
func (mmAddFunctionalModule *IExtenderMock) AddFunctionalModuleBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddFunctionalModule.beforeAddFunctionalModuleCounter)
}

// Calls returns a list of arguments used in each call to IExtenderMock.AddFunctionalModule.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAddFunctionalModule *mIExtenderMockAddFunctionalModule) Calls() []*IExtenderMockAddFunctionalModuleParams {
	mmAddFunctionalModule.mutex.RLock()

	argCopy := make([]*IExtenderMockAddFunctionalModuleParams, len(mmAddFunctionalModule.callArgs))
	copy(argCopy, mmAddFunctionalModule.callArgs)

	mmAddFunctionalModule.mutex.RUnlock()

	return argCopy
}

// MinimockAddFunctionalModuleDone returns true if the count of the AddFunctionalModule invocations corresponds
// the number of defined expectations
func (m *IExtenderMock) MinimockAddFunctionalModuleDone() bool {
	if m.AddFunctionalModuleMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.AddFunctionalModuleMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.AddFunctionalModuleMock.invocationsDone()
}

// MinimockAddFunctionalModuleInspect logs each unmet expectation
func (m *IExtenderMock) MinimockAddFunctionalModuleInspect() {
	for _, e := range m.AddFunctionalModuleMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to IExtenderMock.AddFunctionalModule at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterAddFunctionalModuleCounter := mm_atomic.LoadUint64(&m.afterAddFunctionalModuleCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.AddFunctionalModuleMock.defaultExpectation != nil && afterAddFunctionalModuleCounter < 1 {
		if m.AddFunctionalModuleMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to IExtenderMock.AddFunctionalModule at\n%s", m.AddFunctionalModuleMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to IExtenderMock.AddFunctionalModule at\n%s with params: %#v", m.AddFunctionalModuleMock.defaultExpectation.expectationOrigins.origin, *m.AddFunctionalModuleMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAddFunctionalModule != nil && afterAddFunctionalModuleCounter < 1 {
		m.t.Errorf("Expected call to IExtenderMock.AddFunctionalModule at\n%s", m.funcAddFunctionalModuleOrigin)
	}

	if !m.AddFunctionalModuleMock.invocationsDone() && afterAddFunctionalModuleCounter > 0 {
		m.t.Errorf("Expected %d calls to IExtenderMock.AddFunctionalModule at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.AddFunctionalModuleMock.expectedInvocations), m.AddFunctionalModuleMock.expectedInvocationsOrigin, afterAddFunctionalModuleCounter)
	}
}

type mIExtenderMockFilter struct {
	optional           bool
	mock               *IExtenderMock
	defaultExpectation *IExtenderMockFilterExpectation
	expectations       []*IExtenderMockFilterExpectation

	callArgs []*IExtenderMockFilterParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// IExtenderMockFilterExpectation specifies expectation struct of the IExtender.Filter
type IExtenderMockFilterExpectation struct {
	mock               *IExtenderMock
	params             *IExtenderMockFilterParams
	paramPtrs          *IExtenderMockFilterParamPtrs
	expectationOrigins IExtenderMockFilterExpectationOrigins
	results            *IExtenderMockFilterResults
	returnOrigin       string
	Counter            uint64
}

// IExtenderMockFilterParams contains parameters of the IExtender.Filter
type IExtenderMockFilterParams struct {
	moduleName string
	logLabels  map[string]string
}

// IExtenderMockFilterParamPtrs contains pointers to parameters of the IExtender.Filter
type IExtenderMockFilterParamPtrs struct {
	moduleName *string
	logLabels  *map[string]string
}

// IExtenderMockFilterResults contains results of the IExtender.Filter
type IExtenderMockFilterResults struct {
	bp1 *bool
	err error
}

// IExtenderMockFilterOrigins contains origins of expectations of the IExtender.Filter
type IExtenderMockFilterExpectationOrigins struct {
	origin           string
	originModuleName string
	originLogLabels  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmFilter *mIExtenderMockFilter) Optional() *mIExtenderMockFilter {
	mmFilter.optional = true
	return mmFilter
}

// Expect sets up expected params for IExtender.Filter
func (mmFilter *mIExtenderMockFilter) Expect(moduleName string, logLabels map[string]string) *mIExtenderMockFilter {
	if mmFilter.mock.funcFilter != nil {
		mmFilter.mock.t.Fatalf("IExtenderMock.Filter mock is already set by Set")
	}

	if mmFilter.defaultExpectation == nil {
		mmFilter.defaultExpectation = &IExtenderMockFilterExpectation{}
	}

	if mmFilter.defaultExpectation.paramPtrs != nil {
		mmFilter.mock.t.Fatalf("IExtenderMock.Filter mock is already set by ExpectParams functions")
	}

	mmFilter.defaultExpectation.params = &IExtenderMockFilterParams{moduleName, logLabels}
	mmFilter.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmFilter.expectations {
		if minimock.Equal(e.params, mmFilter.defaultExpectation.params) {
			mmFilter.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmFilter.defaultExpectation.params)
		}
	}

	return mmFilter
}

// ExpectModuleNameParam1 sets up expected param moduleName for IExtender.Filter
func (mmFilter *mIExtenderMockFilter) ExpectModuleNameParam1(moduleName string) *mIExtenderMockFilter {
	if mmFilter.mock.funcFilter != nil {
		mmFilter.mock.t.Fatalf("IExtenderMock.Filter mock is already set by Set")
	}

	if mmFilter.defaultExpectation == nil {
		mmFilter.defaultExpectation = &IExtenderMockFilterExpectation{}
	}

	if mmFilter.defaultExpectation.params != nil {
		mmFilter.mock.t.Fatalf("IExtenderMock.Filter mock is already set by Expect")
	}

	if mmFilter.defaultExpectation.paramPtrs == nil {
		mmFilter.defaultExpectation.paramPtrs = &IExtenderMockFilterParamPtrs{}
	}
	mmFilter.defaultExpectation.paramPtrs.moduleName = &moduleName
	mmFilter.defaultExpectation.expectationOrigins.originModuleName = minimock.CallerInfo(1)

	return mmFilter
}

// ExpectLogLabelsParam2 sets up expected param logLabels for IExtender.Filter
func (mmFilter *mIExtenderMockFilter) ExpectLogLabelsParam2(logLabels map[string]string) *mIExtenderMockFilter {
	if mmFilter.mock.funcFilter != nil {
		mmFilter.mock.t.Fatalf("IExtenderMock.Filter mock is already set by Set")
	}

	if mmFilter.defaultExpectation == nil {
		mmFilter.defaultExpectation = &IExtenderMockFilterExpectation{}
	}

	if mmFilter.defaultExpectation.params != nil {
		mmFilter.mock.t.Fatalf("IExtenderMock.Filter mock is already set by Expect")
	}

	if mmFilter.defaultExpectation.paramPtrs == nil {
		mmFilter.defaultExpectation.paramPtrs = &IExtenderMockFilterParamPtrs{}
	}
	mmFilter.defaultExpectation.paramPtrs.logLabels = &logLabels
	mmFilter.defaultExpectation.expectationOrigins.originLogLabels = minimock.CallerInfo(1)

	return mmFilter
}

// Inspect accepts an inspector function that has same arguments as the IExtender.Filter
func (mmFilter *mIExtenderMockFilter) Inspect(f func(moduleName string, logLabels map[string]string)) *mIExtenderMockFilter {
	if mmFilter.mock.inspectFuncFilter != nil {
		mmFilter.mock.t.Fatalf("Inspect function is already set for IExtenderMock.Filter")
	}

	mmFilter.mock.inspectFuncFilter = f

	return mmFilter
}

// Return sets up results that will be returned by IExtender.Filter
func (mmFilter *mIExtenderMockFilter) Return(bp1 *bool, err error) *IExtenderMock {
	if mmFilter.mock.funcFilter != nil {
		mmFilter.mock.t.Fatalf("IExtenderMock.Filter mock is already set by Set")
	}

	if mmFilter.defaultExpectation == nil {
		mmFilter.defaultExpectation = &IExtenderMockFilterExpectation{mock: mmFilter.mock}
	}
	mmFilter.defaultExpectation.results = &IExtenderMockFilterResults{bp1, err}
	mmFilter.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmFilter.mock
}

// Set uses given function f to mock the IExtender.Filter method
func (mmFilter *mIExtenderMockFilter) Set(f func(moduleName string, logLabels map[string]string) (bp1 *bool, err error)) *IExtenderMock {
	if mmFilter.defaultExpectation != nil {
		mmFilter.mock.t.Fatalf("Default expectation is already set for the IExtender.Filter method")
	}

	if len(mmFilter.expectations) > 0 {
		mmFilter.mock.t.Fatalf("Some expectations are already set for the IExtender.Filter method")
	}

	mmFilter.mock.funcFilter = f
	mmFilter.mock.funcFilterOrigin = minimock.CallerInfo(1)
	return mmFilter.mock
}

// When sets expectation for the IExtender.Filter which will trigger the result defined by the following
// Then helper
func (mmFilter *mIExtenderMockFilter) When(moduleName string, logLabels map[string]string) *IExtenderMockFilterExpectation {
	if mmFilter.mock.funcFilter != nil {
		mmFilter.mock.t.Fatalf("IExtenderMock.Filter mock is already set by Set")
	}

	expectation := &IExtenderMockFilterExpectation{
		mock:               mmFilter.mock,
		params:             &IExtenderMockFilterParams{moduleName, logLabels},
		expectationOrigins: IExtenderMockFilterExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmFilter.expectations = append(mmFilter.expectations, expectation)
	return expectation
}

// Then sets up IExtender.Filter return parameters for the expectation previously defined by the When method
func (e *IExtenderMockFilterExpectation) Then(bp1 *bool, err error) *IExtenderMock {
	e.results = &IExtenderMockFilterResults{bp1, err}
	return e.mock
}

// Times sets number of times IExtender.Filter should be invoked
func (mmFilter *mIExtenderMockFilter) Times(n uint64) *mIExtenderMockFilter {
	if n == 0 {
		mmFilter.mock.t.Fatalf("Times of IExtenderMock.Filter mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmFilter.expectedInvocations, n)
	mmFilter.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmFilter
}

func (mmFilter *mIExtenderMockFilter) invocationsDone() bool {
	if len(mmFilter.expectations) == 0 && mmFilter.defaultExpectation == nil && mmFilter.mock.funcFilter == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmFilter.mock.afterFilterCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmFilter.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Filter implements IExtender
func (mmFilter *IExtenderMock) Filter(moduleName string, logLabels map[string]string) (bp1 *bool, err error) {
	mm_atomic.AddUint64(&mmFilter.beforeFilterCounter, 1)
	defer mm_atomic.AddUint64(&mmFilter.afterFilterCounter, 1)

	mmFilter.t.Helper()

	if mmFilter.inspectFuncFilter != nil {
		mmFilter.inspectFuncFilter(moduleName, logLabels)
	}

	mm_params := IExtenderMockFilterParams{moduleName, logLabels}

	// Record call args
	mmFilter.FilterMock.mutex.Lock()
	mmFilter.FilterMock.callArgs = append(mmFilter.FilterMock.callArgs, &mm_params)
	mmFilter.FilterMock.mutex.Unlock()

	for _, e := range mmFilter.FilterMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.bp1, e.results.err
		}
	}

	if mmFilter.FilterMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmFilter.FilterMock.defaultExpectation.Counter, 1)
		mm_want := mmFilter.FilterMock.defaultExpectation.params
		mm_want_ptrs := mmFilter.FilterMock.defaultExpectation.paramPtrs

		mm_got := IExtenderMockFilterParams{moduleName, logLabels}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.moduleName != nil && !minimock.Equal(*mm_want_ptrs.moduleName, mm_got.moduleName) {
				mmFilter.t.Errorf("IExtenderMock.Filter got unexpected parameter moduleName, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmFilter.FilterMock.defaultExpectation.expectationOrigins.originModuleName, *mm_want_ptrs.moduleName, mm_got.moduleName, minimock.Diff(*mm_want_ptrs.moduleName, mm_got.moduleName))
			}

			if mm_want_ptrs.logLabels != nil && !minimock.Equal(*mm_want_ptrs.logLabels, mm_got.logLabels) {
				mmFilter.t.Errorf("IExtenderMock.Filter got unexpected parameter logLabels, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmFilter.FilterMock.defaultExpectation.expectationOrigins.originLogLabels, *mm_want_ptrs.logLabels, mm_got.logLabels, minimock.Diff(*mm_want_ptrs.logLabels, mm_got.logLabels))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmFilter.t.Errorf("IExtenderMock.Filter got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmFilter.FilterMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmFilter.FilterMock.defaultExpectation.results
		if mm_results == nil {
			mmFilter.t.Fatal("No results are set for the IExtenderMock.Filter")
		}
		return (*mm_results).bp1, (*mm_results).err
	}
	if mmFilter.funcFilter != nil {
		return mmFilter.funcFilter(moduleName, logLabels)
	}
	mmFilter.t.Fatalf("Unexpected call to IExtenderMock.Filter. %v %v", moduleName, logLabels)
	return
}

// FilterAfterCounter returns a count of finished IExtenderMock.Filter invocations
func (mmFilter *IExtenderMock) FilterAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFilter.afterFilterCounter)
}

// FilterBeforeCounter returns a count of IExtenderMock.Filter invocations
func (mmFilter *IExtenderMock) FilterBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFilter.beforeFilterCounter)
}

// Calls returns a list of arguments used in each call to IExtenderMock.Filter.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmFilter *mIExtenderMockFilter) Calls() []*IExtenderMockFilterParams {
	mmFilter.mutex.RLock()

	argCopy := make([]*IExtenderMockFilterParams, len(mmFilter.callArgs))
	copy(argCopy, mmFilter.callArgs)

	mmFilter.mutex.RUnlock()

	return argCopy
}

// MinimockFilterDone returns true if the count of the Filter invocations corresponds
// the number of defined expectations
func (m *IExtenderMock) MinimockFilterDone() bool {
	if m.FilterMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.FilterMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.FilterMock.invocationsDone()
}

// MinimockFilterInspect logs each unmet expectation
func (m *IExtenderMock) MinimockFilterInspect() {
	for _, e := range m.FilterMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to IExtenderMock.Filter at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterFilterCounter := mm_atomic.LoadUint64(&m.afterFilterCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.FilterMock.defaultExpectation != nil && afterFilterCounter < 1 {
		if m.FilterMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to IExtenderMock.Filter at\n%s", m.FilterMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to IExtenderMock.Filter at\n%s with params: %#v", m.FilterMock.defaultExpectation.expectationOrigins.origin, *m.FilterMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcFilter != nil && afterFilterCounter < 1 {
		m.t.Errorf("Expected call to IExtenderMock.Filter at\n%s", m.funcFilterOrigin)
	}

	if !m.FilterMock.invocationsDone() && afterFilterCounter > 0 {
		m.t.Errorf("Expected %d calls to IExtenderMock.Filter at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.FilterMock.expectedInvocations), m.FilterMock.expectedInvocationsOrigin, afterFilterCounter)
	}
}

type mIExtenderMockIsTerminator struct {
	optional           bool
	mock               *IExtenderMock
	defaultExpectation *IExtenderMockIsTerminatorExpectation
	expectations       []*IExtenderMockIsTerminatorExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// IExtenderMockIsTerminatorExpectation specifies expectation struct of the IExtender.IsTerminator
type IExtenderMockIsTerminatorExpectation struct {
	mock *IExtenderMock

	results      *IExtenderMockIsTerminatorResults
	returnOrigin string
	Counter      uint64
}

// IExtenderMockIsTerminatorResults contains results of the IExtender.IsTerminator
type IExtenderMockIsTerminatorResults struct {
	b1 bool
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmIsTerminator *mIExtenderMockIsTerminator) Optional() *mIExtenderMockIsTerminator {
	mmIsTerminator.optional = true
	return mmIsTerminator
}

// Expect sets up expected params for IExtender.IsTerminator
func (mmIsTerminator *mIExtenderMockIsTerminator) Expect() *mIExtenderMockIsTerminator {
	if mmIsTerminator.mock.funcIsTerminator != nil {
		mmIsTerminator.mock.t.Fatalf("IExtenderMock.IsTerminator mock is already set by Set")
	}

	if mmIsTerminator.defaultExpectation == nil {
		mmIsTerminator.defaultExpectation = &IExtenderMockIsTerminatorExpectation{}
	}

	return mmIsTerminator
}

// Inspect accepts an inspector function that has same arguments as the IExtender.IsTerminator
func (mmIsTerminator *mIExtenderMockIsTerminator) Inspect(f func()) *mIExtenderMockIsTerminator {
	if mmIsTerminator.mock.inspectFuncIsTerminator != nil {
		mmIsTerminator.mock.t.Fatalf("Inspect function is already set for IExtenderMock.IsTerminator")
	}

	mmIsTerminator.mock.inspectFuncIsTerminator = f

	return mmIsTerminator
}

// Return sets up results that will be returned by IExtender.IsTerminator
func (mmIsTerminator *mIExtenderMockIsTerminator) Return(b1 bool) *IExtenderMock {
	if mmIsTerminator.mock.funcIsTerminator != nil {
		mmIsTerminator.mock.t.Fatalf("IExtenderMock.IsTerminator mock is already set by Set")
	}

	if mmIsTerminator.defaultExpectation == nil {
		mmIsTerminator.defaultExpectation = &IExtenderMockIsTerminatorExpectation{mock: mmIsTerminator.mock}
	}
	mmIsTerminator.defaultExpectation.results = &IExtenderMockIsTerminatorResults{b1}
	mmIsTerminator.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmIsTerminator.mock
}

// Set uses given function f to mock the IExtender.IsTerminator method
func (mmIsTerminator *mIExtenderMockIsTerminator) Set(f func() (b1 bool)) *IExtenderMock {
	if mmIsTerminator.defaultExpectation != nil {
		mmIsTerminator.mock.t.Fatalf("Default expectation is already set for the IExtender.IsTerminator method")
	}

	if len(mmIsTerminator.expectations) > 0 {
		mmIsTerminator.mock.t.Fatalf("Some expectations are already set for the IExtender.IsTerminator method")
	}

	mmIsTerminator.mock.funcIsTerminator = f
	mmIsTerminator.mock.funcIsTerminatorOrigin = minimock.CallerInfo(1)
	return mmIsTerminator.mock
}

// Times sets number of times IExtender.IsTerminator should be invoked
func (mmIsTerminator *mIExtenderMockIsTerminator) Times(n uint64) *mIExtenderMockIsTerminator {
	if n == 0 {
		mmIsTerminator.mock.t.Fatalf("Times of IExtenderMock.IsTerminator mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmIsTerminator.expectedInvocations, n)
	mmIsTerminator.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmIsTerminator
}

func (mmIsTerminator *mIExtenderMockIsTerminator) invocationsDone() bool {
	if len(mmIsTerminator.expectations) == 0 && mmIsTerminator.defaultExpectation == nil && mmIsTerminator.mock.funcIsTerminator == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmIsTerminator.mock.afterIsTerminatorCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmIsTerminator.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// IsTerminator implements IExtender
func (mmIsTerminator *IExtenderMock) IsTerminator() (b1 bool) {
	mm_atomic.AddUint64(&mmIsTerminator.beforeIsTerminatorCounter, 1)
	defer mm_atomic.AddUint64(&mmIsTerminator.afterIsTerminatorCounter, 1)

	mmIsTerminator.t.Helper()

	if mmIsTerminator.inspectFuncIsTerminator != nil {
		mmIsTerminator.inspectFuncIsTerminator()
	}

	if mmIsTerminator.IsTerminatorMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmIsTerminator.IsTerminatorMock.defaultExpectation.Counter, 1)

		mm_results := mmIsTerminator.IsTerminatorMock.defaultExpectation.results
		if mm_results == nil {
			mmIsTerminator.t.Fatal("No results are set for the IExtenderMock.IsTerminator")
		}
		return (*mm_results).b1
	}
	if mmIsTerminator.funcIsTerminator != nil {
		return mmIsTerminator.funcIsTerminator()
	}
	mmIsTerminator.t.Fatalf("Unexpected call to IExtenderMock.IsTerminator.")
	return
}

// IsTerminatorAfterCounter returns a count of finished IExtenderMock.IsTerminator invocations
func (mmIsTerminator *IExtenderMock) IsTerminatorAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmIsTerminator.afterIsTerminatorCounter)
}

// IsTerminatorBeforeCounter returns a count of IExtenderMock.IsTerminator invocations
func (mmIsTerminator *IExtenderMock) IsTerminatorBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmIsTerminator.beforeIsTerminatorCounter)
}

// MinimockIsTerminatorDone returns true if the count of the IsTerminator invocations corresponds
// the number of defined expectations
func (m *IExtenderMock) MinimockIsTerminatorDone() bool {
	if m.IsTerminatorMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.IsTerminatorMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.IsTerminatorMock.invocationsDone()
}

// MinimockIsTerminatorInspect logs each unmet expectation
func (m *IExtenderMock) MinimockIsTerminatorInspect() {
	for _, e := range m.IsTerminatorMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to IExtenderMock.IsTerminator")
		}
	}

	afterIsTerminatorCounter := mm_atomic.LoadUint64(&m.afterIsTerminatorCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.IsTerminatorMock.defaultExpectation != nil && afterIsTerminatorCounter < 1 {
		m.t.Errorf("Expected call to IExtenderMock.IsTerminator at\n%s", m.IsTerminatorMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcIsTerminator != nil && afterIsTerminatorCounter < 1 {
		m.t.Errorf("Expected call to IExtenderMock.IsTerminator at\n%s", m.funcIsTerminatorOrigin)
	}

	if !m.IsTerminatorMock.invocationsDone() && afterIsTerminatorCounter > 0 {
		m.t.Errorf("Expected %d calls to IExtenderMock.IsTerminator at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.IsTerminatorMock.expectedInvocations), m.IsTerminatorMock.expectedInvocationsOrigin, afterIsTerminatorCounter)
	}
}

type mIExtenderMockName struct {
	optional           bool
	mock               *IExtenderMock
	defaultExpectation *IExtenderMockNameExpectation
	expectations       []*IExtenderMockNameExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// IExtenderMockNameExpectation specifies expectation struct of the IExtender.Name
type IExtenderMockNameExpectation struct {
	mock *IExtenderMock

	results      *IExtenderMockNameResults
	returnOrigin string
	Counter      uint64
}

// IExtenderMockNameResults contains results of the IExtender.Name
type IExtenderMockNameResults struct {
	e1 extenders.ExtenderName
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmName *mIExtenderMockName) Optional() *mIExtenderMockName {
	mmName.optional = true
	return mmName
}

// Expect sets up expected params for IExtender.Name
func (mmName *mIExtenderMockName) Expect() *mIExtenderMockName {
	if mmName.mock.funcName != nil {
		mmName.mock.t.Fatalf("IExtenderMock.Name mock is already set by Set")
	}

	if mmName.defaultExpectation == nil {
		mmName.defaultExpectation = &IExtenderMockNameExpectation{}
	}

	return mmName
}

// Inspect accepts an inspector function that has same arguments as the IExtender.Name
func (mmName *mIExtenderMockName) Inspect(f func()) *mIExtenderMockName {
	if mmName.mock.inspectFuncName != nil {
		mmName.mock.t.Fatalf("Inspect function is already set for IExtenderMock.Name")
	}

	mmName.mock.inspectFuncName = f

	return mmName
}

// Return sets up results that will be returned by IExtender.Name
func (mmName *mIExtenderMockName) Return(e1 extenders.ExtenderName) *IExtenderMock {
	if mmName.mock.funcName != nil {
		mmName.mock.t.Fatalf("IExtenderMock.Name mock is already set by Set")
	}

	if mmName.defaultExpectation == nil {
		mmName.defaultExpectation = &IExtenderMockNameExpectation{mock: mmName.mock}
	}
	mmName.defaultExpectation.results = &IExtenderMockNameResults{e1}
	mmName.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmName.mock
}

// Set uses given function f to mock the IExtender.Name method
func (mmName *mIExtenderMockName) Set(f func() (e1 extenders.ExtenderName)) *IExtenderMock {
	if mmName.defaultExpectation != nil {
		mmName.mock.t.Fatalf("Default expectation is already set for the IExtender.Name method")
	}

	if len(mmName.expectations) > 0 {
		mmName.mock.t.Fatalf("Some expectations are already set for the IExtender.Name method")
	}

	mmName.mock.funcName = f
	mmName.mock.funcNameOrigin = minimock.CallerInfo(1)
	return mmName.mock
}

// Times sets number of times IExtender.Name should be invoked
func (mmName *mIExtenderMockName) Times(n uint64) *mIExtenderMockName {
	if n == 0 {
		mmName.mock.t.Fatalf("Times of IExtenderMock.Name mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmName.expectedInvocations, n)
	mmName.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmName
}

func (mmName *mIExtenderMockName) invocationsDone() bool {
	if len(mmName.expectations) == 0 && mmName.defaultExpectation == nil && mmName.mock.funcName == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmName.mock.afterNameCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmName.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Name implements IExtender
func (mmName *IExtenderMock) Name() (e1 extenders.ExtenderName) {
	mm_atomic.AddUint64(&mmName.beforeNameCounter, 1)
	defer mm_atomic.AddUint64(&mmName.afterNameCounter, 1)

	mmName.t.Helper()

	if mmName.inspectFuncName != nil {
		mmName.inspectFuncName()
	}

	if mmName.NameMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmName.NameMock.defaultExpectation.Counter, 1)

		mm_results := mmName.NameMock.defaultExpectation.results
		if mm_results == nil {
			mmName.t.Fatal("No results are set for the IExtenderMock.Name")
		}
		return (*mm_results).e1
	}
	if mmName.funcName != nil {
		return mmName.funcName()
	}
	mmName.t.Fatalf("Unexpected call to IExtenderMock.Name.")
	return
}

// NameAfterCounter returns a count of finished IExtenderMock.Name invocations
func (mmName *IExtenderMock) NameAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmName.afterNameCounter)
}

// NameBeforeCounter returns a count of IExtenderMock.Name invocations
func (mmName *IExtenderMock) NameBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmName.beforeNameCounter)
}

// MinimockNameDone returns true if the count of the Name invocations corresponds
// the number of defined expectations
func (m *IExtenderMock) MinimockNameDone() bool {
	if m.NameMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.NameMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.NameMock.invocationsDone()
}

// MinimockNameInspect logs each unmet expectation
func (m *IExtenderMock) MinimockNameInspect() {
	for _, e := range m.NameMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to IExtenderMock.Name")
		}
	}

	afterNameCounter := mm_atomic.LoadUint64(&m.afterNameCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.NameMock.defaultExpectation != nil && afterNameCounter < 1 {
		m.t.Errorf("Expected call to IExtenderMock.Name at\n%s", m.NameMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcName != nil && afterNameCounter < 1 {
		m.t.Errorf("Expected call to IExtenderMock.Name at\n%s", m.funcNameOrigin)
	}

	if !m.NameMock.invocationsDone() && afterNameCounter > 0 {
		m.t.Errorf("Expected %d calls to IExtenderMock.Name at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.NameMock.expectedInvocations), m.NameMock.expectedInvocationsOrigin, afterNameCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *IExtenderMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockAddFunctionalModuleInspect()

			m.MinimockFilterInspect()

			m.MinimockIsTerminatorInspect()

			m.MinimockNameInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *IExtenderMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *IExtenderMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAddFunctionalModuleDone() &&
		m.MinimockFilterDone() &&
		m.MinimockIsTerminatorDone() &&
		m.MinimockNameDone()
}
