#!/bin/bash

source /deckhouse/shell_lib.sh

function __main__() {
  if values::has global.clusterConfiguration ; then
    echo "true" > "$MODULE_ENABLED_RESULT"
  else
    echo "false" > "$MODULE_ENABLED_RESULT"
  fi
}

enabled::run "$@"
