{{- $dockercfg := .Values.global.modulesImages.registry.dockercfg }}
{{- if .Values.istio.registry }}
  {{- $dockercfg = .Values.istio.registry.dockercfg | default $dockercfg }}
{{- end }}
{{- if $dockercfg }}
---
apiVersion: v1
kind: Secret
metadata:
  name: deckhouse-registry
  namespace: d8-ingress-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockercfg }}
{{- end }}
