#!/bin/bash -e

if [[ "$1" == "--config" ]]; then
    echo "
{
    \"beforeHelm\": 2
}
"
else
    cat << 'EOF' > "$VALUES_JSON_PATCH_PATH"
[
    { "op": "add", "path": "/module/beforeHelm", "value": "override-value" }
]
EOF
fi
