#!/bin/bash

# dependency: alpha

c=$(cat ${VALUES_PATH:-/dev/null} | jq .global.enabledModules[] | grep '"alpha"' | wc -l)
if [ "$c" == "1" ] ; then
  echo true > $MODULE_ENABLED_RESULT
  exit 0
fi

echo false > $MODULE_ENABLED_RESULT
