- name: d8.control-plane-manager.migration
  rules:
  - alert: D8ObsoletePublishAPIInUserAuthn
    for: 10m
    expr: |
      d8_obsolete_publishapi_in_user_authn == 1
    labels:
      d8_component: control-plane-manager
      d8_module: control-plane-manager
      severity_level: "6"
      tier: cluster
    annotations:
      plk_protocol_version: "1"
      plk_markup_format: "markdown"
      plk_create_group_if_not_exists__d8_obsolete_publishapi_in_user_authn: "D8ObsoletePublishAPIInUserAuthn,tier=cluster,prometheus=deckhouse,kubernetes=~kubernetes"
      plk_grouped_by__d8_obsolete_publishapi_in_user_authn: "D8ObsoletePublishAPIInUserAuthn,tier=cluster,prometheus=deckhouse,kubernetes=~kubernetes"
      summary: Obsolete Publish API settings in `user-authn` need to be migrated.
      description: |-
        Publish API ingress settings are being migrated from `mc user-authn` to `mc control-plane-manager`.

        To complete the migration, follow the steps below:

        1. Review current settings for `publishAPI` in resource `modeleConfig user-authn`.
        2. Update `moduleConfig control-plane-manager` spec to `spec.version: 3`, if the `mc` exists. This may require migrating `settings.apiserver.loadBalancer` to newer `settings.apiserver.publishAPI.loadBalancer` if it's set.
        3. If `moduleConfig` does not exist, create it via `d8`: 
          ```
          d8 s module enable control-plane-manager
          ```
          And patch in the version:
          ```
          d8 k patch moduleconfig control-plane-manager --type merge \
          -p '{"spec":{"version":3}}'
          ```
        4. Patch settings into `moduleConfig control-plane-manager` from temporary configMap by executing the following script:
          ```bash
          d8 k patch moduleconfig control-plane-manager --type merge \
        -p "$(cat <<EOF
        {"spec": {"settings": {"apiserver": {"publishAPI": {"ingress": \
        $(d8 k -n kube-system get cm d8-publishapi-config-migration -ojsonpath='{.data.config}')
              }}}}}
        EOF
        )"
          ```
        5. Remove obsolete `spec.settings.publishAPI` from `moduleConfig user-authn`