apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    heritage: deckhouse
    module: monitoring-kubernetes
    rbac.deckhouse.io/aggregate-to-observability-as: manager
    rbac.deckhouse.io/kind: capability
    rbac.deckhouse.io/scope: system
    rbac.deckhouse.io/namespace: d8-monitoring
  name: d8:system-capability:monitoring-kubernetes:edit
  annotations:
    en.meta.deckhouse.io/title: "Module monitoring-kubernetes: edit configuration"
    ru.meta.deckhouse.io/title: "Модуль monitoring-kubernetes: управление конфигурацией"
    en.meta.deckhouse.io/description: "Manage the monitoring-kubernetes module configuration."
    ru.meta.deckhouse.io/description: "Управление конфигурацией модуля monitoring-kubernetes."
rules:
- apiGroups:
  - deckhouse.io
  resourceNames:
  - monitoring-kubernetes
  resources:
  - moduleconfigs
  verbs:
  - create
  - update
  - patch
  - delete
