#!/bin/bash

### Миграция 2019-06-17: https://github.com/deckhouse/deckhouse/merge_requests/829
###
### Этот хук можно удалить, после выката данного MR'а на все инсталяции.

source /antiopa/shell_lib.sh

function __config__() {
  jo -p onStartup=0
}

function __main__() {
  fltr='.spec.template.spec.containers[].env |= map(select(.name != "GITLAB_TOKEN")) |
        .spec.template.spec.containers[0].volumeMounts = [{"mountPath":"/etc/registrysecret","name":"registrysecret","readOnly":true}] |
        .spec.template.spec.volumes = [{"name":"registrysecret","secret":{"defaultMode":420,"secretName":"antiopa-registry"}}]'

  kubectl -n antiopa delete secret antiopa-secret >/dev/null 2>&1 || true
  kubectl::jq_patch antiopa deployment/antiopa "$fltr"
}

hook::run "$@"
