#!/bin/bash
### Миграция 2019-09-12: https://github.com/deckhouse/deckhouse/issues/527

source /antiopa/shell_lib.sh

function __config__() {
  jo -p onStartup=100
}

function __main__() {
  fltr='. | del (.spec.strategy.rollingUpdate) | .spec.strategy.type = "Recreate"'
  kubectl::jq_patch antiopa deploy/antiopa "$fltr"
}

hook::run $@
