#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
    cat << "EOF"
    configVersion: v1
    beforeAll: 20
    kubernetes:
    - name: nodes_resources
      group: main
      keepFullObjectsInMemory: false
      apiVersion: v1
      kind: Node
      labelSelector:
        matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: Exists
      jqFilter: |
        {
          allocatableCPU: .status.allocatable.cpu,
          allocatableMemory: .status.allocatable.memory
        }
EOF
}

control_plane_percent="50"
# Set hard upper limit allocatable resources in millicpu and memory bytes
hard_limit_millicpu=$(( 4 * 1000 ))                       # 4 Cpu
hard_limit_memory=$(( 8 * 1024 * 1024 * 1024 ))           # 8G ram
# hard limit if master nodes absent (managed cluster)
managed_hard_limit_millicpu=1000                          # 1 Cpu
managed_hard_limit_memory=$(( 1 * 1024 * 1024 * 1024 ))   # 1G ram

# min of val1 and val2
function min() {
  local val1="$1"
  local val2="$2"
  if [ "$val1" -lt "$val2" ]; then
    echo "$val1"
  else
    echo "$val2"
  fi
}

function __main__() {
  # values for managed cluster
  discovery_millicpu_master=$managed_hard_limit_millicpu
  discovery_memory_master=$managed_hard_limit_memory
  millicpu_control_plane=0
  memory_control_plane=0

# Get requests parameters from config for everyNode and set corresponding internal variables
  config_millicpu_every_node="$(tools::dk_convert --milli "$(values::get --required "global.modules.resourcesRequests.everyNode.cpu")" )"
  if [ "$config_millicpu_every_node" -le 0 ]; then
    >&2 echo "ERROR: global.modules.resourcesRequests.everyNode.cpu must be greater 0"
    return 1
  fi
  config_memory_every_node="$(tools::dk_convert "$(values::get --required "global.modules.resourcesRequests.everyNode.memory")" )"
  if [ "$config_memory_every_node" -le 0 ]; then
    >&2 echo "ERROR: global.modules.resourcesRequests.everyNode.memory must be greater 0"
    return 1
  fi

  is_master_nodes_found="$(context::jq -r '.snapshots.nodes_resources | length > 0')"
  if [ "$is_master_nodes_found" == true ]; then
    # Get minimal cpu and memory allocatable on master nodes and convert it to milli for cpu and bytes for memory
    cpuAllocatable=$(context::jq -re '.snapshots.nodes_resources[] | .filterResult.allocatableCPU')
    discovery_millicpu_master=$(for allocatableCPU in $cpuAllocatable; do
      tools::dk_convert --milli "$allocatableCPU"
    done | sort | head -1)

    memoryAllocatable=$(context::jq -re '.snapshots.nodes_resources[] | .filterResult.allocatableMemory')
    discovery_memory_master=$(for allocatableMemory in $memoryAllocatable; do
      tools::dk_convert "$allocatableMemory"
    done | sort | head -1)
  fi

  # Get requests parameters from config for masterNode or calculate if absent
  if values::has "global.modules.resourcesRequests.masterNode.cpu"; then
    millicpu_master="$(tools::dk_convert --milli "$(values::get "global.modules.resourcesRequests.masterNode.cpu")" )"
  else
    min_millicpu="$(min "$discovery_millicpu_master" "$hard_limit_millicpu")"
    millicpu_master="$(( min_millicpu - config_millicpu_every_node ))"
  fi
  if values::has "global.modules.resourcesRequests.masterNode.memory"; then
    memory_master="$(tools::dk_convert "$(values::get "global.modules.resourcesRequests.masterNode.memory")" )"
  else
    min_memory="$(min "$discovery_memory_master" "$hard_limit_memory")"
    memory_master="$(( min_memory - config_memory_every_node ))"
   fi

  # millicpu_master must be greater than 0
  if [ "$millicpu_master" -le 0 ]; then
    >&2 echo "ERROR: CPU resources for allocating on master nodes must be greater than 0"
    return 1
  fi
  # memory_master must be greater than 0
  if [ "$memory_master" -le 0 ]; then
    >&2 echo "ERROR: Memory resources for allocating on master nodes must be greater than 0"
    return 1
  fi
  # Check if master + everynode can be placed on minimal master node
  if [ "$(( millicpu_master + config_millicpu_every_node ))" -gt "$discovery_millicpu_master" ]; then
    >&2 echo "ERROR: everyNode CPU + masterNode CPU must be less than discovered minimal master node CPU"
    return 1
  fi
  if [ "$(( memory_master + config_memory_every_node ))" -gt "$discovery_memory_master" ]; then
    >&2 echo "ERROR: everyNode memory + masterNode memory must be less than discovered minimal master node memory"
    return 1
  fi

  if [ "$is_master_nodes_found" == true ]; then
    # set resources requests for control-plane
    millicpu_control_plane="$(bc <<< "$millicpu_master * $control_plane_percent / 100" )"
    memory_control_plane="$(bc <<< "$memory_master * $control_plane_percent / 100" )"
    # set resources requests for master
    millicpu_master="$(bc <<< "$millicpu_master * (100 - $control_plane_percent) / 100" )"
    memory_master="$(bc <<< "$memory_master * (100 - $control_plane_percent) / 100" )"
  fi

  # Set global internal variables
  if ! values::has "global.modules.resourcesRequests.internal"; then
    values::set "global.modules.resourcesRequests.internal" "{}"
  fi
  values::set "global.modules.resourcesRequests.internal.milliCpuEveryNode" "$config_millicpu_every_node"
  values::set "global.modules.resourcesRequests.internal.memoryEveryNode" "$config_memory_every_node"
  values::set "global.modules.resourcesRequests.internal.milliCpuControlPlane" "$millicpu_control_plane"
  values::set "global.modules.resourcesRequests.internal.memoryControlPlane" "$memory_control_plane"
  values::set "global.modules.resourcesRequests.internal.milliCpuMaster" "$millicpu_master"
  values::set "global.modules.resourcesRequests.internal.memoryMaster" "$memory_master"
}

hook::run "$@"
