#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  jo -p onStartup=10
}

function __main__() {
  if ! kubectl -n kube-system get configmap d8-cluster-uuid >/dev/null 2>/dev/null ; then
    cluster_uuid=$(uuidgen -r)
    configmap=$(cat <<- YAML
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: d8-cluster-uuid
  namespace: kube-system
  labels:
    heritage: deckhouse
data:
  cluster-uuid: "${cluster_uuid}"
YAML
)
    echo "$configmap" | kubectl -n kube-system create -f -
  else
    cluster_uuid=$(kubectl -n kube-system get configmap d8-cluster-uuid -o json | jq '.data."cluster-uuid"' -r)
  fi

  values::set global.discovery.clusterUUID "${cluster_uuid}"
}

hook::run "$@"
