#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p onStartup=0
}

function __main__() {
  ### Миграция 2019-07-16: https://github.com/deckhouse/deckhouse/issues/364
  # Этот хук можно удалить, после выката релиза с данным коммитом

  if values::has --config global.clusterHostname; then
    values::set --config global.addonsPublicDomainTemplate "%s."$(values::get --config global.clusterHostname)
    values::unset --config global.clusterHostname
  fi
}

hook::run $@
