#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: is_bootstraped_cm
      includeSnapshotsFrom: ["is_bootstraped_cm", "not_master_and_ready_nodes"]
      keepFullObjectsInMemory: false
      apiVersion: v1
      kind: ConfigMap
      namespace:
        nameSelector:
          matchNames: [kube-system]
      nameSelector:
        matchNames: [d8-cluster-is-bootstraped]
    - name: not_master_and_ready_nodes
      includeSnapshotsFrom: ["is_bootstraped_cm", "not_master_and_ready_nodes"]
      keepFullObjectsInMemory: false
      apiVersion: v1
      kind: Node
      executeHookOnEvent: ["Added", "Modified"]
      jqFilter: '
        (.spec.taints == null or ([.spec.taints[] | select(.key == "node-role.kubernetes.io/master")] | any | not))
        and
        (.status.conditions | [.[] | select(.type == "Ready")] | all(.[] ; .status == "True"))
      '
EOF
}

function _create_is_bootstraped_cm() {
    kubernetes::create_if_not_exists_yaml << EOF
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: d8-cluster-is-bootstraped
        namespace: kube-system
EOF
}

function __main__() {
  if context::has snapshots.is_bootstraped_cm.0; then
    values::set global.clusterIsBootstrapped true
    return 0
  fi

  if values::is_true global.clusterIsBootstrapped; then
    _create_is_bootstraped_cm
    return 0
  fi

  if context::jq -e '[.snapshots.not_master_and_ready_nodes[] | .filterResult] | any' >/dev/null 2>&1; then
    values::set global.clusterIsBootstrapped true
    _create_is_bootstraped_cm
    return 0
  fi
}

function __on_kubernetes::is_bootstraped_cm::deleted() {
  >&2 echo "ERROR: CM kube-system/d8-cluster-is-bootstraped was deleted. Don't know what to do."
  return 1
}

hook::run $@
