#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: cni_configuration_secret
      queue: /modules/$(module::name::kebab_case)
      keepFullObjectsInMemory: false
      group: main
      apiVersion: v1
      kind: Secret
      namespace:
        nameSelector:
          matchNames: [kube-system]
      nameSelector:
        matchNames: [d8-cni-configuration]
      jqFilter: |
        {
          "cniModule": ((.data // {}) | with_entries(.value |= (. | @base64d)) | .cni)
        }
EOF
}

function __main__() {
  if context::jq -e '.snapshots.cni_configuration_secret[0].filterResult.cniModule == "flannel"'; then
    values::set cniFlannelEnabled "true"
  else
    values::unset cniFlannelEnabled
  fi

  if context::jq -e '.snapshots.cni_configuration_secret[0].filterResult.cniModule == "simple-bridge"'; then
    values::set cniSimpleBridgeEnabled "true"
  else
    values::unset cniSimpleBridgeEnabled
  fi
}

hook::run "$@"
