#!/bin/bash

# Copyright 2021 Flant CJSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### Migration 26.10.2020: Remove after release with this MR

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: cm
      keepFullObjectsInMemory: false
      group: main
      apiVersion: v1
      kind: ConfigMap
      namespace:
        nameSelector:
          matchNames: [kube-system]
      nameSelector:
        matchNames: [kube-flannel-cfg]
      jqFilter: |
        {"backend": .data."net-conf.json" | fromjson.Backend.Type}
    - name: ds
      keepFullObjectsInMemory: false
      group: main
      apiVersion: apps/v1
      kind: DaemonSet
      namespace:
        nameSelector:
          matchNames: [kube-system]
      nameSelector:
        matchNames: [kube-flannel-ds]
      jqFilter: |
        {"name": .metadata.name}
    - name: ns
      keepFullObjectsInMemory: false
      group: main
      apiVersion: v1
      kind: Namespace
      nameSelector:
        matchNames:
        - d8-cni-flannel
      jqFilter: .metadata.name
EOF
}

function __main__() {
  if context::has snapshots.ns.0; then
    return 0
  fi

  if context::has snapshots.cm.0 && context::has snapshots.ds.0; then
    values::set cniFlannelEnabled "true"
  fi
}

hook::run "$@"
