#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p onStartup=1
}

function __main__() {
  ### Миграция 2019-09-03: https://github.com/deckhouse/deckhouse/issues/687
  # Этот хук можно удалить, после выката релиза с данным коммитом

  if [[ $(kubectl -n antiopa get configmap -l NAME=vertical-pod-autoscaler-crd,OWNER=TILLER --ignore-not-found=true) ]]; then
    kubectl -n antiopa delete configmap -l NAME=vertical-pod-autoscaler-crd,OWNER=TILLER
  fi

  if [[ $(kubectl -n antiopa get configmap -l NAME=cert-manager-crd,OWNER=TILLER --ignore-not-found=true) ]]; then
    kubectl -n antiopa delete configmap -l NAME=cert-manager-crd,OWNER=TILLER
  fi
}

hook::run "$@"
