#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat <<EOF
    configVersion: v1
    onStartup: 10
EOF
}

function __main__() {
  if [[ -f /deckhouse/version ]] ; then deckhouseVersion=$(cat /deckhouse/version) ; else deckhouseVersion="unknown"; fi
  values::set global.deckhouseVersion "$deckhouseVersion"
}

hook::run "$@"
