#!/bin/bash

# Copyright 2021 Flant CJSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: cni_configuration_secret
      keepFullObjectsInMemory: false
      group: main
      apiVersion: v1
      kind: Secret
      namespace:
        nameSelector:
          matchNames: [kube-system]
      nameSelector:
        matchNames: [d8-cni-configuration]
      jqFilter: |
        {
          "cniModule": ((.data // {}) | with_entries(.value |= (. | @base64d)) | .cni)
        }
EOF
}

function __main__() {
  if context::jq -e '.snapshots.cni_configuration_secret[0].filterResult.cniModule == "flannel"'; then
    values::set cniFlannelEnabled "true"
  else
    values::unset cniFlannelEnabled
  fi

  if context::jq -e '.snapshots.cni_configuration_secret[0].filterResult.cniModule == "simple-bridge"'; then
    values::set cniSimpleBridgeEnabled "true"
  else
    values::unset cniSimpleBridgeEnabled
  fi
}

hook::run "$@"
