#!/bin/bash

# Copyright 2021 Flant CJSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: config
      group: main
      keepFullObjectsInMemory: false
      apiVersion: v1
      kind: Secret
      namespace:
        nameSelector:
          matchNames: [kube-system]
      nameSelector:
        matchNames: [d8-cluster-configuration]
      jqFilter: '.data."cluster-configuration.yaml" | @base64d'
EOF
}

function __main__() {
  cloud_provider=""
  if context::has snapshots.config.0; then
    cloud_provider=$(context::get  --required 'snapshots.config.0.filterResult' \
      | deckhouse-controller helper cluster-configuration \
      | jq -rc '.clusterConfiguration | if .cloud then .cloud.provider else . end')

  elif values::has --config cloudProviderOpenstack; then
    cloud_provider="OpenStack"

  elif values::has --config cloudProviderAws; then
    cloud_provider="AWS"

  elif values::has --config cloudProviderGcp; then
    cloud_provider="GCP"

  elif values::has --config cloudProviderVsphere; then
    cloud_provider="vSphere"

  elif values::has --config cloudProviderYandex; then
    cloud_provider="Yandex"

  elif values::has --config cloudProviderAzure; then
    cloud_provider="Azure"

  fi

  declare -A providers; providers=( \
      ["OpenStack"]="cloudProviderOpenstack"
      ["AWS"]="cloudProviderAws"
      ["GCP"]="cloudProviderGcp"
      ["Yandex"]="cloudProviderYandex"
      ["vSphere"]="cloudProviderVsphere"
      ["Azure"]="cloudProviderAzure"
  )

  for key in "${!providers[@]}"; do
    module=${providers[$key]}
    if [[ "$key" == "$cloud_provider" ]]; then
      values::set "${module}Enabled" true
    else
      values::unset "${module}Enabled"
    fi
  done
}

hook::run "$@"
