#!/bin/bash

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  jo -p onStartup=9999
}

function __main__() {
  mkdir /tmp/***REMOVED***
  values::get global.discovery.clusterType > /tmp/***REMOVED***/cluster_type
}

hook::run $@
