#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    onStartup: 9999
EOF

}

function __main__() {
  mkdir -p /tmp/***REMOVED***
  values::get global.discovery.clusterType > /tmp/***REMOVED***/cluster_type
}

hook::run $@
