#!/bin/bash

### Миграция 25.03.2020: Удалить после выката релиза с данным MR
source /deckhouse/shell_lib.sh

function __config__() {
  jo -p configVersion=v1 onStartup=5
}

function __on_startup() {
  if kubectl -n d8-system  get cm deckhouse -o json | jq .data.prometheus -r | grep 'madisonSelfSetupKey: false' 2>/dev/null >/dev/null; then
    kubernetes::patch_jq "d8-system" "configmap/deckhouse" '.data.prometheusMadisonIntegrationEnabled = "false"'
  fi
}

hook::run $@
