#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p onStartup=5
}

function __main__() {
  ### Миграция 2018-12-09: https://github.com/deckhouse/deckhouse/merge_requests/571
  # Этот хук можно удалить, после выката релиза с данным коммитом
  if ! kubectl -n antiopa get secret/antiopa-registry 2>/dev/null > /dev/null ; then
    kubectl -n antiopa get secret registrysecret -o json | \
      jq -r ".metadata.name=\"antiopa-registry\" |
             .metadata |= with_entries(select([.key] | inside([\"name\", \"namespace\", \"labels\"])))" \
      | kubectl::replace_or_create
    kubectl -n antiopa delete secret registrysecret
  fi

  fltr='.'

  ###
  # Если у antiopa deployment еще старый imagePullSecrets,
  # то меняем его на новый
  if kubectl -n antiopa get deployment antiopa -o json | jq -re '.spec.template.spec.imagePullSecrets[0].name == "registrysecret"' ; then
    fltr=$fltr' | .spec.template.spec.imagePullSecrets = [{"name":"antiopa-registry"}]'

    # Применяем
    kubectl::jq_patch antiopa deployment/antiopa "$fltr"
  fi
}

hook::run $@
