{
 "title": "Sidekiq",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(sidekiq_processed_jobs_total, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Queues latency",
   "type": "graph",
   "description": "The amount of seconds between oldest job being pushed to the queue and current time (labels: name)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(sidekiq_queue_latency_seconds{namespace=\"$namespace\"}[$__interval_sx4])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Queue enqueued jobs",
   "type": "graph",
   "description": "The number of enqueued jobs in the queue (labels: name)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(sidekiq_queue_enqueued_jobs{namespace=\"$namespace\"}[$__interval_sx4])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Scheduled and enqueued jobs",
   "type": "graph",
   "description": "The number of jobs scheduled for a future execution and the number of enqueued jobs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sidekiq_scheduled_jobs{namespace=\"$namespace\"}[$__interval_sx4])",
     "legendFormat": "scheduled"
    },
    {
     "expr": "increase(sidekiq_enqueued_jobs{namespace=\"$namespace\"}[$__interval_sx4])",
     "legendFormat": "enqueued"
    }
   ]
  },
  {
   "title": "Failed, retry and dead jobs",
   "type": "graph",
   "description": "failed - The total number of failed jobs\n\nretry - The number of jobs scheduled for the next try\n\ndead - The number of jobs being dead",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sidekiq_failed_jobs_total{namespace=\"$namespace\"}[$__interval_sx4])",
     "legendFormat": "failed"
    },
    {
     "expr": "increase(sidekiq_retry_jobs{namespace=\"$namespace\"}[$__interval_sx4])",
     "legendFormat": "retry"
    },
    {
     "expr": "increase(sidekiq_dead_jobs{namespace=\"$namespace\"}[$__interval_sx4])",
     "legendFormat": "dead"
    }
   ]
  },
  {
   "title": "Total processed jobs",
   "type": "graph",
   "description": "The total number of processed jobs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sidekiq_processed_jobs_total{namespace=\"$namespace\"}[$__interval_sx4])",
     "legendFormat": "processed"
    }
   ]
  },
  {
   "title": "Busy workers",
   "type": "graph",
   "description": "The number of workers performing the job",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sidekiq_busy_workers{namespace=\"$namespace\"}[$__interval_sx4])",
     "legendFormat": "workers"
    }
   ]
  }
 ]
}