{{- $controllers := .Values.ingressNginx.internal.ingressControllers | default (list) -}}
{{- $licenseMap := include "geoip_collect_license_editions" (dict "controllers" $controllers) | fromJson -}}
{{- if gt (len $licenseMap) 0 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: geoproxy
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "geoproxy")) | nindent 2 }}
spec:
  minAvailable: {{ include "helm_lib_is_ha_to_value" (list . 1 0) }}
  selector:
    matchLabels:
      app: geoproxy
{{- end }}

