#!/bin/bash
# Copyright 2025 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -Eeo pipefail
mkdir -p /opt/deckhouse/bin

enable_selinux=false

if type -p getenforce &>/dev/null && [[ $(getenforce) != Disabled ]]; then
  enable_selinux=true
fi

mkdir -p /etc/containerd/certs.d/_default

cat << EOF > /etc/containerd/config.toml
version = 3
[plugins]
  [plugins.'io.containerd.cri.v1.runtime']
    enable_selinux = ${enable_selinux}
EOF

cp -f containerd containerd-shim-runc-v2 ctr runc /opt/deckhouse/bin

mkdir -p /lib/systemd/system/
cp -f containerd.service /lib/systemd/system/containerd-deckhouse.service
systemctl daemon-reload

if [[ -f /etc/systemd/system/containerd.service ]] || [[ -f /usr/lib/systemd/system/containerd.service ]] || [[ -f /lib/systemd/system/containerd.service ]]; then
  systemctl disable --now containerd.service &> /dev/null
fi

systemctl enable containerd-deckhouse.service
