#!/bin/bash
# Copyright 2023 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -Eeo pipefail

systemctl disable containerd-deckhouse.service
rm -f /opt/deckhouse/bin/containerd /opt/deckhouse/bin/containerd-shim-runc-v1 /opt/deckhouse/bin/containerd-shim-runc-v2 /opt/deckhouse/bin/ctr /opt/deckhouse/bin/runc

rm -f /lib/systemd/system/containerd-deckhouse.service
systemctl daemon-reload
