diff --git a/Makefile b/Makefile
index 23fd163..6460588 100644
--- a/Makefile
+++ b/Makefile
@@ -117,8 +117,7 @@ endif
 
 # Run go fmt against code and add the licence header
 fmt: gci addlicense
-	go mod tidy
-	go fmt ./...
+	go mod download
 	find . -type f -name '*.go' -a -exec $(GCI) write -s standard -s default -s "prefix(github.com/falcosecurity/k8s-metadata)" {} \;
 	find . -type f -name '*.go' -exec $(ADDLICENSE) -l apache -c "The Falco Authors" -y "$(shell date +%Y)" {} \;
 
@@ -157,4 +156,4 @@ ifeq (, $(shell which protoc))
 	rm -rf $$PROTOC_TMP_DIR ;\
 	}
 endif
-PROTOC=$(shell which protoc)
\ No newline at end of file
+PROTOC=$(shell which protoc)
