{{- define "zvirt_cdd_pod_annotations" -}}
checksum/config: {{ printf "%s%s" (include (print $.Template.BasePath "/cloud-data-discoverer/secret.yaml") . | toString) (include (print $.Template.BasePath "/secret.yaml") . | toString) | sha256sum }}
{{- end -}}

{{- define "zvirt_cdd_envs" -}}
- name: ZVIRT_API_URL
  valueFrom:
    secretKeyRef:
      name: cdd-zvirt-credentials
      key: server
- name: ZVIRT_USERNAME
  valueFrom:
    secretKeyRef:
      name: cdd-zvirt-credentials
      key: username
- name: ZVIRT_PASSWORD
  valueFrom:
    secretKeyRef:
      name: cdd-zvirt-credentials
      key: password
- name: ZVIRT_INSECURE
  valueFrom:
    secretKeyRef:
      name: cdd-zvirt-credentials
      key: insecure
- name: ZVIRT_CA_BUNDLE
  valueFrom:
    secretKeyRef:
      name: cdd-zvirt-credentials
      key: caBundle
{{- end -}}

{{- $cddConfig := dict -}}
{{- $_ := set $cddConfig "fullname" "cloud-data-discoverer" -}}
{{- $_ := set $cddConfig "image" (include "helm_lib_module_image" (list . "cloudDataDiscoverer")) -}}
{{- $_ := set $cddConfig "additionalEnv" (include "zvirt_cdd_envs" . | fromYamlArray) -}}
{{- $_ := set $cddConfig "additionalPodAnnotations" (include "zvirt_cdd_pod_annotations" . | fromYaml) -}}
{{- $_ := set $cddConfig "vpaEnabled" true -}}

{{- include "helm_lib_cloud_data_discoverer_manifests" (list . $cddConfig) }}
