{
 "title": "Capacity Planing",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "node",
    "label": "Nodes",
    "query": "label_values(up{job=\"node-exporter\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(kube_node_status_allocatable_cpu_cores{node=~\"$node\"}[$__interval]))",
     "legendFormat": "Allocatable CPU Cores"
    },
    {
     "expr": "sum(avg_over_time(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"}[$__interval]))",
     "legendFormat": "Requested CPU Cores"
    },
    {
     "expr": "sum\n(\n  (\n    (\n      sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"}[$__interval]))\n      -\n      sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{node=~\"$node\", container!=\"POD\"}[$__interval_rv]))\n    ) > 0\n  )\n)",
     "legendFormat": "Over-requested"
    },
    {
     "expr": "sum\n  (\n    (\n      (\n        sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{node=~\"$node\", container!=\"POD\"}[$__interval_rv]))\n        -\n        sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"}[$__interval]))\n      ) or sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{node=~\"$node\", container!=\"POD\"}[$__interval_rv]))\n    )\n    > 0\n  )",
     "legendFormat": "Under-requested"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(avg_over_time(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"}[$__interval])) / sum(avg_over_time(kube_node_status_allocatable_cpu_cores{node=~\"$node\"}[$__interval])) * 100"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(kube_node_status_allocatable_memory_bytes{node=~\"$node\"}[$__interval]))",
     "legendFormat": "Allocatable Memory"
    },
    {
     "expr": "sum(avg_over_time(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"}[$__interval]))",
     "legendFormat": "Requested Memory"
    },
    {
     "expr": "sum\n  (\n    (\n      sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"}[$__interval]))\n      -\n      sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{node=~\"$node\", container!=\"POD\"}[$__interval]))\n    ) > 0\n  )",
     "legendFormat": "Over-requested"
    },
    {
     "expr": "sum\n  (\n    (\n      (\n        sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{node=~\"$node\", container!=\"POD\"}[$__interval]))\n        -\n        sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"}[$__interval]))\n      ) or sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{node=~\"$node\", container!=\"POD\"}[$__interval]))\n    )\n    > 0\n  )",
     "legendFormat": "Under-requested"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(avg_over_time(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"}[$__interval])) / sum(avg_over_time(kube_node_status_allocatable_memory_bytes{node=~\"$node\"}[$__interval])) * 100"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (\n  max by (node, pod) (kube_pod_info{node=~\"$node\"} > 0) \n  and on(pod) \n  max by (pod) (kube_pod_status_phase{phase=~\"Running|Pending\"} > 0)\n)",
     "legendFormat": "Current number of Pods"
    },
    {
     "expr": "sum(avg_over_time(kube_node_status_capacity_pods{node=~\"$node\"}[$__interval]))",
     "legendFormat": "Maximum capacity of pods"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 16 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (sum(avg_over_time(kube_node_status_capacity_pods{node=~\"$node\"}[$__interval])) - sum(avg_over_time(kube_pod_info{node=~\"$node\"}[$__interval]))) / sum(avg_over_time(kube_node_status_capacity_pods{node=~\"$node\"}[$__interval])) * 100"
    }
   ]
  }
 ]
}