{
 "title": "Namespaces",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Average",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (namespace) (kube_controller_pod{namespace=~\"$namespace\"})",
     "legendFormat": "Namespace"
    },
    {
     "expr": "100 * count by (namespace) (sum by (namespace, vpa) (vpa_recommendation{namespace=~\"$namespace\", container!=\"POD\"})) / count by (namespace) (sum by (namespace, controller) (kube_controller_pod{namespace=~\"$namespace\"}))\nor\ncount (kube_controller_pod{namespace=~\"$namespace\"}) by (namespace) * 0",
     "legendFormat": "VPA %"
    },
    {
     "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container!=\"POD\"}[$__range]))\nor\ncount (kube_controller_pod{namespace=~\"$namespace\"}) by (namespace) * 0",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"}[$__range]))\nor count(kube_controller_pod{namespace=~\"$namespace\"}) by (namespace) * 0",
     "legendFormat": "Req CPU"
    },
    {
     "expr": "sum by (namespace)\n  (\n    (\n      sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"}[$__range]))\n      -\n      sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{container!=\"POD\", namespace=~\"$namespace\"}[$__range]))\n    ) > 0\n  )\nor count (kube_controller_pod{namespace=~\"$namespace\"}) by (namespace) * 0",
     "legendFormat": "Over-req CPU"
    },
    {
     "expr": "sum by (namespace)\n  (\n    (\n      (\n        sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{container!=\"POD\", namespace=~\"$namespace\"}[$__range]))\n        -\n        sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"}[$__range]))\n      ) or sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{container!=\"POD\", namespace=~\"$namespace\"}[$__range]))\n    )\n    > 0\n  )\nor count (kube_controller_pod{namespace=~\"$namespace\"}) by (namespace) * 0",
     "legendFormat": "Under-req CPU"
    },
    {
     "expr": "(sum by (namespace) (rate(container_cpu_cfs_throttled_periods_total{namespace=~\"$namespace\"}[$__range])) / sum by (namespace) (rate(container_cpu_cfs_periods_total{namespace=~\"$namespace\"}[$__range]))) * sum by (namespace) (kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\"})\nor\ncount (kube_controller_pod{namespace=~\"$namespace\"}) by (namespace) * 0",
     "legendFormat": "Throttling cores"
    },
    {
     "expr": "sum by (namespace) (avg_over_time(container_memory_working_set_bytes{namespace=~\"$namespace\", container!=\"POD\"}[$__range]))\nor\ncount (kube_controller_pod{namespace=~\"$namespace\"}) by (namespace) * 0",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\"}[$__range]))\nor count(kube_controller_pod{namespace=~\"$namespace\"}) by (namespace) * 0",
     "legendFormat": "Req Memory"
    },
    {
     "expr": "sum by (namespace)\n  (\n    (\n      sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\"}[$__range]))\n      -\n      sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{container!=\"POD\", namespace=~\"$namespace\"}[$__range]))\n    ) > 0\n  )\nor count(kube_controller_pod{namespace=~\"$namespace\"}) by (namespace) * 0",
     "legendFormat": "Over-req Memory"
    },
    {
     "expr": "sum by (namespace)\n  (\n    (\n      (\n        sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{container!=\"POD\", namespace=~\"$namespace\"}[$__range]))\n        -\n        sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\"}[$__range]))\n      ) or sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{container!=\"POD\", namespace=~\"$namespace\"}[$__range]))\n    )\n    > 0\n  )\nor count (kube_controller_pod{namespace=~\"$namespace\"}) by (namespace) * 0",
     "legendFormat": "Under-req Memory"
    },
    {
     "expr": "sum by (namespace) (rate(container_network_receive_bytes_total{namespace=~\"$namespace\"}[$__range]))\nor\ncount (kube_controller_pod{namespace=~\"$namespace\"}) by (namespace) * 0",
     "legendFormat": "RX Network"
    },
    {
     "expr": "sum by (namespace) (rate(container_network_transmit_bytes_total{namespace=~\"$namespace\"}[$__range]))\nor\ncount (kube_controller_pod{namespace=~\"$namespace\"}) by (namespace) * 0",
     "legendFormat": "TX Network"
    },
    {
     "expr": "sum by (namespace) (rate(container_fs_reads_total{namespace=~\"$namespace\", container!=\"POD\"}[$__range]))\nor\ncount (kube_controller_pod{namespace=~\"$namespace\"}) by (namespace) * 0",
     "legendFormat": "Read IOPS"
    },
    {
     "expr": "sum by (namespace) (rate(container_fs_writes_total{namespace=~\"$namespace\", container!=\"POD\"}[$__range]))\nor\ncount (kube_controller_pod{namespace=~\"$namespace\"}) by (namespace) * 0",
     "legendFormat": "Write IOPS"
    },
    {
     "expr": "sum by (namespace) (increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}[$__range]))\nor\ncount (kube_controller_pod{namespace=~\"$namespace\"}) by (namespace) * 0",
     "legendFormat": "Restart count"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Usage by namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Usage by state",
   "type": "graph",
   "description": "Total может быть не равен system + user из-за особенностей учета cgroup в ядре. Более детально можно почитать тут: https://www.kernel.org/doc/Documentation/cgroup-v1/cpuacct.txt",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_system_seconds_total{namespace=~\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
     "legendFormat": "System"
    },
    {
     "expr": "sum (rate(container_cpu_user_seconds_total{namespace=~\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
     "legendFormat": "User"
    },
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Over-requested by namespace",
   "type": "graph",
   "description": "На данном графике отображается запрошенные (requested) ресурсы CPU выше реального потребления CPU. По факту, сколько еще CPU необходимо \"застолбить\" для корректной работы сервиса.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace)\n  (\n    (\n      sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"}[$__interval]))\n      -\n      sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{container!=\"POD\", namespace=~\"$namespace\"}[$__interval_rv]))\n    ) > 0\n  )",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum\n(\n  (\n    (\n      sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"}[$__interval]))\n      -\n      sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{container!=\"POD\", namespace=~\"$namespace\"}[$__interval_rv]))\n    ) > 0\n  )\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Under-requested by namespace",
   "type": "graph",
   "description": "На данном графике отображается потребление CPU выше запрошенных (requested) ресурсов CPU. Т.е. по факту, сколько еще CPU необходимо \"застолбить\" для корректной работы сервиса.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace)\n  (\n    (\n      (\n        sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{container!=\"POD\", namespace=~\"$namespace\"}[$__interval_rv]))\n        -\n        sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"}[$__interval]))\n      ) or sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{container!=\"POD\", namespace=~\"$namespace\"}[$__interval_rv]))\n    )\n    > 0\n  )",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum\n  (\n    (\n      (\n        sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{container!=\"POD\", namespace=~\"$namespace\"}[$__interval_rv]))\n        -\n        sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"}[$__interval]))\n      ) or sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{container!=\"POD\", namespace=~\"$namespace\"}[$__interval_rv]))\n    )\n    > 0\n  )",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Throttling",
   "type": "graph",
   "description": "Если на графике нет данных, значит не заданы ресурсы для контейнеров",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "(sum by (namespace) (rate(container_cpu_cfs_throttled_periods_total{namespace=~\"$namespace\"}[$__interval_rv])) / sum by (namespace) (rate(container_cpu_cfs_periods_total{namespace=~\"$namespace\"}[$__interval_rv]))) * sum by (namespace) (kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\"})\n",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum ((rate(container_cpu_cfs_throttled_periods_total{namespace=~\"$namespace\"}[$__interval_rv])) / sum by (namespace) (rate(container_cpu_cfs_periods_total{namespace=~\"$namespace\"}[$__interval_rv]))) * sum by (namespace) (kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Pods count",
   "type": "graph",
   "description": "Количество подов в каждом namespace",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (namespace) (max_over_time(kube_pod_info{namespace=~\"$namespace\"}[$__interval]))",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "count(kube_pod_info{namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Namespaces CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 36 },
     "repeat": "namespace",
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 36 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 36 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 45 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 45 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 54 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 54 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 63 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 63 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 72 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 72 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 72 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 81 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 81 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 81 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 90 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 90 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 90 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 99 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 99 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 99 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 99 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 108 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 108 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 108 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 108 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 117 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 117 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 117 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 117 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 126 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 126 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 126 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(vpa_recommendation{container!=\"POD\", namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))",
       "legendFormat": "VPA Target"
      }
     ]
    }
   ]
  },
  {
   "title": "Namespaces CPU by state",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "$namespace",
     "type": "graph",
     "description": "Total может быть не равен system + user из-за особенностей учета cgroup в ядре. Более детально можно почитать тут: https://www.kernel.org/doc/Documentation/cgroup-v1/cpuacct.txt",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "repeat": "namespace",
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_system_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "System"
      },
      {
       "expr": "sum by (namespace) (rate(container_cpu_user_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "User"
      },
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "description": "Total может быть не равен system + user из-за особенностей учета cgroup в ядре. Более детально можно почитать тут: https://www.kernel.org/doc/Documentation/cgroup-v1/cpuacct.txt",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_system_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "System"
      },
      {
       "expr": "sum by (namespace) (rate(container_cpu_user_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "User"
      },
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Usage by namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (avg_over_time(container_memory_working_set_bytes{namespace=~\"$namespace\", container!=\"POD\"}[$__interval]))",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum (avg_over_time(container_memory_working_set_bytes{namespace=~\"$namespace\", container!=\"POD\"}[$__interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Usage by state",
   "type": "graph",
   "description": "Метрика Working set bytes - реально используемая память контейнером, так как включает active file memory. И пр достижении данного значения к лимиту, может прийти OOMKiller. Данное значение может быть выше RSS + Cache. Так как не вся active file memory является Cache.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (avg_over_time(container_memory_rss{namespace=~\"$namespace\", container!=\"POD\"}[$__interval]))",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum (avg_over_time(container_memory_cache{namespace=~\"$namespace\", container!=\"POD\"}[$__interval]))",
     "legendFormat": "Cache"
    },
    {
     "expr": "sum (avg_over_time(container_memory_swap{namespace=~\"$namespace\", container!=\"POD\"}[$__interval]))",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum (avg_over_time(container_memory_working_set_bytes{namespace=~\"$namespace\", container!=\"POD\"}[$__interval]))",
     "legendFormat": "Working set bytes"
    }
   ]
  },
  {
   "title": "Over-requested by namespace",
   "type": "graph",
   "description": "На данном графике отображается запрошенные (requested) ресурсы Memory выше реального потребления Memory. По факту, сколько еще Memory необходимо \"застолбить\" для корректной работы сервиса.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace)\n  (\n    (\n      sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\"}[$__interval]))\n      -\n      sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{container!=\"POD\", namespace=~\"$namespace\"}[$__interval]))\n    ) > 0\n  )",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum\n  (\n    (\n      sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\"}[$__interval]))\n      -\n      sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{container!=\"POD\", namespace=~\"$namespace\"}[$__interval]))\n    ) > 0\n  )",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Under-requested by namespace",
   "type": "graph",
   "description": "На данном графике отображается потребление Memory выше запрошенных (requested) ресурсов Memory. Т.е. по факту, сколько еще Memory необходимо \"застолбить\" для корректной работы сервиса.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace)\n  (\n    (\n      (\n        sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{container!=\"POD\", namespace=~\"$namespace\"}[$__interval]))\n        -\n        sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\"}[$__interval]))\n      ) or sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{container!=\"POD\", namespace=~\"$namespace\"}[$__interval]))\n    )\n    > 0\n  )",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum\n  (\n    (\n      (\n        sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{container!=\"POD\", namespace=~\"$namespace\"}[$__interval]))\n        -\n        sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\"}[$__interval]))\n      ) or sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{container!=\"POD\", namespace=~\"$namespace\"}[$__interval]))\n    )\n    > 0\n  )",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Namespaces Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "$namespace",
     "type": "graph",
     "description": "Метрика Working set bytes - реально используемая память контейнером, так как включает active file memory. И пр достижении данного значения к лимиту, может прийти OOMKiller. Данное значение может быть выше RSS + Cache. Так как не вся active file memory является Cache.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
     "repeat": "namespace",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (avg_over_time(container_memory_rss{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))",
       "legendFormat": "RSS"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(container_memory_cache{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))",
       "legendFormat": "Cache"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(container_memory_swap{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))",
       "legendFormat": "Swap"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))",
       "legendFormat": "Working set bytes"
      },
      {
       "expr": "sum by(namespace) (avg_over_time(vpa_recommendation{namespace=\"$namespace\", container!=\"POD\", resource_type=\"memory\", recommendation_type=\"target\"}[$__interval]))",
       "legendFormat": "VPA Target"
      },
      {
       "expr": "sum by(namespace) (avg_over_time(kube_pod_container_resource_requests_memory_bytes{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by(namespace) (avg_over_time(kube_pod_container_resource_limits_memory_bytes{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "$namespace",
     "type": "graph",
     "description": "Метрика Working set bytes - реально используемая память контейнером, так как включает active file memory. И пр достижении данного значения к лимиту, может прийти OOMKiller. Данное значение может быть выше RSS + Cache. Так как не вся active file memory является Cache.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (avg_over_time(container_memory_rss{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))",
       "legendFormat": "RSS"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(container_memory_cache{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))",
       "legendFormat": "Cache"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(container_memory_swap{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))",
       "legendFormat": "Swap"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))",
       "legendFormat": "Working set bytes"
      },
      {
       "expr": "sum by(namespace) (avg_over_time(vpa_recommendation{namespace=\"$namespace\", container!=\"POD\", resource_type=\"memory\", recommendation_type=\"target\"}[$__interval]))",
       "legendFormat": "VPA Target"
      },
      {
       "expr": "sum by(namespace) (avg_over_time(kube_pod_container_resource_requests_memory_bytes{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by(namespace) (avg_over_time(kube_pod_container_resource_limits_memory_bytes{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Limits"
      }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Receive",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (rate(container_network_receive_bytes_total{namespace=~\"$namespace\"}[$__interval_rv]))",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum (rate(container_network_receive_bytes_total{namespace=~\"$namespace\"}[$__interval_rv]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Transmit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (rate(container_network_transmit_bytes_total{namespace=~\"$namespace\"}[$__interval_rv]))",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum (rate(container_network_transmit_bytes_total{namespace=~\"$namespace\"}[$__interval_rv]))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "IOPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (rate(container_fs_reads_total{namespace=~\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum (rate(container_fs_reads_total{namespace=~\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (rate(container_fs_writes_total{namespace=~\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum (rate(container_fs_writes_total{namespace=~\"$namespace\", container!=\"POD\"}[$__interval_rv]))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "PVC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "PVC Provisioned (except local storage classes)",
   "type": "graph",
   "description": "На данном графике не отображается информация о дисках, со StorageClass с названием (/local.+/), так как в local storage дисках потребленное место рассчитывается неверно. \n\nТут рисуются ТОЛЬКО используемые в данный момент (НЕ local storage) диски.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (\n  (\n    sum by (namespace, persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes)\n    * on (namespace, persistentvolumeclaim)\n    sum by (namespace, persistentvolume, persistentvolumeclaim) (\n      label_replace(\n        max_over_time(kube_persistentvolumeclaim_info{namespace=~\"$namespace\", storageclass!~\"local.+\"}[$__interval]),\n        \"persistentvolume\", \"$1\", \"volumename\", \"(.*)\")\n    )\n  )\n  or on(namespace, persistentvolumeclaim) (\n    sum by (persistentvolume) (\n      max_over_time(kube_persistentvolume_capacity_bytes[$__interval])\n    )\n    * on(persistentvolume) group_left(namespace, persistentvolumeclaim)\n    sum by (namespace, persistentvolume, persistentvolumeclaim) (\n      label_replace(\n        max_over_time(kube_persistentvolumeclaim_info{namespace=~\"$namespace\", storageclass!~\"local.+\"}[$__interval]),\n        \"persistentvolume\", \"$1\", \"volumename\", \"(.*)\")\n    )\n  )\n)",
     "legendFormat": "Provisioned {{ namespace }}"
    },
    {
     "expr": "sum(\n  sum by (namespace) (\n    (\n      sum by (namespace, persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes)\n      * on (namespace, persistentvolumeclaim)\n      sum by (namespace, persistentvolume, persistentvolumeclaim) (\n        label_replace(\n          max_over_time(kube_persistentvolumeclaim_info{namespace=~\"$namespace\", storageclass!~\"local.+\"}[$__interval]),\n          \"persistentvolume\", \"$1\", \"volumename\", \"(.*)\")\n      )\n    )\n    or on(namespace, persistentvolumeclaim) (\n      sum by (persistentvolume) (\n        max_over_time(kube_persistentvolume_capacity_bytes[$__interval])\n      )\n      * on(persistentvolume) group_left(namespace, persistentvolumeclaim)\n      sum by (namespace, persistentvolume, persistentvolumeclaim) (\n        label_replace(\n          max_over_time(kube_persistentvolumeclaim_info{namespace=~\"$namespace\", storageclass!~\"local.+\"}[$__interval]),\n          \"persistentvolume\", \"$1\", \"volumename\", \"(.*)\")\n      )\n    )\n  )\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "PVC Used (except local storage classes)",
   "type": "graph",
   "description": "На данном графике не отображается информация о дисках, со StorageClass с названием (/local.+/), так как в local storage дисках потребленное место рассчитывается неверно. \n\nТут рисуются ТОЛЬКО используемые в данный момент (НЕ local storage) диски.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (\n  sum by (namespace, persistentvolumeclaim) (\n    max_over_time(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"}[$__interval])\n  )\n  * on (namespace, persistentvolumeclaim) group_left(persistentvolume)\n\tsum by (namespace, persistentvolume, persistentvolumeclaim) (\n\t\tlabel_replace(\n\t\t\tmax_over_time(kube_persistentvolumeclaim_info{namespace=~\"$namespace\", storageclass!~\"local.+\"}[$__interval]),\n\t\t\t\"persistentvolume\", \"$1\", \"volumename\", \"(.*)\")\n\t)\n)",
     "legendFormat": "Usage {{ namespace }}"
    },
    {
     "expr": "sum(\n  sum by (namespace) (\n    sum by (namespace, persistentvolumeclaim) (\n      max_over_time(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"}[$__interval])\n    )\n   \t* on (namespace, persistentvolumeclaim) group_left(persistentvolume)\n\t\tsum by (namespace, persistentvolume, persistentvolumeclaim) (\n\t\t\tlabel_replace(\n\t\t\t\tmax_over_time(kube_persistentvolumeclaim_info{namespace=~\"$namespace\", storageclass!~\"local.+\"}[$__interval]), \n\t\t\t\t\"persistentvolume\", \"$1\", \"volumename\", \"(.*)\")\n\t\t)\n  )\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "PVC Used in % (except local storage classes)",
   "type": "graph",
   "description": "На данном графике не отображается информация о дисках, со StorageClass с названием (/local.+/), так как в local storage дисках потребленное место рассчитывается неверно. \n\nТут рисуются ТОЛЬКО используемые в данный момент (НЕ local storage) диски.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (\n  sum by (namespace, persistentvolumeclaim) (\n    max_over_time(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"}[$__interval])\n  )\n  * on (namespace, persistentvolumeclaim)\n\tsum by (namespace, persistentvolumeclaim) (\n\t\tlabel_replace(\n\t\t\tmax_over_time(\n\t\t\t\tkube_persistentvolumeclaim_info{namespace=~\"$namespace\", storageclass!~\"local.+\"}[$__interval]),\n\t\t\t\t\"persistentvolume\", \"$1\", \"volumename\", \"(.*)\")\n\t)\n)\n/\nsum by (namespace) (\n  sum by (namespace, persistentvolumeclaim) (\n    max_over_time(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"}[$__interval])\n  )\n  * on (namespace, persistentvolumeclaim)\n\tsum by (namespace, persistentvolumeclaim) (\n\t\tlabel_replace(\n\t\t\tmax_over_time(\n\t\t\t\tkube_persistentvolumeclaim_info{namespace=~\"$namespace\", storageclass!~\"local.+\"}[$__interval]),\n\t\t\t\t\"persistentvolume\", \"$1\", \"volumename\", \"(.*)\")\n\t)\n)",
     "legendFormat": "Usage {{ namespace }}"
    }
   ]
  }
 ]
}