{
 "title": "Namespace",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "controller_type",
    "label": "Controller Type",
    "query": "label_values(kube_controller_pod{namespace=~\"$namespace\"}, controller_type)"
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": "label_values(kube_controller_pod{namespace=~\"$namespace\", controller_type=~\"$controller_type\"}, controller)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}, pod)"
   },
   {
    "name": "persistentvolumeclaim",
    "label": "PersistentVolumeClaim",
    "query": "label_values(kube_persistentvolumeclaim_info{namespace=\"$namespace\"}, persistentvolumeclaim)"
   }
  ]
 },
 "panels": [
  {
   "title": "Controllers",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (job, namespace, controller, controller_name) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"})",
     "legendFormat": "Controller"
    },
    {
     "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (vpa_recommendation{namespace=\"$namespace\", update_policy=\"Off\"})) * 0\nor\nsum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (vpa_recommendation{namespace=\"$namespace\", update_policy=\"Initial\"})) * 0 + 1\nor\nsum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (vpa_recommendation{namespace=\"$namespace\", update_policy=\"Auto\"})) * 0 + 2\nor\nsum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (vpa_recommendation{namespace=\"$namespace\", update_policy=\"Recreate\"})) * 0 + 3",
     "legendFormat": "VPA Mode"
    },
    {
     "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__range])))\nor\ncount (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}) by (controller) * 0",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}\n    * on (pod) group_left()\n    sum by (pod) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}[$__range]))\n  )\nor\ncount (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}) by (controller) * 0",
     "legendFormat": "Req CPU"
    },
    {
     "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}\n    * on (pod) group_left()\n    sum by(pod) (avg_over_time(vpa_recommendation{container!=\"POD\",namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__range]))\n  ) \nor\ncount (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}) by (controller) * 0",
     "legendFormat": "VPA CPU"
    },
    {
     "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}\n    * on (namespace, pod) group_left()\n    sum by (namespace, pod)\n      (\n        (\n          sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}[$__range]))\n          -\n          sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{container!=\"POD\", namespace=\"$namespace\"}[$__range]))\n        ) > 0\n      )\n  )\nor\ncount (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}) by (controller) * 0",
     "legendFormat": "Over-req CPU"
    },
    {
     "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}\n    * on (namespace, pod) group_left()\n    sum by (namespace, pod)\n      (\n        (\n          (\n            sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[$__range]))\n            -\n            sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__range]))\n          ) or sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{container!=\"POD\", namespace=\"$namespace\"}[$__range]))\n        ) > 0\n      )\n  )\nor\ncount (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}) by (controller) * 0",
     "legendFormat": "Under-req CPU"
    },
    {
     "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() ((sum by (pod) (rate(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\"}[$__range])) / sum by (pod) (rate(container_cpu_cfs_periods_total{namespace=\"$namespace\"}[$__range]))) * sum by (pod) (kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"})))\nor\ncount (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}) by (controller) * 0",
     "legendFormat": "Throttling cores"
    },
    {
     "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"POD\"}[$__range])))\nor\ncount (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}) by (controller) * 0",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}\n    * on (pod) group_left()\n    sum by (namespace, pod)\n      (\n        avg_over_time(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", container!=\"POD\"}[$__range])\n      )\n    )\n  or\n  count (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}) by (controller) * 0",
     "legendFormat": "Req Memory"
    },
    {
     "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}\n    * on (pod) group_left()\n    sum by(pod) (avg_over_time(vpa_recommendation{container!=\"POD\",namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"memory\"}[$__range]))\n  ) \n  or  \ncount (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}) by (controller) * 0",
     "legendFormat": "VPA Memory"
    },
    {
     "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}\n    * on (namespace, pod) group_left()\n    sum by (namespace, pod)\n      (\n        (\n          sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}[$__range]))\n          -\n          sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{container!=\"POD\", namespace=\"$namespace\"}[$__range]))\n        ) > 0\n      )\n  )\nor\ncount (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}) by (controller) * 0",
     "legendFormat": "Over-req Memory"
    },
    {
     "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}\n    * on (namespace, pod) group_left()\n    sum by (namespace, pod)\n      (\n        (\n          (\n            sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\"}[$__range]))\n            -\n            sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_memory_bytes{container!=\"POD\", namespace=\"$namespace\"}[$__range]))\n          ) or sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{container!=\"POD\", namespace=\"$namespace\"}[$__range]))\n        ) > 0\n      )\n  )\nor\ncount (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}) by (controller) * 0",
     "legendFormat": "Under-req Memory"
    },
    {
     "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[$__range])))\nor\ncount (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}) by (controller) * 0",
     "legendFormat": "RX Network"
    },
    {
     "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[$__range])))\nor\ncount (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}) by (controller) * 0",
     "legendFormat": "TX Network"
    },
    {
     "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_fs_reads_total{container!=\"POD\", namespace=\"$namespace\"}[$__range])))\nor\ncount (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}) by (controller) * 0",
     "legendFormat": "Read IOPS"
    },
    {
     "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_fs_writes_total{container!=\"POD\", namespace=\"$namespace\"}[$__range])))\nor\ncount (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}) by (controller) * 0",
     "legendFormat": "Write IOPS"
    },
    {
     "expr": "(max by (job, namespace, controller_type, controller_name) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}) * on(controller_type, controller_name) kube_controller_replicas{namespace=\"$namespace\"})\nor\nmax by (controller_type, controller_name) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}) * 0",
     "legendFormat": "Total replicas count"
    },
    {
     "expr": "((max by (job, namespace, controller_type, controller_name, controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"})) *  on (job, namespace, controller_type, controller_name) group_right(controller)\n(kube_controller_replicas - kube_controller_replicas_ready))\nor\nmax by (job, namespace, controller_type, controller_name, controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}) * 0",
     "legendFormat": "Not ready replicas"
    },
    {
     "expr": "sum by (controller) \n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}\n    * on (pod) group_left()\n    sum by (pod) (increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[$__range]))\n  )\nor\ncount (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}) by (controller) * 0",
     "legendFormat": "Pod restart count"
    }
   ]
  },
  {
   "title": "Status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "((max by (job, namespace, controller_type, controller_name, controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"})) *  on (job, namespace, controller_type, controller_name) group_right(controller) \n(kube_controller_replicas_ready/kube_controller_replicas == 1)) * 1",
     "legendFormat": "{{ controller }}"
    },
    {
     "expr": "((max by (job, namespace, controller_type, controller_name, controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"})) *  on (job, namespace, controller_type, controller_name) group_right(controller) \n((kube_controller_replicas_ready/kube_controller_replicas >   0) and  (kube_controller_replicas_ready/kube_controller_replicas <  0.3)) > bool 0)  * 2",
     "legendFormat": "{{ controller }}"
    },
    {
     "expr": "((max by (job, namespace, controller_type, controller_name, controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"})) *  on (job, namespace, controller_type, controller_name) group_right(controller) \n((kube_controller_replicas_ready/kube_controller_replicas >=   0.3) and  (kube_controller_replicas_ready/kube_controller_replicas <  0.6)) > bool 0)  * 3",
     "legendFormat": "{{ controller }}"
    },
    {
     "expr": "((max by (job, namespace, controller_type, controller_name, controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"})) *  on (job, namespace, controller_type, controller_name) group_right(controller) \n((kube_controller_replicas_ready/kube_controller_replicas >=   0.6) and  (kube_controller_replicas_ready/kube_controller_replicas <  1)) > bool 0)  * 4",
     "legendFormat": "{{ controller }}"
    },
    {
     "expr": "((max by (job, namespace, controller_type, controller_name, controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"})) *  on (job, namespace, controller_type, controller_name) group_right(controller)\n(kube_controller_replicas_ready/kube_controller_replicas == 0)) * 5",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Usage by controller",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv])))",
     "legendFormat": "{{ controller }}"
    },
    {
     "expr": "sum (sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Usage by state",
   "type": "graph",
   "description": "Total может быть не равен system + user из-за особенностей учета cgroup в ядре. Более детально можно почитать тут: https://www.kernel.org/doc/Documentation/cgroup-v1/cpuacct.txt",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_system_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))))",
     "legendFormat": "System"
    },
    {
     "expr": "sum (sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_user_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))))",
     "legendFormat": "User"
    },
    {
     "expr": "sum (sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv]))))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Over-requested by controller",
   "type": "graph",
   "description": "На данном графике отображается запрошенные (requested) ресурсы CPU выше реального потребления CPU. По факту, сколько еще CPU необходимо \"застолбить\" для корректной работы сервиса.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}\n    * on (namespace, pod) group_left()\n    sum by (namespace, pod)\n      (\n        (\n          sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}[$__interval]))\n          -\n          sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{container!=\"POD\", namespace=\"$namespace\"}[$__interval_rv]))\n        ) > 0\n      )\n  )",
     "legendFormat": "{{ controller }}"
    },
    {
     "expr": "sum\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}\n    * on (namespace, pod) group_left()\n    sum by (namespace, pod)\n      (\n        (\n          sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}[$__interval]))\n          -\n          sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{container!=\"POD\", namespace=\"$namespace\"}[$__interval_rv]))\n        ) > 0\n      )\n  )",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Under-requested by controller",
   "type": "graph",
   "description": "На данном графике отображается потребление CPU выше запрошенных (requested) ресурсов CPU. Т.е. по факту, сколько еще CPU необходимо \"застолбить\" для корректной работы сервиса.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}\n    * on (namespace, pod) group_left()\n    sum by (namespace, pod)\n      (\n        (\n          (\n            sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[$__interval_rv]))\n            -\n            sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))\n          ) or sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{container!=\"POD\", namespace=\"$namespace\"}[$__interval_rv]))\n        ) > 0\n      )\n  )",
     "legendFormat": "{{ controller }}"
    },
    {
     "expr": "sum\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}\n    * on (namespace, pod) group_left()\n    sum by (namespace, pod)\n      (\n        (\n          (\n            sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[$__interval_rv]))\n            -\n            sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))\n          ) or sum by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{container!=\"POD\", namespace=\"$namespace\"}[$__interval_rv]))\n        ) > 0\n      )\n  )",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Throttling",
   "type": "graph",
   "description": "Если на графике нет данных, значит не заданы ресурсы для контейнеров",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() ((sum by (pod) (rate(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\"}[$__interval_rv])) / sum by (pod) (rate(container_cpu_cfs_periods_total{namespace=\"$namespace\"}[$__interval_rv]))) * sum by (pod) (kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"})))",
     "legendFormat": "{{ controller }}"
    },
    {
     "expr": "sum (sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() ((sum by (pod) (rate(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\"}[$__interval_rv])) / sum by (pod) (rate(container_cpu_cfs_periods_total{namespace=\"$namespace\"}[$__interval_rv]))) * sum by (pod) (kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}))))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Controllers CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "$controller",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 43 },
     "repeat": "controller",
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv])))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by(pod) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\",namespace=\"$namespace\"}[$__interval]))\n  )",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by(pod) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\",namespace=\"$namespace\"}[$__interval]))\n  )",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by(pod) (avg_over_time(vpa_recommendation{container!=\"POD\",namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))\n  )",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$controller",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 43 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv])))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by(pod) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\",namespace=\"$namespace\"}[$__interval]))\n  )",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by(pod) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\",namespace=\"$namespace\"}[$__interval]))\n  )",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by(pod) (avg_over_time(vpa_recommendation{container!=\"POD\",namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))\n  )",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$controller",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv])))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by(pod) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\",namespace=\"$namespace\"}[$__interval]))\n  )",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by(pod) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\",namespace=\"$namespace\"}[$__interval]))\n  )",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by(pod) (avg_over_time(vpa_recommendation{container!=\"POD\",namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))\n  )",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$controller",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 43 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv])))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by(pod) (avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\",namespace=\"$namespace\"}[$__interval]))\n  )",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by(pod) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"POD\",namespace=\"$namespace\"}[$__interval]))\n  )",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by(pod) (avg_over_time(vpa_recommendation{container!=\"POD\",namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"cpu\"}[$__interval]))\n  )",
       "legendFormat": "VPA Target"
      }
     ]
    }
   ]
  },
  {
   "title": "Controllers CPU by state",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "$controller",
     "type": "graph",
     "description": "Total может быть не равен system + user из-за особенностей учета cgroup в ядре. Более детально можно почитать тут: https://www.kernel.org/doc/Documentation/cgroup-v1/cpuacct.txt",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 44 },
     "repeat": "controller",
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_system_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv])))",
       "legendFormat": "System"
      },
      {
       "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_user_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv])))",
       "legendFormat": "User"
      },
      {
       "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv])))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "$controller",
     "type": "graph",
     "description": "Total может быть не равен system + user из-за особенностей учета cgroup в ядре. Более детально можно почитать тут: https://www.kernel.org/doc/Documentation/cgroup-v1/cpuacct.txt",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 44 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_system_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv])))",
       "legendFormat": "System"
      },
      {
       "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_user_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv])))",
       "legendFormat": "User"
      },
      {
       "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv])))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "$controller",
     "type": "graph",
     "description": "Total может быть не равен system + user из-за особенностей учета cgroup в ядре. Более детально можно почитать тут: https://www.kernel.org/doc/Documentation/cgroup-v1/cpuacct.txt",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 44 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_system_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv])))",
       "legendFormat": "System"
      },
      {
       "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_user_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv])))",
       "legendFormat": "User"
      },
      {
       "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\"}[$__interval_rv])))",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Usage by controller",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}\n    * on (pod) group_left()\n    sum by (pod) (avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))\n  )",
     "legendFormat": "{{ controller }}"
    },
    {
     "expr": "sum\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}\n    * on (pod) group_left()\n    sum by (pod) (avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))\n  )",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Usage by state",
   "type": "graph",
   "description": "Метрика Working set bytes - реально используемая память контейнером, так как включает active file memory. И пр достижении данного значения к лимиту, может прийти OOMKiller. Данное значение может быть выше RSS + Cache. Так как не вся active file memory является Cache.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}\n    * on (pod) group_left()\n    sum by (pod) (avg_over_time(container_memory_rss{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))\n  )",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum \n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}\n    * on (pod) group_left()\n    sum by (pod) (avg_over_time(container_memory_cache{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))\n  )",
     "legendFormat": "Cache"
    },
    {
     "expr": "sum \n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}\n    * on (pod) group_left()\n    sum by (pod) (avg_over_time(container_memory_swap{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))\n  )",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum \n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}\n    * on (pod) group_left()\n    sum by (pod) (avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))\n  )",
     "legendFormat": "Working set bytes"
    }
   ]
  },
  {
   "title": "Over-requested by controller",
   "type": "graph",
   "description": "На данном графике отображается запрошенные (requested) ресурсы Memory выше реального потребления Memory. По факту, сколько еще Memory необходимо \"застолбить\" для корректной работы сервиса.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}\n    * on (namespace, pod) group_left()\n    sum by (namespace, pod)\n      (\n        (\n          sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}[$__interval]))\n          -\n          sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))\n        ) > 0\n      )\n  )",
     "legendFormat": "{{ controller }}"
    },
    {
     "expr": "sum\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}\n    * on (namespace, pod) group_left()\n    sum by (namespace, pod)\n      (\n        (\n          sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}[$__interval]))\n          -\n          sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))\n        ) > 0\n      )\n  )",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Under-requested by controller",
   "type": "graph",
   "description": "На данном графике отображается потребление Memory выше запрошенных (requested) ресурсов Memory. Т.е. по факту, сколько еще Memory необходимо \"застолбить\" для корректной работы сервиса.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (controller)\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}\n    * on (namespace, pod) group_left()\n    sum by (namespace, pod)\n      (\n        (\n          (\n            sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\"}[$__interval]))\n            -\n            sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_memory_bytes{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))\n          ) or sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))\n        ) > 0\n      )\n  )",
     "legendFormat": "{{ controller }}"
    },
    {
     "expr": "sum\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"}\n    * on (namespace, pod) group_left()\n    sum by (namespace, pod)\n      (\n        (\n          (\n            sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\"}[$__interval]))\n            -\n            sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests_memory_bytes{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))\n          ) or sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{container!=\"POD\", namespace=\"$namespace\"}[$__interval]))\n        ) > 0\n      )\n  )",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Controllers Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "$controller",
     "type": "graph",
     "description": "Метрика Working set bytes - реально используемая память контейнером, так как включает active file memory. И пр достижении данного значения к лимиту, может прийти OOMKiller. Данное значение может быть выше RSS + Cache. Так как не вся active file memory является Cache.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 63 },
     "repeat": "controller",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum \n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left() \n    sum by (pod) (avg_over_time(container_memory_rss{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))\n  )",
       "legendFormat": "RSS"
      },
      {
       "expr": "sum\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"} \n    * on (pod) group_left() \n    sum by (pod) (avg_over_time(container_memory_cache{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))\n  )",
       "legendFormat": "Cache"
      },
      {
       "expr": "sum \n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left() \n    sum by (pod) (avg_over_time(container_memory_swap{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))\n  )",
       "legendFormat": "Swap"
      },
      {
       "expr": "sum \n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by (pod) (avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))\n  )",
       "legendFormat": "Working set bytes"
      },
      {
       "expr": "sum \n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by(pod) (avg_over_time(kube_pod_container_resource_requests_memory_bytes{container!=\"POD\",namespace=\"$namespace\"}[$__interval]))\n  ) ",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"} \n    * on (pod) group_left() \n    sum by(pod) (avg_over_time(kube_pod_container_resource_limits_memory_bytes{container!=\"POD\",namespace=\"$namespace\"}[$__interval]))\n  )",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum \n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by(pod) (avg_over_time(vpa_recommendation{container!=\"POD\",namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"memory\"}[$__interval]))\n  )",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$controller",
     "type": "graph",
     "description": "Метрика Working set bytes - реально используемая память контейнером, так как включает active file memory. И пр достижении данного значения к лимиту, может прийти OOMKiller. Данное значение может быть выше RSS + Cache. Так как не вся active file memory является Cache.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 63 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum \n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left() \n    sum by (pod) (avg_over_time(container_memory_rss{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))\n  )",
       "legendFormat": "RSS"
      },
      {
       "expr": "sum\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"} \n    * on (pod) group_left() \n    sum by (pod) (avg_over_time(container_memory_cache{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))\n  )",
       "legendFormat": "Cache"
      },
      {
       "expr": "sum \n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left() \n    sum by (pod) (avg_over_time(container_memory_swap{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))\n  )",
       "legendFormat": "Swap"
      },
      {
       "expr": "sum \n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by (pod) (avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))\n  )",
       "legendFormat": "Working set bytes"
      },
      {
       "expr": "sum \n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by(pod) (avg_over_time(kube_pod_container_resource_requests_memory_bytes{container!=\"POD\",namespace=\"$namespace\"}[$__interval]))\n  ) ",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"} \n    * on (pod) group_left() \n    sum by(pod) (avg_over_time(kube_pod_container_resource_limits_memory_bytes{container!=\"POD\",namespace=\"$namespace\"}[$__interval]))\n  )",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum \n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by(pod) (avg_over_time(vpa_recommendation{container!=\"POD\",namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"memory\"}[$__interval]))\n  )",
       "legendFormat": "VPA Target"
      }
     ]
    },
    {
     "title": "$controller",
     "type": "graph",
     "description": "Метрика Working set bytes - реально используемая память контейнером, так как включает active file memory. И пр достижении данного значения к лимиту, может прийти OOMKiller. Данное значение может быть выше RSS + Cache. Так как не вся active file memory является Cache.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 63 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum \n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left() \n    sum by (pod) (avg_over_time(container_memory_rss{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))\n  )",
       "legendFormat": "RSS"
      },
      {
       "expr": "sum\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"} \n    * on (pod) group_left() \n    sum by (pod) (avg_over_time(container_memory_cache{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))\n  )",
       "legendFormat": "Cache"
      },
      {
       "expr": "sum \n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left() \n    sum by (pod) (avg_over_time(container_memory_swap{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))\n  )",
       "legendFormat": "Swap"
      },
      {
       "expr": "sum \n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by (pod) (avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"POD\"}[$__interval]))\n  )",
       "legendFormat": "Working set bytes"
      },
      {
       "expr": "sum \n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by(pod) (avg_over_time(kube_pod_container_resource_requests_memory_bytes{container!=\"POD\",namespace=\"$namespace\"}[$__interval]))\n  ) ",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum\n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"} \n    * on (pod) group_left() \n    sum by(pod) (avg_over_time(kube_pod_container_resource_limits_memory_bytes{container!=\"POD\",namespace=\"$namespace\"}[$__interval]))\n  )",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum \n  (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_left()\n    sum by(pod) (avg_over_time(vpa_recommendation{container!=\"POD\",namespace=\"$namespace\", recommendation_type=\"target\", resource_type=\"memory\"}[$__interval]))\n  )",
       "legendFormat": "VPA Target"
      }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Recieve",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[$__interval_rv])))",
     "legendFormat": "{{ controller }}"
    },
    {
     "expr": "sum (sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[$__interval_rv]))))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Transmit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[$__interval_rv])))",
     "legendFormat": "{{ controller }}"
    },
    {
     "expr": "sum (sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[$__interval_rv]))))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "IOPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_fs_reads_total{container!=\"POD\", namespace=\"$namespace\"}[$__interval_rv])))",
     "legendFormat": "{{ controller }}"
    },
    {
     "expr": "sum (sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_fs_reads_total{container!=\"POD\", namespace=\"$namespace\"}[$__interval_rv]))))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_fs_writes_total{container!=\"POD\", namespace=\"$namespace\"}[$__interval_rv])))",
     "legendFormat": "{{ controller }}"
    },
    {
     "expr": "sum (sum by (controller) (kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} * on (pod) group_left() sum by (pod) (rate(container_fs_writes_total{container!=\"POD\", namespace=\"$namespace\"}[$__interval_rv]))))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "PVC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "PVC Provisioned (except local storage classes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, controller) (\n  max by (namespace, controller, persistentvolumeclaim)\n  (\n    sum by (namespace, persistentvolumeclaim) (\n        max_over_time(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"}[$__interval])\n    ) \n\n    * max by (namespace, persistentvolumeclaim) (\n        max_over_time(kube_persistentvolumeclaim_info{namespace=\"$namespace\", storageclass!~\"local.+\"}[$__interval])\n    )\n\n        * on (namespace, persistentvolumeclaim) group_left(pod) \n    max by (namespace, persistentvolumeclaim, pod) (\n         max_over_time(kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$namespace\"}[$__interval])\n    ) \n\n       * on (namespace, pod) group_left(controller)\n      kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} \n  )\n)",
     "legendFormat": "Provisioned {{ controller }}"
    },
    {
     "expr": "sum (\n  sum by (namespace, persistentvolumeclaim) (\n    max_over_time(kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=\"$namespace\"}[$__interval])\n  ) \n  * \n  sum by (namespace, persistentvolumeclaim) (\n    max_over_time(kube_persistentvolumeclaim_info{namespace=\"$namespace\", storageclass!~\"local.+\"}[$__interval])\n  )\n  unless\n  sum by (namespace, persistentvolumeclaim) (\n    max_over_time(kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$namespace\"}[$__interval])\n  ) \n)",
     "legendFormat": "Unused PVC"
    },
    {
     "expr": "sum (\n  sum by (namespace, controller) (\n    max by (namespace, controller, persistentvolumeclaim)\n    (\n      sum by (namespace, persistentvolumeclaim) (\n          max_over_time(kubelet_volume_stats_capacity_bytes{namespace=\"wtis-test-16\"}[30s])\n      ) \n\n      * max by (namespace, persistentvolumeclaim) (\n          max_over_time(kube_persistentvolumeclaim_info{namespace=\"wtis-test-16\", storageclass!~\"local.+\"}[30s])\n      )\n\n      * on (namespace, persistentvolumeclaim) group_left(pod) \n      max by (namespace, persistentvolumeclaim, pod) (\n         max_over_time(kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"wtis-test-16\"}[30s])\n      ) \n\n      * on (namespace, pod) group_left(controller)\n      kube_controller_pod{namespace=\"wtis-test-16\", controller=~\".*\"} \n    )\n  )\n)\n+\nsum (\n  sum by (namespace, persistentvolumeclaim) (\n    max_over_time(kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=\"wtis-test-16\"}[30s])\n  ) \n  * \n  sum by (namespace, persistentvolumeclaim) (\n    max_over_time(kube_persistentvolumeclaim_info{namespace=\"wtis-test-16\", storageclass!~\"local.+\"}[30s])\n  )\n  unless\n  sum by (namespace, persistentvolumeclaim) (\n    max_over_time(kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"wtis-test-16\"}[30s])\n  ) \n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "PVC Usage (except local storage classes)",
   "type": "graph",
   "description": "На данном графике не отображается информация о дисках, со StorageClass с названием (/local.+/), так как в local storage дисках потребленное место рассчитывается неверно. \n\nТут рисуются ТОЛЬКО используемые в данный момент (НЕ local storage) диски.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, controller) (\n  max by (namespace, controller, persistentvolumeclaim)\n  (\n    sum by (namespace, persistentvolumeclaim) (\n        max_over_time(kubelet_volume_stats_used_bytes{namespace=\"$namespace\"}[$__interval])\n    ) \n\n    * max by (namespace, persistentvolumeclaim) (\n        max_over_time(kube_persistentvolumeclaim_info{namespace=\"$namespace\", storageclass!~\"local.+\"}[$__interval])\n    )\n\n        * on (namespace, persistentvolumeclaim) group_left(pod) \n    max by (namespace, persistentvolumeclaim, pod) (\n         max_over_time(kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$namespace\"}[$__interval])\n    ) \n\n       * on (namespace, pod) group_left(controller)\n      kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} \n  )\n)",
     "legendFormat": "Usage {{ controller }}"
    },
    {
     "expr": "sum(\n  sum by (namespace, controller) (\n    max by (namespace, controller, persistentvolumeclaim)\n    (\n      sum by (namespace, persistentvolumeclaim) (\n        max_over_time(kubelet_volume_stats_used_bytes{namespace=\"$namespace\"}[$__interval])\n      ) \n\n      * max by (namespace, persistentvolumeclaim) (\n        max_over_time(kube_persistentvolumeclaim_info{namespace=\"$namespace\", storageclass!~\"local.+\"}[$__interval])\n      )\n\n      * on (namespace, persistentvolumeclaim) group_left(pod) \n      max by (namespace, persistentvolumeclaim, pod) (\n        max_over_time(kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$namespace\"}[$__interval])\n      ) \n\n      * on (namespace, pod) group_left(controller)\n      kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} \n    )\n  )\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "PVC Usage in % (except local storage classes)",
   "type": "graph",
   "description": "На данном графике не отображается информация о дисках, со StorageClass с названием (/local.+/), так как в local storage дисках потребленное место рассчитывается неверно. \n\nТут рисуются ТОЛЬКО используемые в данный момент (НЕ local storage) диски.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, controller) (\n  max by (namespace, controller, persistentvolumeclaim)\n  (\n    sum by (namespace, persistentvolumeclaim) (\n        max_over_time(kubelet_volume_stats_used_bytes{namespace=\"$namespace\"}[$__interval])\n    ) \n\n    * max by (namespace, persistentvolumeclaim) (\n        max_over_time(kube_persistentvolumeclaim_info{namespace=\"$namespace\", storageclass!~\"local.+\"}[$__interval])\n    )\n\n        * on (namespace, persistentvolumeclaim) group_left(pod) \n    max by (namespace, persistentvolumeclaim, pod) (\n         max_over_time(kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$namespace\"}[$__interval])\n    ) \n\n       * on (namespace, pod) group_left(controller)\n      kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} \n  )\n)\n/\nsum by (namespace, controller) (\n  max by (namespace, controller, persistentvolumeclaim)\n  (\n    sum by (namespace, persistentvolumeclaim) (\n        max_over_time(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"}[$__interval])\n    ) \n\n    * max by (namespace, persistentvolumeclaim) (\n        max_over_time(kube_persistentvolumeclaim_info{namespace=\"$namespace\", storageclass!~\"local.+\"}[$__interval])\n    )\n\n        * on (namespace, persistentvolumeclaim) group_left(pod) \n    max by (namespace, persistentvolumeclaim, pod) (\n         max_over_time(kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$namespace\"}[$__interval])\n    ) \n\n       * on (namespace, pod) group_left(controller)\n      kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} \n  )\n)",
     "legendFormat": "Usage {{ controller }}"
    }
   ]
  },
  {
   "title": "PVC Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overview",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
     "targets": [
      {
       "expr": "max by (persistentvolumeclaim, storageclass) (\n  max_over_time(kube_persistentvolumeclaim_info{namespace=\"$namespace\"}[$__range])\n)",
       "legendFormat": "Name, StorageClass"
      },
      {
       "expr": "sum by (persistentvolumeclaim) (\n  kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=\"$namespace\"}\n)",
       "legendFormat": "Requested (pvc)"
      },
      {
       "expr": "max by (persistentvolumeclaim) (\n  max by (persistentvolume) (max_over_time(kube_persistentvolume_capacity_bytes[$__range])) \n  * on (persistentvolume) group_right() \n  max by (persistentvolume, persistentvolumeclaim) (\n    label_replace(\n      max_over_time(kube_persistentvolumeclaim_info{namespace=\"$namespace\"}[$__range]),\n      \"persistentvolume\", \"$1\", \"volumename\", \"(.*)\")\n  )\n)",
       "legendFormat": "Provisioned (pv)"
      },
      {
       "expr": "max by (persistentvolumeclaim) (\n  max_over_time(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"}[$__range])\n)",
       "legendFormat": "Capacity (real)"
      },
      {
       "expr": "max by (persistentvolumeclaim) (\n  max_over_time(kubelet_volume_stats_used_bytes{namespace=\"$namespace\"}[$__range])\n)",
       "legendFormat": "used bytes"
      },
      {
       "expr": "max by (persistentvolumeclaim) (\n  max_over_time(kubelet_volume_stats_inodes_used{namespace=\"$namespace\"}[$__range])\n)",
       "legendFormat": "used inodes"
      },
      {
       "expr": "max by (persistentvolumeclaim) (\n  max_over_time(kubelet_volume_stats_used_bytes{namespace=\"$namespace\"}[$__range]) \n  / \n  max_over_time(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"}[$__range])\n)",
       "legendFormat": "used byetes %"
      },
      {
       "expr": "max by (persistentvolumeclaim) (\n  max_over_time(kubelet_volume_stats_inodes_used{namespace=\"$namespace\"}[$__range]) \n  / \n  max_over_time(kubelet_volume_stats_inodes{namespace=\"$namespace\"}[$__range])\n)",
       "legendFormat": "used inodes %"
      },
      {
       "expr": "sum by (persistentvolumeclaim, controller) (\n  max by (namespace, persistentvolumeclaim, pod) (\n    max_over_time(kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$namespace\"}[$__interval])\n  ) \n  * on (namespace, pod) group_left(controller)\n  kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\"} \n)",
       "legendFormat": "used by controller"
      }
     ]
    },
    {
     "title": "$persistentvolumeclaim",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 103 },
     "repeat": "persistentvolumeclaim",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max by (persistentvolumeclaim) (\n  max_over_time(kube_persistentvolume_capacity_bytes[$__interval]) \n  * on (persistentvolume) group_right() \n  (\n    label_replace(\n      max_over_time(kube_persistentvolumeclaim_info{namespace=\"$namespace\", persistentvolumeclaim=~\"$persistentvolumeclaim\"}[$__interval]),\n      \"persistentvolume\", \"$1\", \"volumename\", \"(.*)\")\n  )\n)",
       "legendFormat": "Provisioned"
      },
      {
       "expr": "max by (persistentvolumeclaim) (\n  max_over_time(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=\"$persistentvolumeclaim\"}[$__interval])\n)",
       "legendFormat": "Capacity"
      },
      {
       "expr": "max by (persistentvolumeclaim) (\n  max_over_time(kubelet_volume_stats_used_bytes{namespace=\"$namespace\", persistentvolumeclaim=\"$persistentvolumeclaim\"}[$__interval])\n)",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  }
 ]
}