{
 "title": "Overview All Namespaces",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Restarts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "restart per minute" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts{pod!=\"\"}[$__interval_rv])) by (namespace) > 0",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Not Ready Pods",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((sum(kube_pod_status_ready{condition=\"false\"}) by (namespace) - sum(kube_pod_status_phase{phase=\"Succeeded\"}) by (namespace)) or sum(kube_pod_status_ready{condition=\"false\"}) by (namespace)) > 0",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Old Deployment Pods",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas - kube_deployment_status_replicas_updated) by (namespace) > 0",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "namespace:container_cpu_usage:sum{namespace!=\"\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Network Receive",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod!=\"\",namespace!~\"kube-.*|monitoring\"}[$__interval_rv])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(namespace:container_memory_usage_bytes:sum)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Network Transmit",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod!=\"\",namespace!~\"kube-.*|monitoring\"}[$__interval_rv])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory RSS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(cluster_namespace_controller_pod_container:memory_rss:bytes) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "FS Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{pod!=\"\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Requested",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Requested",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}