{
 "title": "Namespace / Controller / Pod",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(min_over_time(kube_pod_container_status_ready{namespace=\"$namespace\", pod=\"$pod\"}[$__interval_rv]) == 1) * 0",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "(min_over_time(kube_pod_container_status_running{namespace=\"$namespace\", pod=\"$pod\"}[$__interval_rv]) == 1) * 1",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "(min_over_time(kube_pod_container_status_terminated{namespace=\"$namespace\", pod=\"$pod\"}[$__interval_rv]) == 1) * 2",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "(min_over_time(kube_pod_container_status_waiting{namespace=\"$namespace\", pod=\"$pod\"}[$__interval_rv]) == 1) * 3",
     "legendFormat": "{{ container }}"
    },
    {}
   ]
  },
  {
   "title": "Pods reason down",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Terminated reason",
     "type": "flant-statusmap-panel",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "(max_over_time(kube_pod_container_status_terminated_reason{namespace=\"$namespace\", pod=\"$pod\", reason=\"Error\"}[$__interval_rv]) == 1) * 0",
       "legendFormat": "{{ container }}"
      },
      {
       "expr": "(max_over_time(kube_pod_container_status_terminated_reason{namespace=\"$namespace\", pod=\"$pod\", reason=\"Completed\"}[$__interval_rv]) == 1) * 1",
       "legendFormat": "{{ container }}"
      },
      {
       "expr": "(max_over_time(kube_pod_container_status_terminated_reason{namespace=\"$namespace\", pod=\"$pod\", reason=\"ContainerCannotRun\"}[$__interval_rv]) == 1) * 2",
       "legendFormat": "{{ container }}"
      },
      {
       "expr": "(max_over_time(kube_pod_container_status_terminated_reason{namespace=\"$namespace\", pod=\"$pod\", reason=\"OOMKilled\"}[$__interval_rv]) == 1) * 3",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "Waiting reason",
     "type": "flant-statusmap-panel",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "(max_over_time(kube_pod_container_status_waiting_reason{namespace=\"$namespace\", pod=\"$pod\", reason=\"ContainerCreating\"}[$__interval_rv]) == 1) * 0",
       "legendFormat": "{{ container }}"
      },
      {
       "expr": "(max_over_time(kube_pod_container_status_waiting_reason{namespace=\"$namespace\", pod=\"$pod\", reason=\"CrashLoopBackOff\"}[$__interval_rv]) == 1) * 1",
       "legendFormat": "{{ container }}"
      },
      {
       "expr": "(max_over_time(kube_pod_container_status_waiting_reason{namespace=\"$namespace\", pod=\"$pod\", reason=\"CreateContainerConfigError\"}[$__interval_rv]) == 1) * 2",
       "legendFormat": "{{ container }}"
      },
      {
       "expr": "(max_over_time(kube_pod_container_status_waiting_reason{namespace=\"$namespace\", pod=\"$pod\", reason=\"ErrImagePull\"}[$__interval_rv]) == 1) * 3",
       "legendFormat": "{{ container }}"
      },
      {
       "expr": "(max_over_time(kube_pod_container_status_waiting_reason{namespace=\"$namespace\", pod=\"$pod\", reason=\"ImagePullBackOff\"}[$__interval_rv]) == 1) * 4",
       "legendFormat": "{{ container }}"
      }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Usage by container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by(container) (rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=\"$pod\", namespace=\"$namespace\"}[$__interval_rv]))",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=\"$pod\", namespace=\"$namespace\"}[$__interval_rv]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Usage by state",
   "type": "graph",
   "description": "Total может быть не равен system + user из-за особенностей учета cgroup в ядре. Более детально можно почитать тут: https://www.kernel.org/doc/Documentation/cgroup-v1/cpuacct.txt",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_system_seconds_total{container!=\"POD\", pod=\"$pod\", namespace=\"$namespace\"}[$__interval_rv]))",
     "legendFormat": "System"
    },
    {
     "expr": "sum by(pod) (rate(container_cpu_user_seconds_total{container!=\"POD\", pod=\"$pod\", namespace=\"$namespace\"}[$__interval_rv]))",
     "legendFormat": "User"
    },
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=\"$pod\", namespace=\"$namespace\"}[$__interval_rv]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Throttling",
   "type": "graph",
   "description": "Если на графике нет данных, значит не заданы ресурсы для контейнеров",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "(sum by (pod, container) (rate(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", container=~\"$container\", pod=\"$pod\"}[$__interval_rv])) / sum by (container, pod) (rate(container_cpu_cfs_periods_total{namespace=\"$namespace\", container=~\"$container\", pod=\"$pod\"}[$__interval_rv]))) * sum by (pod, container) (kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\"})",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "sum by (pod) ((sum by (pod, container) (rate(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", container=~\"$container\", pod=\"$pod\"}[$__interval_rv])) / sum by (container, pod) (rate(container_cpu_cfs_periods_total{namespace=\"$namespace\", container=~\"$container\", pod=\"$pod\"}[$__interval_rv]))) * sum by (pod, container) (kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\"}))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Containers CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "$container",
     "type": "graph",
     "description": "Total может быть не равен system + user из-за особенностей учета cgroup в ядре. Более детально можно почитать тут: https://www.kernel.org/doc/Documentation/cgroup-v1/cpuacct.txt",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
     "repeat": "container",
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by(container) (rate(container_cpu_system_seconds_total{container!=\"POD\", pod=\"$pod\", namespace=\"$namespace\", container=\"$container\"}[$__interval_rv]))",
       "legendFormat": "System"
      },
      {
       "expr": "sum by(container) (rate(container_cpu_user_seconds_total{container!=\"POD\", pod=\"$pod\", namespace=\"$namespace\", container=\"$container\"}[$__interval_rv]))",
       "legendFormat": "User"
      },
      {
       "expr": "sum by(container) (rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=\"$pod\", namespace=\"$namespace\", container=\"$container\"}[$__interval_rv]))",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Usage by container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container) (container_memory_working_set_bytes{container!=\"POD\", pod=\"$pod\", namespace=\"$namespace\"})",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Usage by state",
   "type": "graph",
   "description": "Метрика Working set bytes - реально используемая память контейнером, так как включает active file memory. И пр достижении данного значения к лимиту, может прийти OOMKiller. Данное значение может быть выше RSS + Cache. Так как не вся active file memory является Cache.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_rss{container!=\"POD\", pod=\"$pod\", namespace=\"$namespace\"})",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum by(pod) (container_memory_cache{container!=\"POD\", pod=\"$pod\", namespace=\"$namespace\"})",
     "legendFormat": "Cache"
    },
    {
     "expr": "sum by(pod) (container_memory_swap{container!=\"POD\", pod=\"$pod\", namespace=\"$namespace\"})",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{container!=\"POD\", pod=\"$pod\", namespace=\"$namespace\"})",
     "legendFormat": "Working set bytes"
    }
   ]
  },
  { "title": "Containers Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "$container",
   "type": "graph",
   "description": "Метрика Working set bytes - реально используемая память контейнером, так как включает active file memory. И пр достижении данного значения к лимиту, может прийти OOMKiller. Данное значение может быть выше RSS + Cache. Так как не вся active file memory является Cache.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "repeat": "container",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container) (container_memory_rss{container!=\"POD\", pod=\"$pod\", namespace=\"$namespace\", container=\"$container\"})",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum by(container) (container_memory_cache{container!=\"POD\", pod=\"$pod\", namespace=\"$namespace\", container=\"$container\"})",
     "legendFormat": "Cache"
    },
    {
     "expr": "sum by(container) (container_memory_swap{container!=\"POD\", pod=\"$pod\", namespace=\"$namespace\", container=\"$container\"})",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum by(container) (container_memory_working_set_bytes{container!=\"POD\", pod=\"$pod\", namespace=\"$namespace\", container=\"$container\"})",
     "legendFormat": "Working set bytes"
    },
    {
     "expr": "sum by(container) (kube_pod_container_resource_limits_memory_bytes{pod=\"$pod\", container=\"$container\", namespace=\"$namespace\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum by(container) (kube_pod_container_resource_requests_memory_bytes{pod=\"$pod\", container=\"$container\", namespace=\"$namespace\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Recieve",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_network_receive_bytes_total{pod=\"$pod\", namespace=\"$namespace\"}[$__interval_rv]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Transmit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_network_transmit_bytes_total{pod=\"$pod\", namespace=\"$namespace\"}[$__interval_rv]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "IOPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by(container) (rate(container_fs_reads_total{container!=\"POD\", pod=\"$pod\", namespace=\"$namespace\"}[$__interval_rv]))",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "sum (rate(container_fs_reads_total{container!=\"POD\", pod=\"$pod\", namespace=\"$namespace\"}[$__interval_rv]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by(container) (rate(container_fs_writes_total{container!=\"POD\", pod=\"$pod\", namespace=\"$namespace\"}[$__interval_rv]))",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "sum (rate(container_fs_writes_total{container!=\"POD\", pod=\"$pod\", namespace=\"$namespace\"}[$__interval_rv]))",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}