{
 "title": "Summary",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "controller_kind",
    "label": "Controller Kind",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_name!=\"<none>\", created_by_kind!=\"<none>\"}, created_by_kind)"
   },
   {
    "name": "controller_name",
    "label": "Controller Name",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_name!=\"<none>\", created_by_kind!=\"<none>\", created_by_kind=~\"$controller_kind\"}, created_by_name)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_kind=~\"$controller_kind\", created_by_name=~\"$controller_name\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"$pod\", namespace=~\"$namespace\", container_name=~\"$container\"}[5m] ))",
     "legendFormat": "Current"
    },
    {
     "expr": "sum (kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\", namespace=~\"$namespace\", container=~\"$container\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\", namespace=~\"$namespace\", container=~\"$container\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_cfs_throttled_periods_total{namespace=~\"$namespace\", container_name=~\"$container\", pod_name=~\"$pod\"}[5m])) / sum(irate(container_cpu_cfs_periods_total{namespace=~\"$namespace\", container_name=~\"$container\", pod_name=~\"$pod\"}[5m]))",
     "legendFormat": "Throttled periods"
    }
   ]
  },
  {
   "title": "Detailed CPU usage (stacked)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum\n                                              (irate(container_cpu_user_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"$pod\", namespace=~\"$namespace\", container_name=~\"$container\"}[5m]))",
     "legendFormat": "User"
    },
    {
     "expr": "sum\n                                              (irate(container_cpu_system_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"$pod\", namespace=~\"$namespace\", container_name=~\"$container\"}[5m]))",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Reports incorrect result when multiple containers are selected.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum  (container_memory_usage_bytes{pod_name=~\"$pod\", container_name!=\"POD\", pod_name=~\"$pod\", namespace=~\"$namespace\", container_name=~\"$container\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "sum  (kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\", container=~\"$container\", namespace=~\"$namespace\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum  (kube_pod_container_resource_requests_memory_bytes{pod=~\"$pod\", container=~\"$container\", namespace=~\"$namespace\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum (irate(container_network_receive_bytes_total{pod_name=~\"$pod\", pod_name=~\"$pod\", namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum (irate(container_network_transmit_bytes_total{pod_name=~\"$pod\", pod_name=~\"$pod\", namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum (irate(container_fs_reads_total{container_name=~\"$container\", container_name!=\"POD\", pod_name=~\"$pod\", pod_name=~\"$pod\", namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum (irate(container_fs_writes_total{container_name=~\"$container\", container_name!=\"POD\", pod_name=~\"$pod\", pod_name=~\"$pod\", namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{pod_name=~\"$pod\", container_name!=\"POD\", pod_name=~\"$pod\", namespace=~\"$namespace\", container_name=~\"$container\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(container_fs_limit_bytes{pod_name=~\"$pod\", container_name!=\"POD\", pod_name=~\"$pod\", namespace=~\"$namespace\", container_name=~\"$container\"})",
     "legendFormat": "Limit"
    }
   ]
  }
 ]
}