{{- $providerID := "gcp" }}
{{- define "registration_values" }}
{{- $context := index . 0 }}
# obligatory
type: {{ b64enc "gcp" | quote }}
region: {{ $context.Values.cloudProviderGcp.internal.providerClusterConfiguration.provider.region | b64enc | quote }}
zones: {{ $context.Values.cloudProviderGcp.internal.providerDiscoveryData.zones | toJson | b64enc | quote }}
instanceClassKind: {{ b64enc "GCPInstanceClass" | quote }}
machineClassKind: {{ b64enc "GCPMachineClass" | quote }}
# GCP
{{- $gcpValues := dict }}
{{- $_ := set $gcpValues "serviceAccountJSON" $context.Values.cloudProviderGcp.internal.providerClusterConfiguration.provider.serviceAccountJSON }}
{{- $_ := set $gcpValues "region" $context.Values.cloudProviderGcp.internal.providerClusterConfiguration.provider.region }}
{{- $_ := set $gcpValues "sshKey" $context.Values.cloudProviderGcp.internal.providerClusterConfiguration.sshKey }}

{{- $_ := set $gcpValues "networkName" $context.Values.cloudProviderGcp.internal.providerDiscoveryData.networkName }}
{{- $_ := set $gcpValues "subnetworkName" $context.Values.cloudProviderGcp.internal.providerDiscoveryData.subnetworkName }}
{{- $_ := set $gcpValues "disableExternalIP" $context.Values.cloudProviderGcp.internal.providerDiscoveryData.disableExternalIP }}

{{- $_ := set $gcpValues "image" $context.Values.cloudProviderGcp.internal.providerDiscoveryData.instances.image }}
{{- $_ := set $gcpValues "diskSizeGb" $context.Values.cloudProviderGcp.internal.providerDiscoveryData.instances.diskSizeGb }}
{{- $_ := set $gcpValues "diskType" $context.Values.cloudProviderGcp.internal.providerDiscoveryData.instances.diskType }}
{{- $_ := set $gcpValues "networkTags" $context.Values.cloudProviderGcp.internal.providerDiscoveryData.instances.networkTags }}
{{- $_ := set $gcpValues "labels" $context.Values.cloudProviderGcp.internal.providerDiscoveryData.instances.labels }}
gcp: {{ $gcpValues | toJson | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: d8-node-manager-cloud-provider
  namespace: kube-system
  {{- include "helm_lib_module_labels" (list . (dict
    "cloud-provider.deckhouse.io/registration" ""
    "cloud-provider.deckhouse.io/name" $providerID
    )) | nindent 2 }}
type: Opaque
data: {{- include "registration_values" (list . ) | nindent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "d8-node-manager-cloud-provider-%s" $providerID }}
  namespace: kube-system
  {{- include "helm_lib_module_labels" (list . (dict
    "cloud-provider.deckhouse.io/registration" ""
    "cloud-provider.deckhouse.io/name" $providerID
    )) | nindent 2 }}
type: Opaque
data: {{- include "registration_values" (list . ) | nindent 2 }}
