#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p onKubernetesEvent="$(jo -a "$(jo event="$(jo -a delete)" kind=configmap jqFilter=".metadata.labels" selector=$(jo matchLabels=$(jo hello=world)))")"
}

function __main__() {
    echo "KUBE EVENT delete-configmaps"
}

hook::run $@
