#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p onUpdate="$(jo -a "$(jo kind=configmap selector=$(jo matchLabels=$(jo hello=world)))")"
}

function __main__() {
    echo "KUBE EVENT update-configmaps"
}

hook::run $@
