{
 "title": "etcd",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(up{job=\"etcd\"}, namespace)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(up{job=\"etcd\",namespace=\"$namespace\"}, service)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(up{job=\"etcd\",namespace=\"$namespace\",service=~\"$service\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(etcd_server_has_leader{job=\"etcd\", namespace=\"$namespace\", service=~\"$service\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"etcd\", namespace=\"$namespace\", service=~\"$service\", instance=~\"$instance\", grpc_type=\"unary\"}[$__interval_rv]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"etcd\", namespace=\"$namespace\", service=~\"$service\", instance=~\"$instance\", grpc_type=\"unary\",grpc_code!=\"OK\"}[$__interval_rv]))",
     "legendFormat": "RPC Failed Rate"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{job=\"etcd\", namespace=\"$namespace\", service=~\"$service\", instance=~\"$instance\", grpc_service=\"etcdserverpb.Watch\", grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{job=\"etcd\", namespace=\"$namespace\", service=~\"$service\", instance=~\"$instance\", grpc_service=\"etcdserverpb.Watch\", grpc_type=\"bidi_stream\"})",
     "legendFormat": "Watch Streams"
    },
    {
     "expr": "sum(grpc_server_started_total{job=\"etcd\", namespace=\"$namespace\", service=~\"$service\", instance=~\"$instance\", grpc_service=\"etcdserverpb.Lease\", grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{job=\"etcd\", namespace=\"$namespace\", service=~\"$service\", instance=~\"$instance\", grpc_service=\"etcdserverpb.Lease\", grpc_type=\"bidi_stream\"})",
     "legendFormat": "Lease Streams"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_total_size_in_bytes{job=\"etcd\", namespace=\"$namespace\", service=~\"$service\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} DB Size"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=\"etcd\", namespace=\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__interval_rv])) by (instance, le))",
     "legendFormat": "{{instance}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{job=\"etcd\", namespace=\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__interval_rv])) by (instance, le))",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"etcd\", namespace=\"$namespace\", service=~\"$service\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Resident Memory"
    }
   ]
  },
  {
   "title": "Client Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{job=\"etcd\", namespace=\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__interval_rv])",
     "legendFormat": "{{instance}} Client Traffic In"
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{job=\"etcd\", namespace=\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__interval_rv])",
     "legendFormat": "{{instance}} Client Traffic Out"
    }
   ]
  },
  {
   "title": "Peer Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total{job=\"etcd\", namespace=\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__interval_rv])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic In"
    }
   ]
  },
  {
   "title": "Peer Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total{job=\"etcd\", namespace=\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__interval_rv])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic Out"
    }
   ]
  },
  {
   "title": "Raft Proposals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total{job=\"etcd\", namespace=\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__interval_rv]))",
     "legendFormat": "Proposal Failure Rate"
    },
    {
     "expr": "sum(etcd_server_proposals_pending{job=\"etcd\", namespace=\"$namespace\", service=~\"$service\", instance=~\"$instance\"})",
     "legendFormat": "Proposal Pending Total"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{job=\"etcd\", namespace=\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__interval_rv]))",
     "legendFormat": "Proposal Commit Rate"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{job=\"etcd\", namespace=\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__interval_rv]))",
     "legendFormat": "Proposal Apply Rate"
    }
   ]
  },
  {
   "title": "Total Leader Elections",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{job=\"etcd\", namespace=\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__range])",
     "legendFormat": "{{service}} / {{instance}}"
    }
   ]
  }
 ]
}