{
 "title": "JMX exporter",
 "description": "Complete dashboard using metrics from prometheus JMX exporter, with drill down per release > pod",
 "tags": [ "JVM" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(jvm_info,namespace)"
   },
   { "name": "service", "label": "Service", "query": "label_values(jvm_info,service)" },
   { "name": "pod", "label": "Pod", "query": "label_values(jvm_info,pod)" }
  ]
 },
 "panels": [
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(jvm_memory_bytes_used{area=\"heap\",namespace=~\"$namespace\",service=~\"$service\"})*100) / sum(jvm_memory_bytes_max{area=\"heap\",namespace=~\"$namespace\",service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(process_start_time_seconds)*1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds)"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jvm_info{}" }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Used {{pod}}"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Max {{pod}}"
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Used  {{pod}}"
    }
   ]
  },
  {
   "title": "PS Eden Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Eden Space\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"} or jvm_memory_pool_bytes_max{pool=\"Par Eden Space\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Max  {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Eden Space\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"} or jvm_memory_pool_bytes_used{pool=\"Par Eden Space\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Used  {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Eden Space\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"} or jvm_memory_pool_bytes_committed{pool=\"Par Eden Space\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Committed  {{pod}}"
    }
   ]
  },
  {
   "title": "Tenured Gen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Tenured Gen\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"} or jvm_memory_pool_bytes_max{pool=\"CMS Old Gen\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Max  {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Tenured Gen\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"} or jvm_memory_pool_bytes_used{pool=\"CMS Old Gen\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Used  {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Tenured Gen\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"} or jvm_memory_pool_bytes_committed{pool=\"CMS Old Gen\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Committed  {{pod}}"
    }
   ]
  },
  {
   "title": "PS Survivor Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Survivor Space\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"} or jvm_memory_pool_bytes_max{pool=\"Par Survivor Space\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Max  {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Survivor Space\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"} or jvm_memory_pool_bytes_used{pool=\"Par Survivor Space\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Used  {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Survivor Space\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"} or jvm_memory_pool_bytes_committed{pool=\"Par Survivor Space\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Committed  {{pod}}"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Metaspace\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Max {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Metaspace\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Used {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Metaspace\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Committed {{pod}}"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Compressed Class Space\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Max {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Compressed Class Space\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Used {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Compressed Class Space\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Committed {{pod}}"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Code Cache\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Max {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Code Cache\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Used {{pod}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Code Cache\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Committed {{pod}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{pod=~\"$pod\",namespace=~\"$namespace\",service=~\"$service\",}",
     "legendFormat": "JVM current threads  {{pod}}"
    },
    {
     "expr": "jvm_threads_daemon{pod=~\"$pod\",namespace=~\"$namespace\",service=~\"$service\",}",
     "legendFormat": "JVM daemon threads {{pod}}"
    },
    {
     "expr": "jvm_threads_deadlocked{pod=~\"$pod\",namespace=~\"$namespace\",service=~\"$service\",}",
     "legendFormat": "JVM deadlocked threads  {{pod}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{pod=~\"$pod\",namespace=~\"$namespace\",service=~\"$service\"}",
     "legendFormat": "{{gc}}  {{pod}}"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{gc}} {{pod}}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "loaded  {{pod}}"
    }
   ]
  }
 ]
}