{
 "title": "Memcached",
 "description": "Monitors Kubernetes Memcached Pods. Shows memory usage, hit rate, evicts and reclaims rate, items in cache, network stats, commands rate. Requires Memcached Exporter for Prometheus.",
 "tags": [
  "prometheus",
  "memcached"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(memcached_up{job=\"memcached\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(memcached_up{job=\"memcached\",namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(memcached_current_bytes{job=\"memcached\",pod=\"$pod\",namespace=\"$namespace\"}) / sum(memcached_limit_bytes{job=\"memcached\",pod=\"$pod\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Hit rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (rate (memcached_commands_total{job=\"memcached\",status=\"hit\",command=\"get\",pod=\"$pod\",namespace=\"$namespace\"}[$__interval_rv])) / sum (rate (memcached_commands_total{job=\"memcached\", command=\"get\",pod=\"$pod\",namespace=\"$namespace\"}[$__interval_rv]\n))",
     "legendFormat": "Hit"
    }
   ]
  },
  {
   "title": "Evicts & Reclaims rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (memcached_items_evicted_total{job=\"memcached\",pod=\"$pod\",namespace=\"$namespace\"}[$__interval_rv]))",
     "legendFormat": "evicts"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (memcached_current_bytes{job=\"memcached\",pod=\"$pod\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (memcached_limit_bytes{job=\"memcached\",pod=\"$pod\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Hit & Miss ratio",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_commands_total{job=\"memcached\",status=\"hit\",command=\"get\",pod=\"$pod\",namespace=\"$namespace\"}) / sum (memcached_commands_total{job=\"memcached\",command=\"get\",pod=\"$pod\",namespace=\"$namespace\"})",
     "legendFormat": "hit"
    },
    {
     "expr": "sum (memcached_commands_total{job=\"memcached\",status=\"miss\",command=\"get\",pod=\"$pod\",namespace=\"$namespace\"}) / sum (memcached_commands_total{job=\"memcached\",command=\"get\",pod=\"$pod\",namespace=\"$namespace\"})",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Evicts (total)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (memcached_items_evicted_total{job=\"memcached\",pod=\"$pod\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Reclaims (total)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (memcached_items_reclaimed_total{job=\"memcached\",pod=\"$pod\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Items in cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_current_items{job=\"memcached\",pod=\"$pod\",namespace=\"$namespace\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (rate (memcached_read_bytes_total{job=\"memcached\",pod=\"$pod\",namespace=\"$namespace\"}[$__interval_rv]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum (rate (memcached_written_bytes_total{job=\"memcached\",pod=\"$pod\",namespace=\"$namespace\"}[$__interval_rv]))",
     "legendFormat": "written"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_current_connections{job=\"memcached\",pod=\"$pod\",namespace=\"$namespace\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Get & Set ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_commands_total{job=\"memcached\",command=\"get\",pod=\"$pod\",namespace=\"$namespace\"}) / (sum (memcached_commands_total{job=\"memcached\",command=\"get\",pod=\"$pod\",namespace=\"$namespace\"}) + sum (memcached_commands_total{job=\"memcached\",command=\"set\",pod=\"$pod\",namespace=\"$namespace\"}))",
     "legendFormat": "Get"
    },
    {
     "expr": "sum (memcached_commands_total{job=\"memcached\",command=\"set\",pod=\"$pod\",namespace=\"$namespace\"})  / (sum (memcached_commands_total{job=\"memcached\",command=\"get\",pod=\"$pod\",namespace=\"$namespace\"}) + sum (memcached_commands_total{job=\"memcached\",command=\"set\",pod=\"$pod\",namespace=\"$namespace\"}))",
     "legendFormat": "Set"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (memcached_commands_total{job=\"memcached\",pod=\"$pod\",namespace=\"$namespace\"}[$__interval_rv])) by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  }
 ]
}