{
 "title": "PHP-FPM",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(phpfpm_up, namespace)"
   },
   {
    "name": "controller_kind",
    "label": "Controller Kind",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_name!=\"<none>\", created_by_kind!=\"<none>\"}, created_by_kind)"
   },
   {
    "name": "controller_name",
    "label": "Controller Name",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_name!=\"<none>\", created_by_kind!=\"<none>\", created_by_kind=~\"$controller_kind\"}, created_by_name)"
   },
   {
    "name": "pod_name",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_kind=~\"$controller_kind\", created_by_name=~\"$controller_name\"}, pod)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(phpfpm_up{namespace=~\"$namespace\",  pod=~\"$pod_name\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Accepted connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, namespace) (irate(phpfpm_accepted_connections_total{namespace=~\"$namespace\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "{{ namespace }} / {{ pod }}"
    }
   ]
  },
  {
   "title": "Connection backlog",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, pod) (phpfpm_listen_queue_length_connections{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Size {{namespace}} / {{pod}}"
    },
    {
     "expr": "sum by (namespace, pod) ((phpfpm_listen_queue_connections{namespace=~\"$namespace\", pod=~\"$pod\"} > 0) + phpfpm_listen_queue_length_connections{namespace=~\"$namespace\", pod=~\"$pod\"} )",
     "legendFormat": "Current {{namespace}} / {{pod}}"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, pod) (phpfpm_processes_total{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Total {{namespace}} / {{pod}}"
    },
    {
     "expr": "sum by (namespace, pod) (phpfpm_processes_total{namespace=~\"$namespace\", pod=~\"$pod\", state=\"active\"})",
     "legendFormat": "Active {{namespace}} / {{pod}}"
    },
    {
     "expr": "sum by (namespace, pod) (phpfpm_processes_total{namespace=~\"$namespace\", pod=~\"$pod\", state=\"idle\"})",
     "legendFormat": "Idle {{namespace}} / {{pod}}"
    }
   ]
  },
  {
   "title": "Slow requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, pod) (irate(phpfpm_slow_requests_total{pod=~\"$pod\", namespace=~\"namespace\"}[5m]))"
    }
   ]
  }
 ]
}