{
 "title": "RabbitMQ",
 "description": "Basic rabbitmq host stats: Node Stats, Exchanges, Channels, Consumers,  Connections, Queues, Messages, Messages per Queue, Memory, File Descriptors, Sockets.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(rabbitmq_running, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(rabbitmq_running{namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(rabbitmq_running{namespace=~\"$namespace\", pod=~\"$pod\"}, node)"
   },
   {
    "name": "vhost",
    "label": "vhost",
    "query": "label_values(rabbitmq_queue_messages_published_total{namespace=~\"$namespace\", pod=~\"$pod\"}, vhost)"
   },
   {
    "name": "queue",
    "label": "Queue",
    "query": "label_values(rabbitmq_queue_messages_published_total{namespace=~\"$namespace\", pod=~\"$pod\"}, queue)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster status",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(rabbitmq_up) >= sum (rabbitmq_up)"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rabbitmq_connectionsTotal{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}} connections"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rabbitmq_consumersTotal{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}} consumers"
    }
   ]
  },
  {
   "title": "Node up Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_running{namespace=~\"$namespace\", pod=~\"$pod\", node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Network partitions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rabbitmq_partitions{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Exchanges",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rabbitmq_exchangesTotal{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}} exchanges"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rabbitmq_channelsTotal{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}} channels"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rabbitmq_queuesTotal{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}} queues"
    }
   ]
  },
  {
   "title": "Messages published",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(rabbitmq_exchange_messages_published_in_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__interval_rv]))",
     "legendFormat": "{{ pod }} in"
    },
    {
     "expr": "sum by (pod) (rate(rabbitmq_exchange_messages_published_out_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__interval_rv]))",
     "legendFormat": "{{ pod }} out"
    }
   ]
  },
  {
   "title": "Queues for \"$vhost\" vhost",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "vhost",
   "collapsed": true,
   "panels": [
    {
     "title": "Queue depth (ready + unACKed)",
     "type": "graph",
     "description": "Sum of ready and unacknowledged messages (queue depth)",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (rabbitmq_queue_messages{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"})",
       "legendFormat": "{{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      },
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (rabbitmq_queue_messages_ram{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"})",
       "legendFormat": "RAM {{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      }
     ]
    },
    {
     "title": "Ready messages",
     "type": "graph",
     "description": "Number of messages ready to be delivered to clients",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (rabbitmq_queue_messages_ready{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"})",
       "legendFormat": "{{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      },
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (rabbitmq_queue_messages_ready_ram{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"})",
       "legendFormat": "RAM {{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      }
     ]
    },
    {
     "title": "UnACKed messages",
     "type": "graph",
     "description": "Number of messages delivered to clients but not yet acknowledged",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (rabbitmq_queue_messages_unacknowledged\t{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"})",
       "legendFormat": "{{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      },
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (rabbitmq_queue_messages_unacknowledged_ram\t{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"})",
       "legendFormat": "RAM {{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      }
     ]
    },
    {
     "title": "Queue depth (ready + unACKed) bytes",
     "type": "graph",
     "description": "Sum of the size of all message bodies in the queue. This does not include the message properties (including headers) or any overhead",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (rabbitmq_queue_message_bytes{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"})",
       "legendFormat": "{{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      },
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (rabbitmq_queue_message_bytes_ram{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"})",
       "legendFormat": "RAM {{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      }
     ]
    },
    {
     "title": "Ready messages bytes",
     "type": "graph",
     "description": "Like message_bytes but counting only those messages ready to be delivered to clients",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (rabbitmq_queue_message_bytes_ready{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"})",
       "legendFormat": "{{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      }
     ]
    },
    {
     "title": "UnACKed messages bytes",
     "type": "graph",
     "description": "Like message_bytes but counting only those messages delivered to clients but not yet acknowledged",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (rabbitmq_queue_message_bytes_unacknowledged{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"})",
       "legendFormat": "{{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      }
     ]
    },
    {
     "title": "Disk reads/writes",
     "type": "graph",
     "description": "Total number of times messages have been read/written from/to the disk by this queue since it started",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (rate(rabbitmq_queue_disk_reads\t{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"}[$__interval_rv]))",
       "legendFormat": "Reads {{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      },
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (rate(rabbitmq_queue_disk_writes\t{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"}[$__interval_rv]))",
       "legendFormat": "Writes {{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      }
     ]
    },
    {
     "title": "Messages persistent",
     "type": "graph",
     "description": "Total number of persistent messages in the queue (will always be 0 for transient queues)",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (queue_messages_persistent\t{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"})",
       "legendFormat": "{{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      }
     ]
    },
    {
     "title": "Messages persistent bytes",
     "type": "graph",
     "description": "Like message_bytes but counting only those messages which are persistent",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (queue_messages_persistent_bytes\t{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"})",
       "legendFormat": "{{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      }
     ]
    },
    {
     "title": "Queue memory",
     "type": "graph",
     "description": "Bytes of memory consumed by the Erlang process associated with the queue, including stack, heap and internal structures",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (rabbitmq_queue_memory{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"})",
       "legendFormat": "Reads {{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      }
     ]
    },
    {
     "title": "Queue consumers",
     "type": "graph",
     "description": "Number of consumers",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (rabbitmq_queue_consumers\t{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"})",
       "legendFormat": "{{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      }
     ]
    },
    {
     "title": "Queue consumer utilization",
     "type": "graph",
     "description": "Fraction of the time that the queue is able to immediately deliver messages to consumers. This can be less than 1.0 if consumers are limited by network congestion or prefetch count",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (rabbitmq_queue_consumer_utilisation\t{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"}) * 100",
       "legendFormat": "{{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      }
     ]
    },
    {
     "title": "Messages published / confirmed",
     "type": "graph",
     "description": "Count of messages published and confirmed",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (rate(rabbitmq_queue_messages_published_total\t{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"}[$__interval_rv]))",
       "legendFormat": "Published {{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      },
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (rate(rabbitmq_queue_messages_confirmed_total\t{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"}[$__interval_rv]))",
       "legendFormat": "Confirmed {{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      }
     ]
    },
    {
     "title": "Messages delivered ACK / noACK modes",
     "type": "graph",
     "description": "Count of messages delivered in acknowledgement or no-acknowledgement mode to consumers",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (rate(rabbitmq_queue_messages_delivered_total\t{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"}[$__interval_rv]))",
       "legendFormat": "ACK {{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      },
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (rate(rabbitmq_queue_messages_delivered_noack_total\t{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"}[$__interval_rv]))",
       "legendFormat": "noACK {{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      }
     ]
    },
    {
     "title": "Get messages delivered ACK / noACK modes",
     "type": "graph",
     "description": "Count of messages delivered in acknowledgement or no-acknowledgement mode in response to basic.get",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (rate(rabbitmq_queue_messages_get_total\t{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"}[$__interval_rv]))",
       "legendFormat": "ACK {{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      },
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (rate(rabbitmq_queue_messages_get_noack_total\t{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"}[$__interval_rv]))",
       "legendFormat": "noACK {{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      }
     ]
    },
    {
     "title": "Messages returned",
     "type": "graph",
     "description": "Count of messages returned to publisher as unroutable",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (rate(rabbitmq_queue_messages_returned_total\t{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"}[$__interval_rv]))",
       "legendFormat": "{{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      }
     ]
    },
    {
     "title": "Messages redelivered",
     "type": "graph",
     "description": "Count of subset of messages in deliver_get which had the redelivered flag set",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(pod, durable, queue, vhost, policy) (rate(rabbitmq_queue_messages_redelivered_total\t{namespace=~\"$namespace\", pod=~\"$pod\", vhost=~\"$vhost\", queue=~\"$queue\"}[$__interval_rv]))",
       "legendFormat": "{{queue}} / Policy: {{policy}} / Durable:  {{durable}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Host resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sockets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod, node) (rabbitmq_sockets_used{namespace=~\"$namespace\", pod=~\"$pod\", node=~\"$node\"})",
       "legendFormat": "{{node}} used"
      },
      {
       "expr": "sum by (pod, node) (rabbitmq_sockets_total{namespace=~\"$namespace\", pod=~\"$pod\", node=~\"$node\"})",
       "legendFormat": "{{node}} total"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (pod, node) (rabbitmq_node_mem_used{namespace=~\"$namespace\", pod=~\"$pod\", node=~\"$node\"})",
       "legendFormat": "{{node}} used"
      },
      {
       "expr": "sum by (pod, node) (rabbitmq_node_mem_limit{namespace=~\"$namespace\", pod=~\"$pod\", node=~\"$node\"})",
       "legendFormat": "{{node}} minimum"
      }
     ]
    },
    {
     "title": "FIle descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod, node) (rabbitmq_fd_used{namespace=~\"$namespace\", pod=~\"$pod\", node=~\"$node\"})",
       "legendFormat": "{{node}} used"
      },
      {
       "expr": "sum by (pod, node) (rabbitmq_fd_total{namespace=~\"$namespace\", pod=~\"$pod\", node=~\"$node\"})",
       "legendFormat": "{{node}} total"
      }
     ]
    },
    {
     "title": "Disk",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (pod, node) (rabbitmq_node_disk_free{namespace=~\"$namespace\", pod=~\"$pod\", node=~\"$node\"})",
       "legendFormat": "{{node}} free"
      },
      {
       "expr": "sum by (pod, node) (rabbitmq_node_disk_free_limit{namespace=~\"$namespace\", pod=~\"$pod\", node=~\"$node\"})",
       "legendFormat": "{{node}} minimum"
      }
     ]
    }
   ]
  }
 ]
}