{
 "title": "Node controller",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Short stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reconcile Error Rate",
   "type": "stat",
   "description": "Number of reconcile errors",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  rate(controller_runtime_reconcile_errors_total{d8_source=\"dkp\", \n    namespace=\"d8-cloud-instance-manager\",\n    job=\"node-controller\"\n  }[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workqueue Depth",
   "type": "stat",
   "description": "Number of objects waiting in the workqueue",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  workqueue_depth{d8_source=\"dkp\", \n    namespace=\"d8-cloud-instance-manager\",\n    job=\"node-controller\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconcile Duration p99",
   "type": "stat",
   "description": "Duration of the slowest reconcile loops",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (\n    rate(controller_runtime_reconcile_time_seconds_bucket{d8_source=\"dkp\", \n      namespace=\"d8-cloud-instance-manager\",\n      job=\"node-controller\"\n    }[1m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Informer Cache Objects",
   "type": "stat",
   "description": "Total number of objects in the informer cache",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "objects" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\nnode_controller_cache_objects{d8_source=\"dkp\", \nnamespace=\"d8-cloud-instance-manager\",\njob=\"node-controller\"\n}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "stat",
   "description": "Number of goroutines",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_goroutines{d8_source=\"dkp\", namespace=\"d8-cloud-instance-manager\", pod=~\"node-controller.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go Heap Allocated Memory",
   "type": "stat",
   "description": "Current Go heap memory usage",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\ngo_memstats_heap_alloc_bytes{d8_source=\"dkp\", \nnamespace=\"d8-cloud-instance-manager\",\npod=~\"node-controller.*\"\n}\n)/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go Heap Objects",
   "type": "stat",
   "description": "Number of objects in Go heap",
   "gridPos": { "h": 6, "w": 3, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_objects{d8_source=\"dkp\", namespace=\"d8-cloud-instance-manager\", pod=~\"node-controller.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (\n  max(kube_controller_pod{d8_source=\"dkp\", node=~\".*\", namespace=\"d8-cloud-instance-manager\", controller=\"deploy/node-controller\", pod=~\".*\"}) by(pod)\n  * on (pod)\n  sum by (pod) (rate(container_cpu_usage_seconds_total{d8_source=\"dkp\", node=~\".*\", container!=\"POD\", pod=~\".*\", namespace=\"d8-cloud-instance-manager\"}[$__rate_interval]))\n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Usage by state",
   "type": "timeseries",
   "description": "The Working set bytes metric is the actual memory used by the container, as it includes active file memory. When its value approaches the limit, the container can be killed by the OOMKiller. This value can be higher than the sum RSS and Cache since not all active file memory is Cache.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (\n  max(kube_controller_pod{d8_source=\"dkp\", node=~\".*\", namespace=\"d8-cloud-instance-manager\", controller=\"deploy/node-controller\", pod=~\".*\"}) by(pod)\n  * on (pod)\n  sum by (pod) (avg_over_time(container_memory_rss{d8_source=\"dkp\", node=~\".*\", namespace=\"d8-cloud-instance-manager\", pod=~\".*\", container!=\"POD\"}[$__rate_interval]))\n)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum (\n  max(kube_controller_pod{d8_source=\"dkp\", node=~\".*\", namespace=\"d8-cloud-instance-manager\", controller=\"deploy/node-controller\", pod=~\".*\"}) by(pod)\n  * on (pod)\n  sum by (pod) (avg_over_time(container_memory_cache{d8_source=\"dkp\", node=~\".*\", namespace=\"d8-cloud-instance-manager\", pod=~\".*\", container!=\"POD\"}[$__rate_interval]))\n)",
     "legendFormat": "Cache"
    },
    {
     "expr": "sum (\n  max(kube_controller_pod{d8_source=\"dkp\", node=~\".*\", namespace=\"d8-cloud-instance-manager\", controller=\"deploy/node-controller\", pod=~\".*\"}) by(pod)\n  * on (pod)\n  sum by (pod) (avg_over_time(container_memory_swap{d8_source=\"dkp\", node=~\".*\", namespace=\"d8-cloud-instance-manager\", pod=~\".*\", container!=\"POD\"}[$__rate_interval]))\n)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum (\n  max(kube_controller_pod{d8_source=\"dkp\", node=~\".*\", namespace=\"d8-cloud-instance-manager\", controller=\"deploy/node-controller\", pod=~\".*\"}) by(pod)\n  * on (pod)\n  sum by (pod) (avg_over_time(container_memory_working_set_bytes:without_kmem{d8_source=\"dkp\", node=~\".*\", namespace=\"d8-cloud-instance-manager\", pod=~\".*\", container!=\"POD\"}[$__rate_interval]))\n)",
     "legendFormat": "Working set bytes without kmem"
    },
    {
     "expr": "sum (\n  max(kube_controller_pod{d8_source=\"dkp\", node=~\".*\", namespace=\"d8-cloud-instance-manager\", controller=\"deploy/node-controller\", pod=~\".*\"}) by(pod)\n  * on (pod)\n  sum by (pod) (avg_over_time(container_memory:kmem{d8_source=\"dkp\", node=~\".*\", namespace=\"d8-cloud-instance-manager\", pod=~\".*\", container!=\"POD\"}[$__rate_interval]))\n)",
     "legendFormat": "Kmem"
    }
   ]
  },
  { "title": "Reconcile stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Webhook Request Rate",
   "type": "timeseries",
   "description": "Number of webhook requests processed per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (webhook)(\nrate(\ncontroller_runtime_webhook_latency_seconds_count{d8_source=\"dkp\", \nnamespace=\"d8-cloud-instance-manager\",\npod=~\"node-controller.*\"\n}[$__rate_interval]\n))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile Request Rate",
   "type": "timeseries",
   "description": "Number of Reconcile requests processed per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (controller) (\n  rate(controller_runtime_reconcile_total{d8_source=\"dkp\", \n    namespace=\"d8-cloud-instance-manager\",\n    job=\"node-controller\"\n  }[1m])\n)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile Duration p99",
   "type": "timeseries",
   "description": "Controllers with the longest reconcile duration",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (controller, le) (\n    rate(controller_runtime_reconcile_time_seconds_bucket{d8_source=\"dkp\", \n      namespace=\"d8-cloud-instance-manager\",\n      job=\"node-controller\"\n    }[1m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Workers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by(controller)(\ncontroller_runtime_active_workers{d8_source=\"dkp\", \njob=\"node-controller\"\n}\n)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile Error Rate ",
   "type": "timeseries",
   "description": "Controllers with the highest error rate",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by (controller) (\n  rate(controller_runtime_reconcile_errors_total{d8_source=\"dkp\", \n    namespace=\"d8-cloud-instance-manager\",\n    job=\"node-controller\"\n  }[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Request Rate by Operation",
   "type": "timeseries",
   "description": "Number of controller-runtime client Get/List operations",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation) (\n  rate(node_controller_client_requests_total{d8_source=\"dkp\", \n    namespace=\"d8-cloud-instance-manager\",\n    pod=~\"node-controller.*\"\n  }[$__rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cache and queue depth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Cache by objects",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(api_group, kind) (node_controller_cache_objects{d8_source=\"dkp\"})",
     "legendFormat": "{{api_group}}/{{kind}}"
    }
   ]
  },
  {
   "title": "Workqueue Depth",
   "type": "timeseries",
   "description": "Workqueues with accumulated backlog",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum by (name) (\n  workqueue_depth{d8_source=\"dkp\", \n    namespace=\"d8-cloud-instance-manager\",\n    job=\"node-controller\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Pause Duration p75",
   "type": "timeseries",
   "description": "GC pause duration",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(\n  go_gc_duration_seconds{\n    d8_source=\"dkp\", namespace=\"d8-cloud-instance-manager\",\n    pod=~\"node-controller.*\",\n    quantile=\"0.75\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}