{
 "title": "Istio Performance Dashboard",
 "description": "Istio Performance Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Performance Dashboard Notes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Performance Dashboard README",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "The charts on this dashboard are intended to show Istio main components cost in terms of resources utilization under steady load.\n\n- **vCPU / 1k rps:** shows vCPU utilization by the main Istio components normalized by 1000 requests/second. When idle or low traffic, this chart will be blank. The curve for istio-proxy refers to the services sidecars only.\n- **vCPU:** vCPU utilization by Istio components, not normalized.\n- **Memory:** memory footprint for the components. Telemetry and policy are normalized by 1k rps, and no data is shown  when there is no traffic. For ingress and istio-proxy, the data is per instance.\n- **Bytes transferred / sec:** shows the number of bytes flowing through each Istio component.\n\n\n"
   }
  },
  {
   "title": "vCPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "vCPU / 1k rps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(irate(container_cpu_usage_seconds_total{d8_source=\"dkp\", pod=~\"istio-ingressgateway-.*\",container=\"istio-proxy\"}[$__rate_interval])) / (round(sum(irate(istio_requests_total{d8_source=\"dkp\", source_workload=\"istio-ingressgateway\", reporter=\"source\"}[$__rate_interval])), 0.001)/1000))",
     "legendFormat": "istio-ingressgateway"
    },
    {
     "expr": "(sum(irate(container_cpu_usage_seconds_total{d8_source=\"dkp\", namespace!=\"istio-system\",container=\"istio-proxy\"}[$__rate_interval]))/ (round(sum(irate(istio_requests_total{d8_source=\"dkp\"}[$__rate_interval])), 0.001)/1000))/ (sum(irate(istio_requests_total{d8_source=\"dkp\", source_workload=\"istio-ingressgateway\"}[$__rate_interval])) >bool 10)",
     "legendFormat": "istio-proxy"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{d8_source=\"dkp\", pod=~\"istio-ingressgateway-.*\",container=\"istio-proxy\"}[$__rate_interval]))",
     "legendFormat": "istio-ingressgateway"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{d8_source=\"dkp\", namespace!=\"istio-system\",container=\"istio-proxy\"}[$__rate_interval]))",
     "legendFormat": "istio-proxy"
    }
   ]
  },
  {
   "title": "Memory and Data Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{d8_source=\"dkp\", pod=~\"istio-ingressgateway-.*\"}) / count(container_memory_working_set_bytes{d8_source=\"dkp\", pod=~\"istio-ingressgateway-.*\",container!=\"POD\"})",
     "legendFormat": "per istio-ingressgateway"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{d8_source=\"dkp\", namespace!=\"istio-system\",container=\"istio-proxy\"}) / count(container_memory_working_set_bytes{d8_source=\"dkp\", namespace!=\"istio-system\",container=\"istio-proxy\"})",
     "legendFormat": "per istio proxy"
    }
   ]
  },
  {
   "title": "Bytes transferred / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(istio_response_bytes_sum{d8_source=\"dkp\", source_workload=\"istio-ingressgateway\", reporter=\"source\"}[$__rate_interval]))",
     "legendFormat": "istio-ingressgateway"
    },
    {
     "expr": "sum(irate(istio_response_bytes_sum{d8_source=\"dkp\", source_workload_namespace!=\"istio-system\", reporter=\"source\"}[$__rate_interval])) + sum(irate(istio_request_bytes_sum{d8_source=\"dkp\", source_workload_namespace!=\"istio-system\", reporter=\"source\"}[$__rate_interval]))",
     "legendFormat": "istio-proxy"
    }
   ]
  },
  {
   "title": "Istio Component Versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Istio Components by Version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(istio_build{d8_source=\"dkp\"}) by (component, tag)",
     "legendFormat": "{{ component }}: {{ tag }}"
    }
   ]
  },
  {
   "title": "Proxy Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{d8_source=\"dkp\", container=\"istio-proxy\"})",
     "legendFormat": "Total (k8s)"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{d8_source=\"dkp\", container=\"istio-proxy\"}[$__rate_interval]))",
     "legendFormat": "Total (k8s)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{d8_source=\"dkp\", container=\"istio-proxy\"})",
     "legendFormat": "Total (k8s)"
    }
   ]
  },
  {
   "title": "Istiod Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (version) (process_virtual_memory_bytes{d8_source=\"dkp\", app=\"istiod\"})",
     "legendFormat": "{{version}} - Virtual Memory"
    },
    {
     "expr": "sum by (version) (process_resident_memory_bytes{d8_source=\"dkp\", app=\"istiod\"})",
     "legendFormat": "{{version}} - Resident Memory"
    },
    {
     "expr": "sum by (version) (go_memstats_alloc_bytes{d8_source=\"dkp\", app=\"istiod\"})",
     "legendFormat": "{{version}} - Alloc"
    },
    {
     "expr": "sum by (version) (go_memstats_heap_inuse_bytes{d8_source=\"dkp\", app=\"istiod\"})",
     "legendFormat": "{{version}} - Heap in-use"
    },
    {
     "expr": "sum by (version) (go_memstats_stack_inuse_bytes{d8_source=\"dkp\", app=\"istiod\"})",
     "legendFormat": "{{version}} - Stack in-use"
    },
    {
     "expr": "sum by (label_app_kubernetes_io_version) (container_memory_working_set_bytes{d8_source=\"dkp\", container=~\"discovery|istio-proxy\", pod=~\"istiod-.*\", namespace=\"d8-istio\"} * on (namespace, pod) group_left (label_app_kubernetes_io_version) kube_pod_labels{d8_source=\"dkp\", namespace=\"d8-istio\", pod=~\"istiod-.*\", label_app_kubernetes_io_version!=\"\"})",
     "legendFormat": "{{label_app_kubernetes_io_version}} - Total (k8s)"
    },
    {
     "expr": "sum by (label_app_kubernetes_io_version, container) (container_memory_working_set_bytes{d8_source=\"dkp\", container=~\"discovery|istio-proxy\", pod=~\"istiod-.*\", namespace=\"d8-istio\"} * on (namespace, pod) group_left (label_app_kubernetes_io_version) kube_pod_labels{d8_source=\"dkp\", namespace=\"d8-istio\", pod=~\"istiod-.*\", label_app_kubernetes_io_version!=\"\"})",
     "legendFormat": "{{label_app_kubernetes_io_version}} - {{container}} (k8s)"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (label_app_kubernetes_io_version) (rate(container_cpu_usage_seconds_total{d8_source=\"dkp\", container=~\"discovery|istio-proxy\", pod=~\"istiod-.*\", namespace=\"d8-istio\"}[$__rate_interval]) * on (namespace, pod) group_left (label_app_kubernetes_io_version) kube_pod_labels{d8_source=\"dkp\", namespace=\"d8-istio\", pod=~\"istiod-.*\", label_app_kubernetes_io_version!=\"\"})",
     "legendFormat": "{{label_app_kubernetes_io_version}} - Total (k8s)"
    },
    {
     "expr": "sum by (label_app_kubernetes_io_version, container) (rate(container_cpu_usage_seconds_total{d8_source=\"dkp\", container=~\"discovery|istio-proxy\", pod=~\"istiod-.*\", namespace=\"d8-istio\"}[$__rate_interval]) * on (namespace, pod) group_left (label_app_kubernetes_io_version) kube_pod_labels{d8_source=\"dkp\", namespace=\"d8-istio\", pod=~\"istiod-.*\", label_app_kubernetes_io_version!=\"\"})",
     "legendFormat": "{{label_app_kubernetes_io_version}} - {{container}} (k8s)"
    },
    {
     "expr": "sum by (version) (irate(process_cpu_seconds_total{d8_source=\"dkp\", app=\"istiod\"}[$__rate_interval]))",
     "legendFormat": "{{version}} - pilot (self-reported)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{d8_source=\"dkp\",  container=~\"discovery|istio-proxy\", pod=~\"istiod-.*\"}",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (version) (go_goroutines{d8_source=\"dkp\", app=\"istiod\"})",
     "legendFormat": "{{version}}"
    }
   ]
  }
 ]
}