{
 "title": "Istio Control Plane Dashboard",
 "description": "Istio Control Plane Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Deployed Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pilot Versions",
   "type": "timeseries",
   "description": "Version number of each running instance",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (tag) (istio_build{d8_source=\"dkp\", component=\"pilot\"})",
     "legendFormat": "Version ({{tag}})"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage of each running instance",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{d8_source=\"dkp\", container=\"discovery\",pod=~\"istiod-.*\"})",
     "legendFormat": "Container ({{pod}})"
    },
    {
     "expr": "sum by (pod) (go_memstats_stack_inuse_bytes{d8_source=\"dkp\", app=\"istiod\"})",
     "legendFormat": "Stack ({{pod}})"
    },
    {
     "expr": "sum by (pod) (go_memstats_heap_inuse_bytes{d8_source=\"dkp\", app=\"istiod\"})",
     "legendFormat": "Heap (In Use) ({{pod}})"
    },
    {
     "expr": "sum by (pod) (go_memstats_heap_alloc_bytes{d8_source=\"dkp\", app=\"istiod\"})",
     "legendFormat": "Heap (Allocated) ({{pod}})"
    }
   ]
  },
  {
   "title": "Memory Allocations",
   "type": "timeseries",
   "description": "Details about memory allocations",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(go_memstats_alloc_bytes_total{d8_source=\"dkp\", app=\"istiod\"}[$__rate_interval]))",
     "legendFormat": "Bytes ({{pod}})"
    },
    {
     "expr": "sum by (pod) (rate(go_memstats_mallocs_total{d8_source=\"dkp\", app=\"istiod\"}[$__rate_interval]))",
     "legendFormat": "Objects ({{pod}})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage of each running instance",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{d8_source=\"dkp\", container=\"discovery\",pod=~\"istiod-.*\"}[$__rate_interval]))",
     "legendFormat": "Container ({{pod}})"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Goroutine count for each running instance",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 2 },
   "targets": [
    {
     "expr": "sum by (pod) (go_goroutines{d8_source=\"dkp\", app=\"istiod\"})",
     "legendFormat": "Goroutines ({{pod}})"
    }
   ]
  },
  { "title": "Push Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "XDS Pushes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (type) (irate(pilot_xds_pushes{d8_source=\"dkp\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Events",
   "type": "timeseries",
   "description": "Size of each xDS push.\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "sum by (type,event) (rate(pilot_k8s_reg_events{d8_source=\"dkp\"}[$__rate_interval]))",
     "legendFormat": "{{event}} {{type}}"
    },
    {
     "expr": "sum by (type,event) (rate(pilot_k8s_cfg_events{d8_source=\"dkp\"}[$__rate_interval]))",
     "legendFormat": "{{event}} {{type}}"
    },
    {
     "expr": "sum by (type) (rate(pilot_push_triggers{d8_source=\"dkp\"}[$__rate_interval]))",
     "legendFormat": "Push {{type}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Total number of XDS connections\n",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{d8_source=\"dkp\", cluster_name=\"xds-grpc\"})",
     "legendFormat": "Connections (client reported)"
    },
    {
     "expr": "sum (pilot_xds{d8_source=\"dkp\"})",
     "legendFormat": "Connections (server reported)"
    }
   ]
  },
  {
   "title": "Push Errors",
   "type": "timeseries",
   "description": "Number of push errors. Many of these are at least potentional fatal and should be explored in-depth via Istiod logs.\nNote: metrics here do not use rate() to avoid missing transition from \"No series\"; series are not reported if there are no errors at all.\n",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (type) (pilot_total_xds_rejects{d8_source=\"dkp\"})",
     "legendFormat": "Rejected Config ({{type}})"
    },
    {
     "expr": "pilot_total_xds_internal_errors{d8_source=\"dkp\"}",
     "legendFormat": "Internal Errors"
    },
    {
     "expr": "pilot_xds_push_context_errors{d8_source=\"dkp\"}",
     "legendFormat": "Push Context Errors"
    }
   ]
  },
  {
   "title": "Push Time",
   "type": "heatmap",
   "description": "Distribution of xDS push time from Istiod to proxies.\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(pilot_xds_push_time_bucket{d8_source=\"dkp\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Push Size",
   "type": "heatmap",
   "description": "Size of each xDS push.\n",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(pilot_xds_config_size_bytes_bucket{d8_source=\"dkp\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Webhooks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Validation",
   "type": "timeseries",
   "description": "Rate of Galley configuration validation results.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "sum (rate(galley_validation_passed{d8_source=\"dkp\"}[$__rate_interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum (rate(galley_validation_failed{d8_source=\"dkp\"}[$__rate_interval]))",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Injection",
   "type": "timeseries",
   "description": "Rate of sidecar injection results.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "targets": [
    {
     "expr": "sum (rate(sidecar_injection_success_total{d8_source=\"dkp\"}[$__rate_interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum (rate(sidecar_injection_failure_total{d8_source=\"dkp\"}[$__rate_interval]))",
     "legendFormat": "Failure"
    }
   ]
  }
 ]
}