{
 "title": "Deckhouse",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Heartbeat",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ceil(max by (job) (increase(deckhouse_live_ticks[1m]) > 5))^0",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Main queue length",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "deckhouse_tasks_queue_length{queue=\"main\"}"
    }
   ]
  },
  {
   "title": "Last startup converge duration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "deckhouse_convergence_seconds{activation=\"OperatorStartup\"}"
    }
   ]
  },
  {
   "title": "Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queue length",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (queue) (deckhouse_tasks_queue_length{queue!~\"main|main-subqueue.*\"})"
      }
     ]
    },
    {
     "title": "Queue rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 9 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(deckhouse_tasks_queue_length[$__interval_sx4]) > 0",
       "legendFormat": "{{ queue }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Snapshots objects",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum by (hook, binding) (deckhouse_kube_snapshot_objects)",
       "legendFormat": "{{ hook }} - {{ binding}}"
      }
     ]
    },
    {
     "title": "Snapshots size",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (hook, binding) (deckhouse_kube_snapshot_bytes)",
       "legendFormat": "{{ hook }} - {{ binding }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total CPU time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"deckhouse\"}[$__interval_sx4])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{job=\"deckhouse\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Process Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"deckhouse\"}",
       "legendFormat": "{{pod}} - resident"
      },
      {
       "expr": "process_virtual_memory_bytes{job=\"deckhouse\"}",
       "legendFormat": "{{pod}} - virtual"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{job=\"deckhouse\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Opened file descriptors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{job=\"deckhouse\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Object allocations rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{job=\"deckhouse\"}[$__interval_sx4])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "GC duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "max by (job, quantile) (go_gc_duration_seconds{job=\"deckhouse\"})",
       "legendFormat": "Quantile - {{ quantile }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events frequency by Kind",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (kind) (rate(deckhouse_kube_event_duration_seconds_count[$__interval_sx4])) > 0",
       "legendFormat": " {{ kind }}"
      }
     ]
    },
    {
     "title": "Hook run frequency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (hook) (rate(deckhouse_module_hook_run_seconds_count[$__interval_sx4])) > 0",
       "legendFormat": " {{ hook }}"
      },
      {
       "expr": "sum by (hook) (rate(deckhouse_glob_hook_run_seconds_count[$__interval_sx4])) > 0"
      }
     ]
    },
    {
     "title": "JQ Filter frequency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (hook, binding) (rate(deckhouse_kube_jq_filter_duration_seconds_count[$__interval_sx4])) > 0",
       "legendFormat": "{{ hook }} - {{ binding }}"
      }
     ]
    },
    {
     "title": "Helm run frequency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (module) (rate(deckhouse_helm_operation_seconds_count[$__interval_sx4])) > 0",
       "legendFormat": "{{ module }}"
      }
     ]
    },
    {
     "title": "Kubernetes client requests frequency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ceil(sum by (module) (increase(deckhouse_kubernetes_client_request_result_total[$__interval_sx4]))) > 0",
       "legendFormat": "{{ module }}"
      }
     ]
    }
   ]
  }
 ]
}