apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    heritage: deckhouse
    module: prometheus
    rbac.deckhouse.io/aggregate-to-observability-as: manager
    rbac.deckhouse.io/kind: capability
    rbac.deckhouse.io/scope: system
    rbac.deckhouse.io/namespace: d8-monitoring
  name: d8:system-capability:prometheus:edit
  annotations:
    en.meta.deckhouse.io/title: "Module prometheus: edit configuration"
    ru.meta.deckhouse.io/title: "Модуль prometheus: управление конфигурацией"
    en.meta.deckhouse.io/description: "Manage the prometheus module configuration."
    ru.meta.deckhouse.io/description: "Управление конфигурацией модуля prometheus."
rules:
- apiGroups:
  - deckhouse.io
  resources:
  - clusteralerts
  - customalertmanagers
  - customprometheusrules
  - grafanaadditionaldatasources
  - grafanaalertschannels
  - grafanadashboarddefinitions
  - prometheusremotewrites
  verbs:
  - create
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - deckhouse.io
  resourceNames:
  - prometheus
  resources:
  - moduleconfigs
  verbs:
  - create
  - update
  - patch
  - delete
