//go:build !ignore_autogenerated

// Copyright 2025 Flant JSC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Application) DeepCopyInto(out *Application) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Application.
func (in *Application) DeepCopy() *Application {
	if in == nil {
		return nil
	}
	out := new(Application)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Application) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationInternalStatusCondition) DeepCopyInto(out *ApplicationInternalStatusCondition) {
	*out = *in
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationInternalStatusCondition.
func (in *ApplicationInternalStatusCondition) DeepCopy() *ApplicationInternalStatusCondition {
	if in == nil {
		return nil
	}
	out := new(ApplicationInternalStatusCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationList) DeepCopyInto(out *ApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Application, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationList.
func (in *ApplicationList) DeepCopy() *ApplicationList {
	if in == nil {
		return nil
	}
	out := new(ApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationPackage) DeepCopyInto(out *ApplicationPackage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationPackage.
func (in *ApplicationPackage) DeepCopy() *ApplicationPackage {
	if in == nil {
		return nil
	}
	out := new(ApplicationPackage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationPackage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationPackageList) DeepCopyInto(out *ApplicationPackageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApplicationPackage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationPackageList.
func (in *ApplicationPackageList) DeepCopy() *ApplicationPackageList {
	if in == nil {
		return nil
	}
	out := new(ApplicationPackageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationPackageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (apStatus *ApplicationPackageStatus) DeepCopyInto(out *ApplicationPackageStatus) {
	*out = *apStatus
	if apStatus.Installed != nil {
		in, out := &apStatus.Installed, &out.Installed
		*out = make(map[NamespaceName][]ApplicationPackageStatusInstalled, len(*in))
		for key, val := range *in {
			var outVal []ApplicationPackageStatusInstalled
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]ApplicationPackageStatusInstalled, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if apStatus.AvailableRepositories != nil {
		in, out := &apStatus.AvailableRepositories, &out.AvailableRepositories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationPackageStatus.
func (apStatus *ApplicationPackageStatus) DeepCopy() *ApplicationPackageStatus {
	if apStatus == nil {
		return nil
	}
	out := new(ApplicationPackageStatus)
	apStatus.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationPackageStatusInstalled) DeepCopyInto(out *ApplicationPackageStatusInstalled) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationPackageStatusInstalled.
func (in *ApplicationPackageStatusInstalled) DeepCopy() *ApplicationPackageStatusInstalled {
	if in == nil {
		return nil
	}
	out := new(ApplicationPackageStatusInstalled)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationPackageVersion) DeepCopyInto(out *ApplicationPackageVersion) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationPackageVersion.
func (in *ApplicationPackageVersion) DeepCopy() *ApplicationPackageVersion {
	if in == nil {
		return nil
	}
	out := new(ApplicationPackageVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationPackageVersion) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationPackageVersionCondition) DeepCopyInto(out *ApplicationPackageVersionCondition) {
	*out = *in
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationPackageVersionCondition.
func (in *ApplicationPackageVersionCondition) DeepCopy() *ApplicationPackageVersionCondition {
	if in == nil {
		return nil
	}
	out := new(ApplicationPackageVersionCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationPackageVersionList) DeepCopyInto(out *ApplicationPackageVersionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApplicationPackageVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationPackageVersionList.
func (in *ApplicationPackageVersionList) DeepCopy() *ApplicationPackageVersionList {
	if in == nil {
		return nil
	}
	out := new(ApplicationPackageVersionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationPackageVersionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationPackageVersionSpec) DeepCopyInto(out *ApplicationPackageVersionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationPackageVersionSpec.
func (in *ApplicationPackageVersionSpec) DeepCopy() *ApplicationPackageVersionSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationPackageVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationPackageVersionStatus) DeepCopyInto(out *ApplicationPackageVersionStatus) {
	*out = *in
	if in.PackageMetadata != nil {
		in, out := &in.PackageMetadata, &out.PackageMetadata
		*out = new(ApplicationPackageVersionStatusMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ApplicationPackageVersionCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UsedBy != nil {
		in, out := &in.UsedBy, &out.UsedBy
		*out = make([]ApplicationPackageVersionStatusInstance, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationPackageVersionStatus.
func (in *ApplicationPackageVersionStatus) DeepCopy() *ApplicationPackageVersionStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationPackageVersionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationPackageVersionStatusInstance) DeepCopyInto(out *ApplicationPackageVersionStatusInstance) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationPackageVersionStatusInstance.
func (in *ApplicationPackageVersionStatusInstance) DeepCopy() *ApplicationPackageVersionStatusInstance {
	if in == nil {
		return nil
	}
	out := new(ApplicationPackageVersionStatusInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationPackageVersionStatusMetadata) DeepCopyInto(out *ApplicationPackageVersionStatusMetadata) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(PackageDescription)
		**out = **in
	}
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = new(PackageRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Licensing != nil {
		in, out := &in.Licensing, &out.Licensing
		*out = new(PackageLicensing)
		(*in).DeepCopyInto(*out)
	}
	if in.Changelog != nil {
		in, out := &in.Changelog, &out.Changelog
		*out = new(PackageChangelog)
		(*in).DeepCopyInto(*out)
	}
	if in.Compatibility != nil {
		in, out := &in.Compatibility, &out.Compatibility
		*out = new(PackageVersionCompatibilityRules)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationPackageVersionStatusMetadata.
func (in *ApplicationPackageVersionStatusMetadata) DeepCopy() *ApplicationPackageVersionStatusMetadata {
	if in == nil {
		return nil
	}
	out := new(ApplicationPackageVersionStatusMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationSpec) DeepCopyInto(out *ApplicationSpec) {
	*out = *in
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationSpec.
func (in *ApplicationSpec) DeepCopy() *ApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationStatus) DeepCopyInto(out *ApplicationStatus) {
	*out = *in
	if in.CurrentVersion != nil {
		in, out := &in.CurrentVersion, &out.CurrentVersion
		*out = new(ApplicationStatusVersion)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ApplicationStatusCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InternalConditions != nil {
		in, out := &in.InternalConditions, &out.InternalConditions
		*out = make([]ApplicationInternalStatusCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationStatus.
func (in *ApplicationStatus) DeepCopy() *ApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationStatusCondition) DeepCopyInto(out *ApplicationStatusCondition) {
	*out = *in
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationStatusCondition.
func (in *ApplicationStatusCondition) DeepCopy() *ApplicationStatusCondition {
	if in == nil {
		return nil
	}
	out := new(ApplicationStatusCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationStatusVersion) DeepCopyInto(out *ApplicationStatusVersion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationStatusVersion.
func (in *ApplicationStatusVersion) DeepCopy() *ApplicationStatusVersion {
	if in == nil {
		return nil
	}
	out := new(ApplicationStatusVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailableModule) DeepCopyInto(out *AvailableModule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailableModule.
func (in *AvailableModule) DeepCopy() *AvailableModule {
	if in == nil {
		return nil
	}
	out := new(AvailableModule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeckhouseRelease) DeepCopyInto(out *DeckhouseRelease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeckhouseRelease.
func (in *DeckhouseRelease) DeepCopy() *DeckhouseRelease {
	if in == nil {
		return nil
	}
	out := new(DeckhouseRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeckhouseRelease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeckhouseReleaseList) DeepCopyInto(out *DeckhouseReleaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeckhouseRelease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeckhouseReleaseList.
func (in *DeckhouseReleaseList) DeepCopy() *DeckhouseReleaseList {
	if in == nil {
		return nil
	}
	out := new(DeckhouseReleaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeckhouseReleaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeckhouseReleaseSpec) DeepCopyInto(out *DeckhouseReleaseSpec) {
	*out = *in
	if in.ApplyAfter != nil {
		in, out := &in.ApplyAfter, &out.ApplyAfter
		*out = (*in).DeepCopy()
	}
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Disruptions != nil {
		in, out := &in.Disruptions, &out.Disruptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Changelog != nil {
		in, out := &in.Changelog, &out.Changelog
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeckhouseReleaseSpec.
func (in *DeckhouseReleaseSpec) DeepCopy() *DeckhouseReleaseSpec {
	if in == nil {
		return nil
	}
	out := new(DeckhouseReleaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeckhouseReleaseStatus) DeepCopyInto(out *DeckhouseReleaseStatus) {
	*out = *in
	in.TransitionTime.DeepCopyInto(&out.TransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeckhouseReleaseStatus.
func (in *DeckhouseReleaseStatus) DeepCopy() *DeckhouseReleaseStatus {
	if in == nil {
		return nil
	}
	out := new(DeckhouseReleaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Module) DeepCopyInto(out *Module) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Properties.DeepCopyInto(&out.Properties)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Module.
func (in *Module) DeepCopy() *Module {
	if in == nil {
		return nil
	}
	out := new(Module)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Module) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleAccessibility) DeepCopyInto(out *ModuleAccessibility) {
	*out = *in
	if in.Editions != nil {
		in, out := &in.Editions, &out.Editions
		*out = make(map[string]ModuleEdition, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleAccessibility.
func (in *ModuleAccessibility) DeepCopy() *ModuleAccessibility {
	if in == nil {
		return nil
	}
	out := new(ModuleAccessibility)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleCondition) DeepCopyInto(out *ModuleCondition) {
	*out = *in
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleCondition.
func (in *ModuleCondition) DeepCopy() *ModuleCondition {
	if in == nil {
		return nil
	}
	out := new(ModuleCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleConfig) DeepCopyInto(out *ModuleConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleConfig.
func (in *ModuleConfig) DeepCopy() *ModuleConfig {
	if in == nil {
		return nil
	}
	out := new(ModuleConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModuleConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleConfigList) DeepCopyInto(out *ModuleConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModuleConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleConfigList.
func (in *ModuleConfigList) DeepCopy() *ModuleConfigList {
	if in == nil {
		return nil
	}
	out := new(ModuleConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModuleConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleConfigSpec) DeepCopyInto(out *ModuleConfigSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleConfigSpec.
func (in *ModuleConfigSpec) DeepCopy() *ModuleConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ModuleConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleConfigStatus) DeepCopyInto(out *ModuleConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleConfigStatus.
func (in *ModuleConfigStatus) DeepCopy() *ModuleConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ModuleConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleDisableOptions) DeepCopyInto(out *ModuleDisableOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleDisableOptions.
func (in *ModuleDisableOptions) DeepCopy() *ModuleDisableOptions {
	if in == nil {
		return nil
	}
	out := new(ModuleDisableOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleDocumentation) DeepCopyInto(out *ModuleDocumentation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleDocumentation.
func (in *ModuleDocumentation) DeepCopy() *ModuleDocumentation {
	if in == nil {
		return nil
	}
	out := new(ModuleDocumentation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModuleDocumentation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleDocumentationCondition) DeepCopyInto(out *ModuleDocumentationCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleDocumentationCondition.
func (in *ModuleDocumentationCondition) DeepCopy() *ModuleDocumentationCondition {
	if in == nil {
		return nil
	}
	out := new(ModuleDocumentationCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleDocumentationKind) DeepCopyInto(out *ModuleDocumentationKind) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleDocumentationKind.
func (in *ModuleDocumentationKind) DeepCopy() *ModuleDocumentationKind {
	if in == nil {
		return nil
	}
	out := new(ModuleDocumentationKind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleDocumentationList) DeepCopyInto(out *ModuleDocumentationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModuleDocumentation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleDocumentationList.
func (in *ModuleDocumentationList) DeepCopy() *ModuleDocumentationList {
	if in == nil {
		return nil
	}
	out := new(ModuleDocumentationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModuleDocumentationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleDocumentationSpec) DeepCopyInto(out *ModuleDocumentationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleDocumentationSpec.
func (in *ModuleDocumentationSpec) DeepCopy() *ModuleDocumentationSpec {
	if in == nil {
		return nil
	}
	out := new(ModuleDocumentationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleDocumentationStatus) DeepCopyInto(out *ModuleDocumentationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ModuleDocumentationCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleDocumentationStatus.
func (in *ModuleDocumentationStatus) DeepCopy() *ModuleDocumentationStatus {
	if in == nil {
		return nil
	}
	out := new(ModuleDocumentationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleEdition) DeepCopyInto(out *ModuleEdition) {
	*out = *in
	if in.EnabledInBundles != nil {
		in, out := &in.EnabledInBundles, &out.EnabledInBundles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleEdition.
func (in *ModuleEdition) DeepCopy() *ModuleEdition {
	if in == nil {
		return nil
	}
	out := new(ModuleEdition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleList) DeepCopyInto(out *ModuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Module, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleList.
func (in *ModuleList) DeepCopy() *ModuleList {
	if in == nil {
		return nil
	}
	out := new(ModuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModulePlatformRequirements) DeepCopyInto(out *ModulePlatformRequirements) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModulePlatformRequirements.
func (in *ModulePlatformRequirements) DeepCopy() *ModulePlatformRequirements {
	if in == nil {
		return nil
	}
	out := new(ModulePlatformRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleProperties) DeepCopyInto(out *ModuleProperties) {
	*out = *in
	if in.Subsystems != nil {
		in, out := &in.Subsystems, &out.Subsystems
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AvailableSources != nil {
		in, out := &in.AvailableSources, &out.AvailableSources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = new(ModuleRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.DisableOptions != nil {
		in, out := &in.DisableOptions, &out.DisableOptions
		*out = new(ModuleDisableOptions)
		**out = **in
	}
	if in.Accessibility != nil {
		in, out := &in.Accessibility, &out.Accessibility
		*out = new(ModuleAccessibility)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleProperties.
func (in *ModuleProperties) DeepCopy() *ModuleProperties {
	if in == nil {
		return nil
	}
	out := new(ModuleProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModulePullOverride) DeepCopyInto(out *ModulePullOverride) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModulePullOverride.
func (in *ModulePullOverride) DeepCopy() *ModulePullOverride {
	if in == nil {
		return nil
	}
	out := new(ModulePullOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModulePullOverride) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModulePullOverrideList) DeepCopyInto(out *ModulePullOverrideList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModulePullOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModulePullOverrideList.
func (in *ModulePullOverrideList) DeepCopy() *ModulePullOverrideList {
	if in == nil {
		return nil
	}
	out := new(ModulePullOverrideList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModulePullOverrideList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModulePullOverrideSpec) DeepCopyInto(out *ModulePullOverrideSpec) {
	*out = *in
	out.ScanInterval = in.ScanInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModulePullOverrideSpec.
func (in *ModulePullOverrideSpec) DeepCopy() *ModulePullOverrideSpec {
	if in == nil {
		return nil
	}
	out := new(ModulePullOverrideSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModulePullOverrideStatus) DeepCopyInto(out *ModulePullOverrideStatus) {
	*out = *in
	in.UpdatedAt.DeepCopyInto(&out.UpdatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModulePullOverrideStatus.
func (in *ModulePullOverrideStatus) DeepCopy() *ModulePullOverrideStatus {
	if in == nil {
		return nil
	}
	out := new(ModulePullOverrideStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleRelease) DeepCopyInto(out *ModuleRelease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleRelease.
func (in *ModuleRelease) DeepCopy() *ModuleRelease {
	if in == nil {
		return nil
	}
	out := new(ModuleRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModuleRelease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleReleaseList) DeepCopyInto(out *ModuleReleaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModuleRelease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleReleaseList.
func (in *ModuleReleaseList) DeepCopy() *ModuleReleaseList {
	if in == nil {
		return nil
	}
	out := new(ModuleReleaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModuleReleaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleReleasePlatformRequirements) DeepCopyInto(out *ModuleReleasePlatformRequirements) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleReleasePlatformRequirements.
func (in *ModuleReleasePlatformRequirements) DeepCopy() *ModuleReleasePlatformRequirements {
	if in == nil {
		return nil
	}
	out := new(ModuleReleasePlatformRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleReleaseRequirements) DeepCopyInto(out *ModuleReleaseRequirements) {
	*out = *in
	out.ModuleReleasePlatformRequirements = in.ModuleReleasePlatformRequirements
	if in.ParentModules != nil {
		in, out := &in.ParentModules, &out.ParentModules
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleReleaseRequirements.
func (in *ModuleReleaseRequirements) DeepCopy() *ModuleReleaseRequirements {
	if in == nil {
		return nil
	}
	out := new(ModuleReleaseRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleReleaseSpec) DeepCopyInto(out *ModuleReleaseSpec) {
	*out = *in
	if in.ApplyAfter != nil {
		in, out := &in.ApplyAfter, &out.ApplyAfter
		*out = (*in).DeepCopy()
	}
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = new(ModuleReleaseRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.UpdateSpec != nil {
		in, out := &in.UpdateSpec, &out.UpdateSpec
		*out = new(UpdateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Changelog != nil {
		in, out := &in.Changelog, &out.Changelog
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleReleaseSpec.
func (in *ModuleReleaseSpec) DeepCopy() *ModuleReleaseSpec {
	if in == nil {
		return nil
	}
	out := new(ModuleReleaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleReleaseStatus) DeepCopyInto(out *ModuleReleaseStatus) {
	*out = *in
	in.TransitionTime.DeepCopyInto(&out.TransitionTime)
	out.PullDuration = in.PullDuration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleReleaseStatus.
func (in *ModuleReleaseStatus) DeepCopy() *ModuleReleaseStatus {
	if in == nil {
		return nil
	}
	out := new(ModuleReleaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleRequirements) DeepCopyInto(out *ModuleRequirements) {
	*out = *in
	out.ModulePlatformRequirements = in.ModulePlatformRequirements
	if in.ParentModules != nil {
		in, out := &in.ParentModules, &out.ParentModules
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleRequirements.
func (in *ModuleRequirements) DeepCopy() *ModuleRequirements {
	if in == nil {
		return nil
	}
	out := new(ModuleRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSettingsConversion) DeepCopyInto(out *ModuleSettingsConversion) {
	*out = *in
	if in.Expr != nil {
		in, out := &in.Expr, &out.Expr
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Descriptions != nil {
		in, out := &in.Descriptions, &out.Descriptions
		*out = new(ModuleSettingsConversionDescriptions)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSettingsConversion.
func (in *ModuleSettingsConversion) DeepCopy() *ModuleSettingsConversion {
	if in == nil {
		return nil
	}
	out := new(ModuleSettingsConversion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSettingsConversionDescriptions) DeepCopyInto(out *ModuleSettingsConversionDescriptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSettingsConversionDescriptions.
func (in *ModuleSettingsConversionDescriptions) DeepCopy() *ModuleSettingsConversionDescriptions {
	if in == nil {
		return nil
	}
	out := new(ModuleSettingsConversionDescriptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSettingsDefinition) DeepCopyInto(out *ModuleSettingsDefinition) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSettingsDefinition.
func (in *ModuleSettingsDefinition) DeepCopy() *ModuleSettingsDefinition {
	if in == nil {
		return nil
	}
	out := new(ModuleSettingsDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModuleSettingsDefinition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSettingsDefinitionList) DeepCopyInto(out *ModuleSettingsDefinitionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModuleSettingsDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSettingsDefinitionList.
func (in *ModuleSettingsDefinitionList) DeepCopy() *ModuleSettingsDefinitionList {
	if in == nil {
		return nil
	}
	out := new(ModuleSettingsDefinitionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModuleSettingsDefinitionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSettingsDefinitionSpec) DeepCopyInto(out *ModuleSettingsDefinitionSpec) {
	*out = *in
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]ModuleSettingsDefinitionVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSettingsDefinitionSpec.
func (in *ModuleSettingsDefinitionSpec) DeepCopy() *ModuleSettingsDefinitionSpec {
	if in == nil {
		return nil
	}
	out := new(ModuleSettingsDefinitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSettingsDefinitionVersion) DeepCopyInto(out *ModuleSettingsDefinitionVersion) {
	*out = *in
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(v1.CustomResourceValidation)
		(*in).DeepCopyInto(*out)
	}
	if in.Conversions != nil {
		in, out := &in.Conversions, &out.Conversions
		*out = make([]ModuleSettingsConversion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSettingsDefinitionVersion.
func (in *ModuleSettingsDefinitionVersion) DeepCopy() *ModuleSettingsDefinitionVersion {
	if in == nil {
		return nil
	}
	out := new(ModuleSettingsDefinitionVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSource) DeepCopyInto(out *ModuleSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSource.
func (in *ModuleSource) DeepCopy() *ModuleSource {
	if in == nil {
		return nil
	}
	out := new(ModuleSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModuleSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSourceList) DeepCopyInto(out *ModuleSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModuleSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSourceList.
func (in *ModuleSourceList) DeepCopy() *ModuleSourceList {
	if in == nil {
		return nil
	}
	out := new(ModuleSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModuleSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSourceSpec) DeepCopyInto(out *ModuleSourceSpec) {
	*out = *in
	out.Registry = in.Registry
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSourceSpec.
func (in *ModuleSourceSpec) DeepCopy() *ModuleSourceSpec {
	if in == nil {
		return nil
	}
	out := new(ModuleSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSourceSpecRegistry) DeepCopyInto(out *ModuleSourceSpecRegistry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSourceSpecRegistry.
func (in *ModuleSourceSpecRegistry) DeepCopy() *ModuleSourceSpecRegistry {
	if in == nil {
		return nil
	}
	out := new(ModuleSourceSpecRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSourceStatus) DeepCopyInto(out *ModuleSourceStatus) {
	*out = *in
	in.SyncTime.DeepCopyInto(&out.SyncTime)
	if in.AvailableModules != nil {
		in, out := &in.AvailableModules, &out.AvailableModules
		*out = make([]AvailableModule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSourceStatus.
func (in *ModuleSourceStatus) DeepCopy() *ModuleSourceStatus {
	if in == nil {
		return nil
	}
	out := new(ModuleSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleStatus) DeepCopyInto(out *ModuleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ModuleCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleStatus.
func (in *ModuleStatus) DeepCopy() *ModuleStatus {
	if in == nil {
		return nil
	}
	out := new(ModuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleUpdatePolicy) DeepCopyInto(out *ModuleUpdatePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleUpdatePolicy.
func (in *ModuleUpdatePolicy) DeepCopy() *ModuleUpdatePolicy {
	if in == nil {
		return nil
	}
	out := new(ModuleUpdatePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModuleUpdatePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleUpdatePolicyList) DeepCopyInto(out *ModuleUpdatePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModuleUpdatePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleUpdatePolicyList.
func (in *ModuleUpdatePolicyList) DeepCopy() *ModuleUpdatePolicyList {
	if in == nil {
		return nil
	}
	out := new(ModuleUpdatePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModuleUpdatePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleUpdatePolicySpec) DeepCopyInto(out *ModuleUpdatePolicySpec) {
	*out = *in
	in.Update.DeepCopyInto(&out.Update)
	in.ModuleReleaseSelector.DeepCopyInto(&out.ModuleReleaseSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleUpdatePolicySpec.
func (in *ModuleUpdatePolicySpec) DeepCopy() *ModuleUpdatePolicySpec {
	if in == nil {
		return nil
	}
	out := new(ModuleUpdatePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleUpdatePolicySpecReleaseSelector) DeepCopyInto(out *ModuleUpdatePolicySpecReleaseSelector) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleUpdatePolicySpecReleaseSelector.
func (in *ModuleUpdatePolicySpecReleaseSelector) DeepCopy() *ModuleUpdatePolicySpecReleaseSelector {
	if in == nil {
		return nil
	}
	out := new(ModuleUpdatePolicySpecReleaseSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleUpdatePolicySpecUpdate) DeepCopyInto(out *ModuleUpdatePolicySpecUpdate) {
	*out = *in
	out.Windows = in.Windows.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleUpdatePolicySpecUpdate.
func (in *ModuleUpdatePolicySpecUpdate) DeepCopy() *ModuleUpdatePolicySpecUpdate {
	if in == nil {
		return nil
	}
	out := new(ModuleUpdatePolicySpecUpdate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageChangelog) DeepCopyInto(out *PackageChangelog) {
	*out = *in
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Fixes != nil {
		in, out := &in.Fixes, &out.Fixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageChangelog.
func (in *PackageChangelog) DeepCopy() *PackageChangelog {
	if in == nil {
		return nil
	}
	out := new(PackageChangelog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageDescription) DeepCopyInto(out *PackageDescription) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageDescription.
func (in *PackageDescription) DeepCopy() *PackageDescription {
	if in == nil {
		return nil
	}
	out := new(PackageDescription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageEdition) DeepCopyInto(out *PackageEdition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageEdition.
func (in *PackageEdition) DeepCopy() *PackageEdition {
	if in == nil {
		return nil
	}
	out := new(PackageEdition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageLicensing) DeepCopyInto(out *PackageLicensing) {
	*out = *in
	if in.Editions != nil {
		in, out := &in.Editions, &out.Editions
		*out = make(map[string]PackageEdition, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageLicensing.
func (in *PackageLicensing) DeepCopy() *PackageLicensing {
	if in == nil {
		return nil
	}
	out := new(PackageLicensing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageRepository) DeepCopyInto(out *PackageRepository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageRepository.
func (in *PackageRepository) DeepCopy() *PackageRepository {
	if in == nil {
		return nil
	}
	out := new(PackageRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PackageRepository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageRepositoryList) DeepCopyInto(out *PackageRepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PackageRepository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageRepositoryList.
func (in *PackageRepositoryList) DeepCopy() *PackageRepositoryList {
	if in == nil {
		return nil
	}
	out := new(PackageRepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PackageRepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageRepositoryOperation) DeepCopyInto(out *PackageRepositoryOperation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageRepositoryOperation.
func (in *PackageRepositoryOperation) DeepCopy() *PackageRepositoryOperation {
	if in == nil {
		return nil
	}
	out := new(PackageRepositoryOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PackageRepositoryOperation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageRepositoryOperationList) DeepCopyInto(out *PackageRepositoryOperationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PackageRepositoryOperation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageRepositoryOperationList.
func (in *PackageRepositoryOperationList) DeepCopy() *PackageRepositoryOperationList {
	if in == nil {
		return nil
	}
	out := new(PackageRepositoryOperationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PackageRepositoryOperationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageRepositoryOperationSpec) DeepCopyInto(out *PackageRepositoryOperationSpec) {
	*out = *in
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(PackageRepositoryOperationUpdate)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageRepositoryOperationSpec.
func (in *PackageRepositoryOperationSpec) DeepCopy() *PackageRepositoryOperationSpec {
	if in == nil {
		return nil
	}
	out := new(PackageRepositoryOperationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageRepositoryOperationStatus) DeepCopyInto(out *PackageRepositoryOperationStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Packages != nil {
		in, out := &in.Packages, &out.Packages
		*out = new(PackageRepositoryOperationStatusPackages)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]PackageRepositoryOperationStatusCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageRepositoryOperationStatus.
func (in *PackageRepositoryOperationStatus) DeepCopy() *PackageRepositoryOperationStatus {
	if in == nil {
		return nil
	}
	out := new(PackageRepositoryOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageRepositoryOperationStatusCondition) DeepCopyInto(out *PackageRepositoryOperationStatusCondition) {
	*out = *in
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageRepositoryOperationStatusCondition.
func (in *PackageRepositoryOperationStatusCondition) DeepCopy() *PackageRepositoryOperationStatusCondition {
	if in == nil {
		return nil
	}
	out := new(PackageRepositoryOperationStatusCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageRepositoryOperationStatusDiscoveredPackage) DeepCopyInto(out *PackageRepositoryOperationStatusDiscoveredPackage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageRepositoryOperationStatusDiscoveredPackage.
func (in *PackageRepositoryOperationStatusDiscoveredPackage) DeepCopy() *PackageRepositoryOperationStatusDiscoveredPackage {
	if in == nil {
		return nil
	}
	out := new(PackageRepositoryOperationStatusDiscoveredPackage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageRepositoryOperationStatusFailedPackage) DeepCopyInto(out *PackageRepositoryOperationStatusFailedPackage) {
	*out = *in
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]PackageRepositoryOperationStatusFailedPackageError, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageRepositoryOperationStatusFailedPackage.
func (in *PackageRepositoryOperationStatusFailedPackage) DeepCopy() *PackageRepositoryOperationStatusFailedPackage {
	if in == nil {
		return nil
	}
	out := new(PackageRepositoryOperationStatusFailedPackage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageRepositoryOperationStatusFailedPackageError) DeepCopyInto(out *PackageRepositoryOperationStatusFailedPackageError) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageRepositoryOperationStatusFailedPackageError.
func (in *PackageRepositoryOperationStatusFailedPackageError) DeepCopy() *PackageRepositoryOperationStatusFailedPackageError {
	if in == nil {
		return nil
	}
	out := new(PackageRepositoryOperationStatusFailedPackageError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageRepositoryOperationStatusPackage) DeepCopyInto(out *PackageRepositoryOperationStatusPackage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageRepositoryOperationStatusPackage.
func (in *PackageRepositoryOperationStatusPackage) DeepCopy() *PackageRepositoryOperationStatusPackage {
	if in == nil {
		return nil
	}
	out := new(PackageRepositoryOperationStatusPackage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageRepositoryOperationStatusPackages) DeepCopyInto(out *PackageRepositoryOperationStatusPackages) {
	*out = *in
	if in.Discovered != nil {
		in, out := &in.Discovered, &out.Discovered
		*out = make([]PackageRepositoryOperationStatusDiscoveredPackage, len(*in))
		copy(*out, *in)
	}
	if in.Failed != nil {
		in, out := &in.Failed, &out.Failed
		*out = make([]PackageRepositoryOperationStatusFailedPackage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Processed != nil {
		in, out := &in.Processed, &out.Processed
		*out = make([]PackageRepositoryOperationStatusPackage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageRepositoryOperationStatusPackages.
func (in *PackageRepositoryOperationStatusPackages) DeepCopy() *PackageRepositoryOperationStatusPackages {
	if in == nil {
		return nil
	}
	out := new(PackageRepositoryOperationStatusPackages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageRepositoryOperationUpdate) DeepCopyInto(out *PackageRepositoryOperationUpdate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageRepositoryOperationUpdate.
func (in *PackageRepositoryOperationUpdate) DeepCopy() *PackageRepositoryOperationUpdate {
	if in == nil {
		return nil
	}
	out := new(PackageRepositoryOperationUpdate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageRepositorySpec) DeepCopyInto(out *PackageRepositorySpec) {
	*out = *in
	out.Registry = in.Registry
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageRepositorySpec.
func (in *PackageRepositorySpec) DeepCopy() *PackageRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(PackageRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageRepositorySpecRegistry) DeepCopyInto(out *PackageRepositorySpecRegistry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageRepositorySpecRegistry.
func (in *PackageRepositorySpecRegistry) DeepCopy() *PackageRepositorySpecRegistry {
	if in == nil {
		return nil
	}
	out := new(PackageRepositorySpecRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageRepositoryStatus) DeepCopyInto(out *PackageRepositoryStatus) {
	*out = *in
	in.SyncTime.DeepCopyInto(&out.SyncTime)
	if in.Packages != nil {
		in, out := &in.Packages, &out.Packages
		*out = make([]PackageRepositoryStatusPackage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageRepositoryStatus.
func (in *PackageRepositoryStatus) DeepCopy() *PackageRepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(PackageRepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageRepositoryStatusPackage) DeepCopyInto(out *PackageRepositoryStatusPackage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageRepositoryStatusPackage.
func (in *PackageRepositoryStatusPackage) DeepCopy() *PackageRepositoryStatusPackage {
	if in == nil {
		return nil
	}
	out := new(PackageRepositoryStatusPackage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageRequirements) DeepCopyInto(out *PackageRequirements) {
	*out = *in
	if in.Modules != nil {
		in, out := &in.Modules, &out.Modules
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageRequirements.
func (in *PackageRequirements) DeepCopy() *PackageRequirements {
	if in == nil {
		return nil
	}
	out := new(PackageRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageVersionCompatibilityRule) DeepCopyInto(out *PackageVersionCompatibilityRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageVersionCompatibilityRule.
func (in *PackageVersionCompatibilityRule) DeepCopy() *PackageVersionCompatibilityRule {
	if in == nil {
		return nil
	}
	out := new(PackageVersionCompatibilityRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageVersionCompatibilityRules) DeepCopyInto(out *PackageVersionCompatibilityRules) {
	*out = *in
	if in.Upgrade != nil {
		in, out := &in.Upgrade, &out.Upgrade
		*out = new(PackageVersionCompatibilityRule)
		**out = **in
	}
	if in.Downgrade != nil {
		in, out := &in.Downgrade, &out.Downgrade
		*out = new(PackageVersionCompatibilityRule)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageVersionCompatibilityRules.
func (in *PackageVersionCompatibilityRules) DeepCopy() *PackageVersionCompatibilityRules {
	if in == nil {
		return nil
	}
	out := new(PackageVersionCompatibilityRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateConstraint) DeepCopyInto(out *UpdateConstraint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateConstraint.
func (in *UpdateConstraint) DeepCopy() *UpdateConstraint {
	if in == nil {
		return nil
	}
	out := new(UpdateConstraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateSpec) DeepCopyInto(out *UpdateSpec) {
	*out = *in
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]UpdateConstraint, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSpec.
func (in *UpdateSpec) DeepCopy() *UpdateSpec {
	if in == nil {
		return nil
	}
	out := new(UpdateSpec)
	in.DeepCopyInto(out)
	return out
}
