#!/bin/bash
# Copyright 2025 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -Eeo pipefail

# Install systemctl wrapper binary.
WRAPPER=systemctl-power-commands-wrapper
mkdir -p /opt/deckhouse/bin
cp -f "${WRAPPER}" /opt/deckhouse/bin

# Create symlinks for power commands.
cd /usr/local/sbin
ln -f -s /opt/deckhouse/bin/"${WRAPPER}" reboot
ln -f -s /opt/deckhouse/bin/"${WRAPPER}" poweroff
ln -f -s /opt/deckhouse/bin/"${WRAPPER}" shutdown
ln -f -s /opt/deckhouse/bin/"${WRAPPER}" halt
