#!/bin/bash

source /antiopa/shell_lib.sh

function __main__() {
  module::disable_if_cluster_is_not_bootstraped

  cluster_version=$(values::get global.discovery.clusterVersion)
  if [ "$(semver compare $cluster_version 1.14.0)" -ne "-1" ] ; then
    echo "true" > $MODULE_ENABLED_RESULT
  else
    echo "false" > $MODULE_ENABLED_RESULT
  fi
}

hook::run $@
