#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p beforeHelm=0
}

### Миграция 2018-04-27: https://github.com/deckhouse/deckhouse/merge_requests/307
function __main__() {
  for resource in ns/antiopa secret/registrysecret secret/antiopa-secret deployment/antiopa serviceaccount/antiopa clusterrolebinding/antiopa configmap/antiopa ; do
    kubectl::apply_jq antiopa $resource '.metadata.labels.heritage = "antiopa"'
  done

  for resource in role/antiopa rolebinding/antiopa ; do
    if kubectl -n antiopa get $resource > /dev/null 2> /dev/null ; then
      kubectl -n antiopa delete $resource
    fi
  done
}

hook::run $@
