#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p beforeHelm=10
}

function __main__() {
  # Никто не защищен от ошибки, и чтобы максимально обезопасить себя — ставим
  # жесткий лимит на память и CPU.
  # Важно! Изменять необходимо синхронно и здесь и в инсталляторе!
  kubectl::apply_jq antiopa deploy/antiopa '.spec.template.spec.containers[0].resources.limits = {"cpu":"420m","memory":"500Mi"}'
}

hook::run $@
