#!/bin/bash -e

if [[ "$1" == "--config" ]]; then
    echo "
{
    \"afterDeleteHelm\": 1
}
"
else
    cat << 'EOF' > "$DYNAMIC_VALUES_JSON_MERGE_PATH"
{
    "module": {
        "afterDeleteHelm": "value"
    }
}
EOF
fi
