#!/bin/bash -e

if [[ "$1" == "--config" ]]; then
    echo "
{
    \"afterDeleteHelm\": 1
}
"
else
    cat << 'EOF' > "$VALUES_JSON_PATCH_PATH"
[
    { "op": "add", "path": "/module/afterDeleteHelm", "value": "value" }
]
EOF
fi
