#!/bin/bash

### Миграция 2019-09-26: https://github.com/deckhouse/deckhouse/merge_requests/1194
###
### Этот хук можно удалить, после выката данного MR'а на все инсталяции.

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  jo -p onStartup=0
}

function __main__() {
  if [[ "${ADDON_OPERATOR_NAMESPACE}" == "d8-system" ]] ; then
    for i in $(seq 1 120); do
      if ! kubectl -n antiopa get deployments.apps antiopa >/dev/null 2>/dev/null ; then
        return 0
      fi

      echo "Waiting for the old antiopa deployment to be deleted"
      sleep 1
    done

    if [[ $i -ge 120 ]] ; then
      >&2 echo "Error: Timeout occurred while waiting for the old antiopa deployment to be deleted"
      return 1
    fi
  fi
}

hook::run "$@"
