ARG DISTRO
FROM $DISTRO
RUN apt-get update &&\
    apt-get install -y --no-install-recommends apt-utils bash binutils binutils-aarch64-linux-gnu binutils-x86-64-linux-gnu build-essential bzip2 ca-certificates clang coreutils curl g++-aarch64-linux-gnu g++-x86-64-linux-gnu gcc gcc-aarch64-linux-gnu gcc-x86-64-linux-gnu git gnupg jq libbtrfs-dev libc6-dev libc6-dev-amd64-cross libc6-dev-arm64-cross libcap2-bin libelf-dev libseccomp-dev make musl musl-tools openssh-client openssl patch pkg-config unzip zlib1g-dev && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/trusted.gpg.d/nodesource.gpg &&\
    export NODE_MAJOR=20 &&\
    echo "deb [signed-by=/etc/apt/trusted.gpg.d/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list &&\
    apt-get update && apt-get install nodejs -y &&\
    npm update -g npm &&\
    npm install webpack -g &&\
    npm config set registry http://registry.npmjs.org/ &&\
    apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg &&\
    echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list &&\
    apt-get update && apt-get install -y yarn
