#!/bin/bash

# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 20
EOF
}

function __main__() {
  storage_classes='[
    {
      "name": "managed-standard-ssd",
      "type": "StandardSSD_LRS",
      "cachingMode": "None"
    },
    {
      "name": "managed-standard",
      "type": "Standard_LRS"
    },
    {
      "name": "managed-premium",
      "type": "Premium_LRS"
    },
    {
      "name": "managed-standard-ssd-huge",
      "type": "StandardSSD_LRS",
      "cachingMode": "None"
    },
    {
      "name": "managed-standard-huge",
      "type": "Standard_LRS",
      "cachingMode": "None"
    },
    {
      "name": "managed-premium-huge",
      "type": "Premium_LRS",
      "cachingMode": "None"
    }
  ]'

  if values::has cloudProviderAzure.storageClass.exclude; then
    storage_classes="$(jq --arg exclude "$(values::get cloudProviderAzure.storageClass.exclude | jq -r 'join("|")')" '
      map(select(.name | test("^(\($exclude))$") | not))
      ' <<< "$storage_classes")"
  fi

  if values::has cloudProviderAzure.storageClass.provision; then
    storage_classes="$(jq --argjson provision "$(values::get cloudProviderAzure.storageClass.provision)" '
      . + [$provision[]| .type |= (. // "UltraSSD_LRS")]
      ' <<< "$storage_classes")"
  fi

  values::set cloudProviderAzure.internal.storageClasses "$storage_classes"

  if values::has cloudProviderAzure.storageClass.default; then
    values::set cloudProviderAzure.internal.defaultStorageClass "$(values::get cloudProviderAzure.storageClass.default)"
  else
    values::unset cloudProviderAzure.internal.defaultStorageClass
  fi
}

hook::run "$@"
