{
 "title": "Ovpn-Admin",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Server cert valid time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ovpn_server_cert_expire{d8_source=\"dkp\"}"
    }
   ]
  },
  {
   "title": "Server CA cert valid time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ovpn_server_ca_cert_expire{d8_source=\"dkp\"}"
    }
   ]
  },
  {
   "title": "Total clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ovpn_clients_total{d8_source=\"dkp\"}"
    }
   ]
  },
  {
   "title": "Connected clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ovpn_clients_connected{d8_source=\"dkp\"}"
    }
   ]
  },
  {
   "title": "Revoked clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ovpn_clients_expired{d8_source=\"dkp\"}"
    }
   ]
  },
  {
   "title": "Expired clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ovpn_clients_expired{d8_source=\"dkp\"}"
    }
   ]
  },
  {
   "title": "Client bytes received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ovpn_client_bytes_received{d8_source=\"dkp\"}",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "Client bytes sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ovpn_client_bytes_sent{d8_source=\"dkp\"}",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "Clients bytes received rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ovpn_client_bytes_received{d8_source=\"dkp\"}[1m])",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "Client bytes sent rate ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ovpn_client_bytes_sent{d8_source=\"dkp\"}[1m])",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "Connection info",
   "type": "stat",
   "description": "value show last connection check time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ovpn_client_connection_info{d8_source=\"dkp\"} * 1000",
     "legendFormat": "{{ client }}-{{ip}}"
    }
   ]
  },
  {
   "title": "Connection from",
   "type": "stat",
   "description": "value shows when connection was started",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ovpn_client_connection_from{d8_source=\"dkp\"} * 1000",
     "legendFormat": "{{ client }}-{{ip}}"
    }
   ]
  },
  {
   "title": "Client cert valid days",
   "type": "stat",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ovpn_client_cert_expire{d8_source=\"dkp\"} ",
     "legendFormat": "{{ client }}"
    }
   ]
  }
 ]
}