#!/usr/bin/env bash

# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /shell_lib.sh

function __config__(){
  cat <<EOF
configVersion: v1
kubernetesValidating:
- name: d8-secret-encryption-key-secret.deckhouse.io
  group: main
  labelSelector:
    matchLabels:
      name: d8-secret-encryption-key
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["*"]
    resources:   ["secrets"]
    scope:       "Namespaced"
EOF
}

function __main__() {
  # Secret kube-system/d8-secret-encryption-key cannot be deleted
  if context::jq -e -r '.review.request.operation != "CREATE"' >/dev/null 2>&1; then
    cat <<EOF > "$VALIDATING_RESPONSE_PATH"
{"allowed":false, "message":"it is forbidden to modify secret d8-secret-encryption-key"}
EOF

    return 0
  fi

    cat <<EOF > "$VALIDATING_RESPONSE_PATH"
{"allowed":true}
EOF

  return 0
}

hook::run "$@"
