#!/bin/bash

### Миграция 2019-09-09: https://github.com/deckhouse/deckhouse/merge_requests/1114
# Данный хук можно удалить после выката релиза с данным хуком

source /antiopa/shell_lib.sh

function __config__() {
  echo '
{
  "beforeHelm": 5
}'
}

function __main__() {
  if kubectl -n kube-prometheus get configmap ping-exporter-config 2>/dev/null >/dev/null ; then
    kubectl -n kube-prometheus delete configmap ping-exporter-config
  fi

  if kubectl -n kube-prometheus get vpa ping-exporter 2>/dev/null >/dev/null ; then
    kubectl -n kube-prometheus delete vpa ping-exporter
  fi

  if kubectl -n kube-prometheus get ds ping-exporter 2>/dev/null >/dev/null ; then
    kubectl -n kube-prometheus delete ds ping-exporter
  fi

  if kubectl -n kube-prometheus get sa ping-exporter 2>/dev/null >/dev/null ; then
    kubectl -n kube-prometheus delete sa ping-exporter
  fi
}

hook::run "$@"
