#!/bin/bash

source /antiopa/shell_lib.sh

function __config__() {
  jo -p beforeHelm=20 onKubernetesEvent="$(jo -a \
    "$(jo kind=node jqFilter=".status.addresses" disableDebug=true)" \
  )"
}

function __main__() {
  targets=$(kubectl get no -o json | jq -c '{cluster_targets: (.items | map ({name: (.status.addresses | map (select(.type=="Hostname").address) | first), ipAddress: (.status.addresses | map (select(.type=="InternalIP").address) | first) }) | sort)}')

  external_targets=$(values::get --config pingExporter.externalTargets | jq '{external_targets: .}')
  if [ -n "$external_targets" ]; then
    targets=$(jq -n --argjson cluster_targets "$targets" --argjson external_targets "$external_targets" '$cluster_targets + $external_targets')
  fi
  values::set pingExporter.targets "$targets"
}

hook::run $@
