{{- define "azure_cdd_pod_annotations" -}}
checksum/config: {{ include (print $.Template.BasePath "/cloud-data-discoverer/secret.yaml") . | sha256sum }}
{{- end -}}

{{- define "azure_cdd_envs" -}}
- name: AZURE_LOCATION
  valueFrom:
    secretKeyRef:
      key: location
      name: cloud-data-discoverer
- name: AZURE_SUBSCRIPTION_ID
  valueFrom:
    secretKeyRef:
      key: subscriptionID
      name: cloud-data-discoverer
- name: AZURE_CLIENT_ID
  valueFrom:
    secretKeyRef:
      key: clientID
      name: cloud-data-discoverer
- name: AZURE_TENANT_ID
  valueFrom:
    secretKeyRef:
      key: tenantID
      name: cloud-data-discoverer
- name: AZURE_CLIENT_SECRET
  valueFrom:
    secretKeyRef:
      key: clientSecret
      name: cloud-data-discoverer
{{- end -}}

{{- define "azure_cdd_volume_mounts" -}}
- mountPath: /etc/config
  name: config
  readOnly: true
{{- end -}}

{{- define "azure_cdd_volumes" -}}
- name: config
  secret:
    secretName: cloud-data-discoverer
{{- end -}}

{{- $cddConfig := dict -}}
{{- $_ := set $cddConfig "fullname" "cloud-data-discoverer" -}}
{{- $_ := set $cddConfig "image" (include "helm_lib_module_image" (list . "cloudDataDiscoverer")) -}}
{{- $_ := set $cddConfig "additionalEnv" (include "azure_cdd_envs" . | fromYamlArray) -}}
{{- $_ := set $cddConfig "additionalPodAnnotations" (include "azure_cdd_pod_annotations" . | fromYaml) -}}
{{- $_ := set $cddConfig "additionalVolumeMounts" (include "azure_cdd_volume_mounts" . | fromYamlArray) -}}
{{- $_ := set $cddConfig "additionalVolumes" (include "azure_cdd_volumes" . | fromYamlArray) -}}
{{- $_ := set $cddConfig "vpaEnabled" true -}}

{{- include "helm_lib_cloud_data_discoverer_manifests" (list . $cddConfig) }}
