#!/bin/bash

# Copyright 2021 Flant JSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE


source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 15
EOF
}

function __main__() {
  if ! values::has openvpn.auth.externalAuthentication ; then
    if ! values::has openvpn.auth.password ; then
      if ! values::has --config openvpn.auth ; then
        values::set --config openvpn.auth {}
      fi
      values::set --config openvpn.auth.password $(tools::generate_password)
    fi
  else
    values::unset --config openvpn.auth.password
    if [[ $(values::get --config openvpn.auth) == '{}' ]]; then
      values::unset --config openvpn.auth {}
    fi
  fi
}

hook::run $@
