#!/bin/bash

# Copyright 2021 Flant JSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE


source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 10
EOF
}

function __main__() {
  cluster_domain="$(values::get global.discovery.clusterDomain)"

  if ! values::has 'openvpn.pushToClientSearchDomains' ; then
    values::set --config openvpn.pushToClientSearchDomains "[\"$cluster_domain\"]"
  fi
}

hook::run $@
