#!/bin/bash

# Copyright 2021 Flant JSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE


source /deckhouse/shell_lib.sh

function __config__() {
  common_hooks::storage_class_change::config "d8-openvpn" "app=openvpn"
}


function __on_group::pvc_modified() {
  common_hooks::storage_class_change::pvc_modified "d8-openvpn"
}

function __on_group::pvc_deleted() {
  common_hooks::storage_class_change::pvc_deleted "d8-openvpn"
}

function __main__() {
  common_hooks::storage_class_change::main "d8-openvpn" "statefulset" "openvpn"
}

hook::run $@
