#!/bin/bash

### Миграция 2019-09-26: https://github.com/deckhouse/deckhouse/merge_requests/1194
###
### Этот хук можно удалить, после выката данного MR'а на все инсталяции.

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  jo -p onStartup=1
}

function __main__() {
  if [[ "${ADDON_OPERATOR_NAMESPACE}" == "antiopa" ]] ; then
    if ! kubectl -n d8-system get deployments.apps deckhouse >/dev/null 2>/dev/null ; then
      if kubectl -n antiopa get deployments.apps antiopa >/dev/null 2>/dev/null ; then
        deckhouse_image=$(kubectl -n antiopa  get deployments.apps antiopa -o json | jq '.spec.template.spec.containers[0].image' -r)
        log_level=$(kubectl -n antiopa  get deployments.apps antiopa -o json | jq '.spec.template.spec.containers[0].env[] | select(.name == "RLOG_LOG_LEVEL") | .value')
        DEPLOYMENT=$(cat <<- YAML
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deckhouse
  labels:
    heritage: deckhouse
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: deckhouse
  template:
    metadata:
      labels:
        app: deckhouse
    spec:
      containers:
      - name: deckhouse
        image: ${deckhouse_image}
        imagePullPolicy: Always
        command: ["/deckhouse/deckhouse"]
        resources:
          requests:
            cpu: 50m
            memory: 512Mi
        workingDir: /deckhouse
        ports:
        - containerPort: 9650
        env:
        - name: KUBERNETES_DEPLOYED
          value: "$(date --rfc-3339=seconds)"
        - name: RLOG_LOG_LEVEL
          value: ${log_level}
        - name: ADDON_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ADDON_OPERATOR_CONFIG_MAP
          value: "deckhouse"
        - name: ADDON_OPERATOR_PROMETHEUS_METRICS_PREFIX
          value: "deckhouse_"
        - name: ADDON_OPERATOR_LISTEN_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DECKHOUSE_POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: HELM_HOST
          value: "127.0.0.1:44434"
        volumeMounts:
        - name: registrysecret
          mountPath: "/etc/registrysecret"
          readOnly: true
      serviceAccountName: deckhouse
      tolerations:
      - operator: Exists
      imagePullSecrets:
      - name: deckhouse-registry
      nodeSelector:
        node-role.kubernetes.io/master: ""
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      volumes:
      - name: registrysecret
        secret:
          secretName: deckhouse-registry
YAML
)

        RBAC=$(cat <<- YAML
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deckhouse
  namespace: d8-system
  labels:
    heritage: deckhouse
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: deckhouse
  labels:
    heritage: deckhouse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: deckhouse
    namespace: d8-system
YAML
)
        echo "$RBAC" | kubectl -n d8-system create -f -
        echo "$DEPLOYMENT" | kubectl -n d8-system create -f -
        kubectl -n antiopa delete deployments.apps antiopa
      fi
    fi
  fi
}

hook::run "$@"
