#!/bin/bash

### Миграция 2019-09-26: https://github.com/deckhouse/deckhouse/merge_requests/1194
###
### Этот хук можно удалить, после выката данного MR'а на все инсталяции.

source /deckhouse/shell_lib.sh

function __config__() {
  jo -p onStartup=0
}

function __main__() {
  if [[ "${ADDON_OPERATOR_NAMESPACE}" == "antiopa" ]] ; then
    for configmap in $(kubectl -n antiopa  get cm -l OWNER=TILLER --no-headers -o custom-columns=":metadata.name"); do
      kubectl -n antiopa get configmap $configmap -o json | \
      jq -r "include \"remove_empty\"; .metadata.namespace=\"d8-system\" | remove_empty |
            .metadata |= with_entries(select([.key] | inside([\"name\", \"namespace\", \"labels\"])))" \
      | kubectl::replace_or_create
    done
    # Hack for remove namespace object from helm release
    kubectl -n d8-system delete configmap -l NAME=deckhouse,OWNER=TILLER >/dev/null 2>/dev/null
    if kubectl -n d8-system get podmonitor deckhouse >/dev/null 2>/dev/null ; then
      kubectl -n d8-system delete podmonitor deckhouse >/dev/null 2>/dev/null
    fi
    if kubectl -n d8-system get vpa deckhouse >/dev/null 2>/dev/null ; then
      kubectl -n d8-system delete vpa deckhouse >/dev/null 2>/dev/null
    fi
    if kubectl -n kube-system get secret deckhouse-registry >/dev/null 2>/dev/null ; then
      kubectl -n kube-system delete secret deckhouse-registry >/dev/null 2>/dev/null
    fi
  fi
}

hook::run "$@"
