#!/bin/bash

### Миграция 2019-09-26: https://github.com/deckhouse/deckhouse/merge_requests/1194
###
### Этот хук можно удалить, после выката данного MR'а на все инсталяции.

source /deckhouse/shell_lib_legacy.sh

function __config__() {
  jo -p afterHelm=0
}

function __main__() {
  if ! kubectl -n d8-system get secret deckhouse-registry >/dev/null 2>/dev/null ; then
    kubectl -n d8-system get secret deckhouse-registry-tmp -o json | \
      jq -r "include \"remove_empty\"; .metadata.namespace=\"d8-system\" | .metadata.name=\"deckhouse-registry\" | remove_empty |
          .metadata |= with_entries(select([.key] | inside([\"name\", \"namespace\", \"labels\"])))" \
      | kubectl::replace_or_create
  fi
  if kubectl -n d8-system get secret deckhouse-registry-tmp >/dev/null 2>/dev/null ; then
    kubectl -n d8-system delete secret deckhouse-registry-tmp >/dev/null 2>/dev/null
  fi
}

hook::run "$@"
