#!/bin/bash

### Миграция 2019-09-26: https://github.com/deckhouse/deckhouse/merge_requests/1194
###
### Этот хук можно удалить, после выката данного MR'а на все инсталяции.

source /deckhouse/shell_lib.sh

function __config__() {
  jo -p onStartup=3
}

function __main__() {
  if [[ "${ADDON_OPERATOR_NAMESPACE}" == "d8-system" ]] ; then
    if kubectl get clusterrolebinding antiopa >/dev/null 2>/dev/null ; then
      kubectl delete clusterrolebinding antiopa
    fi
    if kubectl -n antiopa get serviceaccount antiopa >/dev/null 2>/dev/null ; then
      kubectl -n antiopa delete serviceaccount antiopa
    fi
  fi
}

hook::run "$@"
