- name: coreos.node
  rules:
  - alert: NodeExporterDown
    expr: absent(up{job="node-exporter"} == 1)
    for: 10m
    labels:
      severity_level: "3"
    annotations:
      plk_protocol_version: "1"
      summary: Prometheus couldn't scrape a `node-exporter`.
      description: Prometheus has been unable to scrape a `node-exporter` for more than 10 minutes,
        or `node-exporters` have disappeared from service discovery.
