#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  common_hooks::https::apply_crds::config
}

function __main__() {
  common_hooks::https::apply_crds::main $(module::path)/crds/*
}

hook::run "$@"
