#!/bin/bash

# Copyright 2021 Flant CJSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 1
    schedule:
    - crontab: "*/10 * * * *"
EOF
}

function __main__() {
  enabled=0
  if values::array_has global.enabledModules "nginx-ingress" ; then
    enabled=1
  fi

  jq -rc '{"name":"d8_nginx_ingress_deprecated", "set": .}' <<< "${enabled}" >> $METRICS_PATH
}

hook::run $@
