#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    kubernetes:
    - name: controller
      apiVersion: deckhouse.io/v1alpha1
      kind: IngressNginxController
      includeSnapshotsFrom:
      - controller
      jqFilter: |
        .spec.config //= {}
        | .spec.loadBalancer //= {}
        | {"name": .metadata.name, "spec": .spec}
EOF
}

function __main__() {
  if [[ $(context::jq -rc '.snapshots.controller | length') == "0" ]]; then
    values::set ingressNginx.internal.ingressControllerCRDs '[]'
    return 0
  fi

  default_controller_version=$(values::get ingressNginx.defaultControllerVersion)
  crds=$(context::jq -rc --arg default_controller_version "$default_controller_version" '
    [ .snapshots.controller[] | .filterResult | .spec.controllerVersion //= $default_controller_version ]')

  values::set ingressNginx.internal.ingressControllerCRDs "$crds"
}

hook::run "$@"
