#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  legacy::common_hooks::certificates::order_certificate::config
}

function __main__() {
  for name in $(values::get ingressNginx.internal.ingressControllers | jq -r '.[].name') ; do
    legacy::common_hooks::certificates::order_certificate::main "d8-ingress-nginx" "${name}-ingress-nginx-auth-tls" "nginx-ingress:${name}" "internal.nginxAuthTLS${name}" "ingress-nginx:auth"
  done
}

hook::run "$@"
