#!/bin/bash

# Copyright 2021 Flant CJSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


source /deckhouse/shell_lib.sh

function __config__() {
  legacy::common_hooks::certificates::order_certificate::config
}

function __main__() {
  for name in $(values::get ingressNginx.internal.ingressControllers | jq -r '.[].name') ; do
    legacy::common_hooks::certificates::order_certificate::main "d8-ingress-nginx" "ingress-nginx-${name}-auth-tls" "nginx-ingress:${name}" "internal.nginxAuthTLS${name}" "ingress-nginx:auth"
  done
}

hook::run "$@"
