{
 "title": "Secrets strore webhook",
 "description": "Secrets store webhook dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "mutating_wh", "label": "Webhook", "query": "vault-secrets-pods" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kubewebhook_mutating_webhook_review_duration_seconds_sum,resource_namespace)"
    }
   },
   { "name": "range", "query": "1m" }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum(kubewebhook_mutating_webhook_review_duration_seconds_count{webhook_id=\"${mutating_wh}\",resource_namespace=~\"$namespace\"}) by (webhook_id)) OR on() vector(0)",
     "legendFormat": "Mutating WH"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  sum(increase(kubewebhook_mutating_webhook_review_duration_seconds_count{webhook_id=\"${mutating_wh}\",mutated=\"true\",resource_namespace=~\"$namespace\"}[${range}]))\n) OR on() vector(0)",
     "legendFormat": "Mutated"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  sum(increase(kubewebhook_mutating_webhook_review_duration_seconds_count{webhook_id=\"${mutating_wh}\",mutated=\"false\",resource_namespace=~\"$namespace\"}[24h]))\n) OR on() vector(0)",
     "legendFormat": "Not mutated"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rev/s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"kubewebhook_(mutating|validating)_webhook_review_duration_seconds_count\",webhook_id=\"${mutating_wh}\",resource_namespace=~\"$namespace\"}[${interval}]))\nOR on() vector(0)",
     "legendFormat": "Rev rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate({__name__=~\"kubewebhook_(mutating|validating)_webhook_review_duration_seconds_count\",success=\"false\",webhook_id=\"${mutating_wh}\",resource_namespace=~\"$namespace\"}[${interval}]))\n  /\n  sum(rate({__name__=~\"kubewebhook_(mutating|validating)_webhook_review_duration_seconds_count\",webhook_id=\"${mutating_wh}\",resource_namespace=~\"$namespace\"}[${interval}]))\n\n) OR on() vector (0)",
     "legendFormat": "Rev errors"
    }
   ]
  },
  {
   "title": "Webhook reviews rate",
   "type": "graph",
   "description": "The webhook reviews processing rate (left Y-axis) and its % rate errors (right Y-axis)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "rev/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubewebhook_mutating_webhook_review_duration_seconds_count{webhook_id=\"${mutating_wh}\",resource_namespace=~\"$namespace\"}[${interval}])) by (mutated)",
     "legendFormat": "mutated: {{mutated}}"
    },
    {
     "expr": "(\n  sum(rate(kubewebhook_mutating_webhook_review_duration_seconds_count{webhook_id=\"${mutating_wh}\", success=\"false\",resource_namespace=~\"$namespace\"}[${interval}]))\n  OR on() vector(0)\n)\n/\n(\n  sum(rate(kubewebhook_mutating_webhook_review_duration_seconds_count{webhook_id=\"${mutating_wh}\",resource_namespace=~\"$namespace\"}[${interval}]))\n  OR on() vector(0)\n)",
     "legendFormat": "error %"
    }
   ]
  },
  {
   "title": "Webhook reviews latency",
   "type": "graph",
   "description": "The latency of different percentiles for webhook reviews",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum(rate(kubewebhook_mutating_webhook_review_duration_seconds_bucket{webhook_id=\"${mutating_wh}\",resource_namespace=~\"$namespace\"}[${interval}])) by (le)\n)",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90,\n  sum(rate(kubewebhook_mutating_webhook_review_duration_seconds_bucket{webhook_id=\"${mutating_wh}\",resource_namespace=~\"$namespace\"}[${interval}])) by (le)\n)",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50,\n  sum(rate(kubewebhook_mutating_webhook_review_duration_seconds_bucket{webhook_id=\"${mutating_wh}\",resource_namespace=~\"$namespace\"}[${interval}])) by (le)\n)",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Webhook review rate by operation",
   "type": "graph",
   "description": "The webhooks reviews processing rate by operation",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "rev/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"kubewebhook_(mutating|validating)_webhook_review_duration_seconds_count\",webhook_id=\"${mutating_wh}\",resource_namespace=~\"$namespace\"}[${interval}])) by (operation)\n",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Webhook review rate by version",
   "type": "graph",
   "description": "The webhooks reviews processing rate by version",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "rev/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"kubewebhook_(mutating|validating)_webhook_review_duration_seconds_count\",webhook_id=\"${mutating_wh}\",resource_namespace=~\"$namespace\"}[${interval}])) by (webhook_version)\n",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Webhook % of errors rate",
   "type": "table",
   "description": "The % of review errors per webhook",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  sum(rate({__name__=~\"kubewebhook_(mutating|validating)_webhook_review_duration_seconds_count\", success=\"false\",webhook_id=\"${mutating_wh}\",resource_namespace=~\"$namespace\"}[5m])) by (webhook_version, webhook_id)\n  /\n  sum(rate({__name__=~\"kubewebhook_(mutating|validating)_webhook_review_duration_seconds_count\",webhook_id=\"${mutating_wh}\",resource_namespace=~\"$namespace\"}[5m])) by (webhook_version, webhook_id)\n) > 0"
    }
   ]
  },
  {
   "title": "Webhook review rate by resource",
   "type": "graph",
   "description": "The webhooks reviews processing rate by resource",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 24 },
   "yaxes": [
    { "format": "rev/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"kubewebhook_(mutating|validating)_webhook_review_duration_seconds_count\",webhook_id=\"${mutating_wh}\",resource_namespace=~\"$namespace\"}[${interval}])) by (resource_kind)",
     "legendFormat": "{{resource_kind}}"
    }
   ]
  }
 ]
}