#!/bin/bash

source /deckhouse/shell_lib_legacy.sh

function __main__() {
  enabled::disable_module_in_kubernetes_versions_less_than 1.15.0

  if values::get global.enabledModules | jq '.[]' -r | grep -E '^cloud-provider-[a-z-]+$' > /dev/null && kubectl -n kube-system get secret d8-cloud-instance-manager-cloud-provider >/dev/null 2>&1; then
    echo "true" > "$MODULE_ENABLED_RESULT"
  else
    echo "false" > "$MODULE_ENABLED_RESULT"
  fi
}

hook::run "$@"
