#!/bin/bash

source /deckhouse/shell_lib.sh

function __config__() {
  jo -p afterHelm=10
}

function __main__() {
  for i in $(seq 1 120); do
    if kubectl -n d8-cert-manager get pod -l app=webhook -o json  | jq -e '.items[].status.conditions | select(.) | all(.[] ; .status == "True")' > /dev/nul ; then
      return 0
    fi

    master_nodes=$(kubectl get node -l node-role.kubernetes.io/master="" -o json)

    all_initialized=$(echo "$master_nodes" | jq '[.items[].spec.taints | [(.[] | select(.key == "node.cloudprovider.kubernetes.io/uninitialized"))] | length == 0] | all')
    all_ready=$(echo "$master_nodes" | jq '[.items[].status.conditions | [(.[] | select(.type == "Ready"))] | all(.[] ; .status == "True")] | all')

    if [[ "x$all_initialized" == "xfalse" && "x$all_ready" == "xfalse" ]] ; then
      echo "Waiting for master nodes to become initialized by cloud provider and to become ready"
    elif [[ "x$all_initialized" == "xfalse" ]] ; then
      echo "Waiting for master nodes to become initialized by cloud provider"
    elif [[ "x$all_ready" == "xfalse" ]] ; then
      echo "Waiting for master nodes to become ready"
    else
      return 0
    fi

    sleep 1
  done
  if [[ $i -ge 120 ]] ; then
    >&2 echo "Timeout waiting for master nodes"
    return 1
  fi
}

hook::run $@
