linters-settings:
  module:
    oss:
      disable: true
  container:
    exclude-rules:
      host-network-ports:
        - kind: DaemonSet
          name: user-authz-webhook
          container: webhook
      readiness-probe:
        - kind: DaemonSet
          name: user-authz-webhook
          container: webhook
  rbac:
    exclude-rules:
      placement:
        - kind: ClusterRole
          name: user-authz:user:custom
        - kind: ClusterRole
          name: user-authz:privileged-user:custom
        - kind: ClusterRole
          name: user-authz:editor:custom
        - kind: ClusterRole
          name: user-authz:admin:custom
        - kind: ClusterRole
          name: user-authz:cluster-editor:custom
        - kind: ClusterRole
          name: user-authz:cluster-admin:custom
        - kind: ClusterRole
          name: user-authz:cluster-editor
        - kind: ClusterRole
          name: user-authz:admin
        - kind: ClusterRole
          name: user-authz:super-admin
        - kind: ClusterRole
          name: user-authz:privileged-user
        - kind: ClusterRole
          name: user-authz:user
        - kind: ClusterRole
          name: user-authz:cluster-admin
        - kind: ClusterRole
          name: user-authz:scale
        - kind: ClusterRole
          name: user-authz:port-forward
        - kind: ClusterRole
          name: user-authz:editor
