#!/bin/bash

# Copyright 2021 Flant JSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE


source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 10
EOF
}

function __main__() {
  if ! values::has networkGateway.nodeSelector; then
    >&2 echo "ERROR: networkGateway.nodeSelector is mandatory."
    return 1
  fi

  if ! values::has networkGateway.subnet; then
    >&2 echo "ERROR: networkGateway.subnet is mandatory."
    return 1
  fi

  subnet=$(values::get networkGateway.subnet)
  if ! echo "${subnet}" | grep -q -E '^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$'; then
    >&2 echo "ERROR: networkGateway.subnet format is 'IP/Prefix'."
    return 1
  fi

  if ! values::has networkGateway.publicAddress; then
    >&2 echo "ERROR: networkGateway.publicAddress is mandatory."
    return 1
  fi
}

hook::run $@
