apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:subsystem:observability:superadmin
  annotations:
    en.meta.deckhouse.io/title: "Observability: Superadmin"
    ru.meta.deckhouse.io/title: "Суперадминистратор подсистемы наблюдаемости"
    en.meta.deckhouse.io/description: "Full control over the Observability subsystem, including its system resources."
    ru.meta.deckhouse.io/description: "Полный контроль над подсистемы наблюдаемости, включая её системные ресурсы."
  labels:
    heritage: deckhouse
    module: user-authz
    rbac.deckhouse.io/use-role: superadmin
    rbac.deckhouse.io/kind: role
    rbac.deckhouse.io/scope: subsystem
    rbac.deckhouse.io/subsystem: observability
    rbac.deckhouse.io/aggregate-to-system-as: superadmin
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.deckhouse.io/aggregate-to-observability-as: superadmin
rules: []
