#!/usr/bin/env bash

# Copyright 2024 Flant JSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE

source /shell_lib.sh

function __config__(){
  cat <<EOF
configVersion: v1
kubernetesValidating:
- name: multipledefaultmlbchandler-policy.deckhouse.io
  group: main
  includeSnapshotsFrom: ["mlbc_default"]
  rules:
  - apiGroups:   ["network.deckhouse.io"]
    apiVersions: ["v1alpha1"]
    operations:  ["CREATE", "UPDATE"]
    resources:   ["metalloadbalancerclasses"]
    scope:       "Cluster"
kubernetes:
- name: mlbc_default
  group: main
  executeHookOnEvent: []
  executeHookOnSynchronization: false
  keepFullObjectsInMemory: false
  apiVersion: network.deckhouse.io/v1alpha1
  kind: MetalLoadBalancerClass
  jqFilter: |
    {
      "isDefault": .spec.isDefault,
      "name": .metadata.name,
    }
EOF
}

function forbid() {
  jq -nc --arg message "$1" '
    {
      "allowed": false,
      "message": $message
    }
    ' > "$VALIDATING_RESPONSE_PATH"
}

function __main__() {
  echo "HOOK-TEST"
  context::jq . > /tmp/multiple-default-mlbc-handler.json # TODO: delete line
  exit 0

}

hook::run "$@"
