apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    heritage: deckhouse
    module: user-authz
    rbac.deckhouse.io/aggregate-to-namespace-as: viewer
    rbac.deckhouse.io/kind: capability
    rbac.deckhouse.io/capability: "namespace-capability.user-authz.view"
    rbac.deckhouse.io/scope: namespace
  name: d8:namespace-capability:user-authz:view
  annotations:
    en.meta.deckhouse.io/title: "Module user-authz: view"
    ru.meta.deckhouse.io/title: "Модуль user-authz: просмотр"
    en.meta.deckhouse.io/description: "Read-only access to user-authz resources in a namespace."
    ru.meta.deckhouse.io/description: "Доступ только на чтение к ресурсам модуля user-authz в пространстве имён."
rules:
- apiGroups:
  - deckhouse.io
  resources:
  - authorizationrules
  verbs:
  - get
  - list
  - watch
