spec:
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: |
            Представляет информацию о доступном пакете приложения.
          properties:
            apiVersion:
              description: |-
                Определяет версионированную схему этого представления объекта. Серверы должны преобразовывать распознанные схемы в последнее внутреннее значение и могут отклонять нераспознанные значения.

                Больше информации [в документации](https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources).
            kind:
              description: |-
                Значение, представляющее REST-ресурс, который описывает данный объект. Серверы могут определить его из конечной точки, к которой клиент отправляет запросы. Не может быть изменено. Используется в CamelCase.

                Больше информации [в документации](https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds).
            status:
              description: |
                Статус пакета приложения.
              properties:
                availableRepositories:
                  description: |
                    Список названий репозиториев, где доступен этот пакет приложения.
                usedBy:
                  description: |
                    Информация о приложениях, использующих этот пакет.
                  items:
                    properties:
                      name:
                        description: |
                          Название экземпляра приложения.
                      namespace:
                        description: |
                          Пространство имён, в котором установлено приложение.
                      version:
                        description: |
                          Версия пакета, используемая этим приложением.
                usedByCount:
                  description: |
                    Количество приложений, использующих этот пакет.
