#!/bin/bash
# Copyright 2022 Flant JSC
# Licensed under the Deckhouse Platform Enterprise Edition (EE) license. See https://github.com/deckhouse/deckhouse/blob/main/ee/LICENSE.

set -Eeo pipefail
dpkg -i -E cri-tools_amd64.deb kubeadm_amd64.deb
apt-mark hold kubeadm cri-tools
