/*
Copyright 2021 Flant JSC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package hooks

import (
	"context"
	"encoding/base64"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/Masterminds/semver/v3"
	"github.com/flant/addon-operator/pkg/module_manager/go_hook"
	"github.com/flant/addon-operator/sdk"
	"github.com/flant/shell-operator/pkg/kube_events_manager/types"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"sigs.k8s.io/yaml"

	sdkobjectpatch "github.com/deckhouse/module-sdk/pkg/object-patch"

	"github.com/deckhouse/deckhouse/go_lib/dependency"
	"github.com/deckhouse/deckhouse/go_lib/dependency/requirements"
)

/*
Description:
	Hook generates 4 kinds of snapshots:
		- control-plane pods with annotation "control-plane-manager.deckhouse.io/kubernetes-version" from kube-system NS
		- all Nodes (filtering .status.nodeInfo.kubeletVersion)
		- Secret: d8-cluster-configuration from NS: kube-system - deckhouseDefaultKubernetesVersion,
		  plus maxUsedControlPlaneKubernetesVersion as a migration seed
		- ConfigMap: d8-cluster-kubernetes from NS: kube-system - only spec.maxUsedKubernetesVersion
	and get desired k8s version from `global.discovery.targetKubernetesVersion`

	Then process following logic:
	```
	floor = max(values maxUsedKubernetesVersion, ConfigMap maxUsedKubernetesVersion, Secret maxUsedControlPlaneKubernetesVersion)
	if floor is unknown: floor = maxControlPlaneVersion   // no history => the control plane is the maximum

	if global.discovery.targetKubernetesVersion > maxNodeVersion
		if minNodeVersion < minControlPlaneVersion:
			effectiveKubernetesVersion = minControlPlaneVersion
		else:
			effectiveKubernetesVersion =  minControlPlaneVersion.IncMinor() // bumped minor version
	else if global.discovery.targetKubernetesVersion < maxNodeVersion:
		if maxNodeVersion < maxControlPlaneVersion && maxControlPlaneVersion == floor:
			unbumped := fmt.Sprintf("%d.%d.%d", maxControlPlaneVersion.Major(), maxControlPlaneVersion.Minor()-1, maxControlPlaneVersion.Patch())
			effectiveKubernetesVersion = semver.MustParse(unbumped) // minor version-1
		else:
			effectiveKubernetesVersion = maxControlPlaneVersion
	else:
		effectiveKubernetesVersion = global.discovery.targetKubernetesVersion
	```

	then save to Values:
		controlPlaneManager.internal.effectiveKubernetesVersion = effectiveKubernetesVersion
		controlPlaneManager.internal.maxUsedKubernetesVersion    = max(floor, effectiveKubernetesVersion)

	Both reach update-observer as container environment of the control-plane-manager DaemonSet;
	update-observer is the single writer of ConfigMap kube-system/d8-cluster-kubernetes and is what
	makes maxUsedKubernetesVersion durable. This hook no longer writes the Secret key.

     For deckhouse upgrade requirements we are using minimal version of whole cluster.
*/

const minK8sVersionRequirementKey = "controlPlaneManager:minUsedControlPlaneKubernetesVersion"

const maxUsedK8sVersionSecretKey = "maxUsedControlPlaneKubernetesVersion"
const deckhouseDefaultK8sVersionSecretKey = "deckhouseDefaultKubernetesVersion"

const (
	clusterKubernetesConfigMapSnapshot = "cluster_kubernetes_config_map"
	clusterKubernetesConfigMapName     = "d8-cluster-kubernetes"
	clusterKubernetesNamespace         = "kube-system"

	maxUsedK8sVersionValuesKey = "controlPlaneManager.internal.maxUsedKubernetesVersion"
)

// This value is set on the controller build in the deckhouse-controller/go-build.sh script.
// Do not touch it !!!
var DefaultKubernetesVersion = "<autogenerated on the build stage>"

var _ = sdk.RegisterFunc(&go_hook.HookConfig{
	Queue:        moduleQueue,
	OnBeforeHelm: &go_hook.OrderedConfig{Order: 50},
	Kubernetes: []go_hook.KubernetesConfig{
		{
			Name:       "control_plane_versions",
			ApiVersion: "v1",
			Kind:       "Pod",
			FilterFunc: ekvFilterControlPlaneAnnotations,
			LabelSelector: &v1.LabelSelector{
				MatchExpressions: []v1.LabelSelectorRequirement{
					{
						Key:      "component",
						Operator: v1.LabelSelectorOpIn,
						Values:   []string{"kube-apiserver", "kube-controller-manager", "kube-scheduler"},
					},
					{
						Key:      "tier",
						Operator: v1.LabelSelectorOpIn,
						Values:   []string{"control-plane"},
					},
				},
			},
			NamespaceSelector: &types.NamespaceSelector{
				NameSelector: &types.NameSelector{
					MatchNames: []string{"kube-system"},
				},
			},
		},
		{
			Name:       "node_versions",
			ApiVersion: "v1",
			Kind:       "Node",
			FilterFunc: ekvFilterNode,
		},
		{
			Name:       "max_used_control_plane_version",
			ApiVersion: "v1",
			Kind:       "Secret",
			NameSelector: &types.NameSelector{
				MatchNames: []string{"d8-cluster-configuration"},
			},
			NamespaceSelector: &types.NamespaceSelector{
				NameSelector: &types.NameSelector{
					MatchNames: []string{"kube-system"},
				},
			},
			FilterFunc: ekvFilterSecret,
		},
		{
			Name:       clusterKubernetesConfigMapSnapshot,
			ApiVersion: "v1",
			Kind:       "ConfigMap",
			NameSelector: &types.NameSelector{
				MatchNames: []string{clusterKubernetesConfigMapName},
			},
			NamespaceSelector: &types.NamespaceSelector{
				NameSelector: &types.NameSelector{
					MatchNames: []string{clusterKubernetesNamespace},
				},
			},
			FilterFunc: ekvFilterClusterKubernetesConfigMap,
		},
	},
}, dependency.WithExternalDependencies(handleEffectiveK8sVersion))

type controlPlanePod struct {
	Name       string
	K8sVersion string
}

func ekvFilterControlPlaneAnnotations(unstructured *unstructured.Unstructured) (go_hook.FilterResult, error) {
	var pod corev1.Pod
	err := sdk.FromUnstructured(unstructured, &pod)
	if err != nil {
		return nil, err
	}
	annotations := pod.GetAnnotations()

	k8sVersion, ok := annotations["control-plane-manager.deckhouse.io/kubernetes-version"]
	if !ok {
		return nil, nil
	}

	return controlPlanePod{Name: pod.Name, K8sVersion: k8sVersion}, nil
}

func ekvFilterNode(unstructured *unstructured.Unstructured) (go_hook.FilterResult, error) {
	var node corev1.Node

	err := sdk.FromUnstructured(unstructured, &node)
	if err != nil {
		return nil, err
	}

	rawV := node.Status.NodeInfo.KubeletVersion
	rawV = strings.TrimPrefix(rawV, "v")

	return semver.NewVersion(rawV)
}

type kubernetesVersionsInSecret struct {
	MaxUsed          *semver.Version
	DeckhouseDefault *semver.Version
}

func ekvFilterSecret(unstructured *unstructured.Unstructured) (go_hook.FilterResult, error) {
	var secret corev1.Secret

	err := sdk.FromUnstructured(unstructured, &secret)
	if err != nil {
		return nil, err
	}

	versions := kubernetesVersionsInSecret{}

	// Trim before parsing. These are Secret values a human can edit, and a trailing newline used
	// to fail right here — inside a FilterFunc, which takes the whole hook down rather than one
	// check, while admission (parseVersion) trimmed the same byte and carried on.
	rawMaxUsed, ok := secret.Data[maxUsedK8sVersionSecretKey]
	if ok {
		maxUsed, err := semver.NewVersion(strings.TrimSpace(string(rawMaxUsed)))
		if err != nil {
			return nil, err
		}
		versions.MaxUsed = maxUsed
	}

	rawDeckhouseDefault, ok := secret.Data[deckhouseDefaultK8sVersionSecretKey]
	if ok {
		deckhouseDefault, err := semver.NewVersion(strings.TrimSpace(string(rawDeckhouseDefault)))
		if err != nil {
			return nil, err
		}
		versions.DeckhouseDefault = deckhouseDefault
	}

	return versions, nil
}

// ekvFilterClusterKubernetesConfigMap returns spec.maxUsedKubernetesVersion and nothing else.
//
// The narrowness is load-bearing, not tidiness: update-observer stamps lastReconciliationTime on
// the same ConfigMap on every reconcile and requeues once a minute until the cluster is UpToDate.
// A filter that returned the object, its annotations or even the whole spec would therefore
// re-run this hook — and reconverge the module — every minute for the whole duration of an
// upgrade. Only a value that actually changes may enter the snapshot.
//
// Parse failures are swallowed on purpose: a FilterFunc error takes the entire hook down, and a
// hand-mangled data.spec must not stop the effective version from being computed. An unreadable
// value degrades to "no maxUsed from the ConfigMap", which the Secret and values sources cover.
func ekvFilterClusterKubernetesConfigMap(unstructured *unstructured.Unstructured) (go_hook.FilterResult, error) {
	var configMap corev1.ConfigMap
	if err := sdk.FromUnstructured(unstructured, &configMap); err != nil {
		return nil, err
	}

	var spec struct {
		MaxUsedVersion string `json:"maxUsedKubernetesVersion"`
	}
	if err := yaml.Unmarshal([]byte(configMap.Data["spec"]), &spec); err != nil {
		return "", nil
	}

	return strings.TrimSpace(spec.MaxUsedVersion), nil
}

// ekvMaxVersion returns the highest non-nil version, or nil when every argument is nil.
func ekvMaxVersion(versions ...*semver.Version) *semver.Version {
	var maxVersion *semver.Version
	for _, v := range versions {
		if v == nil {
			continue
		}
		if maxVersion == nil || v.GreaterThan(maxVersion) {
			maxVersion = v
		}
	}
	return maxVersion
}

// ekvParseVersion parses an "X.Y" (or "X.Y.Z") string, returning nil for anything unusable.
func ekvParseVersion(raw string) *semver.Version {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return nil
	}
	v, err := semver.NewVersion(raw)
	if err != nil {
		return nil
	}
	return v
}

func handleEffectiveK8sVersion(ctx context.Context, input *go_hook.HookInput, dc dependency.Container) error {
	prevEffectiveVersion := input.Values.Get("controlPlaneManager.internal.effectiveKubernetesVersion").String()

	configVersionRaw := input.Values.Get("global.discovery.targetKubernetesVersion").String()
	if configVersionRaw == "" {
		return fmt.Errorf("kubernetesVersion required (global.discovery.targetKubernetesVersion is empty)")
	}

	// TODO(E2E-KV): temporary stand Info logs — remove before final PR (`rg E2E-KV`).
	input.Logger.Info("E2E-KV effective-k8s",
		"source", "global.discovery.targetKubernetesVersion",
		"target", configVersionRaw,
		"prevEffective", prevEffectiveVersion,
	)

	configVersion, err := semver.NewVersion(configVersionRaw)
	if err != nil {
		return fmt.Errorf("kubernetesVersion is not valid semver: %s", configVersionRaw)
	}

	// process pods snapshot
	minControlPlaneVersion, maxControlPlaneVersion, err := ekvProcessPodsSnapshot(ctx, input, dc)
	if err != nil {
		return err
	}

	// process nodes snapshot
	minNodeVersion, maxNodeVersion, err := ekvProcessNodeSnapshot(ctx, input)
	if err != nil {
		return err
	}

	requirements.SaveValue(minK8sVersionRequirementKey, minNodeVersion.String())

	// process secret snapshot
	versionsInSecret, err := ekvProcessSecretSnapshot(ctx, input)
	if err != nil {
		return err
	}

	// Step 1 of 2: the floor — the highest minor this cluster is known to have converged onto.
	// Derived from effectiveKubernetesVersion below, which leads the running control plane by one
	// minor while a rollout is in flight, so during an upgrade the floor already names the minor
	// being moved to. That is deliberate — the alternative is a floor that forgets an upgrade the
	// moment it is announced — but it means the value is not literally "what the apiservers serve".
	//
	// The three sources are not different quantities being aggregated; they are the same
	// monotonic quantity at three different freshnesses, so "highest" and "first that has a
	// value" coincide and taking the maximum is also the correct fallback order:
	//
	//   values  — what this hook published on its previous run. Covers the window in which the
	//             control-plane-manager DaemonSet has not rolled out yet and the ConfigMap
	//             therefore has not caught up. Lost when the deckhouse Pod restarts.
	//   CM      — the durable record, written by update-observer from the container environment.
	//   Secret  — the pre-move durable record.
	//             TODO(kubernetesVersion-deprecation): T+1 remove — without it, a Deckhouse
	//             upgrade would find both other sources empty and collapse the floor onto the
	//             current effective version, erasing the history of a cluster that legitimately
	//             sits below its historical maximum. The Secret binding stays either way for
	//             deckhouseDefaultKubernetesVersion, so this source is free.
	floor := ekvMaxVersion(
		ekvParseVersion(input.Values.Get(maxUsedK8sVersionValuesKey).String()),
		ekvParseVersion(ekvProcessConfigMapSnapshot(input)),
		versionsInSecret.MaxUsed,
	)
	if floor == nil {
		// No history anywhere: the running control plane is the maximum by definition. This must
		// be an explicit substitution rather than a nil left for the switch below — semver's
		// Equal(nil) returns false instead of panicking, so a nil floor would silently disable
		// the downgrade step without any signal.
		//
		// Seeding from configVersion (as this hook used to) is the one thing that must never
		// happen: configVersion is declared, not observed, so "1.32 cluster, declare 1.36" would
		// record 1.36 as historically used and lock every version below 1.35 out forever.
		floor = maxControlPlaneVersion
		input.Logger.Warn("no maxUsedKubernetesVersion recorded yet, using the current control plane version as the floor",
			"maxControlPlaneVersion", maxControlPlaneVersion.String())
	}

	var effectiveKubernetesVersion *semver.Version

	// getting version logic here
	switch {
	case configVersion.GreaterThan(maxNodeVersion):
		if minNodeVersion.LessThan(minControlPlaneVersion) {
			effectiveKubernetesVersion = minControlPlaneVersion
		} else {
			bumped := minControlPlaneVersion.IncMinor()
			effectiveKubernetesVersion = &bumped
		}

	case configVersion.LessThan(maxNodeVersion):
		// Stepping the control plane down a minor is allowed only while it still stands exactly on
		// the highest version the cluster ever ran: below that the downgrade is already under way
		// and a second step would overshoot.
		if maxNodeVersion.LessThan(maxControlPlaneVersion) && maxControlPlaneVersion.Equal(floor) {
			unbumped := fmt.Sprintf("%d.%d.%d", maxControlPlaneVersion.Major(), maxControlPlaneVersion.Minor()-1, maxControlPlaneVersion.Patch())
			effectiveKubernetesVersion = semver.MustParse(unbumped)
		} else {
			effectiveKubernetesVersion = maxControlPlaneVersion
		}

	default:
		effectiveKubernetesVersion = configVersion
	}

	// result semver should me in form X.Y, not X.Y.Z
	resultStr := fmt.Sprintf("%d.%d", effectiveKubernetesVersion.Major(), effectiveKubernetesVersion.Minor())

	input.Values.Set("controlPlaneManager.internal.effectiveKubernetesVersion", resultStr)
	input.MetricsCollector.Set("d8_kubernetes_version", 1, map[string]string{"k8s_version": resultStr})

	// Step 2 of 2: publish the new floor. It has to be computed after the switch — effective is
	// what the switch produces — which is exactly why the floor above is a separate value: the
	// throttling condition cannot depend on a number derived from its own result.
	//
	// max() with the previous floor is what makes the quantity monotonic, and effective (not
	// configVersion) is what keeps it a record of what ran rather than of what was asked for.
	newMaxUsed := ekvMaxVersion(floor, effectiveKubernetesVersion)
	maxUsedStr := fmt.Sprintf("%d.%d", newMaxUsed.Major(), newMaxUsed.Minor())
	input.Values.Set(maxUsedK8sVersionValuesKey, maxUsedStr)

	// TODO(E2E-KV): temporary stand Info logs — remove before final PR (`rg E2E-KV`).
	input.Logger.Info("E2E-KV effective-k8s result",
		"target", configVersionRaw,
		"effective", resultStr,
		"floor", floor.String(),
		"maxUsed", maxUsedStr,
	)

	var patch map[string]interface{}

	addToPatch := func(key, value string) {
		if patch == nil {
			patch = map[string]interface{}{
				"data": map[string]interface{}{},
			}
		}

		data := patch["data"].(map[string]interface{})
		data[key] = value
	}

	// maxUsedControlPlaneKubernetesVersion is no longer written here: update-observer owns the
	// durable copy in spec.maxUsedKubernetesVersion of the d8-cluster-kubernetes ConfigMap. The
	// Secret key is still *read* above as a migration seed.
	// TODO(kubernetesVersion-deprecation): T+1 remove — drop the key and its reader.

	currentDeckhouseDefault, err := semver.NewVersion(DefaultKubernetesVersion)
	if err != nil {
		return fmt.Errorf("incorrect default kubernetes version %s: %v", DefaultKubernetesVersion, err)
	}

	if versionsInSecret.DeckhouseDefault == nil || currentDeckhouseDefault.GreaterThan(versionsInSecret.DeckhouseDefault) {
		resultStr := fmt.Sprintf("%d.%d", currentDeckhouseDefault.Major(), currentDeckhouseDefault.Minor())
		encoded := base64.StdEncoding.EncodeToString([]byte(resultStr))
		addToPatch(deckhouseDefaultK8sVersionSecretKey, encoded)
	}

	if patch != nil {
		input.PatchCollector.PatchWithMerge(patch, "v1", "Secret", "kube-system", "d8-cluster-configuration")
	}

	if prevEffectiveVersion != "" && prevEffectiveVersion != resultStr {
		_ = os.RemoveAll("~/.kube/http-cache")
		_ = os.RemoveAll("~/.kube/cache")
	}

	return nil
}

// process control plane pods snapshot with annotation, gettings minimum and maximum from control-plane-pods
// returns minControlPlaneVersion, maxControlPlaneVersion and error
func ekvProcessPodsSnapshot(_ context.Context, input *go_hook.HookInput, dc dependency.Container) (*semver.Version, *semver.Version, error) {
	controlPlaneVersions, err := sdkobjectpatch.UnmarshalToStruct[controlPlanePod](input.Snapshots, "control_plane_versions")
	if err != nil {
		return nil, nil, fmt.Errorf("unmarshal control_plane_versions: %w", err)
	}

	var apiserverExists bool
	for _, pod := range controlPlaneVersions {
		if strings.Contains(pod.Name, "kube-apiserver") {
			apiserverExists = true
			break
		}
	}

	if !apiserverExists {
		input.Logger.Warn("deckhouse-managed control plane Pods are not yet deployed, setting control_plane_version to version acquired from kubectl version")

		k8sClient, err := dc.GetK8sClient()
		if err != nil {
			return nil, nil, err
		}

		verInfo, err := k8sClient.Discovery().ServerVersion()
		if err != nil {
			return nil, nil, err
		}

		controlPlaneVersions = []controlPlanePod{{
			Name:       "server_discovery",
			K8sVersion: fmt.Sprintf("%s.%s.0", verInfo.Major, verInfo.Minor),
		}}
	}

	controlPlaneVs := make([]*semver.Version, len(controlPlaneVersions))
	for i, pod := range controlPlaneVersions {
		v, err := semver.NewVersion(pod.K8sVersion)
		if err != nil {
			return nil, nil, fmt.Errorf("control_plane_version: %s has invalid semver: %s", pod.Name, pod.K8sVersion)
		}
		controlPlaneVs[i] = v
	}

	sort.Sort(semver.Collection(controlPlaneVs))

	return controlPlaneVs[0], controlPlaneVs[len(controlPlaneVs)-1], nil
}

// determine minimum and maximum node versions
func ekvProcessNodeSnapshot(_ context.Context, input *go_hook.HookInput) (*semver.Version /*minNodeVersion*/, *semver.Version /*maxNodeVersion*/, error) {
	nodeVersions := make([]*semver.Version, 0, len(input.Snapshots.Get("node_versions")))
	for nodeVersionsSnap, err := range sdkobjectpatch.SnapshotIter[semver.Version](input.Snapshots.Get("node_versions")) {
		if err != nil {
			return nil, nil, fmt.Errorf("unmarshal node_versions: %w", err)
		}

		nodeVersions = append(nodeVersions, &nodeVersionsSnap)
	}

	if len(nodeVersions) == 0 {
		return nil, nil, fmt.Errorf("no Nodes? What are you doing here")
	}

	sort.Sort(semver.Collection(nodeVersions))

	return nodeVersions[0], nodeVersions[len(nodeVersions)-1], nil
}

// ekvProcessConfigMapSnapshot returns spec.maxUsedKubernetesVersion from the cluster ConfigMap,
// or "" when the ConfigMap is absent or the key is unset. Never an error: this is one of three
// interchangeable sources of the same monotonic value, so a missing one is not a failure.
func ekvProcessConfigMapSnapshot(input *go_hook.HookInput) string {
	maxUsedVersions, err := sdkobjectpatch.UnmarshalToStruct[string](input.Snapshots, clusterKubernetesConfigMapSnapshot)
	if err != nil {
		input.Logger.Warn("cannot unmarshal cluster_kubernetes_config_map snapshot", "error", err)
		return ""
	}

	if len(maxUsedVersions) > 0 {
		return maxUsedVersions[0]
	}

	return ""
}

// get semver from secret
func ekvProcessSecretSnapshot(_ context.Context, input *go_hook.HookInput) (kubernetesVersionsInSecret, error) {
	versions, err := sdkobjectpatch.UnmarshalToStruct[kubernetesVersionsInSecret](input.Snapshots, "max_used_control_plane_version")
	if err != nil {
		return kubernetesVersionsInSecret{}, fmt.Errorf("cannot unmarshal max_used_control_plane_version: %w", err)
	}

	if len(versions) > 0 {
		return versions[0], nil
	}

	return kubernetesVersionsInSecret{}, nil
}
