// Code generated by go generate; DO NOT EDIT.
// This file is generated from feature_gates_map.yml

package hooks

type ComponentFeatures struct {
	Deprecated            []string
	Forbidden             []string
	Kubelet               []string
	APIServer             []string
	KubeControllerManager []string
	KubeScheduler         []string
}

type FeatureGateInfo struct {
	Exists bool
	IsDeprecated bool
	IsForbidden bool
}

var FeatureGatesMap = map[string]ComponentFeatures{
	"1.29": {
		Kubelet: []string{
			"CPUManager",
			"MemoryManager",
		},
		APIServer: []string{
			"APIServerIdentity",
			"StorageVersionAPI",
		},
		KubeControllerManager: []string{
			"CronJobsScheduledAnnotation",
		},
		KubeScheduler: []string{
			"SchedulerQueueingHints",
		},
	},
	"1.30": {
		Kubelet: []string{
			"CPUManager",
			"MemoryManager",
		},
		APIServer: []string{
			"APIServerIdentity",
			"StorageVersionAPI",
		},
		KubeControllerManager: []string{
			"CronJobsScheduledAnnotation",
		},
		KubeScheduler: []string{
			"SchedulerQueueingHints",
		},
	},
	"1.31": {
		Kubelet: []string{
			"CPUManager",
			"MemoryManager",
		},
		APIServer: []string{
			"APIServerIdentity",
			"StorageVersionAPI",
		},
		KubeControllerManager: []string{
			"CronJobsScheduledAnnotation",
		},
		KubeScheduler: []string{
			"SchedulerQueueingHints",
		},
	},
	"1.32": {
		Kubelet: []string{
			"CPUManager",
			"MemoryManager",
		},
		APIServer: []string{
			"APIServerIdentity",
			"StorageVersionAPI",
		},
		KubeControllerManager: []string{
			"CronJobsScheduledAnnotation",
		},
		KubeScheduler: []string{
			"SchedulerQueueingHints",
		},
	},
	"1.33": {
		Deprecated: []string{
			"DynamicResourceAllocation",
		},
		Forbidden: []string{
			"SomeProblematicFeature",
		},
		Kubelet: []string{
			"CPUManager",
			"MemoryManager",
		},
		APIServer: []string{
			"APIServerIdentity",
			"StorageVersionAPI",
		},
		KubeControllerManager: []string{
			"CronJobsScheduledAnnotation",
		},
		KubeScheduler: []string{
			"SchedulerQueueingHints",
		},
	},
}

func GetFeatureGateInfo(version, component, featureName string) FeatureGateInfo {
	info := FeatureGateInfo{}
	
	features, ok := FeatureGatesMap[version]
	if !ok {
		return info
	}
	
	for _, name := range features.Deprecated {
		if name == featureName {
			info.IsDeprecated = true
			break
		}
	}
	
	for _, name := range features.Forbidden {
		if name == featureName {
			info.IsForbidden = true
			break
		}
	}
	
	var featureList []string
	switch component {
	case "kubelet":
		featureList = features.Kubelet
	case "apiserver":
		featureList = features.APIServer
	case "kube-controller-manager":
		featureList = features.KubeControllerManager
	case "kube-scheduler":
		featureList = features.KubeScheduler
	default:
		return info
	}
	
	for _, name := range featureList {
		if name == featureName {
			info.Exists = true
			return info
		}
	}
	
	return info
}
